### ISSUE TITLE
Implementation of bucket online/offline

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1004]
This ticket tracks coding of taking bucket online/offline

**Comment by tleyden** [comment]
Related test: https://github.com/couchbase/sync_gateway/issues/1003

This test should pass after this is finished (as long as something puts the bucket back online)

**Comment by ajres** [comment]
Task Breakdown:
- [x] Add an RunState enum to track the state of a database
- [x] Add a RunState member to DatabaseContext struct
- [x] Bring DB online
- [x] Take DB offline
- [x] Support offline operations
- [x] Unit Tests

**Comment by ajres** [comment]
Spawned two subtickets to be scheduled after this ticket is complete

#1012 Put bucket in offline mode for n seconds
#1013 Automatically put bucket in offline mode when lose TAP feed

**Comment by ajres** [comment]
Also see original ticket #722

**Comment by tleyden** [comment]
Does it drop the channel cache when it takes the bucket offline?

**Comment by ajres** [comment]
When re-opening a db the current database context is closed, the config reloaded and a new db context created. The old context and the nested channel cache objects will be GC'd.

**Comment by ajres** [comment]
Now tracking progress via #1012 and #1013
