### ISSUE TITLE
Simplify exp date format in _session response

### ISSUE THREAD

**Issue by pasin** [couchbase/sync_gateway#1009]
This is not a bug but the expiration date format returned by _session is not easy to parse. For example, Java 6 (Android) SimpleDateFormat doesn't support more than 3 digits of milliseconds (as below there are 9 digits of milliseconds). 

Current _session response.

```
{
    "session_id": "9768064a616b70a84c28c7ebab3560a25a00cb93",
    "expires": "2015-07-29T11:28:42.533388357-07:00",
    "cookie_name": "SyncGatewaySession"
}
```

Possible formats:
yyyy-MM-dd'T'HH:mm:ss.SSSZ (limit number of millisecond digits to 3).
yyyy-MM-dd'T'HH:mm:ssZ (no milliseconds).
*\* Time zone(-07:00) could be replaced with just Z if it's UTC.

**Comment by zgramana** [comment]
Note: ensure this is UTC in the new format.

**Comment by ajres** [comment]
Date format is not consistent across SG instances as seen when testing #1049

**Comment by adamcfraser** [comment]
Moved to https://issues.couchbase.com/browse/CBG-647
