### ISSUE TITLE
Automatically put bucket in offline mode when lose TAP feed

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1013]
After completion of #1004

Add the following feature

when we get an error on the TAP feed, automatically put bucket in offline mode

This is the wrap-up ticket for all the following related tickets
- [x] - 622   - not clear behavior with SG when sync CB bucket recreated
- [x] - 748   - Enable taking a bucket offline/online
- [x] - 907   - Document implementation design taking bucket offline/online
- [x] - 908   - Allow an Admin to take a DB Offline
- [x] - 909   - Allow Admin to take an Offline DB Online
- [x] - 910   - Update _resync to use bucket online/offline
- [x] - 911   - Detection of lost TAP feed impacting service availability
- [x] - 912   - Write unit tests for bucket online/offline updates
- [x] - 942   - Handle changes to Couchbase Server cluster topology at runtime
- [x] - 1004 - Implementation of bucket online/offline
- [x] - 1011 - Uptake BucketUpdater for upgrade, stability
- [x] - 1170 - Bucket online/offline knowledge transfer
- [x] - 1176 - Add WebHook notifications for bucket online/offline
- [x] - 1250 - Potential test scenarios for DB online/offline

**Comment by ajres** [comment]
Created a separate ticket  #1085 to track the same issue for DCP feed

**Comment by tleyden** [comment]
@ajres did you mean to link to #1085?

**Comment by ajres** [comment]
Design notes 

go-couchbase will auto reconnect after loosing TAP feed, if the TAP feed comes back then there may be sequences that were never received.

BucketUpdater - can notify that there is a change is a change to topology. We can use that same model or we can use gocb api.

Work with go-couchbase to notify a re-connect then take bucket offline, then put on  a delayed online mode.

When reconnecting we need to connect in a way that does not have gaps, we need to be able to specify the point to where we want to do a backfill to. Explore use of TAP feed capability to take a backfill parameter.

For informal testing we can stop backing CBS instance, for automated testing we can extended existing leaky bucket.

**Comment by ajres** [comment]
@tleyden yes that is the new ticket to track the same issue for DCP

**Comment by adamcfraser** [comment]
@ajres We should discuss whether this is portable to the feed used for bucket shadowing.  A user reported an similar issue related to the bucket shadowing feed being dropped.

**Comment by ajres** [comment]
Official docs for TAP Fee BackFill option:

```
Backfill
BACKFILL ( =0x01=) contains a single 64-bit body that represents the oldest entry (from epoch) you're interested in. Specifying a time in the future (for the server you are connecting to), will cause it to start streaming only current changes.
```

Note: Time needs to align with server TAP feed is being requested from.

**Comment by ajres** [comment]
Based on TAP feed docs here:

http://www.couchbase.com/wiki/display/couchbase/TAP+Protocol

**Comment by tleyden** [comment]
This is wall clock time?

**Comment by ajres** [comment]
UNIX epoch time:

```
number of seconds that have elapsed since 00:00:00 Coordinated Universal Time (UTC), Thursday, 1 January 1970
```

Based on the clock on the server the we are requesting the TAP feed from.

**Comment by ajres** [comment]
This ticket encompasses the following online/offline base tickets #908 and #909, which will be closed out by the downloan PR.

**Comment by ajres** [comment]
[ ] - 908   - 
 [ ] - 909   - 
 [ ] - 910   - 
 [ ] - 911   -
 [ ] - 1176 -

**Comment by ajres** [comment]
TAP feed detection requires downstream changes to go-couchbase

Have [cloned](https://github.com/ajres/go-couchbase) and pushed a candidate change to tap.go for discussion with go-couchbase team as to the best way to detect TAP feed loss.

**Comment by ajres** [comment]
Passing Jenkins build

http://mobile.jenkins.couchbase.com/view/Sync_Gateway_Dev/job/sync-gateway-dev-build/359/
