### ISSUE TITLE
Logging client IP address

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1014]
From irc:

> cgbspender: is it possible for the sync gateway to log the client ip?  without fronting it with a reverse proxy

**Comment by tleyden** [comment]
Another request: user-agent

**Comment by gojihotsauce** [comment]
Being able to log specific HTTP request headers in general would be great as well. For example, X-Forwarded-For.

**Comment by zgramana** [comment]
Closing as a duplicate of issue #939.
