### ISSUE TITLE
Support an array of URLs for server key for startup handling

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1019]
From #942 - we're using go-couchbase's bucketUpdater handling to support the rebalance/dropped connection handling.

However, we still need a way for Sync Gateway to try multiple URLs when initially making the bucket connection.  This can be implemented strictly on the Sync Gateway side.

**Comment by adamcfraser** [comment]
The primary motivation for supporting multiple server URLs was around upgrade support - to ensure Sync Gateway was able to maintain connection to the Couchbase Server cluster, even if nodes in that cluster were going online/offline.

The higher priority aspect of this - handling changes to the Couchbase Server topology while Sync Gateway is running - was addressed in #942, and is included in 1.1.1.  If the Couchbase Server cluster node specified in the Sync Gateway config goes offline while Sync Gateway is running, SG will automatically reconnect via other nodes in the Couchbase Server cluster.

The functionality that is still pending (and tracked in this ticket), is for Sync Gateway to try multiple server URLs on Sync Gateway startup.  In 1.1.1, if the node specified in the Sync Gateway config is unavailable when Sync Gateway is first run, Sync Gateway will not start.  When this is implemented, users will be able to define a list of server URLs in the Sync Gateway config, and SG will try each until it's able to successfully connect.

**Comment by househippo** [comment]
Adam,
Is it possible to have as random shuffle in the array before connecting to prevent too many sync gateway auth to a single CB node. and a timeout and/or number of retries parameter that the user can pass along.

**Comment by JFlath** [comment]
Is this not already available in the underlying SDK? If so, is it just a matter of exposing that?

**Comment by adamcfraser** [comment]
We're currently using go-couchbase's ConnectWithAuth, which just takes a single URL, so it's not quite as easy as that.  It still shouldn't be a significant amount of work, but it's not a one line change.

**Comment by JFlath** [comment]
That sounds like a bug in go-couchbase then?

**Comment by adamcfraser** [comment]
At some point Sync Gateway will move to gocb (which I believe does included built-in support for this scenario).  If we end up targeting this fix before that happens, it's probably an open question whether we build that support into SG or try to push it down to go-couchbase.

**Comment by JFlath** [comment]
Awesome stuff! OOI, is there an open ticket for moving to gocb?

**Comment by abogdanovbg** [comment]
Hello,
Any news about implementing the feature ( Sync Gateway to try multiple server URLs) ?

**Comment by adamcfraser** [comment]
The move to gocb is targeted for 1.4.2 - adding this to the 1.4.2 accordingly.

**Comment by tleyden** [comment]
This might solve https://github.com/couchbase/sync_gateway/issues/2576

**Comment by tleyden** [comment]
Pending [forum question](https://forums.couchbase.com/t/how-to-connect-to-multiple-couchbase-server-urls/13655) for GoCB url format.

**Comment by tleyden** [comment]
Pending issue [MB-25522](https://issues.couchbase.com/browse/MB-25522) to get clarity on supported multiple URL syntax in CBGT

**Comment by tleyden** [comment]
Ran into https://github.com/couchbase/sync_gateway/issues/2768 during development

**Comment by tleyden** [comment]
Just ran into another snag:

In `bucket_gocb.go`:

```
func (bucket CouchbaseBucketGoCB) UUID() (string, error) {

	// Temp workaround -- create a go-couchbase bucket just to get the UUID
	// See https://github.com/couchbase/sync_gateway/issues/2418#issuecomment-289941131
	goCouchbaseBucket, err := GetCouchbaseBucket(bucket.spec, nil)
	if err != nil {
		return "", err
	}
	if goCouchbaseBucket == nil {
		return "", fmt.Errorf("GetCouchbaseBucket() returned nil.  Cannot get bucket UUID")
	}

	uuid, err := goCouchbaseBucket.UUID()
	goCouchbaseBucket.Close()

	return uuid, err

}
```

Basically since gocb doesn't support the `UUID()` call, we create a `go-couchbase` bucket as a workaround.  However, that fails due to:

```
// Creates a Bucket that talks to a real live Couchbase server.
func GetCouchbaseBucket(spec BucketSpec, callback sgbucket.BucketNotifyFn) (bucket *CouchbaseBucket, err error) {
	client, err := couchbase.ConnectWithAuth(spec.Server, spec.Auth)
	if err != nil {
		return
	}
       ..
}
```

which calls:

```
func ConnectWithAuth(baseU string, ah AuthHandler) (c Client, err error) {
	c.BaseURL, err = ParseURL(baseU)
	if err != nil {
		return
	}
```

which gives an error:  **net/http.BadStringError** unsupported protocol scheme: couchbase

**Comment by tleyden** [comment]
re: https://github.com/couchbase/sync_gateway/issues/1019#issuecomment-319777577

Added workaround: https://github.com/couchbase/sync_gateway/commit/dadc8dc0d670fa9ff7f9f50e50533c7428e51da9

**Comment by sridevi-15** [comment]
Verified on 1.5.0-573 and working fine.
