### ISSUE TITLE
Run the service installer during package installation on Linux

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1022]
The service installer script should be run as a `%post` installation macro during RPM package installation, and a `postinst` script for dpkg.

In addition, the Sync Gateway service should also be started.

**Comment by adamcfraser** [comment]
@zgramana Have you checked in with @michaelkwok on this one?

**Comment by zgramana** [comment]
@michaelkwok ping

**Comment by ajres** [comment]
The Sync Gateway service installer is now run in the post installation script for both RMP and dpkg installers.

The sync_gateway user will be created if it does not already exist.

Merged changes to a branch off master, reaised PR #1249.

Closing out this ticket.
