### ISSUE TITLE
Migrate to cross-platform structured logging system

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1023]
Current support for log rotation is limited and does not work on MS Windows as it is not possible to send SIGHUP system signal.

There is limit support for sending SIG_INT signal to a 64bit process, by typing CTRL^C in the terminal where the process was launched.

It might be better to add an enterprise grade logging subsystem to SG to support common logging scenarios across all platforms.

e.g. log rotation, log formatting, multiple log channel, log channels, log levels, log filtering.

**Comment by djpongh** [comment]
This has been fixed on Windows
