### ISSUE TITLE
Sync Gateway not reporting changes

### ISSUE THREAD

**Issue by DaGenix** [couchbase/sync_gateway#1024]
I have two couchbase server instances (both v3.0.1) and two sync gateway instances (both 1.1.0). There are two servers each of which hosts a couchbase instance and a sync gateway instance. Each sync gateway instance is configured to connect to its local couchbase server instance.

One of the sync gateway instances stopped reporting changes on its _changes feed a few days ago, however. The last change that it reports has sequence number 2179. However, the other, working server, reports changes past 2179, all the way up until 2404. If I run `curl 'localhost:4985/default/_changes?since=2178&limit=2'` on the working server, I get:

``` json
{"results":[
{"seq":2179,"id":"ELEMID1","changes":[{"rev":"1-4f515e610893b11a9d42828a30fe633a"}]}
,{"seq":2188,"id":"ELEMID2","changes":[{"rev":"2-4fb1ff31e2412a983e0fe8cb2820a4a5"}]}
],
"last_seq":"2188"}
```

However, on the non-working instance, that same command returns:

``` json
{"results":[
{"seq":2179,"id":"ELEMID1","changes":[{"rev":"1-4f515e610893b11a9d42828a30fe633a"}]}
],
"last_seq":"2179"}
```

In order to try to see if the Couchbase server instance one the non-working server might be at fault, I started up another sync gateway instance on that server. The new sync gateway instance returns all the changes i'd expect it to, however.

I still have the non-working instance running. What additional information can I gather to help debug the problem?

**Comment by adamcfraser** [comment]
It's possible you're hitting https://github.com/couchbase/sync_gateway/issues/722 - that would explain the scenario you're seeing.   If one of your sync gateway's had dropped the server TAP feed, it would results in the behaviour you've described - that node would no longer be notified of new changes from Couchbase Server.

Restarting that Sync Gateway instance would address the problem in this scenario.

You could also check that Sync Gateway's logs - there should be warning/error logging present if the feed connection was dropped.

**Comment by DaGenix** [comment]
The instance that is failing does have

```
2015-08-03T18:04:51.633Z WARNING: Couldn't interpret error type *net.OpError, value read tcp 10.0.211.8:41368: connection reset by peer -- base.ErrorAsHTTPStatus() at error.go:63
```

in its log. The other instance doesn't seem to have any similar error. This log entry looks a bit like the one from #722, but, its a different port. #722 has port 11210, while the error I'm seeing seems to be an ephemeral port.

Does this indicate that I'm hitting the same error as #722 or am I not looking for the right thing?

**Comment by adamcfraser** [comment]
The changes made in 1.3 to support auto-reconnection to a dropped tap feed should address this issue.
