### ISSUE TITLE
413 Too Large

### ISSUE THREAD

**Issue by nl** [couchbase/sync_gateway#1025]
A few of my clients (Mac CBL, master) are stuck in their replication with SG (master) because of a 413 Request Too Large error.

Server logs: https://gist.github.com/nl/326d0a51cb6093ecdfde

Care to make this more verbose for me? What's too large? The revision tree? The attachments? The JSON body?

**Comment by adamcfraser** [comment]
@nl That 413 is getting generated based on the 'Too Large' error being returned from Couchbase Server when Sync Gateway tries to write the doc, so it looks to me like the full doc is exceeding the server limit.  

I believe the single doc limit is 20MB.  That's going to be the combination of the document as sent by the client, as well as the sync metadata added by Sync Gateway (i.e. revision tree).  

Are you expecting the doc in question to be well below that limit?

**Comment by ajres** [comment]
Possibly this is also the cause of #1026, by corrupting the revisionCache causing a subsequent call to _bulk_get to panic.

**Comment by adamcfraser** [comment]
Need to check whether SG is properly routing this error back to the client.

**Comment by adamcfraser** [comment]
@nl If you've got any client logs you can share for this issue, it would be helpful.
