### ISSUE TITLE
Gateway panic on _bulk_docs call

### ISSUE THREAD

**Issue by nl** [couchbase/sync_gateway#1026]
Using both master and 1.1.0, I'm getting the following panic when a CBL Mac client tries to replicate.

https://gist.github.com/nl/e16fa929b20b1d9a6cb7

This is using golang 1.4.1 on Ubuntu.

**Comment by ajres** [comment]
I can't repro for a simple _bulk_get sent using curl:

```
curl -H "Content-Type: application/json" -d '{"docs": [{"id": "somedoc", "rev": "2-cafebabe", "atts_since": [12]},{"id": "otherdoc", "rev": "5-bedbedbe"}]}' -X POST "http://localhost:4985/db/_bulk_get?revs=true&attachments=true"
```

Would you be able to capture the HTTP req/response using something like HTTPScoop and upload to a gist and link on this ticket.

**Comment by ajres** [comment]
We're wondering of the 'too large' error reported in #1025 has corrupted the revision cache or a document in the database.

Can you restart SG and attempt to replicate again, if this issue is isolated to the revision cache replication should succeed.

**Comment by nl** [comment]
Thanks for the pointer. HTTPScoop wouldn't capture anything (I'm guessing it'll only listen on standard Web ports?) but your cache theory was right. The problem went away.

**Comment by tleyden** [comment]
> HTTPScoop wouldn't capture anything (I'm guessing it'll only listen on standard Web ports?) 

In the preferences you can tell it which ports to listen on -- eg, add 4984 and 4985
