### ISSUE TITLE
GET of attachment doesn't have Content-Length header

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#1040]
SG doesn't return a Content-Length header in the response when a client requests an attachment:

```
$  curl -I http://127.0.0.1:4984/attach_test/oneBigAttachment/IMG_0450.MOV
HTTP/1.1 200 OK
Content-Type: video/quicktime
Etag: "sha1-KCvt8/P11KAolXKamQ/kEHTza/c="
Server: Couchbase Sync Gateway/unofficial
Date: Wed, 05 Aug 2015 23:35:28 GMT
```

This means a client can't use HEAD to determine the size of the attachment, and it can't track the fractional progress of the download of a large attachment. (The latter issue is affecting the lazy-attachment-download feature I'm implementing in CBL.)

**Comment by adamcfraser** [comment]
This has been fixed back in https://github.com/couchbase/sync_gateway/pull/1052
