### ISSUE TITLE
Allow resuming attachment downloads (support Range: request headers)

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#1046]
SG's HTTP handlers should honor Range: headers on requests, at least when requesting an attachment (handler.handleGetAttachment(), in rest/doc_api.go.) This would allow a client to download a byte range of the attachment body — it's needed to be able to resume an interrupted download. Since attachments can be huge, interrupted downloads are going to happen and it'd be nice if the client didn't have to start over each time.

(Byte ranges are also sometimes used in media playback; I _think_ this is how video players support being able to scrub to a random spot in a video.)

Here's the [spec for the Range: header](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35). It supports multiple ranges but that's not necessary for our purposes. You may want to look at my implementation in CBL/iOS — see the method `-processRequestRanges` in CBL_Router.m.

**Comment by jchris** [comment]
This can enable all sorts of secondary use cases like bittorrent and media servers.
