### ISSUE TITLE
implement cases to test SG with diff params/configs: ServerConfig, DbConfig, ShadowConfig

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#1048]
full list of avaliable params https://github.com/couchbase/sync_gateway/blob/55b487be3db991b98711961df86a44deb257a83c/src/github.com/couchbase/sync_gateway/rest/config.go#L48-L145

**Comment by adamcfraser** [comment]
Have good generic coverage in functional test suite now - if there are gaps, can open new specific tickets for those in mobile testkit repo.
