### ISSUE TITLE
Error from 'channels' view: No rows can match your key range, reverse your start_key and end_key or set descending=true

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1050]
Observed error in Sync Gateway logs:

```
Cache:   Querying 'channels' view for "*" (start=#46, end=#45, limit=0)
Error from 'channels' view: error executing view req at http://...: 400 Bad Request - {"error":"query_parse_error","reason":"No rows can match your key range, reverse your start_key and end_key or set descending=true"}
WARNING: Skipped Sequence 45 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the * channel view - will be abandoned. -- db.func·005() at change_cache.go:195
```

It's unclear how things got into this state or how to reproduce. 

Version: Sync Gw 1.1.0

**Comment by tleyden** [comment]
It appears that the view query is being kicked off from here:

https://github.com/couchbase/sync_gateway/blob/1.1.0/src/github.com/couchbase/sync_gateway/db/change_cache.go#L178-L205

**Comment by adamcfraser** [comment]
That's the code that should be attempting to retrieve skipped sequences that don't show up after an extended period of time using the view, prior to abandoning that sequence.  It looks like it's not generating the key range correctly.
