### ISSUE TITLE
Couchbase Server indexing stuck on SG views

### ISSUE THREAD

**Issue by nl** [couchbase/sync_gateway#1051]
On every large database (several million docs or more) I have, Couchbase Server (3.0-3.1) gets stuck indexing the _design/sync_gateway ddoc daily. The only fix I have found is stopping SG, deleting the views, starting it up again and letting it reinstall them. I have tried all SG releases from 1.0.4 to 1.1, and even the current tip of master.

In the attached screenshot, indexing is stuck at 38%, and has been sitting there for several days. Not sure if this should be a SG or CBS ticket, but this problem only seems to affect SG views.

![screen shot 2015-08-08 at 8 28 07 am](https://cloud.githubusercontent.com/assets/35510/9149377/6cfb05a8-3da7-11e5-9aff-7664409fb4cb.png)

**Comment by ajres** [comment]
We have an issue on our demo cluster where documents over a certain size will cause the map reduce process to fail.

Do you see any entries in your Sync Gateway ending with the "too large body (1544161 bytes)" message, e.g.:

[mapreduce_errors:error,2015-02-24T11:40:21.513,ns_1@pear-s23004.demo.couchbase.local:<0.28152.2857>:couch_set_view_updater:load_doc:483]Bucket `todolite`, main group `_design/sync_gateway`, skipping document with ID `_sync:att:sha1-j1Zh/B/VlzACaa3P3MaPgTv2kfg=`: too large body (1544161 bytes)

The full ticket is [here](https://github.com/couchbase/sync_gateway/issues/677)

Andy

**Comment by zgramana** [comment]
@nl can you give us any information on doc size, per @ajres 's comment above, or any other information on the docs that seem to cause hangs?

**Comment by adamcfraser** [comment]
Closing this given that we don't have additional feedback on the question above - please re-open if you've got additional info.
