### ISSUE TITLE
Add request user as input for Webhooks

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1053]
I want to use webhooks to log the modification of docs, such as [who] [when] modify [which docs]. but for filter function, the input of webhooks is only doc.
To logging the  modification of docs is very important, we can audit/logging/even trigger some thing base on log.

**Comment by atom992** [comment]
any update?

**Comment by adamcfraser** [comment]
Closing based on age.  Probably a reasonable enhancement, but would need a support case to prioritize and track in JIRA.
