### ISSUE TITLE
Multi-node testing issues - distributed index

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1056]
Tracking issue for bugs found during multi-node dev testing 
- [x] Changes feed is missing entries.  Entries appear after a restart.  Missing entries look like they are written to the same block as an earlier, non-missing entry.
- [x] Index entries being written to index with legacy sequence, not vb sequence

**Comment by tleyden** [comment]
Doc Id that didn't show up (until restart)

12389b182ababd12fff662848edeb908 (vbucket 36)

Doc Id that did show up:

1c856b5724dcf4273c3993619900ce7f (vbucket 35)

**Comment by adamcfraser** [comment]
Index entry issue is being tracked separately as part of #1065
