### ISSUE TITLE
Confirm and resolve any issues in AWS-perfcluster

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1071]
@andreibaranouski last time we tried to test the `feature/distributed_index` branch on AWS, there were mysterious couchbase server errors (buckets going offline, memcached errors in logs)

Can you try to spinup an AWS perf cluster and run the gatling tests against the `feature/distributed_index` branch and report the results?

If you run into any issues, let's look at them together.

**Comment by andreibaranouski** [comment]
@zgramana The launch used a default config https://github.com/couchbaselabs/perfcluster-aws/blob/master/cloudformation_template.py ?

**Comment by andreibaranouski** [comment]
run  gatling tests against feature/distributed_index. still not found any abnormal behavior on the server.

**Comment by andreibaranouski** [comment]
3.1.0 builds are not available now in http://latestbuilds.hq.couchbase.com/ https://issues.couchbase.com/browse/CBIT-2932

**Comment by andreibaranouski** [comment]
some fixes in perfcluster-aws
https://github.com/couchbaselabs/perfcluster-aws/commit/dee82ad09424b7474826318ad1ec83c4442ed62b
https://github.com/couchbaselabs/perfcluster-aws/commit/e0cfab1ea47509c8cf798d28ee83db15240a904c
https://github.com/couchbaselabs/perfcluster-aws/commit/e0810c96ad8bd00ff89cde3ae3929cb38eb26222

**Comment by tleyden** [comment]
Thanks @andreibaranouski!  I think you can go ahead and close this now.

**Comment by tleyden** [comment]
@andreibaranouski actually, can you collect the output from gatling and post it somewhere and link to the ticket?
