### ISSUE TITLE
Bucket Shadowing incompatible with low rev limit

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1076]
As described in https://github.com/couchbase/sync_gateway/issues/959, there are design level issues when using Bucket Shadowing in conjunction with low rev limits.

**Comment by JeffThomasWriter** [comment]
This is in the config parameter doc:
                   <row>
                      <entry>
                         <code>revsLimit</code>
                      </entry>
                      <entry><code>integer</code></entry>
                      <entry>Maximum depth to which a document's revision tree can grow
                         <note>If you use bucket shadowing, setting <code>revsLimit</code> to a value that is too small relative to the frequency of document revisions can have negative consequences. Bucket shadowing needs the revision history to be maintained until pending revisions are reconciled.</note>
                      </entry>

Let me know if more is needed. Thanks. Jeff

**Comment by adamcfraser** [comment]
Shadowing has been removed from the product, not an issue with shared bucket access.
