### ISSUE TITLE
Distributed index: simplify CBGT usage with respect to UUID vs bindHttp

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1077]
Since https://github.com/couchbaselabs/cbgt/issues/25 is closed, the Sync Gw code can be simplified

**Comment by tleyden** [comment]
@steveyen can you you please review this code to see if we're using cbgt correctly with respect to the bindHttp param?

https://github.com/couchbase/sync_gateway/blob/feature/distributed_index/src/github.com/couchbase/sync_gateway/rest/server_context.go#L376-L466

**Comment by steveyen** [comment]
At a quick glance, I think this looks ok.  If you're running into some troubles where you suspect something's going weird here, please let me know... in case my eyes that didn't see any troubles were lying to me.

**Comment by tleyden** [comment]
@steveyen cool, thanks.  Nope, not running into any troubles, but just wanted to check that no potential big issues were lurking.

**Comment by steveyen** [comment]
Actually, one more thought: if you're planning on using cbgt's REST API features, I think you can still use those, even though bindHttp is a UUID.

But... there are higher level cmd-line tools and optional libraries that have been built up over time related to the world of cbgt, and those higher level tools/libraries do assume that the bindHttp value actually is a URL.  You aren't using those higher level tools/libraries today, of course, in SGW, but if _one day_ you want to reuse that stuff, then you'll probably need to revisit the uuid==bindHttp thing.
