### ISSUE TITLE
Run Sync Gateway functional test against feature/distributed_index branch

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1079]
The feature/distributed_index branch is under heavy development and it would be very useful feedback to run the Sync Gateway functional tests against it to verify correct behavior.

**Comment by andreibaranouski** [comment]
all tests passed against  feature/distributed_index branch
total ............................................. 1191/1191

**Comment by adamcfraser** [comment]
One note - while running the tests would still be valuable as a regression test, unless the config was changed to enable the distributed index the new functionality isn't being exercised.

**Comment by tleyden** [comment]
Oh, yeah.  Sorry that was my bad!  @andreibaranouski I'm going to re-open this and give you an example config.

**Comment by tleyden** [comment]
Here's an example config:

https://gist.github.com/tleyden/7d2698af1c17c255ead4

Noteworthy:
- [Tell it to use "sharded dcp"](https://gist.github.com/tleyden/7d2698af1c17c255ead4#file-gistfile1-txt-L10)
- [Params related to sharded dcp](https://gist.github.com/tleyden/7d2698af1c17c255ead4#file-gistfile1-txt-L11-L14)
- [Tell it to use a distributed channel index](https://gist.github.com/tleyden/7d2698af1c17c255ead4#file-gistfile1-txt-L27-L31) 

Note that you will need to create the bucket specified in the [channel index](https://gist.github.com/tleyden/7d2698af1c17c255ead4#file-gistfile1-txt-L27-L31)

Also, if it's not already there, please add instructions to the aws-perfcluster README on how to use a  sync gateway config.  And if it's difficult to do so, go ahead and propose or make changes to fix it.

**Comment by tleyden** [comment]
@andreibaranouski any update on this?

**Comment by adamcfraser** [comment]
This is now completed - functional tests are being run against distributed index functionality.
