### ISSUE TITLE
MaxFileDescriptors setting shouldn't reduce the system defined values

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1083]
As discussed on #1080, when Sync Gateway attempts to set MaxFileDescriptors, it shouldn't ever reduce the number of file descriptors - only increase.

**Comment by zgramana** [comment]
Additional reading: http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by tleyden** [comment]
@zgramana I take it this needs to work on Linux, OSX, and Windows?
