### ISSUE TITLE
Automatically put bucket in offline mode when lose DCP feed

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1085]
This ticket parallels 1013 for DCP as apposed to TAP

**Comment by tleyden** [comment]
Notes from @ajres 

Entry point to take DB offline:

https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/database.go#L278

Here is the example from admin API for wrapping takeDbOffline and raising a WebHook event:

https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/rest/admin_api.go#L106

**Comment by tleyden** [comment]
Seeing this DCP error, still investigating: https://gist.github.com/tleyden/ffba4b20ce66ce203d85.

I'm running couchbase server 3.0.3

**Comment by tleyden** [comment]
@sethrosetter as a heads up, keep your eye out for this error when running with feedtype=DCP: https://gist.github.com/tleyden/ffba4b20ce66ce203d85#file-gistfile1-txt-L58

**Comment by tleyden** [comment]
Something seems to be broken with my local OSX setup .. I tried to switch to Couchbase 4.1.0 and I'm getting the same error.  (@adamcfraser isn't seeing the error on his setup with Couchbase Server 4.1.0)

I switched to running both Couchbase Server and Sync Gateway under Ubuntu + Docker and it's working with both Couchbase Server 3.0.3 and 4.1.0, so I'm using that for testing.

How I'm testing:
- Startup sync gateway with [this config](https://gist.github.com/tleyden/e319105ea9a4f2629dcc)
- Issue curl request to `localhost:4985/db2/` and verify that `"state":"Online"` in the returned JSON
- While running, delete the bucket from Couchbase Server Admin UI
- Issue curl request to `localhost:4985/db2/` and verify that `"state":"Offline"` in the returned JSON

[Sync Gateway Logs](https://gist.github.com/tleyden/506d44f9b5c125e76f74) during manual test run

**Comment by tleyden** [comment]
I'm trying to run the functional tests but getting these errors:

https://gist.github.com/tleyden/7d21430ad211243b54d6
- Sync Gw branch: feature/issue_1085_dboffline_dcp
- Sync-gateway-testcluster branch: feature/issue_1085_dboffline_dcp
- Provisioning-config: https://gist.github.com/tleyden/61c988965364424c4656

@sethrosetter any ideas?

**Comment by tleyden** [comment]
Functional test failed: https://gist.github.com/tleyden/8feb655f5d9cc0367073  (with TAP instead of DCP, the same functional test passed)

**Comment by tleyden** [comment]
It looks like the functional test is failing due to the same issue I saw on my local OSX setup (https://github.com/couchbase/sync_gateway/issues/1085#issuecomment-168861297).  Basically as soon as Sync Gateway starts, it gets DCP errors:

https://gist.github.com/tleyden/36905b1de276e8eddec9

when the test tries to validate that the bucket is initially online, it fails since it took the bucket offline (due to DCP errors mentioned above).

NOTE: couchbase server 4.1.0

**Comment by adamcfraser** [comment]
Moving to 1.3, based on the other DCP issues identified (#1406).

**Comment by tleyden** [comment]
Looks like this should have been closed with https://github.com/couchbase/sync_gateway/issues/1411
