### ISSUE TITLE
CBGT uptake followup issues

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1089]
- [x] If the config specifies a channel index, but doesn't specify feed type, it should just default the feed type to DCP shard (instead of throwing an error).  If feed type omitted, and channel_index is specified, default to DCPSHARD.
- [x] FeedParams for CBGT should be defined with the Sync Gateway database definition, instead of as part of BucketSpec
- [x] Is it useful to expose num_replicas as a SG config parameter?
- [x] Can DataDir be defaulted to the location SG is running?
- [x] On SG startup when _sync:cfg hasn't yet been defined, a lot of apparently transient docs show up on the feed with docIDs like 'k21049', 'k021', 'k22025' etc.  Don't see corresponding docs/traffic in the bucket, so they appear to be artificially added to the feed by cbgt.  They get rejected (with error) because they don't have sync metadata, but need to understand whether this would cause problems for cbgt if users created docs with these IDs (in the case where the source bucket is used for cfg storage).
- [x] Hide the cbgt janitor/planner logging behind a log key

**Comment by tleyden** [comment]
> Hide the cbgt janitor/planner logging behind a log key

Filed https://github.com/couchbaselabs/cbgt/issues/38

**Comment by tleyden** [comment]
> Can DataDir be defaulted to the location SG is running?

Moved to https://github.com/couchbase/sync_gateway/issues/1128

**Comment by tleyden** [comment]
> If the config specifies a channel index, but doesn't specify feed type, it should just default the feed type to DCP shard (instead of throwing an error). 

Fixed in commit 7a12b0615c44fc9ec03133595cbd5b5af609338d

**Comment by tleyden** [comment]
> Is it useful to expose num_replicas as a SG config parameter?

Fixed in db7caf638e663724c9c47224b5a0205488b473d9
