### ISSUE TITLE
Add convenience API to delete attachments

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1092]
when I want to delete a by REST API like this:

DELETE /sgdb/Doc2/2.txt?rev=4-113d35b5deb14670ad4aa011a2f966af HTTP/1.1
Host: 127.0.0.1:4984

but got 405 error:

{
  "error": "Method Not Allowed",
  "reason": ""
}

I followed the document of this method from:
http://developer.couchbase.com/mobile/develop/references/couchbase-lite/rest-api/document/delete---db---doc---attachment-/index.html

**Comment by ajres** [comment]
@atom992

The document link you posted is for the Couchbase Lite REST API, the Sync Gateway REST API does not currently support the DELETE operation for an attachment.

**Comment by ajres** [comment]
@atom992

Are you able to share your use case for needing this REST operation on Sync Gateway.

**Comment by atom992** [comment]
The REST API of Sync Gateway is on public network. any operation should be control.

**Comment by atom992** [comment]
@ajres     I found a easy way to delete attachment from SG by delete _attachment section of the attachment I want to deleted. I don't know if it is ok.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
