### ISSUE TITLE
Panic in (*DatabaseContext).getChangesInChannelFromView

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#1093]
I just noticed that my local Sync Gateway instance that I use for Couchbase Lite unit tests had crashed. [The panic dump is here](https://gist.github.com/snej/fcf840f219b0e4409864), with some of the last log output at the top.

The panicked thread looks like:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xc0 pc=0x220e03]

goroutine 13898 [running]:
github.com/couchbase/sync_gateway/db.(*DatabaseContext).getChangesInChannelFromView(0xc210fba540, 0x6e73f0, 0x1, 0x38d, 0x0, 0x0, 0x38d, 0x0, 0x0, 0x0, ...)
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/db/changes_view.go:36 +0x3f3
github.com/couchbase/sync_gateway/db.func·005(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:190 +0x226
github.com/couchbase/sync_gateway/db.(*changeCache).CleanSkippedSequenceQueue(0xc210fba610, 0x2501)
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:205 +0x63
github.com/couchbase/sync_gateway/db.func·004()
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:119 +0x34
created by github.com/couchbase/sync_gateway/db.(*changeCache).Init
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:122 +0x3c3
```

Also worth noting is that there are 182 goroutines with the following stack, which leads me to think that they're not getting cleaned up properly:

```
goroutine 13897 [sleep]:
github.com/couchbase/sync_gateway/db.func·003()
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:113 +0x66
created by github.com/couchbase/sync_gateway/db.(*changeCache).Init
    /Couchbase/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:115 +0x371
```

**Comment by tleyden** [comment]
@snej I take it this is the master branch of Sync Gateway?

Also, which branch of the cblite unit tests are you running?

**Comment by snej** [comment]
This is actually my `blip_sync` branch, commit f310746c6471311b40db2fc61b9ecf7b8c75f2b5. I rebased it onto master last week, and there aren't any changes in the branch related to the code that crashed.

Couchbase Lite is on the master branch. But I don't think this will reproduce easily; I run unit tests all the time and it's been ages since I saw a Gateway crash.

**Comment by adamcfraser** [comment]
There's a relatively recent change in the code in this area - commit 4cb66cccba392abdce4cd78965de1748499e9ce2 - but it doesn't look like the same issue.

It looks like it might be panicking due to a nil bucket reference.  Between that, and the number of goroutines showing up for the CleanUp processes (that should only be one per change_cache), it seems like there might be a situation where change_caches aren't being torn down properly.  

What's the testing scenario here - are new database instances getting added/removed on the fly to this SG, or should it just be a single DB/bucket for the lifetime of the SG?
