### ISSUE TITLE
attachment modify ACL failed

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1097]
I want to user can only Add attachment or Delete attachment, Do not allow to modify attachment. So I compare the doc._attachments[{attachment_id}].digest and oldDoc._attachments[{attachment_id}].digest  in sync function, if the digest is not equal, I will reject the modification.
    when I modify the attachment(In sync function will reject the modification), the doc._rev is not changed. and the doc._attachments[{attachment_id}].revpos is not changed,but the doc._attachments[{attachment_id}].digest is changed.
    Here is a sample Doc as follows:
before modification:

{
  "_attachments": {
    "1.txt": {
      "content_type": "text/plain;charset=UTF-8",
      "digest": "sha1-pX3mLpt07V50sPHdq8gM5YySiMw=",
      "length": 34,
      "revpos": 3,
      "stub": true
    }
  },
  "_id": "Doc1",
  "_rev": "2-12603e7b711007be05fea5c0189a0298",
  "body": "test",
}

after modification:
{
  "_attachments": {
    "1.txt": {
      "content_type": "text/plain;charset=UTF-8",
      "digest": "sha1-dTNKm6Ucfzt87aFkTO3ZKFjNlU0=",
      "length": 24,
      "revpos": 3,
      "stub": true
    }
  },
  "_id": "Doc1",
  "_rev": "2-12603e7b711007be05fea5c0189a0298",
  "body": "test",
}

**Comment by ajres** [comment]
@atom992

I tried to recreate this in a [unit test](https://github.com/couchbase/sync_gateway/commit/156b1af7c712253f41a0c0542e4d0229d04fb10c), but the behaviour is as expected, the attachment update is rejected by the sync function and the attachment metadata is unchanged.

Which version of Sync Gateway are you running?

Are you updating your attachments via direct REST API calls or via replication?

**Comment by atom992** [comment]
I am using sync gateway 1.1.0-28
and I updating  attachments via direct REST API calls.

**Comment by atom992** [comment]
any update?

**Comment by adamcfraser** [comment]
@atom992 Can you provide the exact REST calls you're making when you see this issue?

**Comment by atom992** [comment]
My REST calls looks like this:

```
curl -X PUT -H "Cache-Control: no-cache" -d 'show box?' 'http://testuser:password@127.0.0.1:4984/sgdb/Doc1/1.txt?rev=4-113d35b5deb14670ad4aa011a2f966af'
```

**Comment by adamcfraser** [comment]
@atom992 Have you compared your sync function to the one in the unit test Andy added related to this issue?

**Comment by adamcfraser** [comment]
@atom992 Let us know if this is still an issue - otherwise the issue will be closed.
