### ISSUE TITLE
Design docs with more than one view definition don't work as expected?

### ISSUE THREAD

**Issue by PaulCapestany** [couchbase/sync_gateway#1109]
If one tries to add multiple view definitions within one design document, it seems that they are all properly wrapped by the [wrapViews](https://github.com/couchbase/sync_gateway/blob/3fa7e5e045624956c3a21bf2887dbfa442d536bf/src/github.com/couchbase/sync_gateway/db/design_doc.go#L64) function, yet SG is only actually returning proper results for 1 of the views.

To reproduce, run `curl -vX PUT localhost:4985/test/_design/myviews -H "Content-Type: application/json" -d @testview.json` with the following design doc:

``` json
{
  "views": {
    "by_fname": {
      "map": "function (doc, meta) { emit(doc.fname, null); }"
    },
    "by_lname": {
      "map": "function (doc, meta) { emit(doc.lname, null); }"
    },
    "by_age": {
      "map": "function (doc, meta) { emit(doc.age, null); }"
    }
  }
}
```

I'd expect all three of the following to work:
- [http://localhost:4985/test/_design/myviews/_view/by_fname?stale=false](http://localhost:4985/test/_design/myviews/_view/by_fname?stale=false)
- [http://localhost:4985/test/_design/myviews/_view/by_lname?stale=false](http://localhost:4985/test/_design/myviews/_view/by_lname?stale=false)
- [http://localhost:4985/test/_design/myviews/_view/by_age?stale=false](http://localhost:4985/test/_design/myviews/_view/by_age?stale=false)

...but only one of them does.

I'm running self-built sync_gateway binary (latest commit from master branch). Unless I'm missing something, this seems to be a bug?

**Comment by adamcfraser** [comment]
Will investigate - presumably a workaround for now would be one view per design doc.

**Comment by PaulCapestany** [comment]
@adamcfraser cool. Let me know if for some reason you can't reproduce it and/or need any more info.

**Comment by ajres** [comment]
The issue is in the map wrapper, the doc._sync data is being deleted by the first view called, and subsequent views receive the doc without it's doc._sync property and are excluded from processing in the wrapper.

**Comment by PaulCapestany** [comment]
@ajres thanks for the fix, can confirm the example above works now 👍
