### ISSUE TITLE
Validate sync_gateway doesn't not crash against legal and/or invalid json

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1121]
Motivation: #976 . Empty key in document crashes SG. 
Test sync gateway:
- Creating docs with empty keys
- Create docs with empty keys/values
- Update docs with empty keys
- validate sync gateway works with all the legal json
- validate sync gateway gracefully handles illegal json
  Have an automated test suite which runs through and validates
- legal and illegal json

**Comment by sethrosetter** [comment]
Ticket moved here - https://github.com/couchbaselabs/mobile-testkit/issues/691
