### ISSUE TITLE
What's the use of this ID "_sync:rev:Doc1:34:2-b4693938442076fb87e1afd6760e6aab"

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1122]
I want to know what meaning of the structure in ID "_sync:rev:Doc1:34:2-b4693938442076fb87e1afd6760e6aab"?

I am using sync gateway 1.1.0 with couchbase 3.0 + elasticsearch-transport-couchbase-2.1.1 + elasticsearch-1.5.2, and when I start replication,make some doc changed by sync gateway REST API, I got the following errors:
https://github.com/couchbaselabs/elasticsearch-transport-couchbase/issues/96

[2015-09-07 11:02:41,068][ERROR][transport.couchbase.capi ] [Dazzler] error indexing document id: _sync:rev:Doc1:34:3-bc3826e5e553ded82bd679f8c7027202 exception: InvalidTypeNameException[mapping type name [_sync] can't start with '_']
[2015-09-07 11:02:41,214][WARN ][org.eclipse.jetty.servlet.ServletHandler] /dev4test%2f40/_bulk_docs
java.lang.RuntimeException: InvalidTypeNameException[mapping type name [_sync] can't start with '_']

I have already exclude _sync mapping.

**Comment by ajres** [comment]
All Sync Gateway documents starting with _sync, contain internal SG metadata. The format of these docs is internal to SG and may change between releases.

I would recommend that you continue to exclude them from Elastic search indexing.

Andy

**Comment by adamcfraser** [comment]
@atom992 Please advise if this is actually an issue (i.e. you're not able to exclude these from search indexing).

**Comment by atom992** [comment]
It is a bug,and I try to fixed it:
https://github.com/couchbaselabs/elasticsearch-transport-couchbase/pull/97

**Comment by adamcfraser** [comment]
Closing the SG issue, as it doesn't look like an issue on this side.
