### ISSUE TITLE
Cannot retrieve documents when user has assigned channels to the documents

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1125]
Hi , @adamcfraser  
I am using Sync Gateway 1.1.0-28 + couchbase 3.0.2-1603 Enterprise Edition (build-1603).

The user [user1] has following channels (query from couchbase web console by ID=
_sync:user:user1):

{
  "name": "user1",
  "all_channels": {
    "!": 1,
    "c-CMP-1A0246C5-3CCB-4C84-A5A6-34D4D558D02B": 710,
    "c-CMP-796A3D8C-E339-4A88-A1AE-D13DF7D5060A": 718,
    "g-USR-user1": 710,
    "g-USR-user11": 713,
    "g-USR-user12": 714,
    "g-USR-user13": 717,
    "g-USR-user19": 715,
    "o-CMP-1A0246C5-3CCB-4C84-A5A6-34D4D558D02B": 710,
    "o-CMP-796A3D8C-E339-4A88-A1AE-D13DF7D5060A": 718,
    "u-USR-user1": 493
  },
  "sequence": 393,
  "passwordhash_bcrypt": "JDJhJDEwJEdHMUQ4aENGVG5GLzB3amd4akVMV09RdHFUWHVnaVpwNVd3REUuY3N6ejQ4TTQ1ckhlNU1x",
  "rolesSince": {}
}

the doc [GST:user11] have the following channels(query from couchbase by couchbase web console):

{
  "_sync": {
    "rev": "2-4b10bb8d841e3048ef6f6f4f2f2e7978",
    "sequence": 697,
    "recent_sequences": [
      294,
      697
    ],
    "history": {
      "revs": [
        "1-1529296be88ecf871d03455ea9d8493d",
        "2-4b10bb8d841e3048ef6f6f4f2f2e7978"
      ],
      "parents": [
        -1,
        0
      ],
      "bodies": [
        "",
        ""
      ],
      "channels": [
        [
          "g-USR-user11"
        ],
        [
          "c-CMP-7D8E4F27-371C-41C5-ACD6-4EB6C466E5B2"
        ]
      ]
    },
    "channels": {
      "c-CMP-7D8E4F27-371C-41C5-ACD6-4EB6C466E5B2": null,
      "g-USR-user11": {
        "seq": 697,
        "rev": "2-4b10bb8d841e3048ef6f6f4f2f2e7978"
      }
    },
    "access": {
      "user11": {
        "c-CMP-7D8E4F27-371C-41C5-ACD6-4EB6C466E5B2": 697
      }
    },
    "time_saved": "2015-09-09T20:53:24.374638538+08:00"
  },
  "cmp_list": [
    "CMP:7D8E4F27-371C-41C5-ACD6-4EB6C466E5B2"
  ],
  "name": "user11",
  "status": "using",
  "type": "GST"
}

I notice that user1 have channel [g-USR-user11] , the doc [GST:user11] has assigned channel [g-USR-user11] , but when I used user1 to get doc [GST:user11]  I got 403 forbidden.

but for  the same doc  [GST:user19] , I can used user1 to get doc  [GST:user19]. doc  [GST:user19] looks like this:

{
  "_sync": {
    "rev": "2-0042d539331a8b93bdb414953bbd08f0",
    "sequence": 716,
    "recent_sequences": [
      301,
      716
    ],
    "history": {
      "revs": [
        "1-91954b6acb2866f04c4b27cd8d19c7bb",
        "2-0042d539331a8b93bdb414953bbd08f0"
      ],
      "parents": [
        -1,
        0
      ],
      "bodies": [
        "",
        ""
      ],
      "channels": [
        [
          "g-USR-user19"
        ],
        [
          "c-CMP-1A0246C5-3CCB-4C84-A5A6-34D4D558D02B"
        ]
      ]
    },
    "channels": {
      "c-CMP-1A0246C5-3CCB-4C84-A5A6-34D4D558D02B": null,
      "g-USR-user19": {
        "seq": 716,
        "rev": "2-0042d539331a8b93bdb414953bbd08f0"
      }
    },
    "access": {
      "user19": {
        "c-CMP-1A0246C5-3CCB-4C84-A5A6-34D4D558D02B": 716
      }
    },
    "time_saved": "2015-09-09T23:36:14.943113101+08:00"
  },
  "cmp_list": [
    "CMP:1A0246C5-3CCB-4C84-A5A6-34D4D558D02B"
  ],
  "name": "user19",
  "status": "using",
  "type": "GST"
}

**Comment by adamcfraser** [comment]
That document is no longer in channel g-USR-user11 - it was removed at rev 2-4b10bb8d841e3048ef6f6f4f2f2e7978, seq 697.  When the channels map has a non-null value, the value indicates when the doc was removed from the channel - this is used to propagate removals to clients.

The user has getting access to the second doc via channel c-CMP-1A0246C5-3CCB-4C84-A5A6-34D4D558D02B.  Again, the second doc is no longer in g-USR-user19 - it was removed at rev 2/seq 716.

**Comment by atom992** [comment]
So 
https://github.com/couchbase/sync_gateway/issues/1126
tis issue is cause by the channels map has a non-null value.
