### ISSUE TITLE
Default CBGT DataDir location so users don't need to specify

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1128]
Currently, the CBGT DataDir (where CBGT stores some metadata) needs to be specified in the config file.  

If we could find a sensible default, then users wouldn't have to think about this.  This would need to work in the context of systemd services, and on Windows, etc.

**Comment by adamcfraser** [comment]
cbgt's DataDir has been made optional, and isn't currently used by SG.
