### ISSUE TITLE
[Distributed index] CBGT config validation

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1137]
Channel Index defined AND you're a writer  (previously, was ignoring the writer role)

**Comment by tleyden** [comment]
@adamcfraser While I thought I understood this during the meeting, when I looked at the actual validation code, I realized I didn't understand it.  Here's the validation code:

```

func (dbConfig DbConfig) validate() error {

    // if there is a ChannelIndex being used, then the only valid feed type is DCPSHARD
    if dbConfig.ChannelIndex != nil {
        if strings.ToLower(dbConfig.FeedType) != strings.ToLower(base.DcpShardFeedType) {
            msg := "ChannelIndex declared in config, but the FeedType is %v " +
                "rather than expected value of DCPSHARD"
            return fmt.Errorf(msg, dbConfig.FeedType)
        }
    }

    // if the feed type is DCPSHARD, then there must be a ChannelIndex
    if strings.ToLower(dbConfig.FeedType) == strings.ToLower(base.DcpShardFeedType) {
        if dbConfig.ChannelIndex == nil {
            msg := "FeedType is DCPSHARD, but no ChannelIndex declared in config"
            return fmt.Errorf(msg)
        }
    }

    return nil

}
```

**Comment by adamcfraser** [comment]
There are two possible valid configurations when using the channel index:
1. Index writer
   - dbConfig.ChannelIndex != nil
   - dbConfig.ChannelIndex.CacheWriter = true
   - feed type must be DCPSHARD
2. Index reader
   - dbConfig.ChannelIndex != nil
   - dbConfig.ChannelIndex.CacheWriter = false
   - feed type not required/used, and node shouldn't be registered with CBGT

**Comment by adamcfraser** [comment]
Handling needs to be updated to sync_gateway and sg_accel-specific handling.

**Comment by adamcfraser** [comment]
This issue was moved to couchbaselabs/sync-gateway-accel#27
