### ISSUE TITLE
[Distributed Index] CBGT startup error if renaming a bucket

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1138]
To reproduce:
- Start sync gw with CBGT enabled, with a db that is backed by bucket-2
- Shut down sync gw
- Update sync gw config such that db is backed by bucket-1

**Actual** Startup fails with cryptic error `Could not find database for bucket name: bucket-2` [more logs](https://gist.github.com/tleyden/ef99bf6270b96bfc435c)
**Expected** Not sure

**Comment by adamcfraser** [comment]
Closing - related to obsolete cbgt accel handling.
