### ISSUE TITLE
[Distributed Index] Fix kvChangeIndex DocChanged() throughput bottleneck

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1140]
The fix for https://github.com/couchbase/sync_gateway/issues/1139 was just a quick workaround, which introduced a throughput bottleneck in order to achieve correct behavior.  I'm adding this ticket to track the deeper fix which will take more thinking about design.

**Comment by tleyden** [comment]
One idea: maintain pool of worker goroutines for processing DocChanged callbacks

**Comment by zgramana** [comment]
@adamcfraser to udpate and review with @tleyden.
