### ISSUE TITLE
Jenkins job for perfcluster-aws

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1143]
- [ ] Kick off perfcluster with Jenkins

**Comment by tleyden** [comment]
More info on this Jira ticket: https://issues.couchbase.com/browse/MB-16269

**Comment by sethrosetter** [comment]
@zgramana Can we create a new ticket of move this the the backlog?

**Comment by zgramana** [comment]
Should this be closed instead?
