### ISSUE TITLE
Verify Gatling scenario logs in Splunk

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1148]

**Comment by ajres** [comment]
After updating the spunk monitor to upload all gatling theme scenario logs, this data no appears in in Splunk.

It looks like the splunk monitor polls the log files for changes and periodically uploads new entries. It looks like this happens every 30seconds or so.

**Comment by ajres** [comment]
The custom latency data currently appears in the gatling log entries as 'Some(<latency ms>)'

Will see if the format can be improved i.e. removal of the Some() wrapper

**Comment by ajres** [comment]
Some() is a method response wrapper in Scala, there is no way to remove this from the log entries. Extracting the data from this wrapper will be handled in the Splunk reports. See #1171
