### ISSUE TITLE
New diagnostic tools and scripts for channel index

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1149]
Distributed index uses binary data in the index bucket.

This may make support and root cause analysis challenging.

Should we consider providing data export and diagnostic tools/scripts?

**Comment by zgramana** [comment]
Related https://github.com/couchbase/sync_gateway/issues/1238

**Comment by adamcfraser** [comment]
This also applies to the in-memory channel index - currently we don't expose any way to inspect the number of channels/number of docs being stored in the in-memory channel index.
