### ISSUE TITLE
CORS access control header support

### ISSUE THREAD

**Issue by apage43** [couchbase/sync_gateway#115]
I'd like to be able to use Sync Gateway with PouchDB in a browser.

Browsers will check the `Access-Control-Allow-Origin` header, and if it contains the host being sent from, allow the request.

However, if the request is not a `GET`, or has any custom headers set, it will first send an `OPTIONS` request for the URL, which should reply with the same `Access-Control-Allow-Origin` header.

I believe `Access-Control-Allow-Methods` is also required in the case the `OPTIONS` preflight request is sent. The same headers sent with the `OTPIONS` response _must also_ be sent with the response to the actual request, or the browser will reject it.

[HTTP access control (CORS) - HTTP | MDN](https://developer.mozilla.org/en-US/docs/HTTP/Access_control_CORS#Access-Control-Allow-Methods)

The values for these should be configurable, as being permissive is a security risk.

**Comment by jchris** [comment]
Request on the mailing list for this feature: https://groups.google.com/forum/#!topic/mobile-couchbase/-VrYfdxwnzk

We will need it for any serious HTML5 support.

**Comment by jchris** [comment]
I've rebased a version of this at #695 and there is discussion at #265 but it's probably best to keep the discussion on the ticket.

@zgramana says:

> In reviewing this with @adamcfraser, I think restricting the URI's to which CORS policies can be applied to just the replication protocol endpoints would be appropriate from a security perspective. This would exclude the admin, user, and session API's. These could be revisited later.

I agree, and this would be easy enough to add without having to touch every handler method, just by only adding it to the db handlers, or even detecting leading "_" in the current Mux implementation. We might find we need to be able to interact with `_session` URLs but that will come up quickly in testing.

Also from @zgramana 

> Another thing we can consider is warning when CORS is enabled and the admin interface is not just listening on the local loopback.

There's another discussion about credentials for the admin interface, and https, etc. I think we want CORS on the admin interface b/c its part of the getting started path... but there are some bad cases we should warn about or refuse to allow.

> For those who need help now, and don't want to use a custom SG build: http://enable-cors.org/server_nginx.html

To offer a secure CORS nginx configuration we'd probably need to ask ourselves all the hard questions we have to ask to do a built-in implementation. So hopefully this turns out to be something built-in.

Aside: The #695 implementation doesn't seem to work with multiple origins configured.

**Comment by jchris** [comment]
Note about multiple origins: the spec technically allows for multiple origins, but browsers reject those responses. Google "The 'Access-Control-Allow-Origin' header contains multiple values" to see people hitting this.

The [workaround pattern](https://github.com/nicolaiarocci/eve/issues/408) is to match the origin header to the whitelist and only send the Access-Control-Allow-Origin header if it's in the list. Unless the config is `*`

**Comment by jchris** [comment]
I fixed #695 to do multiple origins correctly. 

I'm still not sure what set of URLs should support CORS. I think it's pretty clear that you shouldn't be able to create users on the admin port over CORS, to prevent session hijacking in cases where the admin has a session open on the admin ui.

**Comment by jchris** [comment]
I updated #695 to ensure there is no CORS on the admin port. 

The only code left I think, is blocking CORS on login attempts (POST to `_session`, `_persona`, and `_facebook` -- but I think there is no way to block password / cookie brute force attempts via GET with basic auth). Unless we want to disable basic auth with CORS.

But basically I think people who want CORS maybe are hosting their "app" from a static HTML and would like to be able to allow login without server code running on the page origin. Or maybe we can say all users are required to have at least a login endpoint on the page origin, so they can establish a session outside of CORS.

**Comment by jchris** [comment]
OK I've blocked all login / logout on CORS requests but I'm open to opening them up if it turns out people need them.

This is ready for review @adamcfraser 

For anyone following along at home, with #695 applied to SG master, and [this PR applied to PouchDB](https://github.com/pouchdb/pouchdb/pull/3633) I am able to get [this TodoMVC PouchDB demo](https://github.com/nickcolley/getting-started-todo) to sync with Sync Gateway.

My one wise for all this is the CORS config were less verbose, but I think that's the nature of the beast.

``` json
  "CORS":{
         "Origin":["http://localhost:8080", "http://localhost:8000"],
         "Headers":["If-Modified-Since","Cache-Control","Content-Type"],
         "MaxAge": 1728000
     }
```

**Comment by zgramana** [comment]
:+1:

**Comment by jchris** [comment]
Thanks @ssured for the original patch!

**Comment by SebastianBO** [comment]
Nice, will take a look at it.

**Comment by antoniusostermann** [comment]
Hey,

> OK I've blocked all login / logout on CORS requests 

does this mean combining PouchDB with https://github.com/nolanlawson/pouchdb-authentication to authenticate with sync gateway via basic auth wouldn't work? I am trying this currently, but I'm getting a 404 on  an `OPTIONS /_session` request. My sync gateway is configured for CORS like you described it:

``` js
   "CORS": {
    "Origin": ["http://localhost:8100"],
    "LoginOrigin": ["http://localhost:8100"],
    "Headers": ["Content-Type", "Accept", "Authorization", "Origin", "Referer","X-CSRF-Token"],
    "MaxAge": 17280000
   },
```

and I already tried different versions of connecting to it with pouchdb:

``` js
var remote = new PouchDB('http://'+user_id+':'+user_password+'@my-ip:4984/sync_gateway', {skipSetup: true});
    remote.login(user_id, user_password, function (err, response) {
      console.log("Login error occured");
      console.log(err);
      console.log(response);
    });
    var local = new PouchDB('db-synced');
    local.sync(remote, {live: true, retry: true}).on('error', console.log.bind(console));
```

gives me 404 on `OPTIONS /_session`, a 404 on a `GET _local/...` but also 200 for the `GET _changes` and `OPTIONS _changes` pulling.

``` js
var ajaxOpts = {
      ajax: {
        headers: {
          Authorization: 'Basic ' + window.btoa(user_id + ':' + user_password)
        }
      }
    };
    var remote = new PouchDB('http://my-ip:4984/sync_gateway', {skipSetup: true});
    var local = new PouchDB('db-synced');
    remote.login(user_id, user_password, ajaxOpts, function (err, response) {
      console.log("Login error occured");
      console.log(err);
      console.log(response);
    }).then(function(){
      console.log("in then function");
      local.sync(remote, {live: true, retry: true}).on('error', console.log.bind(console));
    });
```

Only gives me the 404 on `OPTIONS  /session`, `then`-function is not executed.

In both ways, my browser tells me that CORS-requests for _sessions are blocked. This is also stated by the error object catched in the above error function, although I find all headers I set in the `config.json` even in the response of the `OPTIONS`-request. There is also an `ACCESS-CONTROL-ALLOW-CREDENTIALS: true` header entry.

After hours of searching, I found this issue. Is this anywhere related to my problem? Is basic auth like I am doing it with Ionic/PouchDB not possible with sync gateway?

**Comment by jchris** [comment]
related https://github.com/couchbase/sync_gateway/issues/1310

**Comment by jchris** [comment]
Useful forum discussion https://forums.couchbase.com/t/user-authentication-plugin-for-pouchdb-work-with-sync-gateway/5174/18
