### ISSUE TITLE
Add CBGT UI

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1152]

**Comment by tleyden** [comment]
After attempting this, I'm seeing this page:

![screen shot 2015-10-20 at 11 47 12 am](https://cloud.githubusercontent.com/assets/296876/10617634/5e37c238-7720-11e5-91f7-8512a9973b86.png)

However if I try to click the Indexes link it tries to take me to http://localhost:4985/indexes/ rather than http://localhost:4985/_cbgt/ui/indexes/.  And going directly to http://localhost:4985/_cbgt/ui/indexes/ shows me the same page in the screenshot above.

Also, when I do "view source" it's trying to show static assets from /static rather than /_cbgt/ui/static.  

Either I'm doing something wrong (very likely), or the cbgt ui isn't very "embeddable friendly", or both.  

@steveyen any tips?

**Comment by tleyden** [comment]
Here's the [code](https://github.com/couchbase/sync_gateway/commit/0ba2ac637cde4f2f5d070ba6e32b068a0c3525e6) I added to sync gateway.

**Comment by steveyen** [comment]
No smoking guns.  Traun & I talked about some theories.  A related /api/diag REST fix is in available, which should be able to grab tons more info.

**Comment by tleyden** [comment]
Tagging this as release-prep 1.2 to try to get it into the release

**Comment by tleyden** [comment]
@steveyen I tried adding this again with this [code](https://github.com/couchbase/sync_gateway/commit/0ba2ac637cde4f2f5d070ba6e32b068a0c3525e6) and got pretty much the same results.  If I go to `_cbgt/ui`, it tries to redirect to `static/index.html`

```
curl -v http://localhost:4985/_cbgt/ui/
*   Trying ::1...
* Connected to localhost (::1) port 4985 (#0)
> GET /_cbgt/ui/ HTTP/1.1
> Host: localhost:4985
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Location: /static/index.html
< Date: Thu, 14 Jan 2016 20:04:32 GMT
< Content-Length: 41
< Content-Type: text/html; charset=utf-8
<
<a href="/static/index.html">Found</a>.

* Connection #0 to host localhost left intact
```

In the browser if I go directly to `_cbgt/ui/nodes/`, I see this:

<img width="776" alt="screen shot 2016-01-14 at 12 07 49 pm" src="https://cloud.githubusercontent.com/assets/296876/12336113/77bb319c-bab7-11e5-9f3e-25171397ab00.png">

Any tips or examples I can look at?

**Comment by tleyden** [comment]
Current status: did some experiments, but turned into pretty deep rabbit hole where paths aren't correct.  Also, I later discovered that calling `managerOptions["urlPrefix"] = "/_cbgt/ui"` breaks the cbgt rest api (everything is 404 after that change), so that will need more work.

NOTE: in order to change any of the html / js / or css within CBGT, you just need to run `make` in the cbgt folder, which will rebuild the "bindata" assets.  Due to $GOPATH issues, I ended up doing that under my normal $GOPATH, then copying the bindata.go file back over to the cbgt sync gateway submodule.

**Comment by adamcfraser** [comment]
Not planning to add this - any future monitoring enhancements will be done as part of manageability integration.
