### ISSUE TITLE
Bucket shadower ignores mutations with non-zero expiry

### ISSUE THREAD

**Issue by daverigby** [couchbase/sync_gateway#1161]
As per subject, the Bucket Shadower (https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/shadower.go#L74) currrently skips any TAP mutations which have a non-zero expiry:

```
if !isDeletion && event.Expiry > 0 {
    break // ignore ephemeral documents
}
```

From speaking to @ajres he notes that:

> ... I think the reason they are ignored is that SG does not get notified when a CBS doc is expired which would result in an inconsistency between the SG bucket and shadow bucket.

While this may be true, this is problematic for any use-case which uses non-zero expiries; these aren't necessarily "ephemeral" - an expiry could be many years in the future...

**Comment by djpongh** [comment]
With SG 1.50+ it is recommended to use XATTR's and not bucket shadowing
