### ISSUE TITLE
Bucket shadower ignores incoming document flags

### ISSUE THREAD

**Issue by daverigby** [couchbase/sync_gateway#1162]
The incoming document flags from a TAP mutation are ignored by the shadower: https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/shadower.go#L92

Note that `flags` is not used.

This will result in the flags getting reset to zero if documents are modified by a SGW client (and then sync'd back to the shadow bucket).

**Comment by djpongh** [comment]
With SG 1.50+ it is recommended to use XATTR's and not bucket shadowing
