### ISSUE TITLE
[Distributed index] Rename sequenceHasher.GetHash() to sequenceHasher.GetAndStoreHash()

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1165]
While trying to wrap my head around the code while debugging https://github.com/couchbase/sync_gateway/issues/1159, I feel the `sequenceHasher.GetHash()` method name isn't descriptive enough, since calling this method also causes the sequence hash to be stored in the hash bucket.

**Comment by adamcfraser** [comment]
The idea was to hide the underlying implementation - consumers are just getting a hash for a clock value (GetHash), or getting a clock for a hash value (GetClock).  Consumers don't need to worry about whether things are stored or not (or if the hasher is actually just doing compression on the clock, etc)

In addition, it's only going to 'Store' if someone else hasn't already stored the hash for that clock value.  

I think we should add detailed comments for the GetHash and GetClock methods to describe what they are doing, but I don't know if a change in the method name is appropriate.

**Comment by adamcfraser** [comment]
Added additional comments to GetHash while adding LRU cache support - available on distributed_index_hash_cache branch.
