### ISSUE TITLE
Create test run reports in Splunk

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1171]

**Comment by ajres** [comment]
Using Gatling fields from scenario.log required custom regex in the search query, this has been encapsulated as named fields using the Field Extractor tool in splunk.

The following fields are now available at search time for gatling events

gatling_scenario
gatling_test_user
gatling_record_type
gatling_group_hierarchy
gatling_request_name
gatling_first_byte_sent
gatling_last_byte_sent
gatling_first_byte_received
gatling_last_byte_received
gatling_extra_info
