### ISSUE TITLE
Add test run identifier to Splunk data

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1172]

**Comment by ajres** [comment]
Gatling creates scenario logs in a directory named with the epoch time when the test run started.

The path to the scenario.log is contained in the 'source' property and the uniquie directory name can be extracted with the following regex:

```
^.+-(?<test_run_identifier>\d+).*$ in source
```

This has been added to the Couchbase Splunk App as the field

test_run_identifier 

Need to find a similar solution for gateload

**Comment by ajres** [comment]
@sethrosetter, @tleyden 

Is the gateload.log always utilised when reviewing perf runs? If it is, it could be used to provide a test run identifier in a similar way to gatling scenario.log.

Currently the splunk forwarder tracks the directory containing the gateload.log, it will forward any file that appears there.

```
shell: /opt/splunkforwarder/bin/splunk add monitor /home/centos/logs -index main -sourcetype gateload_logs -auth admin:changeme
```

We could add a timestamp to the gatelaod.log name e.g.:

```
gateload-1443552758550.log
```

We can then extract the timestamp as a search field in splunk and map it to the test run identifier?

**Comment by tleyden** [comment]
> Is the gateload.log always utilised when reviewing perf runs?

So far, we pretty much ignore the gateload.log file .. so feel free to do what you want with it (rename it)

**Comment by djpongh** [comment]
Don't see us enhancing gateload anymore.
