### ISSUE TITLE
Add WebHook notifications for bucket online/offline

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1176]
Bucket online offline events should be added to the WebHooks service.

**Comment by ajres** [comment]
This would be useful to monitor SG bucket tavailability

**Comment by ajres** [comment]
Looking at the event processing code we will need to make the following changes:

event.go

Add a new const:

```
const {
    DocumentChange EventType = iota
    DBStateChange
    UserAdd
}
```

event_manager.go

Add convenience method RaiseDBStateChangeEvent

server-context.go

Update initEventHandlers method to validate a new dbstate_changed event key

Add new call to processEventHandlersForEvent for DBStateChange handlers

In online/offline code (and possible normal startup code?) raise DBStateChanges events:

```
if db.EventMgr.HasHandlerForEvent(DBStateChange) {
        db.EventMgr.RaiseDBStateChangeEvent(db, state, reason, instanceIP)
    }
```

WebHook payload will be a JSON document to compatibility with JS filter functions, proposed:

```
{
    "database" : "<Name of database that event has been raised against>",
    "adminInterface" : "<IP address:port of network interface ADMIN REST API is bound to>",
    "state" : "<state of interface i.e. 'online' or 'offline'>",
    "reason" : "<Reason for state change, i.e. Admin action or Auto detection of lost TAP feed",
    "localTime" : "<local system time when event was raised (ISO 8601)>"
}
```

**Comment by tleyden** [comment]
#1013 needs to get merged first.
