### ISSUE TITLE
event_manager_test failures

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#1178]
My guess is [the http listener for the webhooks](https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/event_manager_test.go#L227) either needs to be started Only Once, or else shut down after each test completes. Maybe InitWebhookTest() can take a closure as argument do the shutdown for us? withWebhookListener?

**Comment by adamcfraser** [comment]
Webhook tests have since been refactored in a way that addresses this.
