### ISSUE TITLE
GZip-compress continuous changes feed

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#1184]
GZip-compressing the changes feed is pretty effective at reducing bandwidth. The continuous mode is harder to compress, though, because it's sent in chunked mode, and the chunks need to be delivered and parsed independently. I'm actually not sure of what the HTTP spec says about the combination of Content-Encoding and chunked mode, i.e. which one takes priority. (I haven't looked at the spec to see if it covers this case.)

A good way to do this, whether or not it's standard, would be to have a single gzip context for the response. Each chunk would be compressed through this context, and then the context would be flushed to make sure the output contains all the input data. Then that compressed data would be written as a chunk. (This is the same way that I implemented the WebSocket-based changes feed yesterday, just substituting chunks for WebSocket messages.)

Of course we'd have to make sure that the response works correctly with various proxies/gateways.

**Comment by snej** [comment]
iOS doesn't use this mode, but Java and C# do, so once work on this is underway you should file issues on those two CBL implementations, to support this on the client side.

**Comment by adamcfraser** [comment]
Closing, as functionality has been superseded by 2.x replication.
