### ISSUE TITLE
[Distributed index] Fix gocb timeout errors / "skb rides the rocket" networking issue on AWS

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1193]
Factored out of https://github.com/couchbase/sync_gateway/issues/1185:

```
2015-10-08T21:13:34.053Z WARNING: WriteCasRaw got error when calling GetRaw:%!(EXTRA gocbcore.overloadError=Queue overflow.) -- db.writeCasRaw() at crud.go:958
```

**Comment by zgramana** [comment]
@brett19 We could really use your help on this one.

**Comment by tleyden** [comment]
- [x] Capture logs with gocb logging enabled and time outs and push to gist (Traun)
- [x] Look into bulk ops in order to reduce amount of cpu processing (Adam) 
- [x] Verify if per-node pipeline completely stops after timeout errors
- [x] Kick off longer go-couchbase-throughput at the same time
- [x] For both go execution tracer and cpu profiling: collect before timeouts and after timeouts and see if anything jumps out
- [x] Track server connection errors -- write error
- [x] Check CPU usage of Sync Gateway
- [x] Check netstat output to make sure kernel buffers aren't filling up
- [x] Look in server error logs (Traun)
- [x] Fork gocb and add verbose logging (write error, etc) (Adam)
- [x] Enhance logging with custom logger (Adam)
- [x] Convert back to interface{} from []byte (Traun)
- [x] Fix splunk (Traun)
- [x] Try go-throughput with 1k writers and 10k readers (Traun) 
- [x] Do an experiment where we run throughput test on sync gateway experiencing issues (Traun)

**Comment by tleyden** [comment]
> Try go-throughput with 1k writers and 10k readers

No issues observed with this

**Comment by tleyden** [comment]
> Do an experiment where we run throughput test on sync gateway experiencing issues

No issues observed with this either

**Comment by tleyden** [comment]
> Look in server error logs

The only errors I'm seeing in the couchbase error.log file during a run are these:

```
 buckets became not ready on node 'ns_1@ip-10-157-113-108.ec2.internal': ["bucket-1"], those of them are active ["bucket-1"]
[ns_server:error,2015-10-12T18:07:59.827,ns_1@ip-10-157-113-108.ec2.internal:ns_doctor<0.966.0>:ns_doctor:update_status:229]The following buckets became not ready on node 'ns_1@ip-10-154-37-187.ec2.internal': ["bucket-2"], those of them are active ["bucket-2"]
```

but they are just related to the "bucket flush" operation that happens before the run.

**Comment by tleyden** [comment]
With 500 pushers/pullers: [Logs with gocb logging enabled where timeouts appear](http://couchbase-mobile.s3.amazonaws.com/misc/sync_gateway_distributed_index_log.tar.gz)

Also, I did not see the `Got write error:` message on any of the three sync gateway machines for this run.

**Comment by tleyden** [comment]
In a recent run, after the gateloads had stopped pushing loads, I saw this message repeated in the logs:

```
2015-10-13T22:23:15.263Z gocb: DEBUG: Writing request to queue!
2015-10-13T22:23:15.263Z WARNING: Error loading stable sequence - skipping polling. Error:Queue overflow. -- db.(*kvChangeIndex).
```

as well as the "write error" message:

```
2015-10-13T20:58:27.753Z gocb: DEBUG: Got write error: write tcp 10.233.162.250:55006->10.157.113.108:11210: write: connection timed out
2015-10-13T20:59:31.753Z gocb: DEBUG: Got write error: write tcp 10.233.162.250:39503->10.154.37.187:11210: write: broken pipe
2015-10-13T20:59:31.753Z gocb: DEBUG: Got write error: write tcp 10.233.162.250:44675->10.169.54.14:11210: write: connection timed out
```

[Full logs](http://couchbase-mobile.s3.amazonaws.com/misc/sg_log_queue_overflow.tar.gz)

**Comment by tleyden** [comment]
I'm able to reproduce timeout issues with [go-couchbase-throughput](https://github.com/couchbaselabs/go-couchbase-throughput) commit https://github.com/couchbaselabs/go-couchbase-throughput/commit/a712706b20028c5144d0b78b45b529f973870efb:

## Steps to reproduce
- Setup perfcluster-aws cluster (3 CBS c3.8xlarge, 3 SGW c3.2xlarge)
- On each SGW machine, run

```
$ go get -u -v github.com/couchbaselabs/go-couchbase-throughput
$ go-couchbase-throughput -couchbaseUrl http://10.157.113.108:8091 -couchbaseBucket bucket-2 -docSizeBytes 1024 -totalNumDocs 500000
```

[go-couchbase-throughput logs](https://gist.github.com/tleyden/a7565c389b479dc03463) contains:
- [timeout errors](https://gist.github.com/tleyden/a7565c389b479dc03463#file-centos-ip-10-203-164-26-L13)
- [queue overflow errors](https://gist.githubusercontent.com/tleyden/a7565c389b479dc03463/raw/3d3003adc4e3036bd27035e8a73de7e502951ed7/centos@ip-10-203-164-26)  (search file for "overflow")

**Comment by tleyden** [comment]
- [x] Run pillowfight -- look for errors occurring.  Set num threads to number of cores.  Ratio: 1

**Comment by tleyden** [comment]
- [x] Look at IndexEntry docs -- byte array or json doc?

**Comment by tleyden** [comment]
- [x] Look at # of ops in sync gateway perf run (see expvars), size of docs.
- [x] Add expvars for histogram of index doc size

**Comment by tleyden** [comment]
> Run pillowfight -- look for errors occurring. Set num threads to number of cores. Ratio: 1

Running pillowfight from a single SG node as follows:

```
cbc-pillowfight -t 8 -r 50 -i 500000 --timeout 2500000 -B 1000 --spec couchbase://10.157.113.108/bucket-2 -m 1024 -M 1024 -n -v
```

Results: 
- No errors observed
- 220K ops/second (approx 10X seen on go-couchbase-throughput)
- 32 connections to couchbase (go-couchbase-throughput only uses 1 connection)
- Disk write queue between 1.5k - 2.5k

**Comment by tleyden** [comment]
I also tried pillowfight on the bare metal perf cluster, and got nearly identical results.  The only difference is that it was using 36 connections.

**Comment by tleyden** [comment]
With https://github.com/couchbaselabs/go-couchbase-throughput/commit/17e8f82721c083010976281cdaaf3ce3eb57511a on a single SG instance on AWS, I was able to reproduce the timeouts / queue  overflow using a single gocb bucket instance on the first try:

```
go build && ./go-couchbase-throughput -couchbaseUrl http://10.157.113.108:8091 -couchbaseBucket bucket-2 -docSizeBytes 1024 -totalNumDocs 500000 -storageEngineType gocb -numGoCBStorageEngines 1
```

whereas if I set it to 32 gocb bucket instances, I was not able to reproduce after 10+ tries.

```
go build && ./go-couchbase-throughput -couchbaseUrl http://10.157.113.108:8091 -couchbaseBucket bucket-2 -docSizeBytes 1024 -totalNumDocs 500000 -storageEngineType gocb -numGoCBStorageEngines 32
```

**Conclusion**: Using more gocb bucket instances, while not having any apparent increase in throughput so far (which may be a go-couchbase-throughput issue), does prevent timeout / queue overflow errors since we have effectively multiplied the total effective queue size by 32.

**Comment by tleyden** [comment]
- [x] Total time taken for run, total number of docs written + total number of docs read

**Comment by tleyden** [comment]
- [x] When getting a timed out error, sleep for 1 second to let the queue drain, then resume.

**Comment by tleyden** [comment]
> When getting a timed out error, sleep for 1 second to let the queue drain, then resume.

Did not help

**Comment by tleyden** [comment]
With these gocb code changes:
- Add a [write timeout](https://github.com/couchbase/gocb/blob/feature/metrics_expvar/gocbcore/memdconn.go#L114-L115) 
- Add some [extra logging](https://github.com/couchbase/gocb/blob/feature/metrics_expvar/gocbcore/memdpipeline.go#L209-L222)

and running go-couchbase-throughput with:

```
go build && ./go-couchbase-throughput -couchbaseUrl http://10.157.113.108:8091 -couchbaseBucket bucket-2 -docSizeBytes 1024 -totalNumDocs 20000000 -storageEngineType gocb -numGoCBStorageEngines 4
```

I am seeing these log messages:

```
2015/10/21 00:26:37 0xc8230c4000 Writer loop err: write tcp 10.233.162.250:60380->10.154.37.187:11210: i/o timeout
2015/10/21 00:26:37 0xc8230c4000 Writer loop waiting for killSig
2015/10/21 00:26:37 0xc8231c2630 Writer loop err: write tcp 10.233.162.250:47269->10.157.113.108:11210: i/o timeout
2015/10/21 00:26:37 0xc8231c2630 Writer loop waiting for killSig
2015/10/21 00:26:37 0xc8231a83f0 Writer loop err: write tcp 10.233.162.250:37323->10.169.54.14:11210: i/o timeout
2015/10/21 00:26:37 0xc8231a83f0 Writer loop waiting for killSig
2015/10/21 00:26:37 0xc8230c4750 Writer loop err: write tcp 10.233.162.250:37332->10.169.54.14:11210: i/o timeout
2015/10/21 00:26:37 0xc8230c4750 Writer loop waiting for killSig
```

And looking at the netstat output for the first port listed above:

```
[centos@ip-10-233-162-250 gocb]$ netstat | grep -i 60380
tcp        0  81780 ip-10-233-162-250:60380 ip-10-154-37-187.:11210 ESTABLISHED
[centos@ip-10-233-162-250 gocb]$ netstat | grep -i 60380
tcp        0  81780 ip-10-233-162-250:60380 ip-10-154-37-187.:11210 ESTABLISHED
[centos@ip-10-233-162-250 gocb]$ netstat | grep -i 60380
tcp        0  81780 ip-10-233-162-250:60380 ip-10-154-37-187.:11210 ESTABLISHED
[centos@ip-10-233-162-250 gocb]$ netstat | grep -i 60380
tcp        0  81780 ip-10-233-162-250:60380 ip-10-154-37-187.:11210 ESTABLISHED
```

The Send-Q is "stuck" at 81780.

Also it's noteworthy that it looks like it takes 15 minutes between waiting for the killSig and actually receiving it:

```
2015/10/21 00:26:37 0xc8230c4000 Writer loop err: write tcp 10.233.162.250:60380->10.154.37.187:11210: i/o timeout
2015/10/21 00:26:37 0xc8230c4000 Writer loop waiting for killSig
...
2015/10/21 00:41:31 0xc8230c4000 Writer loop got killSig
```

**Comment by brett19** [comment]
At quick glance, I suspect the queue that the dead servers offload their requests to is becoming full and preventing the killSig from completing.

**Comment by tleyden** [comment]
Some more diagnosis after adding more instrumentation.

It looks like after a write error, the goroutine is getting stuck [waiting for something to appear on the killsig channel](https://github.com/couchbase/gocb/blob/feature/metrics_expvar/gocbcore/memdpipeline.go#L229), and meanwhile the queue continues to pile up.

At this snapshot, note that:
- PacketWriteErrors is 1, meaning it had a write error.
- PacketWriteWaitKillSig is 1, meaning it's waiting for a killsig
- PacketWriteGotKillSig is 0, meaning it's never gotten a killsig

```
      {
        "Name": "ip-10-157-113-108.ec2.internal:11210",
        "QueueSize": 305,
        "State": 1,
        "PacketsWritten": 7938,
        "PacketsRead": 6841,
        "PacketWriteAttempts": 7939,
        "PacketWriteErrors": 1,
        "PacketWriteWaitKillSig": 1,
        "PacketWriteGotKillSig": 0,
        "PacketReadAttempts": 6842,
        "PacketReadErrors": 0
      },
```

a bit later .. everything else is the same, but the Queue is piling up:

```
      {
        "Name": "ip-10-157-113-108.ec2.internal:11210",
        "QueueSize": 806,
        "State": 1,
        "PacketsWritten": 7938,
        "PacketsRead": 6841,
        "PacketWriteAttempts": 7939,
        "PacketWriteErrors": 1,
        "PacketWriteWaitKillSig": 1,
        "PacketWriteGotKillSig": 0,
        "PacketReadAttempts": 6842,
        "PacketReadErrors": 0
      },
```

ditto:

```
      {
        "Name": "ip-10-157-113-108.ec2.internal:11210",
        "QueueSize": 1106,
        "State": 1,
        "PacketsWritten": 7938,
        "PacketsRead": 6841,
        "PacketWriteAttempts": 7939,
        "PacketWriteErrors": 1,
        "PacketWriteWaitKillSig": 1,
        "PacketWriteGotKillSig": 0,
        "PacketReadAttempts": 6842,
        "PacketReadErrors": 0
      },

....

      {
        "Name": "ip-10-157-113-108.ec2.internal:11210",
        "QueueSize": 2007,
        "State": 1,
        "PacketsWritten": 7938,
        "PacketsRead": 6841,
        "PacketWriteAttempts": 7939,
        "PacketWriteErrors": 1,
        "PacketWriteWaitKillSig": 1,
        "PacketWriteGotKillSig": 0,
        "PacketReadAttempts": 6842,
        "PacketReadErrors": 0
      },

....

      {
        "Name": "ip-10-157-113-108.ec2.internal:11210",
        "QueueSize": 5000,
        "State": 1,
        "PacketsWritten": 7938,
        "PacketsRead": 6841,
        "PacketWriteAttempts": 7939,
        "PacketWriteErrors": 1,
        "PacketWriteWaitKillSig": 1,
        "PacketWriteGotKillSig": 0,
        "PacketReadAttempts": 6842,
        "PacketReadErrors": 0
      },

```

**Comment by tleyden** [comment]
> It looks like after a write error, the goroutine is getting stuck waiting for something to appear on the killsig channel, and meanwhile the queue continues to pile up.

The reason it never gets anything on the killsig channel appears to be because it's blocked on a [read call](https://github.com/couchbase/gocb/blob/feature/metrics_expvar/gocbcore/memdpipeline.go#L194) -- based on the fact that in the above stats, PacketsRead and PacketReadAttempts are both stuck at the same values, with PacketReadAttempts being +1 more than PacketsRead

**Comment by tleyden** [comment]
I did an experiment to set a read timeout of 5 seconds in https://github.com/couchbase/gocb/commit/4c5c862177a2fb3560345b38113309fc4412c133, and it made a huge difference.  The go-couchbase-throughput test ran to completion and ops were steadily at 125K almost the entire time, except for one brief dip to 25K for about 15 seconds.  

In the [logs](https://gist.github.com/tleyden/c95d4c00e88bbbbb7639) I noticed read timeout messages such as:

```
2015/10/21 18:30:07 Server read error: read tcp 10.233.162.250:60651->10.154.37.187:11210: i/o timeout
2015/10/21 18:30:07 Server read error: read tcp 10.233.162.250:37588->10.169.54.14:11210: i/o timeout
2015/10/21 18:30:07 Server read error: read tcp 10.233.162.250:47516->10.157.113.108:11210: i/o timeout
2015/10/21 18:30:07 Server read error: read tcp 10.233.162.250:37609->10.169.54.14:11210: use of closed network connection

```

**Comment by tleyden** [comment]
Action items:
- [x] Document behavior when read/write timeouts are removed from go-couchbase-throughput
- [x] Compare behavior to bare metal cluster
- [x] Enhance go-couchbase-throughput to keep metrics on how many ops failed
- [x] Enhance go-couchbase-throughput to retry failed ops, so at end of run we know that we had X successful ops
- [x] Study why writes are blocking for so long
- [x] Is it possible to get info on how full kernel buffers are?

**Comment by tleyden** [comment]
> Document behavior when read/write timeouts are removed from go-couchbase-throughput

With [read/write timeouts removed](https://github.com/couchbase/gocb/commit/818fb2a55450ca83c5f6e7870cb914f0060b9b90), and running with 

```
go build && ./go-couchbase-throughput -couchbaseUrl http://10.157.113.108:8091 -couchbaseBucket bucket-2 -docSizeBytes 1024 -totalNumDocs 20000000 -storageEngineType gocb -numGoCBStorageEngines 10
```

I'm not seeing any "Server read" or "Write loop" errors in the logs, yet the throughput drops to ~ 1k ops/sec and many of the queues are full at 5000 and not processing any data.  Here is the expvar output:

https://gist.github.com/tleyden/0a47b1a366970f75407a  (search for 5000)

Also, when I do netstat, many of the sockets have "stuck" Send-Q values.  For example, this one has been at the same value of 0/80064 for 15 minutes:

```
tcp        0  80064 ip-10-233-162-250:48830 ip-10-157-113-108:11210 ESTABLISHED
```
- [Full netstat output](https://gist.github.com/tleyden/be143ad28c500dd76c58)
- [Full netstat output 1 min later](https://gist.github.com/tleyden/84335ee6895365496c2a)

**Comment by tleyden** [comment]
> Compare behavior to bare metal cluster

Using this gocb commit: https://github.com/couchbase/gocb/commit/818fb2a55450ca83c5f6e7870cb914f0060b9b90 and running go-couchbase-throughput via:

```
go build && ./go-couchbase-throughput -couchbaseUrl http://172.23.96.64:8091 -couchbaseBucket bucket-1 -docSizeBytes 1024 -totalNumDocs 20000000 -storageEngineType gocb -numGoCBStorageEngines 10
```

on gateload_1 in the bare metal cluster, throughput was consistent at 125K and I saw no timeout errors or other errors in the logs.  [Full logs](https://gist.github.com/tleyden/af07961249246f1fc71b)

**Comment by tleyden** [comment]
Looked at the network capture with @jamesmauss, and found that for the "stuck" sockets where no data is moving according to netstat, there are many retransmission errors showing up in wireshark:

![screen shot 2015-10-22 at 4 01 39 pm](https://cloud.githubusercontent.com/assets/296876/10680630/57bb910c-78d6-11e5-8aac-4a4fe778cefb.png)

**Comment by tleyden** [comment]
According to this [Server Fault](http://serverfault.com/questions/143910/finding-cause-of-tcp-retransmission-within-a-lan) post:

> TCP retransmissions are usually due to network congestion.

However, the network on AWS actually appears to be _faster_ than on the bare metal cluster.

## AWS

```
 $ iperf -f m -c 10.157.113.108
------------------------------------------------------------
Client connecting to 10.157.113.108, TCP port 5001
TCP window size: 0.09 MByte (default)
------------------------------------------------------------
[  3] local 10.233.162.250 port 39257 connected with 10.157.113.108 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1298 MBytes  1088 Mbits/sec
```

## Bare Metal

```
gateload_1:/root # iperf -f m -c 172.23.96.64
------------------------------------------------------------
Client connecting to 172.23.96.64, TCP port 5001
TCP window size: 0.02 MByte (default)
------------------------------------------------------------
[  3] local 172.23.96.63 port 17659 connected with 172.23.96.64 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1123 MBytes   942 Mbits/sec
```

Note: I'm not sure why there was a discrepancy in the TCP window size

**Comment by tleyden** [comment]
Another thing worth noting is that it's actually possible to get a 10 Gigabit/second network on AWS.  From this [blog post](https://blog.serverdensity.com/network-performance-aws-google-rackspace-softlayer/):

> Amazon’s larger instances, such as the c3.8xlarge tested here, support the enhanced 10 GB networking, however you must use the Amazon Linux AMI ([or manually install the drivers](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html)) within a VPC.

**Comment by tleyden** [comment]
iftop output on bare metal load test:

```
./go-couchbase-throughput -couchbaseUrl http://172.23.96.64:8091 -couchbaseBucket bucket-1 -docSizeBytes 1024 -totalNumDocs 20000000 -storageEngineType gocb -numGoCBStorageEngines 1
```

![screen shot 2015-10-22 at 4 26 55 pm](https://cloud.githubusercontent.com/assets/296876/10681001/da29d9e8-78d9-11e5-8a58-601cfaaad35a.png)

**Comment by tleyden** [comment]
From @jamesmauss:

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1317811

and I noticed these in our dmesg logs:

```
[879436.173803] net_ratelimit: 14 callbacks suppressed
[879436.174792] xen_netfront: xennet: skb rides the rocket: 19 slots
[879436.298796] xen_netfront: xennet: skb rides the rocket: 19 slots
[879436.322374] xen_netfront: xennet: skb rides the rocket: 19 slots
... repeated many times
```

This [blog post](http://blog.stathat.com/2014/12/22/fix_ec2_network_issue_skb_rides_the_rocket.html) suggests a fix:

```
sudo ethtool -K eth0 sg off
```

**Comment by tleyden** [comment]
After making the above change, was able to run the gocb test with:

```
go build && ./go-couchbase-throughput -couchbaseUrl http://172.23.96.64:8091 -couchbaseBucket bucket-1 -docSizeBytes 1024 -totalNumDocs 20000000 -storageEngineType gocb -numGoCBStorageEngines 10
```

and it stayed steady at 90K ops/sec throughout the test until I killed it.  (I let it run for at least 10 mins)

**Comment by tleyden** [comment]
Fixed by these changes https://github.com/couchbase/sync_gateway/issues/1193#issuecomment-150395613

**Comment by tleyden** [comment]
Here is the corresponding [jira ticket](https://issues.couchbase.com/browse/MB-16640) for the "skb rides the rocket" issue.
