### ISSUE TITLE
stats hooks to run on customer machines

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#120]
we want to be able to see how right-sized their cluster is, and also understand the client and backend patterns that are driving it.

some ideas for what to include in the dump:
- req/sec over time (maybe 1 minute resolution is ok)
- number of documents (can log it every 1 minute)

As I write this I think maybe it could be done by a script that consumes the log file...

What do you think?

**Comment by adamcfraser** [comment]
Expect to continue to use expvars going forward for diagnostic tracking.
