### ISSUE TITLE
GET /{db}/_session/{session-id} by Admin REST API return 200 when session is expired

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1201]
I am using SG 1.1.1-10 + CB 3.1.0-1776 Enterprise Edition (build-1776), 
when I call  /{db}/_session/{session-id} by 4985 with a expired session, I can get 200 response with authentication_handlers/channels etc Info. 
when a session is expired,I think I should not get the session info.

**Comment by atom992** [comment]
and at the same time,when I got doc by Cookies with a expired session, I can either  get the doc.

**Comment by adamcfraser** [comment]
How are you confirming/verifying that the session is expired?

**Comment by atom992** [comment]
I checked the session doc in cb, the expired time shows it is expired. such as:

{
  "id": "bd438edcbc28c8c215f10d0734b61e2430879621",
  "username": "testuser",
  "expiration": "2015-10-16T16:36:38.499956558+08:00",
  "ttl": 86400000000000
}

**Comment by atom992** [comment]
the ttl value is strange, it is a huge number that do not match expiration.

**Comment by atom992** [comment]
I do some test, and I found that the ttl value of session doc in cb will be add 9 zero. 
so if I create a session with 1 day, the ttl will be: 86400000000000, It should be 86400
even I create a session by Admin REST API with ttl ,it will be add 9 zero too.

**Comment by adamcfraser** [comment]
Session expiry is based on actual expiry (removal) of the document by Couchbase.  If you can still see the session doc in cb, it's not being expired properly.

The ttl in the doc looks like the normal default expiry value (24 hours, in nanoseconds).

The expiration value looks like tomorrow (at least in my time zone) - are you certain it should be expired based on that date?

**Comment by atom992** [comment]
yes, I am certain. because when I got _changes API of SG  from CBL with this cookies, It return 401.

**Comment by adamcfraser** [comment]
If the session doc still exists in cb, the 401 shouldn't be due to session expiry.  Can you replicate the 401 with a direct API call against 4984?

**Comment by atom992** [comment]
sorry , may be the  Cookie problem, I catch the request from CBL to SG,and I found I send 2 SyncGatewaySession Cookies like this:
cookie: 'SyncGatewaySession=bd438edcbc28c8c215f10d0734b61e2430879621, SyncGatewaySession=bd438edcbc28c8c215f10d0734b61e2430879621',
I will do more test.

**Comment by ajres** [comment]
The ttl value stored in the doc is a golang time.Duration which is serialised in nanoseconds.

As @adamcfraser  says this is the correct value for a ttl of 24 hours

**Comment by atom992** [comment]
when I login with the same session today,I found the session info in cb is changed to:

{
  "id": "bd438edcbc28c8c215f10d0734b61e2430879621",
  "username": "testuser",
  "expiration": "2015-10-17T09:33:58.99828523+08:00",
  "ttl": 86400000000000
}

yesterday the same session info is:

{
"id": "bd438edcbc28c8c215f10d0734b61e2430879621",
"username": "testuser",
"expiration": "2015-10-16T16:36:38.499956558+08:00",
"ttl": 86400000000000
}

**Comment by atom992** [comment]
Does this mean the ttl value is Idle session timeout , not the max session timeout?

**Comment by ajres** [comment]
When you access a valid session and 10% or more of the ttl has expired, then the session is extended by the ttl from the current access time and the session document updated.

**Comment by zgramana** [comment]
May need to make this change in 2.0 since this is a breaking change for any existing clients depending on this behavior.

**Comment by adamcfraser** [comment]
@jamiltz We should document that ttl is idle session timeout.

**Comment by djpongh** [comment]
Opened new issue under mobile-portal: https://github.com/couchbaselabs/couchbase-mobile-portal/issues/617
