### ISSUE TITLE
GET _active_tasks from CBL show it takes long time during  progress = 99

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1214]
I am using SG 1.1.0-28 + CBL 1.1

when I sync docs from SG to CBL, and I check the _active_tasks from REST API, I found it will take a long time during  progress = 99, such as:
[{"completed_change_count":112,"source":"http://X.X.X.X/sgdb/","task":"repl005","status":"Processed 112 / 113 changes","progress":99,"continuous":true,"target":"cbldb","change_count":113,"type":"Replication"}]

the last changed docs is not a big doc.

so I want to know what order does sync docs from SG to CBL? and is there some reason cause the long time during  progress = 99?

**Comment by zgramana** [comment]
@atom992, can you please refile this in the CBL repo you are seeing it in (e.g. iOS, Android, .NET). This isn't a SG issue.
