### ISSUE TITLE
Convert cb-heartbeat to use cbgt cfg instead of view

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1217]
@adamcfraser noticed heartbeat view queries taking up to 5 seconds!  
- We are doing `stale=false` view queries
- The view has to index all docs, not just heartbeat docs .. if the indexer gets backed up then it could cause this view query to be slow
- In general, we are trying to move away from views

**Comment by steveyen** [comment]
Hmmm, might need to think about this one a bit...

The backstory... I've tried somewhat to reduce writes/updates in cbgt as much as I can to the Cfg.  Not from any hard data, but just from a design or architectural intuition that the configuration backends underneath the hood of the Cfg interface might not be so good at heavy writes/mutation load.

So, currently, cbgt only updates the Cfg when a new node is added/removed, or when an index is created/deleted.  So, not too often.

Heartbeats, though... might be more often.

That said, the couchbase bucket Cfg backend is the expected exception to be able to handle lots of writes.

**Comment by tleyden** [comment]
We'd only be reading from the Cfg, no writes.  Essentially as a way to discover all the known node uuids, so we could know which heartbeat doc id's to perform a GET on.

**Comment by adamcfraser** [comment]
This has been included as part of import work in Mercury.
