### ISSUE TITLE
Gocb sharding issue

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1218]
Reported by @sethrosetter via Email -- with num_shards = 64 and 4 sync gateway writer nodes, it ends up where 2 nodes are servicing 32 shards, and the other 2 nodes aren't servicing any.

Wondering if it's an issue with cbgt pindex residue files from previous runs.

I will try to reproduce and study.

**Comment by tleyden** [comment]
Here is the cfg from the aws perfcluster .. 

https://gist.github.com/tleyden/cae8ca5862d08d250df9

**Comment by tleyden** [comment]
After looking at the cfg from the aws perfcluster posted in previous comment, it seems to be correct.  The 64 pindexes, which each service 16 vbuckets, are spread evenly across the three nodes:

```
[root@ip-10-233-162-250 logs]# cat /tmp/cfg.json | grep -i 10ab5d63f4d8cc2e | wc -l
21
[root@ip-10-233-162-250 logs]# cat /tmp/cfg.json | grep -i 35a4f3f0edceaae6 | wc -l
22
[root@ip-10-233-162-250 logs]# cat /tmp/cfg.json | grep -i 5a08ec2121e795f4 | wc -l
21
```

**Comment by tleyden** [comment]
@sethrosetter can you run this command on one of your sync gateways and upload the result to a gist?

```
curl localhost:4985/_cbgt/api/cfg | jq .
```

**Comment by tleyden** [comment]
@adamcfraser I just tried:
1. shutting down the sync gateways
2. deleting the sync gateway logs
3. flushing the buckets -- without touching the .pindex files on disk
4. restarting the sync gateways

When I looked at the Cfg json, it looked fine: https://gist.github.com/tleyden/30b8e56e193ab64d494d

However, grepping through the Sync Gateway logs for pindex add / remove messages, the numbers did not seem to add up:

https://gist.github.com/tleyden/a742f799c2f7ad6235ec

@steveyen despite the pindex -> node distribution looking fine when looking at the Cfg JSON, from grepping the sync gateway [logs](https://gist.github.com/tleyden/a742f799c2f7ad6235ec) for pindex messages, it appears that the pindex counts on the respective nodes would be 0 on all of the nodes.  Am I mis-interpreting the cbgt logs?

Here are the full sync gateway logs for each node:
- [ip-10-203-164-26 logs](http://filebin.ca/2Jckr3nFnOQA/sync_gateway_error.log)
- [ip-10-67-182-77 logs](http://filebin.ca/2JclEAFY9rOZ/sync_gateway_error.log)
- [ip-10-233-162-250 logs](http://filebin.ca/2JclN2dcMxyH/sync_gateway_error.log)

**Comment by adamcfraser** [comment]
Looking at the actual logs, I think the pindex counts look ok, if you assume that the initial 'removals' are cleanup of the stale pindex references from the previous run:

ip-10-203-164-26
- removes 21 pindexes (old?)
- adds 21 
  result: 21 new pindexes

ip-10-67-182-77
- removes 22 pindexes (old?)
- adds 32 
- removes 10 
  result: 22 new pindexes

ip-10-233-162-250
- removes 21 (old)
- adds 64
- removes 32 
- removes 14
- adds 3
  result: 21 new pindexes

(total 64 pindexes)

**Comment by tleyden** [comment]
Ahh, makes sense.

**Comment by sethrosetter** [comment]
@tleyden 4 sg configs https://gist.github.com/sethrosetter/ed37089a1363c5a5f79c

**Comment by tleyden** [comment]
@sethrosetter are they all distributed index writers?

**Comment by sethrosetter** [comment]
@tleyden yes

**Comment by sethrosetter** [comment]
Weird cbgt error on non registered node https://gist.github.com/sethrosetter/c30919813085df2e4831

**Comment by sethrosetter** [comment]
Beginning of the log for a working sync_gateway https://gist.github.com/sethrosetter/fbb4c71ae2785ff2eb17

**Comment by tleyden** [comment]
@steveyen We have a case where there are 4 sync gateways, but [only three](https://gist.github.com/sethrosetter/ed37089a1363c5a5f79c#file-sg1_config-json-L31-L72) are showing up in the CBGT Cfg.  

Here are the [logs](https://gist.github.com/sethrosetter/c30919813085df2e4831#file-gistfile1-txt-L71-L146) for the Sync Gateway that does not show up in Cfg -- any clues?  

For comparison purposes, [here are the logs](https://gist.github.com/sethrosetter/fbb4c71ae2785ff2eb17#file-gistfile1-txt-L69-L99) for one of the Sync Gateways that did manage to appear in the Cfg.

**Comment by sethrosetter** [comment]
Upon restart of the sync_gateway service, the sync_gateway appeared to be properly registered with cbgt https://gist.github.com/sethrosetter/7da934c1e282ba9f5e5b

**Comment by sethrosetter** [comment]
curl -X "GET" "http://172.23.105.122:4985/_cbgt/api/cfg" now shows 4 node defs instead of 3.

**Comment by tleyden** [comment]
Action items for me:
- [x] Upgrade to use latest cbgt
- [ ] Document how to use "diag" endpoint
- [ ] @sethrosetter to reproduce (or at least try)
- [ ] Send "diag" output to @steveyen
