### ISSUE TITLE
Can't purge documents (_purge is not implemented)

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#1219]
SG doesn't implement the [`/db/_purge`](http://docs.couchdb.org/en/latest/api/database/misc.html) command, so there is no way to purge documents. I've seen this feature requested several times by developers who want to get rid of obsolete documents (i.e. ones that were deleted a long time ago, or are time-sensitive and have expired.)

**Comment by snej** [comment]
This keeps coming up over and over — people are asking how to get rid of old documents to reduce db size, and I keep having to explain that it's not implemented. I think I've written about it four times in the last week, on the forum and Google group and with our own support engineers.

AFAIK this should be easy to implement: just a Del call on the doc's key in the bucket. It would be great if this could be done for 1.2.

**Comment by adamcfraser** [comment]
I agree - this should be quick to turn around.  I think concerns around documentation and recommendations for appropriate usage were the main reason this originally got pushed to 1.3, but we should revisit based on how much of a pain point it's becoming for users.

**Comment by ajres** [comment]
Also need to remove doc from the rev cache to prevent false hits post purge.

Will not explicitly remove from channel cache or channel index, devs need to understand issues with using this feature.

**Comment by ajres** [comment]
Discussed implementation with @snej and @adamcfraser 

/{db}/_purge will be admin only call

To perform a purge operation you must send a JSON object, where the keys are the document IDs to purge and each value is a list of the revisions to purge.

This implementation will only support a revision of "*", which means purge the complete document revision tree

If a revision other than "*" is passed log a warning, do not purge the document and do not include the document ID in the response.

If a document ID is passed that does not exist in the database, do not include the document ID in the response.

The response will contain  a list of the document IDs and revisions successfully purged.

This implementation will always return "*" as the revision purged for each document ID.

This implementation will not return a "purge_seq" property in the response.

**Comment by ajres** [comment]
The initial implementation has some potential side effects due to not removing entries from caches.

When purging a document, a message similar to the following may appear in the Sync Gateway logs

```
2016-01-13T17:32:32.811Z WARNING: changeCache: Error unmarshaling doc "doc1": unexpected end of JSON input -- db.(*changeCache).DocChanged.func1() at change_cache.go:327
```

The removed document may still be returned by _changes and _all_docs calls
