### ISSUE TITLE
Add golang attributes to generate swagger spec

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1221]
It may make the rest API more discoverable. The idea came up when I was asked to provide the http://XXX.XX.XXX.XXX:4985/_cbgt/api/cfg for debugging purposes. This is not a very discoverable endpoint but users may like to know it exists.

**Comment by zgramana** [comment]
For reference, see https://github.com/yvasiyarov/swagger/wiki/Declarative-Comments-Format

**Comment by ajres** [comment]
@adamcfraser can we tag this for 1.4?

**Comment by djpongh** [comment]
@ajres no

**Comment by adamcfraser** [comment]
Not planning to implement this - sticking with the docs-based version of the swagger spec for the time being.
https://github.com/couchbaselabs/couchbase-mobile-portal/tree/master/swagger
