### ISSUE TITLE
Update nginx sample configs to support CORS

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1226]
Forum post was asking about configuring CORS in SG, with nginx in front of SG.

Looks like nginx may need to be configured to support CORS.

http://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx

**Comment by ajres** [comment]
From original forum post OP issue was a typo in their CORS config

**Comment by JeffThomasWriter** [comment]
I moved this to the mobile portal issues, as issue 270:

https://github.com/couchbaselabs/couchbase-mobile-portal/issues/270
