### ISSUE TITLE
Always return Forbidden by User Port of SG while query data with view 

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1232]
I am using SG 1.1.1-10, and when I query data by user port, I always return  Forbidden. and when I create more than one view under one design view. only the last view can by queried by admin port.

**Comment by ajres** [comment]
There is a fix for multiple views in the same design doc on master, [see](https://github.com/couchbase/sync_gateway/issues/1109)

Could you retest against master and post here if you still experience an issue.

**Comment by atom992** [comment]
yes,It works as expect against master.Thank you.

**Comment by atom992** [comment]
which version of SG  will be included the fixed code?

**Comment by ajres** [comment]
It should be included in the 1.2 release

**Comment by atom992** [comment]
ok, Is there a exactly time to release 1.2?

**Comment by zgramana** [comment]
We don't have an official release date, though it will be before the end of the year.
