### ISSUE TITLE
Item Count is very high 

### ISSUE THREAD

**Issue by DayronIG** [couchbase/sync_gateway#1242]
That the bucket containing the database has a count item very high , for example I have 10 documents , but in the bucket containing the syncgateway appear 1500 item counts in the bucket , and synchronize 10 documents too you delay .
What am I doing wrong.
Thank you

**Comment by adamcfraser** [comment]
The forums are probably a better place for this type of question - moved it here:
https://forums.couchbase.com/t/item-count-is-very-high/5682
