### ISSUE TITLE
Sync gateway "service" pid may be confusing

### ISSUE THREAD

**Issue by krugster** [couchbase/sync_gateway#1246]
After installing the latest RPM it now installs sync gateway as a service (thanks Andy!)

Both the installer and "initctl" show sync gateway running on one pid (lets say 2490 for this example) yet a 'ps' shows it running on other pids and the one that is listed seems to just be running /bin/sh:
Install/Updated:
[root@cb1 ~]# rpm -U couchbase-sync-gateway-enterprise_1.1.1-327_x86_64.rpm 
initctl: Job is already running: sync_gateway

You have successfully uninstalled Couchbase Sync Gateway.

sync_gateway stop/waiting
sync_gateway start/running, process 2940
...

initctl:
[root@cb1 ~]# initctl status sync_gateway
sync_gateway start/running, process 2940

ps:
[root@cb1 ~]# ps aux | grep 2940
root      2940  0.0  0.0  11340  1252 ?        Ss   16:20   0:00 /bin/sh -e /dev/fd/11
root      3157  0.0  0.0 103256   856 pts/0    S+   16:20   0:00 grep 2940

[root@cb1 ~]# ps aux | grep sync
root      2941  0.0  0.0  66884  1832 ?        S    16:20   0:00 su --session-command /opt/couchbase-sync-gateway/bin/sync_gateway /home/sync_gateway/sync_gateway.json >> /home/sync_gateway/logs/sync_gateway_access.log 2>> /home/sync_gateway/logs/sync_gateway_error.log sync_gateway
500       2942  0.0  0.0   9232  1056 ?        S    16:20   0:00 bash -c /opt/couchbase-sync-gateway/bin/sync_gateway /home/sync_gateway/sync_gateway.json >> /home/sync_gateway/logs/sync_gateway_access.log 2>> /home/sync_gateway/logs/sync_gateway_error.log
500       2943  0.1  0.5 131136 11124 ?        Sl   16:20   0:00 /opt/couchbase-sync-gateway/bin/sync_gateway /home/sync_gateway/sync_gateway.json

If I kill 2940, sync gateway stays running.

It may be a minor issue, but for someone who is trying to track down the pid of a process this would lead to some confusion.  I'm also not entirely clear why there are 3 sync gateway processes running.

**Comment by ajres** [comment]
Demonising a gaoling built executable is [problematic](http://stackoverflow.com/questions/10067295/how-to-start-a-go-program-as-a-daemon-in-ubuntu) 

This means that the /etc/init.d/functions damon command can not be used.

The sys_init script mentioned above runs the process via a separate shell.

This results in the multiple associated processes that you see using 'ps'

**Comment by ajres** [comment]
This [repo](https://github.com/takama/daemon) might offer a solution for running SG as a true daemon process without having to use wrapper shell processes.

**Comment by adamcfraser** [comment]
Closing based on age - can reopen if specific use cases are identified.
