### ISSUE TITLE
Use single gocb BulkOp (BulkSet) for concurrent index writes

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1247]
NOTE: regression found in https://github.com/couchbase/sync_gateway/issues/1262

There are several places in the index write processing where we're spawning multiple goroutines to do concurrent writes to the index bucket:
1. Writing index entry docs: https://github.com/couchbase/sync_gateway/blob/feature/distributed_index/src/github.com/couchbase/sync_gateway/db/kv_change_index.go#L548
2. Writing channel blocks:
   https://github.com/couchbase/sync_gateway/blob/feature/distributed_index/src/github.com/couchbase/sync_gateway/db/kv_channel_storage.go#L140

It would be more efficient to use the gocb BulkOp handling to perform these in a single call to gocb - both to avoid the additional goroutines in the Sync Gateway codebase, as well as to reduce the work being done on the gocb side to manage the separate calls (spawning notification channels for the response, etc).
#1 (writing the index entry docs) is just a simple insert, and doesn't need cas handling.  Returning errors for any failed operations should be sufficient.
#2 (writing the channel docs) does a cas write loop.  The new bulk operation would need to be able to report cas failure in a way that will let us implement cas loop handling similar to what's in the existing WriteCasRaw.

**Comment by tleyden** [comment]
@adamcfraser I just pushed a commit if you want to take a quick look.

I wasn't able to use `UpsertOp`, since it didn't take a Cas value.  I took the same approach we have in `WriteCas` and am doing:
- If Cas == 0, do an Insert
- Else, do a Replace

Still pending is to create something like the existing writeCasRaw that does the cas loop/replay for bulk ops.

**Comment by ingenthr** [comment]
w.r.t. CAS, that's the right approach @tleyden !

**Comment by tleyden** [comment]
Thanks @ingenthr!

**Comment by tleyden** [comment]
@adamcfraser ran into issues:

> my AWS perf runs this morning against distributed_index were consistently failing with timeout-related panics.  I just ran a perf test without the set bulk commit, and it ran clean.

So this change was backed out, and issue remains open.

**Comment by tleyden** [comment]
I did a test run, and got:
- [changes feed](https://gist.github.com/tleyden/fa4cd09be87d45541ca7)
- [all docs](https://gist.github.com/tleyden/854bf963ad791e8e2acb)

And noticed that `ff85a0b8-b0eb-4037-a3a2-2872fbd80974` is present in all_docs, but missing from the changes feed.  Whereas `ffd61b19-db19-4cab-8b2e-35a161eac489` is present in both.

Vbucket ids:
- ffd61b19-db19-4cab-8b2e-35a161eac489 -> **983**
- ff85a0b8-b0eb-4037-a3a2-2872fbd80974 -> **576**  

For the `ffd61b19-db19-4cab-8b2e-35a161eac489` doc which was present in the changes feed, I found `_idx_entry:983:1` which was the only  `_idx_entry:983:*` doc with that doc id, which contains:

```
{
  "Sequence": 1,
  "DocID": "ffd61b19-db19-4cab-8b2e-35a161eac489",
  "RevID": "1-23a0884b732b27e0e268942f1567c70f",
  "Flags": 0,
  "VbNo": 983,
  "TimeSaved": "2015-11-06T16:38:00.356529495Z",
  "TimeReceived": "2015-11-06T16:38:00.359208342Z",
  "Channels": null,
  "Skipped": false,
  "IsPrincipal": false
}
```

For the `ff85a0b8-b0eb-4037-a3a2-2872fbd80974` docs which was missing from the changes feed, I found `_idx_entry:576:6` which contains:

```
{
  "Sequence": 6,
  "DocID": "ff85a0b8-b0eb-4037-a3a2-2872fbd80974",
  "RevID": "1-23a0884b732b27e0e268942f1567c70f",
  "Flags": 0,
  "VbNo": 576,
  "TimeSaved": "2015-11-06T16:38:07.991671244Z",
  "TimeReceived": "2015-11-06T16:38:07.988705218Z",
  "Channels": null,
  "Skipped": false,
  "IsPrincipal": false
}
```

**Comment by tleyden** [comment]
From @adamcfraser:

For a doc to show up on the _changes feed, four things need to be in place:
1. The index doc needs to be present
2. It needs to be present in an index block (binary, hard to introspect w/out the enhancement we discussed)
3. The channel clock for the channel needs to have reached the vb:seq
4. The stable sequence clock needs to have reached the vb:seq

**Comment by tleyden** [comment]
Add to _index/channels, something that shows the stable sequence in readable format.  This is on a branch somewhere, just need to find.

Something like this: https://gist.github.com/adamcfraser/90d847456c324d259afd

**Comment by tleyden** [comment]
Currently stuck on getting these errors:

```
2015-11-17T15:44:10.555-08:00 WARNING: GetBulkRaw() err:: Queue overflow. -- base.CouchbaseBucketGoCB.GetBulkRaw() at bucket_gocb.go:187
2015-11-17T15:44:10.555-08:00 WARNING: GetBulkRaw() err:: Queue overflow. -- base.CouchbaseBucketGoCB.GetBulkRaw() at bucket_gocb.go:187
2015-11-17T15:44:10.555-08:00 WARNING: GetBulkRaw() err:: Queue overflow. -- base.CouchbaseBucketGoCB.GetBulkRaw() at bucket_gocb.go:187
2015-11-17T15:44:10.555-08:00 WARNING: GetBulkRaw() err:: Queue overflow. -- base.CouchbaseBucketGoCB.GetBulkRaw() at bucket_gocb.go:187
2015-11-17T15:44:10.555-08:00 WARNING: GetBulkRaw() err:: Queue overflow. -- base.CouchbaseBucketGoCB.GetBulkRaw() at bucket_gocb.go:187
2015-11-17T15:44:10.555-08:00 WARNING: GetBulkRaw() err:: Queue overflow. -- base.CouchbaseBucketGoCB.GetBulkRaw() at bucket_gocb.go:187
2015-11-17T15:44:10.555-08:00 WARNING: GetBulkRaw() err:: Queue overflow. -- base.CouchbaseBucketGoCB.GetBulkRaw() at bucket_gocb.go:187
```

when running this functional test:

```
python -m pytest --capture=no functional_tests/test_single_user_single_channel.py
```

The fix requires two things:
- Gocb failure/retry handling as described in https://github.com/couchbase/sync_gateway/issues/1289
- A wrapper around gocb that minimizes these kinds of errors (@adamcfraser has work in progress on a branch)

The plan is to fix https://github.com/couchbase/sync_gateway/issues/1289 and verify that the functional tests pass, then rebase this branch off distributed_index after the fix.
