### ISSUE TITLE
Duplicates in _changes feed with distributed index with multiple users and multiple channels

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1248]
Using "Couchbase Sync Gateway/feature/distributed_index(d81a303)"

Test setup:

User A has channels ["ABC"] and pushes 2356 unique docs with channels: ["ABC"]
User B has channels ["NBC", "CBS"] and pushes 8198 unique docs with channels: ["NBC", "CBS"]
User C has channels ["ABC", "NBC", "CBS"] and pushes 2999 unique docs with channels: ["ABC", "NBC", "CBS"]

User A - http://XXX.XX.XXX.XXX:4984/db/_all_docs = 5355 (Expected)
User B - http://XXX.XX.XXX.XXX:4984/db/_all_docs = 11197 (Expected)
User C - http://XXX.XX.XXX.XXX:4984/db/_all_docs = 13553 (Expected)

http://XXX.XX.XXX.XXX:4985/db/_all_docs returns the expected 13553 docs

A issues a _changes request. I expect 5355 results and get 5355
B issues a _changes request. I expect 11197 results and get 11197

BUG
C issues a _changes request. I expect 13553 results and get 16493. There are duplicates in the _changes response.

_changes responses: https://gist.github.com/sethrosetter/00a83f897e8c0a396248. Logs have also been shared via email

**Comment by adamcfraser** [comment]
Fix is merged to feature/distributed_index.  @sethrosetter - can you close this issue once you validate the fix?
