### ISSUE TITLE
Potential test scenarios for DB online/offline

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1250]
This is a list of potential test scenarios for DB online/offline changes.

**Comment by ajres** [comment]
Start SG with bucket in online state (no offline config property), make REST API calls against DB - expected result RAST API calls are successful

Start SG with bucket in online state setting Db 'offline' config property to false),  make REST API calls against DB - expected result REST API calls are successful

With DB in online state, no active RAST API calls, take DB offline, expected result _offline call returns status 200, make REST API calls against DB, expected result returns status 503.

With DB in online state, make REST API call to get DB runtime details /db/, expected result 'state' property with value 'Online' is returned.

With DB in online state, active _changes (try longpoll, continuous, websockets feeds), take DB offline, expected result _offline call returns status 200, all active changes feeds are closed in a controlled way returning to client, longpoll should return a valid last sequence value.

Start SG with bucket in offline state setting DB 'offline' config property to true),  make REST API calls against DB - expected result RAST API calls fail with 503

With DB in offline state, make REST API calls against DB for supported offline operations, GET db status, PUT DB config, expected result calls should return status 200.

With DB in offline state, make REST API call to get DB runtime details /db/, expected result 'state' property with value 'Offline' is returned.

With DB in offline state, make REST API _online call against DB,  expected result _online call should return status 200.  Make REST API calls against DB - expected result REST API calls are successful

With DB in offline state, make REST API _online call against DB with a delay of 15 soconds,  expected result _online call should return status 200.  Make REST API calls against DB - expected result REST API calls will fail status 503. Wait until 15 second delay has elapsed, make REST API calls against DB - expected result REST API calls will succeed with status 200.

With DB in online state, put a large number of docs (enough to cause _resync to run for 10-15 seconds), put DB offline, run _resync, attempt to bring DB online while _resync is running, expected result _online will fail with status 503, when _resync is complete, attempt to bring DB _online, expected result _online will succeed, return status 200.

While DB is running _resync make REST API calls against DB for supported offline operations, GET db status, PUT DB config, expected result calls should return status 200.

With DB running a _resync, make REST API call to get DB runtime details /db/, expected result 'state' property with value 'Resyncing' is returned.

With DB in online state, put new valid DB config, take DB offline, bring DB online. Expected result DB has new config applied.

With DB in offline state, put new valid DB config, bring DB online. Expected result DB has new config applied.

With DB in online state, put new invalid DB config, take DB offline, bring DB online. Expected result DB fails to come online, error status is returned.

With DB in offline state, put new invalid DB config, bring DB online. Expected result DB fails to come online, error status is returned.

Configure WebHooks for online/offline events, With DB in online State, take DB offline, expected result a DBOffline event is sent to the configured webhook endpoint

Configure WebHooks for online/offline events, With DB in offline State, take DB online, expected result a DBOnline event is sent to the configured webhook endpoint

With DB in online state, simulate loss of TAP feed, expected result the DB should be taken offline. 

Configure WebHooks for online/offline events, with DB in online state, simulate loss of TAP feed, expected result the DB should be taken offline, a DBOffline event is sent to the configured webhook endpoint

**Comment by ashvindersingh** [comment]
Thanks @ajres ! updated our Test scenarios list: 
https://docs.google.com/spreadsheets/d/1nlba3SsWagDrnAep3rDZHXHIDmRH_FFDeTaYJms_55k/edit#gid=1856069956
