### ISSUE TITLE
[Distributed index] Sporadic errors in tests

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1257]
I'm seeing data race errors on the distributed index branch:
- [jenkins](http://mobile.jenkins.couchbase.com/view/Sync_Gateway_Dev/job/sync-gateway-dev-build/335/console)
- [local](https://gist.github.com/tleyden/f90941bceca1779eb19e)

I'm not sure when they were introduced.

I'm also seeing sporadic errors when running locally without the race detector:

```
$ ./clean.sh && ./test.sh
2015/11/03 13:07:36 Changes entry: &{9 doc-9 false {} map[] [map[rev:1-a]] <nil> false}
2015/11/03 13:07:36 Miscount

    change_cache_test.go:462
    assert.True(t, err == nil)

    change_cache_test.go:463
    assert.Equals(t, len(changes), 9)

    expected: 9
         got: 8
2015/11/03 13:07:36 verifyChangesSequences: changes size (8) not equals to sequences size (9)

    change_cache_test.go:464
    assert.True(t, verifyChangesSequences(changes, []uint64{1, 2, 5, 6, 3, 4, 7, 8, 9}))
--- FAIL: TestLowSequenceHandling (0.58s)
    assert.go:31:
    assert.go:31:
    assert.go:31:
```

and:

```
kv_change_index_test.go:166
    assert.Equals(t, len(entries), 3)   

    expected: 3
         got: 1
```

**Comment by tleyden** [comment]
As mentioned in [Introducing the Go Race Detector](http://blog.golang.org/race-detector), it's possible to detect race conditions during live program run, not just during unit tests.   

I was able to reproduce data race warnings in running gateload against a live running sync gateway server via these steps:
- Modify `run.sh` to add the `-race` flag, eg: `./go.sh run -race src/github.com/couchbase/sync_gateway/main.go "$@"`
- `./run.sh config.json`
- Run gateload and point to local server

and saw the following race detector warnings:
- https://gist.github.com/tleyden/202f2bfe0fbcfdfce735
- https://gist.github.com/tleyden/d5b0e70d9bb1ac823ea7

**Comment by adamcfraser** [comment]
Filed #1260 and #1261 for the specific race errors.

**Comment by adamcfraser** [comment]
The main source of failure appears to be when waiting for writes to get indexed.  Need an enhancement in the test framework to waitForIndexed, instead of doing a time.Sleep().
