### ISSUE TITLE
Race condition in sequence hasher cache

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1260]
Running SG with -race found a race condition when reading/writing cachedClocks after retrieving from hash cache.

Original ticket:
https://github.com/couchbase/sync_gateway/issues/1257#issuecomment-153493476

Details here:
https://gist.github.com/tleyden/202f2bfe0fbcfdfce735

It looks like the issue isn't with obtaining the actual cache entry, but when working with the cachedClocks collection within that entry.

**Comment by tleyden** [comment]
After this is fixed, we should manually run the functional tests against sync gateway built with -race to see if there are more pending issues.  Feel free to re-assign this ticket to me for that.

**Comment by adamcfraser** [comment]
Fix included in PR #1396.  Assigning back to @tleyden as requested.

**Comment by tleyden** [comment]
Closing this -- opened a separate ticket to re-run the functional tests with the -race flag.  https://github.com/couchbase/sync_gateway/issues/1400
