### ISSUE TITLE
Sync Gateway does not send Heartbeat packets through nginx SSL reverse proxy

### ISSUE THREAD

**Issue by alex7egli** [couchbase/sync_gateway#1263]
We have nginx version 1.8.0 running on Ubuntu 12.04 and sync gateway v1.1.1. Nginx is configured as a reverse proxy and it handles SSL for us. When we create a non-websockets pull replicator (pullReplicator.customProperties = {@"websocket":@0};) with Couchbase Lite iOS v1.1.1 it replicates all the documents a user has access to correctly, but it never receives any heartbeats from the server to keep the replication connection open. If we disable SSL (comment out the ssl lines in the nginx config below and change it to listen on port 80) on the server then we see it sending heartbeat packets (using tcpdump) and we see log messages on the device showing it received the heartbeat packets. What we expect to see with SSL enabled is the heartbeat packets are sent over port 443 to the client and the client receives them and keeps the connection open.

Nginx config:

```
server {
    listen  80;
    server_name host.cloudapp.net;
    return      301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;

  ssl on;
  ssl_certificate /etc/nginx/ssl/pushdev.crt;
  ssl_certificate_key /etc/nginx/ssl/pushdev.key;
  server_name host.cloudapp.net;
  client_max_body_size 40M;

  root /home/azureuser/PushWeb/app;
  index index.html index.htm;

  # Make site accessible from http://localhost/
   server_name localhost;

  location / {
    expires 5m;
    try_files $uri $uri/ =404;
  }

  location /dbws/ {
    proxy_pass_header Accept;
    proxy_pass_header Server;
    keepalive_requests 1000;
    keepalive_timeout 360s;
    proxy_read_timeout 360s;
    proxy_pass http://localhost:4984/todos/;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
  }
}
```

**Comment by tleyden** [comment]
Possibly related: https://github.com/couchbase/sync_gateway/pull/971#issuecomment-126750011

**Comment by ajres** [comment]
#971 was not tested against an nginx instance doing SSL termination, so it could have been present at that time.

**Comment by adamcfraser** [comment]
Closing based on age, and inability to reproduce - there are several known scenarios where heartbeats are working successfully with nginx/SSL.
