### ISSUE TITLE
Log a warning or fail to launch with non optimal configurations

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1268]
Scenarios that may result in unexpected user experience / bugs. 
- [ ] multiple dbs targeting the same bucket
  Data is shared across databases and the user may expect the data to be isolated at the database level.
- [ ] multiple index writers targeting the same bucket 
  Not recommended. Each db should have it's own bucket to write indexes to

These scenarios could be caught when parsing the configuration and handled during start.

**Comment by zgramana** [comment]
Related to #1121

**Comment by adamcfraser** [comment]
The first case is being covered by CBG-630, the latter is obsolete.
