### ISSUE TITLE
escaping for backticks in config function

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#1270]
currently if you need a literal backtick in a json string, you have to write it like

``` json
{
  "key" : "value with \u0060backticks\u0060"
}
```

we should do something with double backticks or something... actually I'd like add TOML as an optional config format, since it has JSON semantics. https://github.com/toml-lang/toml

**Comment by adamcfraser** [comment]
Closing based on age - can reopen if specific use cases are identified.
