### ISSUE TITLE
TOML format for config?

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#1271]
https://github.com/toml-lang/toml has multi line string capabilities and other things we might want, while maintaining JSON compatibility.

**Comment by jchris** [comment]
There are a bunch of go options https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=toml%20golang

**Comment by adamcfraser** [comment]
Not critical to implement.
