### ISSUE TITLE
[Distributed index] Update perfcluster-aws to support mixed mode (mix of index-writers and non-writers)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1273]
In order to be able to gather performance data as in https://github.com/couchbase/sync_gateway/issues/1272, the perfcluster work needs to be able to support "mixed mode" where:
- Certain instances are tagged as index writers, and other instances are non-writers.  
- The gateload/gatling load generators should only be pointed at the non-writers 
- The index writers will need to have their JSON config changed to set indexwriter = true (the rest of the config would be identical)

**Comment by sethrosetter** [comment]
Per conversation with @tleyden 
- [ ] Add tag_sg_index_writer. 
- [ ] Ability to specify the --num-sync-gateway-writers could by done via provision_cluster.py

```
python provision_cluster.py --num-sync-gateway-writers=3
```
