### ISSUE TITLE
[Config] allow sync functions to be stored in an external file

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#1274]
Perhaps the can be referenced with a path as an alternate option, like `"sync" : "@myfunction.js"` as a relative path from the config file location.

**Comment by jchris** [comment]
Inspired by this forum post: https://forums.couchbase.com/t/feature-request-externalize-sync-function/5803

**Comment by SebastianBO** [comment]
Great feature.

**Comment by zgramana** [comment]
Good feature. The value for the "sync" key would be [a JSON pointer](http://tools.ietf.org/html/draft-ietf-appsawg-json-pointer-07). This way, we can resolve potentially resolve the link when the value is PUT via the REST API.

**Comment by npomfret** [comment]
+1 It would be very nice to have it in a separate file

**Comment by paulharter** [comment]
please - js in the json gives me vertigo

**Comment by programmarchy** [comment]
Another +1. Having the sync function in a separate file makes unit testing a bit easier. For now, munging my config with a javascript file in a build step.

**Comment by iamdanthedev** [comment]
Any updates on that?

**Comment by tleyden** [comment]
@rasdaniil I haven't heard anything internally about this being in progress, but if I do I will update the ticket.  I agree 100% that it is painful to have the javascript embedded in the json config.

**Comment by iamdanthedev** [comment]
@tleyden Thanks for the information!

**Comment by adamcfraser** [comment]
Moved to https://issues.couchbase.com/browse/CBG-660
