### ISSUE TITLE
Jenkins job to build PR's and run functional tests

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1277]

**Comment by zgramana** [comment]
- Build the PR.
- Run the Python functional test suite.

**Comment by michaelkwok** [comment]
I have created the Jenkins job which will add build results as comments at the bottom of the PR.  The Jenkins plugin currently indiscriminately triggered on every PR notification from Github resulting in excessive builds even if there is no code changes on the PR. Jenkins currently will trigger on these PR actions: opened, closed, assigned, labeled or synchronized. I am investigating to see if I can get Jenkins to triggered on opened and synchronized PR.

**Comment by adamcfraser** [comment]
https://issues.couchbase.com/browse/CBLT-392

**Comment by bbrks** [comment]
Pretty much already done - except kicking off the QE test framework. Could be a nice enhancement for the Jenkins pipeline, but will close out this issue for now.
