### ISSUE TITLE
non string channel names should raise error

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#1278]
This should error instead of creating an channel called `b,g`. Maybe treating 4 as "4" is ok?

``` javascript
function(doc){
  channel(["a", ["b", "g"], "c", 4])
}
```

**Comment by jchris** [comment]
the [cast to string here](https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/channels/sync_runner.go#L218) is the culprit. need to audit and make sure no other callers are depending on the bug behavior

**Comment by jchris** [comment]
I think this is gonna mean refactoring `ottoValueToStringArray` to a two-valued return type with error, as well as the corresponding changes up the callchain. I think it's all contained in one file.

**Comment by adamcfraser** [comment]
Moved to CBG-714.
