### ISSUE TITLE
configServer option and backticks for the sync function break

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#1281]
Greetings!

I'm trying to use the configServer option in the sync gateway config, however, when I define the sync function as I normally do surrounding the whole thing with backticks, the sync server tries to parse the whole returned configuration as simple json and breaks.

The documentation for this option is a little sparse. Am I missing anything or is creating a configuration that includes the sync function from a server not supported?

Thanks!

**Comment by adamcfraser** [comment]
This looks like a bug - the direct json unmarshalling being done at https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/rest/server_context.go#L489 should instead be calling ConvertBackQuotedStrings first.

Creating a config that includes a sync function from a server should definitely be supported.  Until we can deliver a fix, I expect you can workaround by formatting your sync function to a single line and escaping any quotes/etc that would break the json.  I understand this is a painful workaround, though - I'll review internally tomorrow to try to get a quick fix scheduled.

**Comment by ghost** [comment]
Thanks!

**Comment by ajres** [comment]
Sync Gateway now calls ConvertBackQuotedStrings before using the config from the Config Server. This will allow a sync function embedded in back quotes to be defined.

See PR #1303
