### ISSUE TITLE
access() call accepts either user names or role identifiers

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#1283]
This means in a common case where a channel management document might end up calling something like this in the sync function:

``` javascript
access(doc.members, doc.channel)
```

Unless the developer also validates that the members list doesn't contain any funny business like `role:public` etc in the list, there is the potential for injection attacks that open up an existing group more than the developer planned for.

It might be more secure to have `roleAccess()` and `userAccess()` calls, so that developers who are calling them with user data, don't accidentally get more than they bargained for. This can be implemented easily today by [writing some javascript in the sync function wrapper](https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/channels/sync_runner.go#L24), and then documenting the `access()` call as deprecated.

**Comment by jchris** [comment]
I went ahead with an implementation because we can make the new API available without removing the old one, at first. I'd like to use these more secure calls in the sync function pattern recipes we put together.

**Comment by jchris** [comment]
Part of the reason I wrote code is to get in touch with other stuff, like the usage in `role()` that [also exposes the "role:" prefix](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/sync-gateway/sync-function-api-guide/routing/index.html#role) to developers. If we go down this road there are probably a few other APIs we'd need to touch.

**Comment by adamcfraser** [comment]
Closing based on age.  In general the input to access() should be validated within the sync function by developers, even in the case of non-role grants, so I don't think this issue on its own represents a security concern.
