### ISSUE TITLE
Adding new node into CB-cluster causing a document to miss revisions

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1285]
Found on CB-Build: 3.1.1-1807
SG: feature/Distributed-Index branch

Setup: 
- 3 node CB cluster with two buckets: Data and Index bucket
- 3 SG, 2 SGs writers and 1 reader

Steps to reproduce: 
- Create 100 docs with 100 revisions for a single user
- While docs are getting updated
- Add new node into the CB-Cluster
- Rebalance and let the Rebalance operation complete
- Expecting to find 100 revisions for 100 docs

Observation:
- Found one document- test-69 to have only 63 revisions. All the remaining docs had all (100) revisions.
- Got 500 internal server error for doc test-69. 

SG-logs: attached with ticket: https://issues.couchbase.com/browse/CBL-41
SG-Config: https://gist.github.com/ashvindersingh/946d9631b35a2a2f7706

**Comment by adamcfraser** [comment]
Is that the full/correct Sync Gateway log? There are only 1100 total PUT /db/ operations in the log, which looks more like a test of 10 revisions for 100 docs.

**Comment by ashvindersingh** [comment]
Sorry inadvertently attached wrong logs. I have now fixed and attached the correct logs. 

I also re-ran the test and found the same issue. Appended the new logs with correct logs. 

1st run correct logs:https://issues.couchbase.com/secure/attachment/28019/2015-11-13-00-27-04-sglogs.zip

2nd run logs: https://issues.couchbase.com/secure/attachment/28018/2015-11-13-02-22-14-sglogs.zip
in ticket:  https://issues.couchbase.com/browse/CBL-41

**Comment by adamcfraser** [comment]
The PUT for doc test-69 is failing (and returning a 500 error to the test client).  This looks like a valid transient error during rebalance, and there's no data loss (i.e. the client is appropriately notified that the write failed).  

I assume the test client isn't doing any retry when an update fails - it looks like it's terminating the updates for that doc on error (there aren't any subsequent write attempts by the client for test-69 after the error).

This doesn't look like a distributed-index issue (the failure is happening during basic write), and more specifically I'm not sure it's a problem for real clients - I'd expect them to resubmit the failed update on next replication.

**Comment by adamcfraser** [comment]
Closing - related to deprecated functionality.
