### ISSUE TITLE
Removing a node from CB-cluster and rebalance causing writer SG to crash

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1286]
Found on CB-Build: 3.1.1-1807
SG: feature/Distributed-Index branch

Setup:

3 node CB cluster with two buckets: Data and Index bucket
3 SG, 2 SGs writers and 1 reader
Steps to reproduce:
- Create 100 docs with 100 revisions for a single user
- While docs are getting updated
- Remove node from the CB-Cluster
- Rebalance 
- Expecting to continue to update Docs on SG

Observation:
- One of index writer SG node serving the client crashed. 
- Got max retries exceeded exception

Snippet of exception got from scripts:

> Generated an exception while updating doc_id:test-14 HTTPConnectionPool(host='172.23.105.59', port=4984): Max retries exceeded with url: /db/test-14 (Caused by <class 'httplib.BadStatusLine'>: '')
> Generated an exception while updating doc_id:test-17 HTTPConnectionPool(host='172.23.105.59', port=4984): Max retries exceeded with url: /db/test-17 (Caused by <class 'httplib.BadStatusLine'>: '')
> Generated an exception while updating doc_id:test-16 HTTPConnectionPool(host='172.23.105.59', port=4984): Max retries exceeded with url: /db/test-16 (Caused by <class 'socket.error'>: [Errno 61] Connection refused)

sg logs: https://issues.couchbase.com/browse/CBL-41

**Comment by adamcfraser** [comment]
The SG failure is the known gocb timeout issue.  Will be addressed with
https://github.com/couchbase/sync_gateway/issues/1289

**Comment by zgramana** [comment]
Will move to review column so that we can verify  #1289.

**Comment by zgramana** [comment]
@ashvindersingh will re-run test (and check it in).

**Comment by ashvindersingh** [comment]
Tested with latest binary 1.2.0-53. This issue is fixed and did not observe the crash
