### ISSUE TITLE
Fix Unit Tests that are failing on Go 1.5

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1290]
With `go version go1.5.1 linux/amd64`:

```
$ git checkout feature/distributed_index OR master
$ ./test.sh
```

https://gist.github.com/tleyden/ea32807818c065086647

With `go version go1.4.2 linux/amd64`:

```
$ git checkout feature/distributed_index OR master
$ ./test.sh
```

https://gist.github.com/tleyden/e76eabe6f8a69d89ceab

Seems to be 100% reproducible.

**Comment by tleyden** [comment]
Related build ticket: https://issues.couchbase.com/browse/CBD-1688

**Comment by tleyden** [comment]
@adamcfraser yes, it's reproducible on master as well

**Comment by tleyden** [comment]
@ajres going to re-assign to you since you are looking into similar issues already

**Comment by tleyden** [comment]
@ajres I've asked @michaelkwok to update the Jenkins jobs to use Go 1.5

**Comment by ajres** [comment]
Jenkins Jobs now use GO version 1.5.2 by default

**Comment by ajres** [comment]
Closing this ticket, Unit tests, deadlocks and data race failures have been resolved and master builds are completing without error.
