### ISSUE TITLE
Viability of enhancement to the sync function and channels

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#1291]
Greetings!

Suppose I have the following documents:
{ '_id': 'doc_1', 'public': true, 'children':['doc_2', 'doc_3']}
{ '_id': 'doc_2', 'parent': 'doc_1' }
{ '_id': 'doc_3', 'parent': 'doc_1' }

Is it viable to add the ability to write a sync function that would publish doc_2 and doc_3 to a channel from doc_1 in the following manner?: 

```
function(doc) {
    if (doc.parent) { return; }
    if (doc.public) {
        channel('published');
        if (doc.children && doc.children.length > 0) {
            for (i = 0; i < doc.children.length; i++) {
                channel(doc.children[i], 'published');
            }
        }
    }
}
```

I would like the ability to publish "child" documents to a channel _from_ the parent and I didn't know if that is a viable feature to be implemented. I don't believe this violates any of the rules behind the sync function and would be indescribably useful.

Thanks!
Justin

**Comment by Fujio-Turner** [comment]
Could we do this in CB Eventing?
with `onUpdate(doc,meta)` you can do more things like N1QL/FTS , move doc(s) to second bucket and etc.
 I don't want SG's Sync Function to HAVE to do multiple write operations for a given document write.
In the above example what if you had 100s of child docs. Eventing you can more control over the retry methods and write more of the business logic in the Eventings framework to do complex operations AFTER the initial write from sync gateway.

**Comment by adamcfraser** [comment]
Closing based on age.  In general there are a number of reasons why documents can only modify their own channels (primarily to do with race conditions around concurrent updates, and the fact that changing a document's channels requires a new revision to be calculated for that document.  Eventing would be one approach to trigger multiple underlying document updates from a single mutation.
