### ISSUE TITLE
API option to pass channels as JSON list

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#1292]
Currently we pass our list of [channels as a comma delimited string](https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/rest/changes_api.go#L94) but encoding it as a JSON array would be more in line with our view APIs etc, and allow us to use any character in channel names, completing the fix in #656

**Comment by jchris** [comment]
Once we fix this we can start on https://github.com/couchbase/couchbase-lite-ios/issues/981

**Comment by adamcfraser** [comment]
To handle this in a POST to _changes, we'd need to fix it [here](https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/rest/changes_api.go#L484), which I agree we should definitely do.

Sending JSON as a URL parameter on an HTTP GET feels a bit clunkier, though.  Have you seen any best practices around sending lists as parameters?  I've seen a few recommendations for channel=ABC&channel=BBC&channel=A,B , but haven't found clear consensus on the preferred approach.

**Comment by jchris** [comment]
We do it in the view query API for start key and endkey

**Comment by adamcfraser** [comment]
We do the same thing to support JSON encoding of the Since value in the _changes GET, but in that case we're supporting both simple URL string and JSON.

I suppose we need to be backwards-compatible for people already using comma-delimited strings here as well, so we'd have to support both approaches here also.

**Comment by jchris** [comment]
We could do it with a different name maybe. At the very least it should be
doable to detect the leading bracket

**Comment by adamcfraser** [comment]
Agreed.  I just reread the discussion here:
https://blogs.dropbox.com/developers/2015/03/json-in-urls/
and I came away less squeamish about JSON in URL parameters, particularly when it's solving a particular problem (like commas in channel names).

**Comment by adamcfraser** [comment]
Closing based on age, and because the 2.x replicator doesn't leverage the REST API for replication.
