### ISSUE TITLE
Ability to filter by a channel without having access to it

### ISSUE THREAD

**Issue by alex7egli** [couchbase/sync_gateway#1296]
We want to do time based filtering for replication so we don't end up replicating a huge amount of historical data when a user logs in, but channels are the only form of filtering available right now and they are used only for access control. Having public filter channels that do not grant access to a document but do allow you to filter replication would be very helpful.

Example: We only want to replicate a 3 week window of data, but currently that means we need a channel for each user for each week (e.g. user1_yyww) and then the owner that is actually replicating this data has to have access to 3 channels for every user they administer(which can be hundreds of users, and thus thousands of channels). If we had public filter channels (e.g. just yyww) that were unrelated to access then we could just assign the correct week channel to each document in that week for filtering, and the correct user channel for each document for access control, and then the administrator just needs to have the user channels in their access list. When replicating we could specify the public week filter channels (e.g. 1525, 1526, 1527 for the 25th, 26th, and 27th weeks of 2015), instead of 3 channels for every user we have access to.

**Comment by jchris** [comment]
OK I think I see what you want to do, you want to be able to grant an admin access to all channels that have a form like `user1_***`. It's starting to feel like some sort of hierarchal namespace would fit here.

With the current API, you could something like create a role per user, something like "admin_for_user1" and then each time you create a user1_yyww channel, you grant that role access to it. That way the admin has access to all of the user's channels, but only has one role per user. And the role can be granted to multiple admins if you want.

You would still need to specify the 3 channels for every user that go with the current week, but that is managed at the client, not the sync function, by using the [channels parameter.](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/replication/replication/index.html)

**Comment by alex7egli** [comment]
Sorry, I worded mine badly. It is not admins that need access to multiple users, it is another generic user type that we have a lot of. Is there any limit on roles? Because we could go with that route, we would just end up with an unlimited number of roles.

**Comment by adamcfraser** [comment]
Closing based on age.  The general functionality makes sense (time-based filtering specifically, or non-security based filtering more generically), but isn't currently on the roadmap.
