### ISSUE TITLE
Do automatic tuning of num_shards based on cluster topology 

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1297]
Making the default SG config simpler. 
"feed_params" : { "num_shards":64}

The user can still use and over write the above value if the need arises.

**Comment by adamcfraser** [comment]
I'm on the fence about whether we should have a default value for num_shards.

num_shards represents the maximum number of index writers you can deploy to your cluster.  Changing this value (to increase the number of index writers) is a very expensive operation - it requires flushing your index bucket and rebuilding from scratch.  (we're considering enhancements to make this less painful/manual, but they aren't planned for the initial release).

There's also additional performance overhead as num_shards increases, as it results in more documents being read during channel index evaluation.  So it's not as simple as "set it to 1024 and be done".

For this reason, I think it's important for customers to put some thought into the value they want to use for num_shards.  Obviously this requires the scaling guidelines documentation to be in place to help customers make the decision.

**Comment by adamcfraser** [comment]
Decision has been made to set default value to 64, and have the field non-mandatory.
