### ISSUE TITLE
Metadata purge interval not work

### ISSUE THREAD

**Issue by sebastian989** [couchbase/sync_gateway#1304]
HI, I am trying to delete the tombstones or deleted documents, I am setting the Metadata purge interval with a value of 0.04 = 1H but notting ever happen and the tombs are always present and there are a lot of these now,

**Comment by zgramana** [comment]
Can you explain in more detail what problem you are trying to solve, and the steps you're taking to solve it?

**Comment by ArihantRk** [comment]
Hi zgramana, I think this is related couchbase server. i am also facing same issue. I have below setup
couchbase : 4.1
sync gateway : 1.2
i am using rest api to delete the documents. and whenever i delete document,it will create new revision with attribute _deleted=true(which is tomstones with only meta data). I have set compaction at cluster level with meta data purge interval = 0.04. whenever compaction runs older revisions are getting deleted permanently from couchbase . but tombstone documents are getting deleted from server.

As per documentation , these tombstones should get delete during autocompaction.

**Comment by JFlath** [comment]
Reading over this, it sounds like this is what's discussed in #2498. I intentionally did that as a separate issue, as I think this one blurs the line a bit between CB and SG. At the risk of favouritism, I'd propose that this can be closed as a duplicate of #2498 :P.

**Comment by JFlath** [comment]
As a side note, perhaps the docs can be improved here, as it can be awkward to grasp the differences of CB tombstones and purges with SG tombstones and purges...

cc @jamiltz - Let me know if you think this is a good idea, I've got some text that could probably be massaged into the docs :)

**Comment by adamcfraser** [comment]
@JFlath Agreed - closing this in favour of #2498.

**Comment by jamesnocentini** [comment]
@JFlath absolutely, that would be great. Looking at the SG guides, it sounds like this is a topic that could fit on the deployment considerations page. https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/deployment/index.html
by having a new section called something like "Tombstone management".

Let me know if you are thinking of somewhere else in the docs.
