### ISSUE TITLE
Getting error "Failed to establish a new connection" with Sync gateway when increased the throughput

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1305]
Setup:
CBS: 3.1.1
SG: Distributed Index branch

sync gateway logs: https://issues.couchbase.com/browse/CBL-43

Scenario: 
- A single user making 100 revisions on 100 docs on single channel. 
- Install and configure sync-gateway-testcluster
- ensure lib/settings.py has MAX_REQUEST_WORKERS=100
- run https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/functional_tests/test_single_user_single_channel_doc_updates.py
  as : python -m pytest --capture=no functional_tests/test_single_user_single_channel_doc_updates.py
- test script starts getting error of the type: 

Generated an exception while updating doc_id:test-82 HTTPConnectionPool(host='172.23.105.59', port=4984): Max retries exceeded with url: /db/test-82 (Caused by NewConnectionError("<requests.packages.urllib3.connection.HTTPConnection object at 0x11802ce10>: Failed to establish a new connection: [Errno 49] Can't assign requested address",))
Generated an exception while updating doc_id:test-57 HTTPConne

ctionPool(host='172.23.105.59', port=4984): Max retries exceeded with url: /db/test-57 (Caused by NewConnectionError("<requests.packages.urllib3.connection.HTTPConnection object at 0x117f13d90>: Failed to establish a new connection: [Errno 49] Can't assign requested address",))

Observation some docs missing revisions

This error does not occur when the MAX_REQUEST_WORKERS=5. The script runs to completion with no errors.

**Comment by adamcfraser** [comment]
"Can't assign requested address" suggests that your client is running out of ports to issue the request.  Based on this, I'd call this a test script issue, and not a Sync Gateway issue.

**Comment by zgramana** [comment]
@ashvindersingh will re-run the test with an update to the Python test logic that closes the REST connection.
