### ISSUE TITLE
sync_gateway "CacheSkippedSeqMaxWait" parameter value taking default value, not able to update

### ISSUE THREAD

**Issue by sudhanitk** [couchbase/sync_gateway#1312]
CacheSkippedSeqMaxWait parameter is set to default value i.e. 1 hr. Not able to update the interval for CacheSkippedSeqMaxWait parameter.

CacheSkippedSeqMaxWait value is set in syncgw config file as below and restarted syncgw but not applying the update interval.
 "databases":{
      "pttdata":{
         "server":"http://10.3.2.23:8091",
         "bucket":"pttdata",
         "revs_limit" : 5,
         "CacheSkippedSeqMaxWait":300000
............

After setting parameter value, SG logs still shows as 
2015-11-23T23:24:47.372-06:00 Cache: Initializing changes cache with options {CachePendingSeqMaxWait:5s CachePendingSeqMaxNum:10000 CacheSkippedSeqMaxWait:1h0m0s}

Let us know if any changes required or how to set the parameter value.

**Comment by adamcfraser** [comment]
There's an error in the documentation for that property - I'll have that fixed.

That property should be set as the `max_wait_skipped` property in the cache settings.  e.g.:

```
"databases":{
"pttdata":{
"server":"http://10.3.2.23:8091",
"bucket":"pttdata",
"revs_limit" : 5,
"cache": {
     "max_wait_skipped": 300000
 }
```

**Comment by adamcfraser** [comment]
Fixed with https://github.com/couchbaselabs/couchbase-mobile-portal/pull/276
