### ISSUE TITLE
Support _doc_ids filter when using distributed index

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1316]
The fix for #545 uses the _all_docs model to retrieve the latests revision for each docID, it then looks up the sequenceID associated with that revison to return in the changes feed.

In distributed index a revision no longer has an associated sequence ID.

It may be necessary to add a reverse index to allow a sequence ID to be retrieved for a given docID/revID.

**Comment by ajres** [comment]
The Fix for 5#545 uses the _all_docs model to retrieve the latests revision for each docID, it then looks up the sequenceID associated with that revison to return in the changes feed.

In distributed index a revision no longer has an associated sequence ID.

It may be necessary to add a reverse index to allow a sequence ID to be retrieved for a given docID/revID.

**Comment by tleyden** [comment]
Two steps:
- [ ] Disable this on distributed index and return 500 error
- [ ] Implement this (more work)

**Comment by zgramana** [comment]
Issue #993 makes this much easier to implement this.

**Comment by zgramana** [comment]
Will be a known-issue in the 1.2 release notes.

**Comment by djpongh** [comment]
Moved to accel repo: https://github.com/couchbaselabs/sync-gateway-accel/issues/217
