### ISSUE TITLE
Non-writer node of SG crashes when launched with other index writer node sync gateways

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1317]
Test setup topology:
- 3 Node Couchbase server running build 3.1.1-1807
- 3 Sync gateways with 2 as index writers and 1 as non writer
  - SG-1 and SG-2 as writers. SG-3 is non-writer. 
- Couchbase server having three buckets: Data bucket, Index bucket and cbgt bucket. 
  Using SG  build / branch = feature/distributed_index , dev-build-number=365

Test Scenario Steps: 
- Git clone and setup https://github.com/couchbaselabs/sync-gateway-testcluster
- Execute script by running : https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/functional_tests/test_single_user_single_channel_doc_updates.py
  as python -m pytest --capture=no functional_tests/test_single_user_single_channel_doc_updates.py 

Expected Result: 
- The test script runs to successful completion

Observed output:
- Test script fails at the initialization setup with following output:

```
> config = <closed file '/Users/ashvinder/mobile_testing/sync-gateway- testcluster/conf/sync_gateway_default_functional_tests.json', mode 'r' at 0x10a48f300>
>   ???
> lib/cluster.py:96: 
>
> script_name = 'reset-sync-gateway.yml', extra_vars =  'sync_gateway_config_filepath=/Users/ashvinder/mobile_testing/sync-gateway-testcluster/conf/sync_gateway_default_functional_tests.json'

>   ???
 E   SystemExit: 1
```

Please see the attached logs: 
https://issues.couchbase.com/browse/CBL-44

The reader node 172.23.106.212 error logs contains the panic and stack trace. 

 Here is the config file for the reader node: 
 https://gist.github.com/ashvindersingh/940ea367f73efc2e3891

Here is the config files for the index writer nodes: 
- https://gist.github.com/ashvindersingh/9e7bb8425951d8d1c4b3
- https://gist.github.com/ashvindersingh/adef02f241077ab2d4c1

CBGT output:
https://gist.githubusercontent.com/ashvindersingh/ef5e920e6adc2689d113/raw/7a8d9cdf2b0bf96b61a7dd63b9ad05dc477884c4/cbgt.json

**Comment by tleyden** [comment]
I ran into a similar sounding issue here: https://github.com/couchbase/sync_gateway/issues/1289#issuecomment-160743751

**Comment by ashvindersingh** [comment]
Gist for the crashing non-writer sync gateway having the ip 172.23.106.212: https://gist.github.com/anonymous/bfd04f169b6542df1df2#file-sync_gateway_error-log-L341

**Comment by tleyden** [comment]
@sethrosetter I tried to kick off a functional test against my branch with a potential fix, but the functional test failed.  Think it might be an error with the functional tests:

http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/124/console

**Comment by tleyden** [comment]
@sethrosetter as a smoke test I kicked off the functional tests against distributed_index http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/125/

**Comment by tleyden** [comment]
Fixed via https://github.com/couchbase/sync_gateway/pull/1322
