### ISSUE TITLE
2-way replication setup between CouchDB and Couchbase 2.0

### ISSUE THREAD

**Issue by guptam** [couchbase/sync_gateway#132]
Hi,

Is it possible to setup a 2-way replication between couchdb and couchbase server? I was able to setup one way replication from CouchDB to Couchbase Server using Sync Gateway, but couldn't find anything that show steps for performing the synching of Couchbase Server back to CouchDB.

I am trying to implement a simple scenario:
- All my documents from CouchDB should get replicated to Couchbase multi-node Cluster (This is done).
- Subset of documents from Couchbase server should get replicated back to local CouchDB database. Let's say, subset can be identified from the document structure itself or maybe using some partition logic on keys. 

If you could provide some pointer/direction for the second scenario, it would be a great help.

Thanks in advance,
Manish

**Comment by alexalexalex96** [comment]
@guptam how can I setup a replication from CouchDB to Couchbase Server using Sync Gateway
