### ISSUE TITLE
Consolidate feed_params and channel_index in config

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1321]
Configuration of the channel index will be more straightforward if we move all configuration into the channel_index section of the config.  Currently the feed_params are only relevant for distributed index writers.

We should move the feed_params.num_shards property under the channel_index section of the config, as it's only relevant to  channel_index writers.

**Comment by tleyden** [comment]
@sethrosetter just a reminder that you guys will need to update your configs once this change is made.
