### ISSUE TITLE
Validate CBGT registration to make sure DB configured for all CBGT indexes

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1323]
## Problem
- You've got SG1 acting as an index writer for two dbs: DB1, DB2
- You add SG2, which is an index writer for DB1, and has no configuration for DB2

Will currently crash because SG2 will get the DCP stream for DB2 and not know how to handle the messages.
## Proposed Fix

Panic when you get a CBGT registration request for a DB that either (a) doesn't exist in the config, or (b) isn't marked as a writer in the config
## Functional Test

https://github.com/couchbaselabs/sync-gateway-testcluster/issues/70

**Comment by adamcfraser** [comment]
Closing - related to deprecated functionality.
