### ISSUE TITLE
Map URI's without a trailing slash to the same handlers as the trailing backslash routes

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1326]
On Couchbase Sync Gateway/master(6b72a30)

GET http://172.23.122.251:4985/db -> results in a 301 Moved permanently
GET http://172.23.122.251:4985/db/ -> returns expected JSON result 

```
{
  "committed_update_seq": 1,
  "compact_running": false,
  "db_name": "db",
  "disk_format_version": 0,
  "instance_start_time": 1449251270892103,
  "purge_seq": 0,
  "state": "Offline",
  "update_seq": 1
}
```

**Comment by adamcfraser** [comment]
Fix should handle cases on both public and admin ports.

**Comment by adamcfraser** [comment]
This is a known limitation/feature of the gorilla/mux library.  There isn't an obvious solution.
