### ISSUE TITLE
Stale parameter between the sync-gateway and the couch base server is hard coded.

### ISSUE THREAD

**Issue by stephanelorcy** [couchbase/sync_gateway#1327]
We use the sync-gateway in front of a couchbase server to synchronize information beetwen a mobile device and our IS.

We have several channels and, for a given channel, documents are locally stored in a dedicated local database.

In our use case, documents are read-only ones. And we synchronize only in a single way: from the server to the device. We use classic `_change` http request.

We have made some stressing tests in the worst scenario : 1000 users synchronize all the documents from scratch (local databases are emtpy). We have 20 channels and about 100 documents per channel. Documents are very light (less than 1 KO). Each channel is relied to a single couchbase bucket.

We have 2 hosts : one for the sync-gateway and a single node for the couchbase server. 

Our first tests are disapointing : we need 4 minutes for our gateway to serve the 20 channels to the 1000 users. And each user needs about 40 secondes to populate his local databases.

We have analyzed logs and noticed that between the syn-gateway and the couchbase node, the `stale = false` parameter is forced. Consequently, the couchbase node update the views at each request (index refresh).

We have found that in the sync-gateway code (even if I'm not a Go specialist), the `stale = false` is hard coded.

So, I've changed the code related to this paramter, re-compiled the gateway, and made some new tests.

The results are much better: we need less than two minutes to serve the 20 channels of our 1000 users and each user is served in less than 15 seconds.

Is it possible to make an evolution of the sync gateway code to specify which strategy we need ? 
We use shadow buckets and it would be cool if in the new config, we could specify a json attribute such as: `"stale":"ok"` 

What do you thing of this proposal ? We don't want to hack the code without understanding all the consequences ...

Thank you very much.

**Comment by adamcfraser** [comment]
Given the scenario you're describing, it sounds like the particular stale=false query you're talking about is the one used to [backfill the channel cache here?](https://github.com/couchbase/sync_gateway/blob/03fe1b40068efa24e8425b9551136f93ae3e21d7/src/github.com/couchbase/sync_gateway/db/changes_view.go#L78)

Using stale=ok here introduces a potential data correctness issue - Sync Gateway assumes that it has a consistent view of all data within the view range, but that's not necessarily the case for a stale=ok query.  

Having said that - for your given channel and document load (~2000 documents across 20 channels?), I would expect you to be getting results in seconds, not minutes.  There shouldn't be more than one view request getting made per channel in any case - after that the results will be stored in the in-memory channel cache for subsequent requests.

To help understand what might be causing the problems here:
1. When you say "each channel is relied to a single couchbase bucket" - does that mean you have one bucket that Sync Gateway is using for all channels, or multiple buckets?
2. What type of authentication are you using?
3. How many channels does each user have access to (on average)?

Thanks.

**Comment by stephanelorcy** [comment]
Hi, 

Thank you for your quick answer...
I am going to try to explain my use case.

In fact, we have only one bucket : Animals, which contains ... some animals :-)

Animals belong to a farming. A farm contains about 100 animals and there are 6000 farms in the system.
Each farm is a channel.

According to the informations in the user calendar, each farm which has an entry in the calendar is silently synchronized on the user device.

The morning, each user has 20 farms in his daily calendar. We have about 1000 users.

So, the morning, we have 1000 users which have to synchronize 20 channels (20 farms) of 100 animals.

And each request to the sync-gateway produces an index refresh on the animals bucket !
This is because between the sync-gateway and the couch base node, `stale = false` is systematically used.

Hope that my explanations are clear. Sorry for my bad english.

Thank you.

PS : for the moment, no authentication during our stressing tests.
We use in fact a sync_animals bucket which is a gateway shadow of the animals bucket.

**Comment by stephanelorcy** [comment]
To clarify the issue : some buckets are frequently updated and having the Sync Gateway querying with "stale=false" is perfect. But this particular bucket is not updated very often and for performance, we we'd like to choose by program the way that Sync Gateway pass this parameter. Index updates managed by the Database Change Protocol (DCP) is enough in our case.
Query send to Sync Gateway :

```
GET /animals/_changes?timeout=25000&style=all_docs&heartbeat=10000&
filter=sync_gateway%2Fbychannel&channels=1&since=9025&limit=100
```

Query passed to Couchbase :

```
GET /sync_animals/_design/sync_gateway/_view/channels?
endkey=%5B%221%22%2C5756%5D&limit=100&stale=false&startkey=%5B%221%22%2C1%5D
```

What could be nice for exemple : ability to pass stale parameter (the same way we can pass limit parameter) so that:

```
GET /animals/_changes?timeout=25000&style=all_docs&heartbeat=10000&
filter=sync_gateway%2Fbychannel&channels=1&since=9025&limit=100&stale=ok
```

could become

```
GET /sync_animals/_design/sync_gateway/_view/channels?
endkey=%5B%221%22%2C5756%5D&limit=100&stale=ok&
startkey=%5B%221%22%2C1%5D
```

Another solution would be to use the sync gateway config file in order to add a stale attribute in the shadow bucket section.

**Comment by adamcfraser** [comment]
Closing based on age (but also because for this volume of data, it should be sufficient to size the cache such that queries aren't generated)
