### ISSUE TITLE
Test double bucket shadowing

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1332]
## Steps to reproduce

Run couchbase server and two sync gateways configured with bucket shadowing

```
$ docker network create app
$ docker run -p 8091:8091 -itd --net=app --name=cbserver couchbase/server:enterprise-3.1.0
(Now go to couchbase server admin UI and create two buckets: data-bucket and shadow-bucket)
$ docker run -p 4984:4984 -p 4985:4985 -itd --net=app --name=sg1 couchbase/sync-gateway https://gist.githubusercontent.com/tleyden/f30e64d317300f43eea3/raw/23cfa1e6f69761ab18e282af3144cdfe8f351217/gistfile1.txt
$ docker run -p 4986:4984 -p 4987:4985 -itd --net=app --name=sg2 couchbase/sync-gateway https://gist.githubusercontent.com/tleyden/f30e64d317300f43eea3/raw/23cfa1e6f69761ab18e282af3144cdfe8f351217/gistfile1.txt
```

Run load test tool against shadow bucket

```
$ docker run -it --net=app --name=go --entrypoint=/bin/bash couchbase/sync-gateway
$ go get -u -v github.com/couchbaselabs/go-couchbase-throughput
$ cd $GOPATH/src/github.com/couchbaselabs/go-couchbase-throughput
$ edit main.go file to replace main function with func main() { flag.Parse();  updateLoop()}
$ go build
$ ./go-couchbase-throughput -couchbaseBucket="shadow-bucket" -couchbaseUrl="http://cbserver.app:8091" -storageEngineType="go-couchbase"
```

**Comment by tleyden** [comment]
I just noticed the following errors in one of the [sync gateway logs](https://gist.github.com/tleyden/d849628d51c906da448f#file-gistfile1-txt-L213-L214):

```
2015-12-08T01:29:11.760Z Error from 'channels' view: error executing view req at http://172.18.0.2:8092/data-bucket/_design/sync_gateway/_view/channels?endkey=%5B%22%2A%22%2C155%5D&stale=false&startkey=%5B%22%2A%22%2C156%5D: 400 Bad Request - {"error":"query_parse_error","reason":"No rows can match your key range, reverse your start_key and end_key or set descending=true"}
2015-12-08T01:29:11.760Z WARNING: Skipped Sequence 155 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the * channel view - will be abandoned. -- db.func·005() at change_cache.go:195

```

**Comment by tleyden** [comment]
I did a fresh test (flush cb server buckets), restart sync gateways, but did not reproduce the errors from the previous comment.  

In this test, as well as the last one, I'm not seeing any conflicts for the doc in the mobile bucket, and the sync gateways are fully in sync:

```
# curl sg1.app:4984/db/key-df534ee8-9419-4f06-579d-1ecc988e84a3
{"_id":"key-df534ee8-9419-4f06-579d-1ecc988e84a3","_rev":"9-9223bfc9968aa3d600a000341833a477","value":"9"}
# curl sg2.app:4984/db/key-df534ee8-9419-4f06-579d-1ecc988e84a3
{"_id":"key-df534ee8-9419-4f06-579d-1ecc988e84a3","_rev":"9-9223bfc9968aa3d600a000341833a477","value":"9"}
```

The [Couchbase Server Doc](https://gist.github.com/tleyden/cac0226062bf98239d55) isn't showing any conflicts in the revision history.

**Comment by adamcfraser** [comment]
That's not showing a particularly high number of revs in the document - what do you have the revs limit set to in the SGs?  I'd expect conflicts when there's a race and one SG has already pruned a revision the other SG tries to write.

Otherwise I think conflicts would be avoided by these bits of code:
https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/shadower.go#L113
https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/shadower.go#L131

**Comment by tleyden** [comment]
I saw the "skipped sequence" error again:

https://gist.github.com/tleyden/d45699ba3beaae9077f3

Note that several hours passed while things were essentially idle until the error was shown.

**Comment by tleyden** [comment]
Possible reason why we are seeing the skipped sequences in the first place (via @adamcfraser):

>  It's skipped when it doesn't show up on the Tap feed for 5 seconds.  In your scenario, what's more likely is probably that something in bucket shadowing is allocating the sequence, and then not using it when the other SG has already pulled the doc

**Comment by tleyden** [comment]
With `revs_limit` set to 10, still was not able to reproduce doc conflicts in Sync Gateway.

[Couchbase Server Doc](https://gist.github.com/tleyden/0872fd5d972661e33a96)

**Comment by adamcfraser** [comment]
Bucket shadowing is deprecated - closing.
