### ISSUE TITLE
[DB Online / Offline] PUT new db config and restarting sync_gateway fails to launch

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1338]
Using Couchbase Sync Gateway/master(6b72a30)

1) Running sync_gateway with the following config:

GET http://172.23.122.251:4985/db/_config
200

```
{
  "name": "db",
  "server": "http://172.23.122.250:8091",
  "bucket": "data-bucket",
  "pool": "default",
  "sync": null
}
```

2) Issue a PUT with a new config (below)

PUT http://172.23.122.251:4985/db/_config with body:
201

```
{
  "server": "172.23.122.250:8091",
  "bucket": "data-bucket",
  "users": {
    "seth": {
      "password": "password",
      "admin_channels": [
        "*",
        "ABC"
      ]
    },
    "ashvinder": {
      "password": "password",
      "admin_channels": [
        "*",
        "CBS"
      ]
    },
    "andy": {
      "password": "password",
      "admin_channels": [
        "*",
        "NBC"
      ]
    }
  }
}
```

3) Take db offline

POST http://172.23.122.251:4985/db/_offline
200

GET http://172.23.122.251:4985/db/
200
{
  "committed_update_seq": 0,
  "compact_running": false,
  "db_name": "db",
  "disk_format_version": 0,
  "instance_start_time": 1449611230543979,
  "purge_seq": 0,
  "state": "Offline",
  "update_seq": 0
}

3) Bring db online

POST http://172.23.122.251:4985/db/_online
200

GET http://172.23.122.251:4985/db/
404

```
{
  "error": "not_found",
  "reason": "no such database \"db\""
}
```

Expected: The db would come online with the new changes.
Actual: It can't find the database.

**Comment by adamcfraser** [comment]
Moved to CBG-717
