### ISSUE TITLE
Set-Cookie response header for SyncGatewaySession should contain path value with /{db}

### ISSUE THREAD

**Issue by hideki** [couchbase/sync_gateway#1345]
Hi,

Recently I encountered the issue, https://github.com/couchbase/couchbase-lite-java-core/issues/852 .
This issue could be caused by `Set-Cookie: SyncGatewaySession=xxxx` response header.  SyncGateway returns the response with the extended SyncGatewaySession by `Set-Cookie:`. However, it does not contain `path` value, so client library automatically stores the cookie with requested URL path.

Following is example scenario the current implementation causes problem:
1. Client set cookie with SyncGatewaySession and its value with null, "", or /{db} as path in the replicator. <- This cookie matches any Sync Gateway REST API that starts with `/{db}`.
2. Client sends the request with `/{db}/_local` with cookie. 
3. If session expires in 10% of TTL, Sync Gateway set Cookie with new expired date with in response header. But `path` is not specified. Note: Cookie in the request does not contain `path`. (See: https://github.com/couchbase/sync_gateway/blob/03fe1b40068efa24e8425b9551136f93ae3e21d7/src/github.com/couchbase/sync_gateway/auth/session.go#L65)
4. Client library (ex HttpClient third party library) stores the cookie from SyncGateway into CookieStore. As path is not specified in Set-Cookie,  the request URL path is used as a path. In this example, it is `/{db}/_local`. This cookie only matches with URL request which starts with `/{db}/_local`. It does not match with other URLs such as `/{db}`, `/{db}/_revs_diff`, etc..
5. When client tries to send the request `/{db}/_revs_diff`, updated cookie does not match because of path. It causes 401 Unauthorized Error.

To avoid above problem, could you please add `path` with `/{db}` in Set-Cookie for SyncGatewaySession?

NOTE: http://tools.ietf.org/html/rfc2109#section-4.2.2

```
4.2.2  Set-Cookie Syntax

   The syntax for the Set-Cookie response header is

   set-cookie      =       "Set-Cookie:" cookies
   cookies         =       1#cookie
   cookie          =       NAME "=" VALUE *(";" cookie-av)
   NAME            =       attr
   VALUE           =       value
   cookie-av       =       "Comment" "=" value
                   |       "Domain" "=" value
                   |       "Max-Age" "=" value
                   |       "Path" "=" value
                   |       "Secure"
                   |       "Version" "=" 1*DIGIT
```

Thanks!
Hideki

**Comment by tleyden** [comment]
@sethrosetter does a functional test for this seem feasible?  are there any functional tests that use session based auth yet?

**Comment by zgramana** [comment]
See https://github.com/couchbase/couchbase-lite-java-core/issues/852, which has the steps to reproduce. I don't think @sethrosetter will get a chance to knock this out before the end of the sprint.

**Comment by hideki** [comment]
With [the fix](https://github.com/couchbase/sync_gateway/tree/feature/issue_1345_cookie_path), Sync Gateway includes path in Set-Cookie. CBL Android works fine with this fix.

![screen shot 2015-12-15 at 3 27 16 pm](https://cloud.githubusercontent.com/assets/15889/11827346/5a6a2488-a340-11e5-87a6-a8142f1a6564.png)
