### ISSUE TITLE
Integrate Windows service wrapper into installer

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1349]
The windows service wrapper just needs to be run as administrator by the installer, e.g. `sg-windows.exe install [exepath] [configpath]`.

**Comment by zgramana** [comment]
Needs to copy the examples basic-couchbase-database.json file to the same path as the exe files.

**Comment by zgramana** [comment]
I've added a Windows service wrapper for `sg-accel.exe`, and command file that will build both of them.

**Comment by ajres** [comment]
To build the service wrappers the following package dependencies are required:

golang.org/x/sys
github.com/kardianos/osext
github.com/kardianos/service

And the build.cmd file must define the GOPATH variable to locate the packages.

**Comment by ajres** [comment]
Command file must be added into the jenkins build so that the InstallShield packager can find the service wrapper .exe's. @michaelkwok is doing this.

**Comment by michaelkwok** [comment]
#1551 service wrapper added to build and Installshield installer for sg-accel
