### ISSUE TITLE
Fix Intermittent failing unit tests

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1350]
- [x] TestLowSequenceHandling 
- [ ] TestUserAccessRace
- [x] DATA RACE in DatabaseContext.Authenticator()

Moved the first two tests out of ticket #1319 as these are intermittently failing rather than reporting Data Race issues.

Moved one DATA RACE out of ticket #1319 as fixing it will likely have merge conflicts with distributed index

**Comment by tleyden** [comment]
Moved `TestUserAccessRace ` TODO to https://github.com/couchbase/sync_gateway/issues/2978
