### ISSUE TITLE
Add TTL support for Couchbase Mobile documents

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1354]
As a Couchbase Mobile user, I want to limit the lifespan of some documents so that I can limit the amount of data I'm retaining without having to build custom functionality specifically for this purpose. This is particularly useful when creating a large number of single-revision documents, such as for time-series data and messaging-style documents.

**Comment by tleyden** [comment]
Closing as duplicate of https://github.com/couchbase/sync_gateway/issues/1823
