### ISSUE TITLE
Dev build packages do not install as a service when calling rpm -i

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1357]
http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/0.0.1/feature/distributed_index/0.0.1-432/couchbase-sync-gateway-community_0.0.1-432_x86_64.rpm

```
rpm -i couchbase-sync-gateway-community_0.0.1-432_x86_64.rpm 
```

will install the binary to /opt/couchbase-sync-gateway/ but will not install sync_gateway as a service. 

http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.2.0/1.2.0-5/couchbase-sync-gateway-enterprise_1.2.0-5_x86_64.rpm

```
rpm -i couchbase-sync-gateway-enterprise_1.2.0-5_x86_64.rpm 
```

will install as a service.

Is there a way that we could generate enterprise builds so that the dev packages and the master binaries have consistent behavior?

**Comment by ajres** [comment]
The service installer changes have been cherry picked to the feature/distributed_index branch.

@sethrosetter please retest

**Comment by sethrosetter** [comment]
@ajres  rpm -i will now install dev build packages (ex. http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/0.0.1/feature/distributed_index/0.0.1-490/couchbase-sync-gateway-community_0.0.1-490_x86_64.rpm)

**Comment by sethrosetter** [comment]
@ajres. Closing,
