### ISSUE TITLE
[enhancement] Add IdentityStore to sync_gateway to make sync_gateway more flexible and high scalability

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1359]
I am build a app, the business logic as following:
one user belong to 0-n company, one company have some documents. 
I want to deploy couchbase and sync_gateway by company. so I can manage documents by company. such as distributed cluster deploy, backup and restore by company.
I think it will be more flexible and high scalability.

As I know, sync_gateway will route document and control write/read document by channel, which depend on user and session(access()/requrieUser()). that means user document are coupling with 'company' documents
so, If sync_gateway can store user document and session document(may be) alone with other documents as public identity store,It will be possible to deploy sync_gateway and couchbase by company.
And this enhancement ability will make sync_gateway more flexible and high scalability.

the config of sync_gateway database might looks like as following:

```
"databases": {
  "db": {
    "server": "http://localhost:8091",
    "bucket": "default",
    "identity_server": "http://localhost:8091",
    "identity_bucket": "identity",    
    "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } }
  }
}
```

**Comment by adamcfraser** [comment]
Closing based on age, and support for OIDC for remote IdP support.
