### ISSUE TITLE
Sync gateway sending an infinite number of empty messages

### ISSUE THREAD

**Issue by jschmid** [couchbase/sync_gateway#1365]
This issue is related to the one I filled at couchbase/couchbase-lite-ios#1003. @snej suggested I post it here.

We are using Sync Gateway 1.1.0 and Couchbase Lite 1.1.0. We have 3 SG nodes with 3 Couchbase server nodes behind the AWS load balancer. The iOS client uses a continuous pull replication. There is no special configuration in place (not changed the heartbeat, etc...)

We had a case where the sync gateway would send an infinite loop of empty messages. See the log here: https://gist.github.com/jschmid/521be17b6395de9e8fcf

This only happened on the iOS simulator and never on a device. This happened to two people, on two different machines, with two different internet connections. Since then, we cannot reproduce it anymore. (We had Wireshark sniff our packets on the SG server, with no luck)

Any chance you've seen this before ? Thanks

**Comment by adamcfraser** [comment]
There was an issue in 1.1.0 that could result in Sync Gateway going into a loop as described, related to initialization of the user channel set during continuous or longpoll changes replication.  It was a related case to issue #916, but could also occur for continuous replication.

This was fixed and should be addressed in Sync Gateway 1.1.1.  If you haven't upgraded to 1.1.1, upgrading may resolve the issue.  

If you're already on 1.1.1 and still seeing this, getting the Sync Gateway logs - ideally with Changes and Changes+ logging enabled, would help narrow down what's going on.

**Comment by jschmid** [comment]
Thanks @adamcfraser. We will upgrade to 1.1.1 and reopen this issue if it happens again. :+1:

**Comment by puffin** [comment]
@adamcfraser Can you push the version 1.1.1 to Docker Hub please?
