### ISSUE TITLE
Docker Hub not updated with latest SG release

### ISSUE THREAD

**Issue by puffin** [couchbase/sync_gateway#1366]
The latest docker images build on your Docker Hub repository is the 1.1.0. As we were suggested to upgrade our SG to the 1.1.1 https://github.com/couchbase/sync_gateway/issues/1365, Can you push this release to Docker Hub please?

**Comment by tleyden** [comment]
Hey @puffin I can take care of this.  What's the urgency on this from your side?

**Comment by puffin** [comment]
@tleyden ASAP is always welcomed! :+1:

**Comment by tleyden** [comment]
Builds in progress!

https://hub.docker.com/r/couchbase/sync-gateway/builds/

Btw, I added instructions on the steps I did in the commit message:

https://github.com/couchbase/docker/commit/19d65a2b353e8cf656c30b2cdeb462b4bc6c8b10

theoretically, if anyone is ever blocked in the future on newer docker images .. you could:
- fork the https://github.com/couchbase/docker repo
- do [these steps](https://github.com/couchbase/docker/commit/19d65a2b353e8cf656c30b2cdeb462b4bc6c8b10) yourself
- push to your fork and open a PR on the https://github.com/couchbase/docker
- open a dockerhub account, and create an automated build pointed to your fork

**Comment by tleyden** [comment]
If the build fails, please re-open this ticket.

**Comment by puffin** [comment]
Ok great, build succeed. thanks! :+1:
