### ISSUE TITLE
Collect periodic time-series data at varying 'zoom' levels

### ISSUE THREAD

**Issue by Chippiewill** [couchbase/sync_gateway#1367]
eg. The data contained on the _expvars endpoint should be periodically collected

This would be useful for monitoring and issue diagnosis.

**Comment by Chippiewill** [comment]
Ideally this data would be included as part of #1331

**Comment by adamcfraser** [comment]
Should be covered as part of https://github.com/couchbase/sync_gateway/issues/3213.
