### ISSUE TITLE
[Distributed Index] Index reader trying to read from empty index when writer fails to initialize

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1372]
Using Couchbase Sync Gateway/feature/distributed_index(a157f83)

Below is the log output of a writer that fails to register with CBGT
https://gist.github.com/sethrosetter/704c93e65a1dfed63721

Despite the writers not registering, the readers continue to try and read from an empty index https://gist.github.com/sethrosetter/9add6ad6425ef5d9e3f9

full logs -> https://s3.amazonaws.com/sync-gateway-logs/snapshot-2015-12-17-17-52-24-sglogs.zip

**Comment by tleyden** [comment]
If you can reproduce it, can you try to capture the CBGT diagnostics as mentioned in https://github.com/couchbaselabs/sync-gateway-testcluster/issues/157?

**Comment by adamcfraser** [comment]
I think it's appropriate for the readers continuing to try to read from an empty index.  That handles the case where the readers spin up before the writers do - readers shouldn't abort/fail while waiting for the writer to show up.

**Comment by zgramana** [comment]
@sethrosetter please review and comment if there are any functional implications that are concerning. If not, please close.

**Comment by sethrosetter** [comment]
@adamcfraser @tleyden After re-reading the logs, I think I was concerned about this line https://gist.github.com/sethrosetter/e94f839262e6ba6d61db#file-gistfile1-txt-L12 and the large amount of warnings such as https://gist.github.com/sethrosetter/85889120b693f0419f2f If these are expected, when the cluster is in the state, then this is not an issue.
