### ISSUE TITLE
[DB Online / Offline] - db not returning expected error codes after losing TAP feed and going offline

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1377]
Using "Couchbase Sync Gateway/1.2.0(6;9bc164c)"

If you take a db offline via Admin REST 
POST :4985/db/_offline -> 200 OK
GET :4585/db/

```
{
  "committed_update_seq": 8,
  "compact_running": false,
  "db_name": "db",
  "disk_format_version": 0,
  "instance_start_time": 1450568031131227,
  "purge_seq": 0,
  "state": "Offline",
  "update_seq": 8
}
```

Any REST calls to the Admin db or public db endpoints return expected 503 responses
However, if the db is taken offline when losing TAP feed (simulated by deleting the server bucket), the db is taken into an offline state and public rest db endpoint REST call return 401 auth errors

A server bucket is deleted
GET :4985/db/

```
{
  "committed_update_seq": 0,
  "compact_running": false,
  "db_name": "db",
  "disk_format_version": 0,
  "instance_start_time": 1450568648513177,
  "purge_seq": 0,
  "state": "Offline",
  "update_seq": 0
}
```

From the response above, the db has been taken offline
GET :4985/db/_user/

```
{
  "error": "Service Unavailable",
  "reason": "DB is currently under maintenance"
}
```

GET :4984/db/_changes?include_docs=true -> 401 Unauthorized

```
{
  "error": "Unauthorized",
  "reason": "Invalid login"
}
```

Expected: A db that loses its TAP feed should be taken to an offline state and all db REST endpoint calls should return 503

Actual: A db that loses its TAP feed should be taken to an offline state returns 503 for admin REST db endpoints and 401 error for public endpoints

**Comment by adamcfraser** [comment]
Discussed this with Seth, and I agree that a DB that loses it's entire bucket connection, but is in an offline state, should be returning a 503 for requests against the public API.  In particular this would be the way to handle a single node in a SG cluster that loses bucket connection (from a network partition, say), while the rest of the SG cluster is still online.

@ajres Can you review whether it's feasible to do the online/offline check before doing authentication for public API requests?
