### ISSUE TITLE
[Distributed Index]  _changes feed return incomplete response with invalid entries

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1379]
I have a user that posts 5000 docs in a loop to channel "ABC". After all docs have been pushed, the user then updates each document 10 times.

After all of the update, the user issues a _changes request and gets 4997 docs with some invalid entries (entries with empty doc ids) in the response

Part of the response.

```
{
  "results": [
    {
      "seq": "32-2",
      "id": "8fde0d39-6fd2-4778-8c7d-e3ecf5c12a4c",
      "doc": {
        "_id": "8fde0d39-6fd2-4778-8c7d-e3ecf5c12a4c",
        "_rev": "11-21329ea85123f08e0f183c10edeba24d",
        "channels": [
          "ABC"
        ],
        "updates": 10
      },
      "changes": [
        {
          "rev": "11-21329ea85123f08e0f183c10edeba24d"
        }
      ]
    },
    {
      "seq": "46-2",
      "id": "c8cf4a95-69e7-4208-bc10-759f51e0f28b",
      "doc": {
        "_id": "c8cf4a95-69e7-4208-bc10-759f51e0f28b",
        "_rev": "11-21329ea85123f08e0f183c10edeba24d",
        "channels": [
          "ABC"
        ],
        "updates": 10
      },
      "changes": [
        {
          "rev": "11-21329ea85123f08e0f183c10edeba24d"
        }
      ]
    },
    {
      "seq": "52-2",
      "id": "",
      "changes": [
        {
          "rev": ""
        }
      ]
    },
    {
      "seq": "62-2",
      "id": "02703b93-73e2-4aa9-bbcd-3196b98edf44",
      "doc": {
        "_id": "02703b93-73e2-4aa9-bbcd-3196b98edf44",
        "_rev": "11-21329ea85123f08e0f183c10edeba24d",
        "channels": [
          "ABC"
        ],
        "updates": 10
      },
      "changes": [
        {
          "rev": "11-21329ea85123f08e0f183c10edeba24d"
        }
      ]
    },
    {
...
```

NOTE the entry missing data. 

When issuing an :4984:/db/_all_docs query, I am returned the expected 5000k docs

Logs for the test here. https://s3.amazonaws.com/sync-gateway-logs/functional_tests-test_continuous.py-test_continuous_changes_parametrized%5BDI-4%5D-2015-12-21-13-34-33-sglogs.zip

**Comment by adamcfraser** [comment]
Reviewed with Seth, but wasn't able to identify the source of the problem.  Need to build a unit test to repro and then debug.

**Comment by tleyden** [comment]
@sethrosetter Can you add instructions on how to repro?  (which test?)

Also, was it happening 100% of the time?

**Comment by sethrosetter** [comment]
@adamcfraser Do think this is a possible duplicate of #1440? The empty entry in the above response looks identical to the intermittent empty response that issue.

**Comment by adamcfraser** [comment]
This looks the same as #1440 - going to close this one and track the fix w/ 1440.
