### ISSUE TITLE
resync operation only supported in offline state

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1382]
Opening this defect since earlier resync operation could be run when sync-gateway was online. Now it is only possible in db offline state. If this is the intended behavior we need to release note the difference from the previous releases.

**Comment by zgramana** [comment]
I'll add a release note.

**Comment by adamcfraser** [comment]
Also need to update the resync docs to reflect this.

**Comment by adamcfraser** [comment]
Already updated in the docs (https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/docs/src/guides/sync-gateway/rest-apis/admin-rest-api/database-resources/post-db-resync.xml#L11).
