### ISSUE TITLE
nginx load balancer needs plugins to detect db offline state.

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1383]
nginx needs to configured with custom plugin to detect the db offline state. 
https://www.nginx.com/resources/wiki/modules/healthcheck/
Needs to be release noted.

**Comment by maxmilton** [comment]
Where is the documentation about this?

**Comment by adamcfraser** [comment]
This ticket doesn't describe a Sync Gateway issue - it's just referring to the nginx HTTP healthcheck module (described at the above link).
