### ISSUE TITLE
Final Packaging for 1.2

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1387]
This is a tracking ticket for release packaging for sync_gateway 1.2
- [x] Distributed index merged to master
- [x] Separate binary packages for IR / IW
- [ ] Release candidate build number

**Comment by michaelkwok** [comment]
Now that Distributed Index is merged to master.  Does somebody from Dev need to update the build generate the separate binary?  If you require that I update the build script, please provide build instructions.  Currently, I don't see the second binary getting generated.

**Comment by tleyden** [comment]
@michaelkwok see https://github.com/couchbase/sync_gateway/pull/1362#issue-122588447 and let me know if you have any questions.

**Comment by michaelkwok** [comment]
@Zack, are we naming the final binary package sync_gateway_index_writer_xxx?

**Comment by michaelkwok** [comment]
@zgramana have we finalized on the name sync_gateway_index_writer_xxx?
