### ISSUE TITLE
sync gateway not emitting webhook event when going to offline state

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1389]
Scenario:
- Configure SG with webhook events for both document and db_state_change. https://gist.github.com/ashvindersingh/1bdbfbae5d95c1911256
- Ensure the SG launches and is online. 
- Make the db go offline by issuing "db/_offline" REST call. 
  Expect an offline event to be emitted from SG
  Observed behavior: No event is emitted when db is going from online to offline state. 
  Going from offline --> online does generate an 'online' webhook event.

**Comment by sethrosetter** [comment]
@ashvindersingh there is still a failing webhook test. Can you look?
