### ISSUE TITLE
[Distributed Index] Seeing bulk_get timeouts when running performance tests.

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1390]
When running the performance tests, I am seeing a rapid increase of p95 and p99  toward the the end of the test runs for 10k pushers / 10k pullers. 

Here is the run results - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/150#issuecomment-168110716

When grep-ing the warnings from the sync_gateway logs, there seem to be a bunch of bulk_get timeouts. Here is a subset of the output. https://gist.github.com/sethrosetter/ea67a4fa1d05d8ff4611

sync_gateway logs - https://s3.amazonaws.com/sync-gateway-logs/snapshot-2015-12-30-18-10-56-sglogs.zip

**Comment by adamcfraser** [comment]
Per @sethrosetter - this is when running with 2 readers/1 writer.  i believe the timeouts are a symptom of hitting the current throughput limits for index readers.  Will be reviewed as part of the 1.3 work to increase that throughput limit.

**Comment by adamcfraser** [comment]
Consider converting this to a more generic KPI review ticket.

**Comment by adamcfraser** [comment]
Deliverable for this ticket - enhance our perf suite to provide reporting on the number of timeouts being hit in the logs.  Most straightforward approach is probably to track timeout errors in expvars (along with log messages) to support monitoring.

**Comment by adamcfraser** [comment]
Closing, related to deprecated functionality (accel).
