### ISSUE TITLE
[Distributed Index] Writer memory continually growing during perf tests

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1391]
Using "Couchbase Sync Gateway/feature/distributed_index(807177a)"

I ran a 10k pusher / 10k puller gateload performance test targeting 4 IRs / 2 IW for 30 min. You can see the reader group memory stabilizes while the the writer's memory is growing linearly.

![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/1365736/12068241/6766edb2-afbe-11e5-97c3-3ef84d281ae6.png)

Full test results (expvars) - https://s3.amazonaws.com/sync-gateway-logs/10k-10k-4IR-2IW.zip

**Comment by adamcfraser** [comment]
Index writer isn't releasing cached index blocks when they are no longer active/needed.
