### ISSUE TITLE
Documentation issue regarding views

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1395]
In [this documentation](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/sync-gateway/accessing-cb-views/creating-and-using-a-view/index.html) it gives this example view:

```
{
    "views":{
        "all_lists":{
            "map":"function (doc, meta) { if (doc._sync === undefined || meta.id.substring(0,6) == \"_sync:\") { return; } if (doc.type != \"list\") { return; } emit(doc.title, doc.owner); }"
        }
    }
}
```

Through trial and error it seems that the line `if (doc._sync === undefined || meta.id.substring(0,6) == \"_sync:\")` is causing the view to not emit any results.  Also, even if I removed that from the view code that was pushed to Sync Gateway, that same if check appears in the actual Couchbase Server view that is generated by Sync Gateway:

<img width="667" alt="screen shot 2016-01-03 at 11 50 35 am" src="https://cloud.githubusercontent.com/assets/296876/12080492/bc975228-b210-11e5-9f75-c700fe2287cd.png">

Should the docs be updated to remove `if (doc._sync === undefined || meta.id.substring(0,6) == \"_sync:\")` from the example?

**Comment by adamcfraser** [comment]
Yes - that shouldn't be in the example - that's included in the wrap code that SG adds to the view for channel security.

The `delete doc._sync` (also included when we wrap) is going to cause any custom views that include that check to not emit any data.

**Comment by adamcfraser** [comment]
Has been fixed.
