### ISSUE TITLE
Startup checks for index writer binary

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1399]
- on a regular sync gw binary, fail if writer = true in config
- on an index writer sync gw binary, fail if writer = false in config
- add a command line override to disable strict checking

1.3:
- turn off public api, etc

**Comment by tleyden** [comment]
Stubbed out: https://github.com/couchbase/sync_gateway/pull/1362

**Comment by adamcfraser** [comment]
Also 1.2 - get PM approval for name of index_writer binary.

**Comment by michaelkwok** [comment]
Is the final binary package named sync_gateway_index_writer_xxx?

**Comment by tleyden** [comment]
@adamcfraser in the case of the sg_accel binary, should this be looping over the databases and making sure that _all_ of them are configured as index writers?  (and vice-versa on the normal sg binary, making sure that _none_ of them are configured as index writers?)
