### ISSUE TITLE
Index writer panics under heavy load

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1405]
Kicked of a perf run demo with @adamcfraser and @tleyden and saw the above behavior. It seems to be a perf regression as I have run similar perf scenarios stable outcomes.

This is targeting sync_gateway 1.2.0-20.

Test results - https://s3.amazonaws.com/sync-gateway-logs/10k-10k-8IR-2IW_2016-01-05-11-07-05.zip
sg logs (1W / 1R) - https://s3.amazonaws.com/sync-gateway-logs/snapshot-2016-01-05-11-32-36-sglogs.zip

**Comment by sethrosetter** [comment]
Running against Couchbase Sync Gateway/feature/distributed_index(ec2d898)

Full results (including sync_gateway logs) - https://s3.amazonaws.com/sync-gateway-logs/10k-10k-8IR-2IW_2016-01-05-12-30-17.zip

In the sync_gateway logs, sg1 and sg2 are writers

![gateload_expvars](https://cloud.githubusercontent.com/assets/1365736/12130121/12bb372a-b3bd-11e5-8549-856b5dbecea1.png)
![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/1365736/12130123/12bc7c3e-b3bd-11e5-93d7-0e1b7c314034.png)
![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/1365736/12130122/12bc2072-b3bd-11e5-8433-6c39b5318cb7.png)

**Comment by sethrosetter** [comment]
Running against - Couchbase Sync Gateway/feature/distributed_index_pre_access(807177a)

Full results (including sync_gateway logs) - https://s3.amazonaws.com/sync-gateway-logs/10k-10k-8IR-2IW_2016-01-05-14-04-00.zip

In the sync_gateway logs, sg1 and sg2 are writers

![gateload_expvars](https://cloud.githubusercontent.com/assets/1365736/12130131/21658fdc-b3bd-11e5-89ef-11a34f233920.png)
![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/1365736/12130133/21666506-b3bd-11e5-9ac0-7da31e358f02.png)
![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/1365736/12130132/2165c042-b3bd-11e5-882f-a796fde186ae.png)

**Comment by zgramana** [comment]
IndexWriters were panicking as the result of getting a transient CBS error during the write cycle, and was not getting retried. The fix approach is expanding the recovery strategy to include these scenarios in the writer functionality. Still need to add similar handling logic on the reader side.

**Comment by adamcfraser** [comment]
Filed a separate issue for the performance degradation on the reader side, as it looks unrelated to the writer issue: https://github.com/couchbase/sync_gateway/issues/1423
