### ISSUE TITLE
Feedtype=DCP not working sometimes

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1406]
Factored out of https://github.com/couchbase/sync_gateway/issues/1085#issuecomment-168844340.  I'm seeing strange connection errors when using the DCP feedtype under certain conditions.

**Comment by steveyen** [comment]
Hi @tleyden 

Wondering if you could add some more info on the "certain conditions".  From the link to issue #1085, looks like it works for others and on other platforms.  But, just not on your OSX dev laptop?  Is that the right characterization?

Is it easily reproducible?  Or, kinda sometimes intermittent?

According to the error message from the #1085, looks like the "UPROpen receive" error happens here, right after sending a UPR_OPEN request...

```
https://github.com/couchbase/go-couchbase/blob/master/cbdatasource/cbdatasource.go#L1470
```

So, a read/recv on the socket is returning EOF.

One place to look next is there might be logs and/or stats from Couchbase Server, too, that might give hints as to why the connection is getting closed.

Also, wondering if you could grab diag stats from cbgt once you see it again.

**Comment by tleyden** [comment]
I'm seeing it on AWS right now, 100% reproducible.  This is using `cbdatasource`, but not CBGT.

I'll check the couchbase server logs.

**Comment by tleyden** [comment]
@steveyen I'm tailing all of the couchbase server logs, and when I restart sync gateway I see the following new log output:

https://gist.github.com/tleyden/1d34e6c8c803f8324c0d

(nothing jumps out at me as being unexpected)

Here are the sync gw logs:

https://gist.github.com/tleyden/ed7e7ad94d7f69d5930e

**Comment by tleyden** [comment]
Here are some wireshark traces from my OSX machine, and I'm assuming it's the same story on the AWS boxes.

When using feed=DCP (cbdatasource), there is no response to the DCP Open Connection request:

<img width="1465" alt="dcp_open_no_response" src="https://cloud.githubusercontent.com/assets/296876/12129186/ce76a17c-b3b6-11e5-925a-58e1880351b9.png">

When using feed=DCPSHARD (cbgt), it's getting a response to the DCP Open Connection request:

<img width="1465" alt="dcp_open_response" src="https://cloud.githubusercontent.com/assets/296876/12129199/de2f5794-b3b6-11e5-8066-4c2f4f22ab06.png">

**Comment by tleyden** [comment]
TODO: 
- [x] wireshark capture of setup under Docker where it's working with feedtype=dcp

**Comment by steveyen** [comment]
Thanks - I also didn't see any a-ha's from the logs either (especially memcached.log).

This is really strange.  cbgt is using cbdatasource underneath the hood, so you'd think they should have the same behavior.

Any chance that the sync-gateway code that uses cbdatasource directly has changed recently?

Anything related to auth, perhaps?

Or, sync-gateway's implementation of the cbdatasource Receiver interface (probably less likely)?

If you "rollback" your build or branch back to pre-cbgt, are you able to still see the problem with direct usage of cbdatasource?

**Comment by steveyen** [comment]
One more thing from the logs, is I would have expected to see some "Connecting to new bucket datasource" kind of log entries somewhere, from here...

https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/base/bucket.go#L295

But, didn't see it (or I'm blind)

**Comment by tleyden** [comment]
> Any chance that the sync-gateway code that uses cbdatasource directly has changed recently?

It might be more the case that it has been broken for a long time and we are just now noticing, especially since the feedtype=DCP is not a very popular way to run Sync Gateway.  (off by default)

> Anything related to auth, perhaps?

We looked into that a bit and it didn't seem to be the case.  It's the UPROpen call that's giving an error:

```
2016-01-05T22:33:11.383Z WARNING: Feed%!(EXTRA string=Error processing DCP stream: %v, *errors.errorString=UPROpen receive, err: EOF) -- base.(*DCPReceiver).OnError() at dcp_feed.go:97
```

> If you "rollback" your build or branch back to pre-cbgt, are you able to still see the problem with direct usage of cbdatasource?

I was able to reproduce it on Sync Gateway 1.1.1 which predates any of the CBGT additions.

It seems to be working in some setups (locally for me under Docker, locally for Adam directly on OSX), with everything apparently equal (both using direct cbdatasource).  I'm going to focus on trying to tease out the differences in those and compare the wireshark logs, etc.

**Comment by tleyden** [comment]
> I would have expected to see some "Connecting to new bucket datasource" kind of log entries somewhere, from here...

That's not showing up since the `Feed+` loglevel isn't enabled.

**Comment by tleyden** [comment]
I tried running this under Docker on AWS, expecting it to work (since it worked under Docker on my OSX setup), and ended up seeing a _third_ behavior!  

In the [sync gateway logs](https://gist.github.com/tleyden/94dec89e62022b0f4583) there are tons of DCP rollback errors.

```
2016-01-06T00:33:56.971Z WARNING: DCP Rollback request - rolling back DCP feed for: vbucketId: 520, rollbackSeq: 0 -- base.(*DCPReceiver).Rollback() at dcp_feed.go:176

```

In the [couchbase server babysitter logs](https://gist.github.com/tleyden/0989c2001ebf4ca8c93d) there are lots of [errors](https://gist.github.com/tleyden/0989c2001ebf4ca8c93d#file-gistfile1-txt-L1542) regarding the sequence numbers:

```
memcached<0.76.0>: 2016-01-06T00:46:53.667653Z WARNING (default) DCP (Producer) eq_dcpq:cbdatasource-3e1a2d322bc37113 - (vb 520) Stream request failed because the snap start seqno (2) <= start seqno (0) <= snap end seqno (2) is required
```

To try to sanity check the setup, I ran with feedtype=DCPSHARD with no issues -- [startup log output for sync gateway](https://gist.github.com/tleyden/3335c89c5ce3cb1492e3).  Ditto for feedtype=TAP.

Since Sync Gateway doesn't recover from the DCP Rollback messages I think there are bugs with feedtype=DCP around dealing with DCP Rollbacks (the feedtype=DCPSHARD has undergone more testing in that regard as far as I know)

Setup:
- [Sync Gateway config feedtype=dcp](https://gist.github.com/tleyden/5bd00a4c4f30e06cf9e3)
- Couchbase server 4.1.0, configured hostname to be 127.0.0.1 during setup
- The Couchbase Server bucket is empty when starting Sync Gateway
- Running `--net host` so that both docker containers share the host networking and Sync Gateway can view docker over 127.0.0.1.

Steps to repo:
- Install Docker
- `docker run -itd --net host couchbase/server:enterprise-4.1.0`
- Manually setup Couchbase Server via web UI and create buckets
- `docker run -itd --net host --entrypoint /bin/bash couchbase/sync-gateway`
- `docker exec -ti container-id bash` to get a bash shell in the container
- Switch to the `feature/issue_1085_dboffline_dcp` branch, run `git submodule init && git submodule update`, rebuild Sync Gateway
- Use the  [Sync Gateway config feedtype=dcp](https://gist.github.com/tleyden/5bd00a4c4f30e06cf9e3)
- Start Sync Gateway

**Comment by sethrosetter** [comment]
I'm seeing a test failure in the sync_gateway functional tests that seems to be related to this issue. http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests/59/testReport/junit/functional_tests/test_db_online_offline/test_db_offline_tap_loss_sanity_CC_1_/

Using Couchbase Sync Gateway/1.2.0(35;a2a9c49) with the config below

```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": true,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "verbose":"true",
    "databases":{
        "db":{
            "server":"http://{{ couchbase_server_primary_node }}:8091",
            "bucket":"data-bucket",
            "feed_type":"DCP"
        }
    }
}
```

The errors are the same as @tleyden 's comment above https://github.com/couchbase/sync_gateway/issues/1406#issuecomment-169174722

sync_gateway log output
https://gist.github.com/sethrosetter/864fe38f9f67627c54e3#file-gistfile1-txt-L11-L47

**Comment by tleyden** [comment]
Until this is resolved disable DCP mode: https://github.com/couchbase/sync_gateway/issues/1427

**Comment by adamcfraser** [comment]
This turns out to be an auth issue after all.  I believe the 'certain conditions' mentioned above had to do with whether we were testing against a Couchbase bucket named 'default' (which works), or a named bucket (which doesn't).

It looks like as part of the CBGT uptake work, the bucket auth setup for the non-CBGT DCP was broken.  

With the current bucket AuthHandler functionality using TransformBucketCredentials, we just need to ensure there's a non-nil AuthHandler being passed along.
