### ISSUE TITLE
TestDBOnlineConcurrent unit test fails sporadically

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1413]
This test failed:

http://mobile.jenkins.couchbase.com/view/Sync_Gateway_Dev/job/sync-gateway-dev-build/512/

however it seems to be sporadic, as re-running it worked:

http://mobile.jenkins.couchbase.com/view/Sync_Gateway_Dev/job/sync-gateway-dev-build/513/

(the only difference was passing the -v flag)

Locally when I run with `test.sh -v` I'm seeing this failure:

```
 the admin_channels parameter. -- rest.emitAccessRelatedWarnings() at server_context.go:1061
2016-01-06T12:20:41.023-08:00 HTTP:  #1136: GET http://localhost/db/  (ADMIN)
--- FAIL: TestDBOnlineConcurrent (0.02s)
    api_test.go:194: Response status 404 (expected 200) for POST <http://localhost/db/_online> : {"error":"not_found","reason":"no such database \"db\""}
```

**Comment by tleyden** [comment]
In [build 514](http://mobile.jenkins.couchbase.com/view/Sync_Gateway_Dev/job/sync-gateway-dev-build/514/consoleFull) I saw the same failure:

```
12:27:10 --- FAIL: TestDBOnlineConcurrent (0.04s)
12:27:10    api_test.go:194: Response status 404 (expected 200) for POST <http://localhost/db/_online> : {"error":"not_found","reason":"no such database \"db\""}
```

**Comment by tleyden** [comment]
Looks like this test has had issues in the past:  https://github.com/couchbase/sync_gateway/commit/2a3da714aa418e428aad5b1a82614fcd6464b2f2

**Comment by adamcfraser** [comment]
Duplicate of https://github.com/couchbase/sync_gateway/issues/1408?

**Comment by tleyden** [comment]
Looks like it .. closing
