### ISSUE TITLE
Use legacy compression for non-CBL 1.2 user agents

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1419]
The compression enhancement for _bulk_get introduced un-intended side effects in Java Core. While [this was fixed in 1.2](https://github.com/couchbase/couchbase-lite-java-core/issues/824), the problem presents for earlier versions. This creates a problem as many apps will have some older versions of CBL connecting to upgraded 1.2 servers for some period of time.

Instead, the SG response should use the new method only for clients that are aware of the change, and use the previous behavior for the remainder.

**Comment by zgramana** [comment]
Will work out the user agent strings sent by Couchbase Lites.

**Comment by zgramana** [comment]
Will also need to update API docs.

**Comment by adamcfraser** [comment]
Details on user agent here: https://github.com/couchbase/couchbase-lite-java/pull/86

If you see the 1.2 user agent or higher on a request, use the compression logic that's currently on master.

If you don't see the 1.2 user agent, that means it's an old client build, and so you want to force the part-based compression.

**Comment by tleyden** [comment]
Check the user agent of the android cbl for 1.1 release, if you don't find the user agent then disable compression.  

if no user agent string:
   disable compression
if user agent string:
   must be version 1.2 or greater, otherwise disable compression

**Comment by adamcfraser** [comment]
To be clear - we're not disabling compression altogether - just switching between full response compression, and part-based compression.

**Comment by tleyden** [comment]
Related to https://github.com/couchbase/sync_gateway/issues/1163

**Comment by tleyden** [comment]
cblite android request headers for `_bulk_get` endpoint:

| client version | accept-encoding header | X-Accept-Part-Encoding | useragent header | handles gzip encoded full response | per-part gzip encoded response |
| --- | --- | --- | --- | --- | --- |
| cblite android 1.0 | EMPTY | EMPTY | CouchbaseLite/1.0.0 | n/a | n/a |
| cblite android 1.1 | "gzip, deflate" | "gzip" | CouchbaseLite/1.1.0 | NO | YES |
| cblite android 1.2 | "gzip, deflate" | "gzip" | [CouchbaseLite/1.2 (xxxx)](https://github.com/couchbase/couchbase-lite-java-core/issues/909) | YES | YES |

@hideki can you update the above table with the correct values?  I think cbl android v1.1 or earlier are the versions that have the issue, if not then please correct the version info.

**Comment by tleyden** [comment]
Desired SG behavior (I think).  I put the cases in **bold** which will be behavior modified by the changes for this issue.

| Accept-Encoding | X-Accept-Part-Encoding | User-Agent | sg 1.1 response | sg 1.2 response |
| --- | --- | --- | --- | --- |
| EMPTY | EMPTY | EMPTY OR CouchbaseLite/1.1 | No gzip encoding | No gzip encoding |
| gzip | EMPTY | EMPTY OR CouchbaseLite/1.1 | No gzip encoding | No gzip encoding |
| EMPTY | gzip | EMPTY OR CouchbaseLite/1.1 | Gzip Encode Parts (Not full response) | Gzip Encode Parts (Not full response) |
| gzip | gzip | EMPTY OR CouchbaseLite/1.1 | Gzip Encode Parts (Not full response) | **Gzip Encode Parts (Not full response)** |
| EMPTY | EMPTY | CouchbaseLite/1.2 | No gzip encoding | No gzip encoding |
| gzip | EMPTY | CouchbaseLite/1.2 | No gzip encoding | Gzip Encode full response |
| EMPTY | gzip | CouchbaseLite/1.2 | Gzip Encode Parts (Not full response) | Gzip Encode Parts (Not full response) |
| gzip | gzip | CouchbaseLite/1.2 | Gzip Encode Parts (Not full response) | Gzip Encode full response |

**Comment by adamcfraser** [comment]
@tleyden I believe there's also a set of cases where Accept-Encoding = EMPTY.  Are you leaving those off the table because they aren't changing?

**Comment by tleyden** [comment]
@adamcfraser good call!  I just realized that after I looked at the first version, will update

**Comment by tleyden** [comment]
I've got the messy version working, trying to get this cleaned up.

**Comment by tleyden** [comment]
How I tested manually:

This curl request:

```
curl -X "POST" "http://localhost:4984/db/_bulk_get" \
    -H "Content-Type: application/json" \
    -H "Accept-Encoding: gzip" \
    -H "Authorization: Basic Zm9vOmZvbw==" \
    -H "X-Accept-Part-Encoding: gzip" \
    -H "User-Agent: couchbaselite/1.1" \
    -d "{\"docs\":[{\"id\":\"82d38d2ef10a5ce91e67312854cfd6dd\"}]}"
```

returns:

```
HTTP/1.1 200 OK
Content-Type: multipart/mixed; boundary="d1664e5a7cf3df9d31a5b8a34c173b7981c419e51adef2161c0a43643443"
Server: Couchbase Sync Gateway/1.2 branch/feature/issue_1419_compression_useragent commit/285f883+CHANGES
Date: Thu, 14 Jan 2016 02:40:56 GMT
Content-Length: 342
Connection: close

--d1664e5a7cf3df9d31a5b8a34c173b7981c419e51adef2161c0a43643443
Content-Type: application/json
Content-Encoding: gzip

  nÿìËKªÂ@Fá½Ô8®tu3»ºÐvU¡I Ä½Ûûð|£sÞ´ÜfN£hgÎ!
ÙþØÆ)r'C]GUjh9ìYKnÓ8=ÄkP÷)s~¸Õ6¯iÛ¬<h¾ÐÿéL×V+e¯ÿk?¶B!B!?#}¾ÿÿÝ½Ùs
--d1664e5a7cf3df9d31a5b8a34c173b7981c419e51adef2161c0a43643443--
```

Note: no content-encoding == gzip, and parts are gzip encoded.

Whereas this curl request:

```
curl -X "POST" "http://localhost:4984/db/_bulk_get" \
    -H "Content-Type: application/json" \
    -H "Accept-Encoding: gzip" \
    -H "Authorization: Basic Zm9vOmZvbw==" \
    -H "X-Accept-Part-Encoding: gzip" \
    -H "User-Agent: couchbaselite/1.2" \
    -d "{\"docs\":[{\"id\":\"82d38d2ef10a5ce91e67312854cfd6dd\"}]}"
```

Returns

```
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: multipart/mixed; boundary="7a37cfd9cd87c89da08ec779f07777054cea2b5ddd973fc74f755e6d9764"
Server: Couchbase Sync Gateway/1.2 branch/feature/issue_1419_compression_useragent commit/d3da279+CHANGES
Date: Thu, 14 Jan 2016 03:58:25 GMT
Content-Length: 235
Connection: close

--7a37cfd9cd87c89da08ec779f07777054cea2b5ddd973fc74f755e6d9764
Content-Type: application/json

{"_id":"82d38d2ef10a5ce91e67312854cfd6dd","_rev":"1-a678de10f341883c0afd0dff7c1c845b","channels":["ABC"],"hello":"world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-world-wo...
```

Note the `content-encoding: gzip`.

By the way, if you are trying to test this, make sure your doc is over 300 bytes, otherwise it will skip gzip encoding of parts.
