### ISSUE TITLE
[enhancement]Add a new rest api endpoint:support transaction in one request

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1424]
SG have a rest api [POST /{db}/_bulk_docs](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/sync-gateway/rest-api/database/post-bulk-docs/index.html) that can add, update, or delete multiple documents to a database in a single request. but those modifications are independent.
In a common usecase, we need modify multiple documents as one transaction.
such as add 2 docs: doc1 and doc2(may be not only add, but also modify,delete,etc), but only when doc1 was added successfully, doc2 can be added, and only doc1 and doc2 created successfully both,This REST API endpooint can return ok, or the REST API endpoint must return error, and no doc created.

**Comment by adamcfraser** [comment]
This would be more than a Sync Gateway API enhancement - this would require support for multi-document transactions in the underlying data source.  For Couchbase Server this isn't currently the case.
