### ISSUE TITLE
HTTP/2 support needed

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1428]
Is there any plan to support HTTP/2 protocol ? I think HTTP/2 will take a huge performance improvement.

**Comment by tleyden** [comment]
We have a [new replicator](https://github.com/couchbase/sync_gateway/pull/1086) in pre-alpha stage, which has http/2-like properties in terms of minimizing tcp socket overhead.  @snej iirc, did you say that it's theoretically possible for blip to use http/2 as the underlying transport mechanism?

**Comment by snej** [comment]
Probably, depending on what the platform's HTTP2 API looks like. I don't know how that would affect performance compared to BLIP, though.

**Comment by tleyden** [comment]
@snej Go 1.6 is due out in a few weeks which will have HTTP2 support

**Comment by bbrks** [comment]
The replicator in 2.x should be sufficient for improved performance.

There's an unsupported config option to switch on HTTP/2, but has not been extensively tested, both functionally, or performance-wise.

```json
{
  "unsupported": {
    "http2": {
      "enabled": true
    }
  }
}
```
