### ISSUE TITLE
[Distributed Index] sg-accel not installing as service

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1430]
Currently installing the sg-accel package with rpm -i will only copy the binary to /opt/couchbase-sg-accel. It does not launch as a service like the sync_gateway package.

**Comment by tleyden** [comment]
@michaelkwok re-assigning to you

**Comment by sethrosetter** [comment]
Tried with build 1.2.0-32

```
rpm -i /tmp/couchbase-sg-accel-enterprise_1.2.0-32_x86_64.rpm
```

The service installer seems to be looking for the incorrect binary. 
The sync_gateway executable does not exist "/opt/couchbase-sync-gateway/bin/sync_gateway"

**Comment by sethrosetter** [comment]
Right now the rpm -i /tmp/couchbase-sg-accel-enterprise_1.2.0-32_x86_64.rpm is calling into the existing sync_gateway install script (https://github.com/couchbase/sync_gateway/blob/master/service/sync_gateway_service_install.sh) and blows up when trying to find sg_accel binaries

**Comment by tleyden** [comment]
@ajres ideally the [sync_gateway_service_install.sh](https://github.com/couchbase/sync_gateway/blob/master/service/sync_gateway_service_install.sh) script could be parameterized so it could be re-used for the sg_accel binaries -- @sethrosetter mentioned that certain things were hardcoded and wouldn't be appropriate for sg_accel.  Worst case we could duplicate it into sg_accel_service_install.sh to unblock the testing effort.

**Comment by michaelkwok** [comment]
If we do decide to maintain 2 separate install script, then I can include the appropriate file for each corresponding package.

**Comment by adamcfraser** [comment]
I think cloning the existing script is the right approach for 1.2.

**Comment by ajres** [comment]
There is also an upgrade script and an uninstall script which would need updating, cloning might be more work than parameterising.

@sethrosetter can you describe which things are hardcoded and not appropriate for sg_accel? most default values can be overridden by passing arguments to the install script.

**Comment by zgramana** [comment]
Close out once installer is tested on Ubuntu.

**Comment by ajres** [comment]
When testing on Ubuntu, the service was installed but sg_accel panic'd on start as it was using the default config also used for sync_gateway i.e. examples/serviceconfig.json

```
2016-01-22T22:25:14.373Z PANIC: SG is running in sg-accelerator mode but there are databases configured as index readers -- rest.ValidateConfigOrPanic() at config.go:693
panic: SG is running in sg-accelerator mode but there are databases configured as index readers
```

sg_accel needs a new default config for use with the default service installation

**Comment by ajres** [comment]
It looks like there is no way to start sg_accel with a default config, it requires connection to Couchbase Server buckets.

The best option would be to install a template config and when installing the service wrapper do not start the service. Print out instructions for the user to edit the template and then manually start the service.

**Comment by ajres** [comment]
Here is the proposed template, there is an outstanding question about whether "data_dir" should be an absolute or relative path. An absolute path will require a separate Windows template.

```
{
  "log": ["HTTP+"],
  "adminInterface": "127.0.0.1:4985",
  "interface": "0.0.0.0:4984",
  "cluster_config":{
    "server":"http://localhost:8091",
    "bucket":"default",
    "data_dir":"."
  },
  "databases": {
    "default": {
      "server": "http://localhost:8091",
      "bucket": "default",
      "users": {
        "GUEST": { "disabled": false, "admin_channels": ["*"] }
      },
      "channel_index": {
        "writer": true,
        "server":"http://localhost:8091",
        "bucket":"channel_index"
      }
    }
  }
}
```

**Comment by ajres** [comment]
Package post install template messages will be updated to direct users to examples folder  for template config examples.
