### ISSUE TITLE
[DB Online / Offline] POST /db/_offline hangs and does not close long poll changes feed.

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1435]
I was investigating a test hang in Jenkins for this longpoll changes closing test. https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/functional_tests/test_db_online_offline.py#L381-L425

This test was passing until very recently.

Using "Couchbase Sync Gateway/1.2.0(32;256d4b9)"

The scenario is as follow. A user opens a longpoll changes feed with a timeout of 0. 

```
curl -X GET "http://XXX.XX.XXX.XXX:4985/db/_changes?feed=longpoll&since=0&timeout=0&include_docs=true"
```

In another terminal, issue the following command:

```
curl -X POST http://XXX.XX.XXX.XXX:4985/db/_offline
```

Expected behavior
the POST to _offline return 200 and the changes feed is closed

Actual behavior
the POST to _offline blocks, and the longpoll changes feed is never closed

**Comment by sethrosetter** [comment]
I have tried the same against "Couchbase Sync Gateway/1.2.0(25;83ac2d5)" and experienced the expected behavior, so this was introduced between build 25 and build 32

**Comment by ajres** [comment]
The 'break loop' was lost on commit 92c1, which explains the regression, but it is not showing in the diff for that commit, not sure how that would happen unless it's due to squashing the commits?
