### ISSUE TITLE
[Install] Windows 10 install warns that about developer identity when running the .exe

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1449]
Steps to reproduce
- Download the latest sync_gateway .exe for Windows
- Run it on Windows 10

**Comment by zgramana** [comment]
Need to sign with the .NET Authenticode certificate using for CBS.

**Comment by zgramana** [comment]
The build team's tracking ticket is https://issues.couchbase.com/browse/CBD-1743

**Comment by michaelkwok** [comment]
Don't think I can get to this for 1.2.0 release

**Comment by adamcfraser** [comment]
@sethrosetter This is fixed, based on the latest update from Michael.  Assigning to you to retest/validate/close.

**Comment by adamcfraser** [comment]
Verified by @michaelkwok.
