### ISSUE TITLE
Switch from base/logging.go to 'clog' package

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#145]
Dustin's extracted our logging utility into a standalone package called 'clog'. To avoid having multiple copies of the source code, we should remove base/logging.go and instead use github.com/couchbaselabs/clog.

(This won't affect the product; it's just code cleanup.)

**Comment by djpongh** [comment]
Now couchbase/clog

**Comment by bbrks** [comment]
The new logging functionality in SGW 2.1.0 means we don't use the old logging functions any more.

clog is only used in the case of log redaction tagging.
