### ISSUE TITLE
Write new portal docs for SG _purge feature

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1453]
issue #1219 adds a new /db/_purge operation, this needs documenting

**Comment by ajres** [comment]
Documentation notes

The _purge operation supports the removal of documents from an SG bucket. The removed document will no longer replicate to SG clients, this can be useful to remove tombstones of "_deleted" documents that are no longer relevant to the application.

The _purge operation is at the scope of a single DB

```
/{db}/_purge
```

The _purge operation requires admin privileges su must be called on the ADMIN rest interface.

The _purge operation only supports the POST method

To perform a purge operation you must send a JSON object, where the keys are the document IDs to purge and each value is a list of the revisions to purge.

This implementation will only support a single revision of "*", which means purge the complete document revision tree.

```
POST /{db}/_purge
Content-Type: application/json

{
  "doc1" : ["*"],
  "doc2" : ["*"]
}
```

If the revision is is not passed in a JSON array, a message will be logged and the document skipped.

If there is not exactly one revision passed, a message will be logged and the document skipped.

If any revision value other than "*" is passed a message will be logged and the document skipped.

If a document ID is passed that does not exist in the database, a message will be logged and the document skipped.

The response will contain a list of the document IDs and revisions successfully purged. Skipped documents are not listed in the response.

```
{
   "purged" : {
      "doc1" : ["*"],
      "doc2" : ["*"]
   }
}
```

This implementation will always return "*" as the revision for each successfully purged document ID.

This implementation is not compatible with CouchDB as it will not return a "purge_seq" property in the response.

The initial implementation has some potential side effects due to not removing entries from revision caches or changes cache.

When purging a document, a message similar to the following may appear in the Sync Gateway logs

2016-01-13T17:32:32.811Z WARNING: changeCache: Error unmarshaling doc "doc1": unexpected end of JSON input -- db.(*changeCache).DocChanged.func1() at change_cache.go:327

Purged documents may still be returned by _changes and _all_docs calls, but any attempt to retrieve the document itself will fail.

**Comment by ajres** [comment]
See docs portal [PR](https://github.com/couchbaselabs/couchbase-mobile-portal/pull/284)

**Comment by ArihantRk** [comment]
is _purge will propagate through replication as well. replica also deletes from other server?

**Comment by npomfret** [comment]
Is this feature released yet?

**Comment by adamcfraser** [comment]
Yes - documentation here: http://developer.couchbase.com/documentation/mobile/1.2/develop/references/sync-gateway/admin-rest-api/database-admin/post-db-purge/index.html

**Comment by npomfret** [comment]
Sorry, just found it.  Thanks for the reply.

**Comment by npomfret** [comment]
When I purge a doc it still visible in clients _changes feed until I bounce the sync-gateway.  Is that correct?

**Comment by adamcfraser** [comment]
Purge simply removes the document from persistent storage - it doesn't (currently) remove the document from Sync Gateway's in memory caches - particularly the channel and revision caches.

The motivation behind _purge is to provide a way to remove long-obsolete documents, such as tombstones that have already been replicated to all the appropriate clients.  

We're considering a future enhancement to expand purge to cover in-memory storage as well, but it's not in the 1.2 release.
