### ISSUE TITLE
Manual testing of _purge implementation

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1469]
@ajres will put together some docs in #1453 to use for testing guidance.

**Comment by adamcfraser** [comment]
Completed manual testing of purge - didn't find any issues.  Tested the following scenarios - all were working as intended.
- Single doc purge
- Multiple doc purge (existing and non-existing)
- Purge of non-SG doc (after direct write to bucket)
- Attempted purge of non-existent doc
- Duplicate keys in purge payload
- Invalid purge payload
- Multiple purges for same doc
