### ISSUE TITLE
bulk_get compression regression: compressing parts without X-Accept-Part-Encoding: gzip header

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1472]
Referring to this test
https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/functional_tests/test_bulk_get_compression.py

The following behavior was exhibited:

```
curl -X "POST" {0}/db/_bulk_get
```

Last week, with neither  "Accept-Encoding: gzip" nor "X-Accept-Part-Encoding: gzip" in the headers, the response was uncompressed.

Now testing against 1.2.0-47, the results seems to be part compressed when no "Accept-Encoding: gzip" or "X-Accept-Part-Encoding: gzip" header is specified.

**Comment by tleyden** [comment]
I verified this locally -- it is gzipping the parts even if `X-Accept-Part-Encoding: gzip` is not passed in the header.

**Comment by tleyden** [comment]
@sethrosetter can you retest against the `feature/issue_1472_gzip_part_no_header` branch?  (or wait until it's merged to master?)

**Comment by sethrosetter** [comment]
@tleyden also updating . 

```
2016-01-15 14:42:19,229 - INFO - test_bulk_get_compression - no_compression_response size 2244882
2016-01-15 14:42:19,229 - INFO - test_bulk_get_compression - 'Accept-Encoding: gzip' response size 2244882
2016-01-15 14:42:19,229 - INFO - test_bulk_get_compression - 'X-Accept-Part-Encoding-response: gzip' response size 2244882
```

All three header responses were return the expected part encoding size

**Comment by sethrosetter** [comment]
@tleyden I can retest
