### ISSUE TITLE
 Support CouchbaseLite use of row-level sequences (as opposed to using last_seq)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1475]
Steps to repro:
- Run Sync Gateway commit https://github.com/couchbase/sync_gateway/commit/732d490345bd7cc65eb6ace88ba539e0b780105e with config: https://github.com/couchbaselabs/sync-gateway-testcluster/pull/230/files (see https://github.com/couchbaselabs/sync-gateway-testcluster/issues/229)
- Build master branch of couchbase-lite-ios (commit 9d881661babacb812fcf1693779ceeca6843eda1) into a framework
- Checkout master branch of todolite-ios 
- Copy couchbase-lite framework over to todolite-ios
- Point todolite-ios to http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite-di/
- FB login on todolite-ios
- Add a new item to an existing list

Observed errors on todolite-ios: 
https://gist.github.com/tleyden/f1f3665986029a4e825b

**Comment by tleyden** [comment]
@adamcfraser I'm seeing this error in the [logs](https://gist.github.com/tleyden/28a9aee33df3870b2f12):

```
2016-01-16T06:46:31.669Z HTTP:  #168: POST /todolite-di/_changes  (as 778915335487383)
2016-01-16T06:46:31.669Z Debug: Unmarshalling clock sequence: 2
2016-01-16T06:46:31.669Z WARNING: Couldn't interpret error type *errors.errorString, value Error converting hash sequence 388.1 to string: strconv.ParseUint: parsing "388.1": invalid syntax -- base.ErrorAsHTTPStatus() at error.go:63
2016-01-16T06:46:31.669Z HTTP: #168:     --> 500 Internal error: Error converting hash sequence 388.1 to string: strconv.ParseUint: parsing "388.1": invalid syntax  (1.0 ms)
```

**Comment by tleyden** [comment]
I just updated the steps to repro -- I'm seeing the error shortly after adding a new item to the list.

Client logs: https://gist.github.com/tleyden/4ebc0e61a19fd3f62dd1

**Comment by tleyden** [comment]
Actually I take that back, just now after uninstalling and restarting the app, I'm seeing the error.

Client logs, server logs, and server ngrep: https://gist.github.com/tleyden/9e72b9ed161ab1487b19  (unfortunately much of the ngrep output is gzipped)

**Comment by tleyden** [comment]
I did a tcpdump packet capture and opened it locally in wireshark, it looks like todolite-ios is returning an intermediate sequence rather than last_seq.

Here the changes feed response sent to the client by Sync Gw:

<img width="1552" alt="screen shot 2016-01-16 at 12 04 14 pm" src="https://cloud.githubusercontent.com/assets/296876/12374213/70d12984-bc49-11e5-83fc-a7930ab38861.png">

On the next changes feed request, the client sends a since value of `513.1` rather than the lase_seq value of `11-0`:

<img width="1552" alt="screen shot 2016-01-16 at 12 05 49 pm" src="https://cloud.githubusercontent.com/assets/296876/12374220/967d99f6-bc49-11e5-8c46-34d8545dc1d4.png">

**Comment by adamcfraser** [comment]
Based on feedback from the Couchbase Lite team, it's common for clients to use row-level sequences for subsequent changes requests, instead of last_seq. 

There are a few potential solutions for this:
1. Restore hashing of every sequence value for longpoll and one-off changes requests.  Would have a decent performance overhead.
2. For longpoll and one-off changes requests, use a similar approach to what's being used for continuous replication - hash every n sequences, and use that hash as a 'low' value in the sequence.  Would also need to enforce that the last sequence returned gets hashed, to avoid looping.
3. For longpoll and one-off changes requests, use a low value as in #2, but replace the vb.seq value with a binary token storing the information needed to build the full vector clock (i.e. information on all sequences that have been sent since the last hash).

**Comment by tleyden** [comment]
@sethrosetter this is ripe for a failing functional test:
- Add docs 
- Request changes feed with since=0
- Assume 2nd doc returned in changes feed has sequence `355.1`
- Request changes feed with since=355.1

**Actual Behavior**: Sync Gateway returns a 500 error
**Expected Behavrior**: Sync Gateway returns the changes since sequence `355.1`

**Comment by tleyden** [comment]
I redeployed the sync gateway on ec2-54-145-244-2.compute-1.amazonaws.com and retested todolite-ios against ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite-di, and verified that the issue is now fixed.

@ashvindersingh feel free to move forward with todolite client testing
