### ISSUE TITLE
Rebalance -in a CBS node results in timeouts which manifests as empty changes feed

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1488]
Setup: 
Couchbase 3 node cluster with 4.1.0-5005
Sync Gateway + SG_Accel = 1.2.0-53
Client: Sync gateway functional tests suite. 

Scenario:
- With three node CB-cluster and 
- 2 sg index writers and 1 reader
- Add 100 users with sharing 3 channels, 
- Each user creates 100 docs with 10 revision
- While the above operation is going. 
- Do rebalance out a  node from the CB cluster
- Ensure rebalance succeds.
- Rebalance in the same node
- Issue changes feed request from the reader node
  Expected: latest changes
  Observed: empty changes feed with no results and no docs.

**Comment by ashvindersingh** [comment]
Logs: https://issues.couchbase.com/browse/CBL-47

The sg-3 (reader) logs show timeouts at the end of the file. 
The sg-1 and sg-2 are index writers.

**Comment by adamcfraser** [comment]
Based on the logs, it looks like gocb might not be handling the CBS topology change as seamlessly as go-couchbase does (at least with the recent go-couchbase enhancement on that front).  Since gocb is just used for distributed index, will investigate for 1.3.

**Comment by tleyden** [comment]
Can you add steps to reproduce?  Ideally via jebkins job, otherwise with cmd line instructions.

**Comment by tleyden** [comment]
Is there enough info to report a gocb issue?

**Comment by adamcfraser** [comment]
I think we'd need to repro in a simpler test:
1. Point gocb at a multiple-node cluster, using the IP of node A.
2. Start a loop of gocb ops
3. Take down node A
4. See if the ops loop temporarily fails, permanently fails, etc

**Comment by ashvindersingh** [comment]
@tleyden Here are the steps to reproduce in your local environment:
1. Setup and install functinal test framework: https://github.com/couchbaselabs/sync-gateway-testcluster
2. Please edit this test https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/functional_tests/test_multiple_users_multiple_channels_multiple_revisions.py#L23 and increase the number of users and docs to 100 from 10. ("sync_gateway_default_functional_tests_di.json", 100, 3, 100, 10),
4. While the test is running rebalance out a node.
5. Verify rebalance succeeds. 
6. Add back the same node from the web console of the server. 
7. Click rebalance. ensure rebalance completes. 
8. Issue a changes feed request on the reader node from your configuration. http:/reader_ip:4984/db/_changes
9. Observe empty changes feed returns.
10. Issue a changes feed on writer node returns changes as expected.
