### ISSUE TITLE
RetryLoop should return underlying error when it hits retry limit

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1498]
Currently the RetryLoop processing is returning a custom error when the number of retries is exceeded.  

This custom error isn't correctly resolved by ErrorAsHTTPStatus, resulting in some failure states returning a 500 error where they previously returned a more meaningful error.

When possible, RetryLoop should return error returned by the last failed attempt.

**Comment by tleyden** [comment]
> When possible, RetryLoop should return error returned by the last failed attempt.

Yeah, totally agree

**Comment by adamcfraser** [comment]
Fixed as part of PR #1499.
