### ISSUE TITLE
_changes doesn't support ?conflicts=true parameter

### ISSUE THREAD

**Issue by ethanfrey** [couchbase/sync_gateway#1505]
Hi,

For performance reasons, I am transitioning an app from CouchDB v1.4 to Couchbase Sync Gateway 1.1.1. I figured it is pretty straight-forward, just some set up and changing the filters we were using on the push and pull replication with channels.  And adjust the auth mechanism a bit.  Should be no big deal.

BUT.... we happen to resolve conflicts on the server, as we have a somewhat complex method for auto-resolution and only want to do it in one place.  On CouchDB, we had a feed with `/db/_changes?include_docs=true&conflicts=true` and a filter to return only docs where `_conflicts` member existed.  That worked well. I understand that with Sync Gateway, I cannot run a server side filter, so, well, I will stream all changes and then quickly filter out the conflicting ones in my code, before acting on the conflicts streaming in. Easy enough, except the information is not there!

In spite of what it says on http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/sync-gateway/rest-api/database/get-changes/index.html the conflicts=true query parameter has absolutely no effect (and yes, I am sure I have conflicts).  After a few hours, I found a semi-workaround by using `/db/_changes?style=all_docs` This does give me a changes field with a list of all leaf revisions, which is a good start, except it doesn't distinguish between deleted and non-deleted revisions, so my once there is a conflict in an object one time, even after it is resolved, it will trigger my change detection algorithm every time, where I must query the database multiple times to verify that the listed revisions are deleted (okay, I could build some caching mechanism, but I want multiple workers, and it seems like a big headache).

I think the setup is quite clear, generate a conflict on two devices while they are offline, and view the _changes feed on the server show no info. If needed, I can provide an explicit test case.

I dug through the web and found very little info here, notably https://groups.google.com/forum/#!msg/mobile-couchbase/tWn9vVc_vl4/KMdbNg-tD0QJ suggesting to do exactly what I was trying to do (and that doesn't work).  And https://forums.couchbase.com/t/how-to-get-conflicts/1894 saying that conflict detection is not possible on the server at all, only on the clients.

Maybe this is a bug in the implementation, in which case, I hope for a quick fix.  Maybe it is just a documentation issue, possibly related to issue #269, in which case you should update the web site and make it clear that this functionality from CouchDB is not supported at all, or suggesting how one would do this.

This is a currently a _blocker_ for our companies transition, and the incorrect documentation is quite frustrating.  Could you please let me know if this will be fixed as a bug, or if there is an acceptable work-around we can use to get the needed info.  I don't care what the API call is, or what format we get back, just the information on conflicts is available.

Cheers,
 Ethan

**Comment by adamcfraser** [comment]
@ethanfrey It sounds like the proposed enhancement to add an all_active style to changes in https://github.com/couchbase/sync_gateway/issues/1503 might address your use case - it's basically all_docs, excluding deletes and removals.  Can you review and provide input on whether you think covers your needs?

**Comment by ethanfrey** [comment]
Thanks for the quick reply.

Yes, I think the proposal in #1503 would solve this use case quite well (and a few others).  And it would actually be a more efficient solution than the `_conflicts` query I am using now (as it requires `include_docs=true`) Is this on the short-term roadmap?

And is `_changes?conflicts=true` officially unsupported (please note that in the docs) or failing due to a bug?  It would be good to know.

Currently, a co-worker suggested I might be able to see this information in the sync function and then set these documents to a "conflicts" channel to be picked up on a feed.  Would be great, but I don't know what info I have in the sync function, just digging in there now, any references are welcome.

**Comment by ethanfrey** [comment]
For a documentation review, I decided to compare http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/rest-api/database/get-changes/index.html with `src/github.com/couchbase/sync_gateway/rest/changes_api.go` in the master branch.

If I look at the strings that are parsed from the query string into options, I that the GET request supports the following:
- since
- limit
- style (only allowed: all_docs)
- include_docs
- filter (only allowed: sync_gateway/bychannel) 
- channels
- doc_ids
- heartbeat
- timeout

The POST request supports the same as well as:
- feed
- accept_encoding (gzip compression, nice!)

The following parameters are listed in the documentation but are completely ignored by the codebase:
- attachments
- att_encoding_info
- conflicts
- descending
- last-event-id
- view

Please correct me if I am wrong.

**Comment by zgramana** [comment]
I'm going to close this as a dup of #1503, but filed a new docs issue for the last item: #1507.

**Comment by ethanfrey** [comment]
Fair enough.  I'm going to try to pull the fix from #1503 (now on master I see) and test it. 

@adamcfraser  Very fast response time with the feature change. Thanks!

**Comment by adamcfraser** [comment]
@ethanfrey What type of changes feed are you using for your use case (continuous, longpoll, one-shot, etc)?  For the Couchbase Lite use case, we only want active_only to apply for the initial iteration of a continuous changes feed (see #1576).  I'm trying to work out whether that breaks your use case.

**Comment by ethanfrey** [comment]
Sorry for the slow response, I didn't see this notification.

We are using a continuous change_feed for a server component that responds to conflicts by doing intelligent merging with more info than available on any device.  We could use another type if it is efficient for server polling. Currently running off the compiled master branch after the feed is merged, so no changes broke our code... until we update.

Please let me know if the changes were made and if there is a work-around we can do to get only a list of nodes where there are conflicts of non-deleted nodes.

@sinnedh will be taking over this issue from our side, so I mention him so he can respond later.

**Comment by adamcfraser** [comment]
@ethanfrey @sinnedh At this point we haven't made the change described in #1576 yet, so you should be fine with what's on master (the continuous changes feed will stay active-only indefinitely).  

For your second question - are you looking for something like a 'conflicts_only' changes filter?
