### ISSUE TITLE
Duplicate doc ids in changes feed for docs removed from a subset of user channels

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1508]
In the following scenario, a user will see multiple revisions of the same docID  in a _changes response:
1. User has access to channels A and B
2. In rev-1, doc_1 is in channel A.
3. In rev-2, doc_1 is removed from channel A and moved to channel B.
4. In rev-3, doc_1 is updated, remains in channel B.

For a since=0 changes request, the response for this user will include both rev-2 and rev-3: rev-2 as a removal from channel A, and rev-3 as the active entry in channel B.

**Comment by adamcfraser** [comment]
@snej From a client replication perspective, do you know whether this is "working as intended" or a potential problem?

**Comment by snej** [comment]
It's not _correct_ to have the same docID appear in more than one feed item, but I'm pretty sure it won't cause trouble. I'd have to look closely at the puller code to be sure, though.

**Comment by adamcfraser** [comment]
This doesn't look like a new issue - I see the same behaviour when running SG 1.1.1 - but we should review whether there's a potential fix in 1.3.

**Comment by adamcfraser** [comment]
Closing based on age, and as it's required in order to support interruptions to replication.
