### ISSUE TITLE
Seeing "503 Database server is over capacity" pushing docs w/ large attachments

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1510]
While pushing approx 50-100 docs with large attachments, I noticed this error in the [SG logs](https://gist.github.com/tleyden/ad5f51e55518ea67a0da#file-sg-logs):

```
503 Database server is over capacity  (12388.0 ms)
```

when verifying https://github.com/couchbase/couchbase-lite-ios/issues/1059#issuecomment-174384184

I logged into the Couchbase Server web ui and the usage looked relatively light.  
- SG version: https://github.com/couchbase/sync_gateway/commit/089dddf72c1b09ae40221523cda4b414c8717d0c
- SG url: http://ec2-54-145-244-2.compute-1.amazonaws.com:4985/deepstyle-cc/
- SG config: https://gist.github.com/tleyden/5f9a0c79036bffdc9c37
- SG mode: channel cache

I will leave the cluster in the current state, I'm assuming it should be relatively easy to repro using [these steps](https://github.com/couchbase/couchbase-lite-ios/issues/1053)

**Comment by adamcfraser** [comment]
It looks like we're returning that error when Couchbase returns a temporary failure error (gomemcached.TMPFAIL).  For the same error gocb returns "A temporary failure occurred.  Try again later.".

**Comment by tleyden** [comment]
After chatting with @mcpaddy this is looking like I'd misconfigured the Couchbase Server bucket to have too low of memory for the amount of data being shoved into it at a high rate.

Doesn't look like an SG issue, especially since there weren't any observed errors aside from some alarming looking errors in the logs.

**Comment by tleyden** [comment]
Some notes from conversation:
- Couchbase supports DGM, and will shuttle items from memory -> disk when running into memory pressure
- Items must be persisted to disk before they can be evicted from memory
- In this case, items were being pushed to Couchbase Server and filling up memory faster than they were being pushed to disk, and therefore could not be evicted fast enough
- When this happens, Couchbase Server (memcached I believe) will return `temp_oom` errors
