### ISSUE TITLE
sync_gateway fails to install service on Debian

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1517]
http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.2.0/1.2.0-65/couchbase-sync-gateway-enterprise_1.2.0-65_x86_64.deb

Steps to repoduce:

Using Debian GNU/Linux 8 (jessie)
1. wget http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.2.0/1.2.0-65/couchbase-sync-gateway-enterprise_1.2.0-65_x86_64.deb
2. dpkg -i couchbase-sync-gateway-enterprise_1.2.0-65_x86_64.deb

Fails with 

```
root@debian:/home/seth# ERROR unknown OS "Debian"
```

**Comment by falsecrypt** [comment]
Any news on Debian support?

**Comment by timecamp** [comment]
I manage to install this on Debian 8:

```
# GO LANG 1.6 TO COMPILE SYNC GATEWAY
curl -O https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz
tar -xvf go1.6.linux-amd64.tar.gz
mv go /usr/local
export PATH=$PATH:/usr/local/go/bin
#echo "export PATH=$PATH:$HOME/go/bin:/usr/local/go/bin" >> ~/......
#source ~/.....
#mkdir -p ~/go; echo "export GOPATH=$HOME/go" >> ~/.bashrc

# COACHBASE SYNC GATEWAY
cd ~
go get -u -t github.com/couchbase/sync_gateway
cd $GOPATH
./src/github.com/couchbase/sync_gateway/tools/manifest-helper -u
cp bin/sync_gateway /usr/local/bin
#RUN COMMAND: sync_gateway /var/www/uuu/couchbase/demo/sync-gateway-config.json
```

**Comment by ajres** [comment]
Added support for Debian 8, using systemd init serivce
