### ISSUE TITLE
Panic in sync_gateway if db is over capacity (sequence rollback, sg_accel)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1523]
I'm not really sure what the expected behavior is here. 

I am seeing a panic when a db is over resourced. 

https://gist.github.com/sethrosetter/f02ac6c062cab9e3d039#file-gistfile1-txt-L316

This is using sync_gateway eb6fd2159ae5ffba1b40c76261540768f2a13fbb and can be reproduced by running the following test in sync-gateway-tests using an 

```
node tests/cbl-large-revisions.js
```

using an admin_party_cb.json that looks like:

```
{
    "log": ["CRUD", "REST+", "CHANGES"],
    "skip_runmode_validation" : true,
    "cluster_config": {
        "server":"http://localhost:8091",
        "data_dir":".",
        "bucket":"db"
    },
    "databases": {
        "db": {
            "feed_type":"DCPSHARD",
            "server": "http://localhost:8091",
            "bucket":"db",
            "sync": `
function(doc){
    channel(doc.channels);
}`,
            "users": {
                "GUEST": {"disabled": false, "admin_channels": ["*"] }
            },
            "channel_index":{
                "server":"http://localhost:8091",
                "bucket":"db-index",
                "writer":true
            }
        }
    }
}

```

**Comment by sethrosetter** [comment]
Bumping the ramQuotaMB=1000 for the db bucket above resolved the panic.

**Comment by adamcfraser** [comment]
Expect this to be fixed when rollback support is completed (https://github.com/couchbase/sync_gateway/issues/1963)

**Comment by adamcfraser** [comment]
This issue was moved to couchbaselabs/sync-gateway-accel#25
