### ISSUE TITLE
TodoLite list wasn't correctly shared / deleted tasks didn't propagate using SG DI (pre test-fest)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1524]
In preparation for the test-fest, we did smoke testing against http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite12rc2-di/ -- we used this to prevent polluting http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite12rc2-cc/ which was the intended test-fest target.  We ran into a few issues.

Steps to repro:
- Test against http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite12rc2-di/ (1.2 distributed index)
- [SG Config](https://gist.github.com/tleyden/e50d5434db6a5886ba0a)
- Ashvinder running todolite-ios version ? and couchbase lite ios version (release/1.2)
- I'm running couchbase lite ios version from release/1.2 and todolite ios mater
- When Ashvinder adds a list and shares with me, I don't see it
- Seth running TodoLite-Android at commit - 15526b74b83bdac6d2d4a75779e75780e42699c2, release/1.2.0-sqlite
- I shared an "everyone" list and shared with Seth and Ashvinder, and added two items -- Seth deleted both of them, I never saw them deleted on my side.

Unable to repro on http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite12rc2-cc/, which indicated that it was a DI-specific issue.

[SG logs for both runs](https://gist.github.com/tleyden/4405665868483824d2cb)

**Comment by tleyden** [comment]
I just tried running a fresh install against http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite12rc2-di/, and it was able to see the lists that were not shown before:

![screen shot 2016-01-27 at 9 41 06 am](https://cloud.githubusercontent.com/assets/296876/12622439/34d04e1c-c4da-11e5-95b9-138d15f095bc.png)

**Comment by tleyden** [comment]
Changes requests from my device:
- HTTP #626 https://gist.github.com/tleyden/4405665868483824d2cb#file-gistfile1-txt-L1404
- HTTP #920 https://gist.github.com/tleyden/4405665868483824d2cb#file-gistfile1-txt-L4423 (terminated, probably killed from client side)

List activity happens between [HTTP #650 and ~#800](https://gist.github.com/tleyden/4405665868483824d2cb#file-gistfile1-txt-L1637-L2720)

**Comment by tleyden** [comment]
1. Ashvinder grants access to me for the list
2. My user doc is updated
3. Expected: wake up changes feed for my user
4. Actual: changes feed never woken up, and so I don't see the new changes

Apparently I didn't even get access to my own `everyone` list, which explains why I didn't see Seth's deletes.

**Comment by adamcfraser** [comment]
It looks like tleyden's client's changes feed isn't being notified (woken up) when access() grants happens, so isn't seeing any updates since the longpoll _changes request issues at HTTP-#626.
