### ISSUE TITLE
Longpoll _changes request that returns no results, returns invalid sequence number for last_seq

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1529]
Steps to reproduce:

Using - Couchbase Sync Gateway/1.2.0(66;eb6fd21)

Issue the below CURL request and wait for it to time out, using a user that exists with no documents in the their channel.

```
curl -X "POST" "http://172.23.122.253:4984/db/_changes" \
    -H "Authorization: Basic YWNjZXNzX2RvY19wdXNoZXI6cGFzc3dvcmQ=" \
    -H "Content-Type: application/json" \
    -d "{\"include_docs\":true,\"feed\":\"longpoll\",\"style\":\"all_docs\",\"timeout\":10000,\"since\":0}"
```

This should be the result. 

```
{
  "results": [],
  "last_seq": "0.0"
}
```

Using that sequence number as the since, issue another CURL request

```
curl -X "POST" "http://172.23.122.253:4984/db/_changes" \
    -H "Authorization: Basic YWNjZXNzX2RvY19wdXNoZXI6cGFzc3dvcmQ=" \
    -H "Content-Type: application/json" \
    -d "{\"include_docs\":true,\"feed\":\"longpoll\",\"style\":\"all_docs\",\"timeout\":10000,\"since\":\"0.0\"}"
```

sync_gateway returns the below error. 

```
Couldn't interpret error type *errors.errorString, value Error converting hash sequence 0.0 to string: strconv.ParseUint: parsing "0.0": invalid syntax -- base.ErrorAsHTTPStatus() at error.go:63
2016-01-27T22:52:04.822-08:00 HTTP: #008:     --> 500 Internal error: Error converting hash sequence 0.0 to string: strconv.ParseUint: parsing "0.0": invalid syntax  (156.6 ms)
```

**Comment by adamcfraser** [comment]
On timeout/other failure, last_seq should get returned as the since value.  Need to compare this with the channel cache handling of the same scenario, to see what's returned.

**Comment by tleyden** [comment]
Specifically for a longpoll that times out -- not sure if any clients are using the last_seq field.  Need to confirm if that's the case for ios, android, etc.

@hideki can you confirm if the last_seq returned from the changes feed is used to store the local checkpoint?

**Comment by ajres** [comment]
The issue is in the rendering of an "empty clock"

In `sequence_id.go`  `func parseClockSequenceID` will convert a since=0 to an empty clock.

The code segment that creates the clock is `base.NewSequenceClockImpl`:

```
func NewSequenceClockImpl() *SequenceClockImpl {
	// Initialize empty clock
	clock := &SequenceClockImpl{
		value: make([]uint64, KMaxVbNo),
	}
	return clock
}
```

In `sequence_id.go` in db.clockSeqToString(), the "empty clock" clockSequence is currently rendered in the final else block.

This logic needs to be updated to recognise the "empty clock" and render a a single binary zero "0".


```
func (s SequenceID) clockSeqToString() string {

	// If TriggeredBy hash has been set, return it and vbucket sequence as triggeredByHash:vb.seq
	if s.TriggeredByClock != nil && s.TriggeredByClock.GetHashedValue() != "" {
		return fmt.Sprintf("%s:%d.%d", s.TriggeredByClock.GetHashedValue(), s.vbNo, s.Seq)
	} else {
		// If lowHash is defined, send that and the vbucket sequence as lowHash::vb.seq
		if s.LowHash != "" {
			return fmt.Sprintf("%s::%d.%d", s.LowHash, s.vbNo, s.Seq)
		}
		// If the clock hash has been set, return it.  Otherwise, return vbucket sequence as vb.seq
		if s.ClockHash != "" {
			return s.ClockHash
		} else if s.Clock != nil && s.Clock.GetHashedValue() != "" {
			return s.Clock.GetHashedValue()
		} else {
			return fmt.Sprintf("%d.%d", s.vbNo, s.Seq)
		}
	}
}
```

**Comment by adamcfraser** [comment]
As mentioned above - we don't want to return last_seq=0 in this scenario; we want to return last_seq = since.  So I think it may be more about initializing last_seq to since, instead of handling the zero case.

**Comment by ajres** [comment]
Yes, that's whats happening here, if "since=0" is passed in the _changes request it is parsed to generate a SequenceID, then that is used to render the last_seq value on the response if the request times out.

The issue is that between being parsed into an "empty clock" and then rendering that clock results in the "0.0" last_seq value instead of "0".

**Comment by adamcfraser** [comment]
Ah ok - thanks for the clarification.
