### ISSUE TITLE
Sync gateway fails to handle request _all_docs?startkey=

### ISSUE THREAD

**Issue by iOliverNguyen** [couchbase/sync_gateway#1530]
Hi guys,

I sent a request `GET /db/_all_docs?startkey=%22id%22`
and the sync gateway responsed 200 OK but with an error message:

```
{"rows":[
{"error":"Internal Server Error","reason":"Internal error: error executing view req at http://127.0.0.1:8092/db/_design/sync_housekeeping/_view/all_docs?reduce=false\u0026stale=false\u0026startkey=%22%22id%22%22: 400 Bad Request - {\"error\":\"bad_request\",\"reason\":\"invalid UTF-8 JSON: {{error,garbage_after_value},\\\"\\\\\\\"\\\\\\\"id\\\\\\\"\\\\\\\"\\\"}\"}\n"}
```

Sync gateway version: 1.1.1, 1.2.0-rc1
Couchbase version: 4.0.0-CE

**Note:**
Request `GET /db/_all_docs?keys=%5B%22id1%22%5D` is ok.

**Comment by adamcfraser** [comment]
It looks like the problem is the double-quoting of your value.  GET /db/_all_docs/startkey=id should work.

**Comment by iOliverNguyen** [comment]
Yeah. But I think because sync gateway implements CouchDB API, it should handle double quote correctly. The reason I got this because I used PouchDB on client and it sent the mentioned request.

Link [1] says that `startkey` must be a proper URL encoded JSON value.

Link [2] gives an example with double quote:
`GET /somedatabase/_all_docs?startkey="doc2"&endkey="doc3" HTTP/1.0`

[1] http://wiki.apache.org/couchdb/HTTP_view_API#Querying_Options
[2] https://wiki.apache.org/couchdb/HTTP_Document_API#all_docs
