### ISSUE TITLE
[Distributed Index] Panic in integration tests

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1532]
Using sync_gateway - eb6fd2159ae5ffba1b40c76261540768f2a13fbb

```
node tests/cbl-replication-mismatch-2-gateways.js
```

https://gist.github.com/sethrosetter/f26d5121eec67a9c9786#file-gistfile1-txt-L156

**Comment by sethrosetter** [comment]
Full test run logs - https://gist.github.com/sethrosetter/1e5d0cbce0b139f8bae8

**Comment by adamcfraser** [comment]
How many Sync Gateways are being run in this test?  The full test run logs only seem to show one Sync Gateway, that's getting assigned all 64 partitions.  Is that correct?

**Comment by ashvindersingh** [comment]
There are two sync gateways. With liteserv having two dbs. Each pointing to different sync gateway. Liteserv then sets up push/pull replication on both dbs. Creates docs on the dbs. And then checks the changes feed on both dbs that they contain the expected docs.

**Comment by adamcfraser** [comment]
Can we get logs and configs for both Sync Gateways?  The provided test run logs don't really shed light on what's going on, or provide enough information to reproduce.

**Comment by sethrosetter** [comment]
sg1 config - http://localhost:9889/_config

```
{
"Interface": ":9888",
"AdminInterface": ":9889",
"Log": [
"CRUD",
"REST+",
"CHANGES"
],
"Databases": {
"db": {
"server": "http://localhost:8091",
"pool": "default",
"bucket": "db",
"name": "db",
"sync": "\nfunction(doc){\nchannel(doc.channels);\n}",
"users": {
"GUEST": {
"name": "",
"admin_channels": [
"*"
],
"all_channels": null
}
},
"feed_type": "DCPSHARD",
"channel_index": {
"server": "http://localhost:8091",
"bucket": "db-index",
"writer": true
}
}
},
"cluster_config": {
"server": "http://localhost:8091",
"bucket": "db",
"data_dir": "."
},
"skip_runmode_validation": true
}
```

sg2 - http://localhost:9891/_config

```
{
"Interface": ":9890",
"AdminInterface": ":9891",
"Log": [
"CRUD",
"REST+",
"CHANGES"
],
"Databases": {
"db": {
"server": "http://localhost:8091",
"pool": "default",
"bucket": "db",
"name": "db",
"sync": "\nfunction(doc){\nchannel(doc.channels);\n}",
"users": {
"GUEST": {
"name": "",
"admin_channels": [
"*"
],
"all_channels": null
}
},
"feed_type": "DCPSHARD",
"channel_index": {
"server": "http://localhost:8091",
"bucket": "db-index",
"writer": true
}
}
},
"cluster_config": {
"server": "http://localhost:8091",
"bucket": "db",
"data_dir": "."
},
"skip_runmode_validation": true
}
```

**Comment by adamcfraser** [comment]
The failure appears to be happening during CAS retry on a write of a channel clock.  That would suggest that more than one Sync Gateway is writing information for the same partition and vbucket to the cluster.

Improved handling for this scenario is planned for 1.3, to handle cases during partition handoff between Sync Gateway nodes, where it's valid for multiple gateways to be attempting to index the same vbucket at once.

In the context of this test, however, I wouldn't expect this to happen.  Hopefully the full SG logs will shed some light on whether this was a case of both gateways indexing the same data, or potentially a case of the index not being flushed prior to the test start.

**Comment by sethrosetter** [comment]
https://gist.github.com/sethrosetter/3783eeca6963e57e0c22 - sg1 panic logs

**Comment by sethrosetter** [comment]
https://gist.github.com/sethrosetter/88b9ee583dd03422f4e8 - sg2 logs

**Comment by tleyden** [comment]
I just noticed that it's using the same directory for the pindex files (these sync gw's are running side by side, directly on osx), which could be causing issues.

We're going to try using separate directories.

**Comment by adamcfraser** [comment]
If you're going to rerun, is it quick to switch to \* logging?  That might also help.

**Comment by sethrosetter** [comment]
Tried with different data dirs for the two sgs. That seemed to resolve the issue. No panics and the tests succeeded.

**Comment by ashvindersingh** [comment]
This test needs a review. The way it was designed it is not applicable to run with Distributed index enabled.
