### ISSUE TITLE
Sync Gateway config.json as a template with env variable substitution

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1533]
Spun out of user request at https://forums.couchbase.com/t/sync-gateway-config-with-environment-variables/6071

It seems like it should be relatively easy to run the configuration file through a go text template and substitute any instances of:

```
{{ .Env.WHATEVER }}
```

with the contents of the `$WHATEVER` environment variable if it's defined, or "" if it's not defined.

**Comment by derekdon** [comment]
I need something like this as my database / sync gateway containers are scaled up in docker cloud. Each database node in my cluster has a Couchbase Server and Sync Gateway container on it and uses bridge networking. Using localhost:8091 doesn't seem to work, and I don't believe I can use database:8091 as database is the service name and what I really need is database-1:8091, database-2:8091, and database-3:8091 etc. Currently each sync gateway container is loading the same config from a gist file. I probably need to use a volume and some sort of template / text replacement like you suggested to substitute a placeholder with one of the $DOCKER bla env variables. I'm not sure how to go about the text replacement within the container / bash or whatever... 

Found this: https://theagileadmin.com/2015/11/12/templating-config-files-in-docker-containers/

Based on the links in that article, something like this might work:

> **sed inline replacement**
> Use a startup script to edit your config file and replace values in it with the values of the environment variables using sed before runnin your app:

```
/app/bin/boot
#!/bin/bash
sed -i "s/xxxTEXTxxx/${TEXT}" /app/example/example.conf
python /app/example/app.py
```

**Comment by tleyden** [comment]
This was brought up again on a forums post: https://forums.couchbase.com/t/bucket-password-in-sync-gateway-config-file/12951/2

So I'm going to pull it out of the icebox and put it in incoming to see if it can get rescheduled.

**Comment by adamcfraser** [comment]
Closing based on age - needs to be prioritized in conjunction with general container/operator integration.
