### ISSUE TITLE
Unable to update docs taking too long after SG restart

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1540]
Found: SG-1.2.0-69
LiteServ: 1.2.0-101

Found when run in DI index mode. 
Scenario:
- Using liteserv, setup two dbs
- Setup push and pull replication on both db
- Add docs to both dbs
- Kill SG
- restart SG
- try updating docs

Unable to update docs within 5mins causing script to fail. 

test script: https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-replication-mismatch-restart-cb.js

jenkins run: http://qa.sc.couchbase.com/view/mobile/job/mobile-integration-tests-cbserver-sync-gateway-cblitios-liteserv/13/consoleFull

**Comment by adamcfraser** [comment]
This seems like it's most likely a test framework issue - can you provide more specifics on how this is failing, particularly with some details from the SG logs for the calls that are timing out?

**Comment by ashvindersingh** [comment]
Rerun of the test did not generate any errors. 
logs: https://gist.github.com/c4528593ed048744db62

```
>>>>>>>>>>>>>>>>>>>cbl-replication-mismatch-restart-cb.js Mon Feb 01 2016 12:50:51 GMT-0800 (PST): 102852.723ms
2016-02-01T12:52:34.649-08:00 HTTP:  #262: PUT /db/_local/42b76326bcb7045cfb92605c76f0f8c8577e6761
2016-02-01T12:52:34.655-08:00 HTTP:  #263: PUT /db/_local/cc296112937df265a069e43deb7cab8dcbd682e3
2016-02-01T12:52:34.649-08:00 HTTP:  #262: PUT /db/_local/42b76326bcb7045cfb92605c76f0f8c8577e6761
2016-02-01T12:52:34.655-08:00 HTTP:  #263: PUT /db/_local/cc296112937df265a069e43deb7cab8dcbd682e3

# done

1..34
# tests 34
# pass  34

# ok
```
