### ISSUE TITLE
Unable to recreate test databases when syncgateway restarted

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#1541]
SG-1.2.0-69
LiteServ: 1.2.0-101

Distributed index enabled. Run in mixed mode. 
Scenario:
- Using liteserv create testdb
- Setup push pull replication
- Load DB
- Verify docs replicated
- Kill SG
- del db
- launch sg

Cannot create db again. Timeout occurs in test. 

Script: https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-restart.js

Jenkins run: http://qa.sc.couchbase.com/view/mobile/job/mobile-integration-tests-cbserver-sync-gateway-cblitios-liteserv/13/consoleFull

**Comment by adamcfraser** [comment]
Can you paste an excerpt from the test output where you think there's an SG issue?

**Comment by ashvindersingh** [comment]
We were successfully able to delete and then recreate a database when manually tried. When tried from liteserv the liteserv hangs. So this is not a sync gateway issue.
