### ISSUE TITLE
Switch to CLA Assistant

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1545]
CLA signing is making open source contributions higher friction than they need to be

https://cla-assistant.io/

**Comment by pritambaral** [comment]
+1

I was just asked to sign the CLA on http://review.couchbase.org, but I can't even register on that site.

**Comment by bbrks** [comment]
http://review.couchbase.org uses GitHub accounts. Should be able to log in and sign the CLA as per step 1 below:

https://developer.couchbase.com/open-source-projects/#how-to-contribute-code

I don't think there are any plans to switch to another CLA mechanism, so closing out.
