### ISSUE TITLE
get all the user with a role

### ISSUE THREAD

**Issue by gine** [couchbase/sync_gateway#1553]
At the moment to get the list of the user assigned to a role you need to get all the users and then cycle on them to get info of the user and then compare their roles with a role passed.

I think that can be usefull that function on rest API:
GET _users/`role_name`

or return the list of user assigned to a role on that call:
GET _role/

or maybe if you prefer leave the old behavior:
GET _role/_users

**Comment by adamcfraser** [comment]
@gine This would require a new view to support retrieval of users by role.  To help us with prioritization of this feature, can you provide some more specifics on your use case for this functionality?

**Comment by househippo** [comment]
@gine , Why not use N1QL.

Quick and Dirty.

`SELECT * FROM {bucket_name} WHERE name IS NOT MISSING AND all_channels IS NOT MISSING;`

**Comment by gine** [comment]
@househippo 
i don't know N1QL

@adamcfraser 
i need on my angular application, an input field(select) with a list of user with a specific role. Chosing a user from this list, i assign to him a channel with the id of the document.

In another case i need only a list of db_user who are in 2 specific roles.

**Comment by househippo** [comment]
@gine 
N1QL is easy. Its Just like SQL but for JSON.
Here is a playground for it: http://query.pub.couchbase.com/tutorial/#1

**Comment by househippo** [comment]
@gine 

Below is a user in couchbase server. 
Who is admin of two channels "fishing" and "biking"
![screen shot 2016-03-03 at 6 23 23 pm](https://cloud.githubusercontent.com/assets/4956099/13516240/2ce8f3a2-e16d-11e5-9381-16c71fce7348.png)

**Comment by househippo** [comment]
@gine 

A simple query to find all the USERS and their channels would look like this:

>  SELECT admin_channels FROM default WHERE admin_channels IS NOT MISSING;

Your request of: 

> In another case i need only a list of db_user who are in 2 specific roles.

This should do it.

> SELECT name FROM default WHERE admin_channels.biking IS NOT MISSING AND admin_channels.fishing IS NOT MISSING ;

OUTPUT

> {
>     "requestID": "d9cfe607-3cb4-4272-a8e1-5cd1e760656c",
>     "signature": {
>         "id": "json"
>     },
>     "results": [
>         {
>             "id": "kevin"
>         }
>     ],
>     "status": "success",
>     "metrics": {
>         "elapsedTime": "11.314868ms",
>         "executionTime": "11.270953ms",
>         "resultCount": 1,
>         "resultSize": 48
>     }

}

**Comment by adamcfraser** [comment]
Closing based on age, and discussion of alternatives.
