### ISSUE TITLE
MQTT broker support

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1555]
Gateway module to allow it to act as a broker for MQTT data. This allows SG to directly ingest data from MQTT networks, run map reduce on them, and additionally push results into a channel--even to an upstream Sync Gateway.

Preliminary requirements:
- Bridge MQTT topics to SG channels.
- Optimize for ForestDB storage engine.
- Support incremental reductions.
- Support reduce 'into'.

**Comment by atom992** [comment]
+1

**Comment by adamcfraser** [comment]
Closing based on age.
