### ISSUE TITLE
issues starting sync_gateway 1.2

### ISSUE THREAD

**Issue by domutom** [couchbase/sync_gateway#1563]
Hi there, having an issue starting sync_gateway with my current config file:
FATAL: Failed to start HTTP server on xxx.xxx.xxx.xxx:4984: listen tcp xxx.xxx.xxx.xxx:4984: bind: address already in use -- rest.(*ServerConfig).serve() at config.go:591

Did I miss a something to configure differently?

**Comment by ajres** [comment]
@domutom 

If you installed SG 1.2 from a package then a service called 'sync_gateway' will be created and started automatically.

It looks like that's what has happened here.

On Ubuntu or RedHat a new sync_gateway user will have been created, the service will start SG using the sync_gateway.json config in the home directory of that user. Replace sync_gateway.json with the contents your own config and restart the sync_gateway service.

Which OS type and version are you installing on? I can provide specific commands for starting and stopping the service.

**Comment by domutom** [comment]
Hi Andrew,

Thanks a lot, Andrew. I´m on Centos 6.7 

Am 04.02.2016 um 12:27 schrieb Andrew Reslan notifications@github.com:

@domutom

If you installed SG 1.2 from a package then a service called 'sync_gateway' will be created and started automatically.
It looks like that's what has happened here.
On Ubuntu or RedHat a new sync_gateway user will have been created, the service will start SG using the sync_gateway.json config in the home directory of that user. Replace sync_gateway.json with the contents your own config and restart the sync_gateway
 service.
Which OS type and version are you installing on? I can provide specific commands for starting and stopping the service.
—
Reply to this email directly or 
view it on GitHub.

**Comment by ajres** [comment]
@domutom 

For centos 6, the common service control commands are:

initctl start sync_gateway
initctl stop sync_gateway
initctl restart sync_gateway

**Comment by zgramana** [comment]
@domutom let us know if you have any further problems.

**Comment by gauravdhungana** [comment]
Hi,

I'm having the exact same problem as @domutom had except I'm on Ubuntu 14.04. 
I followed @ajres suggestion above where I changed the contents of sync_gateway.json with my own (after changing permissions). No luck. What could I be missing?
