### ISSUE TITLE
Admin hostname not binding to specified address

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#1565]
I changed the below setting in the config *.json file and in the startup its outputing that its binding to it. 

> "adminInterface":"10.0.2.15:4985"

but curl-ing is returns error and netstats is saying its binding to localhost.

![screen shot 2016-02-04 at 5 36 31 pm](https://cloud.githubusercontent.com/assets/4956099/12835611/96f169a4-cb66-11e5-9dd7-1ee054eae516.png)

**Comment by tleyden** [comment]
The logs are cut off .. can you copy and paste into a gist rather than a screenshot?

**Comment by tleyden** [comment]
Are there any other sync gateways running on the machine?

**Comment by adamcfraser** [comment]
That error in the logs looks like the start of "FATAL: Failed to start HTTP server on 10.0.2.15:4984: listen tcp 10.0.1.22:4985: bind: can't assign requested address".  Along with Traun's suggestion, you'd also get that error if 10.0.2.15 isn't the IP assigned to the machine.

**Comment by househippo** [comment]
Adman,
I see it.

>   err := base.ListenAndServeHTTP(addr, maxConns, config.SSLCert, config.SSLKey, handler, config.ServerReadTimeout, config.ServerWriteTimeout)
>   if err != nil {
>       base.LogFatal("Failed to start HTTP server on %s: %v", addr, err)
>   }

Traun,
(we talked at lunch) I tried downloading and use the GA of SG 1.2 from couchbase.com/download  
after installing the _.deb I only saw the bin/sync_gateway and no sg_accel
I went back to the couchbase.com/download to find a separate SG_ACCEL build but couldn't find it.
*_BUILD FROM SOURCE**
So I cloned from master branch built from source today.
so now I can do   bin/sg_accel config-dcpshard.json &

and then this Admin hostname issue popped up.  Funny it was working fine on last weeks build on last weeks source built. So curling http://127.0.0.1:4985 return json.  

ill do a pkill -f sg_accel   & syng_gateway  to make all process are not running and I'll  start up sg_accel get the output.

**Comment by househippo** [comment]
Found it & it working again.

> couchbase@ubuntu:~$ curl http://10.0.2.15:4985
> {"ADMIN":true,"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":1.2},"version":"Couchbase Sync Gateway/master(fb1bbbb)"}

an old sync_gateway process was running under a different user.

please mark as closed.
