### ISSUE TITLE
On Windows Sync Gateway gets installed to the root level Couchbase folder

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1567]
When using the Windows installer both Sync Gateway and SG Accel get installed to the same directory:

C:\Program Files (x86)\Couchbase

This has no operational impact as all .exe and .json file names are unique.

LICENSE.txt README.txt and VERSION.txt are duplicated in both products.

The Windows Installer allows users to select different directories, but most users will probably not read the install path.

Couchbase Server default install directory is:

C:\Program Files (x86)\Couchbase\Server

The default directories for SG and SG_Accel could be changed to:

C:\Program Files (x86)\Couchbase\sync_gateway
C:\Program Files (x86)\Couchbase\sg_accel

**Comment by ajres** [comment]
SG 1.1.1 currently installs to C:\Program Files (x86)\Couchbase, moving the directory might cause issues upgrading. Also uninstalling SG where CBS and SG_Accel are installed under the same folder might cause issues, this will need testing.

**Comment by adamcfraser** [comment]
Key work here is to identify how to handle the upgrade scenario.

**Comment by djpongh** [comment]
Moving off of InstallShield for 2.0
