### ISSUE TITLE
sg_accel still reports as 'Couchbase Sync Gateway' on REST API

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1568]
Once sg_accel is split into a separate repo make sure that the response from the REST API 'host:4985/' end point returns the correct vendor and version info.

Currently it reports as 'Sync Gateway':

```
"vendor":{"name":"Couchbase Sync gateway","version":1.2},"version":"Couchbase Sync Gateway/1.2.0"}
```

**Comment by bbrks** [comment]
Was probably fixed a while back, but no longer relevant.
