### ISSUE TITLE
Windows InstallShield installer fails when upgrading an existing SG 1.1.1 installation

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1573]
Opened this ticket to track potential new issue with SG Windows installer posted on #1564.

**Comment by ajres** [comment]
I have installed SG from the 1.2 download at:

"http://www.couchbase.com/dl/releases/couchbase-sync-gateway/1.2.0/couchbase-sync-gateway-enterprise_1.2.0-83_x86_64.exe"

Windows 8 x64

Clean VM image.

**Comment by ajres** [comment]
@rainerg2000, was this a new install of Sync Gateway or was there a previous installation on that Windows server instance?

**Comment by Crapulax** [comment]
Hi,

I have the same issue installing SG on windows10. I have currently SG 1.1.1 up and running.
Thanks!

**Comment by zgramana** [comment]
@ajres just tested on Windows 10, upgrade from existing 1.1.1 installer, and hit the same error as #1564.

**Comment by zgramana** [comment]
Note: when the user selects the 'upgrade' path, InstallShield will uninstall the previous version. When it fails, there are still remnants available of the previous install--such as the uninstaller from 1.1. However, when you attempt to uninstall from 1.1.1 you will receive an error that the file only works for currently installed products. This leaves the user completely blocked.

I was able to re-install with the 1.1 version downloaded at the Couchbase downloads page (which was actually 1.1.1). I was able to re-install by opting for 'upgrade' once again. I had to reboot, and once I did, I confirmed by opening my browser to http://localhost:4985/ that I was running 1.1.1. However, when I looked at the list of running services, I noticed that  `sg-windows.exe` was running, as was the `SyncGateway` service. I realized that I had a development version of the service wrapper service still installed. Once I stopped it, I was able to remove it by running `sg-windows.exe uninstall`. Once that was complete I successfully uninstalled 1.1.1, but only by going via **Control Panel > Uninstall or change a program > Couchbase Sync Gateway > Uninstall**.

After completely uninstalling 1.1.1, I was able to successfully install 1.2. However, I could not find the `SyncGateway` service in the list of installed services. When uninstalling 1.2 the second time, and hitting the same error (#1721), I noticed that, at the point at which the uninstall script is looking for `sg-windows.exe`, the installation directory is already empty. Moreover, the installer appears to be trying to run the _install_ command. That's a bit opposite of what one expects an uninstaller to do.

At any rate, it not surprisingly fails to find the service wrapper executable. Ironically, once the user selects 'Ok' the installer's transaction script rollback and restores `sg-windows.exe`, and its companions, back to their location in the installation dir. Any user that goes to access the installation dir will find the file sitting there.

**Comment by rainerg2000** [comment]
@ajres I was attempting to upgrade from Sync Gateway 1.1.1-10 to 1.2 .

**Comment by zgramana** [comment]
#### Quick note for those looking for a workaround

Run a command prompt as `Administrator` and enter the following command to install Sync Gateway as a service after installing Sync Gateway via the clean install/non-upgrade path explained above:

```
"C:\Program Files (x86)\Couchbase\sg-windows.exe" install "c:\Program Files (x86)\Couchbase\sync_gateway.exe" "c:\Program Files (x86)\Couchbase\serviceconfig.json"
```

from there you can run the following command to actually start the service:

```
net start SyncGateway
```

**Comment by ajres** [comment]
The remove service custom action had the ‘Installed’ condition, which works for a straight uninstall, but ‘Installed’ also returns true for other maintenance operations so this would attempt to remove the service on update as well. I have added the additional check 'REMOVE=“ALL”’ which should only be set for a full uninstall, not for any other maintenance operations.

**Comment by ajres** [comment]
Tested SG 1.2 windows install and upgrade from 1.1.1 with this developer build [enterprise binary](http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/0.0.1/master/1.2.0-556/couchbase-sync-gateway-enterprise_1.2.0-556_x86_64.exe).

Waiting for release binary to be uploaded to couchbase.com

**Comment by ajres** [comment]
If anyone is looking for the commit, it was direct to master:

https://github.com/couchbase/sync_gateway/commit/41aa099150f2c5cbd971fe9d096e1f99b6cc4c19

**Comment by tleyden** [comment]
@ajres I tried to cherry pick this onto `release/1.2.1` and there's a conflict with an `.ism` file.  Can you cherry pick and resolve the conflicts?

**Comment by Voyz** [comment]
The community edition binaries are still displaying the same problem, not even on upgrading but on a first install. 

The developer [binary](http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/0.0.1/master/1.2.0-556/couchbase-sync-gateway-enterprise_1.2.0-556_x86_64.exe) given by @ajres seem to install fine, although it's an enterprise edition

**Comment by iamchathu** [comment]
Still Sync gateway community edition gives this error when I tried to clean install on windows

**Comment by greenais** [comment]
While 1.2.1 Community edition fails, 1.2 installs with no issue.
So the current for Windows is obviously broken.
