### ISSUE TITLE
Windows installer does not start and stop service wrapper

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1574]
On installing or upgrading SG windows from the InstallShiled, the SG service wrapper is installed but not started.

Starting the SG service is not problematic as it is configured to use a Walrus bucket. Do we want to auto start the service?

When uninstalling Sync Gateway, the service will be removed if it is stopped, but if it is running a dialog is displayed to the user warning that a component can not be removed until a reboot. 

The iunstalle shield could automatically stop the service wrapper before removing it.

**Comment by djpongh** [comment]
2.0 using WIX
