### ISSUE TITLE
Continuous changes requests should disable active_only once they've caught up

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1576]
From @snej:

If you’re using a continuous or websocket feed, then after the client has “caught up”, the active_only mode should turn off, so the client can hear about deletions of docs it knows about.

In other words, active_only should only filter out revisions that were already deleted before the feed started, not new deletions that come in afterwards.

**Comment by snej** [comment]
I think the fix may be as simple as a one-line insertion at `db/changes.go:502`, i.e. just before the `waitForChanges:` label:

``` go
options.ActiveOnly = false
```

**Comment by adamcfraser** [comment]
Fix is available for testing on feature/issue_1576.

**Comment by adamcfraser** [comment]
Based on discussion with @snej, @zgramana, we're considering a few options:
1. Have active_only work as implemented on feature/issue_1576:
   - one-shot _changes requests never return deleted/removed elements
   - continuous/longpoll/websocket _changes requests don't return deleted/removed elements for existing data.  For new updates made after the _changes request was issued, deletes and removals will be sent
2. Have active_only always only return non-deleted, non-removed revisions.  CBL clients would need to be enhanced to make multiple calls - first a one-off with active_only, then switch to continuous.
3. Have Sync Gateway support multiple flavours of active_only - something like active_only=all and active_only=backfill.
