### ISSUE TITLE
Migrate Windows installers to WiX

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1587]
It's F/OSS software, and very popular with sys admins.

http://wixtoolset.org

Steps to transition from InstallShield to WiX installer :
- [x] Document prerequisites for WiX dev environment
- [x] Create WiX project for Sync Gateway
- [x] SG project needs to copy required files from Jenkins build area into destination installation dir.
- [x] SG project needs to add service wrapper for SG on install or update
- [x] SG project needs to remove service wrapper on uninstall
- [x] SG project should ideally recognise previous InstallShield installations and upgrade as appropriate.
- [x] Manually test SG installer for clean install, upgrade from 1.1.1 and 1.2 and uninstall
- [x] Integrate SG WiX package builder into Jenkins build
- [x] Create WiX project for SG Accel
- [x] SGA project needs to copy required files from Jenkins build area into destination installation dir.
- [x] SGA project needs to add service wrapper for SGA on install or update
- [x] SGA project needs to remove service wrapper on uninstall
- [x] SGA project should ideally recognise previous InstallShield installations and upgrade as appropriate.
- [x] Manually test SGA installer for clean install, upgrade from 1.2 and uninstall
- [x] Integrate SGA WiX package builder into Jenkins build
- [x] Add Wiki page with development process for maintaining WiX package installer.

**Comment by ajres** [comment]
Prerequisites:

Windows machine or VM (Currently developing on Windows 8)
Install Visual Studio (Community is good)
Download [WiX toolset](http://wixtoolset.org) (After installing VS, this will add new WiX project templates)

**Comment by ajres** [comment]
I recommend [this book](https://www.packtpub.com/application-development/wix-36-developers-guide-windows-installer-xml) for anyone learning Windows Installer and WiX 3.

**Comment by ajres** [comment]
Moved final integration into Jenkins Windows build to new ticket #1637, closing this ticket out.
