### ISSUE TITLE
Unit tests sporadically failing due to timing / race conditions

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1589]
Steps to reproduce:
- `docker run -it tleyden5iwx/emacs-n-go /bin/bash`
- Use these instructions from the README to [Build from source](https://github.com/couchbase/sync_gateway#building-from-source) 
- `go test ./...`

Failing tests:
- [ ] TestDBOnlineConcurrent
- [ ] TestDBOfflineSingleResync
- [ ] TestRecentSequenceHistory
- [ ] TestChangeIndexChanges  

They are failing sporadically:
- [test run where everything succeeds](https://gist.github.com/tleyden/8386239e31b4d816dc56#file-gistfile1-txt-L1-L9) 
- [full test logs when only one test failed](https://gist.github.com/tleyden/8386239e31b4d816dc56)

**Comment by djpongh** [comment]
oops wrong bug...

**Comment by tleyden** [comment]
Moved to https://github.com/couchbase/sync_gateway/issues/2978
