### ISSUE TITLE
Refactored SG, can't build with repo tool

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1590]
The repo instruction still contain a path to the cocuhbaselabs test repo:

```
$ ./repo init -u "https://github.com/couchbaselabs/sync_gateway.git" -m manifest/default.xml
```

So the following change directory fails:

```
cd $GOPATH/src/github.com/couchbase/sync_gateway
```

**Comment by ajres** [comment]
Changed URL to "https://github.com/couchbase/sync_gateway.git"

Repo build instructions now work.

**Comment by tleyden** [comment]
Good catch!
