### ISSUE TITLE
log dissapeared after upgrade to SG 1.2

### ISSUE THREAD

**Issue by Crapulax** [couchbase/sync_gateway#1591]
Using 1.1.1 i was getting log() information in SG logs from sync function. After upgrade I do not have them anymore.

Am I missing something? How to get them back?

Thanks!

**Comment by tleyden** [comment]
@Crapulax can you post a sample sync function?

**Comment by ajres** [comment]
@Crapulax have you tried using console.log() e.g.:

```
 "sync": ` function(doc, oldDoc) { console.log("HELLO!"); }
```

**Comment by Crapulax** [comment]
Thanks! console.log does work!
In 1.1 i was using log()
