### ISSUE TITLE
Handle missing parent revs during bucket shadowing

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1603]
When shadowing pulls a document, it uses the UpstreamRev property on the document to determine the parent.  When that parent doesn't exist in the current revtree, Sync Gateway is currently panicking.

Instead, it should check for existence of the parent in the revtree, and set parentId=nil if it's not found.  This will create a new conflicting branch in the revtree, and so work the same way Sync Gateway handles client pushes with unavailable parent IDs.

**Comment by ajres** [comment]
Modified shadower.go pullDocument so that a revision can be added even if the UpstreamRev is missing from the documents revision history. In this case the revision is added as anew conflict branch.
