### ISSUE TITLE
Pull replication is not working for authenticated user

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1610]
I am creating this for user that posted to closed ticket #687

**Comment by ajres** [comment]
@cuipengfie reported the following:

I am seeing this on mac.
Push works fine on 4984, but not pull.

My config has guest disabled.
But my client is sending requests with a cookie that belongs to a user that has:
"admin_channels":["*"]

More details:
On 4985, push and pull both work, as expected.
On 4984, without a valid session id cookie, push and pull both do not work, as expected.
On 4984, with a valid session id cookie, push works, but pull does not. Expected: they should both work.

Am I missing something in my config? Please advice, thanks.

**Comment by ajres** [comment]
@cuipengfei

Can you post your Sync Gateway config and a sample document.

Unless you have defined a custom sync function the default function will be used:

```
function(doc) {
    channel(doc.channels);
}
```

EDIT: This will add all documents to the "*" channel which your user will have access to via the "admin_channels":["*"] property on the user account.

Is it possible that you did not define your "admin_channels" property correctly?

**Comment by cuipengfei** [comment]
I created another users and created a new session for this user, it worked.
Not sure what went wrong the first time.

**Comment by ajres** [comment]
@cuipengfei I'm going to close this ticket as it looks like the issue is resolved, if you experience this issue again please open a new ticket.
