### ISSUE TITLE
Enhancement request: Allow checking access within sync function

### ISSUE THREAD

**Issue by Crapulax** [couchbase/sync_gateway#1615]
Hello,

We would like you to consider the following requirement: Ability to route requireUser depending on who is modifying the document.

Use case, let say you have a group of documents which are:
- readable by group members, (access handled with a channel)
- with modification allowed to the document creator AND the group owner

If within the sync function we would be able to do something like:
//$$currentUser is the user name of the session doing the doc update
if ($$currentUser == oldDoc.docOwner || $$currentUser == oldDoc.groupOwner)
    //update is ok
else
 // discard update

Currently we have to pass as a doc property the user updating the doc to acheive above doing:
if (doc.Updater == oldDoc.docOwner)
   requireUser(oldDoc.docOwner)
else requireUser(oldDoc.groupOwner)

You might want to extend above requirement to all requireXXX functions with for instance a boolean parameter preventing the sync function exit but instead returning weither the function is verified or not: For instance above use case will translate into:
//first requireUser will not throw an exception while second will when user doing the update is neither the doc owner nor the group owner
requireUser(oldDoc.docOwner,false) && requireUser(oldDoc.groupOwner, true)

And more generally, extended to other require functions:
var hasAccess = requireAccess(oldDoc.mychanne; false)
var isOwner = requireUser(oldDoc.docOwner; false)
...

Additionnally a isResync() function might be useful too in some circumstances.

Thanks for considering this request. Do not hesitate to come back to us if there is already a more convenient way to achieve other than passing extra data on doc updates. Note that our real use case is  with document deletion, where we have to do a POST _deleted:true, mine:whoami instead of plain DELETE...

**Comment by adamcfraser** [comment]
You can use try/catch to handle the exception thrown by requireXXX - I think you should be able to use that to handle this use case, like:

```
try {
  requireUser(oldDoc.docOwner)
} catch {
  requireUser(oldDoc.groupOwner)
}
```

Let me know if that doesn't cover your requirements.

**Comment by Crapulax** [comment]
Thanks Adam. It was too simple to think about it:)
We will give it a try this week but there is no reason for this not to work.
