### ISSUE TITLE
SGW not return with auth error to WebSocket _changes req after change user's credentials

### ISSUE THREAD

**Issue by pasin** [couchbase/sync_gateway#1619]
Based on the information that I found from investigating the issue on https://github.com/couchbase/couchbase-lite-ios/issues/1138, SGW doesn't send out error message when changing user's credentials.

**Comment by adamcfraser** [comment]
I think it's expected that an open continuous or websocket _changes request won't get terminated on credential change.  I couldn't find any handling that force-closed a request.

However, it's not expected that the feed will go silent after a credential change.  From the SG logs on https://github.com/couchbase/couchbase-lite-ios/issues/1138, it looks like it's just going back into wait mode, waiting for more updates.

**Comment by tleyden** [comment]
Seems like this might be the same issue as reported here:

https://forums.couchbase.com/t/session-removal-keeps-sync-active/18188/2

> I think it's expected that an open continuous or websocket _changes request won't get terminated on credential change. I couldn't find any handling that force-closed a request.

@adamcfraser I wasn't able to find anything either in terms of closing a an open continuous or websocket _changes request after user deletion.  Let me know if you know otherwise.

**Comment by adamcfraser** [comment]
@tleyden I think this is unrelated to that issue.  This ticket is talking about changes to credentials (new password).  When a user is actually deleted, the reloadUser operation will fail and the active replication would be closed.

**Comment by adamcfraser** [comment]
Closing this, as there doesn't appear to be a functional issue as stated.  @pasin if you think there is an actual SG issue here, please reopen with additional details.
