### ISSUE TITLE
monitoring _changes w/continuous=true not working as expected

### ISSUE THREAD

**Issue by tahmmee** [couchbase/sync_gateway#162]
When I try:  
 _changes?feed=continuous 
There aren't any changes sent in the response stream even though db is being updated.  I tried adding since="*:N" param , but also seems same behavior.

I've only needed this for perf testing, but is this expected to work for the sync_gateway?

**Comment by adamcfraser** [comment]
This looks obsolete - please reopen if it's an active issue.
