### ISSUE TITLE
What does "new_rev" means in _sync?

### ISSUE THREAD

**Issue by hitales** [couchbase/sync_gateway#1624]
I found a document in couchbase with "new_rev", and this document can not synchronize to couchbase lite forever, i don't know why; one the lite side, the document is not in conflict list.

So,  What does "new_rev" means in _sync? how can i resolve such document?

For example:
"new_rev": "7-89c099875bdeb20239dc68c88ab07727",
"rev": "11-4fac5074eb7189ca1a836ae84bd8edf7"

**Comment by adamcfraser** [comment]
This is probably better handled as a forum question, as it doesn't sound like there's necessarily an issue here.  Moving to https://forums.couchbase.com/t/what-does-new-rev-mean-in--sync-metadata/7141
