### ISSUE TITLE
Use repo init with -b flag

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1625]
Change repo init to:

```
repo init -u "https://github.com/couchbase/sync_gateway.git" -m manifest/default.xml -b <commit hash>
```

and then modify the script which rewrites the manifest .. it _just_ needs to modify the sync gateway commit, doesn't need to wget the manifest from the feature branch (thus simplifying the script)

**Comment by adamcfraser** [comment]
Moved to #1674
