### ISSUE TITLE
[Bucket Shadowing] Doc added while shadower SG will not make it to source bucket

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1635]
Steps to reproduce manually:
- Start SG-non-shadower and SG-shadower nodes
- Bring SG-shadower down
- Add doc to SG-non-shadower
- Bring up SG-shadower
- Doc will not appear in the source bucket

Steps to reproduce via functional test:
- Uncomment https://github.com/couchbaselabs/sync-gateway-testcluster/blob/ffcf80a75025f0f3ffb799a124cba33a2297dfef/functional_tests/test_bucket_shadow.py#L181
- Run `py.test -s functional_tests/test_bucket_shadow.py`

**Comment by adamcfraser** [comment]
This is expected behaviour for the current bucket shadowing architecture.  Bucket shadowing listens for new updates in the SG bucket using the TAP feed.  For bucket shadowing to pick up changes made while offline, it would need to be enhanced to use DCP and resume where it left off.

**Comment by djpongh** [comment]
With SG 1.50+ it is recommended to use XATTR's and not bucket shadowing
