### ISSUE TITLE
sgcollect_info: docs

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1639]
- [x] Integration with support -- send them a stubbed out zipfile
- [x] Single binary (good for windows and 3rd party deps)
- [x] Include curl binary in Sg packages (same as CBS)
- [x] Jenkins Job
- [x] Update packaging (Windows, Linux, etc)
- [x] Docs page

**Comment by ajres** [comment]
Looking at Couchbase Server for Windows, cbcollect_info is delivered as a Python script along with a python27.dll and as a windows .exe

On linux/Mac cb_collect is delivered as a python script.

**Comment by ajres** [comment]
[PyInstaller](http://www.pyinstaller.org) looks to be the best option for building a single executable from a python script, it's dependencies and the python runtime.

The project is actively maintained and covers Windows, MAC OSX and Linux.

**Comment by ajres** [comment]
Added [new article](https://github.com/couchbaselabs/couchbase-mobile-portal/pull/303) to SG docs covering Enterprise support and use of sgcollect_info. This is based on the [CBS page](http://www.couchbase.com/wiki/display/couchbase/Working+with+the+Couchbase+Technical+Support+Team) which covers the use of cbcollect_info.

This new doc will need to be reviewed and updated once the sgcollect_info utility is complete.

**Comment by ajres** [comment]
Validate pyinstaller can build a single standalone executable on the following OS's
- [x] OSX
- [x] Windows
- [x] Linux (tested on ubuntu 14.04)

Initial test with simple hello.py script, used basic pyinstaller command line

```
pyinstaller --onefile hello.py
```

Windows:

```
py -m PyInstaller --onefile hello.py
```

#!/usr/bin/env python
print "Hello World!"

```
```

**Comment by ajres** [comment]
Does sgcollect_info require python 2 or 3?

**Comment by tleyden** [comment]
@ajres I'd assume python 2, but I haven't run it yet, so not 100% sure

**Comment by zgramana** [comment]
It currently requires 2.7 (or lower, presumably). It needs a bit of refactoring to support 3.x.

**Comment by ajres** [comment]
Added a Wiki page for PyInstaller [installation notes](https://github.com/couchbase/sync_gateway/wiki/PyInstaller-installation-notes) on different platforms.

**Comment by ajres** [comment]
Created a [Dockerfile](https://github.com/couchbase/sync_gateway/blob/feature/issue_1331_sgcollect_info/tools/Dockerfile) that builds a docker image of a Jenkins server with pyinstaller configured so that the build can create the .exe's for sgcollect_info

**Comment by tleyden** [comment]
@michaelkwok we have a running server here: http://drone.couchbasemobile.com:8080/

**Comment by tleyden** [comment]
Per @michaelkwok's earlier request, I've created a jira ticket for this:

https://issues.couchbase.com/browse/CBLT-435

**Comment by tleyden** [comment]
> @michaelkwok we have a running server here: http://drone.couchbasemobile.com:8080/

This is no longer running .. you can get in touch with @ajres if you need to know what script was being run by Jenkins.

@ajres if you have this handy, please post it to the jira ticket linked above .. pretty sure it was just calling PyInstaller with some args.

**Comment by ajres** [comment]
@tleyden Added comment to JIRA ticket

**Comment by ajres** [comment]
Dev team to create build on uber Jenkins see #1731

**Comment by michaelkwok** [comment]
@tleyden Any reason why the Jenkins job is no longer running on http://drone.couchbasemobile.com:8080.  Can I at least have access to the job to see how it's configure?  It can save me a bit of time.

**Comment by tleyden** [comment]
@michaelkwok the drone CI build is still running, but the domain name recently changed.  If you go to the Sync Gateway github: https://github.com/couchbase/sync_gateway you will see a badge about the build status.  Click the badge and it will take you to the Drone CI server.  

The configuration that is used by the Drone CI is checked into the Sync Gateway repo itself:

https://github.com/couchbase/sync_gateway/blob/master/.drone.yml

**Comment by michaelkwok** [comment]
I need more information to move forward.  The Drone CI build doesn't give me useful information.

1) What to build when calling pyinstaller?  Andy confirmed it's sgcollect_info.
2) How does it need to be packaged?  Several parts to this questions: build results to pickup, the name for the sgcollect_info package, do we include it as part of sync-gateway package or as a standalone packcage like sg-accel.
3) Is it already added to the default manifest.xml? Looks like it is but I just want a confirmation.

**Comment by ajres** [comment]
When installing sync_gateway or sg-accel, a new /tools folder should be created at the same level as the /bin folder.

The folder should contain a single binary executable called `sgcollect_info`

**Comment by ajres** [comment]
After running `pyinstaller -onefile sgcollect_info` in the tools folder

the binary executable will be created in a `tools/dist` folder

`tools/dist/sgcollect_info`

**Comment by michaelkwok** [comment]
Looks like PyInstaller 3.2 is broken.  I have switched to 3.1 for the moment.

**Comment by adamcfraser** [comment]
Build/packaging is done, docs are remaining.

**Comment by adamcfraser** [comment]
@jamiltz I think this is already on your radar for 1.3 - let me know if that's not the case.

**Comment by jamesnocentini** [comment]
Yes this is being tracked on the docs repo. I'll ping you there for review.

**Comment by tleyden** [comment]
@jamiltz 

The title looks wrong:

```
---
id: openid-connect
title: OpenID Connect
```

**Comment by tleyden** [comment]
I pushed https://github.com/couchbaselabs/couchbase-mobile-portal/commit/5790ca0629dc7973ff62dbd914fd423507c88e60 which:
- Removes CLI option docs since it's duplicated with the CLI --help and will go out of sync
- Added instructions on installing deps, mentioning which Go version to use
- Added some example usages

**Comment by tleyden** [comment]
Oh also added several files to the list of files generated

**Comment by tleyden** [comment]
@jamiltz is there a way to get a HTML preview of the docs?

**Comment by jamesnocentini** [comment]
The 1.3 branch is on staging http://developer-stage.cbauthx.com/documentation/mobile/1.2/develop/guides/sync-gateway/sgcollect-info/index.html

There is no automated job in place yet. Once all the content has been migrated to markdown (which will be fairly soon) we could look into creating our own preview docs site.
