### ISSUE TITLE
sg_collectinfo: integration

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1640]
- [x] Code review, dead code elimination
- [x] Add missing requirements (logging, expvars, pprof)
- [x] S3 Upload
- [x] Spec out how its run 
- [x] Functional integration (check with Seth first)

```
./sgcollect_info --admin-port 4985  (bootstraps by getting current config) 
```

**Comment by tleyden** [comment]
Zipfile Requirements
1. Log files
2. Expvars
3. Pprof
4. System Stats (in couchbase.log)

**Comment by tleyden** [comment]
Related tickets: 
- https://github.com/couchbase/sync_gateway/issues/1331
- https://github.com/couchbase/sync_gateway/issues/1639

**Comment by tleyden** [comment]
Related PR: https://github.com/couchbase/sync_gateway/pull/1620

**Comment by tleyden** [comment]
1. Startup config
   1. Commandline args (covered in expvars, IIRC)
   2. json file.
2. Running config
   1. Server config
   2. Each DB config

**Comment by tleyden** [comment]
What's still pending:
- [ ] Testing on CentOS 
- [ ] Windows compatibility .. no need to test, known to **not work** due to paths issue
- [ ] Submit a PR

**Comment by tleyden** [comment]
@ajres any chance you could look at the windows compatibility of the current branch?

**Comment by ajres** [comment]
The current branch built with pyinstaller on Windows 8.

I then ran the generated executable with Sync Gateway running, see [attached](https://github.com/couchbase/sync_gateway/files/179778/sgcollect_stdout.txt).

There were processing errors, no .zip output file was generated.

**Comment by tleyden** [comment]
TODO
- [x] Get path to config json from expvars
- [x] Path to binary, for use in pprof

**Comment by tleyden** [comment]
- [x] See if pprofs can generate raw

**Comment by tleyden** [comment]
- [x] Curl the / endpoint and /db endpoints
- [x] Grab whole binary and stuff into zip?

**Comment by tleyden** [comment]
- [ ] Pretty print expvars

**Comment by tleyden** [comment]
- [x] Parameterize admin port (default port 4985)
- [x] Option to specify path to config
- [x] Tool should echo the command line args into the zip)

**Comment by tleyden** [comment]
- [x] Double check heap.txt (bug: http://http://localhost:4985/_debug/pprof/heap)
- [ ] Figure out why profile.txt empty

**Comment by tleyden** [comment]
> Get path to config json from expvars
> Path to binary, for use in pprof

Looks like the only thing we can depend on is the path to the binary, since the config may not be passed as a cmd line arg.  See https://github.com/couchbase/sync_gateway/issues/1664

**Comment by tleyden** [comment]
We could _try_ to look for config files passed in the cmd line by looping over args and looking for the first one that contains `.json`, and then doing some light validation on it to make sure it's actually a config file.

**Comment by tleyden** [comment]
>  Pretty print expvars

This is hard due to the fact that we're using curl, and not only that, the stdout and stderr are mixed together.

I think this should be done later in v2 when it gets too annoying.

**Comment by tleyden** [comment]
[Example sg_collectinfo zip](http://couchbase-mobile.s3.amazonaws.com/misc/sg_collect_info.zip)

[Logs when generating above zip](https://gist.github.com/tleyden/a4713e69fd43e7b9eb069f4b1fa556ef)
