### ISSUE TITLE
User unable to pull replicate

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1644]
User is able to push replicate but not pull replicate.

They have tried using curl commands which work on a test install on MAC OS X

Original forum post is here:

https://forums.couchbase.com/t/couchbase-sync-gateway-pulling-issue-for-authenticated-users/7276

I was unable to retrieve the attachments from the forum, requested OP to attach files to this ticket.

**Comment by ManuraCalcey** [comment]
[sg_error.zip](https://github.com/couchbase/sync_gateway/files/165681/sg_error.zip)
[JsonObjectCreator.zip](https://github.com/couchbase/sync_gateway/files/165687/JsonObjectCreator.zip)

**Comment by ajres** [comment]
@manura 

Looking at the SG log, the _changes request failed to authenticate, I also see failed authentications in the screen dump. 

Can you launch SG and just run the curl command to get the _changes and ensure that it does not fail authentication, paste the response form that one call and the SG log from launch to the _changes request coming in.

Is SG running on the Windows platform?

Do you have multiple SG instances connecting to the same Couchbase Server cluster or just a single SG instance.

**Comment by ManuraCalcey** [comment]
@ajres 

yes sg is running in a windows instance and couchbase server is running in a Linux instance. There were multiple instance of sg on Linux and Windows. Anyway I stop the Linux instance and run only the windows instance. But the result is same. I do not understand the thing asked to do in second paragraph.

If you check the screenshot you might see the a pattern first it returns a empty changes array and if we make the same request again it returns a authentication failure. what does that mean.

If we send the same pull request without authentication it sends all the changes.
[sg_error (3).zip](https://github.com/couchbase/sync_gateway/files/166551/sg_error.3.zip)
![curl2](https://cloud.githubusercontent.com/assets/6085777/13660062/d93d4722-e6ac-11e5-80b4-2c9abeb1c3b1.png)

**Comment by ajres** [comment]
@manura 

Looking at your log Sync Gateway does not think that the user has access to the "*" channel, so you see no revisions in the changes feed.

Did you create the SG config on Windows locally or did you copy it from Linux. If it was copied could you try creating it from scratch on Windows and then retry.

If that does not fix the issue try removing the couchbase_user from the config file, re-start SG and create the user via the REST API and retry the _changes request.

```
curl -X PUT http://localhost:4985/batch-test/_user/couchbase_user -H "Content-Type: application/json" -d '{"password":"mobile","admin_channels":["*"]}'
```

If the issue still persists, can you run the following curl commands and paste the results to this ticket.

```
curl -X GET http://couchbase_user:mobile@localhost:4984/batch-test/_all_docs
```

```
curl -X GET http://localhost:4985/batch-test/_dumpchannel/*
```

```
curl -X GET http://localhost:4985/batch-test/_dump/channels
```

**Comment by ManuraCalcey** [comment]
@ajres 

I have deleted the users and recreate them using the command mentioned in the reply. Now it's working. We can pull users with authenticated users :+1: 

Btw must we have to run the following command in the same machine sync gateway is running.
"curl -X PUT http://localhost:4985/batch-test/_user/couchbase_user -H "Content-Type: application/json" -d '{"password":"mobile","admin_channels":["*"]}'"

I try it from my laptop replacing the ip for the localhost. it gives the error 
"curl: (7) Failed to connect to 172.16.1.15 port 4985: Connection refused"
Event if I run it from the hosting maching with the ip instead of local host it gives the same error.

![curl3](https://cloud.githubusercontent.com/assets/6085777/13673538/68b7517a-e6ff-11e5-8da6-fd9db7707d7a.png)

Does sync gate way provide an API for assign channels to users after creating them. Then we don't have to assign all the channels to users. Our application is a CMS and we don't allow all the users evey  document.

Following is the config file we are using now. I don't add users in it. Is that correct. Anyway it's working.

{
    "log":["_"],
    "databases": {
        "batch-test": {
            "server":"http://172.16.1.76:8091/",
            "bucket":"batch-test",
            "sync":`
                function (doc) {
                channel (doc.channels);
            }`,
            "users": {
                "GUEST": {
                    "disabled": false,
                    "admin_channels": ["_"],
                    "channels":["_"] 
                }
            }
        }
    },
    "CORS": {
   "Origin": ["_"],
   "LoginOrigin": ["*"],
   "Headers": ["Content-Type"],
   "MaxAge": 17280000
 }
}

Are there any tips and tricks availabe for sync funtion.

Thank you for your cooperation

**Comment by ajres** [comment]
@manura 

It's good that you are now working, I don't have a definitive answer as to why you were seeing issues previously, other than you possibly had hidden control characters in your SG config that caused the user block to be mis interpreted.

If you still have your original Windows SG config file you could attach it to the ticket and I can take a look (cut and pasting the content will likely loose any control characters if they are there).

By default the SG interfaces will bind to 127.0.0.1, if you need remote access then add the following properties to the top level of your SG config, setting the interface IP you want them to bind to. 

```
"interface":"0.0.0.0:4984",
"adminInterface":"0.0.0.0:4985",
```

IP 0.0.0.0 will bind to all available interfaces which is useful during development but not secure.
Usually you will want to bind the adminInterface to an IP that is not accessible via public networks.

In production you would not typically add users to the SG config, you would add them via the REST API.

One observation, you should set GUEST "disabled": true, this will prevent non-authenticated user access.

Usually you will assign channels to users in the sync function using the access() method, based on the contents of a document.

There is documentation about the sync function API [here](http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/sync-gateway/sync-function-api-guide/index.html) 

A guide to channels [here](http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/sync-gateway/channels/index.html)

There a number of sample Apps that demonstrate sharing data between users e.g. [ToDoLite-Android](https://github.com/couchbaselabs/ToDoLite-Android.git) it is also available for a number of other languages in the [couchbaselabs GitHub repo](https://github.com/couchbaselabs). The App comes with an SG config file that works with the App and demonstrates many of the sync function features.

If you need further assistance with app development please post to the couchbase forum.
