### ISSUE TITLE
WebSocket _changes feed gzip is incorrect

### ISSUE THREAD

**Issue by borrrden** [couchbase/sync_gateway#1647]
The DEFLATE algorithm specifies that the last block in its stream is to be marked as such, but the gzip data received from the _changes feed on sync gateway never sets this marker.  As a result, .NET will continue trying to read the stream and throw an exception thinking that an EOF has been reached when it shouldn't have been.  OS X gunzip has the same problem:

> gunzip websocket_changes.gz
> 
> gunzip: websocket_changes.gz: unexpected end of file
> gunzip: websocket_changes.gz: uncompress failed

Here is the scenario:  I set up a sync gateway (1.2) instance with GUEST enabled, and one user named "jim".  The regular changes feed looks like this:

> curl http://localhost:4984/db/_changes
> 
> {"results":[
> {"seq":1,"id":"_user/","changes":[{"rev":""}]}
> ,{"seq":2,"id":"_user/jim","changes":[{"rev":""}]}
> ],
> "last_seq":"2"}

When querying through the web socket gzip _changes feed I get two binary messages, followed by the "termination" text message.  The concatenated result I posted [here](https://www.dropbox.com/s/k01a52d0xj43hii/websocket_changes.gz?dl=0) (will expire on April 4, 2016).  

The result of my analysis of this particular file is that byte 62 is 0x82.  Byte 62 marks the beginning of a new block, and in this stream it is the final block.  However, the specification says that the lowest bit of this byte (I think?) must be toggled to mark this as the final block.  If I manually change this byte to, for example, 0x83 then I can successfully decompress the file I attached (albeit, the CRC will fail but with the following command I can extract all the data):

> gunzip < websocket_changes.gz > output
> cat output
> 
> [{"seq":1,"id":"_user/","changes":[{"rev":""}]}][{"seq":2,"id":"_user/jim","changes":[{"rev":""}]}]%

**Comment by adamcfraser** [comment]
Websocket replication doesn't have a fixed end - they are expected to be continuous replications, only interrupted by timeout/client disconnect/etc. 

When you say it's the final block in the stream - are you talking about the entire stream (which shouldn't have a 'final' block), or just a single changes entry within that stream?

**Comment by borrrden** [comment]
I'm talking about the final Huffman block that comes in the gzip stream that is terminated by the presence of a "[]" text message from the server to the client.  Otherwise the unzip operation fails because it can't recognize the end of the deflate stream. And doesn't know to look for a footer instead of more Huffman blocks. 

That's different from the end of the web socket stream. To be clear I'm talking about the stream that is composed of all the binary messages received between replication start and the "empty" text message.

**Comment by borrrden** [comment]
Sorry I could be a bit clearer. Each binary message is a gzip chunk, and within those chunks are one or more Huffman blocks (this is getting down to the nitty and gritty of gzip). The deflate algorithm, which gzip uses to store its data, is designed so that you keep reading data until a block is marked as final, at which point the footer containing the CRC and some other info is written over 8 bytes. The final Huffman block in the series of Huffman blocks composing the gzip stream from sync gateway is not marked as so and that causes the inflater to attempt to keep reading blocks instead of parsing the footer. This results in reading past the end of the stream and an exception.

**Comment by snej** [comment]
The stream is never terminated, as Adam said. the empty-array message simply communicates that the client has caught up with pre-existing changes; it's not the end of anything.

All you're supposed to do as a client is keep feeding the binary messages into the gzip decoder as they arrive. When the decoder emits decoded data, you feed that into a streaming JSON parser. When the JSON parser emits an object (an element of the top-level array), you interpret that as a change.
