### ISSUE TITLE
Differentiate logging between standard out and standard error

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1652]
Currently all our logging goes to standard error.  We'd like send regular logging (including error for context) to standard out, and errors (and potentially warnings) only to standard error.  This would allow users to cycle/rotate their standard out without losing critical information.

**Comment by atom992** [comment]
+1

**Comment by adamcfraser** [comment]
Should be reviewed with consideration of the differences in buffering between standard out and standard error.

**Comment by djpongh** [comment]
New 2.1 logging should take care of this.
