### ISSUE TITLE
Repo build failure - unable to check signature of new version

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1654]
I had the following error when trying to build Sync Gateway on OSX using the 'repo' flow via `bootstrap.sh`. 
In addition to the error message the `godeps` directory did not exist after the `bootstrap.sh` script completed.

I had checked out and built successfully on previous occasions.

```
object 203153e7bba61b1b2d782e9e75aef919eab0d54b
type commit
tag v1.12.33
tagger Dan Willemsen <dwillemsen@google.com> 1456952362 -0800

repo v1.12.33

gpg: keyring `/Users/me/.repoconfig/gnupg/pubring.gpg' created
gpg: Signature made Wed  2 Mar 20:59:22 2016 GMT using DSA key ID 920F5C65
gpg: Can't check signature: public key not found
error: could not verify the tag 'v1.12.33'
```

**Comment by ajres** [comment]
The fix was to recursively remove the directory 

`~/.repoconfig`

Then manually run 

`repo init`

Which regenerated a new set of public keys

```
gpg: keyring `/Users/me/.repoconfig/gnupg/secring.gpg' created
gpg: /Users/me/.repoconfig/gnupg/trustdb.gpg: trustdb created
gpg: key 920F5C65: public key "Repo Maintainer <repo@android.kernel.org>" imported
gpg: key 692B382C: public key "Conley Owens <cco3@android.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2  (RSA: 1)
```

Running `bootstrap.sh` again, generated no errors and the `godeps` directory was created correctly.

Sync Gateway built without error using `build.sh`

**Comment by Namburger** [comment]
@ajres Thanks! saved my life lol
