### ISSUE TITLE
Users can be created with empty password even though `allow_empty_password` is `False`

### ISSUE THREAD

**Issue by jamescooke** [couchbase/sync_gateway#1656]
When a User is created with POST, [documentation](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/sync-gateway/admin-rest-api/user-admin/post-user/index.html) says:

> password | string | Password of the user that will be created. Required, unless the `allow_empty_password` Sync Gateway per-database configuration value is set to true, in which case the password can be omitted.

However, this does not appear to be true and Users can be created with empty passwords _under all conditions_. This also effects the PUT endpoint - a user that's new can be created without a password.

Many ways to reproduce, but here's a simple one:
- SG config is:
  
  ``` json
  {
      "log": ["*"],
      "adminInterface": "0.0.0.0:4985",
      "interface": "0.0.0.0:4984",
      "databases": {}
  }
  ```
  
  Therefore [`allow_empty_password` is `False` as per the docs](http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/sync-gateway/configuring-sync-gateway/config-properties/index.html#database-configuration):
  
  > Whether to allow empty passwords for Couchbase Server authentication. The default is false.
- Create new database.
- Create user without password, just POST `{'name': 'person'}` to `/db/_user/`

There are no errors reported in the log.

Alternatively, if I update the database's config by posting `{'allow_empty_password': False}` to `/db/_config`, this is accepted (although _all_ data, valid or not appears to be accepted), and Users can still be created without password.

Version string is `Couchbase Sync Gateway/1.2.0(79;9df63a5)`

**Comment by jamescooke** [comment]
Users that are created without password using the method above can then auth by just setting `password` as `''` in HTTP Basic Auth.

**Comment by ajres** [comment]
The method `isPasswordValid` in users.go does not correctly catch all cases:

```
func (p PrincipalConfig) IsPasswordValid(allowEmptyPass bool) (isValid bool, reason string) {

    // if it's an anon user, they should not have a password
    if p.Name == nil && p.Password != nil {
        return false, "Anonymous users should not have a password"
    }

    if allowEmptyPass {
        // allow any password, skip validation
        return true, ""
    }

    if p.Password != nil && len(*p.Password) < 3 {
        return false, "Passwords must be at least three 3 characters"
    }

    return true, ""

}
```

If `allowEmptyPass` is false then there is no further checking of empty passwords for non nil p.Name.

Any check has to take into account the "GUEST" user which does not have a password and also a number of unit tests call `db.UpdatePrincipal` without defining a password.

**Comment by adamcfraser** [comment]
@ajres But in this situation, shouldn't allowEmptyPass be coming through as false, and so it should fall through to the password check below?

**Comment by ajres** [comment]
Yes, but the password check ignores empty Passwords only Passwords with a non nil value are checked.

**Comment by ajres** [comment]
allowEmptyPassword bool is now evaluated as 'dbc.AllowEmptyPassword || allowReplace', which means that if a user can be replaced (updated) then user.Password is allowed to be empty, in which case the existing password will remain intact.
