### ISSUE TITLE
Comment out Facebook unit test

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1659]
Will recreate as a Robot Framework integration test.

This is blocking @michaelkwok due to failing when running concurrently on multiple processes. This test is an integration test and should be mocked or moved to the robot framework

**Comment by zgramana** [comment]
Will be done as couchbaselabs/ sync-gateway-testcluser#346

**Comment by michaelkwok** [comment]
Note this test failed consistently when 2 or more instances running on the same machine.  Here is the error log.

22e6ede122631f348135126b781e2c25]] Err:<nil> allRemoved:false branched:false}
23:17:03 2016-03-18T02:17:03.629-04:00 Changes+: Notifying that changeListener is stopping
23:17:03 --- FAIL: TestVerifyFacebook (0.00s)
23:17:03 panic: listen tcp 127.0.0.1:4444: bind: address already in use [recovered]
23:17:03    panic: listen tcp 127.0.0.1:4444: bind: address already in use
23:17:03
