### ISSUE TITLE
Add `_replicate` support to SG admin REST API

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1663]
As an admin, I should be able to replicate two or more Sync Gateway instances with each other.

Additional criteria:
- [ ] ~~User and Role docs support.~~ Not in initial delivery.
- [x] Channel filtering.
- [ ] Cookie auth support.
- [x] Include management API `_active_tasks`.

Open questions:
- [ ] Web Sockets? HTTP/2?
- [ ] Prioritization of specific replications?
- [ ] New webhooks: create, delete, started, stopped, retrying?
- [ ] Local docs?
- [ ] TTLs?
- [ ] Optimized backfills?

**Comment by adamcfraser** [comment]
I don't think we can support user and role doc replication between Sync Gateways without an enhancement to manage those docs using revision trees.  It would be relatively straightforward to include user and role docs in an admin _changes request, but without rev trees for those docs, we still wouldn't have a way to resolve when updates to the user docs are made in both systems, or even avoid an echo/feedback loop when an update is originally made in only one system.

**Comment by atom992** [comment]
@zgramana   Can you explain why SG need to  replicate two or more Sync Gateway instances with each other.

**Comment by tleyden** [comment]
There are lots of use cases .. A simple one would be a high availability scenario with an up to date backup in a different data center.

Master-master replication also an option .. One SG on west coast and one on east coast, and user devices would connect to the closest one

**Comment by adamcfraser** [comment]
Current work is on feature/issue_1663_replicate.

Status (initial implementation):
- [x] API for _replicate and _active_tasks stubbed out
- [x] Start one-shot synchronous replication 
- [x] Start continuous replication
- [x] Cancel an active replication
- [x] active_tasks
- [ ] Properly populate response for _replicate request, excluding history
- [x] Add counters inside replication to provide stats in history/active_tasks (moved to https://github.com/couchbase/sync_gateway/issues/1672)
- [x] Identify duplicate replication requests, and return 208 for existing
- [x] Async one-shot replication, returning 202
- [x] Channel filtering (moved to #1671)
