### ISSUE TITLE
Cookie-Based auth return 401 while the Cookies is valid

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1665]
I am using couchbase-lite-android:1.2.0 with Couchbase Sync Gateway 1.2.0 on Android 5.0.1.
When I used  couchbase-lite REST API to setup pull and push replication,it works.
but after few hours(the Cookies is valid),the replication doesn't work.
Cookies Check:

```
curl -v -H "Content-Type: application/json" --cookie "SyncGatewaySession=60445a4d3b4089a1ec726976d815c9917bd59cd2" http://10.0.1.1:4984/sgdb/doc1
```

Return the doc1 info.

adb logcat logs shows:

```
D/Sync    ( 8568): com.couchbase.lite.replicator.PullerInternal$12@27f05333 still running, restarting change tracker
D/Sync    ( 8568): com.couchbase.lite.replicator.PullerInternal@395233f0: starting ChangeTracker with since=10656 mode=OneShot
D/Sync    ( 8568): com.couchbase.lite.replicator.PullerInternal@395233f0: started ChangeTracker com.couchbase.lite.replicator.ChangeTracker@71f26f0
D/ChangeTracker( 8568): com.couchbase.lite.replicator.ChangeTracker@71f26f0: Changed tracker asked to start
D/ChangeTracker( 8568): Thread id => 1100
V/ChangeTracker( 8568): com.couchbase.lite.replicator.ChangeTracker@71f26f0: Making request to http://10.0.1.1:4984/sgdb/_changes
E/ChangeTracker( 8568): com.couchbase.lite.replicator.ChangeTracker@71f26f0: Change tracker got error 401
V/ChangeTracker( 8568): com.couchbase.lite.replicator.ChangeTracker@71f26f0: Change tracker run loop exiting
D/ChangeTracker( 8568): com.couchbase.lite.replicator.ChangeTracker@71f26f0: Change tracker in stopped()
D/ChangeTracker( 8568): com.couchbase.lite.replicator.ChangeTracker@71f26f0: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@395233f0

```

Couchbase Sync Gateway error logs shows:

```
2016-03-23T10:38:19.857+08:00 HTTP:  #28515: POST /sgdb/_changes
2016-03-23T10:38:19.857+08:00 HTTP: #28515:     --> 401 Login required  (0.7 ms)
2016-03-23T10:38:30.055+08:00 HTTP:  #28516: POST /sgdb/_changes
2016-03-23T10:38:30.055+08:00 HTTP: #28516:     --> 401 Login required  (0.5 ms)

```

HTTP Request/Response shows:
Request:

```
POST /sgdb/_changes HTTP/1.1
Content-Type: application/json
User-Agent: CouchbaseLite/1.2 (1.2.0/3fa390b596672fa39243cb9f3457c276eb53707b)
Accept-Encoding: gzip
Cookie: SyncGatewaySession=60445a4d3b4089a1ec726976d815c9917bd59cd2
Content-Length: 101
Host: 10.0.1.1:4984
Connection: Keep-Alive
Cookie: SyncGatewaySession=60445a4d3b4089a1ec726976d815c9917bd59cd2
Cookie2: $Version=1

{"style":"all_docs","heartbeat":300000,"feed":"normal","active_only":null,"limit":null,"since":10656}
```

Response:

```
HTTP/1.1 401  #Unauthorized
Date: Wed, 23 Mar 2016 02:23:11 GMT
Content-Type: application/json
Content-Length: 50
Connection: keep-alive
server: Couchbase Sync Gateway/1.2.0
www-authenticate: Basic realm="Couchbase Sync Gateway"

{"error":"Unauthorized","reason":"Login required"}
```
# https://github.com/couchbase/couchbase-lite-android/issues/817

**Comment by atom992** [comment]
I used curl to send the same request to sync gateway, and it return values:

```
curl -v -X POST -H "Content-Type: application/json" --cookie "SyncGatewaySession=60445a4d3b4089a1ec726976d815c9917bd59cd2" http://10.0.1.1:4984/sgdb/_changes -d '{"style":"all_docs","heartbeat":300000,"feed":"normal","active_only":null,"limit":null,"since":10656}'
```

It return the following info:

```
< HTTP/1.1 200 OK
< Date: Wed, 23 Mar 2016 03:26:10 GMT
< Content-Type: application/json
< Content-Length: 37
< Connection: keep-alive
< cache-control: private, max-age=0, no-cache, no-store
< server: Couchbase Sync Gateway/1.2.0
<
{"results":[
],
"last_seq":"10656"}
* Connection #0 to host 10.0.1.1 left intact
```

and Sync Gateway error log shows:

```
10.0.1.101 - - [23/Mar/2016:11:26:38 +0800] "POST /sgdb/_changes HTTP/1.1" 200 20780 "-" "curl/7.43.0"
```

**Comment by adamcfraser** [comment]
This looks like it may be an Android issue, not a Sync Gateway issue.  @hideki do you know of anything related to this issue?

**Comment by adamcfraser** [comment]
I think this is an Android issue, and should get tracked by https://github.com/couchbase/couchbase-lite-android/issues/817.

**Comment by npomfret** [comment]
I think I'm getting this on iOS.  I create a session using the admin api (in order to provide a longer TTL), and then try to use that session in a one-shot replication.  I get:

`'{"status":401,"reason":"Login required","url":"https:\\/\\/pomochat-sg-read-dev.pomocorp.com\\/sync_gateway\\/ca4917000519529dbc9bd8b07ef5041e?rev=229-e71b5037c9121260cf91ce7cf9aca2ed&revs=true&attachments=true&revs_limit=20","error":"unauthorized"}'` 

But I test the session (again, with the admin api) and it says its fine, and:

```
curl -X GET -H "Cookie: SyncGatewaySession=2395511a996fb8f0049f014a8ae7d63303745aab" "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/"
{"committed_update_seq":767398,"compact_running":false,"db_name":"sync_gateway","disk_format_version":0,"instance_start_time":1487407609074544,"purge_seq":0,"state":"Online","update_seq":767398}
```

Is there something different about using a session thats created in the admin api?  Do I need to wait a few seconds or something before it can be used?

**Comment by adamcfraser** [comment]
@npomfret There shouldn't be any timing issues, AFAIK.  When you test the session, are you using the admin or public API?  Testing against the admin API wouldn't evaluate the session cookie, since there's no auth on the admin API.

**Comment by npomfret** [comment]
I'm using the admin api to test it by doing a get request to `.../bucketName/_session/sessionId`

**Comment by adamcfraser** [comment]
Are you able to validate that the expected session cookie is actually being sent for your iOS request?

**Comment by npomfret** [comment]
So after creating the session, and before using it, the client makes a request to the root sync gateway url (which I hope acts as a good test) - and it's fine.  It's only starting replication (via the CBL rest api) that fails.

**Comment by npomfret** [comment]
How would I validate it?

**Comment by adamcfraser** [comment]
Given that the session initially works, it sounds like there are two potential options:
1. The session expiry is so short that it expires before replication starts, or
2. The replication isn't using the session token.

Since you we able to use the session token later, it sounds like it isn't #1.  So this sounds like an iOS issue, which unfortunately I'm not an expert on.

@pasin @snej Any recommendations about how to debug session token usage by an iOS replication?

**Comment by npomfret** [comment]
Here's an example of the session I'm trying to use; 

`SyncGatewaySession=0562f04b2c832e7c938dc617bba47fd815556022; path=/sync_gateway; domain=localhost; Max-Age=863999; Expires=Thu, 02-Mar-2017 20:33:43 GMT`

And the url is: https://pomochat-sg-read-dev.pomocorp.com/sync_gateway

...and I see stuff like this in the sg logs:

```
2017-02-20T20:40:31.466Z HTTP:  #661621: GET /sync_gateway/_local/31b70ce3f6fd1c7864edabd683634f8b542ff870
2017-02-20T20:40:31.466Z HTTP: #661621:     --> 401 Login required  (3.1 ms)
```

What is this `_local` document??

FYI - i occasionally see the same thing in Android: https://github.com/couchbase/couchbase-lite-android/issues/1077

The only pattern I can spot is that it seems to happen on devices that haven't been used in a while... but that's a bit of a guess.

**Comment by adamcfraser** [comment]
The _local call is the client replication retrieving the previous replication checkpoint - it's the standard first operation in a replication, and so it would be the first one attempting to authenticate.

**Comment by npomfret** [comment]
Right, and if the session has changed between replications would that cause
this error?

**Comment by adamcfraser** [comment]
@npomfret No, the replication checkpoint is unrelated to the authentication session.

**Comment by npomfret** [comment]
I don't really understand where the client gets this `_local` document url from.  But I can confirm this is failing on android too.  Here's an example:

```
curl -X GET -H "Cookie: SyncGatewaySession=884e3b470215d38825b3f42ccf766c59c26563f4; path=/sync_gateway; domain=pomochat-sg-write-dev.pomocorp.com; Max-Age=863999; Expires=Fri, 03-Mar-2017 08:40:22 GMT" "https://pomochat-sg-read-dev.pomocorp.com/sync_gateway/_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6"
{"_id":"_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6","_rev":"0-158","lastSequence":"691471"}
```

But from logcat i see this:

```
2-21 08:40:19.749 6249-6297/? I/ReactNativeJS: '_startReplication', { source: 'pc_0_86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3',
                                                  target: 
                                                   { headers: { Cookie: 'SyncGatewaySession=884e3b470215d38825b3f42ccf766c59c26563f4; path=/sync_gateway; domain=pomochat-sg-write-dev.pomocorp.com; Max-Age=863999; Expires=Fri, 03-Mar-2017 08:40:22 GMT' },
                                                     url: 'https://pomochat-sg-write-dev.pomocorp.com/sync_gateway' },
                                                  options: { continuous: true } }
02-21 08:40:20.390 6249-6335/? W/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@41efef28: error getting remote checkpoint
                                       com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized
                                           at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:265)
                                           at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
                                           at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                           at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                           at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                           at java.lang.Thread.run(Thread.java:856)
02-21 08:40:20.390 6249-6335/? W/Sync: PullerInternal{https://pomochat-sg-read-dev.pomocorp.com/sync_gateway, pull, ce695}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized
02-21 08:40:20.390 6249-6334/? W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {GET, https://pomochat-sg-read-dev.pomocorp.com/sync_gateway/_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6}: aborting request: okhttp3.RealCall@41dd4ff0
02-21 08:40:20.750 6249-6342/? W/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@41ddfed8: error getting remote checkpoint
                                       com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized
                                           at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:265)
                                           at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
                                           at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                           at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                           at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                           at java.lang.Thread.run(Thread.java:856)
02-21 08:40:20.750 6249-6342/? W/Sync: PusherInternal{https://pomochat-sg-write-dev.pomocorp.com/sync_gateway, push, 19562}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized
02-21 08:40:20.750 6249-6341/? W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {GET, https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/_local/195629a5aa17f2e27b6bdb06b4b72c8654d3f636}: aborting request: okhttp3.RealCall@41efd350
```

And the sg logs, here's the response from my app and from my `curl`:

```
2017-02-21T08:40:26.262Z HTTP:  #731536: GET /sync_gateway/_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6
2017-02-21T08:40:26.263Z HTTP: #731536:     --> 401 Login required  (1.3 ms)
2017-02-21T08:42:48.011Z HTTP:  #731805: GET /sync_gateway/_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6  (as 86fc56d2-f1d3-4b9d-bcf5-5fc9f09fbdb3)
2017-02-21T08:42:48.015Z HTTP+: #731805:     --> 200   (5.1 ms)
```

**Comment by adamcfraser** [comment]
It's possible that the replication has a previously existing session (that's overwriting the header you're passing in).  However, this is definitely better answered by someone with more Couchbase Lite expertise - it seems like it's clearly a client issue, not a SG issue.

@pasin, @hideki - can you review and move to a CBL repo as appropriate?

**Comment by npomfret** [comment]
That sounds like a reasonable explanation.  I guess it's possible that both implementations have the same bug.  There's already an android issue [here](https://github.com/couchbase/couchbase-lite-android/issues/1077).

**Comment by hideki** [comment]
Hi @adamcfraser  and @npomfret,

I need to review the CBL side codes. I am wondering why the session ID (`884e3b470215d38825b3f42ccf766c59c26563f4`) is not valid even though `Expires` value is `Fri, 03-Mar-2017 08:40:22 GMT`?

```
$ curl -X GET -H "Cookie: SyncGatewaySession=884e3b470215d38825b3f42ccf766c59c26563f4; path=/sync_gateway; domain=pomochat-sg-write-dev.pomocorp.com; Max-Age=863999; Expires=Fri, 03-Mar-2017 08:40:22 GMT" "https://pomochat-sg-read-dev.pomocorp.com/sync_gateway/_local/ce695a5eda223b8dff37c80010f4c271ef30a0e6"

{"error":"Unauthorized","reason":"Login required"}
$ 
```

**Comment by pasin** [comment]
I think to debug this issue we need to see the raw HTTP request/response that has the issue from the client to SGW (e.g. using HTTPScoop or any proxy tools to get the info).

**Comment by hideki** [comment]
REF: 
- https://github.com/couchbase/couchbase-lite-android/issues/1077
- https://github.com/couchbase/couchbase-lite-android/issues/817

**Comment by npomfret** [comment]
@hideki it's possible i've deleted that session but here's another example:

Session id: `c6b92c283f0990266b5a4aae89d291733ddd67b3`
Failing url: `https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/_local/b90f43b1e78657cd017dc80501da641c7f19446d`

```
curl -X GET -H "Cookie: SyncGatewaySession=c6b92c283f0990266b5a4aae89d291733ddd67b3; path=/sync_gateway; domain=pomochat-sg-write-dev.pomocorp.com; Max-Age=82799; Expires=Fri, 24-Feb-2017 08:37:49 GMT" "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/_local/b90f43b1e78657cd017dc80501da641c7f19446d"
{"_id":"_local/b90f43b1e78657cd017dc80501da641c7f19446d","_rev":"0-359","lastSequence":"48649"}
```

My app logs:

```
'_startReplication', 
  { source: 'pc_0_95ee00f0-6f24-4553-8228-d045c4b4289d',
    target: 
      { headers: { Cookie: 'SyncGatewaySession=c6b92c283f0990266b5a4aae89d291733ddd67b3; path=/sync_gateway; domain=pomochat-sg-write-dev.pomocorp.com; Max-Age=82799; Expires=Fri, 24-Feb-2017 08:37:49 GMT' },
        url: 'https://pomochat-sg-write-dev.pomocorp.com/sync_gateway' },
    options: { continuous: true } }

...

com.couchbase.lite.replicator.RemoteRequestRetry$1@41dc7358: RemoteRequestRetry failed, non-transient error.  NOT retrying. url: https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/_local/b90f43b1e78657cd017dc80501da641c7f19446d
  02-23 09:37:54.385 24964-25081/? W/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@41f23f68: error getting remote checkpoint
  com.couchbase.lite.replicator.RemoteRequestResponseException: {code=401, userInfo={AuthChallenge={realm=Couchbase Sync Gateway, WWW-Authenticate=Basic realm="Couchbase Sync Gateway", Scheme=Basic}}, message=Unauthorized}
 */

```

**Comment by npomfret** [comment]
@pasin the server only accepts https traffic so I'm not sure that a proxy will be able to see the information we need.

There are a couple of options here.  I have 2 devices that are exhibiting the problem.  One virtual iOS device running a dev build from Xcode and one physical android device running production build.

So, if I new how to attach the couchbase lite source code I probably have enough skill to be able to debug it and find out what session id is being used in the failing request.  But unfortunately I don't know how to attach the source code, my iOS skills are not good.

Or, could we make a build of the android codebase that logs the session id thats being used - then I could do another production build just for this one device.

**Comment by npomfret** [comment]
One thought: I'm using a `Cookie` header field in the request, that is the correct thing to do yes?  I used to use an `Authorisation` header.

**Comment by npomfret** [comment]
I'm managed to build the iOS CBL libs from source so I can add some debug logging in.  Have you any suggestions of where/what to log?

**Comment by hideki** [comment]
FYI: Setting SessionID by native API, pull replicator can replicate all 12144 changes.

```
02-23 13:37:24.800 1545-1751/com.couchbase.lite.test E/Issue1063Test: changed() PULL replication event. Source: Replication{https://pomochat-sg-write-dev.pomocorp.com/sync_gateway, pull} Transition: RUNNING -> IDLE Total changes: 12144 Completed changes: 12144
```

```java
        String strUrl = "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway";
        URL url = new URL(strUrl);
        Replication pull = database.createPullReplication(url);
        pull.setContinuous(true);
        pull.setCookie("SyncGatewaySession",
                "c6b92c283f0990266b5a4aae89d291733ddd67b3",
                "/sync_gateway", 82799, false, false);
        CountDownLatch latchFinished = new CountDownLatch(1);
        pull.addChangeListener(new ReplicationFinishedObserver(latchFinished));
        pull.addChangeListener(new Replication.ChangeListener() {
            @Override
            public void changed(Replication.ChangeEvent event) {
                Log.e("Issue1063Test", "changed() %s", event);
            }
        });
        pull.start();
```

**Comment by hideki** [comment]
Hi @npomfret,

I also tested SG session ID with LiteServ which is the app with support REST API. (https://github.com/couchbase/couchbase-lite-android-liteserv)

Following `POST /_replicate`REST command
```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 43e59387-9e63-774b-c60e-ff186f7b78b8" -d '{
  "continuous": true,
  "source": {
    "url": "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/",
    "headers": {
      "Cookie": "SyncGatewaySession=c6b92c283f0990266b5a4aae89d291733ddd67b3; path=/sync_gateway; domain=pomochat-sg-write-dev.pomocorp.com; Max-Age=82799; Expires=Fri, 24-Feb-2017 08:37:49 GMT"
    }
  },
  "target": "cblite-test"
}' "http://192.168.57.101:5984/_replicate"
```

After the replicator became IDLE state, following is the response for `_active_tasks` REST API
```
[
  {
    "progress": 100,
    "continuous": true,
    "source": "https://pomochat-sg-write-dev.pomocorp.com/sync_gateway/",
    "status": "Idle",
    "task": "repl001",
    "change_count": 12155,
    "target": "cblite-test",
    "completed_change_count": 12155,
    "type": "Replication"
  }
]
```

From this test results, Sync Gateway Session ID is valid, and CBL Android set properly Session ID in Cookie Header value.

**Comment by npomfret** [comment]
I might not have explained that I don't know how to reproduce this bug.  But I'm 100% sure it exists and I currently have 2 devices, one virtual iOS and one physical android phone, that are exhibiting the problem.  Also, I'm not using the native API, I'm using the REST api.

**Comment by npomfret** [comment]
Ok, so unfortunately today the iOS device stopped showing the problem.  I did a build from your trunk in order that I could add a load of logging in to check which cookie, if any, was being used.  But on restart the problem was no longer there.  However, I then was having a different issue which was that document updates were not coming though.  I checked the users _changes feed and all new documents were missing.  

I ended up restarting the sync-gateway and all the missing documents started to appear.  Is it possible this error was down to the sync gateway after all?  I seems most likely to me, otherwise both iOS and android would have to have the same bug.  I think it was sometimes returning a 401 when it shouldn't.  After the restart its no longer happening.

https://github.com/couchbase/sync_gateway/issues/2345

**Comment by pasin** [comment]
@npomfret You could log all header fields of the request in this method below:

https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLRemoteRequest.m#L115-L122

**Comment by npomfret** [comment]
Hi,  so my iOS device stopped having the problem.  I don't know what changed other than I restarted the SG.  However, my android device still has it - but I cannot debug it because it's got a production build on.

Here's the log https://gist.github.com/npomfret/46ffab065ad8b687fd0e8deb9a5a0264

I hope it shows that just one cookie is being used (`85834d3376899302734c0c3ab69a49a5d21cd9c5`), it works for a bit but eventually dies with a 401.  Interestingly here my app performs a number of one-shot pull replications which don't fail with a 401.  It's not until the continuous replication starts is there an error.

**Comment by hideki** [comment]
Hi @npomfret,

CBL Android logging does not print HTTP request headers. From current log message, we don't know what cookie values the client sends.

Can you do one of the followings:
- Build CBL Android with modifying the code to print HTTP request header. CBL android uses OkHTTP library as Http client. Please refer the following link to print Http request header. http://stackoverflow.com/questions/24952199/okhttp-enable-logs
- Run Sync Gateway with supporting HTTP (nonsecure connection), and please capture HTTP traffic?

**Comment by npomfret** [comment]
How do I create a build though?  I tried following https://github.com/couchbase/couchbase-lite-android/wiki/Add-Couchbase-Lite-to-your-project-as-a-submodule already but got a duplicate class error.  I gave up after several hours, I just couldn't figure out what was wrong.  How can I build a custom version of CBL and include it in my gradle in place of the current release?

The only device that suffers from the problem has a production build on it, and the production server does not (and am not going to change it) accept http traffic.

The logs I've sent you show that my app is passing a single working session to CBL via the rest api.  From there it's possible that CLB is either not it, or the sync gateway is ignoring it.

**Comment by chayanbhaisare** [comment]
Hi @npomfret,
Did you able to find a solution for this issue?

We are facing exactly the same issue - https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/issues/92

**Comment by npomfret** [comment]
Unfortunately not, it's a mystery.

**Comment by adamcfraser** [comment]
@npomfret I haven't reviewed this in a while - I'd been assuming it had been resolved on the Android side.

One question about your latest logs (https://gist.github.com/npomfret/46ffab065ad8b687fd0e8deb9a5a0264)

It looks like the domain specified on your cookie doesn't match the target domain in several places (cookie has pomochat-sg-write-dev.pomocorp.com, request is targeting pomochat-sg-read-dev.pomocorp.com).  Is that expected?

**Comment by npomfret** [comment]
I looked into that, it doesn't seem to matter - the system works (most of the time), I just get the occasional problem with replication...

**Comment by adamcfraser** [comment]
How occasional are we talking about?  I'm trying to work out whether this is potentially an transient error being returned when Sync Gateway attempts to look up the session document from Couchbase Server.

**Comment by npomfret** [comment]
Its not happened for a while.  When I originally reported it I think I had 2 or 3 devices/vms at home that had the problem.  And I suspect a couple of people testing my app had it too.  I think the last one has recently _unblocked_ itself for want of a better word and so right now I don't have any issue.  

I've upgraded the sync gateway recently, started bouncing it every day.  Not a great solution, but something I've done seems to have made it better.

**Comment by chayanbhaisare** [comment]
Hi @adamcfraser @npomfret 

I watched network traffic(using wireshark) on Sync Gateway and I came to know that cblite is sending old session with the /db/_local request while from app I am passing valid session to cblite for starting the replicator.

E.g. 
Say B456 is the valid session
App -> Cblite 
```
POST /_replicate
Request Payload
{
       continuous: true,
       headers: "SyncGatewaySession=B456",
       source: "edc",
       target: {
              headers: {
                     Cookie: "SyncGatewaySession=B456",
                     url: "http://sg-url/db"
              }
       },
       whatfunc: "pushVar"
}
```

But what cblite is passing to sync gateway:
```
GET /db/_local/486d3ddbfd029024a7a99287c6980b053dcc1c1f
Headers
Cookie: "SyncGatewaySession=A123" // old cookie
```

**Comment by npomfret** [comment]
@chayanbhaisare that's interesting, I wasn't able to get wireshark working.  I thought it was more likely to be a bug in the GS because I had both iOS and Android clients with the problems.  Maybe they both have the same issue?

**Comment by chayanbhaisare** [comment]
@npomfret 
We are using Cordova Android, not sure about IOS.
But it seems 'only after some hours' this problem starts which makes cblite to send old session.
You can try capturing HTTP Requests that will help you to identify the root cause of your issue.
As per the initial findings I think the issue is on CBLite side.

**Comment by jamesnocentini** [comment]
It appears that the exact same discussion is currently taking place on the forums. It would be great if we all converged on the same thread here https://forums.couchbase.com/t/sync-issue-please-help/12315/14. We should use the forum until there is clear evidence this is a Couchbase issue. We can then use GitHub if it does turn out to be a Couchbase issue or feature enhancement. Thanks.

**Comment by hideki** [comment]
I believe this issue is the same problem with https://github.com/couchbase/couchbase-lite-java-core/issues/1617 This issue is addressed with [this PR](https://github.com/couchbase/couchbase-lite-java-core/pull/1618)

**Comment by npomfret** [comment]
That's good to hear.

What release will it be included in?

I've had the same issue with iOS, is there a fix coming for that was well?
