### ISSUE TITLE
sg-replicate functional tests

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1666]
## Basic test: Admin port 4985 + channels
- Kick off SG's
- Add docA in channel A
- Add docB in channel B
- Kick off sync with channel filter equal to A
- Make sure it sync docA and not docB
## Basic test: Public port 4984 no auth
- Kick off SG's with guest user having access to all channels
- Same as basic test against admin port, but on port 4984.
## Basic test: Public port 4984 with auth
- Kick off SG's with foo user having access to all channels
- Test authorizes as foo user
- Same as basic test against admin port, but on port 4984.
## Basic test: Public port 4984 with auth + channels
- Kick off SG's with foo user having access to certain channels
- Test authorizes as foo user
- Add docs to source, some in accessible channels, some not
- Kick off replication as foo user
- Make sure that only the docs in the accessible channels get sync'd
## One shot replication test against non-existent db
- Kick off replication against non-existent db
- Expect a 4xx error
## Continuous replication test
- Kick off continuous replication
- Add docs
- Wait til all docs sync to target
- Shutdown target
- Add more docs
- Wait til all docs sync to target
## Active tasks for continuous replication
- Verify empty
- Start continuous replication
- Wait until IN PROGRESS
- Stop replication
- Wait until DONE
## Deleting replication in progress
- Kick off continuous replication
- Delete replication
- Verify that it's gone from active_tasks
- Add docs
- Wait a few seconds
- Verify that the docs were not propagated to target
## Deleting a database when a replication is in progress
- Kick off continuous replication
- Delete database
- Query active tasks and make sure it's empty
## Create the replications twice in a row
- Does it give a 409 response?
## One shot replication with async=true flag
- Passed in json
- Verify that it does not block
- Default (false .. couchdb behavior)
## Test for replication ID

Should fail against this commit: https://github.com/couchbase/sync_gateway/commit/5d1fda4a3e09b5bdf2f22df55d97edfbb9348586

```
{"replication_id":blah, "cancel": True} 
```
## TODO: Verify response from one-shot replication

Should contain correct number of docs

**Comment by tleyden** [comment]
@ajres / @adamcfraser I just tried to run the basic test against the latest commit (b84e180) and got a 500 error when the test tried to POST to the `_replicate` endpoint:

```
{"error":"Internal Server Error","reason":"Internal error: Replication Aborted"}
```

In the sg logs I see:

```
2016-04-04T19:08:15.742Z HTTP:  #004: POST /_replicate  (ADMIN)
2016-04-04T19:08:15.748Z WARNING: Couldn't interpret error type *errors.errorString, value Replication Aborted -- base.ErrorAsHTTPStatus() at error.go:63
2016-04-04T19:08:15.748Z HTTP: #004:     --> 500 Internal error: Replication Aborted  (6.3 ms)
```

**Comment by ajres** [comment]
Pull the latest commit that @adamcfraser just merged, those tests have been removed now that the backend has been integrated.

**Comment by tleyden** [comment]
Found and filed https://github.com/couchbase/sync_gateway/issues/1678 (Replication continues even after stopped)

**Comment by sethrosetter** [comment]
test failures with build 1.3.0-134 -  http://qa.sc.couchbase.com/view/mobile/job/centos7-robot-sync-gateway-functional-tests/101/robot/

**Comment by tleyden** [comment]
Looks like the failures were related to https://github.com/couchbaselabs/mobile-testkit/pull/434

I'm going to close this as completed.

@sethrosetter if we find more test failures, go ahead and re-open this
