### ISSUE TITLE
Pass sync_gateway logging settings through to sg-replicate

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1676]
Could follow a similar approach to what's done for gocb - when the 'Replicate' key is set (or "*"), enable all logging for sg-replicate.

I don't think there's a need to support more granular logging within sg-replicate, since almost all the sg-replicate logging uses the "Replicate" key.

**Comment by tleyden** [comment]
What is the current state of logging in sg-replicate?  I mean, how do I enable it before this change is done?

**Comment by adamcfraser** [comment]
I don't think there's a way to enable the logging via config before this change is done - would need to modify the code to call logg.LogKeys["Replicate"] at some point.

**Comment by ajres** [comment]
I have added support for passing logging keys to sg-replicate, but I noticed the logg package does not render timestamps as ISO 8601 Format. For consistency we should probably fix that.

pushed to feature/issue_1663_replicate

**Comment by adamcfraser** [comment]
@ajres Good point.  Longer term we should consolidate on a single logging library.  I hadn't realized that  https://github.com/couchbase/clog was originally extracted from Sync Gateway - we could think about switching sg-replicate to use that, then eventually move SG to using it as well.  I don't think the ISO 8601 enhancements we made in SG have made it there yet, though, so it might turn into more work.
