### ISSUE TITLE
Replication continues even after stopped

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1678]
This [assertion](https://github.com/couchbaselabs/mobile-testkit/blob/feature/issue_1666_sg_replicate_func_tests_rebased/testsuites/syncgateway/functional/test_sg_replicate.py#L111-L117) is failing.

The replication is [stopped](https://github.com/couchbaselabs/mobile-testkit/blob/feature/issue_1666_sg_replicate_func_tests_rebased/testsuites/syncgateway/functional/test_sg_replicate.py#L99-L103)  and it even waits until active_tasks is empty, but [adding a new document](https://github.com/couchbaselabs/mobile-testkit/blob/feature/issue_1666_sg_replicate_func_tests_rebased/testsuites/syncgateway/functional/test_sg_replicate.py#L106) is propagating to the target Sync Gateway, when it should not be doing so since the replication should have been stopped.

**Comment by adamcfraser** [comment]
I wasn't able to reproduce via manual testing - once the replication is cancelled, the new doc isn't available from the target DB.

Can we get any additional diagnostics/logging on the test output?

**Comment by tleyden** [comment]
Yes, will re-run and collect more diagnostics

**Comment by tleyden** [comment]
Ngrep output: https://gist.github.com/tleyden/ed875485f41de78e90b95caaf95a7373

**Comment by tleyden** [comment]
Sync Gateway logs: https://gist.github.com/tleyden/b8459c480e4abc0b2b581a67b6941c58

**Comment by tleyden** [comment]
Ugh, nevermind, I just realized that these Sync Gateways are backed by the same couchbase database!!

**Comment by tleyden** [comment]
I'm updating the test to detect this scenario .. before it even starts a replication it verifies that the doc does not sync to the target, or else it fails the test.
