### ISSUE TITLE
SGW /{db}/{doc}?revs_info=true doesn't show revision info

### ISSUE THREAD

**Issue by pasin** [couchbase/sync_gateway#1680]
Based on the [documentation](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/sync-gateway/rest-api/document-public/get-db-doc/index.html), `revs_info query parameters to specify that the response includes information about the known document revisions.`

**Comment by adamcfraser** [comment]
That looks like a docs issue in the example - SG only supports revs and open_revs, as specified in the table at the top.

@pasin Is there functionality you're looking for that's not provided by either revs=true or by using something like open_revs=all?

**Comment by pasin** [comment]
Basically I would like to show a list of all revs of the document. If a revision has body (body is not missing), there will be a link to show the revision body. 

The `revs=true` will give me a list of revision ids but no information that the revision body of each rev-ids exists or not.

**Comment by adamcfraser** [comment]
Non-leaf revision bodies are transient - they get set to expire after 5 minutes - so I'm wondering whether it's ideal to include a link that could become invalid while the list is still loaded.

If you think it's still useful, let me know the priority and we can get support for revs_info added - I don't think it would be too much work.

**Comment by zgramana** [comment]
@pasin to respond, and we'll pickup next sprint.

**Comment by pasin** [comment]
Currently I don't need this feature in the admin UI. I could work around this by just display an error message. Let me close the issue and if I really need it, I will reopen it.
