### ISSUE TITLE
Allow forward slashes in attachment names

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1683]
Given an attachment with a forward slash in the name, SG will not handle the route correctly. Instead, the route matching should not be greedy with respect to `/`, and instead stop caring about `/` once it has a `dbname,doc-id` tuple.

For example, the following fail, but would be expected to work (as they [do for local docs](https://github.com/couchbase/sync_gateway/search?q=%252F&type=Issues&utf8=✓)).
Given:
1. db name = 'todomvc'
2. doc id = 'app'
3. attachment name = 'folder/todoEscape.js'

I expect this to return '201':

```
curl -X "PUT" "http://127.0.0.1:4984/todomvc/app/folder/todoEscape.js?rev=foo \
    -H "Content-Type: application/javascript" \
    -d ...
```

And I expect this command to return the `.js` file that I previously `PUT`.

```
curl http://127.0.0.1:4984/todomvc/app/folder/todoEscape.js
```

**Comment by ajres** [comment]
This feature is already supported, but with the following caveats.

When both file names and attachment names contain '/' characters, there is no obvious way to determine the boundary between the file name and attachment name.

SG handles this by requiring embedded slashes to be escaped using URL encoding ('%2F') in all requests.

e.g. the following steps work:

`curl -X PUT http://localhost:4985/db/doca -H "Content-Type: application/json" -d '{"foo":"bar"}'`

`curl -vX PUT http://localhost:4985/db/doca/attachments%2F50k.png?rev=2-24bfd66d8c0b8a150e12deefd4a06edf --data-binary @50k.png -H "Content-Type: image/png"`

`curl -vX GET http://localhost:4985/db/doca/attachments%2F50k.png > /dev/null`

Additional unit tests have been added to ensure this behaviour does not regress.
