### ISSUE TITLE
Define separate community and enterprise AMI packaging

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1687]
See also: https://github.com/couchbase/sync_gateway/issues/1154

**Comment by tleyden** [comment]
Docs on manually creating an AMI: http://hub.internal.couchbase.com/confluence/pages/viewpage.action?title=AWS&spaceKey=CR

**Comment by tleyden** [comment]
TODO:
- [x] Debug failure
- [x] Parameterize jenkins job
- [x] Make AMI public and put it in all regions  (Automate it or put in docs)
- [x] Use Packer template from version control rather than pasting into Jenkins textbox
- [x] Create a new slave and use that slave
- [x] Create user-facing README on how to run the AMI
- [x] Make the user-data script support three different usages via config flags
- [x] Gerrit PR
- [x] Delete fork
- [x] Update Jenkins to `couchbase/build` repo

**Comment by tleyden** [comment]
@sethrosetter I pushed up another set of changes;

http://review.couchbase.org/#/c/63549/

btw, I decided to punt on unhackifying this until a later ticket:

```

    echo "Sleeping to wait until Couchbase Server is ready"
    # When testing, I saw a case where these messages appeared in the Sync Gateway logs:
    # 2016/04/27 22:27:52 Non-healthy node; node details:
    # Hostname=ec2-54-173-225-77.compute-1.amazonaws.com:8091, Status=warmup, ...
    # TODO: this should query the Couchbase Server REST API to check the node is healthy
    # instead of sleeping
    sleep 30
```

**Comment by tleyden** [comment]
@sethrosetter also, recent successful Jenkins build:

http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-ami/29/console

**Comment by tleyden** [comment]
Merged to couchbase/build master and jenkins job working:

http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-ami

**Comment by tleyden** [comment]
- [x] Check if user data is run on every reboot or just 1st time

**Comment by tleyden** [comment]
- [x] Rpm -uvh (u = update)

**Comment by tleyden** [comment]
Todos from show and tell meeting:
- [ ] Build two sets of ami's: community and enteprise.  NOTE: name of AMI must be parameterized

**Comment by tleyden** [comment]
- [ ] What if I want to update the Sync Gateway config URL?  Can I update the user data script?

**Comment by tleyden** [comment]
- [ ] s3sync the file remotely, then use fswatch to watch for changes and restart sg.  (or use ec2 run command)

**Comment by tleyden** [comment]
@zgramana / @adamcfraser / @michaelkwok 

I verified that the user-data script is only one run once during the initial ec2 instance launch:

https://gist.github.com/tleyden/b81216eb58b7459c8ad5f24dcfd4c398

(note that there is only one instance of `/etc/init.d/sync_gateway start` in the log, but several instances of `Cloud-init v. 0.7.6 finished`)

**Comment by tleyden** [comment]
Done. Sample jenkins run: http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-ami/47/
