### ISSUE TITLE
Implement OpenID Connect relying-party support

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1688]
As an application architect, I want Sync Gateway to be able to use my existing SSO infrastructure so that I only need to maintain a single database of users identities and the resources that they have authorization to access, reducing both time-to-market and administrative overhead.

**Comment by adamcfraser** [comment]
![authcodeflow](https://cloud.githubusercontent.com/assets/8866453/15128138/f3b6db9c-15ee-11e6-8ed0-6e209b25fe74.png)

**Comment by adamcfraser** [comment]
![implicitflow](https://cloud.githubusercontent.com/assets/8866453/15128144/fbaccadc-15ee-11e6-8aa0-42475c98fcf4.png)

**Comment by adamcfraser** [comment]
Design notes: [OpenID Connect Notes](https://github.com/couchbase/sync_gateway/wiki/OIDC-Notes)

**Comment by adamcfraser** [comment]
Subtasks:
- [x] #1772 - Internal Test OP
- [x] #1773 - Auth flow endpoints
- [ ] #1774 - OIDC functional testing
- [x] #1775 - SG authentication using JWT token
