### ISSUE TITLE
building from source (commit 970b213) breaks ssl in browser, at least for self-signed certs

### ISSUE THREAD

**Issue by yonahforst** [couchbase/sync_gateway#1692]
I built from source (to get https://github.com/couchbase/sync_gateway/pull/1618) and suddenly I can't access sync_gateway via HTTPS from my browser.

I'm using a self signed certificate (following https://github.com/couchbase/sync_gateway/wiki/SSL-support#creating-your-own-self-signed-cert) and forwarding 443 to 4984 from iptables: `-A PREROUTING -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 4984`

My apps still work fine (android and ios using the CBL SDKs) and I'm able to curl from the terminal. But when try to access the sync_gateway via the browser (or browser-based api tools, such as postman) the requests fail. I've tested it with chrome, safari, and firefox; windows and OSx,

Chrome shows "ERR_CONNECTION_CLOSED" Here's an capture from chrome://net-internals/#events: https://gist.github.com/joshblour/b7aa0c45d5a39585d72b2a53956ab194 (see line 198)

Safari and firefox just show the request starting but never receives a response.

**Comment by adamcfraser** [comment]
Thanks for the report.  A couple of questions:
1. What method did you use to build from source - with or without dependency pinning?
2. Was your self-signed cert working when running against Sync Gateway 1.2?

**Comment by yonahforst** [comment]
Hi @adamcfraser.

I built from source **with** dependency pinning.
Yes, it was working when running against 1.2 (downloaded from http://www.couchbase.com/nosql-databases/downloads#cb-mobile)

**Comment by adamcfraser** [comment]
@joshblour I wouldn't expect any difference in SSL handling between 1.2 and master, then.  It's interesting that you're only hitting this via the browser, and not from curl/your application.

What version of go are you using to build?  I believe 1.2 was built with go 1.5.3.

**Comment by yonahforst** [comment]
I'm using 1.5.1. Shall I try with 1.5.3?

**Comment by yonahforst** [comment]
just rebuilt with 1.5.3 from commit 062bc26. same issue

**Comment by yonahforst** [comment]
I just noticed that there is a new 1.2.1 release. Is there somewhere I can download it from?

**Comment by yonahforst** [comment]
upgrading to 1.2.1 solved this issue for me
