### ISSUE TITLE
Write Docs for _replicate function

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1697]
We need api and guide docs for new _replicate function

**Comment by adamcfraser** [comment]
@ajres to update for the latest changes to user-defined replication name/id handling.

**Comment by ajres** [comment]
Updated with user defined replication_id's

**Comment by zgramana** [comment]
The PR on the docs portal is https://github.com/couchbaselabs/couchbase-mobile-portal/pull/310

**Comment by ajres** [comment]
Closing as @jamiltz merged PR couchbaselabs/couchbase-mobile-portal#310
