### ISSUE TITLE
Syncgw database offline and online behavior when one of couchbase node goes offline

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#1701]
Below are the observation found in sync gateway during couchbase reboot
1. sync gateway is deleting the database while bring database online from offline when underlying couchbase is still not reachable
2. One of sync database(i have two database) is going to offline when one of couchbase node (clustyer of 2 nodes)stopped. Database gets deleted when POST /_online request to make database online though one couchbase node still healthy
This should not be a expected behavior, if one node goes down in couchbase cluster , it will effect client as sync databases going offline though some of nodes are available to server

please let me now if this is how syncgateway behaves. and is there any config we can do changes to bring database online state.
is there any auto recovery from syncgateway offline to online state when couchbase up and running .
 i have got below error

11:34:37.243565 2016-04-18T11:34:37.243+05:30 WARNING: Lost TAP feed for bucket pttdata, with error: Get http://xx:8091/pools/default/bucketsStreaming/pttdata: dial tcp xx:8091: getsockopt: connection refused -- rest.(*ServerContext)._getOrAddDatabaseFromConfig.func1() at server_context.go:646
11:34:37.243587 2016-04-18T11:34:37.243+05:30 CRUD: Taking Database : pttdata, offline
11:34:37.243596 2016-04-18T11:34:37.243+05:30 CRUD: Waiting for all active calls to complete on Database : pttdata
11:34:37.243604 2016-04-18T11:34:37.243+05:30 CRUD: Database : pttdata, is offline

**Comment by ajres** [comment]
@ArihantRk 

How are you stopping the Couchbase Server node in your cluster.

**Comment by ArihantRk** [comment]
Am stopping with /opt/couchbase/etc/couchbase_init.d stop

regards,
arihant

**Comment by ajres** [comment]
@sethrosetter Do we have a functional test for automatic offline when a single node in a cluster goes offline?

**Comment by ArihantRk** [comment]
@ajres or @sethrosetter, any luck on above request?
