### ISSUE TITLE
Ability for Sync Gateway to bring itself back online after unexpected offline

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1710]
When Sync Gateway loses the TAP feed, it gets moved to Offline mode.  In most cases the desired behaviour is for Sync Gateway to go back online once it's able to connect to the TAP feed again.  Currently this requires a manual step - calling the _online endpoint on the Admin API.  

I propose that when Sync Gateway goes offline unexpectedly as result of a lost TAP feed (i.e. not via a call to the _offline API endpoint), Sync Gateway should periodically attempt to reconnect to the feed and take itself online without user intervention.

To retain user configuration of this behaviour, we could add an optional `disable_reconnect` flag to the config that would disable the reconnect behaviour.

**Comment by atom992** [comment]
+1

**Comment by vk07519** [comment]
Which version of Sync Gateway contains this issue fix?

**Comment by tleyden** [comment]
@vk07519 it had the 1.3 milestone, so I'm gonna assume 1.3
