### ISSUE TITLE
1.3.0 sg_accel package contents wrong

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1711]
Invalid package contents - http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.3.0/1.3.0-128/couchbase-sg-accel-enterprise_1.3.0-128_x86_64.tar.gz. 

When I extract the tar, I notice 2 issues. 
- [ ] There is a nested sync_gateway package
- [ ] There is a sync_gateway binary in the bin/ rather than an sg_accel

**Comment by adamcfraser** [comment]
We need to switch sg-accel to build from https://github.com/couchbaselabs/sync-gateway-accel anyway - I'll file a ticket for the build team to get that done.

**Comment by michaelkwok** [comment]
Sure, that was one of the action items I need to do for 1.3.0.

**Comment by michaelkwok** [comment]
sg_accel is now building from couchbaselabs private sync-gateway-accel

**Comment by michaelkwok** [comment]
@seth can you verify once again.  Thanks

**Comment by sethrosetter** [comment]
@michaelkwok Where are the build packages?

**Comment by sethrosetter** [comment]
These issues are resolved in - http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.3.0/1.3.0-188/couchbase-sg-accel-centos_enterprise_1.3.0-188_x86_64.tar.gz
