### ISSUE TITLE
Add arm build to standard build process

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1718]

**Comment by househippo** [comment]
:thumbsup:

**Comment by zgramana** [comment]
Need to clarify ARM7, ARMv7a, and/or ARM8

**Comment by adamcfraser** [comment]
Should be an easy build change - can just get deployed to latestbuilds along with the rest of the platforms.

**Comment by djpongh** [comment]
Opened: https://issues.couchbase.com/browse/MB-25541 to track
