### ISSUE TITLE
Replication inaccurate 403 forbidden

### ISSUE THREAD

**Issue by Crapulax** [couchbase/sync_gateway#1720]
Hi,

In link and as a continuation of issue https://github.com/couchbase/sync_gateway/pull/464, when the channel granting document is sent, within a bulk_docs, and after granted document, replication fails. Is there a smart way to handle such issue?
What is hapenning is that when the SG process the granteed document, it gets rejected by the validation function. As the document granting the access has not been processed yet.

As far as I have seen there is no way on the client side to:
1- catch in a programatic way that a replication error occured. The information about the document replication failure is in the couchdb log but nowehere else (not in _active_tasks) for instance. In active_tasks you only see the counter doc_write_failure increasing.
2- inform the replicator to replicate document in creation order

As in the meantime you have no network garantee (from mobile) you are likely to run into this issue...

I am looking on two ways to recover from this situation:
1- Parse the SG logs from a server and request the client to update the offending document (assuming granting acces doc was replicated since then). Very dirty solution in my view. And not sure all further failed document will resync anyway.
2 - Wait for grantor document replication to finish before creating depending documents. This is generating processing and complexity overhead on client side. It is also against the concept of  offline mode offered by couchbase-lite!

Yes this issue should probably more be handled on couchdb /. couchbase-lite sides but it is making the sync gateway usage difficult so you might probably want to handle it directly.

below according logs from SG:
016-04-22T16:11:50.899Z HTTP:  #108629: POST /XXXX/_revs_diff  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)
2016-04-22T16:11:50.991Z HTTP:  #108630: POST /XXXX/_revs_diff  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)
2016-04-22T16:11:51.002Z HTTP:  #108631: POST /XXXX/_revs_diff  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)
2016-04-22T16:11:51.059Z HTTP:  #108632: POST /XXXX/_revs_diff  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)
2016-04-22T16:11:51.118Z HTTP:  #108633: POST /XXXX/**_bulk_docs**  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)
***********************************\* debut XXXX USER *************
true
doc id:a4422b6c3812b92d019d46766906f7fc
doc XXXXuser_id:0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb
doc pseudo:cccc
doc XXXX_id:-cvqi7DbLeyr7QzEblCI6dk
***********************************\* fin XXXX properties
2016-04-22T16:11:51.120Z **Sync fn rejected**: new=map[XXXXuser_id:0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb _revisions:map[start:1 ids:[5a1107e8fac754365cd79a9a67fc021
5]] _id:a4422b6c3812b92d019d46766906f7fc _rev:1-5a1107e8fac754365cd79a9a67fc0215 pseudo:cccc creationDate:2016-04-22T16:11:40.263Z type:XXXXUser XXXX_id:-cvqi7
DbLeyr7QzEblCI6dk]  old= --> 403 missing channel access
2016-04-22T16:11:51.120Z        BulkDocs: Doc "a4422b6c3812b92d019d46766906f7fc" --> 403 missing channel access **(403 missing channel access)**
2016-04-22T16:11:51.131Z HTTP:  #108634: POST /XXXX/_bulk_docs  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)
***********************************\* debut MESSAGE
true
doc._id:a4422b6c3812b92d019d46766906feca
message:Dhdhdh joins our XXXX!
XXXX_id:-cvqi7DbLeyr7QzEblCI6dk
creator_id:0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb
pseudo:Dhdhdh
creationDate:2016-04-22T16:11:40.312Z
***********************************\* fin msg properties
***********************************\* fin message
2016-04-22T16:11:51.191Z HTTP:  #108635: POST /XXXX/_bulk_docs  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)
***********************************\* debut INVITE ***********\* **This is the granting channel access doc**
true
doc id:92002d59cc4ea4ab76499a583e4e002f
doc XXXXChannel:-cvqi7DbLeyr7QzEblCI6dk
doc invitedUser_id:0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb
doc inviteStatus:accepted
doc invitingOwner_id:abb20185-1955-450b-baf4-8a7a063827af
***********************************\* fin XXXX invite properties
***********************************\* fin INVITE *******************
2016-04-22T16:11:51.879Z HTTP:  #108636: POST /XXXX/_ensure_full_commit  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)
2016-04-22T16:11:52.018Z HTTP:  #108637: PUT /XXXX/_local/73e62a7fb4d15bfe8778ea42f273db4d  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)
2016-04-22T16:11:52.066Z HTTP:  #108638: GET /XXXX/  (as 0ad9eed4-4e2c-43ae-9a0e-10f1bfe0d3cb)

**Comment by Crapulax** [comment]
For whoever might be interested, We started implemented a third option to workaround the issue which is working well with Chrome/CouchDB, couchbase-lite/IOS.

Solution consists
- to cancel continuous replication before modifying a document granting access
- replicate this granting document using the doc_ids field replication parameter
- resume continuous replication once above document is successfully replicated

Full solution will require a bit more work as we need to deal with several consecutive granting documents, and handle gracefully stop of the application while all granting documents are not yet replicated... but it works.

Not tested yet with couchbase-lite Android.

**Comment by adamcfraser** [comment]
Often this type of issue can be avoided with a change to how the channels are modeled - in this case, for example, by enabling channel write access when the invite is issued, instead of accepted.  However, it's likely there are cases that would still be difficult to avoid.

We could consider the following enhancement on the Sync Gateway side to add retry processing within a single bulk_docs call:
- Process all docs in the bulk_docs as usual
- In the case where a subset of the docs are rejected due to access restrictions (403s), reload the user context and attempt to resubmit those documents

This behaviour could be enabled by a new flag on the bulk_docs request, to allow users to opt-in to this processing.  

To handle the case of multi-level nested access grants, the flag on the bulk_docs request could represent a counter for the number of times to attempt retry (although retry loop should be terminated whenever zero of the retry attempts are successful).

**Comment by Crapulax** [comment]
Hello Adam,

Thanks for your reply, it is really appreciated!
We do not want to enable channel access when invite is issued in our case, because this would mean that all associated documents would be sync BEFORE you accepted the invite.

Thinking about the enhancement you are proposing, with a small adjustment, we could end up with something perfect, working 100% of the time. Just allow the sender to set a _order field in the documents specifying the processing order. If bulk fails, just try processing the document as defined by the _order field. Like this we avoid retrying x times processing and if it fails the issue is real. This ordering field could be defined as a parameter in the SG configuration, like this it will be transparent for the replication source (no need to change protocol or aligned sender versions). What do you think?

Thanks,
Steve.

**Comment by adamcfraser** [comment]
@Crapulax On the invite timing - you're right, you'd need to use two channels (one for write access, one for read access) to avoid that problem.  

On the _order suggestion - my main concern is probably that it requires each developer to write the code to populate the order field in their application.  Changes to the sync function would then (potentially) require changes in the application code to change the _order handling.

**Comment by Crapulax** [comment]
Thanks for the quick reply.
The invite in our case is granting the read access, not the write access (granted through another channel). What we want avoid is to send a client data that he/she is not willing to receive (i.e. invitation not accepted). So invite is a gateway opening the door for read and by the way document replication.
The client is first receiving the invite and only it and then, if it is accepted, the read channel access to the real documents gets granted by the invite.

The _order sounds to me as a kind of counter that I filled when creating documents, it does not need to be sequential or whatever but just an ordered int. I create my documents in the order which is from an application view point correct (gaining access before using the access) incrementing my counter. Whatever I do in my sync function would remain transparent unless I am changing the logic of access granting. But this would anyway require changes in my application processing.

I let you think about it and thanks again for your valuable answers.

PS: by the way i have implemented the Third option mentionned above (with stop / named replication/ restart continuous replication) and it works well. But I will be happy to remove that bunch of code which is creating unnecessary complexity and is somehow risky.

**Comment by adamcfraser** [comment]
Attempting to identify whether this is a result of a race in a scenario like the following

1. _changes processing starts with since=n, identifies the set of channels for this request as ["A"]
2. Document is cached with sequence=n+1, in channel A, granting access to channel B
3. Client is sent sequence n+1, last_seq=n+1

4. Next changes request with since=n+1, identifies the set of channels for this request as ["A", "B"].  Here SG is skipping the backfill, because the since value isn't earlier than the sequence that granted access (i.e. SG thinks backfill should have already happened for this channel). (https://github.com/couchbase/sync_gateway/blob/master/db/changes.go#L364)

If that's the issue, one-shot replication needs to be changed to not send any sequence values later than the value at the time the channel set was calculated.  In the above example, this would result in sequence n+1 not being sent until the second changes request, at which point it would trigger the backfill as expected.

**Comment by adamcfraser** [comment]
The described issue sounds like the same as https://github.com/couchbase/sync_gateway/issues/422 - tracking potential enhancement with that ticket.
