### ISSUE TITLE
Log all changes to SG on admin port - Improvement

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#1721]
Since admins do not require authentication and only access to port have all CRUD operation be logged.

**Comment by adamcfraser** [comment]
Do you have a any more details on the use case you're thinking of?  There are a few different ways this could be implemented, so it would help to know a few more specifics.  

In particular - much of the logging output isn't necessarily tied to an API call, aside from the HTTP/HTTP+ logging.  For example, the CRUD/cache logging could get triggered by background processes that are run with no user context(shadowing, auto-import), as well as direct API calls.  

What type of admin logging/diagnostics would be useful to be able to isolate?

**Comment by househippo** [comment]
Let me change the requirement and title to "logging all changes".

Things like logging: 
- any PUT to /{db}/_config (changes to DB(s))
- creating / updating / deleting users or channel access
- create / update / deletes of any docs _local or non _local
- when /{db}/_online  , _offline , _purge & compact  
- create/update/delete views

The above are all DB changes but as far as READs(GETs) thats can be leverage via [HTTP,HTTP+] right?

-Thank you

**Comment by adamcfraser** [comment]
@househippo Currently these would all get logged with the usual HTTP logging, and would show (ADMIN) as the calling user to indicate they were run by an Admin.

e.g.

```
2016-04-26T11:35:17.833-07:00 HTTP:  #001: GET /default/  (ADMIN)
```

Is the enhancement request to support enabling HTTP/HTTP+ logging for ADMIN, while disabling it for non-admin requests (to manage log size and make it easy to isolate the admin logging)?

**Comment by househippo** [comment]
> Is the enhancement request to support enabling HTTP/HTTP+ logging for ADMIN, while disabling it for non-admin requests (to manage log size and make it easy to isolate the admin logging)?

Yes, so like [AdmiHTTP,AdminHTTP+,AdminCRUD,AdminCRUD+]

The alternative would be to have SG create another set of logs just for admin which would have its own [*] or [HTTP,HTTP+,CRUD,etc] which would make it harder to debug issues reading between two logs.

**Comment by househippo** [comment]
> Yes, so like [AdmiHTTP,AdminHTTP+,AdminCRUD,AdminCRUD+]

There has to be a more elegant and simpler solution then adding more elements in the array with prefex "Admin". 
Maybe ["Admin"] = ["HTTP","CRUD","Changes",etc]
Maybe ["Admin+"] = ["HTTP+","CRUD+","Changes+",etc]

**Comment by adamcfraser** [comment]
Closing based on age - should be filed as an enhancement request in JIRA if still valid.
