### ISSUE TITLE
Doc example wrong for _bulk_get

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1727]
Expected: The example response shows a multipart response. 
Actual: The example response does not show a multipart response. 

http://developer.couchbase.com/documentation/mobile/1.2/develop/references/sync-gateway/rest-api/database-public/post-bulk-get/index.html

**Comment by adamcfraser** [comment]
Moved to https://github.com/couchbaselabs/couchbase-mobile-portal/issues/322.
