### ISSUE TITLE
Add sgcollectinfo build job to uber jenkins

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1731]
@ajres to work with @tleyden to define the work required.  Goal is to get it working on uber jenkins, and then handoff to build team for potential migration to build jenkins.

**Comment by tleyden** [comment]
Xen control center docs: http://hub.internal.couchbase.com/confluence/pages/viewpage.action?title=Mobile+Xen+Hypervisor+Cluster&spaceKey=QA

Need to build sgcollect_info on various platforms
- Windows
- OSX
- Linux

**Comment by adamcfraser** [comment]
Getting tracked in #1639.
