### ISSUE TITLE
sg-replicate: deleting database with continuous replication does not remove from active_tasks

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1738]
To reproduce:
- Run this jenkins job with these parameters: http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/22/

Test failure message is [here](http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/22/artifact/mobile-testkit/debug.txt)

```
20160504 12:00:53.110 - DEBUG - Traceback (most recent call last):
  File "/var/jenkins/workspace/syncgateway-functional-tests-dev/mobile-testkit/testsuites/syncgateway/functional/test_sg_replicate.py", line 203, in test_sg_replicate_delete_db_replication_in_progress
    wait_until_active_tasks_empty(sg1)
  File "/var/jenkins/workspace/syncgateway-functional-tests-dev/mobile-testkit/libraries/testkit/syncgateway.py", line 255, in wait_until_active_tasks_empty
    raise Exception("Tried to wait until _active_tasks were empty, but they were never empty")
20160504 12:00:53.111 - INFO - +-- END KW: test_sg_replicate.Test Sg Replicate Delete Db Replication In Progress (40880)
20160504 12:00:53.112 - INFO - +-- START TEARDOWN: Test Teardown [ ]
20160504 12:00:53.112 - INFO - +--- START KW: NetworkUtils.List Connections [ ]
```

and when I checked the live running sync gateway, the active_tasks was indeed non-empty (this was from a local run, a slightly different run than above in case things don't line up exactly)

```
[{"type":"replication","replication_id":"6566938358a5f46642fc07a55e5dd22c","continuous":true,"source":"http://s61803cnt72.sc.couchbase.com:4985/db1","target":"http://s61805cnt72.sc.couchbase.com:4985/db2","docs_read":0,"docs_written":0,"doc_write_failures":0,"start_last_seq":0,"end_last_seq":null}]
```

After committing a fix, kick off a new run with the same params as http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/22/parameters/, but use the commit from your feature branch that you pushed to github.

**Comment by tleyden** [comment]
@ajres I'm going to take a look at this one since I'm deep in this code already for another ticket (unless you are in progress .. let me know)

**Comment by tleyden** [comment]
Note that this only seems to fail sporadically.

Passes: http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/49/

Fails: http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/50/

**Comment by adamcfraser** [comment]
Planned changes to active_tasks in Hydrogen make this obsolete.
