### ISSUE TITLE
Removal of sync gateway 1.2 via package manager (dpkg) does not work if unsupported OS

### ISSUE THREAD

**Issue by mattcarabine** [couchbase/sync_gateway#1739]
I tried to install Sync Gateway 1.2 via dpkg from the .deb file on the website.

The installation appears successful in terms of creating the correct directories etc but fails at creating the init script:

```
sudo dpkg -i couchbase-sync-gateway-enterprise_1.2.0-79_x86_64.deb 
[sudo] password for matt: 
Selecting previously unselected package couchbase-sync-gateway.
(Reading database ... 146547 files and directories currently installed.)
Preparing to unpack couchbase-sync-gateway-enterprise_1.2.0-79_x86_64.deb ...
Unpacking couchbase-sync-gateway (1.2.0-79) ...
Setting up couchbase-sync-gateway (1.2.0-79) ...
ERROR: unknown OS "neon"
This script creates an init service to run a sync_gateway instance.
If you want to install more than one service instance
create additional services with different names.

sync_gateway_service_install.sh
    -h --help
    --runas=<The user account to run sync_gateway as; default (sync_gateway)>
    --runbase=<The directory to run sync_gateway from; defaut (/home/sync_gateway)>
    --sgpath=<The path to the sync_gateway executable; default (/opt/couchbase-sync-gateway/bin/sync_gateway)>
    --cfgpath=<The path to the sync_gateway JSON config file; default (/home/sync_gateway/sync_gateway.json)>
    --logsdir=<The path to the log file direcotry; default (/home/sync_gateway/logs)>

dpkg: error processing package couchbase-sync-gateway (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 couchbase-sync-gateway
```

This is not a big deal, I kind of expected this as I'm running KDE Neon (based on Ubuntu XenialXerus 16.04) which I know probably isn't supported.
I seemed to be able to run sync_gateway properly by running the binary `sync_gateway` directly, but that's rather besides the point.

As I wanted to test the new `sgcollect_info` directly (via a source-based build) I decided to remove the `sync_gateway` package using `dpkg -r`, at which point I hit the following issue:

```
$ sudo dpkg -r couchbase-sync-gateway
(Reading database ... 146916 files and directories currently installed.)
Removing couchbase-sync-gateway (1.2.0-79) ...
ERROR: unknown OS "neon"
This script removes an init service to run a sync_gateway instance.
dpkg: error processing package couchbase-sync-gateway (--remove):
 subprocess installed pre-removal script returned error exit status 1
Errors were encountered while processing:
 couchbase-sync-gateway
```

Obviously at this point the sync_gateway files are still there (I assumed that it would run in reverse from the install script, shut down the sync_gateway instance safely first and then remove the files), and I can't seem to remove sync gateway through conventional means:

```
$ ls /opt/couchbase-sync-gateway 
bin  cbcollect_info  examples  LICENSE.txt  manifest.txt  README.txt  service  sg-check.py  tools  VERSION.txt
```

I checked the `/opt/couchbase-sync-gateway/service/sync_gateway_service_uninstall.sh` file to see why this was failing my removal. It seems that the script returns 1 (indicating failure) if it doesn't recognise the OS.

This seems really unusual to me as you should be able to make the assumption that if the user has installed on an unsupported OS then they will not have been able to install the service start script in the first place, hence they should not need it removed.

Making the following change to `sync_gateway_service_uninstall.sh` allowed my `dpkg -r` to correctly remove sync gateway from my machine.

```
        echo "ERROR: unknown OS \"$OS\""
        usage
-       exit 1
+       exit 0
```

Example of output on removal:

```
sudo dpkg -r couchbase-sync-gateway                                  
(Reading database ... 146916 files and directories currently installed.)
Removing couchbase-sync-gateway (1.2.0-79) ...
ERROR: unknown OS "neon"
This script removes an init service to run a sync_gateway instance.
```

I am happy to contribute a patch to fix this issue if you think that it's appropriate, I understand if you would prefer slightly different behaviour in this edge-case.
Please let me know if you would like me to fix it in a certain manner or if you would rather one of the sync gateway team makes this fix themselves!

**Comment by tleyden** [comment]
> dpkg: error processing package couchbase-sync-gateway (--install):

Is this error related to sg_collectinfo?  If not, can you either file a separate ticket or rename the title to be a little broader?

Just want to make sure that it gets prioritized appropriately .. from the above it seems more like a general installation issue rather than something related to sg_collectinfo

**Comment by mattcarabine** [comment]
Sorry, this issue is not related to `sgcollect_info`, just an issue that I ran into when trying to get a set up for it.

The current title doesn't make any reference to `sgcollect_info`, please let me know what you think a more suitable title would be for prioritisation purposes, should I add the prefix `Installer:`?

**Comment by tleyden** [comment]
Oh, nevermind then, I must have confused the title when looking through my emails!

Although, is this just related to _removing_ sync gateway?  Seems like the first issue you ran into was related to _installing_, so maybe the title does need to be clarified a bit.

**Comment by mattcarabine** [comment]
The issue was related to just removing, I expect that installing on an unknown OS would fail, therefore the installation bit is not a _bug_.

However, removing the package which didn't successfully manage to create the init script I would expect to succeed.

**Comment by tleyden** [comment]
Gotcha.  Makes sense!

**Comment by npomfret** [comment]
@mattcarabine - thanks for this - was very useful.

**Comment by adamcfraser** [comment]
Closing based on age - can reopen in JIRA if still applies to more recent builds.
