### ISSUE TITLE
sgcollect_info - Doesn't clean up generated outputs after zipping the file

### ISSUE THREAD

**Issue by mattcarabine** [couchbase/sync_gateway#1743]
Kind of a strange one.

When building from source and running `sgcollect_info` against sync gateway, the zip file appears to be created fine (except for the issue documented in #1741) but all of the files generated by go still exist in the directory the zip was created in.

Example:

```
$ sudo ~/go/src/github.com/couchbase/sync_gateway/tools/sgcollect_info ~/sgcollecttest/testsgcollect1.zip

$ ls ~/sgcollecttest
goroutine.pdf   heap.raw                                               pprof.sync_gateway.127.0.0.1:4985.goroutine.003.pb.gz                  pprof.sync_gateway.127.0.0.1:4985.samples.cpu.001.pb.gz  profile.raw
goroutine.raw   heap.text                                              pprof.sync_gateway.127.0.0.1:4985.inuse_objects.inuse_space.001.pb.gz  pprof.sync_gateway.127.0.0.1:4985.samples.cpu.002.pb.gz  profile.text
goroutine.text  pprof.sync_gateway.127.0.0.1:4985.goroutine.001.pb.gz  pprof.sync_gateway.127.0.0.1:4985.inuse_objects.inuse_space.002.pb.gz  pprof.sync_gateway.127.0.0.1:4985.samples.cpu.003.pb.gz  testsgcollect1.zip
heap.pdf        pprof.sync_gateway.127.0.0.1:4985.goroutine.002.pb.gz  pprof.sync_gateway.127.0.0.1:4985.inuse_objects.inuse_space.003.pb.gz  profile.pdf
```

My assumption is that the files generated by go aren't appropriately cleaned up in the intermediate directory after they have been added to the zip file.

These files come from:

```
Collecting sg pprof profile -- which can take several seconds: profile format: pdf (go tool pprof -pdf -seconds=5 -output=/home/matt/sgcollecttest/profile.pdf ./sync_gateway http://127.0.0.1:4985/_debug/pprof/profile) - Exit code 1
Collecting sg pprof profile -- which can take several seconds: profile format: text (go tool pprof -text -seconds=5 -output=/home/matt/sgcollecttest/profile.text ./sync_gateway http://127.0.0.1:4985/_debug/pprof/profile) - Exit code 1
```

There aren't really any ill effects of these files as far as I can see, running the `sgcollect_info` again just regenerates them, but `sgcollect_info` should really be cleaning up files that it creates (that aren't intended output files).

As with the other issues, happy to submit a patch for this myself.

**Comment by tleyden** [comment]
I think we actually want those .gz files, since they are the "raw data" from the pprof collection.

@adamcfraser can you verify this is the case?

**Comment by mattcarabine** [comment]
I am not denying that we want the data, but as a user using sgcollect I'd expect all output to be in the zip folder I specified, not in the parent directory of that zip.

I can see that these .gz files are not in the zip file, really they should also be included and then removed from the parent directory.

**Comment by tleyden** [comment]
Oh gotcha.  So what you mean is that these files end up as unwanted residue on the filesystem?  (and then not even included in the zip?)

If that's the case, then yeah this should be fixed.  Would be great if you could submit a PR!

**Comment by mattcarabine** [comment]
I believe the script probably concats all of the .gz files into a single file in the zip folder, I will do some testing to verify this and then submit a PR based on what I find.
