### ISSUE TITLE
sgcollect_info - Tasks designed to get info from relevant processes use CB server processes

### ISSUE THREAD

**Issue by mattcarabine** [couchbase/sync_gateway#1753]
There are a number of tasks within `cbcollect_info` (and by extension `sgcollect_info`) which use process names to get the relevant data from `lsof`, `/proc` etc.

Looking at the current `sgcollect_info` output and code, it hasn't been changed from the original `cbcollect_info` code and as such tries to find processes such as `moxi`, `memcached`, `beam.smp` etc, none of which you'd be running on a `sync_gateway` server.

Will submit a PR changing these process names to `sync_gateway`, unless you think there are any others that should be covered too?

**Comment by adamcfraser** [comment]
@mattcarabine Can you clarify whether this is just a performance optimization, or whether this causes a functional problem when trying to work with the sgcollect_info output?

**Comment by mattcarabine** [comment]
This is a fundamental problem as the system-level info log for sync gateway does not collect metrics relating to sync gateway.
e.g no open files, no `/proc` info etc

**Comment by mattcarabine** [comment]
I have a PR ready that fixes this, but don't seem to have permission to create a new branch for this repository?

Do I have to do anything in particular to get that permission?
