### ISSUE TITLE
sgcollect_info should look for logs in logFilePath

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1756]
The config json allows users to specify the log path, possibly the command line args as well:

```
logFilePath string  

Absolute or relative path on the filesystem to the log file. A relative path is from the directory that contains the Sync Gateway executable file. The default is stderr.
```

**Comment by mattcarabine** [comment]
Under what circumstances would sgcollect not be able to find the logs?
Do you think it is common that users specify a custom log path?

If so then this probably needs to have its priority increased as collecting logs is the primary intent of `sgcollect_info`.

**Comment by tleyden** [comment]
> Do you think it is common that users specify a custom log path?

Probably not common

**Comment by tleyden** [comment]
One challenge for this issue is that the configuration contains invalid json for the sync function field.

**Comment by tleyden** [comment]
> Is there a REST endpoint on SGW that I can hit to get the config?

Yeah, `host:port/_config`

**Comment by tleyden** [comment]
> invalid json for sync function field

For example: https://github.com/couchbase/sync_gateway/blob/master/examples/basic-sync-function.json#L8-L24

**Comment by mattcarabine** [comment]
Re-opening due to fix being too restrictive, will push a new patch

**Comment by mattcarabine** [comment]
Pending #1840

**Comment by mattcarabine** [comment]
Needs a slight tweak for if the element being looked for does not exist (i.e should return `None`)

Found that the exceptions to be caught were not in a tuple, so not actually caught properly.

Raised #1868 to fix the issue.
