### ISSUE TITLE
Replace the SG binary in the `sgcollect_info` zip with an MD5 hash instead.

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1757]
This reduces the size of the zip file, but saving the MD5 hash to a text file in the zip allows us to match back to the `.md5` files that we release with our downloads when using `go tool pprof`. If we can't find a match, then that indicates someone is not using a supported release.

If we still want the ability to include the `.zip` in our own test infrastructure, then we can instead add a command-line to enable that (e.g. something like `--include-executable`).

**Comment by adamcfraser** [comment]
Closing based on age, and in practive the size of Sync Gateway binary is typically not a significant contributor to the size of an sgcollect.
