### ISSUE TITLE
Spec a manifest schema for the zip output of `sgcollect_info`

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1758]
The support team would like to have some kind of spec in hand as they begin enhancing nutshell to parse `sgcollect_info`'s `.zip` file output. To give them a contract to code against, and to give the product team flexibility in organizing the layout within the zip, we've agreed to add a manifest file in the zip.

This manifest should list:
- [ ] Information specific to the execution of the tool (timestamp, etc,)
- [ ] Identification of the manifest file as representing an `sync_gateway` or a `sg_accel` layout.
- [ ] List of files by semantic grouping; for example, an entry identifying log files sharing a common format in such as way that an external tool could select the correct tool/algorithm necessary to parse and analyze those files (e.g. `go tool pprof`, JSON-parser with XPath-like ability, a W3C log parser, etc.).

**Comment by JFlath** [comment]
Hey guys, so while having a manifest in each `sgcollect_info` might perhaps let us do some clever things with the parsing logic some time in the future, the current system with `cbcollect_info` works just as well, i.e. it's no more difficult to check for a file's existence than it is to check the manifest for its existence.

What's absolutely key is that there's a **spec/one-pager/design doc** for what we can expect to be in your run of the mill `sgcollect.zip`. After all, it'd be great to be able to check at runtime and have parsing tools go "Oh, this one includes `super_awesome_info.log` in the manifest, never heard of that before but ok!", but we still can't do anything with that file until we go away and write the code to parse out what we need from that file.

Sorry if there's been a bit of crossed wires about this. Not to sound too harsh, but a spec is something we'd absolutely need to be able to develop from, a manifest is something we might be able to use, but not at the present time. We would have to refactor pretty much all of how we parse making it super difficult to port code across. There's also the point that relying on a manifest diverges quite a bit from the `cbcollect_info` way of doing things, and the more we do that, the harder life becomes. Perhaps it would work well in the future, especially if there's some convergence between cb and sg?

**Comment by JFlath** [comment]
Hey guys, any update on this or plans for when we might get a spec? I'd be great to be able to start getting tooling around it worked out.

**Comment by adamcfraser** [comment]
Closing - integration with SG has already been completed.
