### ISSUE TITLE
Add a manifest to the zip file output from `sgcollect_info`.

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1759]
The support team would like to have some kind of spec in hand as they begin enhancing nutshell to parse `sgcollect_info`'s `.zip` file output. To give them a contract to code against, and to give the product team flexibility in organizing the layout within the zip, we've agreed to add a manifest file in the zip.

This manifest should list:
- [ ] Information specific to the execution of the tool (timestamp, etc,)
- [ ] Identification of the manifest file as representing an `sync_gateway` or a `sg_accel` layout.
- [ ] List of files by semantic grouping; for example, an entry identifying log files sharing a common format in such as way that an external tool could select the correct tool/algorithm necessary to parse and analyze those files (e.g. `go tool pprof`, JSON-parser with XPath-like ability, a W3C log parser, etc.).

Spec is defined by: https://github.com/couchbase/sync_gateway/issues/1758

**Comment by adamcfraser** [comment]
Closing - nutshell integration with SG has already been completed.
