### ISSUE TITLE
Filtering channels in _changes request 

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#1765]
I am using syncgateway 1.2 and when i used _changes/since=54400&filter=sync_gateway/bychannel&channles=channel1 . i am not receiving any document filter based on channel field. i am getting all the documents which are > last seq(54400)

can any one tell me usage of filtering channel is correct? or any changes in request i need to make?

**Comment by ajres** [comment]
@ArihantRk 

The right place to ask questions is on the [couchbase forums](https://forums.couchbase.com), more people will see your question and you are more likely to get a quick answer.

If your request above is correct then you have a typo:

```
&channles=channel1
```

should be

```
&channels=channel1
```

If you continue to have issues please post to the forum.
