### ISSUE TITLE
sg_replicate add backlog rev count to _active_tasks

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1766]
To allow admins to monitor the overall progress of a replication, we should add a property to the _active_tasks response to indicate the number of revisions that are currently in the queue waiting to the be replicated.

For a one-shot replication this vale would be expected to start high and drop to zero at the end of the replication.

For a continuous replication this value would be expected to vary with write load and replication throughput.

**Comment by adamcfraser** [comment]
I had thought that sg-replicate uses limit (with a default value of 50) when making changes requests (and if it doesn't, it probably should to avoid timeouts on a very large changes response).  With that approach, I don't think there's a really a concept of a queue that's being processed - sg-replicate doesn't really have visibility to the total number of pending changes from the source system.

It's basically the same problem CBL clients have around displaying a replication progress bar - we don't want to take on the performance overhead for Sync Gateway to return count of pending changes before sending those changes, particularly for very large datasets.

**Comment by adamcfraser** [comment]
Closing, as it's not feasible based on how replication works.
