### ISSUE TITLE
Internal OIDC OP testing endpoints

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1772]
Add internal OP endpoints that can be used to test the OIDC flow end-to-end against a standalone SG instance (no external OP). 
- [x] Add the OP endpoints needed for the implicit and auth code flows, per the OIDC spec (/authorize, /token)
- [x] Add a flag to the `unsupported` config to enable the test OP endpoints
- [x] Use in-memory storage for generated auth codes, tokens (i.e. test flow doesn't need to support multi-node SG clusters)
- [x] To simplify testing, we should implement discovery endpoint

**Comment by adamcfraser** [comment]
Sample config endpoint (google OAuth sandbox):
https://accounts.google.com/.well-known/openid-configuration

**Comment by ajres** [comment]
The testing OP endpoint has been pushed to branch `feature/issue_1668`

**Comment by adamcfraser** [comment]
Merged to feature/issue_1688.
