### ISSUE TITLE
Add scenarios for Drop TAP feed tests (and equivalent dropped DCP feed tests)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1786]

**Comment by adamcfraser** [comment]
Should probably be implemented along with other multi-node CBS cluster testing.  Should be possible to replicate by spinning up a multi-node CBS cluster and bringing down the node that SG is originally connecting to.

**Comment by adamcfraser** [comment]
Move to testkit, provide scenario details.

**Comment by djpongh** [comment]
Filed: https://github.com/couchbaselabs/mobile-testkit/issues/1487
