### ISSUE TITLE
Does not build on Windows

### ISSUE THREAD

**Issue by michaelkwok** [couchbase/sync_gateway#1792]
Here are couple blocking issues.
1. sg-service.go is importing github.com/kardianos/service but kardianos does not exit.  I don't see it in the manifest either.
2. routing.go has too many errors, mainly undefined methods.

godeps\src\github.com\couchbase\sync_gateway\rest\config.go:637: undefined: LongVersionString
godeps\src\github.com\couchbase\sync_gateway\rest\handler.go:146: undefined: VersionString
godeps\src\github.com\couchbase\sync_gateway\rest\routing.go:42: (_handler).handleRoot undefined (type *handler has no method handleRoot)
godeps\src\github.com\couchbase\sync_gateway\rest\routing.go:45: (_handler).handleGetDB undefined (type _handler has no method handleGetDB)
godeps\src\github.com\couchbase\sync_gateway\rest\routing.go:59: (_handler).handleEFC undefined (type _handler has no method handleEFC)
godeps\src\github.com\couchbase\sync_gateway\rest\routing.go:104: (_handler).handleCreateTarget undefined (type _handler has no method handleCreateTarget)
godeps\src\github.com\couchbase\sync_gateway\rest\routing.go:176: (_handler).handleProfiling undefined (type _handler has no method handleProfiling)
godeps\src\github.com\couchbase\sync_gateway\rest\routing.go:178: (_handler).handleProfiling undefined (type _handler has no method handleProfiling)
godeps\src\github.com\couchbase\sync_gateway\rest\routing.go:180: (_handler).handleHeapProfiling undefined (type _handler has no method handleHeapProfiling)
godeps\src\github.com\couchbase\sync_gateway\rest\routing.go:182: (_handler).handleStats undefined (type *handler has no method handleStats)
godeps\src\github.com\couchbase\sync_gateway\rest\routing.go:182: too many errors

@tleyden Can you help take a look?  Thanks!

**Comment by tleyden** [comment]
@ajres can you take a look?

**Comment by michaelkwok** [comment]
@ajres The other build issue turned out to be mine.  But we sg-windows service wrapper is not entirely fixed.  It's looking for Kardianos at the wrong place. 

17:00:27 ======== build service wrappers ==============
17:00:27 sg-service.go:9:2: cannot find package "github.com/kardianos/service" in any of:
17:00:27    c:\usr\local\go\1.5.3\go\src\github.com\kardianos\service (from $GOROOT)
17:00:27    c:\jenkins\workspace\sgw-windows-build\1.3.0\enterprise\godeps\src\github.com\couchbase\sync_gateway\service\sg-windows\src\github.com\kardianos\service (from $GOPATH)
17:00:27 sg-accel-service.go:9:2: cannot find package "github.com/kardianos/service" in any of:
17:00:27    c:\usr\local\go\1.5.3\go\src\github.com\kardianos\service (from $GOROOT)

I think the correct path set in the manifest is c:\jenkins\workspace\sgw-windows-build\1.3.0\enterprise\godeps\src\github.com\kardianos.

Can you fix that?  Thanks!

**Comment by ajres** [comment]
Fixed with merged PR #1808
