### ISSUE TITLE
An ability to see a list of users that has access to a given list of channels

### ISSUE THREAD

**Issue by pasin** [couchbase/sync_gateway#1800]
This is a feature request for an admin UI to be able to show a list of users that have accessed to a given list of channels. We may need to be able to paginate the result as well.

**Comment by rajagp** [comment]
From forums : https://forums.couchbase.com/t/get-all-users-who-have-access-to-a-channel-within-the-sync-function/16915

**Comment by adamcfraser** [comment]
Closing - can revisit based on more recent UI plans.
