### ISSUE TITLE
Build oidc callback_url based on request, instead of in config

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1812]
Should be built based on the incoming request (to account for proxies/load balancers, etc).

**Comment by adamcfraser** [comment]
Option to leave the callback URL as a way for customers to override.

**Comment by ajres** [comment]
Updated getOIDCProvider in oidc_api.go to lazy generate provider.CallbackURL if it is not defined by the provider config.

**Comment by ajres** [comment]
pushed to PR 1688
