### ISSUE TITLE
Update windows installer to include sgcollect_info

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1845]
For SG 1.3 sgcollect_info will be installed into a tool folder at the same level as bin

The Windows installer needs to be updated for this change also.

**Comment by ajres** [comment]
This needs to be done for InstallShield, need to build a new VM

**Comment by ajres** [comment]
Closed as redundant, IS project structure picks up tools folder by default.

**Comment by mattcarabine** [comment]
Accidentally re-opened and commented on the PR by mistake.

Just installed the exe produced as part of http://mobile.jenkins.couchbase.com/job/sgw-windows-build/137/ but it didn't seem to include sgcollect_info at all.

Am I doing something wrong here?

Directory structure is as follows:

```
C:\Program Files (x86)\Couchbase>dir
 Volume in drive C has no label.
 Volume Serial Number is 50B5-20F6

 Directory of C:\Program Files (x86)\Couchbase

03/07/2016  19:34    <DIR>          .
03/07/2016  19:34    <DIR>          ..
03/07/2016  19:34    <DIR>          examples
01/07/2016  12:55             2,556 LICENSE.txt
01/07/2016  12:55             1,382 README.txt
01/07/2016  11:29               230 serviceconfig.json
01/07/2016  12:55         3,475,968 sg-windows.exe
01/07/2016  12:51        22,704,128 sync_gateway.exe
01/07/2016  12:55                35 VERSION.txt
               6 File(s)     26,184,299 bytes
               3 Dir(s)     800,608,256 bytes free
```
