### ISSUE TITLE
Test provider should only provide refresh token when requested

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1848]
Currently in the test, it always returns a refresh token, even though I'm not explicitly requesting it with the offline=true param.

Functional test code:

https://github.com/couchbaselabs/mobile-testkit/blob/feature/oidc_tests/testsuites/syncgateway/functional/test_openid_connect.py#L7-L73

**Comment by ajres** [comment]
The link above is broken, I tried to find the right version of the test in GitHub but cannot.

Which request are you passing "offline=true" is it the token request or the previous authorize/authenticate requests.

Looking in the [OIDC spec](http://openid.net/specs/openid-connect-core-1_0.html#OfflineAccessPrivacy), I can't find any reference to an "offline"=true query parameter, but I can find references to a 'scope' value of 'offline' in section "11. Offline Access"

Is there a spec I can reference for the implementation.

**Comment by adamcfraser** [comment]
Reviewed w/ @ajres.  Not required for 1.3 - the OpenID Connect spec doesn't require that providers return refresh token only when access_type and prompt values are set.  Several providers (e.g. Yahoo, Azure) return refresh token for any successful auth code flow authentication.

May revisit in future, but not must-have for 1.3.

**Comment by ajres** [comment]
This is an incomplete list of third party providers, it would be useful to understand how they behave with respect to offline requests.

[Google:](https://developers.google.com/identity/protocols/OpenIDConnect)

[Yahoo:](https://developer.yahoo.com/oauth2/guide/openid_connect/)

[Microsoft Azure Active Directory:](https://msdn.microsoft.com/en-us/library/azure/dn645541.aspx)

[Salesforce:](https://developer.salesforce.com/page/Inside_OpenID_Connect_on_Force.com)

[Paypal:](https://developer.paypal.com/docs/integration/direct/identity/log-in-with-paypal/)

There are also a number of OpenID Connect brokers that connect to a variety of backends (LDAP e.t.c).

[Auth0 (commercial):](https://auth0.com)

[Dex (open source, free AFAIK):](https://coreos.com/blog/announcing-dex/)

**Comment by adamcfraser** [comment]
The existing behaviour is fine for now - doesn't violate the OIDC spec and matches some real-world providers.
