### ISSUE TITLE
_oidc_challenge should return the host address rather than configured address

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1849]
Currently if I go to `http://192.168.0.112:4984/db/_oidc_challenge`, I get back this header:

```
< Www-Authenticate: OIDC login="http://localhost:4984/db/_oidc_testing/authorize?client_id=sync_gateway&redirect_uri=http%3A%2F%2Flocalhost%3A4984%2Fdb%2F_oidc_callback&response_type=code&scope=openid+email&state
```

Expected: instead of `localhost:4984`, it should return `192.168.0.112:4984`

**Comment by adamcfraser** [comment]
If the callbackURL is defined in your config, it will always be used (by design).  If you remove the callbackURL, it will build the URL based on the request.  Can you retest w/out the callbackURL defined?
