### ISSUE TITLE
Add OIDC scope to test provider, functional tests

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1856]
Added the ability to specify the requested scope in the Sync Gateway config.

If scope is provided, that scope is requested from the OP (determines what information is included in the ID token).  

If scope is not defined, SG uses default scope ("openid", "email").

If an invalid scope is defined, Test Provider should return a 'bad scope' error.

Functional tests should cover:
- [x] Using default scope
- [x] Specifying larger scope, and verifying ID token contents
- [x] Specifying smaller scope ('openid' only), and verifying ID token contents
- [x] Specifying invalid scope, verifying OP returns error

**Comment by tleyden** [comment]
See https://github.com/couchbase/sync_gateway/pull/1855 + https://github.com/couchbase/sync_gateway/issues/1854

**Comment by tleyden** [comment]
@adamcfraser can you spec this out a little further and give some concrete examples or pointers to docs?  /cc @jamiltz

**Comment by adamcfraser** [comment]
Description of scope here:
http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims

From a testing perspective - when we request a token from the OP, it includes a scope value.  That scope value determines which claims are included in the payload of the ID token.  Sync Gateway isn't (currently) using those claims, but client application developers may want to inspect those claims for additional information about the user.

What we want to test is that setting the scope property in the Sync Gateway config works, as described in the checklist above.

**Comment by ajres** [comment]
Test OP code changes pushed to [PR](https://github.com/couchbase/sync_gateway/pull/1879)

**Comment by tleyden** [comment]
Are these tests expected to fail until https://github.com/couchbase/sync_gateway/pull/1879 is merged?

**Comment by tleyden** [comment]
> If scope is not defined, SG uses default scope ("openid", "email").

On this description of the scope claims:

http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims

I don't see the "openid" scope listed.  I guess that is a special "baseline" scope?

**Comment by tleyden** [comment]
I specified a larger scope:

```
               "testlargescope":{
                  "issuer":"http://localhost:4984/db/_oidc_testing",
                  "client_id":"sync_gateway",
                  "validation_key":"R75hfd9lasdwertwerutecw8",
                  "callback_url":"http://localhost:4984/db/_oidc_callback",
                  "register":true,
                  "scope":["openid", "email", "address", "phone"]
               }
```

but didn't see any `address` or `phone` fields on the decoded token:

```
decoded_id_token: {u'sub': u'testuser', u'iss': u'http://localhost:4984/db/_oidc_testing', u'exp': 1466056358, u'iat': 1466052758, u'email': u'testuser@syncgatewayoidctesting.com', u'aud': u'sync_gateway'}
```

is this expected behavior?

This is testing against the branch for https://github.com/couchbase/sync_gateway/pull/1879

**Comment by adamcfraser** [comment]
I think you should expect an 'invalid scope requested' error, since the supported scopes on the internal test provider are only supposed to be openid/email/profile (from https://github.com/couchbase/sync_gateway/pull/1879/files#diff-4e102bd90987c5b513fedac905965f74R120)

Usually the scope values get routed from Sync Gateway to the OP as a query string parameter on the redirect returned by the _oidc call.  Since you're not using that redirect directly (and going straight to the POST), are you extracting those from the query string and using them somehow?

**Comment by tleyden** [comment]
> Usually the scope values get routed from Sync Gateway to the OP as a query string parameter on the redirect returned by the _oidc call. Since you're not using that redirect directly (and going straight to the POST)

I changed it early on so that the tests use the `_oidc` call response:

Here is the ngrep output from the above run:

https://gist.github.com/tleyden/c9de7710a192d4a5f2cfcd98a75f3334

**Comment by adamcfraser** [comment]
Looks like the scope is there on the request.  Would need input from @ajres on whether the test OP is doing scope enforcement.

**Comment by tleyden** [comment]
If I use config scope of `"scope":["openid", "email", "phone"]`  (removed `address`), should expect a `phone` field in the returned JWT?

If not, how would I verify that the `phone` scope was set?

**Comment by adamcfraser** [comment]
If you request the 'phone' scope, you should expect the 'phone_number' and 'phone_number_verified' claims in the token (taken from http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims).

However, it's not required for every OP to support every scope.  The set of supported scopes is published on the OPs configuration endpoint.  In our case, it looks like the internal test OP doesn't support the phone scope.  In that scenario, I'd expect it to return an error when you request the phone scope.

**Comment by ajres** [comment]
From section 3.1.2.1 "Authorization Request"

scope
REQUIRED. OpenID Connect requests MUST contain the openid scope value. If the openid scope value is not present, the behavior is entirely unspecified. Other scope values MAY be present. Scope values used that are not understood by an implementation SHOULD be ignored. See Sections 5.4 and 11 for additional scope values defined by this specification.

I implemented the "SHOULD be ignored" for scope values that are not understood by the test OP.

**Comment by ajres** [comment]
Currently the OP only enforces the "openid" scope, it will include claims for "email" and "profile" scopes if they are requested .

Note: for "profile" only "nickname" claim is returned, it wasn't clear (to me) whether all claims associated with "profile" MUST be returned or only those that have valid data (in the test OP just "nickname"

**Comment by ajres** [comment]
Merged to master
