### ISSUE TITLE
changes feed with doc_ids filter omits `deleted` properties

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#1857]
If I use the `doc_ids` filter with the `_changes` feed, to get only specific docIDs, the change objects in the response are missing the `deleted` property denoting a deleted revision.

Here's an example from one of the CBL/iOS test databases, where I first run the changes feed the normal way, but limiting it only to the revision of interest:
`GET :4984/attach_test/_changes?since=3&limit=1`

``` json
{
    "last_seq": "4", 
    "results": [
        {
            "changes": [
                {
                    "rev": "2-61de0ad4b61a3106195e9b21bcb69d0c"
                }
            ], 
            "deleted": true, 
            "id": "propertytest", 
            "seq": 4
        }
    ]
}
```

Now using the `doc_ids` filter:

`GET :4984/attach_test/_changes?filter=_doc_ids&doc_ids=["propertytest"]`

``` json
{
    "last_seq": 4, 
    "results": [
        {
            "changes": [
                {
                    "rev": "2-61de0ad4b61a3106195e9b21bcb69d0c"
                }
            ], 
            "id": "propertytest", 
            "seq": 4
        }
    ]
}
```

Note that `"deleted":true` is missing.

**Comment by ajres** [comment]
I can reproduce this where no document revision has been assigned to a named channel and the user has admin_channels set to ["*"]

Thus far if a revision for the document has been assigned to named channel then the "deleted":true gets returned.

**Comment by ajres** [comment]
Talking with @adamcfraser there are two corner cases that need to be tested and we should add unit tests for.

Delete a document by adding the "deleted" property, without removing "channels" property. Validate that "deleted":true is returned for that doc id.

Delete a document at a revision higher that '1', where sync function is using oldDoc to map the document to channels.

**Comment by snej** [comment]
Yup, the case where I see this is an "admin party" test database with guest access to "*".
