### ISSUE TITLE
Improvement - Timestamp in SG local doc check point.

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#1860]
The local docs for check points that CBL sets really have no method of tracking its status.

It be great to have a time stamp in the JSON payload with datetime of last update. So that when people buy new phones we can find old/dead replications checkpoints and delete them.

**Comment by adamcfraser** [comment]
The local doc content is completely transparent to Sync Gateway, and I think we probably want to avoid introducing SG interference with the contents.  Although checkpoint docs are the most common use of the _local endpoint, it's possible to use it for storing other non-replicated documents.

Another approach might be to have an optional TTL value for _local docs, and so have them expire if they aren't used before the expiry window ends.  Would that cover your use case?

**Comment by tleyden** [comment]
@househippo what's the problem you're running into?

**Comment by househippo** [comment]
@adamcfraser ,

> Another approach might be to have an optional TTL value for _local docs, and so have them expire if they aren't used before the expiry window ends. Would that cover your use case?

That would kill two birds w/ one stone. Auto Cleanup of old check points & can N1QL  META().exp info for dates. Also keep alive good check points with the GETandTouch() and extend the time.

**Comment by JFlath** [comment]
Discussed this the other day. I agree with the statement of:

> The local doc content is completely transparent to Sync Gateway, and I think we probably want to avoid introducing SG interference with the contents.

We don't want to make this a breaking change. I can think of two ways of doing that:

* Separate what is stored in CB from what is returned by SG - we already do this with the `_sync` field in normal docs.
* Store the metadata in xattrs in 2.0. Basically the modern version of option 1, but nice and transparent.

As for the metadata itself, it would definitely be handy to have SG add metadata that will always be available whether it's a checkpoint or something end-user, e.g. timestamp, user who `PUT` the doc (or `admin`)... More broadly though, it'd be awesome if CBLite could be aware of this and save metadata in its checkpoints saying who it is and what it synced - basically what built the hash that forms the name of the replication so we can trace it back...

**Comment by adamcfraser** [comment]
@JFlath I still don't think I understand the exact problem you're trying to solve.  Is it related to cleanup of obsolete checkpoints?  Identifying when a user last replicated?  Something else?

**Comment by JFlath** [comment]
Identifying when a user last replicated would be a key use case. I can only identify which checkpoints to look at from the log messages (especially if we're talking about an end user of a customer's app where we can't get the CBL logs/DB). Say a user (as in SG username) has a number of devices - how do I know which is which?

**Comment by Fujio-Turner** [comment]
@JFlath ,

> Identifying when a user last replicated would be a key use case. 

People can do that by mining the SG logs and people don't mind doing it. I suggested to @snej about having CBL to add a timestamp inside the checkpoint , but he brought up a good point that people many time will move the system clock back or forward to keep a BETA version of an APP alive and thus the timestamp in the checkpoints would not be accurate. https://github.com/couchbase/couchbase-lite-core/issues/99

**Comment by JFlath** [comment]
>People can do that by mining the SG logs and people don't mind doing it.

Yup, but logs wrap ;). With metadata (xattrs?) attached to checkpoints, we can do a lot more - e.g. find all checkpoints for a specific user, we could only do that with logs *if* every checkpoint is in the recent logs we have. Can't really use N1QL etc based off logs.

**Comment by JFlath** [comment]
I'm not sure the changing clocks argument applies too much if we're applying the timestamp in SG rather than client side. If people are changing their SG clocks then all bets are off anyway.

**Comment by adamcfraser** [comment]
Support for expiry on checkpoints is in place - closing.
