### ISSUE TITLE
sgcollect - remove sensitive data (like bucket password)

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#1872]
Many times people are very sensitive about passwords and access. sgcollects collects lots info. It be best if we could redact info from sgcollect like passwords to Couchbase Server.

**Comment by adamcfraser** [comment]
@tleyden I think this should be a priority for 1.3.  Can you review and provide input on the work required?

**Comment by tleyden** [comment]
I agree that we should do this from a security standpoint.

As far as the work required, normally this would be trivial:
- Parse in config JSON (from either the _config endpoint, or the filesystem, or both)
- Strip out password fields
- Write the destination config JSON to the zip file

However this is complicated by the fact that we have to first strip out the sync function field before parsing the JSON, and then re-add it before serializing the JSON.

Some work has been done here by @mattcarabine: https://github.com/couchbase/sync_gateway/blob/27cc2f44c590faf278cfd2fea327c4b95bacc21c/tools/sgcollect_info#L135-L148 but more work would need to be done to make the above work.

Or a simpler approach might be to just strip out the password fields via a regex before writing the configs to the zip file, which would avoid the need for the JSON parsing and first stripping out the the sync function.

Regardless of approach, it should have an accompanying unit test that:
- Takes the content of a config file as input  (string or byte array form)
- Returns the content of the config file as output, with password fields removed or masked

**Comment by adamcfraser** [comment]
If it's preferable/easier to add a like a 'no_passwords' option to the SG _config REST endpoint, we could also do that.

**Comment by tleyden** [comment]
@adamcfraser I'd say we should just do that by default on the `_config` REST endpoint, however for `sg_collectinfo` it's not enough, because it collects "static" configs from the filesystem as well.

**Comment by mattcarabine** [comment]
I agree with @tleyden that for this problem the use of regexes to remove passwords should probably be sufficient.

**Comment by mattcarabine** [comment]
Although the other suggestions about the `_config` endpoint do also seem sensible to implement regardless.

**Comment by tleyden** [comment]
@mattcarabine any chance you can take a look at this?  Feel free to sync up with me if you want to discuss

**Comment by mattcarabine** [comment]
Sure, will do it this weekend.

**Comment by mattcarabine** [comment]
@househippo / @tleyden Do you have any representative configs with CB Server passwords/usernames in them to test with?

**Comment by househippo** [comment]
@mattcarabine ,

Here is a sample below.

You would want to remove username & password with *******\* 

```
{
  "log": ["HTTP","HTTP+"],
  "databases": {
    "db": {
      "server": "http://localhost:8091",
      "bucket": "cake",
      "username":"cake",
      "password":"cake",
      "users": { "GUEST": { "disabled": true, "admin_channels": ["*"] } }
    }
  }
}

```

**Comment by mattcarabine** [comment]
Thanks @househippo will test with this

**Comment by mattcarabine** [comment]
I have a working implementation which sanitises the config we grab off of disk, but sanitising the one from `/_config` will be a little more involved. @tleyden Is the plan to make `/_config` not include passwords by default for 1.3?

**Comment by tleyden** [comment]
@mattcarabine can we drop the retrieval of the running / live config until we can make it secure?

**Comment by mattcarabine** [comment]
I can just add the sanitisation to the live config too, I'd say it's a pretty important feature!

**Comment by adamcfraser** [comment]
@mattcarabine Adding the sanitization to the live config sounds like the right way to go - would you be able to get that done in time for 1.3?

**Comment by mattcarabine** [comment]
Yes, will have it done ASAP.

**Comment by mattcarabine** [comment]
Doing this for Linux is trivial however I'm struggling to find a good way to get the sanitisation to work well on Windows... as an aside I have also raised #1931 to track some existing issues that I have discovered for Windows.

**Comment by tleyden** [comment]
From #1971

There are two styles for providing username and password for protected CBS buckets

External to server URI

```
{
    "log": ["*"],
        "databases": {
        "db": {
            "server": "http://localhost:8091",
                        "bucket":"bucket-1",
                        "username":"bucket-1",
                        "password":"foobar",
        }
    }
}
```

Embedded in server URI

```
{
    "log": ["*"],
        "databases": {
        "db": {
            "server": "http://bucket-1:foobar@localhost:8091",
                        "bucket":"bucket-1"
        }
    }
}
```

Same applies to shadow password protected shadow buckets

**Comment by tleyden** [comment]
With [this config](https://gist.github.com/tleyden/441e94d06bc5aa23088af0b517c26df8) it is collecting [these output files](https://gist.github.com/tleyden/6fc1980155b8c158fa28c43fd3c0665f)

Not checked into master branch yet.
