### ISSUE TITLE
Make HTTP/2 support opt-in

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1888]
Based on issues found when running the current iOS unit tests w/ HTTP/2 (https://github.com/couchbase/couchbase-lite-ios/issues/1307), we should make HTTP/2 support opt-in on the Sync Gateway side for release 1.3.  

I think it makes sense to do this by moving it to an 'unsupported' config option, since we haven't successfully tested/validated.  Once we've done more internal validation of HTTP/2, we can enable it by default (possibly with an opt-out option).

**Comment by adamcfraser** [comment]
Original PR for HTTP/2:
https://github.com/couchbase/sync_gateway/issues/1626

**Comment by pasin** [comment]
Reference to the original iOS ticket that @snej created.
https://github.com/couchbase/couchbase-lite-ios/issues/1170
