### ISSUE TITLE
Disable Password Logon / HTTP Basic

### ISSUE THREAD

**Issue by wtatum** [couchbase/sync_gateway#1892]
When using /_session/ API, Persona, Facebook, or the forthcoming JWT in order to authenticate it would be desirable to completely disable password-based access at the gateway. My understanding is that standard practice is to set a large, random password (to make sure they user isn't created with an empty password) and then ignore password login and user the other methods listed.

This feels a little clumsy to me, and opens up some concerns about whether we can effectively generate a random password which is not in any way predictable to an attacker. I would feel more "at ease" just disabling password-based access since it's not part of my use case.

Some additional discussion has taken place [on gitter](https://gitter.im/couchbase/sync_gateway?at=5761b6e252352c84028283eb) and in [the forums](https://forums.couchbase.com/t/authentication-with-json-web-token/3472/8).

**Comment by adamcfraser** [comment]
This seems like a reasonable security enhancement, and shouldn't be a considerable amount of work to implement.  Adding to the 1.4 backlog.

**Comment by househippo** [comment]
@adamcfraser , I've been asked for this before. Could you make it so that user can only access via _session only.

Most people are ok with setting
1. empty_password_allowed: false
2. make a random password that nobody knows per user

**Comment by wtatum** [comment]
For what it's worth, I think that's a perfectly serviceable workaround but it feels like just that: a workaround. If generating a random password is the way we end up going the onus is pushed back onto my team to do enough code review to make sure we don't wind up with 
`public byte[] genRandomPassword() { return "1234".getBytes(); }`
or some nonsense like that. If password access is disabled there's no need to make sure we aren't leaking the password or failing to generate a high-quality one. The net value in terms of application security is the same, but we have the peace-of-mind of not needing to guarantee we're not doing something wrong.

**Comment by adamcfraser** [comment]
@wtatum I also like your suggestion to extend the strong random password autocreation done by Sync Gateway for Facebook/Persona/JWT auth to make it accessible when creating users via the Admin API.

**Comment by wtatum** [comment]
@adamcfraser I would be perfectly happy with that as well. That was discussed [here](https://forums.couchbase.com/t/authentication-with-json-web-token/3472/12?u=william.r.tatum). I can see how that might be preferred since it doesn't require re engineering of the login system to support null passwords, or modification of the web server to reject basic, but it also still solves my problem of needing to expend additional effort to "reinvent the wheel" regarding generation of a sufficiently random password.

All told, I don't think the security risk or effort for externally generating and setting a random password is all that high, but if every application has to do it, eventually someone will screw it up and end up setting weak or predictable passwords.

**Comment by Lily418** [comment]
Would this also involve removing the Www-Authenticate response header which gets sent when 401s occur?  At the moment I have an issue where that header triggers Chrome to open a dialog to ask for credentials for basic auth, but I'm using Cookie authentication.

**Comment by adamcfraser** [comment]
Should be included as part of a review of the auth config structure as part of 2.0.

**Comment by adamcfraser** [comment]
Closing based on age - should be reopened as JIRA issue based on current use cases/requirements.

**Comment by mnpetersen** [comment]
Hey all - what is the current state of play with this?  Is it still recommended to add a strong random password for each user?
