### ISSUE TITLE
Document does not expire after rolling ttl updates

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1899]
SG Version: `1.3.0-212`
1. Start sync_gateway with backing CBS server
2. PUT /db/doc_1 with "_exp": 3
3. Update /db/doc_1 10 times with "_exp": 3

Expected: after 10 updates, the doc would expire after 3 secs
Actual: after 10 updates, the doc does not expire

**Comment by sethrosetter** [comment]
@adamcfraser has been able to repro it. Please add any caveats I may have missed.

**Comment by adamcfraser** [comment]
Underlying issue is in gomemcached.  Working with owners to get the fix in.

**Comment by adamcfraser** [comment]
https://issues.couchbase.com/browse/MB-20011
