### ISSUE TITLE
Enhance OIDC traceability / minor code change suggestions

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1901]
In [GetProviderForIssuer](https://github.com/couchbase/sync_gateway/blob/b1764b3429ccee99b8f469ab14e1a6ebcc9a7f0f/auth/oidc.go#L62-L69), should the param be named `clientID` instead of `audience`?  Feels a bit confusing to use these terms interchangeably.

In [authenticateJWT](https://github.com/couchbase/sync_gateway/blob/b1764b3429ccee99b8f469ab14e1a6ebcc9a7f0f/auth/auth.go#L344-L352) if the `user.SetEmail()` call has an error, we aren't logging the error anywhere, which can make debugging harder since things fail silently without any hint in the logs.

**Comment by adamcfraser** [comment]
I think `audience` is appropriate here - it's the name of the claim from the ID token that we're trying to verify against the client id.  From the OpenID Connect spec:

`
The Client MUST validate that the aud (audience) Claim contains its client_id value registered at the Issuer identified by the iss (issuer) Claim as an audience.
`

However this does uncover a separate scenario that we're not currently handling - the case where the audience on the ID token is an array of strings.  I've filed https://github.com/couchbase/sync_gateway/issues/1902 for that.

**Comment by adamcfraser** [comment]
On the SetEmail() - that looks like a cut-and-paste from makeSessionFromNameAndEmail, which could also be update to log a warning about the bad email format.

**Comment by tleyden** [comment]
Using `*string` pointers here as opposed to just using strings makes debugging a bit harder:

```
type OIDCProvider struct {
...
    ClientID           *string  `json:"client_id,omitempty"`       // Client ID
    ValidationKey      *string  `json:"validation_key,omitempty"`  // Client secret
    CallbackURL        *string  `json:"callback_url,omitempty"` 
```

because when dumped via a `%+v`, it yields:

```
OIDC+: Provider for issuer: &{JWTOptions:{ValidationKey:<nil> SigningMethod:<nil>} Issuer:http://localhost:4984/db/_oidc_testing Register:true ClientID:0xc820149090 ValidationKey:0xc8201490b0 CallbackURL:0xc8201490c0 DisableSession:false Scope:[] IncludeAccessToken:false UserPrefix:e85633099ae1a8bd06cd43bcea2838d9 OIDCClient:0xc8201ef450 OIDCClientOnce:{m:{state:0 sema:0} done:1} IsDefault:true Name:test}
```

(note the `ClientID:0xc820149090` which shows a pointer address vs the string)

Just wondering what the reasoning behind using `*string` vs `string` here was.

**Comment by adamcfraser** [comment]
@tleyden I'm in the habit of using *string for json entries, to be able to differentiate between absence in the config and empty string in the config.  

In this case it might not be necessary - there shouldn't be a case where empty string is a valid value for any of these (actually, _maybe_ ValidationKey).
