### ISSUE TITLE
Trailing slash on database breaks replication

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1907]
If I configured replication in the sync gateway config json with:

```
      {
         "replication_id":"push-to-us-east",
         "source":"http://localhost:4985/db/",
         "target":"http://otherhost.com:4985/db/",
         "continuous":true
      },
```

things broke because it was trying to go to URLs like `http://otherhost.com:4985/db//_changes`.  The error was difficult to track down.

It should either handle this gracefully or give a clear error in the logs.

**Comment by adamcfraser** [comment]
Nice-to-have for 1.3 if we need to generate a new RC for other issues, doesn't merit a new build on it's own.

**Comment by ajres** [comment]
Also need to see if this issue manifests for the REST API
