### ISSUE TITLE
Improved config-file parser (support comments, etc.)

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#191]
The [jsonpreprocess](http://github.com/hnakamur/jsonpreprocess) package implements a more lenient JSON parser with nice-for-humans features like comments and unquoted keys. It looks like it would be very easy to extend it to support our backquote-style comments, in which car we could use it on config files. I think it'd be very useful if config files could have comments.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
