### ISSUE TITLE
1.3 Performance Sanity Testing

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1910]
- Run a few sanity perf tests against 1.2.1 and 1.3 (latest binaries 1.3.0-234) in channel cache mode and look for regressions
- 2 SG 2 GLs + 3 node CBS
- 1K writers, 1k readers on each gateload (possibly do 5k / 5k load)
- Run for 30 mins
- Collect p95 and p99
- Collect mem and cpu

**Comment by tleyden** [comment]
Running into https://github.com/couchbaselabs/mobile-testkit/issues/330:

```
TASK [Initialize primary node] *************************************************
fatal: [cb1]: FAILED! => {"changed": true, "cmd": "/opt/couchbase/bin/couchbase-cli node-init -c 54.210.56.96:8091 --user=Administrator --password=password --cluster-init-username=Administrator --node-init-hostname=54.210.56.96", "delta": "0:00:04.115557", "end": "2016-06-27 21:59:19.811730", "failed": true, "rc": 2, "start": "2016-06-27 21:59:15.696173", "stderr": "", "stdout": "ERROR: unable to set hostname for 54.210.56.96 (400) Bad Request\n[\"Could not listen: eaddrnotavail\"]", "stdout_lines": ["ERROR: unable to set hostname for 54.210.56.96 (400) Bad Request", "[\"Could not listen: eaddrnotavail\"]"], "warnings": []}

```

**Comment by tleyden** [comment]
Running into https://github.com/couchbaselabs/mobile-testkit/issues/559

Temporarily worked around it by commenting `pipeline=true` from my `ansible.cfg` file

**Comment by tleyden** [comment]
With SG 1.3.0-234 and `--number-pullers 1000 --number-pushers 1000` I'm seeing:
- [Gateload -> SG timeouts](https://gist.github.com/tleyden/a6080a3899563a5adb5ea67401b9757c)
- [Sync Gateway slow query warnings](https://gist.github.com/tleyden/63520fa06f03486227d19d53e30d2d8a)

**Comment by tleyden** [comment]
I haven't yet established a "baseline" with SG 1.2, but just wanted to post what I saw in the logs so far.

**Comment by tleyden** [comment]
SG 1.2 results:
- Machines: SG m3.medium CBS: m3.large Gateload: m3.large
- [Gateload expvars](https://gist.github.com/tleyden/baa0c8cefe0a82133f092991b6f5c1c2) - PushToSubscriberP95 17s
- [SG cpu stats](https://gist.github.com/tleyden/73d42eab5ecb74d6ea54771bef4d332a)
- [SG logs](https://gist.github.com/tleyden/fef42fdc90cf25c675d7ee4ea55a3d87)

TODO: Use machines with higher specs as was done in https://github.com/couchbase/sync_gateway/issues/781#issuecomment-97196203

**Comment by tleyden** [comment]
SG 1.2 updated results:
- Machines: SG c3.2xlarge CBS: c3.8xlarge Gateload: c3.8xlarge
- Gateload expvars: PushToSubscriberP95 2.86 seconds

It ran for 40 minutes, here is the latest expvars output: https://gist.github.com/tleyden/3e5104d1188cdb3c48fd87016c9ecabc

**Comment by tleyden** [comment]
SG 1.3 results:
- Machines: SG c3.2xlarge CBS: c3.8xlarge Gateload: c3.8xlarge
- Gateload expvars: PushToSubscriberP95 2.872387241 seconds

Expvar output: https://gist.github.com/tleyden/a6562f772123ee60aee7e6ccfe0bb70f

**Comment by tleyden** [comment]
@sethrosetter we need to pull numbers into visualization tool to check mem / cpu health

**Comment by tleyden** [comment]
@sethrosetter also, at some point we want a separate service/website that pulls results off of Jenkins and renders web page with charts etc

**Comment by tleyden** [comment]
In [jenkins run 95](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/95/parameters/):
- SG 1.2.1-4
- 4.1.1
- 1k/1k

![gateload_expvars](https://cloud.githubusercontent.com/assets/296876/16890320/246ff4f2-4aa2-11e6-9db1-fa38f3e5fbfd.png)
![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/296876/16890321/247039c6-4aa2-11e6-91a9-4690557c2ea1.png)
![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/296876/16890327/34b939b8-4aa2-11e6-8d08-f96ed7fb81ef.png)

**Comment by tleyden** [comment]
In [jenkins run 97](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/97):
- SG 1.3.0-256
- 4.1.1
- 1k/1k

![gateload_expvars](https://cloud.githubusercontent.com/assets/296876/16890735/285f3eac-4aa6-11e6-8303-2cc8791964b6.png)
![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/296876/16890733/285d1d7a-4aa6-11e6-8fd9-0da0020b0c66.png)
![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/296876/16890734/285efdb6-4aa6-11e6-8aa8-940526441e45.png)

**Comment by tleyden** [comment]
Note: above was run on m3.medium instance on AWS.  Will re-run on VM cluster.

**Comment by tleyden** [comment]
[Build 98](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/98/parameters/)
- SG 1.2.1-4
- Couchbase Server 4.1.1
- 1k/1k pushers/pullers

![gateload_expvars](https://cloud.githubusercontent.com/assets/296876/16926354/2b6e810a-4cdd-11e6-8b97-c8f205d5e4fa.png)
![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/296876/16926355/2b6ee7b2-4cdd-11e6-9d79-c5adb5a7c1e8.png)
![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/296876/16926356/2b6f73e4-4cdd-11e6-8a5c-661f538dd2a7.png)

[Build 99](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/99/parameters/)
- SG 1.3.0-256
- Couchbase Server 4.1.1
- 1k/1k pushers/pullers

![gateload_expvars](https://cloud.githubusercontent.com/assets/296876/16926363/30ef5cbc-4cdd-11e6-9c7e-2e310b3ab48a.png)
![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/296876/16926362/30ef0910-4cdd-11e6-90cf-ac9554c75e37.png)
![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/296876/16926361/30ee3544-4cdd-11e6-99c3-c760e3958ca5.png)

This looks about the same, so I'm going to go ahead and close the ticket.
