### ISSUE TITLE
Error installing SG 1.3 Windows community

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1919]
Error when installing SG 1.3 Windows community/enterprise, missing license.txt file.

**Comment by ajres** [comment]
![image](https://cloud.githubusercontent.com/assets/7745210/16458637/b4ef8048-3e17-11e6-93ba-080b833b29cb.png)

**Comment by michaelkwok** [comment]
@ajres  So it does look like this issue is related to issue #1809 .  PR #1916 should fix this as well.
