### ISSUE TITLE
HTTP basic auth for webhooks

### ISSUE THREAD

**Issue by OldSneerJaw** [couchbase/sync_gateway#1925]
I'd like to request improved support for HTTP basic auth for webhook events. While it's already possible to include basic auth credentials directly in the webhook URL (e.g. `http://username:password@example.com/foobar`), the URL and credentials are written to the Sync Gateway log every time a webhook event is issued. This makes it less than ideal because, in general, secrets should not appear in logs.

There are a few options that come to mind to solve this:
- Block out username and password with, e.g. asterisks, when writing the webhook URL to the log (e.g. `http://****:****@example.com/foobar`). The easiest option, but perhaps not the most elegant.
- Provide additional configuration properties for basic auth username and password, then include them in each webhook request's `Authorization` header. Perhaps not quite as easy as the above option, but less kludgy IMO.
- Provide an additional configuration property to define an arbitrary `Authorization` header value to include in webhook requests. For example, one could enter "Basic dXNlcm5hbWU6cGFzc3dvcmQ=" for basic auth credentials or "MyCustomAuthMethod my-api-token" for some custom auth method. Certainly the most flexible option of all.

Of course, perhaps the best solution is to include a combination of some or all of the options above (or others I haven't thought of/mentioned).

**Comment by adamcfraser** [comment]
Sanitizing the logs should probably be done at minimum (or possibly even just removing the URL logging altogether, unless it's adding significant value).  What type of logging is including the URL?

Beyond that, I like the idea of being able to specify an arbitrary Authorization header in the config.

**Comment by OldSneerJaw** [comment]
@adamcfraser: It's logged by `Events+`. I suppose I could dial back to just `Events` to ensure the basic auth credentials don't show up, but then it seems that webhook events are not logged at all.

Here's an example of a webhook logged by `Events+`:

```
2016-06-30T13:46:39.600-07:00 Events+: Event queue worker sending event Document change event for doc id: foobar to: Webhook handler [http://user:pass@localhost:9000/barfoo/events]
```

**Comment by OldSneerJaw** [comment]
I just opened a pull request (#1932) that implements the first option I suggested (obscure basic auth credentials in webhook URLs). See the PR description for my rationale for keeping the (sanitized) webhook URLs in log messages rather than removing them completely.

**Comment by adamcfraser** [comment]
The PR for sanitizing the logs has been merged - thanks again @OldSneerJaw .
