### ISSUE TITLE
Sync Gateway: OutOfMemory crash while inserting documents

### ISSUE THREAD

**Issue by dtouzet** [couchbase/sync_gateway#1934]
We experience sync gateway crashes (outofmemory crashes) while running tests on our configuration :
Single Sync Gateway 1.2.1-4 (VM with dual core - RAM 4 Go)
3 nodes CouchBase cluster

Test details :
Insertion of about 5000 documents (of 300Ko) - each doc being associated with its own channel.
=> Memory consumption increases continuously, until the sync gateway craches (by reporting outofmemory error).

SG database configuration is based on default values.
It appears that when changing the rev_cache_size value to '1' (instead of default value '5000'), SG memory consumption does not exceed 10% of the available RAM.

NB: the same test has been ran onto a 8Go RAM VM with the same result.
I attached a zip containing different heap profile captured while testing on the 4Go RAM VM.

[heapprofiles.zip](https://github.com/couchbase/sync_gateway/files/348087/heapprofiles.zip)

**Comment by adamcfraser** [comment]
I haven't been able to successfully open the raw heap profiles yet.  Can you let me know what OS you're running?

Alternately, if you can run the following in your environment and share the results for the four profiles, that would be sufficient:

```
go tool pprof --text /<path to SG>/sync_gateway heap.1.profile > heap.1.txt
```

Even better would be:

```
go tool pprof --pdf /<path to SG>/sync_gateway heap.1.profile > heap.1.pdf
```

but that may require the installation of an additional library to pick up Graphviz.

**Comment by dtouzet** [comment]
The Sync Gateway is running on CentOS Linux release 7.1.1503.
I'll try to provide the text version of the profile file today.

**Comment by dtouzet** [comment]
Problem resolved.
Here are the 4 heap in text version:
[heap.zip](https://github.com/couchbase/sync_gateway/files/354118/heap.zip)

**Comment by adamcfraser** [comment]
That's very helpful - thanks for generating.  It's somewhat unexpected that the bulk of the memory usage is related to JSON unmarshalling.  I'm going to set up a local test to try to reproduce.  If it's possible to share a sample document that you're using, that might help (in case there's something unusual in the JSON there).  

Thanks.

**Comment by adamcfraser** [comment]
@dtouzet  So far I haven't been able to reproduce the issue - memory utilization by the revision cache is as expected  (i.e. is rev cache size x document size).

The bulk of the memory usage in JSON unmarshalling is actually valid - that's where the original allocation happens for the data that's stored in the revision cache.

Looking closer at your heap output, it seems like it's also in the ballpark - the last entry (heap4) is showing about 1.8 GB total, which is in the same order of magnitude of 5000 x (300kb + sync metadata).

I wouldn't expect either of these to cause OOM on 4GB (or even 8GB) machines.  I'm running some additional tests here to ensure that memory usage remains stable once the revision cache is full, but can you let me know whether the above heap collections were taken during a test that hit the OOM issue?

**Comment by dtouzet** [comment]
The heap collections where taken during a test that ends with a OOM issue.
(all tests run with default value rev_cache end with an OOM crash).
The last heap collection was taken a few seconds before the crash.
Collections 2 and 3 where taken between 5 and 10mn (crash happened after about 10 minutes).

Here is an additional info that may be of interest for you:
Documents are inserted (/updated - no deletion at this stage) my means of the POST /{db}/_bulk_docs operation.
Each call deals with 10 documents.

I will share a sample doc with you asap.

**Comment by adamcfraser** [comment]
@dtouzet Based on the heap profiles, Sync Gateway is only in the neighbourhood of 2GB a few seconds before your crash.  I'm interested to know where the rest of the memory is going.  I'm assuming there isn't anything else running on the machine at the time?  In the scenario where Sync Gateway has freed memory but not released it to the OS, I still wouldn't expect Sync Gateway to hit an OOM scenario.  

If you can share something like `top` output at the end of your scenario, that might help identify what's going on.

**Comment by dtouzet** [comment]
The VM only hosts the SG service.
I'm not able to provide you with a top output from now, but I checked it during my tests and didn't notice anything special.

However, I just found something interesting:
I tried to format a sample JSON document in order to attach it to the issue.
This simple operation crashed the tool I was using (Notepad++, with JSON plugin).
After a quick investigation, it appears that the pb is related to the serialization of boolean fields, whose values are not escaped by quotes:
`..., "booleanProperty": false,`
Changing it to:
`..., "booleanProperty": "false",`
Makes the formatting works properly.

You earlier mentionned an unexpected memory usage for JSON unmarshalling.
Is there a possible relation between both problems?

**Comment by adamcfraser** [comment]
@dtouzet It seems unlikely for that particular case - that should be the standard JSON formatting for boolean.  Given that the problem goes away when you reduce the size of the revision cache (correct?), I still think it's just down to the size of the docs and the size of the revision cache.

**Comment by dtouzet** [comment]
Here are a few additional info related to the inserted docs.
The test tries to insert/update 5612 docs.
Meduim size of these docs is not 300ko (as previously mentionned), but rather 180ko.
The size of largest doc is around 900ko.
We have117 docs with size > 400ko.
Smallest docs size is about 10-20ko.

Each doc is associated with its own channel, whose value corresponds to:
`'R_' + {doc_id}`
Thus, a doc identified by:
`"_id": "SITE1_FR56172329"`
has the following channels property:
`"channels": ["R_SITE1_FR56172329"]`

I attach a zip containing 3 documents (small, medium and big).
[they have been extracted from the SG, so they already have a revision property]
You should be able to reproduce my test by inserting these docs (using POST /{db}/_bulk_docs - with 10 docs batchs).
As previously stated, the only relevant properties to be overriden are `_id` and `channels`.

[json.zip](https://github.com/couchbase/sync_gateway/files/360945/json.zip)

**Comment by adamcfraser** [comment]
Need to write Gatling perf scenario to reproduce and evaluate this scenario.

**Comment by adamcfraser** [comment]
@tleyden Write throughput scenario should be capable of reproducing this use case.

**Comment by tleyden** [comment]
@adamcfraser I updated the action item list on https://github.com/couchbaselabs/mobile-testkit/issues/607

**Comment by adamcfraser** [comment]
Multiple enhancements have been made around write throughput in 2.6.0 and 2.7.0 - closing.
