### ISSUE TITLE
Webhook handler runs twice for an event if shadow bucket is configured at sync gateway database

### ISSUE THREAD

**Issue by vk07519** [couchbase/sync_gateway#1946]
I have created a database at sync gateway with shadow bucket configured for it. PFB config file for database:

```
"db3": {
    "server": "localhost:8091",
    "bucket": "test3",
    "shadow": {
      "server": "localhost:8091",
      "bucket": "test4"
    },
    "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } },
"sync": `function(doc, oldDoc) {        
}`,
"event_handlers": {
    "document_changed": [
     {"handler": "webhook",
      "url": "http://localhost:49490/test"
     }
    ]
 }
}
```

When I upload a document, my api (http://localhost:49490/test) is hit twice. But when I remove shadow bucket from config, it works fine and hits my api only once.

**Comment by adamcfraser** [comment]
@ajres Also good candidate for functional test.

**Comment by ajres** [comment]
I have successfully reproduced this issue.

**Comment by ajres** [comment]
When pushing a change to the shadow bucket an echo is received back, this is not used to update the document in the Sync Gateway bucket. But db.UpdateDoc is not cancelled and raises a RaiseDocumentChangeEvent a second time.

This is the block in shadower.go pullDocument that processes the echo and does no cancel the db.updateDoc() caller LN#140.

```
} else {
    // We already have this rev; but don't cancel, because we do need to update the
    // doc's UpstreamRev/UpstreamCAS fields.
    base.LogTo("Shadow+", "Not pulling %q, CAS=%x (echo of rev %q)", key, cas, newRev)
}
```

**Comment by adamcfraser** [comment]
Bucket shadowing is actually updating the document in the Sync Gateway bucket when it processes that echo (as mentioned in the comment, to update the shadowing metadata in the doc).  Unlike other updates it's not generating a new revision - it's just setting the UpstreamRev/UpstreamCAS properties.

We need to see if there's a way to identify 'real' (adds a new revision) updates with the current state we have available when the webhook event is raised.  It would be preferable to avoid an change to the updateDoc API, but that would be a last resort.

**Comment by ajres** [comment]
Pushed PR #2014, dded the following test before firing a DocumentChangeEvent:

`if newRevID != doc.UpstreamRev {`

An echo will have it's UpstreamRev set to the newRevID
