### ISSUE TITLE
Querying views with stale=false sometimes fails

### ISSUE THREAD

**Issue by paulharter** [couchbase/sync_gateway#1951]
My understanding of the purpose of having the stale=false option on view queries was to ensure that the view was up to date with documents already added, allowing the possibility of "read your own writes" for such indexed queries. Is this correct? If so then it sometimes fails. 

It seems that if a view is queried before an insert into the database then a subsequent query of the view can fail. 

I have isolated the problem in a test:

https://gist.github.com/paulharter/e33422b1f7d20de462f8b48e07f10310

**Comment by adamcfraser** [comment]
What versions of Sync Gateway and Couchbase Server are you using?

**Comment by paulharter** [comment]
sync gateway 1.3 but only with walrus for this test. If the indexing behaviour might be different with couchbase I'll check.

**Comment by paulharter** [comment]
I just checked it with couchbase on my current dev setup and I'm not seeing the problem so I guess it's a side effect of using walrus that doesn't happen with couchbase. 

I'm using builds from a couple of months ago so I'll redo it in tomorrow with up to date builds just to be sure.

**Comment by adamcfraser** [comment]
I've moved this to https://github.com/couchbaselabs/walrus/issues/18.
