### ISSUE TITLE
Excluding channels from replication using sync_gateway/bychannel filter

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1960]
There are scenarios where users would like to synchronize "all channels except X" - particularly for the case where the set of desired channels changes frequently.

To address this case, we could allow excluded channels to be defined when using the by channel filter using the format `channels = ["- channelname"]` - in this case the changes feed will return all channels the user has access to except for the specified channel.  

A concern is that a combination of excluded and included channels doesn't really make any sense - setting channels=["channelA" "-channelB"] isn't meaningful, since "-channelB" means everything except channelB (including channelA) will already be included.

An alternative approach would be to define a sync_gateway/exceptchannel filter for this scenario.

**Comment by adamcfraser** [comment]
Sample use case discussed here:
https://forums.couchbase.com/t/use-custom-filters-for-changes-feed-of-sync-gateway/9120

**Comment by adamcfraser** [comment]
The exclude filter wouldn't be compatible with admin API requests, or requests by users that have `*` channel access, since changes processing isn't based on a set of channel feeds in those scenarios (which could be excluded) - it's instead based on working the `*` channel feed.  The performance overhead to exclude results from the `*` feed on a record-by-record basis isn't feasible.

**Comment by househippo** [comment]
@adamcfraser I think this is touching on CBL being aware of channels they have access to.

**Comment by adamcfraser** [comment]
Closing this, as the complexities listed above outweigh the potential benefit.  Can reopen if there's a specific use case that can't be handled otherwise.
