### ISSUE TITLE
Fix race between DCP start + view backfill (non-accel)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1961]
Possible way to repro:

On startup:
1. Start DCP feed at the latest 
2. Set validfrom=sync:seq on channel cache
3. For changes requests
   - if since < validfrom then viewbackfill
   - if since >= validfrom then cache
4. But DCP feed doesn't necessarily start at sync:seq 

^^^ not sure about this, needs more details.  May be another ticket out there that describes better

**Comment by adamcfraser** [comment]
Needs more detail to describe the exact problem scenario.

**Comment by adamcfraser** [comment]
Has been addressed by cache enhancements in 2.5.
