### ISSUE TITLE
Sequence allocator should expire unused sequences after 60 mins

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1962]
Otherwise, idle node with unused sequences will write docs that will be replicated.

**Comment by adamcfraser** [comment]
Additional details.  When a Sync Gateway node is going to perform a bulk write (via `_bulk_docs`), it allocates a block of sequences for that write (performing an incr on the sequence document).

If any of those writes fail, the unused sequences are retained for future write operations by that Sync Gateway node.  This has a few issues:
- If that Sync Gateway node is idle for a short period of time, the unused sequences will block sequence buffering for writes done elsewhere in the cluster.  This is mitigated somewhat by the skipped sequence handling - missing sequences will be skipped after a short time (5s) and won't be abandoned for 60m.  However, there's still performance overhead in that window.
- If that Sync Gateway node is idle for a longer period of time (>1h), but then attempts new writes, the cached sequence values will have already been given up on (abandoned) by other SG nodes in the cluster.

**Comment by adamcfraser** [comment]
Has been addressed by sequence allocator improvements in 2.6.
