### ISSUE TITLE
Add DCP support to Walrus w/ rollback ability

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1964]
Walrus can expose DCP feed
1. Ability to trigger rollback (can keep snapshots of its state every second, and the rollback can go back in time X seconds)
2. Send Snapshot markers to test DCP Restart at checkpoint

**Comment by adamcfraser** [comment]
To fully cover our test scenarios, there's probably an additional requirement that walrus supports multiple "vbuckets" (no actual change from the storage perspective, but documents get assigned a vbucket and vbucket seqno).  This might be a separate ticket - we could implement the DCP feed as a stream on a single vbucket for walrus - but should be considered when working out the design for this feature.

**Comment by adamcfraser** [comment]
Not planning to fix - testing requiring DCP being handled by integration tests.
