### ISSUE TITLE
Resync for sg-accel

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1966]
Currently sg-accel doesn't support the resync operation.  At minimum we need the ability to trigger a flush of the index bucket during resync, and documentation on how to use (i.e. entire sg-accel cluster needs to be offline).  Ideally this would be automated through cbgt orchestration.

**Comment by adamcfraser** [comment]
For 1.4, treat as a documentation-only feature, describing how to do this manually.  Filed #2073 for the automated version post-1.4.

**Comment by adamcfraser** [comment]
This ticket tracks the engineering work to submit a PR for @jamiltz to review in the mobile portal.

**Comment by adamcfraser** [comment]
Includes working w/ @jamiltz to clarify the process for engineering submissions to the mobile portal repo.

**Comment by jamesnocentini** [comment]
The DP docs currently live at https://github.com/couchbase/sync_gateway/wiki/Introduction-to-Sync-Gateway-Accelerator. There are no current plans to move them to the official site before 1.4 (should we have them on the site marked as DP?). Until then, the best approach is to update the wiki directly.

For docs currently deploy, I've updated the [couchbase-mobile-portal README](https://github.com/couchbaselabs/couchbase-mobile-portal#contributing-to-docs) with steps to update and a small style guide.

**Comment by adamcfraser** [comment]
This issue was moved to couchbaselabs/sync-gateway-accel#22
