### ISSUE TITLE
Sync Gateway cluster management tool

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1967]

**Comment by adamcfraser** [comment]
Currently there aren't any tools for administrators to monitor the state of their sg-accel cluster.  This would include:
- Reviewing vbucket assignment across nodes (to validate/monitor CBGT management)
- Index write throughput

**Comment by adamcfraser** [comment]
Better to do this as part of a comprehensive cluster administration tool (potentially covering both sg_accel and sync_gateway).

**Comment by adamcfraser** [comment]
Closing, pending prioritization and full specification.
