### ISSUE TITLE
Ability to take sg-accel offline

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1968]
Currently the online/offline functionality is limited to sync gateway - there's no support in sg-accel.  

Functional benefits:
- Immediate removal of the node from the CBGT cluster (i.e. don't need to wait for heartbeat detection to remove the node)
- REST API based node administration (i.e. able to temporarily bring down a node without directly logging in to the box and stopping the service)

**Comment by adamcfraser** [comment]
Needs functional test.

**Comment by djpongh** [comment]
Moved to: https://github.com/couchbaselabs/sync-gateway-accel/issues/214
