### ISSUE TITLE
1.3 Sync Gw docker image

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1969]
Items still pending:
- [ ] QE test of [unofficial Sync Gateway 1.3 Docker image](https://hub.docker.com/r/couchbase/sync-gateway/)  (@sethrosetter)
- [x] Finish first pass of README docs (@tleyden)
- [x] Review of README docs from technical perspective (@jamiltz) 
- [ ] Review of README docs from a marketing perspective (@waynecarter) 
- [ ] Open a PR for docker official image review of Dockerfile (@ceejatec)
- [x] Open a PR for docker official image review of README, which is separate from Dockerfile review (@jamiltz)

**Comment by dgcaron** [comment]
i guess you guys are racing to release the 1.3, i'll just take the released version as soon as it arrives.

**Comment by tleyden** [comment]
Yeah, but we still don't have the docker stuff integrated into our automated release process, so please ping this ticket if you see the release 1.3 go out sans docker image

**Comment by tleyden** [comment]
Note: the way we build sync gateway changes, so the dockerfile will need to get updated to use that.  (or be changed to use pre-built package)

**Comment by tleyden** [comment]
@sethrosetter / @jamiltz -- I'd highly recommend doing all of your testing on Linux rather than OSX.  docker-machine aka boot2docker breaks down pretty quickly.  I tried to add caveats to the docs, but I think we should focus on the common deployment case.

**Comment by dgcaron** [comment]
Small side note The newer docker for mac and docker for windows is a lot better than the older boot2docker stuff

**Comment by tleyden** [comment]
@dgcaron agreed!  But ...

**Comment by dgcaron** [comment]
:) I'll stay out of this talk , you guys know best

**Comment by tleyden** [comment]
@dgcaron 

## Option 1: Use Docker under Linux

Oh, everything Just Works!

## Option 2: Use Docker under OSX using docker-machine

Oh, hey I can't go to localhost, I have to go to this weird IP address!

Oh, hey volume mounts don't work!  Unless I use the `/Users` directory .. then it might work.

etc... :-)

**Comment by dgcaron** [comment]
+1

**Comment by tleyden** [comment]
@dgcaron you are more than welcome to test this [Sync Gw 1.3 Docker README](https://github.com/couchbase/docker/blob/master/enterprise/sync-gateway/1.3.0-274/README.md) btw!  Any feedback you have will influence the final product that gets released.

**Comment by tleyden** [comment]
@jamiltz will be online soon, and he's the one doing the final review of the docs. (and some testing, hopefully!)

**Comment by tleyden** [comment]
@jamiltz ok I've pushed up my latest changes to the README, not planning on making any more .. handing off to you.

The file you want to edit is https://github.com/couchbase/docker/blob/master/generate/resources/sync-gateway/README.md

You can send a PR to @ceejatec to review.  You'll want to run the golang script as described in https://github.com/couchbase/docker/blob/master/README.md

**Comment by jamesnocentini** [comment]
Everything worked fine on my OSX laptop except starting a docker container with a path to a config file. Steps I followed:

```
1. Create config file under /Users (on OSX)
vi ~/Downloads/my-sg-config.json
2. Copy content per readme
{
  "log": ["*"],
  "databases": {
    "db": {
      "server": "http://couchbase-server:8091",
      "bucket": "default",
      "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } }
    }
  }
}
3. Start container with this config file
docker run --net=couchbase -p 4984:4984 -d -v /tmp:/tmp/config couchbase/sync-gateway ~/Downloads/my-sg-config.json
4. Container logs
docker logs container-id
2016-08-11T14:26:35.833Z FATAL: Error reading config file /Users/jamesnocentini/Downloads/my-sg-config.json: open /Users/jamesnocentini/Downloads/my-sg-config.json: no such file or directory -- rest.ParseCommandLine() at config.go:490
```

I haven't tried to use `docker-machine ssh` since the readme notes that it should work under the `/Users` folder on OSX.
