### ISSUE TITLE
sg_accel windows installer missing tools folder

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1970]
the tools folder and sgcollect_info are not installed with sg_accel enterprise

**Comment by ajres** [comment]
It looks like the sg_accel.ism has the tools and sgcollect_info.exe entries.

**Comment by michaelkwok** [comment]
I believe this is a post installation issue.  If you download the sg_accel build, you will see it has the tools folder with sgcollectinfo where it needs to be.  It sounds like it's an real issue with the installer not copying it to the correct location during installation.  Please correct me if I am misunderstand.  Then we need to take a look at the packaging script or the Installshield project configuration.
