### ISSUE TITLE
sgcollect_info assumes sync_gateway not sg_accel

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1971]
sgcollect_info generates a number of paths to lookup files, but it assumes that the user is running sync_gateway so paths are incorrect for sg_acceel e.g.

`sg logs (sync_gateway_error.log) (cat /home/sync_gateway/logs/sync_gateway_error.log)`

**Comment by tleyden** [comment]
@ajres I pushed up a bunch of changes to [feature/sg_collect_info_windows](https://github.com/couchbase/sync_gateway/tree/feature/sg_collect_info_windows)

Can you do the following:
- Write a function called `strip_passwords()` that takes a sync gateway config and runs a regular expression to strip out the bucket password?  And possibly others if there is other sensitive info.
- Plug in `strip_passwords()` as a `content_postprocessor` here:

```

    # Get server config
    server_config_url = "{}/_config".format(sg_url)
    config_task = make_curl_task(name="Collect server config",
                                 user="",
                                 password="",
                                 url=server_config_url,
                                 log_file="running_server_config.log",
                                 content_postprocessors=[reverser])
    collect_config_tasks.append(config_task)
```

as well as passing in an array of `content_postprocessors` here:

```
task = add_file_task(sourcefile_path=sg_config_file)
```

**Comment by tleyden** [comment]
@ajres also, can you add Windows files paths:

```
def make_config_tasks(zip_dir, sg_config_path, sg_url):

    collect_config_tasks = []

    # Here are the "usual suspects" to probe for finding the static config
    sg_config_files = [
        "/home/sg_accel/sg_accel.json",                     # linux sg accel
        "/home/sync_gateway/sync_gateway.json",             # linux sync gateway
        "/Users/sync_gateway/sg_accel.json",                # OSX sg accel
        "/Users/sync_gateway/sync_gateway.json"             # OSX sync gateway
        # TODO: add windows paths
    ]
```

and

```
def make_collect_logs_tasks(zip_dir, sg_url):

    sg_log_files = {
        "sync_gateway_access.log": os.path.join("sync_gateway", "logs", "sync_gateway_access.log"),
        "sync_gateway_error.log": os.path.join("sync_gateway", "logs", "sync_gateway_error.log"),
        "sg_accel_access.log": os.path.join("sg_accel", "logs", "sg_accel_access.log"),
        "sg_accel_error.log": os.path.join("sg_accel", "logs", "sg_accel_error.log"),
    }

    os_home_dirs = [
        "/home",                         # linux
        "/Users"            # OSX
        # TODO: Windows
    ]
```

**Comment by tleyden** [comment]
@ajres Also it would be really useful if you can retest on Windows after the above changes and let me know what's still broken there.

**Comment by ajres** [comment]
@tleyden 

I have pushed changes to branch.

There is still an issue with bundling sgcollect_info in sg_accel Windows installer, I'll retest after I fix that.

I didn't understand what needed actioning for the following comment above.

> as well as passing in an array of content_postprocessors here:
> 
> ```
> task = add_file_task(sourcefile_path=sg_config_file)
> ```

**Comment by ajres** [comment]
There are two styles for providing username and password for protected CBS buckets

External to server URI

```
{
	"log": ["*"],
        "databases": {
		"db": {
			"server": "http://localhost:8091",
                        "bucket":"bucket-1",
                        "username":"bucket-1",
                        "password":"foobar",
		}
	}
}
```

Embedded in server URI

```
{
	"log": ["*"],
        "databases": {
		"db": {
			"server": "http://bucket-1:foobar@localhost:8091",
                        "bucket":"bucket-1"
		}
	}
}
```

**Comment by ajres** [comment]
Same applies to shadow password protected shadow buckets

**Comment by tleyden** [comment]
The PR should take care of shadow buckets and channel_index buckets.  Unit tests cover both scenarios.
