### ISSUE TITLE
Verify fix: sgcollect_info incorrectly build paths on macOS

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1972]
sgcollect_info incorrectly generates paths under the sync_gateway home folder on macOS.

sgcollect_info assumes a default home directory of `/home/sync_gateway`, but on macOS it is `/Users/sync_gateway`

**Comment by adamcfraser** [comment]
Fixed, pending retesting.

**Comment by tleyden** [comment]
I can see from the logs that it's currently looking for logs in `/Users/sync_gateway/logs/sync_gateway_error.log`

**Comment by ajres** [comment]
retested as part of #1911

sync_gateway_error.log is included in the .ZIP archive
