### ISSUE TITLE
Simplify sg-collect-info CLI

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1988]
Why does the user even need to specify `--upload-host`?  

Why not have it so that if a customer and a ticket number is supplied, it will upload to s3.amazonaws.com/cb-customers by default?

If for some reason (seems uncommon), a different upload host should be used, they can override it by adding the `--upload-host` flag?

**upload_ticket help**: "specifies the support ticket number for the upload.  e.g 1234 (must be numeric), contact Couchbase Support to open a new ticket if you don't already have one.  you must also provide the upload_customer flag if this is used"

**upload_customer help**: "specifies the customer name for the upload.  this is an arbitrary string, but please use something that makes it easy to identify you or your company, eg, Acme, Inc"

**upload_host help**: "if you specified upload_ticket and upload_customer, and need to override the default host (s3.amazonaws.com/cb-customers), then specify the alternate upload host here"

From @mattcarabine:

> So the problem is, what if you want to collect logs without uploading them, do we then have to add a further flag that say '--no-upload'?
> 
> To me it doesn't seem to make much difference, but one of the two options is already in place.

From me:

I think you would just not specify upload_customer or upload_ticket in that case.

```
if upload_customer and upload_ticket:
   upload to s3.amazonaws.com/cb-customers or whatever user specified in upload_host
else if upload_customer but not upload_ticket, or vice-versa:
   print an error saying that both must be specified
else if neither upload_customer or upload_ticket:
   collect logs but do not upload to s3 
```

If that's a bigger change than we want for this PR .. how about changing the upload_host help to: "when specifying upload_customer and upload_ticket to upload the logs to a support ticket, you must also specify an upload_host. Use s3.amazonaws.com/cb-customers unless you've been instructed otherwise by Couchbase Support."

**Comment by tleyden** [comment]
@mattcarabine any thoughts?  Part of the reason I'm asking is just to better understand what's required in these args.

**Comment by mattcarabine** [comment]
Doing that seems fine to me, it was just outside the scope of what I was willing to change at this point in the release prep (since if there was a problem it could break upload), which is why I only updated the documentation for it.

You're right that it does make using the CLI slightly easier when uploading logs, so if you're willing to make the change and we have enough testing behind it ensure it works for the 1.3 timescale then that's fine by me.

**Comment by bbrks** [comment]
The REST API endpoint has a default upload host for Couchbase support, but the command line tool has not changed yet.

**Comment by adamcfraser** [comment]
Closing based on age.
