### ISSUE TITLE
1.3 GA release tasks

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#1993]
- [x] Tag SG repo
- [x] Tag sg_accel repo
- [x] Regenerate SG release notes on Github.
- [x] Regenerate SG release notes on mobile portal.
- [x] Regenerate sg_accel release notes on Github.
- [x] Regenerate sg_accel release notes on mobile portal.
- [x] Generate AMI
- [x] Publish AMI to AWS Marketplace (requires Anil)
- [ ] Generate and publish GA docker image (#1969)
- [x] Azure Marketplace (?)
- [x] Push GA binaries to S3

**Comment by ajres** [comment]
Can't locate the sg_accel GitHub repo

**Comment by adamcfraser** [comment]
Repo is couchbaselabs/sync-gateway-accel.

**Comment by ajres** [comment]
Found it, thanks.
