### ISSUE TITLE
Stopping Sync Gateway

### ISSUE THREAD

**Issue by joshglenn** [couchbase/sync_gateway#1994]
New to Couchbase server and sync-gateway. I have installed couchbase server. It is running and I can go the admin interface. sync_gateway is also installed, and running. However... stopping it is another story. The [manual](http://developer.couchbase.com/documentation/mobile/current/develop/guides/sync-gateway/running-sync-gateway/starting-and-stopping/index.html) says:

> You can stop Sync Gateway by typing Control-C. There is no specific shutdown procedure and it is safe to stop Sync Gateway at any time.

Which is not true in my case. That would be the case if I had started it from a TTY, but I didn't. It seems to be running as a daemon. I can stop it like this:

```
sudo service sync_gateway stop
```

So, just FYI. This isn't in the docs. I'm thinking it may be a good idea to update the docs to reflect that it can be started and stopped as a daemon. Granted, those with sysadmin experience under linux already know this. But many other people could use the helping hand, especially when getting started.

**Comment by adamcfraser** [comment]
@jamiltz It looks like we have a gap in the Sync Gateway docs around running SG as a service.

**Comment by adamcfraser** [comment]
Docs added to mobile portal.
