### ISSUE TITLE
Problems Using sync-gateway - Initial setup

### ISSUE THREAD

**Issue by joshglenn** [couchbase/sync_gateway#1995]
If I run the sync_gateway using the following command:

```
sudo service sync_gateway start
```

I can immediately access the sync_gateway server (from outside my local network using its IP) and I get the following response:

```
{"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":1.2},"version":"Couchbase Sync Gateway/1.2.1(4;26c202a)"}
```

However, when I stop the `sync_gateway` service then run the sync gateway from the command line like this:

```
/opt/couchbase-sync-gateway/bin/sync_gateway -dbname="grocery-sync" -url="http://localhost:8091"
```

I get a connection refused error. Any idea why?

**Comment by joshglenn** [comment]
I finally got sync_gateway working. But not from the command line. I did not know how to edit the config for the daemon. I found a thread somewhere that showed how. In case others run into this, here's what worked for me:
1. Run `sudo su - sync_gateway` to login as the sync_gateway user.
2. Run `vi sync_gateway.json` to edit the config. An example looks something like this:
   
   ```
   {
       "log": ["HTTP+"],
       "adminInterface": "127.0.0.1:4985",
       "interface": "0.0.0.0:4984",
       "databases": {
               "grocery-sync": {
                       "server": "http://localhost:8091",
                       "bucket": "grocery-sync",
                       "users": {
                               "GUEST": {"disabled": false, "admin_channels": ["*"] }
                       }
               }
       }
   }
   ```
3. Save the config.
4. Type `exit` then press Enter
5. Execute `sudo service sync_gateway reload` to re-initialize.

What would be the equivalent command line version to start sync_gateway with the above config?

**Comment by adamcfraser** [comment]
This type of question is more appropriate for the forums - moved the question there.

https://forums.couchbase.com/t/problems-using-sync-gateway-initial-setup/9271
