### ISSUE TITLE
sgcollect_info pprof will fail if sync_gateway started with relative path

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#1998]
Initially tested on mac os

When testing sgcollect_info it was agains Sync gateway installed from a package and running as a service.

In this case sync_gateway is started from an absolute path, sgcollect_info uses expvars to retrieve the sync_gateway path and uses the same path to generate the pprof reports.

If sync_gateway is started manually with a relative path, sgcollect_info fails to generate the pprof reports because (highly likely) the relative path will not match the actual location of the sync_gateway executable.

**Comment by adamcfraser** [comment]
This seems like it should be handled as:
1. Attempt to use the cmdline
2. Add a new command line parameter to allow users to set the path to the executable explicitly
3. Attempt to use the default install location?  (or relative path from tools/sgcollect_info?)
4. On failure to obtain the binary from all of the above, just include the raw pprof response in the zip

**Comment by tleyden** [comment]
> On failure to obtain the binary from all of the above, just include the raw pprof response in the zip

@ajres do you know if this already happening?  I mean, even when the PDF pprof reports are failing?

**Comment by ajres** [comment]
@tleyden raw .gz files are not currently added to the .ZIP

**Comment by ajres** [comment]
Have pushed PR #2007 which covers steps 1,2,3.
