### ISSUE TITLE
Generate 1.3 AMI and publish to AWS marketplace

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2017]
- [x] Build AMIs on Jenkins 
- [x] Smoke test AMIs on AWS
- [x] Deliver AMI ID's to PM + help do marketplace listing

**Comment by tleyden** [comment]
1.3.0-274

**Comment by tleyden** [comment]
Jenkins builds:
- [57](http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-ami/57/) -- Enterprise
- [58](http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-ami/58/) -- Community

**Comment by tleyden** [comment]
Status: waiting on AWS marketplace to respond.
