### ISSUE TITLE
Improvement - Admin UI

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#2018]
The admin ui is sorta hidden is plain site on the docs page.

<img width="851" alt="screen shot 2016-07-31 at 12 37 27 am" src="https://cloud.githubusercontent.com/assets/4956099/17275351/874ed9a8-56b9-11e6-9358-15d29de6265d.png">

Could you make create a better hint about it.

<img width="493" alt="screen shot 2016-07-31 at 12 51 30 am" src="https://cloud.githubusercontent.com/assets/4956099/17275357/acb88036-56b9-11e6-8212-4e97ac336752.png">

AND

<img width="1031" alt="screen shot 2016-07-31 at 12 50 14 am" src="https://cloud.githubusercontent.com/assets/4956099/17275376/21d02644-56ba-11e6-8e9a-e4114f2e0e29.png">

**Comment by adamcfraser** [comment]
We should consider this along with the 2.0 enhancements for the admin UI.

**Comment by tleyden** [comment]
@househippo great idea!

**Comment by adamcfraser** [comment]
Closing - admin UI is unsupported.
