### ISSUE TITLE
rev_limit not working when syncgateway documents conflicts happens

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2023]
We are using the syncgateway 1.2.0 version, 

client is using **new_edits=false** in bulk_docs post request which results in conflicts in the revisions if client is disconnected from syncgateway and during this time document is updated at syncgateway by some other application and after some time client has updated the document in local and push the document to syncgateway.

from the below log, can see that the bulk_docs request has been succeeded but there is no change in the content of document except the in _sync part of document.

17:01:40.809048 2016-08-03T17:01:40.808+05:30 HTTP:  #2628: POST /pttdata/_bulk_docs  (ADMIN)
17:01:40.810484 2016-08-03T17:01:40.810+05:30 CRUD+: Invoking sync on doc "s9000000000_Location.doc" rev 10-6cd5463c212d3647821fe2b342ed5c9d
17:01:40.810832 2016-08-03T17:01:40.810+05:30 CRUD+: updateDoc("s9000000000_Location.doc"): Rev "10-6cd5463c212d3647821fe2b342ed5c9d" leaves "10-6cd3543b151d3731994ea9b717ad8b9c" still current
17:01:40.811845 2016-08-03T17:01:40.811+05:30 CRUD: Stored doc "s9000000000_Location.doc" / "10-6cd5463c212d3647821fe2b342ed5c9d"
17:01:40.811977 2016-08-03T17:01:40.811+05:30 HTTP+: #2628:     --> 201   (3.0 ms)

The below is the document in the couchbase
"rev": "10-6cd3543b151d3731994ea9b717ad8b9c",
    "new_rev": "10-6cd5463c212d3647821fe2b342ed5c9d",
    "flags": 28,
    "sequence": 73,
    "recent_sequences": [
      11,
      12,
      24,
      25,
      47,
      48,
      67,
      68,
      69,
      70,
      71,
      72,
      73
    ],
    "history": {
      "revs": [
        "7-7a70c5b46c4256fe44e8014b302e9c5d",
        "4-19920b785b844befbb086986ecf7d91f",
        "10-6cd5463c212d3647821fe2b342ed5c9d",
        "3-cad17bba54dee4ffa46e6906894a6c7b",
        "5-4fe2230129ebbf7b5cc1991fbce5c10a",
        "9-e277966720ec79d457ef70ad6a18f34e",
        "8-3a73347c4ce01074a52355ef0297a70a",
        "9-e277966720ec79d457ef70ad6a18f34",
        "10-6cd3543b151d3731994ea9b717ad8b9c",
        "6-f30d17be11bf538abcf0101f36921809",

rev-limit is set to 5. but looks like whenever conflicts is there rev_limit is not working, revisions are growing in the document.

**Comment by adamcfraser** [comment]
@ArihantRk This is the expected behaviour - revisions are pruned based on the minimum revision generation of non-deleted leaf nodes in the revision tree.  

Some additional details on https://github.com/couchbase/sync_gateway/issues/501 for context on this approach.
