### ISSUE TITLE
sgcollect_info missing items when running under docker

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2027]
Using this [Dockerfile](https://gist.github.com/tleyden/00cdb534d4d0b1232e06511699d1bf8e) which is still under construction, I ran sgcollect_info and got the following output:

https://gist.github.com/tleyden/0b4a4df4a90fa0054907465ac5fcfa17

What's missing:
1. Sync gateway binary
2. Sync gateway logs

**Comment by tleyden** [comment]
> Sync gateway logs

Sync gateway writes logs to stderr / stdout by default, which docker captures .. but they are never written to a file.

With the right configuration to tell sync gateway to write to a file, this should get fixed.

**Comment by tleyden** [comment]
> With the right configuration to tell sync gateway to write to a file, this should get fixed.

Unfortunately using `logFilePath` removes the logging from stdout / stderr.  It might work, but it's not ideal from the docker best practices point of view.

To make things even more confusing, with `logFilePath` set, sync gateway just outputs the following to stdout / err:

```
# sync_gateway config.json
2016-08-03T23:34:19.399Z Enabling logging: [HTTP+]
```

So the user won't even know where to go look for the log files by looking at the stdout.

**Comment by tleyden** [comment]
Workaround steps for sg_collect_info:

```
docker logs container-id > /tmp/logs 2>&1
docker exec container-id mkdir -p /var/log/sync_gateway/
docker cp /tmp/logs contaner-id:/var/log/sync_gateway/sync_gateway_error.log
```

**Comment by tleyden** [comment]
@jamiltz the docker README will need a special section for this workaround step to capture logs when running sg_collect_info 

```
docker logs container-id > /tmp/sync_gateway.log 2>&1
docker exec container-id mkdir -p /var/log/sync_gateway/
docker cp /tmp/sync_gateway.log contaner-id:/var/log/sync_gateway/sync_gateway_error.log
```

**Comment by adamcfraser** [comment]
@tleyden Treating this as a docs-only issue at this point for 1.3.1.  

@jamiltz Should this also get updated in our sgcollect_info docs on the portal, in addition to the docker README?

**Comment by adamcfraser** [comment]
@jamiltz Can you provide an update on when you expect to get to this?  Not urgent, just trying to close out 1.3.1 issues.

**Comment by jamesnocentini** [comment]
Sorry for the late reply. @tleyden if it's a small change I think it'd be easier to open a PR with that change (I've never tried using sg collect info so I don't know where it should go). The md file for sg collect info is at https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/md-docs/ready/guides/sync-gateway/sg-collect-info.md

**Comment by bbrks** [comment]
It may be possible to follow nginx's setup to get both 'normal' Docker behaviour and log to a file for sgcollect_info to pick up...

> In some cases, `docker logs` may not show useful information unless you take
additional steps.
> 
> - [...]
> 
> - If your image runs a non-interactive process such as a web server or a
  database, that application may send its output to log files instead of `STDOUT`
  and `STDERR`.
> 
> [...] In the second case, the official `nginx` image shows one
workaround [...]
> 
> The official `nginx` image creates a symbolic link from
`/dev/stdout` to `/var/log/nginx/access.log`, and creates another symbolic link
from `/dev/stderr` to `/var/log/nginx/error.log`, overwriting the log files and
causing logs to be sent to the relevant special device instead. See the
[Dockerfile](https://github.com/nginxinc/docker-nginx/blob/26d7731f0a7b182c8fea76610dd7aa9a3369ab48/mainline/stretch/Dockerfile#L91-L93).

https://github.com/nginxinc/docker-nginx/blob/26d7731f0a7b182c8fea76610dd7aa9a3369ab48/mainline/stretch/Dockerfile#L91-L93

https://docs.docker.com/config/containers/logging/

**Comment by bbrks** [comment]
The above solution didn't quite work (`sgcollect_info` wouldn't read the logfile when SG had a file handle open for it), but I managed to use tee to achieve the desired result.

PR opened: https://github.com/couchbase/docker/pull/96
