### ISSUE TITLE
Build for Arm architecture

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2029]
@househippo needs to build Sync Gateway for a raspberry pi

**Comment by tleyden** [comment]
@househippo -- can you try this?

```
env GOOS=linux GOARCH=arm go build -v github.com/couchbase/sync_gateway
```

There is one caveat that it won't be using the "pinned dependency versions", but for your demo that probably won't matter.

**Comment by tleyden** [comment]
Btw, that command above should work on an OSX dev workstation with go 1.6 installed.

**Comment by adamcfraser** [comment]
@tleyden Can this be closed out now?

**Comment by tleyden** [comment]
@adamcfraser not done AFAIK but should probably go on @michaelkwok's plate

**Comment by djpongh** [comment]
dup of #1718
