### ISSUE TITLE
sg-collect-info: Validate security on s3 upload

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2037]
1. Need confirmation that we're following the same security standards for s3 upload that cbcollect_info follows. 
2. Validate that the existing process ensures privacy of uploaded customer data.  Some documentation (on this ticket) of how this is done.

**Comment by tleyden** [comment]
I created an email thread regarding this and put up a PR for https://github.com/couchbase/sync_gateway/issues/2051

No other action items so I'm closing this ticket
