### ISSUE TITLE
Sync gateway webhook calls and couchbase view updates

### ISSUE THREAD

**Issue by malisetti** [couchbase/sync_gateway#2044]
This is a doubt and I havent seen any documentation on this. I want to know below details. 

When a document is changed in couchbase server, it calls a webhook that is given in config. We have observed, if we use the document recieved from webhook and query a view it wont give the proper result because the view is not updated to reflect the current document. Is it the case ? Can we make sure that the webhook for a document is called once all the views that are related to the current document is updated ? 

I have tried to use the document that is received from the webhook to query a view with a delay(5 secs). Is there any upper limit to the time takes to update the view to reflect the current document that is sent via webhook ?

**Comment by adamcfraser** [comment]
I've moved this question to the forums - it's the appropriate location for this type of question.
https://forums.couchbase.com/t/sync-gateway-webhook-calls-and-couchbase-view-updates/9627
