### ISSUE TITLE
Couch docs with temporary ID - '_sync:rev:xxx'

### ISSUE THREAD

**Issue by venkat-imaginea** [couchbase/sync_gateway#2045]
When syncing a doc to couchbase through SyncGateway, the doc possesses a temporary ID, starting with '_sync:rev:'. On some very data-intensive usages, this is what been receiving everytime while retrieving the doc through View function. This prevents the doc to be retrieved from couchbase. Let me know if there's any fix for it.

**Comment by adamcfraser** [comment]
The _sync:rev document is a temporary backup of the previous revision body - this is needed to support other clients that are mid-replication and requesting that revision.

If you don't want to see these documents in your view, you'll need to modify your map function to exclude them.  In general any views that execute directly against the bucket used by Sync Gateway will need to exclude documents beginning with _sync - this includes the revision backups described above, but a variety of other internal Sync Gateway data and metadata (users, roles, replication checkpoints, etc).

**Comment by venkat-imaginea** [comment]
@adamcfraser but what is the guarantee that I retrieve the relevant doc? What is the handle I 've to retrieve it? Will ignoring it all the way would just do the need?

**Comment by adamcfraser** [comment]
As I said above, the _sync:rev document is a backup of the previous revision body, not the active version of the document.

**Comment by venkat-imaginea** [comment]
@adamcfraser I understand. How to retrieve the updated doc then? While I fetch for docs using View functions, I get many docs IDs as '_sync:rev', and I'm being forced to ignore those. But I'm in need of retrieving those docs with some 'handles'.

**Comment by adamcfraser** [comment]
The updated document should appear in your view results as usual - it's presence is unrelated to the state of the _sync:rev documents.  Can you be more specific on what you're not seeing in your view results?

**Comment by venkat-imaginea** [comment]
@adamcfraser : On retrieving the docs (which are of updated recently), few docs' IDs are with '_sync:rev'. Meanwhile these aren't enough to retrieve the details of the doc, hence I've no other go than to ignore them. Here, I want to know what else is the handle to obtain full details of those docs at that moment.

**Comment by adamcfraser** [comment]
You should ignore the _sync:rev docs.  The updated document itself will show up under its own doc id.

**Comment by venkat-imaginea** [comment]
@adamcfraser Yes, but it takes time to settle up. But meanwhile I've got to work on or update it further, hence I'm in need of an handle to retrieve and update it. Here comes the prob.

**Comment by adamcfraser** [comment]
This sounds unrelated to the _sync:rev question - can you redirect your workflow question to the forums?
https://forums.couchbase.com/c/mobile

**Comment by venkat-imaginea** [comment]
@adamcfraser I'll raise it up. Yet weird to see this sort of misunderstanding even after mentioning stuffs deep. No issues, I'll raise it right away. It's just that simple! Thanks btw.
