### ISSUE TITLE
Publish Docker image for 1.4.0

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2049]
Build and distribute once 1.3.1 GA is available.

**Comment by michaelkwok** [comment]
We have created images for Docker and AMI.  The Docker official image is awaiting approval from Docker and Traun is following up with them.  AMI is awaiting the push to Marketplace and Dan will handle it.

**Comment by tleyden** [comment]
To be re-assigned to PM

**Comment by ceejatec** [comment]
The amount of work for Docker, AWS, and Azure is quite broad, so I'm splitting this ticket up. This one will continue tracking Docker, and I'll leave it assigned to me as I've worked briefly on proposing the Official Image for Sync Gateway before. AWS will be tracked by the existing ticket #2362 . I've created #2454 for Azure. The latter two I've assigned to Ken as there's a slightly greater chance he'll be able to work on them soon.

**Comment by tleyden** [comment]
For aws and azure you should coordinate with @benofben -- https://github.com/couchbase-partners/amazon-cloud-formation-couchbase was created for similar purpose

**Comment by tleyden** [comment]
For azure there is https://github.com/couchbase-partners/azure-resource-manager-couchbase

**Comment by djpongh** [comment]
1.5 is almost here. We'll do it for that by filing a Jira ticket.
