### ISSUE TITLE
Sync Gateway failed to handle facebook login with specific user.

### ISSUE THREAD

**Issue by hideki** [couchbase/sync_gateway#2057]
During ToDoLite test fest, sync gateway can not handle facebook login for "hideki_iujwnty_test AT tfbnw.net". Please investigate why this account is not handled correctly. @sethrosetter knows this account's password.

**Comment by adamcfraser** [comment]
@hideki What is `"hideki_iujwnty_test AT tfbnw.net"` in this context?  Facebook username?  Sync Gateway user?

**Comment by sethrosetter** [comment]
@adamcfraser That is a facebook test user account.

**Comment by sethrosetter** [comment]
@pasin I am able to repro on my iOS 8 iPhone 4 device but It seems to be failing before it hits sync_gateway. It works fine in the simulator I think we need to pair debug this issue.

**Comment by sethrosetter** [comment]
@hideki @pasin I am no longer able to reproduce this. Can you try again @hideki and see if you are able to grab more information?

**Comment by adamcfraser** [comment]
@hideki Need more details in order to reproduce - wasn't able to reproduce as a Sync Gateway issue in session with @sethrosetter.

**Comment by adamcfraser** [comment]
Closing this as a client issue for the time being.  @hideki - feel free to reopen if you're able to reproduce.
