### ISSUE TITLE
Sync Gateway does not handle missing '/' in OIDC issuer

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2059]
Using SG `1.3.1-16`

This may not be an issue, however, it could be a nice enhancement.

This works in the sync gateway OIDC configuration:
`"issuer": "https://sts.windows.net/<tenant-id>/"`
This does not:
`"issuer": "https://sts.windows.net/<tenant-id>"`

The only difference is that the first has a trailing forward slash while the second does not

**Comment by adamcfraser** [comment]
Closing, as this isn't a necessary enhancement.
