### ISSUE TITLE
syncgateway permanently disconnecting connection from couchbase bucket while automatic bringing offline to online

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2063]
We are using syncgateway 1.3 and 3 nodes CBS 4.1 cluster. 
good to see retry for bringing offline to online feature. but i am receiving below issue
i did check this with one couchbase node in cluster,  this error we could see while making POST request (offline-> online) and request goes to node which is down.

when using 3 nodes, syncgateway 
scenario to reproduce :
1. bucket goes to offline when one of node in cluster goes down 
2. syncgateway catches the TAP connection and trying for making online.  
 Connection to TAP feed for ptxdata re-established, bringing DB back online
3. sometime bucket connection disconnects permanently while offline --> online(POST request) 
 GET /ptxdata/  (ADMIN)
20:03:13.609708 2016-09-07T20:03:13.609+05:30 HTTP: #171:     --> 404 no such database "ptxdata"  (0.1 ms)

Note : POST request response status is 200 but syncgateway loses connection permanently

20:02:46.132599 2016-09-07T20:02:46.132+05:30 WARNING: Bucket Updater for bucket ptxdata returned error: Get http://10.2.0.203:8091/pools/default/bucketsStreaming/ptxdata: dial tcp 10.2.0.203:8091: getsockopt: connection refused -- base.GetCouchbaseBucket.func1() at bucket.go:405
20:02:46.132666 2016-09-07T20:02:46.132+05:30 WARNING: Lost TAP feed for bucket ptxdata, with error: Get http://10.2.0.203:8091/pools/default/bucketsStreaming/ptxdata: dial tcp 10.2.0.203:8091: getsockopt: connection refused -- rest.(_ServerContext)._getOrAddDatabaseFromConfig.func1() at server_context.go:352
20:02:46.132677 2016-09-07T20:02:46.132+05:30 CRUD: Taking Database : ptxdata, offline
20:02:46.132682 2016-09-07T20:02:46.132+05:30 CRUD: Waiting for all active calls to complete on Database : ptxdata
20:02:46.132688 2016-09-07T20:02:46.132+05:30 CRUD: Database : ptxdata, is offline
20:02:46.142736 2016-09-07T20:02:46.142+05:30 Bucket: Refresh() [10.029934ms]
20:02:46.142752 2016-09-07T20:02:46.142+05:30 CRUD: *_Connection to TAP feed for ptxdata re-established, bringing DB back online**
20:02:52.141040 2016-09-07T20:02:52.141+05:30 Heartbeat: heartbeat written to _changes feed for request received  (as ADMIN)
20:02:56.142915 2016-09-07T20:02:56.142+05:30 Closing db /ptxdata (bucket "ptxdata")
20:02:56.142989 2016-09-07T20:02:56.142+05:30 Bucket: Close() [16.339µs]
20:02:56.143012 2016-09-07T20:02:56.143+05:30 Opening db /ptxdata as bucket "ptxdata", pool "default", server http://prod-C1-CBS-V1.service.com:8091

20:02:56.259439 2016-09-07T20:02:56.259+05:30 WARNING: Error from Incr in sequence allocator (0) - attempt (2/3): dial tcp 10.2.0.203:11210: getsockopt: connection refused -- db.(_sequenceAllocator).incrWithRetry() at sequence_allocator.go:88
20:02:56.270816 2016-09-07T20:02:56.270+05:30 Bucket: Incr("_sync:seq", 0, 0, 0) [1.250315ms]
20:02:56.270846 2016-09-07T20:02:56.270+05:30 WARNING: Error from Incr in sequence allocator (0) - attempt (3/3): dial tcp 10.2.0.203:11210: getsockopt: connection refused -- db.(_sequenceAllocator).incrWithRetry() at sequence_allocator.go:88
20:02:56.280996 2016-09-07T20:02:56.280+05:30 WARNING: Too many unsuccessful Incr attempts in sequence allocator - giving up (0): dial tcp 10.2.0.203:11210: getsockopt: connection refused -- db.(_sequenceAllocator).incrWithRetry() at sequence_allocator.go:94
20:02:56.281027 2016-09-07T20:02:56.281+05:30 WARNING: Error from Incr in _reserveSequences(0): Unable to increment sequence: dial tcp 10.2.0.203:11210: getsockopt: connection refused -- db.(_sequenceAllocator)._reserveSequences() at sequence_allocator.go:65
20:02:56.281038 2016-09-07T20:02:56.281+05:30 ERROR: Unable to increment sequence: dial tcp 10.2.0.203:11210: getsockopt: connection refused -- rest.(_ServerContext).TakeDbOnline() at server_context.go:575
20:03:01.058362 2016-09-07T20:03:01.058+05:30 HTTP:  #168: PUT /pttdata/_user/test  (ADMIN)
20:03:01.058422 2016-09-07T20:03:01.058+05:30 HTTP: #168:     --> 400 Invalid JSON: "invalid character '\' looking for beginning of object key string"  (0.1 ms)
20:03:13.266666 2016-09-07T20:03:13.266+05:30 HTTP:  #169: GET /
20:03:13.266720 2016-09-07T20:03:13.266+05:30 HTTP+: #169:     --> 200   (0.1 ms)
20:03:13.421067 2016-09-07T20:03:13.421+05:30 HTTP:  #170: GET /pttdata/  (ADMIN)
20:03:13.422584 2016-09-07T20:03:13.422+05:30 Bucket: Incr("_sync:seq", 0, 0, 0) [1.491052ms]
20:03:13.422622 2016-09-07T20:03:13.422+05:30 WARNING: Error from Incr in sequence allocator (0) - attempt (1/3): dial tcp 10.2.0.203:11210: getsockopt: connection refused -- db.(_sequenceAllocator).incrWithRetry() at sequence_allocator.go:88
20:03:13.434071 2016-09-07T20:03:13.434+05:30 Bucket: Incr("_sync:seq", 0, 0, 0) [1.29413ms]
20:03:13.434109 2016-09-07T20:03:13.434+05:30 WARNING: Error from Incr in sequence allocator (0) - attempt (2/3): dial tcp 10.2.0.203:11210: getsockopt: connection refused -- db.(_sequenceAllocator).incrWithRetry() at sequence_allocator.go:88
20:03:13.445563 2016-09-07T20:03:13.445+05:30 Bucket: Incr("_sync:seq", 0, 0, 0) [1.282954ms]
20:03:13.445595 2016-09-07T20:03:13.445+05:30 WARNING: Error from Incr in sequence allocator (0) - attempt (3/3): dial tcp 10.2.0.203:11210: getsockopt: connection refused -- db.(_sequenceAllocator).incrWithRetry() at sequence_allocator.go:88
20:03:13.455783 2016-09-07T20:03:13.455+05:30 WARNING: Too many unsuccessful Incr attempts in sequence allocator - giving up (0): dial tcp 10.2.0.203:11210: getsockopt: connection refused -- db.(_sequenceAllocator).incrWithRetry() at sequence_allocator.go:94
20:03:13.455834 2016-09-07T20:03:13.455+05:30 WARNING: Error from Incr in lastSequence(): Unable to increment sequence: dial tcp 10.2.0.203:11210: getsockopt: connection refused -- db.(_sequenceAllocator).lastSequence() at sequence_allocator.go:40
20:03:13.455919 2016-09-07T20:03:13.455+05:30 HTTP+: #170:     --> 200   (34.9 ms)
20:03:13.609673 2016-09-07T20:03:13.609+05:30 HTTP:  #171: GET /ptxdata/  (ADMIN)
20:03:13.609708 2016-09-07T20:03:13.609+05:30 HTTP: #171:     --> **404 no such database "ptxdata"  (0.1 ms)**

**Comment by ArihantRk** [comment]
any update on this? this issue we are getting very frequently.

**Comment by djpongh** [comment]
Should be handled with our recently added support for multiple URL's. If that's not the case, please reopen.
