### ISSUE TITLE
bucket shadowing one way

### ISSUE THREAD

**Issue by igreenfield** [couchbase/sync_gateway#2064]
Is there a way to do one way bucket shadowing:

in this direction: `<app-bucket>` ---> `<shadow-bucket>`
and **NOT** in this: `<app-bucket>` <--- `<shadow-bucket>`

**Comment by adamcfraser** [comment]
Not that I know of - bucket shadowing is designed specifically to maintain a copy of the data. 

Can you share any more details on your use case, to help understand whether there's another way to do what you're trying to do?

**Comment by igreenfield** [comment]
I have an app that need to use other bucket data and modify that data, but I don't want that changes will propagate back to the original bucket.

**Comment by adamcfraser** [comment]
Is the source bucket being written to via Sync Gateway (i.e. does the data include Sync Gateway's replication metadata)?  If so, you could do a one-way replication between the buckets using the sg-replicate integration added in 1.3.

**Comment by igreenfield** [comment]
there source bucket is regular bucket (java client) it shadows throw the sync-gateway

**Comment by adamcfraser** [comment]
Bucket shadowing has been deprecated - coexistence of SDK clients and SG is now supported via enable_shared_bucket_access.
