### ISSUE TITLE
Allow sg-replicate to replicate expiry times using show_exp=true

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2065]
As per docs expiration time is not replication through sg replication. as my understanding, sg replication works same like client hence _sync part will not available for sg replicatior and it wont be available in get request.
there will be mismatch between syncgateways connected through sg repicator.

**can't we add show_exp=true parameter in get request so that exp time also gets replicated .**
also **expiration does not work when document deleted from syncgateway.**

**Comment by adamcfraser** [comment]
Please file separate tickets for separate issues.

The expiration feature is specifically designed to remove data in a single database - it's not designed to be replicated.  However, I agree that an sg-replicate enhancement to optionally use show_exp=true would be a useful feature.  Using this ticket to track that enhancement request.

**Comment by ArihantRk** [comment]
Yup thanks @adamcfraser .

**Comment by ArihantRk** [comment]
@adamcfraser 
Replication of **_exp** can be user configurable.

**Comment by adamcfraser** [comment]
sg-replicate runs the Sync Function on the target, and expiry is considered a local property that can be updated via the Sync Function expiry().
