### ISSUE TITLE
SG Admin Console not creating Walrus DB

### ISSUE THREAD

**Issue by PureRockets** [couchbase/sync_gateway#2066]
When using the 1.3 SG Admin UI, it's not possible to create a Walrus type db for testing. The result for the db name shows in the UI as "undefined". It reproduces each time
![sg_admin](https://cloud.githubusercontent.com/assets/6644594/18365651/66bad934-75c8-11e6-8df6-4c924e09d172.png)

**Comment by adamcfraser** [comment]
I'm assuming this isn't a new issue in 1.3 - I don't know of any recent changes to the admin UI codebase.  Let me know if you think it's a regression - otherwise I expect we'll cover this as part of the 2.0 admin UI improvements.

**Comment by elements-of-boredom** [comment]
Its not only unable to create an admin database. The entire UI has issues anywhere a React event should be bound. I was able to download the code and build with some issues (a key node package was deleted and no longer exists). Basically anywhere <fieldName>.state was referenced changing it to use <fieldname>.getDOMNode() seemed to work. It was like the state updates simply weren't firing for React.

In general the entire Admin UI is unusable. Anywhere a form submit takes place that uses inputs is failing. I agree that based on the repository history its not changed in a year... but it did work in 1.2 and 1.1
