### ISSUE TITLE
Webhook Incorrect Numeric Conversion

### ISSUE THREAD

**Issue by PureRockets** [couchbase/sync_gateway#2067]
Using the following curl command, a document is inserted via the Sync Gateway 1.3 REST API:

curl -X POST localhost:4984/sync-gateway/ -H "Content-Type:application/json" -d "{\"hello\":10002318}"

On the listener system during the Webhook POST, it is observed that "1.0002318e+07" is arriving over the wire. The expectation is that no numeric conversion should occur. This happens every time with larger numeric values.

**Comment by adamcfraser** [comment]
The standard golang json unmarshaller is going to unmarshal as float, which is resulting in this behaviour.  Need to unmarshal with a decoder set to UseNumber() to avoid this.
https://golang.org/pkg/encoding/json/#Decoder.UseNumber

**Comment by adamcfraser** [comment]
Closing based on age.
