### ISSUE TITLE
Update user doc sequence for access-based channel grants

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2068]
Currently we only update the user doc sequence for `/db/_user` updates made through the Admin REST API.  When we update the user doc for access-based changes (either when invalidating or recalculating the user's channels), we don't update the user doc sequence value.
## Problem

This can result in several potential race conditions between the normal sequence buffering, and user doc notifications to the changes feed.  These are more likely on a multi-node Couchbase Server instance under load, where the user doc updates are arriving over the mutation feed either slower or faster than the related access granting docs.

Case 1: one-shot replication
1.  User Bob initially has access to channel A
2. Bob issues one-shot _changes request, gets user context with channels=A
3. Document with seq=100 is written to channel A, granting Bob access to channel B.  
4. Bob's userdoc is updated to set channels=nil (based on 3). 
5. Document with seq=101 is written to channel A
6. Documents 100 and 101 are returned by the changes request, last_seq=101
7. Bob issues another _changes request with since=101, gets user context with channels=[A, B]
8. **Bob doesn't get a channel backfill for channel B, because the since value is greater than the sequence at which Bob was granted access**
## Solution
1. When we recalculate the user's channels, set a new sequence value when the updated user doc is written.
2. Update the timed set for the channel with the new user doc sequence, not the sequence of the granting doc.

This will result in:
- The backfill will be triggered when the user doc is sent over the changes feed.
- The user doc will be included in the sequence buffering, ensuring the changes feed can't run ahead of the backfill.

This has a potential problem, however, related to one-off changes request when the user hasn't authenticated for some time.  The user doc will get updated when the changes request is authenticated, but that user doc update will not be buffered/cached by the time the changes request completes - meaning the user won't get the backfill for any new channels in that initial request - they will need to make a subsequent one-off changes request to see the changes.  This isn't an issue for Couchbase Lite (where continuous or longpoll loop processing would get the change in the next iteration), but is unintuitive behaviour for an ad-hoc changes request.

## Action items

- [ ] Reproduce issue in `DisabledTestPostChangesUserTiming(t *testing.T)`
- [ ] Underlying fix
- [ ] Re-enable `TestUserAccessRace` in integration mode, since it's been marked as "Walrus-only" due to sporadic failures documented in https://github.com/couchbase/sync_gateway/issues/3006

**Comment by Crapulax** [comment]
Yes indeed it looks like what we are facing in #2078. Well spot!

**Comment by Crapulax** [comment]
Reading further your answer feel free to contact us as a customer, We might found together an acceptable solution. We are creative and pragmatic.

**Comment by sethrosetter** [comment]
We are pretty sure we saw this during test fest today using Sync Gateway 1.4-98 (cc) + Couchbase Server 4.5.1. Attached are the logs - https://s3.amazonaws.com/cbmobile-bucket/issues/issue_2068_test_fest/sg_log2.log

**Comment by adamcfraser** [comment]
Good documentation of a live reproduction of this scenario on https://github.com/couchbase/sync_gateway/issues/2340 and https://github.com/couchbase/sync_gateway/issues/2267

**Comment by adamcfraser** [comment]
An intermittent unit test failure looks like it may be related to this issue:

TestPostChangesUserTiming
http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-windows-build/810/consoleFull

**Comment by sethrosetter** [comment]
We are seeing this happen almost every time with the Todo app in 1.5. The steps to repro are:

- Log in with 2 users on different devices (user1 and user2)
- Create a list with user1
- Share with user2
- user2 does not see the list

Removing the channel grant here fixes the backfill race - https://github.com/couchbaselabs/mobile-training-todo/blob/master/sync-gateway-config.json#L196

@adamcfraser is going to provide more details as to why.

**Comment by adamcfraser** [comment]
This is the same race condition described above - the granting document is being replicated to user2 before the user doc reflecting the grant is processed.

The main change in 1.5 that would cause this race to be hit more frequently is the change from DCP to TAP - TAP may have been more likely to batch and send the two updates, while the DCP events are streamed immediately.

The workaround - don't give the user access to the granting document - is sufficient in most cases.  There are some cases where it's useful for the user to get access to the granting document, though - in this case, todo is using it as a way to workaround #264.

**Comment by tleyden** [comment]
> 4. Bob's userdoc is updated to set channels=nil (based on 3).

Shouldn't this be set channels=B (based on 3)?

**Comment by adamcfraser** [comment]
@tleyden At document write time (3), the user doc only has its channels invalidated (set to nil).  The new channel set isn't recalculated until the next time the user object is loaded (or reloaded).

**Comment by adamcfraser** [comment]
Migrated to CBG-792
