### ISSUE TITLE
GetMulti Vs Sync GET method

### ISSUE THREAD

**Issue by mahendran-imaginea** [couchbase/sync_gateway#2072]
Hi,

My main objective is to retrieve more than 4000 records from couchbase , perform some operation and stored again to couchbase. In getMulti method, i can get all the document but while updating (BULK_DOCS) in couchbase some of the documents were not updated because of their rev id got changed. When i tried the same process in syncagateway (by GET to retrieve document) it is working fine but time taken is huge compared to getMulti. Could you please tell me how to achieve same thing in getMulti.

Thanks

**Comment by adamcfraser** [comment]
Direct access to the document would be recommended (with shared bucket access).
