### ISSUE TITLE
_changes feed response is missing sequences when couchbase node down and failover

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2079]
I am using syncgateway 1.3. as per wiki ,syncgateway creates the compound sequence numbers whenever some of sequence numbers are delayed for 5 sec.
i could sequences are missing leading to compound sequence number in _changes feed and not available to clients till syncgateway restarts. After restart , there will not be compound sequence  and also missing sequence numbers will be available to clients. 

below is the scenario to reproduce
1. CB 3 nodes, 1 syncgateway node
2. Documents insertion continuously with some delay
3. Made one of couchbase node down and did failover after some time 

below is logs for compound sequence
,{"seq":"1687","id":"3591","changes":[{"rev":"1-235ed910c6b78eeb1c7b7dd2f8c533f5"}]}
,{"seq":"1688","id":"3342","changes":[{"rev":"1-22de77a79c5f35de80846c7e0e58ac2c"}]}
,{"seq":"1689","id":"3592","changes":[{"rev":"1-97b72acb60d1bee9b49b354dcb899bc3"}]}
,{"seq":"1690","id":"3343","changes":[{"rev":"1-0e2cab6f664e2e272af93f5d06a5327b"}]}
,{"seq":"1691","id":"3593","changes":[{"rev":"1-ac4cccbd8e25fa68bf44bd8de90a4dfb"}]}
,{"seq":"1692","id":"3344","changes":[{"rev":"1-d3aafdbd08c7788bb2a6b5ffe7342a34"}]}
,{"seq":"1693","id":"3594","changes":[{"rev":"1-e82605eb80d4eba4ba3b5b2ad787e0d0"}]}
,{"seq":"1693::1696","id":"3347","changes":[{"rev":"1-14b2258596ee21ed6b5de0d85eab6d71"}]}
,{"seq":"1693::1697","id":"3598","changes":[{"rev":"1-4e9e9acc336d7c531847c3b65d80e836"}]}
,{"seq":"1693::1700","id":"3600","changes":[{"rev":"1-d9c14ce980d638e2f38e4950d236bea9"}]}

**Comment by adamcfraser** [comment]
What are the 'missing' sequence numbers in this scenario, that are available after restart?

**Comment by adamcfraser** [comment]
Looks like this may be related to the scenario described in  https://forums.couchbase.com/t/syncgateway-databases-offline/7847/6

which is already filed as https://github.com/couchbase/sync_gateway/issues/1709

**Comment by ArihantRk** [comment]
Thanks @adamcfraser for quick reply, scenario is same but causing issue is different. there are some of sequences are missing in _changes feed Example: seqNo:1694 in above is not listed in _changes. hence causing the compound sequence numbers.
but this will be available after restart of syncgateway process and there wont be compound sequence number.
This is in-turn causing sg-replicate to miss replication of documents since sg-replicate act as client.

**Comment by adamcfraser** [comment]
It does still seem like a problem related to resumption of the TAP feed after node failure.  I would expect that after the skipped sequence timeout (defaults to 1 hour, but configurable using max_wait_skipped, [see config docs here](http://developer.couchbase.com/documentation/mobile/current/develop/guides/sync-gateway/config-properties/index.html#story-h2-8)) the missing sequence would be seen and the changes resume.  

However, I'd still like to better understand the the feed behaviour.  Can you share your SG logs in a gist?

**Comment by ArihantRk** [comment]
please have look of syncgateway log
https://gist.github.com/ArihantRk/c92b8da45e9c189f5fe0fc052eb5be75

skipped sequence will be seen after restart of syncgateway. 
also what could be the reason for missing sequences though document is inserted successfully into couchase.

**Comment by ArihantRk** [comment]
Could see below observation
1. compound sequence number after node down
2. _changes request gets hung after node fail-over
3. both **compound sequence number** and **_changes** request gets hung resolved after restart of syncgateway

**Comment by ArihantRk** [comment]
@adamcfraser , looks like syncgateway restart is mandatory whenever one of couchbase node goes down. and this is very expensive for production environment and also down time to clients.
can you please helt us on this?

**Comment by adamcfraser** [comment]
A question about the sequences that don't show up on the changes feed - can you see documents with these sequences in the backing bucket?  I'm trying to work out whether these were sequences that had been allocated by Sync Gateway before restart and never used, or whether valid documents were actually written using these sequences.

**Comment by ArihantRk** [comment]
@adamcfraser ,Sorry for delay, i could see the document exists in couchbase bucket sequences that does not show up on changes feed. clients will be missing these documents from sync.
not sure, seems like issue in syncgateway cache .

**Comment by adamcfraser** [comment]
Can you share the _sync metadata for one of the docs that's missing on the changes feed but exists in the bucket?

**Comment by ArihantRk** [comment]
will try to reproduce and share the data.

**Comment by ArihantRk** [comment]
@adamcfraser ,Issue seems like related to https://github.com/couchbase/sync_gateway/issues/2197

**Comment by adamcfraser** [comment]
I think the skipped sequences aspect of this issue will have been addressed by https://github.com/couchbase/sync_gateway/commit/2206672e54cd0df1ea66fc81513b41aed314cb1d, and will track the failover aspect on #2197.
