### ISSUE TITLE
Couchbase Health check commands

### ISSUE THREAD

**Issue by Gnanodhar** [couchbase/sync_gateway#2089]
I am currently using the following sample health check commands to determine if Couchbase is running ok on the ports. A 404 response or any other error would indicate that it’s down.  Let me know if you have any more ideas.

**Comment by tleyden** [comment]
@gnanodhar did you forget to include the sample health check commands?

**Comment by Gnanodhar** [comment]
Oh my bad here are those 

curl http://hostname:8091/pools
curl http://hostname:8092

**Comment by tleyden** [comment]
Can you give more context about your problem?  

Going to close this issue because it doesn't seem like a Sync Gateway bug, but feel free to continue the discussion here!

**Comment by ryanmickler** [comment]
Node Status Check
```
#!/bin/bash
res=$(curl -s -u user:pass -X GET http://127.0.0.1:8091/pools/default  | jq -r '.nodes | map(select(.thisNode == 'true'))[0] | .status')
if [[ "$res" == "healthy" ]]; then
  exit 0
fi
exit 1
```
