### ISSUE TITLE
Monitoring scripts

### ISSUE THREAD

**Issue by Gnanodhar** [couchbase/sync_gateway#2091]
How to write a Scripts for the monitoring (Sync Gateway and Couchbase Cluster), mainly focusing on 
- error log 
- XDCR
- Health check (8091 is responding)
- high i/o, cpu (90% Critical, 80% warning)
- others

I'm new to Couchbase, Any suggestions please.

**Comment by adamcfraser** [comment]
This type of question is more appropriate for the Couchbase Forums - please raise it there:
https://forums.couchbase.com/
