### ISSUE TITLE
Update gateload to push to statsd directly

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2093]
From @adamcfraser 

> I think it would be pretty straightforward to enhance the code to pipe existing expvars straight to statsd, instead of going through the HTTP endpoint - particularly by using expvar.Do https://golang.org/pkg/expvar/#Do

**Comment by tleyden** [comment]
Statsdclient: see [sgload](https://github.com/couchbaselabs/sgload/blob/master/sgload/sg_datastore.go#L19) codebase

**Comment by ajres** [comment]
[PR](https://github.com/couchbaselabs/gateload/pull/4) is in gateload repo
