### ISSUE TITLE
Buffering causing latency in changes feed

### ISSUE THREAD

**Issue by paulharter** [couchbase/sync_gateway#2094]
I have just been testing the latency of the changes feed to round trip adding a document and then longpolling for the change. I found it was much slower than I had expected, roughly 100 times slower than couchdb.

After doing some tests it looks like something is ticking in SG. Changes seem to be buffered and flushed every two seconds. The unexpected latency in the changes feed appears to be caused by this buffering and not by computation or io.

In my tests the latency varies between roughly 0.05 - 2.0 for a random request. The latency of successive longpoll changes requests are deterministic if timed from the return of the previous request. They always return 2.0 seconds after the previous one.

I'm testing with:

==== Couchbase Sync Gateway/1.3.0(274;8c3ee28) ====
Couchbase Server Version: 4.5.0-2601 Enterprise Edition (build-2601)

I raised this on the forum and Jens said he thought a deliberate use of a timer was unlikely so I'm raising it here. 

Looking at the code it appears to be waiting for change notifications from the tap feed.

I'm not sure if this counts as a bug or not. It may be an unavoidable part of how change notifications are collected from Couchbase but if these changes could be continually streamed as they arise or the 2 second buffer reduced it would improve SG's latency considerably.

P

**Comment by adamcfraser** [comment]
There's an old issue for this - based on the analysis on that ticket, I believe the 2-second chunking you're seeing is caused by something on the write side, not the read side.  

Additional details on https://github.com/couchbase/sync_gateway/issues/616.

Closing this - if you want to dig into this further, we can do so on #616.
