### ISSUE TITLE
Descending=true not working if limit is set when querying view with REST API

### ISSUE THREAD

**Issue by Stephanevincenza** [couchbase/sync_gateway#2095]
Hello,
If I query curl -vX GET http://10.4.0.2:4985/ck/_design/message/_view/all?limit=5
It works, I get all "messages"
curl -vX GET http://10.4.0.2:4985/ck/_design/message/_view/all?descending=true
It works , I get all messages in reverse order (the key is a timestamp)
But if I curl -vX GET http://10.4.0.2:4985/ck/_design/message/_view/all?limit=5&descending=true, descending is not working. I get the five first "messages" like without descending=true, ordering isn't applied............
And if I curl -vX GET http://10.4.0.2:4985/ck/_design/message/_view/all?descending=true&limit=5, I get all the "messages" like without "limit=5", limit is not applied..........

VERSION.txt says 1.3.0-274 for the gateway.

**Comment by adamcfraser** [comment]
@Stephanevincenza What type of server are you connecting to?  Couchbase Server, or a test walrus instance?

**Comment by Stephanevincenza** [comment]
It's a couchbase server. (Version: 4.1.0-5005 Community Edition (build-5005))

**Comment by Stephanevincenza** [comment]
I join you a file with the output of commands.
[untitled text2.txt](https://github.com/couchbase/sync_gateway/files/499564/untitled.text2.txt)

**Comment by Stephanevincenza** [comment]
I'd just like to precise that's this strange behavior appears with each view.......

**Comment by adamcfraser** [comment]
I think you may just have a curl issue - does it work if you enclose the full URL in single quotes?

`curl -vX GET 'http://10.4.0.2:4985/ck/_design/message/_view/all?limit=5&descending=true'`

**Comment by Stephanevincenza** [comment]
Yes ! It works ! Many thanks....
