### ISSUE TITLE
Memcached, CPU utilization is high 

### ISSUE THREAD

**Issue by Gnanodhar** [couchbase/sync_gateway#2100]
When I use the command top in one of the couchbase server, here is the response.

  PID    USER      PR  NI  VIRT   RES   SHR S %CPU %MEM    TIME+  COMMAND

31684 couchbas  20   0 9074m 844m  11m S 2482.5  0.2  25863:02 cbq-engine
23371 couchbas  20   0 6736m 3.8g 7172 S 135.6  1.0   5922:41 memcached
31669 couchbas  20   0 14.8g 7.2g 9760 S 135.3  1.9  11362:44 indexer
22560 couchbas  20   0 5214m 1.5g 3612 S 68.0  0.4   8318:08 beam.smp

Memcached is high this resulting high CPU Utilization to that server almost 92 % in Admin console.
Can you help me how to get rid of this.

**Comment by adamcfraser** [comment]
This is a Couchbase Server question, not a Sync Gateway question, and so should be directed towards one of the resources here:
http://developer.couchbase.com/support
