### ISSUE TITLE
Protect against empty doc body in handlePutDoc

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2102]
In handlePutDoc, check the body returned by h.readDocument() to ensure it's non-nil.  If it's nil, return error (before we panic trying to set the rev on the body).

**Comment by agonyou** [comment]
Per the prospect:

Here's how to send the sync_gateway into a panic:
1. Create a document. 
2. Update it with curl passing "null" for the json object:

curl -X PUT -H "Content-Type: application/json" -d null http://localhost:4984/db/aa54c1543d00f242612bea7b5f4960afrev=?1-cd809becc169215072fd567eebd8b8de

FYI "null" is what you get if you call json.dumps(None) in python

Obviously there was an underlying bug on our side but the handling in sync_gateway was super confusing. It may be that the whole thing was edge conditions in our conflict resolution code that caused us to (inadvertently) send "null" for the doc.
