### ISSUE TITLE
SGW 1.3.1 has random crashes with MacOS Sierra

### ISSUE THREAD

**Issue by pasin** [couchbase/sync_gateway#2104]
I have seen this several times during running CBL iOS Unit Tests. I haven't seen this behavior before using MacOS Sierra.

SGW Log:
https://gist.github.com/pasin/2b37499abbcedfeb7b94ab1d152cc033

SGW: 1.3.1 Official Release

**Comment by pasin** [comment]
I haven't seen any crashes when using [1.4.0-8](http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.4.0/1.4.0-8).

**Comment by pasin** [comment]
Reopen the issue so that SGW team can at least have a quick look into the issue.

**Comment by adamcfraser** [comment]
I expect this will be addressed by https://github.com/couchbase/sync_gateway/issues/2098.

**Comment by pasin** [comment]
Thanks @adamcfraser. Close the issue now.
