### ISSUE TITLE
missing sequences in _changes feed causing sg-replicate missing documents replication

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2108]
_From @ArihantRk on September 12, 2016 13:16_

I have below setup and scenario
CB version 4.1 and syncgateway 1.3
**site-1**
CB 3 nodes, sync 1 node
**site-2** 
CB 1 node sync 1 node
Replication on both sites between buckets.
1. started inserting documents to site-1 sync-gateway and made one of site-1 couchbase(does not have sync:seq documents) down
2. documents are inserting to other live nodes except down node
3. fail over the down node
could able to see that bulk get from remote replication operation was partial, some documents are not fetched in bulk get(assuming some of them in down node), hence these documents are not replicated to other site and remote local document is updated to latest seq number

_changes feed has compound sequence numbers and missing some of sequence numbers

i am sure partial bulk post has taken care. 
does partial bulk get also taken care?
can all operations bulk get or rev diff have count matching requested and response so that no docs missed from replication.
and do we have any recovery procedure for this?

_Copied from original issue: couchbaselabs/sg-replicate#40_

**Comment by tleyden** [comment]
> Replication on both sites between buckets.

Just to clarify, you are only using sg-replicate and not XDCR correct?

**Comment by tleyden** [comment]
> and made one of site-1 couchbase(does not have sync:seq documents) down

So you mean you are killing the couchbase process abruptly or taking it off the network?

Btw, what is your replica count set to?

**Comment by tleyden** [comment]
> could able to see that bulk get from remote replication operation was partial,

Can you give exact details on this?  A concrete example with actual vs expected would be useful.  If it's more than 20 lines of output, please use a [gist](gist.github.com)

**Comment by tleyden** [comment]
> can all operations bulk get or rev diff have count matching requested and response so that no docs missed from replication.

So you are seeing `bulk_get` requests where only _some_ of the docs are returned, and the replicator treats them all as returned?  This is probably enough info for us to write a unit test for, but if you have any sample output, that would be helpful.

**Comment by tleyden** [comment]
_From @ArihantRk on September 13, 2016 5:55_

Am using sg-replicate for replication(using config file in 1.3)
stopping using /opt/couchbase/etc/couchbase_init.d stop
replicate count is 1

could able to see is not bulk_get,  fetch _changes feed is missing some sequences during failover. below is the _changes feed on source site. here ID 122 and 127 are not listed but could see that documents are inserted in couchbase. 
,{"seq":"82","id":"115","changes":[{"rev":"1-3e8f8bb7a381123076eb5ce763aa1ee6"}]}
,{"seq":"83","id":"116","changes":[{"rev":"1-11a853719aa1976d033d62606cdeee0b"}]}
,{"seq":"84","id":"117","changes":[{"rev":"1-73a6b56d736dcafa8964d7ca1e52bfac"}]}
,{"seq":"85","id":"118","changes":[{"rev":"1-748e12de79ec0b69739f37c306b018e7"}]}
,{"seq":"86","id":"119","changes":[{"rev":"1-e15af0a6d0a005c1c7161a3efe93f881"}]}
,{"seq":"87","id":"120","changes":[{"rev":"1-d08f06071d63db7c2d47369a61637621"}]}
,{"seq":"88","id":"121","changes":[{"rev":"1-71e4712f0f49e127a6ae64a4ae696b57"}]}
,{"seq":"88::90","id":"124","changes":[{"rev":"1-7dc450efeefc7e01eefb008edf071ce3"}]}
,{"seq":"88::92","id":"128","changes":[{"rev":"1-98b084f3e4d2c12e9280ec3902b812bd"}]}
,{"seq":"88::93","id":"131","changes":[{"rev":"1-eba3e101c075c8109bc017c2bfbad72f"}]}
,{"seq":"88::94","id":"132","changes":[{"rev":"1-d94ed3b15165c56b395f70206fd2e079"}]}
,{"seq":"88::96","id":"137","changes":[{"rev":"1-57ff41b11696c07be2b8e3957d9c64a2"}]}
,{"seq":"88::97","id":"138","changes":[{"rev":"1-087bc93597d7ee313527c6a6bd3c222a"}]}
,{"seq":"88::100","id":"143","changes":[{"rev":"1-16eb850434dd32b1a3062397ae73e248"}]}
,{"seq":"88::101","id":"145","changes":[{"rev":"1-4b15bd925e5e6bd9e643ae1515ed6352"}]}
,{"seq":"88::102","id":"146","changes":[{"rev":"1-6a530acc6d4d71bc991824957aec1390"}]}
,{"seq":"88::108","id":"154","changes":[{"rev":"1-b4d32b8496de6607d32f202f0dd7e7f1"}]}
,{"seq":"88::109","id":"155","changes":[{"rev":"1-14f88b72abb704b2c5d113321964fa60"}]}
,{"seq":"88::110","id":"156","changes":[{"rev":"1-f59f6e2793d96074ccf15a28fc84521a"}]}

please find the below for syncgateway,sg-replicate config and sg-replicate logs
https://gist.github.com/ArihantRk/14036f3f9af7a5f18f66765f1d08a93d/revisions

**steps to reproduce:**
**site-1**
CB 3 nodes,sync 1 node, sg 1 node
**site-2** 
CB 1 node sync 1 node, sg 1 node
Replication on both sites between buckets.
1. started inserting documents continuously with delay of 1 sec to site-1 sync-gateway 
2. make one of site-1 couchbase(does not have sync:seq documents) down
3. fail over the down node

**Comment by tleyden** [comment]
_From @ArihantRk on September 13, 2016 12:0_

looks like _changes feed has compound sequence numbers due to some missing sequences. since sg-replicate acts as a client , hence accepts high sequence number from _changes feed and omitting some of documents in other site .
is my understanding correct?

**Comment by tleyden** [comment]
_From @ArihantRk on September 13, 2016 13:19_

also could see that _changes request was getting hung, restart of site-1 syncgateway resolved the both _changes request getting hung and compound sequence number issue.
what could be reason for missing sequence numbers and _changes request getting hung?

**Comment by tleyden** [comment]
_From @ArihantRk on September 28, 2016 4:40_

@tleyden ,any luck on this?

**Comment by tleyden** [comment]
@ArihantRk sorry, haven't looked into it yet.

@adamcfraser do you have any insight on this?

**Comment by tleyden** [comment]
_From @ArihantRk on September 28, 2016 9:32_

@tleyden @adamcfraser  below warning messages got in logs. And these these sequences were not recovered even after restart of syncgateway.

seems like refresh of cache is needed to handle couchabase node going down.

12:39:50.368007 2016-09-28T12:39:50.368+05:30 WARNING: Skipped Sequence 11235 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the \* channel view.  If it's a valid sequence, it won't be replicated until Sync Gateway is restarted. -- db.(_changeCache).CleanSkippedSequenceQueue.func1() at change_cache.go:220
12:39:50.368040 2016-09-28T12:39:50.368+05:30 Cache:   Querying 'channels' view for "_" (start=#11236, end=#11236, limit=0)
12:39:50.376661 2016-09-28T12:39:50.376+05:30 Bucket: ViewCustom("sync_gateway", "channels", ...) [8.59024ms]
12:39:50.376696 2016-09-28T12:39:50.376+05:30 Cache:     Got no rows from view for "_"
12:39:50.376739 2016-09-28T12:39:50.376+05:30 WARNING: Skipped Sequence 11236 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the \* channel view.  If it's a valid sequence, it won't be replicated until Sync Gateway is restarted. -- db.(_changeCache).CleanSkippedSequenceQueue.func1() at change_cache.go:220
12:39:50.376773 2016-09-28T12:39:50.376+05:30 Cache:   Querying 'channels' view for "_" (start=#11237, end=#11237, limit=0)
12:39:50.384778 2016-09-28T12:39:50.384+05:30 Bucket: ViewCustom("sync_gateway", "channels", ...) [7.973668ms]
12:39:50.384801 2016-09-28T12:39:50.384+05:30 Cache:     Got no rows from view for "_"
12:39:50.384830 2016-09-28T12:39:50.384+05:30 WARNING: Skipped Sequence 11237 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the \* channel view.  If it's a valid sequence, it won't be replicated until Sync Gateway is restarted. -- db.(_changeCache).CleanSkippedSequenceQueue.func1() at change_cache.go:220
12:39:50.384860 2016-09-28T12:39:50.384+05:30 Cache:   Querying 'channels' view for "_" (start=#11238, end=#11238, limit=0)
12:39:50.392386 2016-09-28T12:39:50.392+05:30 Bucket: ViewCustom("sync_gateway", "channels", ...) [7.499645ms]
12:39:50.392413 2016-09-28T12:39:50.392+05:30 Cache:     Got no rows from view for "*"

**Comment by tleyden** [comment]
@ArihantRk how reproducible is this?  what are the steps to reproduce?

**Comment by tleyden** [comment]
@ArihantRk sorry, nevermind the second question -- I see you already posted these!

@sethrosetter we should figure out how to make a functional test scenario for this.

**Comment by tleyden** [comment]
_From @sethrosetter on September 28, 2016 21:22_

@tleyden Sounds good.

**Comment by tleyden** [comment]
_From @ArihantRk on October 3, 2016 13:27_

@tleyden , @sethrosetter any update please...

**Comment by tleyden** [comment]
@ArihantRk We chatted about this ticket in our last sprint planning meeting, and we were a bit confused on whether there were any docs missing from your replication, or whether you just noticed some missing sequence numbers.

Is it possible you can re-describe your issue in the clearest terms possible?  I'm personally having trouble understanding the issue.
1. Exact steps to reproduce, as detailed as possible (what you have so far seems ok, but feel free to expand on it and give more details)
2. Actual behavior ("eg, 100 / 125 docs sync from SG1 -> SG2")
3. Expected behavior  ("eg, all 125 docs sync from SG1 -> SG2")
4. Implications of delta between Actual vs Expected behavior (eg, "Docs are not syncing to target, and therefore do not show up on users' devices")

**Comment by ArihantRk** [comment]
@tleyden ,
I have retested with below setup 

versions:
- CB version 4.1.0
-  and sync-gateway 1.3.1

site-1:
- CB 3 nodes
- SG 1 node, 
- SGR 1 node(SG config file with sg-replication config merged)

site-2: 
- CB 3 nodes
- SG 1 node
- SGR 1 node(SG config file with sg-replication config merged)

here replication is between sg-replicate as sg-replicate node also has syncgateway configuration(sync function) with replication configuration.

hence each sg-replication nodes does _changes feed locally and replicates to another sg-replicator

below is my replication config in sg-replicate node

**site-1**

```
"replications":[
   {
               "replication_id":"continuous-147-144",
               "source": "ptxdata",
               "target": "http://10.0.29.144:4985/ptxdata/",
               "continuous":true
        }]
```

**site-2**

```
"replications":[
   {
               "replication_id":"continuous-144-147",
               "source": "ptxdata",
               "target": "http://10.0.29.147:4985/ptxdata/",
               "continuous":true
        }]
```

below is the scenario executed
1. started inserting continuously documents to site-1 sync-gateway and while insertion in progress, made one of site-1 couchbase(does not have sync:seq documents) down
2. as expected, documents are inserting to other healthy nodes except down node
3. after timeout of 60 seconds, fail over the down node
4. stopped the documents insertion after 2 minutes of fail over
5. actual documents inserted in site-1 is 5200 but could see that in 5095 in site-2. all documents are not replicated from site-1 to site-2.

this behavior is seen when couchbase node goes down and also _changes feed has compound sequence number.

documents are not syncing to target by sg-replicator.

so sg-replicator is missing sequences from _changes feed though the document having missing sequence number exists in couchbase. 

hope this details helps you,

**Comment by tleyden** [comment]
@ArihantRk thanks!  That is making more sense now.  I will discuss this with folks and get back to you.

**Comment by sethrosetter** [comment]
This branch adds support for rebalance in / out, may be useful - https://github.com/couchbaselabs/mobile-testkit/pull/616

**Comment by tleyden** [comment]
Might be related to #2079

**Comment by tleyden** [comment]
@sethrosetter let's plan to coordinate to design the functional test for this

**Comment by djpongh** [comment]
Asked QE to write a test to verify if this is still happening (https://github.com/couchbaselabs/mobile-testkit/issues/1469). QE will re-open this issue if it is.
