### ISSUE TITLE
sg-replicate stats are incorrect when calling bulk_docs with attachments

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2110]
_From @tleyden on June 20, 2016 23:25_

Currently in `replication_state.go`

```
        // update stats:
        // TODO: is this accurate when some of the docs had attachments and still need to be pushed?
        r.Stats.AddDocsWritten(uint32(len(r.Documents)))
```

That should probably be:
- `r.Stats.AddDocsWritten(uint32(len(r.Documents)))`
- within `go r.pushAttachmentDocs()` should update more stats

_Copied from original issue: couchbaselabs/sg-replicate#37_

**Comment by adamcfraser** [comment]
Closing based on age.
