### ISSUE TITLE
sg-replicate: Review go-httpclient dependency

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2111]
_From @adamcfraser on March 31, 2016 22:17_

Remove the dependency on go-httpclient (replace with the built-in http.Client timeout handling), as long as the built-in handling covers all the use cases.

_Copied from original issue: couchbaselabs/sg-replicate#22_

**Comment by adamcfraser** [comment]
Closing - will be addressed in Hydrogen.
