### ISSUE TITLE
sg-replicate: allow since sequence to be provided manually

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2113]
_From @jchris on October 21, 2015 18:47_

This would allow new replicas to do a multi pass operation, where recent data is replicated first, and then ancient data is backfilled. Maybe useful in applications with a time based working set.

Also sugar for setting it to zero would be handy, as a way of backfilling old replicas that didn't start at zero.

This would also be a workaround for bugs that might result from thinking someone else's checkpoint is ours. From the readme: "targetCheckpointAddress needs to take more things into account when generating checkpoint address."

_Copied from original issue: couchbaselabs/sg-replicate#14_

**Comment by tleyden** [comment]
Currently to set the remote checkpoint to 0, or to another value, you would manually need to reset the remote checkpoint

**Comment by adamcfraser** [comment]
Closing based on age.
