### ISSUE TITLE
Sum up of issues open about missing documents during replication

### ISSUE THREAD

**Issue by Crapulax** [couchbase/sync_gateway#2117]
Hello,

I create this issue to regroup the different issues created ( #1865 , #2074 , #2085, #2078). I will close them as a consequence.
In short, for different reasons, we can lose documents till and including with SG 1.3.1 for two reasons:
- the one describe by Adam in #2068 
- doc arrives late in the cache (race condition)

Adam,
1- I did a correction that is fully satisfactory from a functional view point 3 weeks ago for above (no more doc lost).
The problem is that I did that correction in two steps. Concretely I did something not working first and build another solution working on top of it. So it cannot be used without rework. It would require one day of clean up that I currently do not have.
2- it would have been impossible to do 1- without the tests scripts I built. I had to fine tuned the algorithm to reach what I have today. Note also that without adding some traces mainly the to(user) it is a pain to analyze logs.

My questions now:
1- Do you want my test scripts? I need to clean them a bit but I can take some time do so. If you confirm that you will use them.
2- Do you want the fix that I did as it is? Would you consider it seriously if I clean it (not before a few weeks). Or you prefer to make it on your own?

In all cases I would like to help if I can. If you want me to make some testing of your correction I am fine but please put the user in changes traces. With the added logs I have it is possible to figure out what is going wrong in 1mn as I can grep the user in error with all needed data.

All the best,
Steve

**Comment by adamcfraser** [comment]
Hi Steve,

Thanks very much for the update, and the details you've provided on this.  The user information on the changes logging makes sense, and I'll include that in any case.

The information I'm missing at this point is what was done in the second part of your fix as described above - in particular what's included there that's not in the current PR associated with #1865.  If it's easiest, you can just put up a PR based on your existing branch with a high-level description of the two rounds of changes you made, and I'll take a look.

For the test scripts - I have a semi-ported version of your scripts that I was using for validation, but wasn't getting exactly the same results you were describing.  I think some of that was down to environment - you were getting relatively high latency between Sync Gateway and Couchbase Server in several runs, and I think that helped to uncover some race scenarios.  I'd still be interesting in reviewing your final scripts (cleaned up or not), so if you want to share those in a gist, I'll take a look.

Thanks.

**Comment by Crapulax** [comment]
Hello Adam,

This is fine, let's go that path. Today I will have no time but you will get feedback on coming days.

**Comment by adamcfraser** [comment]
Have merged components of this fix (as discussed on #1865) with PR #2211.  If you've got any update on pending issues, please let us know.

**Comment by adamcfraser** [comment]
Closing based on age - many enhancements in this area since 1.4.0.
