### ISSUE TITLE
1.4.0-10 Reporting wrong version

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2121]
http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.4.0/1.4.0-10/couchbase-sync-gateway-community_1.4.0-10_x86_64.tar.gz

```
http://localhost:4984
```

```
{
"couchdb": "Welcome",
"vendor": {
"name": "@PRODUCT_NAME@",
"version": 1.4
},
"version": "@PRODUCT_NAME@/1.4.0(10;843cf2a)"
}
```

**Comment by sethrosetter** [comment]
@michaelkwok is this a build issue?

**Comment by adamcfraser** [comment]
@ajres This looks related to your recent commit - can you review?  Is there a pending build change?

**Comment by ajres** [comment]
Needs this [gerrit ticket](http://review.couchbase.org/#/c/68225/) merging, I have slack'd @michaelkwok

**Comment by tleyden** [comment]
Closed via https://github.com/couchbase/build/commit/388ec72a70fc0925823d726609a209201052567b

**Comment by sethrosetter** [comment]
Still seeing this with 1.4.0-13

**Comment by michaelkwok** [comment]
The gerrit ticket has been merged.  I kicked off a new build #14 which should pickup this change.

**Comment by sethrosetter** [comment]
Still broken on 1.4.0-14

http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.4.0/1.4.0-14/couchbase-sg-accel-enterprise_1.4.0-14_x86_64.tar.gz

```
{
"couchdb": "Welcome",
"vendor": {
"name": "@PRODUCT_NAME@",
"version": 1.4
},
"version": "@PRODUCT_NAME@/1.4.0(14;4262be5)"
}
```

**Comment by sethrosetter** [comment]
This is a functional test blocker

**Comment by sethrosetter** [comment]
This is still an issue with `1.4.0-15`
