### ISSUE TITLE
Stream processing for bulk docs

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2123]
Currently bulk docs has to load and parse the entire JSON request body before processing document.  This can result in temporary memory spikes for Sync Gateway when clients send large payloads.   This can be protected against via load balancer configuration, but ideally Sync Gateway would be able to process the incoming request as a stream.

It's possible to use json.Decode and json.Token to stream the incoming payload format today, but there are a few issues:
1. The `new_edits` flag is curently defined in the payload body, as a peer to `docs`.  In cases where the `docs` element appears before `new_edits` in the payload, Sync Gateway won't know the value of the flag when it's trying to stream and write documents.
2. Currently Sync Gateway allocates a block of sequences via a single incr operation, based on the number of docs in the request.  Stream processing will not know how many docs are in the request.  Sync Gateway could do it's own batching (with limits based on batch size in bytes) to avoid the 'one incr per write' overhead.

If we end up needing to change the API signature (to support new_edits as a query string parameter, say), it might be worth evaluating other alternatives, including multipart requests.

**Comment by snej** [comment]
That's a good point about the ordering of the keys in the dictionary.

Replication always uses `new_edits=false`, because it's transferring existing revisions.

**Comment by adamcfraser** [comment]
Addressed in 2.0 replication protocol.
