### ISSUE TITLE
sg_accel packages should use example config from sync-gateway-accel repo

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2139]
sg_accel packages should use examples/basic_sg_accel_config.json from sync-gateway-accel repo

Currently it uses the one from the sync_gateway repo which will cause sg_accel to panic on startup.

**Comment by ajres** [comment]
This will require a change the SG build scripts, to copy over the SG_ACCEL example configs on top of the Sync Gateway configs.

`scripts/jenkins/mobile/sgw_unix_build.sh`

and

`scripts/jenkins/mobile/sgw_windows_build.bat`

**Comment by ajres** [comment]
@michaelkwok has taken on implementing this change to the build scripts.

**Comment by michaelkwok** [comment]
I have made all necessary changes and tested.
