### ISSUE TITLE
Disable basic auth unless SSL is enabled

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2143]
To encourage best practices, should we default Sync Gateway to disable basic auth unless SSL is enabled?

The main concern would be whether this is a barrier to initial adoption/uptake, as users would need to explicitly set a flag to start local testing.

**Comment by adamcfraser** [comment]
This would also need to disable session auth solely based on name/password in the body.

**Comment by rajagp** [comment]
As pointed out, I believe that this would be an issue with adoption , development and testing. In fact, our Travel sample (and probably many more) workshop/tutorial will break . As an example,  for travel sample,  expecting the users to configure their sync gateway with ssl certs will only make the already tedious installation process even longer(not to mention that our right scale cloud sandbox environment  would need to be updated as well to support certs ...)-  

I understand the motivation for this but perhaps we can make this configurable ( of course, that would not be the same but by default disallow basic auth  and users should specifically enable this ...so at least its an opt in so users are aware of consequences).

**Comment by adamcfraser** [comment]
Closing based on the above.
