### ISSUE TITLE
SG build job broken

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2145]
@michaelkwok. Jenkins does not not seem to be building latest sync_gateway anymore - http://mobile.jenkins.couchbase.com/job/sgw-unix-build/

**Comment by tleyden** [comment]
@michaelkwok there has been some changes to the Sync Gateway build process:
- https://github.com/couchbase/sync_gateway/commit/1cf0399c4d1f7593178706366cffba300821844f
- https://github.com/couchbase/sync_gateway/commit/4262be526334f4cc880b55febb4e541c18516e59

It's possible that one of these changes is breaking the Jenkins job

**Comment by michaelkwok** [comment]
Failure due to network issue.  All working now.
