### ISSUE TITLE
syncgateway inconsistency behavior when couchbase nodes goes down

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2146]
i am having below setup 
3 CBS nodes, 1 sync-gateway node

I am getting below outputs, when 2 of couch-base nodes goes(service down or node down abruptly)
1. sometime sync-gateway will be running with one node (having sync:seq) documents
2. No response from sync-gateway to any request(request gets hang or timeout). 
3. sometime sync-gateway goes down by process

does sync-gateway not have consistent behavior when couch-base nodes goes down?

what is the behavior of sync-gateway when couch-base cluster goes down(cluster nodes -1 nodes)?

**Comment by adamcfraser** [comment]
Do you have replicas configured for your Couchbase Server nodes, and are those replicas still available in this scenario?

If Sync Gateway isn't able to access a subset of documents in the Couchbase Server bucket because there aren't any nodes serving those documents, I would expect the type of issues described.

**Comment by ArihantRk** [comment]
@adamcfraser , @djpongh 
we have set replica=1
when 2 nodes goes down at same time. it means cluster goes down.  no fail-over will be enabled as 2 nodes down in 3 node cluster
we are experiencing different behaviors from sync-gateway for same test performed multiple times.
1. sometimes sync-gateway responds to REST requests. 
2. sometimes, all REST requests(read and write) are getting timeout, no response from sync-gateway. No information in logs as well.

i would expect sync-gateway should be able serve documents which exists in healthy node available or sync-gateway service down as it is cluster down or one behavior is consistent
also sync-gateway does not respond(request getting timeout) even when making 2 nodes up and full cluster healthy.  sync-gateway needs restart to get sync-gateway become operational.

hope this info helps in understanding issue.

**Comment by adamcfraser** [comment]
There are a number of scenarios that would prevent retrieval of documents from the healthy node, such as inability to authenticate when user/session documents on are the failed node.  In this type of server failure, it's expected that you will need to take Sync Gateway offline, and bring it back online when your Couchbase Server is in a healthy state.  This could be done via the Admin API, or by restarting the Sync Gateway process.

What version of Sync Gateway are you running?  If the failed Couchbase server nodes result in a dropped mutation feed, I'd expect Sync Gateway 1.3.0 or higher to switch itself to an offline state.

**Comment by ArihantRk** [comment]
@adamcfraser ,currently we are using syncgateway 1.3.1 and  we don't have user/sessions documents. we have used sync-gateway admin admin rest api to insert documents. its nust normal documents without users.
After couch-base nodes(majorly >=2) failure, we could see that REST API requests are getting timeout. sync-gateway does not responsive to REST queries. we are not able set the syncgateway offline as requests getting timeouts

**Comment by adamcfraser** [comment]
If you've got Sync Gateway logs associated with the timeout, post a linked gist here and I can provide more details on why those requests are timing out.  

I expect the conclusion will be the same - in this situation, you'll be required to restart the Sync Gateway process.

**Comment by ArihantRk** [comment]
@adamcfraser , sync-gateway does not log for any requests. request timeout is provided from client side. requests gets hang on removing timeout. 
No log information from syncgateway.
