### ISSUE TITLE
changes_feed_limit is not taken into account in sg-replicate configuration

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2147]
i am using below sg-replicate config

"replications":[
   {
               "replication_id":"continuous-147-144",
               "source": "ptxdata",
               "target": "http://10.0.29.151:4985/ptxdata/",
               "changes_feed_limit":300,
               "continuous":true
                                                           }],

but could able see that limit=50 instead of 300. changes feed limit is not taken into account for fetching document revisions.
logs below
17:18:03.529350 2016-10-15T17:18:03.529+05:30 HTTP+: #3464:     --> 200 OK  (0.0 ms)
17:18:03.550098 2016-10-15T17:18:03.550+05:30 HTTP:  #3465: GET /ptxdata/_changes?feed=normal&**limit=50**&heartbeat=30000&style=all_docs&since=179686  (ADMIN)
17:18:03.550165 2016-10-15T17:18:03.550+05:30 Changes+: Int sequence multi changes feed...
17:18:03.550187 2016-10-15T17:18:03.550+05:30 Changes: MultiChangesFeed({_}, {Since:179686 Limit:50 Conflicts:true IncludeDocs:false Wait:false Continuous:false Terminator:0xc8204d52c0 HeartbeatMs:30000 TimeoutMs:300000 ActiveOnly:false}) ...
17:18:03.550404 2016-10-15T17:18:03.550+05:30 Changes+: MultiChangesFeed: channels expand to channels.TimedSet{"_":channels.VbSequence{VbNo:(_uint16)(nil), Sequence:0x0}} ...
17:18:03.550427 2016-10-15T17:18:03.550+05:30 Cache: getCachedChanges("_", {1 0 0 179686 <nil> <nil> %!d(string=) 0 0 0 %!d(string=)}) --> 0 changes valid from #451838
17:18:03.550437 2016-10-15T17:18:03.550+05:30 Cache:   Querying 'channels' view for "_" (start=#179687, end=#451838, limit=50)
17:18:03.557805 2016-10-15T17:18:03.557+05:30 Cache:     Got 50 rows from view for "_": #179687 ... #179736
17:18:03.557838 2016-10-15T17:18:03.557+05:30 Cache: GetChangesInChannel("*") --> 50 rows
17:18:03.557846 2016-10-15T17:18:03.557+05:30 DIndex+: [changesFeed] Found 50 changes for channel *
17:18:03.557888 2016-10-15T17:18:03.557+05:30 Changes+: Sending seq:179687 from channel *
17:18:03.557905 2016-10-15T17:18:03.557+05:30 Changes+: Sending seq:179688 from channel *

**Comment by ArihantRk** [comment]
any luck on above request please.

**Comment by tleyden** [comment]
From the logs it looks like it's working:

```
GET /ptxdata/_changes?feed=normal&limit=50&heartbeat=30000&style=all_docs&since=179686 (ADMIN)
```

and 

```
Cache: Got 50 rows from view for "": #179687 ... #179736
```

Can you open a new issue with the observations that make you think it's not working?  We just added a new template to file issues, which should help figure out what's going on.

Thanks for following up!!

**Comment by adamcfraser** [comment]
@tleyden I think the issue is that the user is trying to specify limit=300 in the config, and getting limit=50.

**Comment by tleyden** [comment]
OK thanks

**Comment by tleyden** [comment]
@ArihantRk I just opened a PR with a fix: https://github.com/couchbaselabs/sg-replicate/pull/46
