### ISSUE TITLE
1.4.0-15 sg_accel package copying wrong binary (sync_gateway) to bin/

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2148]
http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.4.0/1.4.0-15/couchbase-sg-accel-enterprise_1.4.0-15_x86_64.tar.gz

If you extract the .tar.gz, the sync_gateway binary is in the `bin/` folder. 

Expected: the binary should be `sg_accel`.

**Comment by michaelkwok** [comment]
I fixed this few weeks ago but forgot to advanced the commit in the manifest to pickup this change.  All fixed now.
