### ISSUE TITLE
Sync Gateway stops logging after second rotate

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2149]
From https://forums.couchbase.com/t/sync-gateway-1-3-stops-logging-after-second-rotate.

> After the second rotation sync gateway stopped logging to the newly named sync_gateway_error.log and now it is not logging anything as far as I can tell. 

Platform: Ubuntu 12.04
Sync Gateway: 1.3.1

logrotate config:

```
/home/sync_gateway/logs/sync_gateway_error.log {
        dateext
        dateformat -%s
        rotate 20
        size 10k
        missingok
        notifempty
        compress
        postrotate
                /usr/bin/pkill -HUP sync_gateway > /dev/null
        endscript
}
```

This logrotate config was working with Sync Gateway 1.1.

**Comment by adamcfraser** [comment]
@ajres Do you know of any changes in log rotation handling that would account for the issue?  As well, do you see anything incompatible w/ Sync Gateway in that logrotate configuration?

**Comment by alex7egli** [comment]
Note: I am also experiencing issue with fresh install of sync gateway 1.3.1 on Ubuntu 14.04, connected to couchbase server community edition 4.1.1. All logs were going to /home/sync_gateway/logs/sync_gateway_error.log, then logrotate ran and now nothing is being logged to sync_gateway_error.log or sync_gateway_access.log.

Restarting sync gateway fixes logs and they start logging to sync_gateway_error.log again. Restart commands used:
sudo stop sync_gateway
sudo start sync_gateway

**Comment by alex7egli** [comment]
Issue was that I was missing copytruncate in logrotate config file. Adding that fixed the issue.

**Comment by adamcfraser** [comment]
Thanks for the update @alex7egli
