### ISSUE TITLE
The /{db}/\_changes?include_docs=true request shouldn't return _user/user docs

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2151]
When a _changes request with includeDocs=true includes a pseudo-user doc (like _user/username), it attempts to retrieve that document from the rev cache, and logs a warning if it's not found, like:

2016-10-19T08:36:55.902-07:00 WARNING: Changes feed: error getting doc "_user/user_34": 400 Invalid doc ID -- db.(*Database).addDocToChangeEntry() at changes.go:74

We should bypass attempted doc lookup for pseudo-user docs to avoid the log noise.

**Comment by ArihantRk** [comment]
@adamcfraser any impact from these warnings or we can ignore these.

**Comment by adamcfraser** [comment]
Yes, these are harmless - will disable in a future release.
