### ISSUE TITLE
WARNING: Skipped Sequence occurs on a regular base

### ISSUE THREAD

**Issue by K-Leon** [couchbase/sync_gateway#2155]
I'm using Sync Gateway + CB in the following Setup:

**Server 1:** 
1x Couchbase 4.1
1x Sync Gateway hitting CB Instance on this Server

**Server 2:** 
1x Couchbase 4.1 - Replicating Both Buckets
1x Sync Gateway hitting CB Instance on this Server
( Same Config for Both )
### Sync Gateway version

1.3.1
### Operating system

Official Docker Image
### Config file

``` javascript
{
    "interface": ":4984",
    "adminInterface": ":4985",
    "log": ["HTTP", "HTTP+"],
    "compressResponses":false,
    "databases": {
        "bucketsync": {
            "server": "http://COUCHBASEURL:COUCHBASEPORT",
            "bucket": "bucket_sync_gateway",
            "sync": "function(doc) { requireRole(doc.tenant); channel(doc.channels); }",
            "users": {
                "GUEST": {
                    "disabled": true,
                    "admin_channels": ["*"]
                }
            },
            "revs_limit": 20,
            "shadow": {
                 "server": "http://COUCHBASEURL:COUCHBASEPORT",
                 "bucket": "bucket_sync_holder"
            }
        }
    }
}
```

A Loadbalancer distributes Requests between these Servers
### Log output

```
WARNING: Skipped Sequence 1766953 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the * channel view.  If it's a valid sequence, it won't be replicated until Sync Gateway is restarted
```
### Actual behavior

This kicks shortly in after restarting the sync gateway.

Do i have a configuration mistake or is here something fundamental wrong?

**Comment by adamcfraser** [comment]
@K-Leon You shouldn't have bucket shadowing enabled on both Sync Gateway nodes - that could be resulting in CAS update races that might be related to the skipped sequence messages you're seeing. 

A few questions:
1. Are you seeing these messages on an ongoing basis, or only just after startup?
2. Do you actually need bucket shadowing to be enabled?  It's not recommended, and may be contributing to this issue.
3. What's your typical write throughput (writes/second) to the system?

**Comment by K-Leon** [comment]
@adamcfraser Thank you for your time! 
I'm trying to achieve a minimal Failover Setup - so if a node goes down i can continue with the other node (if everything is fine with more nodes). So both buckets are set for replication - the sync gateway one and the shadows bucket. ( basically both instances of sync gateway connect to the same bucket - but on another server. I think this causes this whole mess somehow, but i'm not sure how i can fix this )

1.)  On Startup everything is fine - after a few writes the whole thing goes south. It's not immanent in the App itself - it doesn't seem to prevent functionality but something must be missing somewhere. There's to much data floating around to pinpoint but i get these messages for hundrets of sequences if everything continiues.

2.) Currently we're still experimenting so i have a very low throughput coming from sync gateway. Moth traffic comes from shadowing the main bucket - the clients doing get + insert only right now.

**Comment by adamcfraser** [comment]
I expect this may be resolved by https://github.com/couchbase/sync_gateway/issues/2238 - closing.

**Comment by ArihantRk** [comment]
@adamcfraser , Same issue we are observing in regular basis during traffic. On a high level looks like Mutation feed not received to syncgateway from couchbase before max_wait_pending time.
