### ISSUE TITLE
Downloading sync_gateway community version downloads sg_accel

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2157]
### Steps to reproduce
1.  http://www.couchbase.com/nosql-databases/downloads#couchbase-mobile
2. Download Sync Gateway Community Version
3. This is the packages that is downloaded - couchbase-sg-accel-community_1.3.1.1-1_x86_64.tar.gz

**Comment by tleyden** [comment]
I did Shift Reload and it seemed to fix it .. looks like a browser cache issue.

**Comment by tleyden** [comment]
Disregard my earlier comment about clearing cache ..

**Comment by adamcfraser** [comment]
Just tried this - got couchbase-sync-gateway-community_1.3.1.1-1_x86_64.tar.gz.
