### ISSUE TITLE
Handle channel removal for coalesced feed updates

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2159]
Currently Sync Gateway uses the recent sequences element to identify rapid updates that have been coalesced by Couchbase Server on the mutation feed, and incorporates those sequences into the standard sequence buffering.  

There's still a missing piece, though - Sync Gateway should also be checking for channel removals associated with the coalesced sequences, and adding a channel removal notification to the cache in this scenario.

**Comment by adamcfraser** [comment]
As part of this work, add unit tests for recent sequence handling.  Walrus doesn't coalesce updates on the TAP feed, so would need to replicate this by doing a raw update of the document directly to the bucket.  For this ticket, test would look like:

1. Write rev-1 of a document (as sequence 1), in channels A and B
2. Craft a rev-3 of the document, and write it directly to the bucket with:
  - recent sequences [3,2,1]
  - revision tree including revs 1,2,3
  - Channel A being removed in rev 2
3. Run a changes feed as a user w/ access to Channel A, validate that they get a removal notification for the doc.

Should also add a more generic recent sequence test, which would just validate the recent sequence buffering:

1. Write rev-1 of a document (as sequence 1), in channels A and B
2. Craft a rev-3 of the document, and write it directly to the bucket with:
  - recent sequences [3,2,1]
3. Validate that rev-3 arrives on the changes feed (i.e. changes feed isn't blocked waiting for seq 2 to be buffered)

**Comment by ajres** [comment]
Code changes pushed to branch feature/issue_2159
