### ISSUE TITLE
Add log rotation capabilities into Sync Gateway

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2160]
The current support for the external logrotate command is not usable on Windows.

To provide a cross platform implementation of log rotation we should build log rotation features into Sync Gateway.

The following golang package provides simple logrotation capabilities: https://github.com/natefinch/lumberjack

This can be used with any logging framework that can be initialised with an io.Writer.

To define logrotation properties we will need to update the sync_gateway config, below is a proposal for a new logging configuration section. For a description of the properties in the "rotation" sub document see the lumberjack github project.

```
{
  "deprecatedLog":["*"],
  "deprecatedLogFilePath":"<PATH_TO_LOG_FILE">,
  "logging" : {
    "theworks" : {
      "filename":"<PATH_TO_LOG_FILE>",
      "logKeys":["*"],
      "logLevel":<"debug"|"info"|"warn"|"error"|"panic"|"fatal">,
      "rotation":{
        "maxsize":100,
        "maxage":30,
        "maxbackups":5,
        "localtime":true
      }
    }
  }
}
```

It is possible to define multiple named logging appenders, each appender writes to a unique log file, each appender may include different log keys and log levels. An appender's log file may be continually appended to or the file may be rotated by defining a "rotation" sub document.

The current top level "log" property will be renamed to "deprecatedLog", the current top level "logFilePath" property will be renamed to "deprecatedLogFilePath". The current proposal is to remove these properties in Sync Gateway 2.0.

Behaviour

In the absence of a "logging" sub document:
    If neither "deprecatedLog" or "deprecatedLogFilePath" are defined log entries with the "HTTP" log key will be written to standard out.

If only the "deprecatedLog" property is defined, log entries with the log keys defined in the "deprecatedLog"property will be written to standard out.

If "deprecatedLog" and "deprecatedLogFilePath" are defined log entries with the log keys defined in the "deprecatedLogFilePath" property will be written to standard out.

If a "logging" subdocument is defined the "deprecatedLog" and "deprecatedLogFilePath" properties will be ignored. 

The "logging" subdocument  must contain at least one valid named appender config, config vaidation should fail if this is not the case. 

One appender (only)  may be defined without a "filename" property, in this case the appender will write to the processes "stdout".
 
All other appenders must define a unique logfile name/path duplicate file names/paths should cause config validation to fail.

For each valid appender configuration, log entries that match the defined key and level properties will be written the logfile defined by the appender. 

If an appender contains a "rotation" sub document the logfile will be rotated using the provided configuration.

On non-windows platforms if the Sync Gateway receives a SIGHUP signal:

If there is no "logging" subdocument and the "deprecatedLogFilePath" property is defined the log file handle will be cycled as it is currently.

If the "logging" subdocument is defined, an appender that has no "filename" property defined will take no action .

If the "logging" subdocument is defined, for each appender that has NO "rotation" subdocument defined the log file handle will be cycled as it is currently.

If the "logging" subdocument is defined, for each appender that has a "rotation" subdocument defined call Logger.Rotate() to force a log file rotation.

After rotating, this initiates a cleanup of old log files according to the rotation properties defined for that appender.

**Comment by paulharter** [comment]
Pls make this optional and don't deprecate logging to standard out in v2. I prefer processes not to manage their own logs. If it's going to be kept don't call it deprecated, if you're going to remove logging to standard out this is worse and less flexible for me.

**Comment by adamcfraser** [comment]
@paulharter There will always be an option to log to standard out - it's only the specific location of the existing logging parameters in the config that may be moved/deprecated.

**Comment by paulharter** [comment]
Ok great. Maybe I misunderstood Andrews notes. It looks like in version 2 the only way to specify log level to standard out is by using a key "deprecatedLog" which is confusing if this is supported. Maybe you could make the keys "filename" and "rotation" optional in the logging block and support the current behaviour that way?

If you're working on logging can I vote for syslog support.

**Comment by ajres** [comment]
Added some additional clarification around support for the current behaviour using the new config layout.

**Comment by adamcfraser** [comment]
@ajres A few comments:
1. We need to maintain the 'log' and 'logFilePath' properties with their existing names in the config file for 1.4.  The point of retaining them is for backwards compatibility with existing config files, which would be broken by a rename.  The corresponding struct properties in the code can be prefixed by 'deprecated'.  With the 1.4 release notes we'll indicate that these properties are being migrated into the 'logging' block of the config.
2. I think retaining the 'logFilePath' naming (instead of 'filename') within the logging config makes the migration clearer.
3. I feel like the support for multiple appenders should be decoupled from the initial log rotation enhancements.  What do you think about only supporting a 'default' named appender initially.  That would provide a path to multiple logging options in the future (without changes to the config structure) if we choose to go that route, but can defer those changes until we review the full set of use cases.

**Comment by ajres** [comment]
Updated these notes to reflect feedback.

The current support for the external logrotate command is not usable on Windows.

To provide a cross platform implementation of log rotation we should build log rotation features into Sync Gateway.

The following golang package provides simple logrotation capabilities: https://github.com/natefinch/lumberjack

This can be used with any logging framework that can be initialised with an io.Writer.

To define log rotation properties we will need to update the sync_gateway config, below is a proposal for a new "logging" configuration section. For a description of the properties in the "rotation" sub document see the lumberjack github project.

```
{
  "log":["*"],
  "logFilePath":"<PATH_TO_LOG_FILE">,
  "logging" : {
    "default" : {
      "logFilePath":"<PATH_TO_LOG_FILE>",
      "logKeys":["*"],
      "logLevel":<"debug"|"info"|"warn"|"error"|"panic"|"fatal">,
      "rotation":{
        "maxsize":100,
        "maxage":30,
        "maxbackups":5,
        "localtime":true
      }
    }
  }
}
```

Introduce a new "logging" sub document.

The "logging" sub document must contain a single named logging appender called "default". 

The "default" appender can write to "stdout", write to a single log file or the log file may be rotated by defining a "rotation" sub document.

The current proposal is to remove the top level "log" and "logFilePath" properties in Sync Gateway 2.0.

Behaviour

In the absence of a "logging" sub document:
    If neither top level property "log" or "logFilePath" are defined, log entries with the "HTTP" log key will be written to standard out.

If only the top level "log" property is defined, log entries with the log keys defined in the "log" property will be written to standard out.

If both "log" and "logFilePath" are defined, log entries with the log keys defined in the "log" property will be written to the file defined in the "logFilePath" property.

If a "logging" subdocument is defined the "log" and "logFilePath" properties will be ignored. 

The "logging" subdocument  must contain a single valid appender config with the name "default", config validation should fail if this is not the case. 

The "default" appender may be defined without a "logFilePath" property, in this case the appender will write to the processes "stdout".

If the "default" appender has a "logFilePath" property,  the appender will write to the log file at the path specified.

Log entries that match the appender "logKeys" and "logLevel" properties will be written by the appender. 

If an appender contains a "rotation" sub document and no "logFilePath" appender property is defined  config validation should fail. 

If an appender contains a "rotation" sub document and the "logFilePath" appender property is defined the log file will be rotated using the provided configuration.

On non-windows platforms if the Sync Gateway receives a SIGHUP signal:

If there is no "logging" subdocument and the top level "logFilePath" property is not defined no action is taken.

If there is no "logging" subdocument and the top level "logFilePath" property is defined the log file handle will be cycled as it is currently.

If the "logging" subdocument is defined, and the "default" appender has no "logFilePath" property defined no action is taken.

If the "logging" subdocument is defined, and the "default" appender has no "rotation" subdocument defined the log file handle will be cycled as it is currently.

If the "logging" subdocument is defined, and the "default" appender has a "rotation" subdocument defined call Logger.Rotate() to force a log file rotation.

After rotating, this initiates a cleanup of old log files according to the rotation properties defined for that appender.

**Comment by ajres** [comment]
- [x] Include lumberjack logrotation library in manifest/default.xml
- [x] import lumberjack package into logging.go 
- [x] Add support for new logging config documented on this ticket
- [x] Add logging config validation as described on this ticket
- [x] Initialise loggers with log rotation if configured
