### ISSUE TITLE
Update Homebrew version

### ISSUE THREAD

**Issue by basememara** [couchbase/sync_gateway#2163]
The `sync_gateware` version in Homebrew is `1.2.1`. Can this please be upgraded to the latest `1.3.1` to match production environments using the latest versions?
```
brew upgrade sync_gateway
Error: sync_gateway 1.2.1 already installed
```

**Comment by tleyden** [comment]
Thanks @basememara!  Can you provide more details / links?

This might have been done by a community member...

**Comment by basememara** [comment]
This is the only thing I can find about it:
https://groups.google.com/forum/#!topic/mobile-couchbase/oTzPzD19lws

Looks like @sideshowcoder put it together and perhaps @snej knows more details on what to do from here?

**Comment by sideshowcoder** [comment]
Yes I put this together back in the day, I think updating should be simple as updating the hash and tag here https://github.com/Homebrew/homebrew-core/blob/4fd00963195f326e60faaf33e0c6d78817c5a844/Formula/sync_gateway.rb

**Comment by tleyden** [comment]
I've asked the homebrew folks to remove the sync gateway homebrew formula until we can get this folded into our build / QA / release process

https://github.com/Homebrew/homebrew-core/pull/7727
