### ISSUE TITLE
syncgateway not aware of document purge with _exp set

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2164]
### Sync Gateway version
syncgateway 1.3.1  

### Operating system
redhat 7.0

### Expected behavior
I have inserted document with _exp attribute, document is purged from couchbase after expiration value. 
document purge changes should be show in _changes feed. so that client are in sync with couchbase server

### Actual behavior
What actually happened?
syncgateway is not aware of document purge in couchbase happens after document expiration value. _changes feed does not know document purge happens in couchbase.

### Steps to reproduce
1.  Insert document with _exp attribute
2.  document will be purged after expiration value
3.  _changes will still show document

**Comment by adamcfraser** [comment]
Purge/expiry doesn't update Sync Gateway's in-memory channel cache.  The intended use case is for obsolete documents that normally should not be resident in Sync Gateway's cache.  

Identifying a document's previous sequence and channels (to trigger a cache purge) based on a delete mutation on the server's mutation feed may not be possible.  This enhancement may need to wait until we get XATTR support (currently planned for 2.0).

**Comment by ArihantRk** [comment]
@adamcfraser Is this included in #1658 fix or still open ?

**Comment by bbrks** [comment]
Hi @ArihantRk 

A document purged via TTL/Expiry will be tombstoned and replicated down to Couchbase Lite clients as a delete when using `"enable_shared_bucket_access": true`. These are still visible in changes feeds, but as a delete mutation.

<img width="367" alt="screenshot 2019-01-30 at 13 02 04" src="https://user-images.githubusercontent.com/1525809/51983031-a2194880-248f-11e9-8b43-66be412e10bf.png">

Tombstones are described in more detail here: https://docs.couchbase.com/sync-gateway/2.1/managing-tombstones.html

**Comment by adamcfraser** [comment]
Closing as this case is handled under shared bucket access (as described above).
