### ISSUE TITLE
SimpleFeed.Close() called but not implemented issue with distributed index

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2166]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
1.4.0-26 

### Operating system
CentOS 7

### Config file
```javascript
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://{{ couchbase_server_primary_node }}:8091",
        "data_dir":".",
        "bucket":"data-bucket"
    },
    "databases":{
        "db":{
            "feed_type":"DCPSHARD",
            "server":"http://{{ couchbase_server_primary_node }}:8091",
            "bucket":"data-bucket",
            "channel_index":{
                "server":"http://{{ couchbase_server_primary_node }}:8091",
                "bucket":"index-bucket",
                "writer":{{ is_index_writer }}
            }
        }
    }
}
```

### Log output
https://gist.github.com/sethrosetter/0a12c7afb2d768199ed7e41170ee649e

### Expected behavior
In channel cache mode, POST /db/_online takes the db online

### Actual behavior
In distributed index mode, POST /db/_online does not the db online. Instead, I am seeing the output `SimpleFeed.Close() called but not implemented`.

This causes `test_online_to_offline_changes_feed_controlled_close_continuous` test to fail

See the linked log for the output of the same steps in each mode.

### Steps to reproduce
1. Open mobile-testkit  
```
pytest -s --mode=di --sync-gateway-version=1.4.0-26 --server-version=4.5.1 -k "test_online_to_offline_changes_feed_controlled_close_continuous" testsuites/syncgateway/functional/tests/
```

**Comment by adamcfraser** [comment]
I think the real issue here is that Sync Gateway shouldn't be starting a feed in the first place when running in di mode.  In database.go (NewDatabaseContext), we shouldn't be calling tapListener.Start when in channel index non-writer mode.

**Comment by sethrosetter** [comment]
Also causing `test_online_to_offline_changes_feed_controlled_close_longpoll` to fail

**Comment by sethrosetter** [comment]
And `test_offline_true_config_bring_online` to fail

**Comment by ajres** [comment]
Not starting the feed in NewDatabaseContext, does fix the initial issue as reported, but results in a panic when bringing the DB _online.

```
HTTP:  #002: POST /db/_online  (ADMIN)
CRUD: Taking Database : db, online in 0 seconds
HTTP+: #002:     --> 200   (0.1 ms)
Closing db /db (bucket "data-bucket")
Unimplemented method: Close() -- base.CouchbaseBucketGoCB.Close() at bucket_gocb.go:910
panic: Unimplemented method: Close()

goroutine 84 [running]:
panic(0x46306a0, 0xc420366c00)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbase/sync_gateway/base.LogPanic(0x4733dc9, 0x1d, 0x0, 0x0, 0x0)
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/logging.go:360 +0x115
github.com/couchbase/sync_gateway/base.CouchbaseBucketGoCB.Close(0xc42031a700, 0xc4201cb040, 0x15, 0x47223a4, 0x7, 0xc4201e8780, 0xc, 0x0, 0x0, 0x0, ...)
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/bucket_gocb.go:910 +0x51
github.com/couchbase/sync_gateway/base.(*CouchbaseBucketGoCB).Close(0xc42024e980)
	<autogenerated>:330 +0x7a
github.com/couchbase/sync_gateway/db.(*kvChangeIndexReader).Stop(0xc420240d20)
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/kv_change_index_reader.go:115 +0x7b
github.com/couchbase/sync_gateway/db.(*kvChangeIndex).Stop(0xc4203101e0)
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:69 +0x2f
github.com/couchbase/sync_gateway/db.(*DatabaseContext).Close(0xc42030e000)
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/database.go:302 +0x99
github.com/couchbase/sync_gateway/rest.(*ServerContext)._removeDatabase(0xc4201ceb40, 0xc4201e878c, 0x2, 0xc420219730)
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:744 +0x16d
github.com/couchbase/sync_gateway/rest.(*ServerContext).ReloadDatabaseFromConfig(0xc4201ceb40, 0xc4201e878c, 0x2, 0xc420219701, 0x0, 0x0, 0x0)
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:239 +0xa1
github.com/couchbase/sync_gateway/rest.(*ServerContext).TakeDbOnline(0xc4201ceb40, 0xc42030e000)
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:575 +0xc9
github.com/couchbase/sync_gateway/rest.(*handler).handleDbOnline.func1(0xc4203cac80, 0xc42019c360)
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/admin_api.go:82 +0x60
created by github.com/couchbase/sync_gateway/rest.(*handler).handleDbOnline
	/Users/andy/projects/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/admin_api.go:83 +0x2c0
```

**Comment by ajres** [comment]
I have put a check `func (k *kvChangeIndexReader) Stop() {` in kv_change_index_reader.go so that Close() is not called on CouchbaseBucketGoCB instances. This prevents the panic, but after each _offline/_online cycle it looks like the old CouchbaseBucketGoCB instance is never released.

Should CouchbaseBucketGoCB support the Close() function?

**Comment by adamcfraser** [comment]
Nice catch.  The underlying gocb bucket already has a Close() operation - we should be calling that.  At first glance I don't think we need to do any additional work for CouchbaseBucketGoCB - we might just be able to remove our Close() implementation and let it pass through to the underlying bucket.  

I had a quick look and don't think there's any additional teardown we need to do for CouchbaseBucketGoCB.   I'm not sure we have a good way to terminate in-flight bucket operations before closing the bucket, though.  How are we covering that scenario for the go-couchbase bucket?

**Comment by ajres** [comment]
We drop through to Bucket.Close()

```
// Close marks this bucket as no longer needed, closing connections it
// may have open.
func (b *Bucket) Close() {
	if b.connPools != nil {
		for _, c := range b.getConnPools() {
			if c != nil {
				c.Close()
			}
		}
		b.connPools = nil
	}
}
```

**Comment by adamcfraser** [comment]
Ok - seems like in both cases we have the potential to break in-flight operations against the bucket?   We can put that aside for now, but might merit a separate tracking ticket.

**Comment by ajres** [comment]
I have removed the type check in kv_change_index_reader.go, and now let the CouchbaseBucketGoCB.Close() function fall through to gocb.Bucket.Close().

Pushed up to PR.
