### ISSUE TITLE
`state` value missing from Db GET documentation

### ISSUE THREAD

**Issue by jamescooke** [couchbase/sync_gateway#2168]
Documentation at http://developer.couchbase.com/documentation/mobile/1.3/references/sync-gateway/admin-rest-api/index.html#operation---db---get does not list the field `state` 

### Sync Gateway version

    {"ADMIN":true,"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":1.2},"version":"Couchbase Sync Gateway/1.2.0(79;9df63a5)"}

Yes this is an old version of Sync Gateway, in live, but it also happens with SG 1.3.1 in Walrus mode.

### Operating system
Ubuntu 14.04

### Config file
n/a

### Log output
When performing a GET on our development database:

```json
{
"committed_update_seq": 39243,
 "compact_running": false,
 "db_name": "dev",
 "disk_format_version": 0,
 "instance_start_time": 1479828267568341,
 "purge_seq": 0,
 "state": "Online",
 "update_seq": 39243
}
```

Note that ` "state": "Online",` is not described in the Documentation.

### Expected behavior
Documentation should list possible `state` values and implications of those values. If these are documented elsewhere then mention the field and link to that doc.

### Actual behavior
Documentation does not mention `state` value.

**Comment by jamesnocentini** [comment]
I created a docs ticket linked to this one. Thanks for the feedback!
