### ISSUE TITLE
Flushing Couchbase Server bucket doesn't cause SG to take db offline

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2172]
From https://github.com/couchbaselabs/sgload/issues/30#issuecomment-262628857, flushing the bucket caused the channel cache to get into a broken state, but the db was not taken offline.

@ajres do you know if flushing the bucket is supposed to cause the db to go offline?

**Comment by adamcfraser** [comment]
@ajres Specifically, we could see that SG had lost the mutation feed from the server (presumably when the flush was done), but SG didn't detect that and go offline.

**Comment by adamcfraser** [comment]
Closing based on age.
