### ISSUE TITLE
go-couchbase 500 errors when rebalancing

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2173]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
1.4.0-27 

### Operating system
CentOS 7

### Config file
standard

### Log output
https://gist.github.com/sethrosetter/393d9ba6a355abd4c974e5180d8dc612

Interesting output

``` 
2016-11-17T17:59:49.744Z HTTP:  #7502: GET /db/test_doc_74?conflicts=true&revs=true  (as seth)
_time=2016-11-17T17:59:50.275+00:00 _level=INFO _msg=go-couchbase: call to Do("_sync:rev:test_doc_73:35:25-4a1eb54ad7e84329901d2b950c6b925c") in github.com/couchbase/go-couchbase.(*Bucket).Write took 638.21429ms 
2016-11-17T17:59:50.275Z WARNING: backupAncestorRevs failed: doc="test_doc_73" rev="25-4a1eb54ad7e84329901d2b950c6b925c" err=unable to complete action after 6 attemps -- db.(*Database).backupAncestorRevs() at crud.go:383
_time=2016-11-17T17:59:50.278+00:00 _level=INFO _msg=go-couchbase: call to Do("test_doc_74") in github.com/couchbase/go-couchbase.(*Bucket).GetsRaw took 533.907398ms 
2016-11-17T17:59:50.278Z HTTP: #7502:     --> 500 Internal error: unable to complete action after 6 attemps  (549.7 ms)
2016-11-17T17:59:50.287Z Cache: SAVING #7427
2016-11-17T17:59:50.288Z CRUD: Stored doc "test_doc_73" / "26-52a0dd75865e851cbef554740430ecfa"
2016-11-17T17:59:50.288Z HTTP+: #7499:     --> 201   (668.8 ms)
2016-11-17T17:59:50.298Z HTTP:  #7503: GET /db/test_doc_75?conflicts=true&revs=t
```

### Expected behavior
- Using a 3 node server cluster running 4.5.1
- Apply write load while rebalancing out one node
- All write ops should succeed

### Actual behavior
- Seeing some docs fail with 500 errors

### Steps to reproduce
1.  Testcase:
https://github.com/couchbaselabs/mobile-testkit/blob/feature/rebalance-support/testsuites/syncgateway/functional/topology_specific_tests/multiple_servers/test_rebalance_scenarios.py#L99-L189

**Comment by sethrosetter** [comment]
https://www.dropbox.com/s/wqnaaryhwk7sn9g/Screenshot%202016-11-28%2016.56.57.png?dl=0

**Comment by sethrosetter** [comment]
Seeing 2 failed GET requests in HTTPScoop

![screenshot 2016-11-28 16 56 57](https://cloud.githubusercontent.com/assets/1365736/20692285/c15a2234-b58b-11e6-99a2-8738c840e656.png)

**Comment by sethrosetter** [comment]
Response
```
{"error":"Internal Server Error","reason":"Internal error: unable to complete action after 6 attemps"}
```

**Comment by sethrosetter** [comment]
@tleyden I ran with this https://github.com/couchbase/go-couchbase/commit/b9fe4de8236c30853a2a313772225b39669e9afc change of go-couchbase and  this build https://github.com/couchbase/sync_gateway/commit/f442d629dc4ca48fc1d53dfc72d8f3e5cc627b6e of sync_gateway and am still seeing the 500 errors

**Comment by sethrosetter** [comment]
This test passes with CBS 4.1.1 but not CBS 4.5.1

**Comment by sethrosetter** [comment]
When this is fixed, please let me know so we can reenable the test - https://github.com/couchbaselabs/mobile-testkit/issues/820

**Comment by adamcfraser** [comment]
No longer relevant (moved to gocb-based bucket).
