### ISSUE TITLE
sg 1.3 replication failure

### ISSUE THREAD

**Issue by npomfret** [couchbase/sync_gateway#2178]
I have a scenario where the sync gateway stopped working.  It looked like it lost its connection to couchbase (maybe) and didn't recover.  

The full details and any logs I could gather at the time are linked to in this [discussion](https://forums.couchbase.com/t/replication-sometimes-not-working/10904/9) on the forum.

**Comment by adamcfraser** [comment]
@npomfret To understand what's going on, it would be very helpful to get an excerpt from the SG log when the failure occurs, from the point described on the linked forum post - the last appearance of `==> channel` in the log.  

If you don't have that from the last time you hit this issue, can you provide them the next time you hit it?  (You mentioned on the original post that you're seeing this "not often...but once in a while").
