### ISSUE TITLE
Same doc is sent twice to longpoll changes feed

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2186]
### Sync Gateway version
Couchbase Sync Gateway/1.4(8;2c128aa) (ONLY occurs in with sg_accel)

### Operating system
CentOS 7

### Config file
```
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "verbose":"true",
    "cluster_config": {
        "server":"http://{{ couchbase_server_primary_node }}:8091",
        "data_dir":".",
        "bucket":"data-bucket"
    },
    "databases":{
        "db":{
            "server":"http://{{ couchbase_server_primary_node }}:8091",
            "bucket":"data-bucket",
            "feed_type":"DCPSHARD",
            "feed_params":{
                "num_shards":64
            },
            "channel_index":{
                "server":"http://{{ couchbase_server_primary_node }}:8091",
                "bucket":"index-bucket",
                "writer":{{ is_index_writer }}
            },
            "sync":
            `function(doc, oldDoc){
                if(doc._id == "access_doc_0") {
                    console.log("granting_access!");
                    access(["adam", "traun", "andy"], "NATGEO");
                }
                if(doc._id == "roles_doc_0") {
                    console.log("adding role to users!");
                    role(["adam", "traun", "andy"], "role:doc_access");
                }
                channel(doc, doc.channels);
            }`
        }
    }
}

```

### Expected behavior
Doc should only be sent to the changes feed once. 

### Actual behavior
I am issuing 2 changes requests:
1. Create a doc with a channel "NATGEO"
1. Create a user that does not have access to "NATGEO"
1. Start a longpoll changes feed for that user
1. Grant the user to "NATGEO" via the sync function
1. The changes feed should exit with doc and a last seq.
1. THE PROBLEM. If you issue another changes request with a since using that last_seq from above, the doc is returned again

Perhaps related?
I'm never seeing _user/ docs in the changes feed during this scenario

ex. 
1. `POST _changes {"feed": "longpoll", "since": "0", "timeout": 10000}`
```
{"results":[
{"seq":"1-0","id":"natgeo_0","changes":[{"rev":"1-f54c513673b8e636f36eeb6636e5ba3b"}]}
],
"last_seq":"1-0"}
```
1. `POST _changes {"feed": "longpoll", "since": "1-0", "timeout": 1000}`
```
{"results":[
{"seq":"2-0:682.1","id":"natgeo_0","changes":[{"rev":"1-f54c513673b8e636f36eeb6636e5ba3b"}]}
],
"last_seq":"2-0:682.1"}
```

**Comment by sethrosetter** [comment]
Also happen when granting the user access via role()

**Comment by sethrosetter** [comment]
Reproducible with https://github.com/couchbaselabs/mobile-testkit/blob/feature/changes-notification-tests/testsuites/syncgateway/functional/tests/test_longpoll.py#L667-L769 running in distributed index mode

**Comment by adamcfraser** [comment]
Re-enable DisableTestPostChangesAdminChannelGrantClock as part of this fix.
