### ISSUE TITLE
SG panic when upgrading keepalive http connection to WebSockets

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2187]
When configuring a reverse proxy to sit in front of SG instances, users may configure a pool of keepalive connections. Connection pools are used to improve the request throughput from the reverse proxy to the service (SG).

When one of these connections is first used as a standard HTTP connection and then subsequently reused for a _changes feed with type WebSockets, Sync Gateway panics attempting to upgrade the connection.

```
2016-10-13T16:59:35.818+02:00 HTTP:  #1176418: GET /sync_gateway/_changes?feed=websocket  (as USER)
2016-10-13 16:59:35.818094 I | http: panic serving 127.0.0.1:18383: Hijack failed: http: Hijack is incompatible with use of CloseNotifier
goroutine 4620480 [running]:
net/http.(*conn).serve.func1(0xc0b4c26580, 0x1e24ff8, 0xc0999a5290)
        c:/go/src/net/http/server.go:1287 +0xbc
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf89aa0, ...)
        c:/jenkins/workspace/sgw-windows-build/godeps/src/golang.org/x/net/websocket/server.go:76 +0x1a5
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf89aa0, ...)
        c:/jenkins/workspace/sgw-windows-build/godeps/src/golang.org/x/net/websocket/server.go:70 +0x53
github.com/couchbase/sync_gateway/rest.(*handler).sendContinuousChangesByWebSocket(0xc09d4ccf30, 0xc08ca67e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        c:/jenkins/workspace/sgw-windows-build/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:751 +0x1e4
github.com/couchbase/sync_gateway/rest.(*handler).handleChanges(0xc09d4ccf30, 0x0, 0x0)
        c:/jenkins/workspace/sgw-windows-build/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:290 +0xee8
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc09d4ccf30, 0xf89868, 0x0, 0x0)
        c:/jenkins/workspace/sgw-windows-build/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:200 +0x7bb
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x2681c58, 0xc0aa5a4c60, 0xc0a8567c00)
        c:/jenkins/workspace/sgw-windows-build/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x7e
net/http.HandlerFunc.ServeHTTP(0xc0823f1ac0, 0x2681c58, 0xc0aa5a4c60, 0xc0a8567c00)
        c:/go/src/net/http/server.go:1422 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0823ab7c0, 0x2681c58, 0xc0aa5a4c60, 0xc0a8567c00)
        c:/jenkins/workspace/sgw-windows-build/godeps/src/github.com/gorilla/mux/mux.go:86 +0x2ad
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x2681c58, 0xc0aa5a4c60, 0xc0a8567c00)
        c:/jenkins/workspace/sgw-windows-build/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:299 +0x334
net/http.HandlerFunc.ServeHTTP(0xc082483380, 0x2681c58, 0xc0aa5a4c60, 0xc0a8567c00)
        c:/go/src/net/http/server.go:1422 +0x41
net/http.serverHandler.ServeHTTP(0xc082467020, 0x2681c58, 0xc0aa5a4c60, 0xc0a8567c00)
        c:/go/src/net/http/server.go:1862 +0x1a5
net/http.(*conn).serve(0xc0b4c26580)
        c:/go/src/net/http/server.go:1361 +0xbf5
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:1910 +0x3fd
```

**Comment by ajres** [comment]
After reviewing SG code, it appears that this error is in the golang net/http library.

It looks like a resolution for this issue is slated for golang 1.8 release.
 `https://github.com/golang/go/commit/99fb19194c03c618c0d8faa87b91ba419ae28ee3`

Golang 1.8 GA is due for release 31st Jan 2017.
Not sure how this fits with SG release milestones.

I'm going to build SG with Golang 1.8 and retest.

**Comment by ajres** [comment]
After discussing with @adamcfraser it appears this fix has been released since golang 1.6.

SG 1.3.0 was built with golang 1.5, but SG 1.3.1 was built with golang 1.6.3 so should not exhibit this behaviour.

**Comment by ajres** [comment]
Moving to review, awaiting feedback from support to see if SG 1.3.1 fixes this issue.

**Comment by dropwhile** [comment]
I'm seeing this on SG 1.3.1 still.

```
2017-01-10T22:45:33.959Z HTTP:  #452: GET /db/_changes?feed=websocket  (as USER)
2017-01-10 22:45:33.959750 I | http: panic serving 127.0.0.1:57134: Hijack failed: http: Hijack is incompatible with use of CloseNotifier
goroutine 630 [running]:
net/http.(*conn).serve.func1(0xc8213fc4d0, 0x7fdeca717230, 0xc822a461d0)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf83150, ...)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/golang.org/x/net/websocket/server.go:76 +0x19e
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf83150, ...)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/golang.org/x/net/websocket/server.go:70 +0x4c
github.com/couchbase/sync_gateway/rest.(*handler).sendContinuousChangesByWebSocket(0xc823bfa240, 0xc8207eb290, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:751 +0x1dd
github.com/couchbase/sync_gateway/rest.(*handler).handleChanges(0xc823bfa240, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:290 +0xee1
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc823bfa240, 0xf82f18, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:200 +0x7b4
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x7fdeca7200f8, 0xc8204c6370, 0xc821d32000)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x77
net/http.HandlerFunc.ServeHTTP(0xc82044e7e0, 0x7fdeca7200f8, 0xc8204c6370, 0xc821d32000)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82042c500, 0x7fdeca7200f8, 0xc8204c6370, 0xc821d32000)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/gorilla/mux/mux.go:86 +0x2a6
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x7fdeca7200f8, 0xc8204c6370, 0xc821d32000)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:299 +0x32d
net/http.HandlerFunc.ServeHTTP(0xc8204de140, 0x7fdeca7200f8, 0xc8204c6370, 0xc821d32000)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc82049da40, 0x7fdeca7200f8, 0xc8204c6370, 0xc821d32000)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8213fc4d0)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by formaggieo** [comment]
I am also seeing this on SG 1.3.1, version string:
{"ADMIN":true,"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":1.3},"version":"Couchbase Sync Gateway/1.3.1(16;f18e833)"}

Traceback:

2017-02-06T21:24:28.333Z HTTP:  #640: GET /db/_changes?feed=websocket  (as user_2)
2017-02-06 21:24:28.333818 I | http: panic serving 10.0.100.68:64623: Hijack failed: http: Hijack is incompatible with use of CloseNotifier
goroutine 843 [running]:
net/http.(*conn).serve.func1(0xc8247dc420, 0x7fb146a340d8, 0xc824b30b40)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf83150, ...)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/golang.org/x/net/websocket/server.go:76 +0x19e
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf83150, ...)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/golang.org/x/net/websocket/server.go:70 +0x4c
github.com/couchbase/sync_gateway/rest.(*handler).sendContinuousChangesByWebSocket(0xc825037e60, 0xc8250785a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:751 +0x1dd
github.com/couchbase/sync_gateway/rest.(*handler).handleChanges(0xc825037e60, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/changes_api.go:290 +0xee1
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc825037e60, 0xf82f18, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:200 +0x7b4
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x7fb147273210, 0xc822dd0dc0, 0xc8207f6620)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:90 +0x77
net/http.HandlerFunc.ServeHTTP(0xc8204e2620, 0x7fb147273210, 0xc822dd0dc0, 0xc8207f6620)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8204819f0, 0x7fb147273210, 0xc822dd0dc0, 0xc8207f6620)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/gorilla/mux/mux.go:86 +0x2a6
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x7fb147273210, 0xc822dd0dc0, 0xc8207f6620)
	/home/couchbase/jenkins/workspace/sgw-unix-build/1.3.1/community/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:299 +0x32d
net/http.HandlerFunc.ServeHTTP(0xc820557fa0, 0x7fb147273210, 0xc822dd0dc0, 0xc8207f6620)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc8202f8300, 0x7fb147273210, 0xc822dd0dc0, 0xc8207f6620)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8247dc420)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

**Comment by formaggieo** [comment]
This error appears to prevent the iOS client from syncing properly; once it occurs documents do not get pushed back to the client from the server.

**Comment by dropwhile** [comment]
@formaggieo we (my company) have worked around it currently by means of nginx configuration (we already had nginx in front of sync gateway to handle ssl). We simply disabled the keepalive stanza for the sync gateway backend (so nginx does not maintain backend connections that live beyond the life of the client side connection). A bit less efficient, but tenable because most client connections are fairly long lived anyway.

**Comment by adamcfraser** [comment]
@formaggieo (or @cactus) What OS are you running Sync Gateway on?

**Comment by dropwhile** [comment]
@adamcfraser centos 7 with current updates (as of last week or so)
sync_gateway is installed via rpm.  
Currently: `couchbase-sync-gateway-community_1.3.1-16_x86_64.rpm`

**Comment by formaggieo** [comment]
@adamcfraser ubuntu 14.04.4

**Comment by adamcfraser** [comment]
@ajres That error message is definitely a golang 1.5.x error message - post-1.6 the related error is appended with "...in the same ServeHTTP call".

Need to revalidate the go version for 1.3.1.

**Comment by formaggieo** [comment]
@cactus thanks for the info. I'm behind an aws lb and it's not clear to me that I can disable the keepalive.

**Comment by adamcfraser** [comment]
@ajres Reviewed, and SG 1.3.1 was actually built with go 1.5.3.

SG 1.3.1.1 (MacOS-only release for Sierra support) was built with 1.7.1, but the other platforms won't move to go 1.7.x (and get this fix) until 1.4 is released.

**Comment by dropwhile** [comment]
@adamcfraser 

```
$ strings sync_gateway |grep go1
go1.5.3
```

**Comment by adamcfraser** [comment]
Closing as fixed in 1.4 - apologies for the miscommunication.

**Comment by dropwhile** [comment]
@adamcfraser is there any information (or a rough estimate -- 3mo? 6mo?) about when 1.4.0 is expected to be released?

**Comment by adamcfraser** [comment]
The current target is early March.  Subject to change, but I wouldn't expect it to be much later than that.
