### ISSUE TITLE
Small utility to grab debug information

### ISSUE THREAD

**Issue by pavel-paulau** [couchbase/sync_gateway#219]
it should be part of package. Similar to cbcollect_info.

It should include at least:

uname
top
vmstat
mpstat
iostat
partitions
diskstats
cpuinfo 
meminfo
lsof
mount
free
swap
lsmod
ps
pstack
lsb_release
ulimit
dmesg
VERSION.txt
/var/log/messages
#217

CPU profile
heap profile
runtime stats

And many other things eventually.

**Comment by adamcfraser** [comment]
sgcollect_info is available as of 1.3 - provides similar information to what's described here.
