### ISSUE TITLE
Backfill triggering for channels that do not need to be backfilled

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2191]
### Sync Gateway version
Couchbase Sync Gateway/1.4(8;2c128aa)

### Operating system
CentOS7

### Config file
Standard

### Log output
https://gist.github.com/sethrosetter/5f1834af8aecc7c8b628fc79cd9f44e9

### Steps to reproduce
1.  `pytest --pdb -s --skip-provisioning --mode=cc --sync-gateway-version=1.4-8 --server-version=4.5.1 -k "test_backfill_channels_oneshot_changes[custom_sync/access-CHANNEL-SYNC]" testsuites/syncgateway/functional/tests/`

Test Scenario:

1. Create user with access to channel "A"
2. Create user USER_B with access to channel "B"

3. Create 50 docs with channel "A"
4. Create 1 doc with channel "B"

5. Verify User B sees "B" doc in changes (store 'last_seq' as last_seq_1)

6. Grant USER_B access to channel "A" via the sync function `access()` method which will trigger a backfill.

7. Issue one shot _changes for USER_B with since=last_seq_1
USER_B should get 50 user A docs in _changes. Store last_seq as last_seq_2

8. Issue one shot_changes for USER_B with since=last_seq_2
Additionally, a backfill is triggered for channel "B" as well causing the doc to show up in changes again (this is unexpected).

@adamcfraser and I debugged this issue and he should be able to comment on other specifics

**Comment by adamcfraser** [comment]
This looks like a gap in the triggered by handling that's outlined here:
https://github.com/couchbase/sync_gateway/blob/master/db/changes.go#L356

There should be a 4th case:
```
//   4. options.Since.TriggeredBy !=0 and options.Since.TriggeredBy > seqAddedAt: We're in the
//  middle of a backfill for another channel.  This should issue normal (non-backfill) changes 
//  request with  since= options.Since.TriggeredBy for the non-backfill channel.
