### ISSUE TITLE
Sync Gateway service doesn't recognize OEL 6 server

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2192]
From @PavanBhushan_twitter on Gitter:

> I am trying to install couchbase server and syncgateway in OEL 6 server. Successfully installed server but sync gateway is failing. When i run .sync_gateway_service_install.sh it is saying Unknown server "Oracle server"

Note: oracle linux is based on RHEL

**Comment by pmaganti** [comment]
@tleyden Thank you for opening the issue here.

> do you know if OEL 6 uses systemd, upstart, or sysV init?

I am not sure about OEL based servers. New to this. I am used to Ubuntu and never faced issues with couchbase setup in last 2 years.

Is there any command that I can run and paste the response here, I am happy to do that.

**Comment by pmaganti** [comment]
Here are the logs.
```
$ wget http://packages.couchbase.com/releases/couchbase-sync-gateway/1.3.1/couchbase-sync-gateway-enterprise_1.3.1-16_x86_64.rpm
$ rpm --install couchbase-sync-gateway-enterprise_1.3.1-16_x86_64.rpm
$ /opt/couchbase-sync-gateway/service/sync_gateway_service_install.sh 
ERROR: unknown OS "OracleServer"
This script creates an init service to run a sync_gateway instance.
If you want to install more than one service instance
create additional services with different names.

sync_gateway_service_install.sh
    -h --help
    --runas=<The user account to run sync_gateway as; default (sync_gateway)>
    --runbase=<The directory to run sync_gateway from; defaut (/home/sync_gateway)>
    --sgpath=<The path to the sync_gateway executable; default (/opt/couchbase-sync-gateway/bin/sync_gateway)>
    --cfgpath=<The path to the sync_gateway JSON config file; default (/home/sync_gateway/sync_gateway.json)>
    --logsdir=<The path to the log file direcotry; default (/home/sync_gateway/logs)>
```

Both `rpm install` and `./sync_gateway_service_install.sh` returned the same `ERROR: unknown OS "OracleServer"`

**Comment by ajres** [comment]
If you have access to /opt/couchbase-sync-gateway/service/sync_gateway_service_install.sh, edit it and make the following change and retest.

On line (approx depending on version) 227 you should see the following switch statement case:

`RedHat|CentOS)`

Change that to:

`RedHat|CentOS|OracleServer)`

Save and retest.

OEL and RedHat major releases are aligned, so the logic for which init system to configure should be correct.

**Comment by pmaganti** [comment]
@ajres I did that before writing this issue.
I don't have the exact error message now(Service is on-premise and can't access from outside) but i remember this kind of error was thrown.

`script_templates/upstart_redhat_sync_gateway.tpl doesn't exist`

I am not sure when, but this error occurred too.(Based on my browser history, posting here. Can give more clear set of error when I am back to work)
`The sync_gateway source JSON config file directory does not exist "../examples".`

**Comment by pmaganti** [comment]
Now I got the access. Here is the error when I added `OracleServer` into the statement @ajres mentioned.
```
$ /opt/couchbase-sync-gateway/service/sync_gateway_service_install.sh 
The sync_gateway source JSON config file directory does not exist "../examples".
```

**Comment by ajres** [comment]
Try running the following commands to run the modified install script:

`$ cd /opt/couchbase-sync-gateway/service/`

`$ sudo ./sync_gateway_service_install.sh`

**Comment by pmaganti** [comment]
Thank you @ajres 
I tried that option and is working fine.

To restart the service, `initctl restart sync_gateway` is the option I found.

**Comment by pmaganti** [comment]
**Update after 1-month experience with OracleServer**

`initctl restart sync_gateway`
Running above is not reloading the sync_gateway.json file.

The only workaround I found is to re-install the sync gateway service again.
