### ISSUE TITLE
Support JSON5 syntax in config files

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#2195]
[JSON5](http://json5.org) is a superset of JSON (and subset of full JS) that is a lot friendlier to write. It allows comments, unquoted keys, trailing commas, single or double quotes, line breaks in strings, and more.

It would be really nice if SG config files could be parsed as JSON5. Comments are great to have for maintainability, and in our example configs to help new users. And the other changes make the file more readable and less likely to break due to stupid syntax errors.

(We may still want to keep the back-quote hack for embedded sync functions, although it's less necessary because the sync fn could be written using all single quotes.)

There is at least one [JSON5 parser for Go](https://github.com/yosuke-furukawa/json5).

**Comment by adamcfraser** [comment]
Closing based on age - considering enhancement for external js file as alternative for inline sync functions.
