### ISSUE TITLE
Missing documentation for custer_config parameter

### ISSUE THREAD

**Issue by lgleim** [couchbase/sync_gateway#2199]
In the current release (1.3.1) sync gateway takes a configuration option `cluster_config`. 
The corresponding go variable can be found here: https://github.com/couchbase/sync_gateway/blob/2311ab055acbfb217605c8b542fa3fd451fe3641/rest/config.go#L85

The online documentation at http://developer.couchbase.com/documentation/mobile/1.3/guides/sync-gateway/config-properties/index.html lacks an explanation of what the configuration parameter does and how to use it.

**Comment by adamcfraser** [comment]
This config property is related to the Sync Gateway Accelerator add-on.  Full documentation will be included when it's GA in release 1.4.  

Added a ticket specifically for config docs here:
https://github.com/couchbaselabs/couchbase-mobile-portal/issues/518
