### ISSUE TITLE
Error when querying /_user/ from the ADMIN port

### ISSUE THREAD

**Issue by gweisz** [couchbase/sync_gateway#2203]
### Sync Gateway version
Couchbase Sync Gateway/1.2.0(79;9df63a5)

### Operating system
ubuntu 14.04

### Config file
{
        "log": ["HTTP+"],
        "adminInterface": ":**...**",
        "interface": ":**...**",
        "CORS": {
                "origin":["*"],
                "loginOrigin":["*"],
                "headers":["Content-Type"],
                "maxAge": 1728000
        },
        "databases": {
                "**...**": {
                        "server": "**...**",
                        "bucket": "**...**",
                        "username": "**...**",
                        "password": "**...**",
                        "users": {
                                "GUEST": {"disabled": true, "admin_channels": ["*"] }
                        },
                        "sync": `function(doc, oldDoc){
                                **...**
                        }`
                }
        }
}

### Log output
2016-12-25T11:45:00.072Z HTTP: #13327416: GET /**...**/_user/ (ADMIN)
2016-12-25T11:45:00.073Z WARNING: Couldn't interpret error type *errors.errorString, value error starting view req at http://**...**/**...**/_design/sync_gateway/_view/principals?stale=false: Get http://**...**/**...**/_design/sync_gateway/_view/principals?stale=false: EOF – base.ErrorAsHTTPStatus() at error.go:63
2016-12-25T11:45:00.073Z HTTP: #13327416: --> 500 Internal error: error starting view req at http://**...**/**...**/_design/sync_gateway/_view/principals?stale=false: Get http://**...**/**...**/_design/sync_gateway/_view/principals?stale=false: EOF (0.4 ms)

### Expected behavior
Normal response of /_user/
e.g. 200 - ["user1","user2","user3","etc..."]

### Actual behavior
Received error response, see logs

### Steps to reproduce
Couldn't reproduce. There's a job that performs this call every minute and only failed once

**Comment by gweisz** [comment]
Some more additional info, the Couchbase server version is "2.2.0 community edition (build-837)"

**Comment by adamcfraser** [comment]
It looks like Couchbase Server is returning an empty response for the principals view request.  There isn't anything obvious from the information you've provided on why that happened.  There currently isn't any automatic retry handling in Sync Gateway's view execution code for EOF errors (the latest Sync Gateway retries when the view isn't found, but not for EOF).   

How frequently are you seeing this failure?  Your best bet is probably to add your own retry logic to your client (to retry on a 500).

**Comment by gweisz** [comment]
@adamcfraser  Thanks much for the response.

We only had this issue once and it's a periodic job that runs every 5', so it's definitely a minor issue.

If it's a bug from Couchbase Server please feel free to close the issue.

**Comment by djpongh** [comment]
Closing based on comments
