### ISSUE TITLE
Currently project is not buildable, please use vendoring

### ISSUE THREAD

**Issue by dlsniper** [couchbase/sync_gateway#2209]
Hello,

Due to a change in a dependency, https://github.com/couchbase/gocb/commit/add6f3109f3e309d66d79a9bfa297771f49c882f, currently this project is not buildable.
Please use the Go vendoring approach in order to vendor the library this project depends on in order to ensure that builds do not break like this and are reproducible.

```
base/bucket_gocb.go:18:2: cannot find package "github.com/couchbase/gocb/gocbcore" in any of:
	/usr/local/go1.8/src/github.com/couchbase/gocb/gocbcore (from $GOROOT)
	/home/florin/go/src/github.com/couchbase/gocb/gocbcore (from $GOPATH)
```

Thank you.

**Comment by adamcfraser** [comment]
As described in the readme (in particular the link to the [Extended Build Instructions](https://github.com/couchbase/sync_gateway/blob/master/docs/BUILD.md)), you currently need to use repo for reproducible builds.

**Comment by dlsniper** [comment]
Then, as described by the README, this is a problem and I should open the issue: https://github.com/couchbase/sync_gateway#download-and-build :)

```
Download and build the code in a single step via go get:

$ go get -u -t github.com/couchbase/sync_gateway/...
After this operation completes you should have a new sync_gateway binary in $GOPATH/bin

NOTE: This build style is only suitable for development rather than deployment. There is a chance this might fail or have runtime errors due to using the latest version of all dependencies (whereas release builds use dependency pinning). Please file an issue if you run into problems.
```

Furthermore, this is a rather an anti-pattern for a Go project so I thought it would be nice to let you know.

**Comment by adamcfraser** [comment]
@dlsniper That's a fair point - apologies if I was a bit abrupt in my earlier reply.

Right now we've got competing priorities - we'd like to move to vendoring as it's become standard, but our build infrastructure (which is shared with non-go repositories) is repo-based.  Eventually we want to improve the build infrastructure to allow us to support both paths, but we're not there yet.

**Comment by dlsniper** [comment]
Fair enough ;) Thanks for the quick replies.

**Comment by tleyden** [comment]
Yeah, I ran into that same issue and meant to bring it up, but then forgot to

**Comment by tleyden** [comment]
@dlsniper I just updated the README to mention that issue.  Thanks again for reporting
