### ISSUE TITLE
how to change the beam.smp value in couchbase

### ISSUE THREAD

**Issue by Gnanodhar** [couchbase/sync_gateway#2215]
Hello, 

I could find some info from couchbase page 
Excessive memory consumption by the beam.smp process on Lnux 
If the XDCR Max Replications per Bucket value is raised (such as to 128), then the beam.smp process uses excessive memory. The solution is to reset to 32 or lower.

I could see some beam.smp errors .. I just want to change or see the value of beam.smp for my couchbase server.. 

Can anyone let me know how to find the value of beam.smp

Thanks, 
Dev

**Comment by tleyden** [comment]
Doesn't seem like a sync gateway bug.  Can you ask on https://forums.couchbase.com/?
