### ISSUE TITLE
SyncGateway Replicate load balance

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2219]
### Sync Gateway version
1.3.1

### Operating system
redHat 7.2

### Config file
"replications":[
   {
               "replication_id":"C1_C2",
               "source": "db",
               "target": "http://prod-GWREP.com:4985/db/",
               "continuous":true,
               "changes_feed_limit":1000
    }],

I am using above replication config in the replication. On the destination side i have 2 sg-replicate nodes with fqdn at source to resolve. we are seeing syncgateway replicator requests are not load balanced between syncgateway replicator at destination

### Expected behavior
Replication should load balance between 2 sg-replicators at destination cluster

### Actual behavior
Replication is happening from only one sg-replicate node

**Comment by ArihantRk** [comment]
any insights on this, does syncgateway replicator load balanced?

**Comment by adamcfraser** [comment]
The source node in a replication doesn't assume anything about the target endpoint, and makes individual HTTP requests (the same as normal replication).  If you're setting the replication target to the load balancer endpoint, then requests will get routed as any other traffic to your target cluster.

**Comment by ghost** [comment]
But while doing pull from a load balanced endpoint and the pull is happening on multiple nodes because they are running in open shift and all have same configurations then the data will be pulled equal to the number of pods in target cluster. which can create excessive bandwidth usage.

**Comment by adamcfraser** [comment]
@erpankaj22081982 You're correct that if multiple nodes are configured to do the same pull replication, they are going to duplicate the traffic.  That's different than what's described on this ticket, though - this is talking about a single node configured to pull from a load balanced cluster of SG nodes.

**Comment by adamcfraser** [comment]
Being addressed in Hydrogen, tracked w/ sg-replicate epic.
