### ISSUE TITLE
SG doesn't check if logFilePath valid: no logs/no errors

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#2221]
### Sync Gateway version
Couchbase Sync Gateway/1.4(31;8b54039)

### Operating system
ubuntu16

### Config file
```
"logging": {
    "default": {
      "logFilePath": "tmp/sg_logs/sglogfile.log",
      "logKeys": ["*"],
      "logLevel": "debug",
      "rotation": {
        "maxsize": 1,
        "maxage": 30,
        "maxbackups": 2,
        "localtime": true
      }
    }
  },
"adminInterface": "127.0.0.1:4985",
	"interface": "0.0.0.0:4984",
	"databases": {
		"db": {
			"server": "walrus:data",
			"users": {
				"GUEST": {"disabled": false, "admin_channels": ["*"] }
			}
		}
	}
}
```

### Log output
2017-01-16 23:49:56.304408 I | Log entries will be written to the file tmp/sg_logs/sglogfile.log

### Expected behavior
'tmp/sg_logs/sglogfile.log' is invalid path on *nix systems. SG should validate path on startup

### Actual behavior
after SG startup in /home/sync_gateway/logs/sync_gateway_error.log I see that 'will be written to the file tmp/sg_logs/sglogfile.log' but this file is not created ( neither relative and absolute path)

### Steps to reproduce
set logFilePath with any invalid OS path

**Comment by adamcfraser** [comment]
@andreibaranouski Same question as #2221, to help understand severity - what's the 1.3.1 behaviour when setting logFilePath to an invalid path?

**Comment by andreibaranouski** [comment]
@adamcfraser 
it's a regression from 1.3.1
```

andrei@abv:/opt/couchbase-sync-gateway$ sudo /opt/couchbase-sync-gateway/bin/sync_gateway  examples/basic-walrus-bucket.json
2017-01-17T19:56:05.212+03:00 Enabling logging: [*]
2017-01-17T19:56:05.212+03:00 FATAL: unable to open logfile for write: /12345/tmp/aaa.log -- base.UpdateLogger() at logging.go:291

andrei@abv:/opt/couchbase-sync-gateway$ cat examples/basic-walrus-bucket.json 
{
  "log": ["*"],
"logFilePath": "/12345/tmp/aaa.log",
  "databases": {
    "db": {
      "server": "walrus:",
      "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } },
      "allow_empty_password": true
    }
  }
}
```

**Comment by ajres** [comment]
Added a new utility method to check that a file path exists and is writable, it is now called during log rotation validation. If the log file parent folder does not exist, or if the parent folder of log file are not writable then sync gateway will exit.

Changes pushed to master
