### ISSUE TITLE
logging rotation allows negative values

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#2222]
### Sync Gateway version
Couchbase Sync Gateway/1.4(31;8b54039)

### Operating system
Ubuntu64

### Config file
```
{
  "logging": {
    "default": {
      "logFilePath": "/tmp/sg_logs/sglogfile.log",
      "logKeys": ["*"],
      "logLevel": "debug",
      "rotation": {
        "maxsize": -1,
        "maxage": -30,
        "maxbackups": -2,
        "localtime": true
      }
    }
  },
"adminInterface": "127.0.0.1:4985",
        "interface": "0.0.0.0:4984",
        "databases": {
                "db": {
                        "server": "walrus:data",
                        "users": {
                                "GUEST": {"disabled": false, "admin_channels": ["*"] }
                        }
                }
        }
}

```

### Log output
2017-01-17 00:01:21.772112 I | Log entries will be written to the file /tmp/sg_logs/sglogfile.log
no errors

### Expected behavior
for rotation's parameters I set negative values and it would be good to catch these mistakes at the start (the best option - not start SG service as we have for some negative cases: "Failed to start Couchbase Sync Gateway server.")

### Actual behavior
SG started, rotation's parameters have been ignored?

### Steps to reproduce
use SG with above config

**Comment by ajres** [comment]
Added additional config validation and pushed to SG master.
