### ISSUE TITLE
PORTS - SG to CB Server access

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#2224]
@sethrosetter / @jamiltz 

Here is the link for the ports a APP can use to connect to Couchbase Server.
https://developer.couchbase.com/documentation/server/current/install/install-ports.html

The "Node-to-client*" are the ports a typical JAVA or Node.js SDK would need. 
But since SG doesn't need: 
**8093 (N1QL)
18093 (SSL N1QL)
8094(Full Text Search)**

the above can be block.

@jamiltz It be great to have some docs about needed ports for SG or add to the above page.

Thank you

**Comment by adamcfraser** [comment]
Moved to https://github.com/couchbaselabs/couchbase-mobile-portal/issues/527
