### ISSUE TITLE
logging with maxbackups=0 shouldn't create backup logs

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#2225]
### Sync Gateway version
Couchbase Sync Gateway/1.4(31;8b54039)

### Operating system
centos 7

### Config file
```
{"logging": {
    "default": {
      "logFilePath": "tmp/sg_logs/sglogfile.log",
      "logKeys": ["*"],
      "logLevel": "debug",
      "rotation": {
        "maxsize": 1,
        "maxage": 30,
        "maxbackups": 0,
        "localtime": true
      }
    }
  },
"adminInterface": "127.0.0.1:4985",
	"interface": "0.0.0.0:4984",
	"databases": {
		"db": {
			"server": "walrus:data",
			"users": {
				"GUEST": {"disabled": false, "admin_channels": ["*"] }
			}
		}
	}
}
```

### Expected behavior
only sg_log_rotation.log should be used. backups not needed

### Actual behavior
backup log has been created

[root@localhost sg_logs]# ls -la
total 1996
drwxrwxrwx  2 sync_gateway sync_gateway      82 Jan 16 19:21 .
drwxrwxrwt. 9 root         root            4096 Jan 16 19:21 ..
-rwxrwxrwx  1 root         root         1048567 Jan 16 19:21 sg_log_rotation-2017-01-16T19-21-30.059.log
-rwxr-xr-x  1 sync_gateway sync_gateway    5940 Jan 16 19:21 sg_log_rotation.log

### Steps to reproduce
run SG with above config and generate any data to fill SG log with more then 1 MB

**Comment by adamcfraser** [comment]
This is the correct behaviour - maxbackups=0 means 'do not limit the number of backups'.  Tracking ticket for log rotation config documentation is https://github.com/couchbaselabs/couchbase-mobile-portal/issues/525.
