### ISSUE TITLE
Invalid logFilePath not validated on Windows

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2234]
### Sync Gateway version
1.4-40 x86_64

### Operating system
Win 10

### Config file
```
{
	"logging": {
      "default": {
        "logFilePath": "/var/tmp/sglogfile.log",
        "logKeys": ["*"],
        "logLevel": "debug",
        "rotation": {
          "maxsize": 1,
          "maxage": 30,
          "maxbackups": 2,
          "localtime": true
        }
      }
    },
	"databases": {
		"db": {
			"server": "http://172.23.105.92:8091",
			"bucket": "default",
			"users": {
				"GUEST": {"disabled": false, "admin_channels": ["*"] }
			}
		}
	}
}
```

### Log output
2017-01-20 13:02:57.908864 I | Log entries will be written to the file /var/tmp/sglogfile.log

### Expected behavior
The path /var/tmp/sglogfile.log is invalid on windows. The config parser should fail the checks and either assume a default log file and log the same or fail to start sync gateway.

### Actual behavior
Sync gateway started but no errors were thrown for the invalid path

### Steps to reproduce
1.  Copy paste the above config file to serviceconfig.json
2.  Restart sync gateway
3.  Check C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log for errors

**Comment by raghusarangapani** [comment]
If I set the logFilePath to /var/lib/couchbase/logs/sg.log, I see the below error:
```
2017-01-20T14:36:19.643-08:00 FATAL: Error setting up logging logFilePath /var/lib/couchbase/logs/sg.log is not writable, error: GetFileAttributesEx \var\lib\couchbase\logs: The system cannot find the path specified. -- rest.ParseCommandLine() at config.go:600
```
If I set it to /var/tmp/sg.log, no error:
```
2017-01-20 14:37:06.389925 I | Log entries will be written to the file /var/tmp/sg.log
```

**Comment by raghusarangapani** [comment]
It seems like I can't set valid windows paths either, "logFilePath": "C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log", and I see 2017-01-23T11:56:31.112-08:00 FATAL: Error reading config file C:\Program Files (x86)\Couchbase\\serviceconfig.json: invalid character 'P' in string escape code -- rest.ParseCommandLine() at config.go:504, 

Would this be a different issue than https://github.com/couchbase/sync_gateway/issues/2234 ?

The behavior is different for " vs '.

If I enclose the path within ' ', I see 2017-01-23T11:55:55.079-08:00 FATAL: Error reading config file C:\Program Files (x86)\Couchbase\\serviceconfig.json: invalid character '\'' looking for beginning of value -- rest.ParseCommandLine() at config.go:504

From the log message, it looks like we are assuming \ to be a regex escape sequence
Setting it to "logFilePath": "C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs\\sync_gateway_error.log", works fine.

2017-01-23 12:01:50.284971 I | Log entries will be written to the file C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log

**Comment by raghusarangapani** [comment]
Seems like github filters double \. I meant Setting logFilePath with double \ works fine.

**Comment by raghusarangapani** [comment]
I see the same behavior with 1.3.1. The workaround is to use two slashes (\\) as the path separator

**Comment by ajres** [comment]
I don't see the same behavior for the original issue described on this ticket.

OS Windows 8
Install package: couchbase-sync-gateway-enterprise_1.4-42_x86_64.exe

I used the following logging Object:

```
"default": {
      "logFilePath": "/var/tmp/sglogfile.log",
      "logKeys": ["*"],
      "logLevel": "debug",
      "rotation": {
        "maxsize": 1,
        "maxage": 30,
        "maxbackups": 2,
        "localtime": true
      }
    }
```

The result from running Sync Gateway was:

```
2017-01-24T19:34:00.470Z FATAL: Error setting up logging logFilePath /var/tmp/sg
logfile.log is not writable, error: GetFileAttributesEx \var\tmp: The system can
not find the path specified. -- rest.ParseCommandLine() at config.go:600
```

I can reproduce the described behaviour if I first create a c:\var\tmp folder in Windows. Please check if this folder exists on the test box.

**Comment by raghusarangapani** [comment]
There is a C:\var\tmp folder with 1/20/2017 timestamp.

**Comment by raghusarangapani** [comment]
The Win 10 system I am using for sync gateway testing had a C:\var\tmp folder which caused the confusion. After deleting the folder I see an error message as expected.

```
2017-01-28T12:46:47.220-08:00 FATAL: Error setting up logging logFilePath /var/tmp/sglogfile.log is not writable, error: GetFileAttributesEx \var\tmp: The system cannot find the path specified. -- rest.ParseCommandLine() at config.go:600
```

Will log a separate issue for the double(\\) as per Andy's request. Closing this one as user error.
