### ISSUE TITLE
Rename sync_gateway_error.log

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2236]
### Sync Gateway version
1.4-40 x86_64  

### Operating system
Win 10.

### Expected behavior
Rename sync_gateway_error.log as sync_gateway.log

### Actual behavior
- The log file under C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\ is named as sync_gateway_error.log
- In reality, all logs let logged to this log file but the file name seems to indicate only errors get logged here.

**Comment by adamcfraser** [comment]
@raghusarangapani Does this represent a change in naming in 1.4?

**Comment by raghusarangapani** [comment]
I have not tested 1.3 but I am thinking, the name is the same as before. This is more of a feature request.

**Comment by adamcfraser** [comment]
Similar motivation to https://github.com/couchbase/sync_gateway/issues/1652 - closing as duplicate.
