### ISSUE TITLE
Different log formats for log file related logs

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2237]
### Sync Gateway version
1.4-40 x86_64 

### Operating system
Win 10

### Config file
```{
	"logging": {
      "default": {
        "logFilePath": "/var/tmp/sglogfile.log",
        "logKeys": ["*"],
        "logLevel": "debug",
        "rotation": {
          "maxsize": 1,
          "maxage": 30,
          "maxbackups": 2,
          "localtime": true
        }
      }
    },
	"databases": {
		"db": {
			"server": "http://172.23.105.92:8091",
			"bucket": "default",
			"users": {
				"GUEST": {"disabled": false, "admin_channels": ["*"] }
			}
		}
	}
}
```

### Log output
```
2017-01-20 14:03:11.008900 I | Log entries will be written to the file /var/tmp/sglogfile.log
_time=2017-01-20T14:03:11.050-08:00 _level=INFO _msg= Trying with http://172.23.105.92:8091/pools/default/bucketsStreaming/default 
_time=2017-01-20T14:03:11.051-08:00 _level=INFO _msg= Trying with selected node 0 
_time=2017-01-20T14:03:11.064-08:00 _level=INFO _msg=Got new configuration for bucket default 
_time=2017-01-20T14:03:11.084-08:00 _level=INFO _msg= Trying with selected node 0 
```

### Expected behavior
The logging format should be the same

### Actual behavior
The logging format is different. For the log line
```2017-01-20 14:03:11.008900 I | Log entries will be written to the file /var/tmp/sglogfile.log```
- The timestamp is in a different format
- The _level is missing
- _msg is missing
- This is an additional I |

### Steps to reproduce
Open the log file at C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log

**Comment by ajres** [comment]
The log entries beginning `_time` are coming from go-couchbase's own logging subsystem.

This format is generated by the default KVFORMATTER, I have replaced this with TEXTFORMATTER which is closer to the Sync Gateway log format. e.g

```
2016-02-10T09:15:25.498-08:00 [INFO] This is a message from test in text format
```

If we want 100% parity we will need to write a custom log formatter for go-couchbase's logging subsystem.

**Comment by ajres** [comment]
Also configured go-couchbase logging system to use log rotation when configured. Changes are pushed to PR #2252

**Comment by tleyden** [comment]
Removed template boilerplate from issue:

> The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!
