### ISSUE TITLE
Logging Full Sync vs Delta Sync

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#2239]
It would be great to know when docs have been sync via Full vs Delta Sync. And if its Delta Sync how many bytes  or percentage of Whole doc have been sent. That way people can track how efficient Delta sync is or is not.

**Comment by tleyden** [comment]
@househippo I'm going to close this in the name of keeping our github issues to being well defined and actionable.  What about turning this into a discussion thread on the google group or the forum?

AFAIK we don't currently have delta sync capabilities in SG yet.

**Comment by househippo** [comment]
@tleyden 
Done
https://groups.google.com/forum/#!topic/mobile-couchbase/AHlX4af2uGY
