### ISSUE TITLE
Improvement - SG 3rd tier logging level - ex HTTP, HTTP+ , HTTP++

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#2240]
It be great to have more or less verbose logging to help debug issues vs mining data for operations and monitoring.

Here is an good example:

So right now to debug whats going on in the _changes feed you would set logging to "Changes+".  "Changes+" exposing what the _changes feed is doing  and dumps the whole document into the log which is a big issue for users who want fine grain control over data storage and access.

So it would be great to give the user the option of "ChagesNoDocs" or "Changes++"  write or not to write the whole doc in the logs.

**Comment by adamcfraser** [comment]
This sounds like the same functionality described in #2366 - logging full request/response.
