### ISSUE TITLE
Revs_limit growing beyond configured

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2243]
### Sync Gateway version
1.3.1

### Operating system
RedHat 7.2

###Setup
Both clusters have below setup details
3* CBS 
2* Syncgw
2* SyngwReplicator

revs_limit=5
replication is configured with both direction. running 33 cps with same documents are updating every 30 seconds, could see that revision history is growing beyond 5 in cluster2
and after sometime cluster1 is also 

###Observation

Both clusters having doc A with 5 revisions.
If any case replication is lagged for sometime and in source cluster doc A is updated and current revision is 10 , this time all 5 revisions will be replicated in shot and could see cluster2 is having 10 revisions including 1-5 also.

### Expected behavior
Replication lagging is expected in case of service down, Revision limit should not grow beyond 5 if current revision of cluster2 not in cluster1

### Actual behavior
Revision limit is increasing beyond 5 in destination which resulting in increase of revs limit in cluster1 also.

### Steps to reproduce
1.  Insert doc A and update till 5 revisions , both clusters should have current revision 5
2.  Stop replication 
3.  Update doc A till current revision reaches 10 and this time revs_limit does not have 5th revision in cluster 1
4 . After starting replication, cluster2 is having revs growing beyond 5

**Comment by adamcfraser** [comment]
If the document is in conflict, it can have more than revs_limit revisions.  It sounds like that's a possibility here, with your very low revs_limit.  If you make more than revs_limit changes before replicating, the target node isn't going to be able to identify a common ancestor with the documents you'd previously pushed, and you'll end up with conflicting branches in your revision tree.

The number of revisions won't return to revs_limit until the conflict is resolved.

**Comment by ArihantRk** [comment]
Thanks @adamcfraser , do you mean revs_limit can grow in destination cluster beyond even though we don't have conflicts in source cluster?
currently we don't have revision conflicts in source cluster, have set revs_limit=60 and updating documents for every 60 seconds. replication is set to bidirectional. Now also we are seeing revision limit growing in both source and destination clusters.

**Comment by ArihantRk** [comment]
@adamcfraser any recovery procedure for revision growth when revision growth is not due to conflicts.
