### ISSUE TITLE
log rotation based on maxage does not work on Windows

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2245]
### Sync Gateway version
1.4-42.   

### Operating system
Win 10.

### Config file
```
{
  "logging": {
    "default": {
      "logFilePath": "C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs\\sync_gateway_error.log",
      "logKeys": ["*"],
      "logLevel": "debug",
      "rotation": {
        "maxsize": 1,
        "maxage": 1,
        "maxbackups": 2,
        "localtime": true
      }
    }
  },
  "databases": {
    "db": {
      "server": "http://<Server_IP>:8091/",
      "bucket": "default",
      "users": {"GUEST": {"disabled": false,"admin_channels": ["*"]}}
    }
  }
}
```

### Steps to reproduce
1. Use the above config for sync gateway and restart sync gateway service.
2. From a remote system execute this command, where Sync_Gw_IP is the IP address of the windows system where sync gateway is running
```for ((i=1;i <= 10000;i += 1)); do curl -s http://<Sync_Gw_IP>:4984/ > /dev/null ; done```
3. Open a cmd window on the windows system Sync_Gw_IP and change the date using the command 
```date 1/26/2017```

### Expected behavior
- After the date change, the log should get backed up.
- A new empty log file should get created and any new logs should get logged in the new log file.

### Actual behavior
- No change in behavior, the logs continue to go into the existing log file.
- The timestamp in the logs change
```
2017-01-24T12:02:44.448-08:00 Starting server on :4984 ...
2017-01-26T12:04:03.098-08:00 HTTP:  #001: GET /
2017-01-26T12:04:31.027-08:00 HTTP:  #1000: GET /
2017-01-28T12:04:51.490-08:00 HTTP:  #1001: GET /
```

**Comment by ajres** [comment]
I'm not sure this is a valid test scenario, here is a section of the docs from the [lumberjack project](https://github.com/natefinch/lumberjack)

MaxAge is used to determine the maximum age of rotated files not the time to rotate the primary log file.

```
type Logger struct {
    // Filename is the file to write logs to.  Backup log files will be retained
    // in the same directory.  It uses <processname>-lumberjack.log in
    // os.TempDir() if empty.
    Filename string `json:"filename" yaml:"filename"`

    // MaxSize is the maximum size in megabytes of the log file before it gets
    // rotated. It defaults to 100 megabytes.
    MaxSize int `json:"maxsize" yaml:"maxsize"`

    // MaxAge is the maximum number of days to retain old log files based on the
    // timestamp encoded in their filename.  Note that a day is defined as 24
    // hours and may not exactly correspond to calendar days due to daylight
    // savings, leap seconds, etc. The default is not to remove old log files
    // based on age.
    MaxAge int `json:"maxage" yaml:"maxage"`

    // MaxBackups is the maximum number of old log files to retain.  The default
    // is to retain all old log files (though MaxAge may still cause them to get
    // deleted.)
    MaxBackups int `json:"maxbackups" yaml:"maxbackups"`

    // LocalTime determines if the time used for formatting the timestamps in
    // backup files is the computer's local time.  The default is to use UTC
    // time.
    LocalTime bool `json:"localtime" yaml:"localtime"`
    // contains filtered or unexported fields
}
```

**Comment by raghusarangapani** [comment]
I was under the assumption that the maximum number of days is calculated based on current system time. Isn't that the case? If not, what is the file's timestamp compared to?

**Comment by raghusarangapani** [comment]
I was under the impression that the file gets rotated after it is x days old.

Adam confirmed that only the max size triggers rotation. maxage determines how long rotated copies are retained. maxage doesn't trigger rotation. Closing.
