### ISSUE TITLE
logFilePath for windows paths need double slash

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2246]
### Sync Gateway version
1.4-42 x86_64

### Operating system
Win 10.

### Config file
```
{
  "logging": {
    "default": {
      "logFilePath": "C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log",
      "logKeys": ["*"],
      "logLevel": "debug",
      "rotation": {
        "maxsize": 1,
        "maxage": 1,
        "maxbackups": 2,
        "localtime": true
      }
    }
  },
  "databases": {
    "db": {
      "server": "http://<Server_IP>:8091/",
      "bucket": "default",
      "users": {"GUEST": {"disabled": false,"admin_channels": ["*"]}}
    }
  }
}
```
### Steps to reproduce
1.  Copy paste the above config file to serviceconfig.json
2. Restart sync gateway
3. Check C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs\\sync_gateway_error.log for errors

### Expected behavior
- Windows paths should be accepted without workarounds.

### Actual behavior
- Valid windows paths cannot be set, 

```"logFilePath": "C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log", ``` 

throws an error

```2017-01-23T11:56:31.112-08:00 FATAL: Error reading config file C:\Program Files (x86)\Couchbase\serviceconfig.json: invalid character 'P' in string escape code -- rest.ParseCommandLine() at config.go:504,```

If I enclose the path in single quotes, I see an error

``` 2017-01-23T11:55:55.079-08:00 FATAL: Error reading config file C:\Program Files (x86)\Couchbase\serviceconfig.json: invalid character ''' looking for beginning of value -- rest.ParseCommandLine() at config.go:504 ```

### Workaround:

From the log message, it looks like we are assuming \ to be a regex escape sequence
Setting it to a path with double slash (\\\\) works fine.

```"logFilePath": "C:\\Program Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs\\sync_gateway_error.log" ```

and the corresponding log

```2017-01-23 12:01:50.284971 I | Log entries will be written to the file C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log```

**Comment by ajres** [comment]
I can reproduce the issue with single backslashes on Windows 8.

**Comment by ajres** [comment]
Further Notes:

It appears that Windows paths can have single forward slashes e.g.

```
"C:/var/tmp/sync_gateway_error.log"
```

It also appears that it is possible to have paths with single back slashes if the path is enclosed in back quotes (like the sync function)
```
`C:\var\tmp\sync_gateway_error.log`
```

**Comment by raghusarangapani** [comment]
Logging and log rotation works with the below logFilePath formats:
```
"C:/tmp/sg_logs/sg_log_rotation.log"
`C:\tmp\sg_logs\sg_log_rotation.log`
`/tmp/sg_logs/sg_log_rotation.log`
"/tmp/sg_logs/sg_log_rotation.log"
```

**Comment by ajres** [comment]
The supported logFilePath formats for Windows have been added to the logRotation docs in a PR here: https://github.com/couchbaselabs/couchbase-mobile-portal/pull/543
