### ISSUE TITLE
(Perf) Erradic behavior during 20k / 20k user ramp up scenario

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2248]
### Sync Gateway version
1.4-42

### Operating system
CentOS 7

### Config file
```
{
    "interface":":4984",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": true,
    "log":["HTTP"],
    "cluster_config": {
        "server":"http://{{ couchbase_server_primary_node }}:8091",
        "data_dir":".",
        "bucket":"data-bucket"
    },
    "databases":{
        "db":{
            "feed_type":"DCPSHARD",
            "server":"http://{{ couchbase_server_primary_node }}:8091",
            "bucket":"data-bucket",
            "revs_limit":25,
            "channel_index":{
                "server":"http://{{ couchbase_server_primary_node }}:8091",
                "bucket":"index-bucket",
                "writer":{{ is_index_writer }}
            }
        }
    }
}

```

### Log output
Gateload output after test blows up - https://gist.github.com/sethrosetter/4e10c1b1ee3dbbfcb21c320e84a5837d

### Expected behavior
Scenario:
2sg 2ac 3cbs c3.2xlarge AWS instances
10k pushers / 10k pullers per sg (20k, 20k total)
test time: 1hr
ramp up: 1hr

I would expect near linear behavior during the the ramp up scenario

### Actual behavior
The test looks good for the beginning and the blows up into the test ~20min. The grafana dashboard is gone now. This same test is fine with 5k pushers / pullers per node

**Comment by adamcfraser** [comment]
Closing as there were known issues (https://github.com/couchbaselabs/sync-gateway-accel/issues/53) with this SG build.
