### ISSUE TITLE
Document Refuses To Be Deleted

### ISSUE THREAD

**Issue by 24601** [couchbase/sync_gateway#2253]
### Sync Gateway version
Version information is written on startup to the Sync Gateway log, or can 
be obtained by accessing the root endpoint (`/`) on the Sync Gateway Admin REST API.   

Couchbase Sync Gateway/1.3.1(16;f18e833)

### Operating system
The operating system you're running Sync Gateway on.

Debian Wheezy

### Config file
```javascript
function(doc){
  channel(doc.channels)
}
```

### Log output
Provide a link to a GitHub Gist containing relevant Sync Gateway log output when
the error occured. Do NOT paste the log output in the issue, just paste the
link to the Gist.

https://gist.github.com/24601/1b1af594da44c1d8ffbb4ff4a524abea

### Expected behavior
What should have happened?

The document should be deleted

### Actual behavior
What actually happened?

The document is not deleted, it still exists, just as it was before, but with a new revision id

### Steps to reproduce
1.  Try to delete document (we are using couchbase-lite-ios 1.3.1 on iOS 10.2 but have also used direct REST calls such as curl -XDELETE 'http://usernameredacted:passwordredacted@hostnameredacted:4984/voltaire/-RoeeE2yDT0cbp35WKBKDIw?rev=1899-995f5cc7fb2020bbbca8952d5ee6e069')

@gittristan

**Comment by tleyden** [comment]
@24601 Thanks for the issue report!

Can you add steps to reproduce?  Are you using Couchbase Lite or direct REST API calls?

**Comment by 24601** [comment]
@tleyden, thanks for the quick response. 

In production we are using Couchbase Lite, we have manually tested during troubleshooting of this issue with direct REST API calls. Both result in the same unexpected behavior. 

Output from the manual curl calls is always the same (with a different rev id of course): 
```
{"id":"-RoeeE2yDT0cbp35WKBKDIw","ok":true,"rev":"1900-4b2a62c6d22d31cdb2edc1c3e5f81ef3"}
```

I've updated Steps to reproduce above to note this. Any other detail I can provide, please let me know, happy to help however we can!

**Comment by tleyden** [comment]
> The document is not deleted, it still exists, just as it was before, but with a new revision id

This sounds like the typical Sync Gateway behavior to "Tombstone" the document, which adds a new revision with `_deleted: true`

How are you verifying that the doc still exists?

Also, is the concern that the doc still shows up in the Couchbase Lite app, or that it is using up more space on the Sync Gateway side (or causing confusion)

**Comment by 24601** [comment]
@tleyden that was my first thought, but the new doc indeed exists and there is no ``` _deleted: true ``` in the document and it is not a tombstone document, it is the full document and is still accessible both via our Couchbase Lite App, directly via URL using curl, and even the Sync Gateway's admin interface. 

The document is indeed there, and it's definitely not a tombstone. Our concern is not that it is taking space it is that it still shows up when it should be "gone", our users are reporting on certain documents (this happens every so often) that our delete function simply does not work (via our Couchbase Lite-backed app), and we have verified this in our testing (in-app via CBL, REST via curl commands, and REST via the Couchbase Sync Gateway admin interface). It is only on this specific document (and a handful of others) that this "Document Refuses To Die" behavior happens, we cannot discern a pattern or consistent factors between these documents but the log statements "No old revision "-RoeeE2yDT0cbp35WKBKDIw" / "1895-2b24c6b7da1469a889cae3e6676152eb" over a bunch of revisions seems to be unique to this phenomenon. 

Anything else we should check?

**Comment by adamcfraser** [comment]
@24601 If your document was in a conflicted state, with multiple non-deleted leaf revisions in the revision tree, then deleting the active revision would result in one of the other non-deleted leaf revisions becoming the active revision.  This sounds a bit like the scenario you're describing.

**Comment by 24601** [comment]
Ahhhh, @adamcfraser, that is a very wise and helpful point. I think you are correct, I will look into this.

**Comment by 24601** [comment]
@adamcfraser - you are correct sorry for filing an issue on something that is behavior-as-expected item that we didn't consider! Thank you as well, @tleyden!

**Comment by adamcfraser** [comment]
@24601 No worries - the forums are also a pretty good place to discuss this kind of question, in case you haven't already seen them:
https://forums.couchbase.com/c/mobile/sync-gateway
