### ISSUE TITLE
Inconsistent push of _user/ doc to _changes (cc vs di)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2258]
### Sync Gateway version
1.4-48

### Operating system
CentOS7

### Config file
```javascript
standard
```
### Expected behavior
Not sure

### Actual behavior
If I create a user via Admin REST API, WITHOUT channels

channel cache: _user/ doc is sent to that users _changes (longpoll since=0)
distibuted index: _user/ doc is NOT sent to that users _changes (longpoll since=0)

### Steps to reproduce
1. Create user via Admin REST API with no channels
2. Issue a _changes request for that user (longpoll since=0)

**Comment by adamcfraser** [comment]
This is expected, and down to the differences in sequence allocation between di and cc.

Worth reviewing in 2.0 as part of fix for role grant notifications in CC.

**Comment by adamcfraser** [comment]
Tracking this on #2277.
