### ISSUE TITLE
Add support for RHEL in service install scripts

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2259]
### Sync Gateway version
1.4

### Operating system
RedHat Enterprise Server

**Comment by raghusarangapani** [comment]
Installed sg_accel 1.4-103. Install works fine but the post install script sg_accel_service_install.sh errors out as below:
ERROR: unknown OS "RedHatEnterpriseServer"
All files got installed under /opt/couchbase-sg-accel and sg_accel was not running.

I edited the sg_accel_service_install.sh Line 233, to RedHat|CentOS|RedHatEnterpriseServer) snd got sg_accel working. There is no /etc/init.d/sg_accel file but “initctl stop/start sg_accel” works.

**Comment by ceejatec** [comment]
@raghusarangapani Do you still have access to the box where this was happening? In particular, can you see if the file /etc/lsb-release exists? We're trying to figure out where the value "RedHatEnterpriseServer" could possibly come from.

In any case, the suggested fix is probably correct, although I might just change it to RedHat*|CentOS)

**Comment by ceejatec** [comment]
By the by, if this was RedHat 7, there should not be an /etc/init.d/sg_accel file because RedHat 7 is based on systemd. So that much at least is expected.

**Comment by ceejatec** [comment]
Another (and probably better) solution would be to re-order the initial if statement so that the check for /etc/lsb-release is done *last*, as a fallback, after checking for /etc/redhat-release and /etc/debian_version.

**Comment by raghusarangapani** [comment]
I only have the RHEL-6.6 VM.
```
[vagrant@sga-rhel-6-6-x64 ~]$ cat /etc/lsb-release
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch

[vagrant@sga-rhel-6-6-x64 ~]$ uname -a
Linux sga-rhel-6-6-x64 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

[vagrant@sga-rhel-6-6-x64 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.6 (Santiago)
```

**Comment by ajres** [comment]
Installing RHEL 6.9 30 Day eval from rhel-server-6.9-x86_64-dvd.iso

**Comment by ajres** [comment]
There is a related ticket #2192 for Oracle Enterprise Linux

**Comment by ajres** [comment]
See PR #2766 for fix and test process
