### ISSUE TITLE
Empty response from _bulk_docs for rev conflict documents

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2261]
### Sync Gateway version
1.3.1

### Log output
https://gist.github.com/ArihantRk/3285763040fd7f1387f0992cb309c243

### Expected behavior
documents should get deleted from syncgateway with _deleted=true

### Actual behavior
Getting  **Empty reply from server** error

### Steps to reproduce
1.  put the documents which should arrive as same as posted in gist
2.  Use bulk_docs api to delete the document

**Comment by adamcfraser** [comment]
Please provide Sync Gateway logs (with log * enabled) for the failing request.  Thanks.

**Comment by ArihantRk** [comment]
@adamcfraser  i could only below . No response seen and nothing observed in error logs
#9678: POST /ptxdata/_bulk_docs  (ADMIN)
13:02:13.644631 2017-01-27T13:02:13.644+05:30 Bucket: WriteUpdate("cg4895_Group_PTX.doc", 0, ...) --> <nil> [934.788µs]

**Comment by ArihantRk** [comment]
@adamcfraser We are getting **BadStatusLine** error in python script.
issue observed in below scenario
A document has revision conflict 1-a3c and 1-x4s revision
hence 1-x4s will be winning revision as per ASCII. but this document has been deleted with _bulk_docs, which results in 2-ff2 revision but active revision is updated as 1-a3c.
Issue we are seeing when we try to delete this doc 1-a3c revision.

**Comment by ArihantRk** [comment]
@adamcfraser  any update on this.
we are getting many panic messages due to this empty response
```
 http: panic serving 192.168.5.72:39238: already contains rev "3-705cf405b62ca8a3d0ab89cc7d0fdd8b"#012goroutine 43122858 [running]:#012net/http.(*conn).serve.func1(0xc45a05de00)#012#011/usr/local/go/1.7.4/go/src/net/http/server.go:1491 +0x12a#012panic(0xa4b560, 0xc4315f8850)#012#011/usr/local/go/1.7.4/go/src/runtime/panic.go:458 +0x243#012github.com/couchbase/sync_gateway/db.RevTree.addRevision(0xc573296660, 0xc573253bf0, 0x22, 0xc573439c50, 0x22, 0x1, 0x0, 0x0, 0x0, 0x0)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/db/revtree.go:251 +0x378#012github.com/couchbase/sync_gateway/db.(*Database).Put.func1(0xc44f37e700, 0x1, 0xc423b52001, 0x1a7a, 0x1a7a)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:459 +0x2b2#012github.com/couchbase/sync_gateway/db.(*Database).updateDoc.func1(0xc423b52004, 0x1a7a, 0x1a7a, 0x0, 0x0, 0xc4bbbd8e90, 0x536836, 0xc4348e7d00, 0x33)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:545 +0x1be#012github.com/couchbase/sync_gateway/base.CouchbaseBucket.WriteUpdate.func1(0xc423b52004, 0x1a7a, 0x1a7a, 0x1235e00, 0x10000c4bbbd8ef8, 0x54c5b0, 0xc4bbbd8e5f, 0xc4348e7d00, 0x33)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/base/bucket.go:114 +0x47#012github.com/couchbase/go-couchbase.(*Bucket).WriteUpdate.func1(0xc423b52004, 0x1a7a, 0x1a7a, 0x0, 0xc4bbbd8ee0, 0x7f640967e501, 0x0, 0x10)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/go-couchbase/client.go:1020 +0x5c#012github.com/couchbase/go-couchbase.(*Bucket).update(0xc42015b500, 0xc4348e7d00, 0x33, 0x0, 0xc4a39440a0, 0xc4bbbd8f90, 0x411178, 0x10)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/go-couchbase/client.go:999 +0xcc#012github.com/couchbase/go-couchbase.(*Bucket).WriteUpdate(0xc42015b500, 0xc4348e7d00, 0x33, 0x0, 0xc5486e0120, 0x41094e, 0xc5741bae10)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/go-couchbase/client.go:1025 +0x10b#012github.com/couchbase/sync_gateway/base.CouchbaseBucket.WriteUpdate(0xc42015b500, 0xc42017fe00, 0x2f, 0xb3eeaa, 0x7, 0xc420187738, 0x7, 0x0, 0x0, 0x10d6300, ...)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/base/bucket.go:118 +0x99#012github.com/couchbase/sync_gateway/base.(*CouchbaseBucket).WriteUpdate(0xc4202523f0, 0xc4348e7d00, 0x33, 0x0, 0xc5741bae10, 0xc54e497fc0, 0xc4bbbd9118)#012#011<autogenerated>:100 +0xb8#012github.com/couchbase/sync_gateway/db.(*Database).updateDoc(0xc54e4975e0, 0xc4348e7d00, 0x33, 0x0, 0xc573296180, 0xc4bbbd9490, 0x411c45, 0xc4bbbd98c8, 0x10)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:741 +0x4da#012github.com/couchbase/sync_gateway/db.(*Database).Put(0xc54e4975e0, 0xc4348e7d00, 0x33, 0xc573439c20, 0xc432311301, 0x96, 0x96, 0x200000003)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:461 +0x3d8#012github.com/couchbase/sync_gateway/rest.(*handler).handleBulkDocs(0xc5741bacf0, 0x0, 0x0)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/rest/bulk_api.go:440 +0x824#012github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc5741bacf0, 0xbf3ef8, 0x0, 0x0)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:221 +0x2c1#012github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x10dc400, 0xc4e916d520, 0xc4fc318d20)#012#011/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:96 +0x80#012net/http.HandlerFunc.ServeHTTP(0xc4203743e0, 0x10dc40
```

**Comment by adamcfraser** [comment]
The revision tree for that document is in an unusual state - presumably due to previous updates that were made to the document.  

The revision tree has three roots, with the following nodes on each branch

 - 2-ff (deleted)
   - 4-cd
     - 5-f1
       - 6-19 (deleted)
 - 1-c1
   - 2-fd
     - 3-23 
 - 1-a3

Somehow revision 2-ff was written as a separate root, instead of as a child of 1-a3, despite the fact that it's revision ID is the one that would be generated for a child of 1-a3.  When you try to issue a delete of 1-a3, it's rejecting that update because the revision ID already exists in the tree.

Do you know how the document got into this state?

**Comment by ArihantRk** [comment]
Thanks @adamcfraser , We are getting this while running traffic. Not sure exactly how documents got into in this situation. but this is caused by sg-replication(two way replication).

can you let us know how revision Id's going into different branches and what scenarios this happens.

**Comment by ArihantRk** [comment]
@adamcfraser ,any update on this.

We are seeing 2 types of conflicts
1. Conflicts due to replication lag(revision growth due to missing ancestor in remote cluster)
2. Conflicts by application in active-active replication

we are running conflicts resolution tool in both clusters.  replication is configured in both directions.
All CRUD operations are done through syncgateway, not sure how documents are getting into this situation.

how do we identify this issue and any recovery procedure to resolve this issue?

**Comment by ArihantRk** [comment]
@adamcfraser any input will be helpful.

**Comment by adamcfraser** [comment]
Avoiding the empty bulk_docs response in this scenario requires #2568.

To avoid this problem in the first place, need to ensure you don't end up with the multiple roots in the revision tree.  The normal root cause of that is running with revs_limit too low in Sync Gateway.
