### ISSUE TITLE
item count doesn`t stop to grow

### ISSUE THREAD

**Issue by sebastian989** [couchbase/sync_gateway#2263]
Hi, I did update the sync gateway to version 1.3, the couchbase DB has 72086 documents but when I restart the sync gateway service, the item Count is growing without stop, even the count is over 1 million, I don´t know from where the sync gateway is taking these documents, can someone help me please.

**Comment by sebastian989** [comment]
this is the log:

Changes+: Notifying that "crystal-sync-db" changed (keys="{*}") count=29862
2017-01-27T21:28:21.013Z Cache: Received #60499 after 854ms ("7cc2aa4fc38a2a0fc3aec387c363d53c" / "1-2cac91faf7b3f5e5fd56ff377bdb5466")
2017-01-27T21:28:21.013Z Cache:   Deferring #60499 (1 now waiting for #60498...#60498)
2017-01-27T21:28:21.013Z Cache: Received #60498 after 854ms ("7cc2aa4fc38a2a0fc3aec387c3079ec8" / "1-2cac91faf7b3f5e5fd56ff377bdb5466")
2017-01-27T21:28:21.013Z Cache:     #60498 ==> channel "*"
2017-01-27T21:28:21.013Z Cache:     #60499 ==> channel "*"
2017-01-27T21:28:21.013Z Changes+: Notifying that "crystal-sync-db" changed (keys="{*}") count=29863
2017-01-27T21:28:21.013Z Cache: Received #60501 after 848ms ("7cc2aa4fc38a2a0fc3aec387c37a7c37" / "1-2cac91faf7b3f5e5fd56ff377bdb5466")
2017-01-27T21:28:21.013Z Cache:   Deferring #60501 (1 now waiting for #60500...#60500)
2017-01-27T21:28:21.013Z Cache: Received #60500 after 848ms ("7cc2aa4fc38a2a0fc3aec387c3665778" / "1-2cac91faf7b3f5e5fd56ff377bdb5466")
2017-01-27T21:28:21.013Z Cache:     #60500 ==> channel "*"
2017-01-27T21:28:21.013Z Cache:     #60501 ==> channel "*"
2017-01-27T21:28:21.013Z Changes+: Notifying that "crystal-sync-db" changed (keys="{*}") count=29864
2017-01-27T21:28:21.014Z Cache: Received #60503 after 848ms ("7cc2aa4fc38a2a0fc3aec387c3a3ba1e" / "1-2cac91faf7b3f5e5fd56ff377bdb5466")
2017-01-27T21:28:21.014Z Cache:   Deferring #60503 (1 now waiting for #60502...#60502)
2017-01-27T21:28:21.014Z Cache: Received #60502 after 848ms ("7cc2aa4fc38a2a0fc3aec387c392a19a" / "1-2cac91faf7b3f5e5fd56ff377bdb5466")
2017-01-27T21:28:21.014Z Cache:     #60502 ==> channel "*"
2017-01-27T21:28:21.014Z Cache:     #60503 ==> channel "*"

**Comment by tleyden** [comment]
Can you post your sync gw config with any sensitive info removed?

**Comment by tleyden** [comment]
> the item Count is growing without stop, even the count is over 1 million

Where do see this?

**Comment by sebastian989** [comment]
Sure, this is the sync gw config:

`{
	"log": ["CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Cache", "Shadow", "Shadow+", "Changes", "Changes+"],
	"compressResponses": true,
	"adminInterface": ":4985",
	"interface": ":4984",
	"databases": {
		"*****": {
			"server": "http://localhost:8091",
			"bucket": "*****",
			"revs_limit": 5,
			"filter": `function(doc) {
                         if( doc.type == "filter"  || doc.type=="material_app" || doc.type == "brand" || doc.type == "campaign" || doc.type=="margin") {
                         	return true;
                         }
                         return false;
                         }`,
			"sync": `function(doc, olddoc) {
                         if( doc.type == "filter"  || doc.type == "material_app" || doc.type == "brand" || doc.type == "campaign") {
                           channel("sync_catalog");
                         } else if(doc.type == "tracking") {
                              if (doc.seller_code == null) {
                                throw({forbidden : "List must have an seller code"})
                              }
                              channel(doc.seller_code);
                         } else if(doc.type == "portfolio") {
                                channel(doc.salesmanCode);
                         } else if(doc.type == "appointment") {
                                channel("appointment_" + doc.user_code);
                        	}
                         }`,
			"users": {
				"GUEST": {
					"disabled": true,
					"admin_channels": ["*"]
				}
			},
			"shadow": {
				"server": "http://localhost:8091",
				"bucket": "crystal-backend-db",
				"username": "*****",
				"password": "*****"
			}
		}
	}
}`

**Comment by sebastian989** [comment]
{
	"log": ["CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Cache", "Shadow", "Shadow+", "Changes", "Changes+"],
	"compressResponses": true,
	"adminInterface": ":4985",
	"interface": ":4984",
	"databases": {
		"*****": {
			"server": "http://localhost:8091",
			"bucket": "*****",
			"revs_limit": 5,
			"filter": `function(doc) {
                         if( doc.type == "filter"  || doc.type=="material_app" || doc.type == "brand" || doc.type == "campaign" || doc.type=="margin") {
                         	return true;
                         }
                         return false;
                         }`,
			"sync": `function(doc, olddoc) {
                         if( doc.type == "filter"  || doc.type == "material_app" || doc.type == "brand" || doc.type == "campaign") {
                           channel("sync_catalog");
                         } else if(doc.type == "tracking") {
                              if (doc.seller_code == null) {
                                throw({forbidden : "List must have an seller code"})
                              }
                              channel(doc.seller_code);
                         } else if(doc.type == "portfolio") {
                                channel(doc.salesmanCode);
                         } else if(doc.type == "appointment") {
                                channel("appointment_" + doc.user_code);
                        	}
                         }`,
			"users": {
				"GUEST": {
					"disabled": true,
					"admin_channels": ["*"]
				}
			},
			"shadow": {
				"server": "http://localhost:8091",
				"bucket": "crystal-backend-db",
				"username": "*****",
				"password": "*****"
			}
		}
	}
}

**Comment by sebastian989** [comment]
Sure, this is the sync gw config:

{
	"log": ["CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Cache", "Shadow", "Shadow+", "Changes", "Changes+"],
	"compressResponses": true,
	"adminInterface": ":4985",
	"interface": ":4984",
	"databases": {
		"*****": {
			"server": "http://localhost:8091",
			"bucket": "*****",
			"revs_limit": 5,
			"filter": `function(doc) {
                         if( doc.type == "filter"  || doc.type=="material_app" || doc.type == "brand" || doc.type == "campaign" || doc.type=="margin") {
                         	return true;
                         }
                         return false;
                         }`,
			"sync": `function(doc, olddoc) {
                         if( doc.type == "filter"  || doc.type == "material_app" || doc.type == "brand" || doc.type == "campaign") {
                           channel("sync_catalog");
                         } else if(doc.type == "tracking") {
                              if (doc.seller_code == null) {
                                throw({forbidden : "List must have an seller code"})
                              }
                              channel(doc.seller_code);
                         } else if(doc.type == "portfolio") {
                                channel(doc.salesmanCode);
                         } else if(doc.type == "appointment") {
                                channel("appointment_" + doc.user_code);
                        	}
                         }`,
			"users": {
				"GUEST": {
					"disabled": true,
					"admin_channels": ["*"]
				}
			},
			"shadow": {
				"server": "http://localhost:8091",
				"bucket": "crystal-backend-db",
				"username": "*****",
				"password": "*****"
			}
		}
	}
}

**Comment by sebastian989** [comment]
Sure, this is the sync gw config:

{
	"log": ["CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Cache", "Shadow", "Shadow+", "Changes", "Changes+"],
	"compressResponses": true,
	"adminInterface": ":4985",
	"interface": ":4984",
	"databases": {
		"*****": {
			"server": "http://localhost:8091",
			"bucket": "*****",
			"revs_limit": 5,
			"filter": `function(doc) {
                         if( doc.type == "filter"  || doc.type=="material_app" || doc.type == "brand" || doc.type == "campaign" || doc.type=="margin") {
                         	return true;
                         }
                         return false;
                         }`,
			"sync": `function(doc, olddoc) {
                         if( doc.type == "filter"  || doc.type == "material_app" || doc.type == "brand" || doc.type == "campaign") {
                           channel("sync_catalog");
                         } else if(doc.type == "tracking") {
                              if (doc.seller_code == null) {
                                throw({forbidden : "List must have an seller code"})
                              }
                              channel(doc.seller_code);
                         } else if(doc.type == "portfolio") {
                                channel(doc.salesmanCode);
                         } else if(doc.type == "appointment") {
                                channel("appointment_" + doc.user_code);
                        	}
                         }`,
			"users": {
				"GUEST": {
					"disabled": true,
					"admin_channels": ["*"]
				}
			},
			"shadow": {
				"server": "http://localhost:8091",
				"bucket": "*****",
				"username": "*****",
				"password": "*****"
			}
		}
	}
}

**Comment by sebastian989** [comment]
Sure, this is the sync gw config:

`
{
	"log": ["CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Cache", "Shadow", "Shadow+", "Changes", "Changes+"],
	"compressResponses": true,
	"adminInterface": ":4985",
	"interface": ":4984",
	"databases": {
		"*****": {
			"server": "http://localhost:8091",
			"bucket": "*****",
			"revs_limit": 5,
			"filter": `function(doc) {
                         if( doc.type == "filter"  || doc.type=="material_app" || doc.type == "brand" || doc.type == "campaign" || doc.type=="margin") {
                         	return true;
                         }
                         return false;
                         }`,
			"sync": `function(doc, olddoc) {
                         if( doc.type == "filter"  || doc.type == "material_app" || doc.type == "brand" || doc.type == "campaign") {
                           channel("sync_catalog");
                         } else if(doc.type == "tracking") {
                              if (doc.seller_code == null) {
                                throw({forbidden : "List must have an seller code"})
                              }
                              channel(doc.seller_code);
                         } else if(doc.type == "portfolio") {
                                channel(doc.salesmanCode);
                         } else if(doc.type == "appointment") {
                                channel("appointment_" + doc.user_code);
                        	}
                         }`,
			"users": {
				"GUEST": {
					"disabled": true,
					"admin_channels": ["*"]
				}
			},
			"shadow": {
				"server": "http://localhost:8091",
				"bucket": "*****",
				"username": "*****",
				"password": "*****"
			}
		}
	}
}
`

**Comment by sebastian989** [comment]
Seems like the main bucked has strange metadata because I did a backup of this, when I restore it in another server and start a new sync gateway it happens again
