### ISSUE TITLE
_User documents are not replicating by sg-replicate

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2268]
### Sync Gateway version
1.3.1

### Operating system
RedHat 7.2
###Setup details
Both clusters having below setup
3*CBS nodes
2*syncgw nodes
2*syncgw replicators

We are using sg-replicate to sync between clusters.
Following https://groups.google.com/forum/#!topic/mobile-couchbase/xGSHfmgHN10
User documents are not replicating to other cluster. Anycase user can not login into other cluster.

### Expected behavior
All documents which are created in cluster1 should replicate to cluster2

### Actual behavior
No User documents are replicating to other cluster

### Steps to reproduce
1.  Setup as above
2.  Create user document in cluster1
No user document exists in cluster2

**Comment by adamcfraser** [comment]
This is by design - sg-replicate doesn't currently replicate security information between clusters, just application data.

**Comment by ddash1** [comment]
@adamcfraser what is the design solution to replicate the users across clusters(replicated)? How do you advise to make sure the channel and access information is available on the replicated cluster if the _user docs are not replicated?

based on a comment from @tleyden  in the thread mentioned in the issue description, it was an earlier limitation. Please check...
   "Yeah, it's a known limitation of sg-replicate that it doesn't sync user documents.
     I don't know what the plan is for that -- I filed a ticket to track the conversation"

Now are you identifying this as a design choice only and not a limitation? What is the motivation...
How are other users getting around this limitation/design choice? We feel this as a basic requirement for any replicated database and the app should not be managing it...for reference consider any major db replications - sql or nosql.

**Comment by adamcfraser** [comment]
The goal of sg-replicate - and by extension embedding the previously standalone sg-replicate application within Sync Gateway itself - is to enable standard Couchbase Mobile replication between two Sync Gateway nodes.  It uses the same replication algorithm used for the rest of the Couchbase Mobile stack (e.g. Couchbase Lite-to-Couchbase Lite, Couchbase Lite-to-SG).  

The intention is to provide a way to safely perform multi-master replication of versioned data (i.e. documents with MVCC metadata) between Sync Gateway clusters.  Non-versioned data (including users and roles, but also sessions, checkpoints, and other replication metadata) can't be safely replicated between clusters in this way.

The most common approach for shared credentials between Sync Gateway clusters would be to have both clusters leverage the same custom authentication provider (as described here: https://developer.couchbase.com/documentation/mobile/1.3/guides/authentication/custom-authentication/index.html).

**Comment by ddash1** [comment]
@adamcfraser thanks. We are using the custom approach. 
But using the custom authentication provider causes unnecessary cross site traffic and management on our side. More so making sure that all the sites(consider having more than 2 sites, in multi pod setup) have the user created and blocking the user creation response for the same does not sound good design. We sure can use some messaging mechanism and audit to cover this but dont you think it should be part of the DB replication when its committed data. 

I see the motivation for the versioned data but then Couchbase should have a way to replicate the non versioned data in the sync bucket. Its a part of the same DB that needs to be replicated for Disaster recovery and similar usecases. Leaving the versioned data not replicated is incomplete from a replication context. Let me ask you this and maybe this is what we need to focus on, Considering Sync GW being used for business critical data store, What is the Couchbase design approach for sync bucket replication for geo/disaster recovery or active/active POD setups?
