### ISSUE TITLE
Starting sync gateway from command line does not always report the right status

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2270]
### Sync Gateway version
1.4-55   

### Operating system
Win 10

### Config file
```
{
   "logging": {
      "default": {
         "logLevel": "debug", 
         "logFilePath": "/12345/1231/131231.log", 
         "rotation": {
            "maxbackups": 2, 
            "maxsize": 1, 
            "maxage": 30, 
            "localtime": true
          }, 
         "logKeys": ["*"]
      }
   }, 
   "databases": {
      "db": {
         "bucket": "data-bucket", 
         "users": {"GUEST": {"disabled": false, "admin_channels": ["*"]}}, 
         "server": "http://<Server_IP>:8091"
      }
   }
}
```
### Steps to reproduce
1.  Use the above config file for sync gateway, which has an invalid logFilePath.
2.  Start the SyncGateway service through command line:
` net start SyncGateway`

### Expected behavior
SyncGateway service should fail to start

### Actual behavior
Sometimes, the command throws an error as expected, but sometimes, it reports that the service started successfully but the service is not running.
```
C:\Users\Administrator>net start "Couchbase Sync Gateway"

The Couchbase Sync Gateway service was started successfully.


C:\Users\Administrator>net start syncgateway

The Couchbase Sync Gateway service was started successfully.


C:\Users\Administrator>echo %errorlevel%
0

C:\Users\Administrator>sc query syncgateway

SERVICE_NAME: syncgateway
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1067  (0x42b)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

In the Windows event viewer, I see:
```
Information:
Starting Sync Gateway service using command: `C:\Program Files (x86)\Couchbase\\sync_gateway.exe C:\Program Files (x86)\Couchbase\\serviceconfig.json`
Event ID: 1
Logged: 2/2/2017 10:36:18 AM
Level: Information
Log Name: Application
Source: SyncGateway

Error:
Sync Gateway exiting with exit status 1
Event ID: 3
Logged: 2/2/2017 10:36:18 AM
Level: Error
Log Name: Application
Source: SyncGateway
```

**Comment by ajres** [comment]
This looks like it might be a race condition in the Windows service wrapper. The wrapper starts Sync Gateway in a go routine and always returns success. If Sync Gateway failes to start the go routine will panic and the service wrapper will exit. Depending on timing Windows may report the service as successfully started but the service then dies.

**Comment by geocine** [comment]
I still encounter this issue using **couchbase-sync-gateway-community_1.4.0-2_x86_64.exe** on Windows 7
