### ISSUE TITLE
Rename SG_Accel in uninstaller UI (Windows)

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2292]
### Sync Gateway version
1.4-68

### Operating system
Win 10

### Steps to reproduce
1.  Install couchbase-sg-accel-enterprise_1.4-68_x86_64
2. Browse to Control Panel -> Programs -> Programs & Features

### Expected behavior
Sync Gateway Accelerator should say "Couchbase Sync Gateway Accelerator"

### Actual behavior
Sync Gateway says "Couchbase Sync Gateway"
Sync Gateway Accelerator says "SG_Accel"

**Comment by raghusarangapani** [comment]
The upgrade prompt needs to be renames as well, it says "This setup will perform an upgrade of 'SG_Accel'. Do you want to continue?"

**Comment by raghusarangapani** [comment]
Installer UI says SG_Accel everywhere

**Comment by adamcfraser** [comment]
@ajres If this is actually just an update to https://github.com/couchbase/sync_gateway/blob/master/build/windows/InstallShield_2014_Projects/sg-accel.ism#L4403 and not a build change, can you go ahead and merge?
