### ISSUE TITLE
Error upon running sgcollect_info.exe on win 10

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2299]
### Sync Gateway version
1.4-71

### Operating system
Win 10

### Log output

https://gist.github.com/raghusarangapani/adcf589eaa21e3965c8d9a76125c969f

### Steps to reproduce
1.  C:\Program Files (x86)\Couchbase\tools>sgcollect_info.exe -v out.zip

### Expected behavior
No errors

### Actual behavior
- Lots of Exit code 1s, 
- compression errors
- gozip errors

**Comment by adamcfraser** [comment]
@raghusarangapani Is this a regression vs. 1.3.1?

**Comment by ajres** [comment]
The Exit Code 1's are expected, this is sgcollect_info trying all the known paths/names of the sg log file. All but one will fail on any system. It usually prints the path of the file it's attempting to locate, so you should be able to validate that those files do not exist on the system under test.

**Comment by ajres** [comment]
Not sure about the compression/gozip errors, does the .zip get created and contain the expected files?

**Comment by raghusarangapani** [comment]
What about the Exit code 1s with the Running go tool pprof...

**Comment by raghusarangapani** [comment]
Tested with 1.3.1:

https://gist.github.com/raghusarangapani/b2e70ad2b52d3fb302704fd8d8766f08

I see the same compression and gozip errors. So not a regression. It also collected 25 items, same as 1.4.1

**Comment by raghusarangapani** [comment]
The out.zip created by 1.4 has the following files. Andy is probably a better person to decide if these are the expected files:

```
C:\Program Files (x86)\Couchbase\tools\out\sgcollect_info_DESKTOP-H4V90F3_20170208-202712>dir
 Volume in drive C has no label.
 Volume Serial Number is A8F8-BE3B

 Directory of C:\Program Files (x86)\Couchbase\tools\out\sgcollect_info_DESKTOP-H4V90F3_20170208-202712

02/08/2017  12:28 PM    <DIR>          .
02/08/2017  12:28 PM    <DIR>          ..
02/08/2017  12:28 PM               376 db_db_status.log
02/08/2017  12:27 PM             5,507 expvars_json.log
02/08/2017  12:28 PM               464 goroutine.pdf
02/08/2017  12:28 PM               464 goroutine.raw
02/08/2017  12:28 PM               466 goroutine.text
02/08/2017  12:28 PM               454 heap.pdf
02/08/2017  12:28 PM               454 heap.raw
02/08/2017  12:28 PM               456 heap.text
02/08/2017  12:28 PM               988 pprof_http_goroutine.log
02/08/2017  12:28 PM             3,010 pprof_http_heap.log
02/08/2017  12:28 PM               275 pprof_http_profile.log
02/08/2017  12:28 PM               460 profile.pdf
02/08/2017  12:28 PM               460 profile.raw
02/08/2017  12:28 PM               462 profile.text
02/08/2017  12:28 PM               489 running_db_db_config.log
02/08/2017  12:28 PM               758 running_server_config.log
02/08/2017  12:28 PM               337 server_status.log
02/08/2017  12:28 PM             1,345 serviceconfig.json
02/08/2017  12:28 PM               817 sgcollect_info_options.log
02/08/2017  12:27 PM             1,621 sg_accel_access.log
02/08/2017  12:27 PM             1,614 sg_accel_error.log
02/07/2017  12:25 AM        19,396,608 sync_gateway.exe
02/08/2017  12:27 PM           285,021 sync_gateway.log
02/08/2017  12:27 PM             1,649 sync_gateway_access.log
02/08/2017  12:27 PM             2,873 sync_gateway_error.log
              25 File(s)     19,707,428 bytes
               2 Dir(s)  50,712,195,072 bytes free
```

**Comment by ajres** [comment]
By default the get_paths_from_expvars() is going to use the following URL

http://127.0.0.1:4985/_expvar

This should be printed out at the start of sgcollect_info

e.g. 

`Using Sync Gateway URL: http://127.0.0.1:4985/_expvar`

Can you confirm that you can connect to the endpoint logged by sgcollect_info using a browser or curl command.

**Comment by raghusarangapani** [comment]
I can connect to http://127.0.0.1:4985/_expvar and http://127.0.0.1:4985 using a browser.

However, on the console, I see 
`
Using Sync Gateway URL: http://127.0.0.1:4985
`
and not
`
Using Sync Gateway URL: http://127.0.0.1:4985/_expvar
`

**Comment by ajres** [comment]
Sorry, that was a typo from me, your output is correct.

The range of files in the .ZIP looks good, but can you sanity check the contents of:
goroutine.text
heap.text
profile.text
pprof_http_goroutine.log
pprof_http_heap.log
pprof_http_profile.log

To make sure they contain data and not error messages

**Comment by raghusarangapani** [comment]
goroutine.text
```
'go' is not recognized as an internal or external command, operable program or batch file.
```
heap.text
```
'go' is not recognized as an internal or external command, operable program or batch file.
```
profile.text
```
'go' is not recognized as an internal or external command, operable program or batch file.
```
pprof_http_goroutine.log - The file content looks like hexdump of a binary.
pprof_http_heap.log- The file content looks like hexdump of a binary with some stats.
pprof_http_profile.log - The file has a ton of special/NULL characters

**Comment by ajres** [comment]
Go is listed as a optional on the [docs page](https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/sgcollect-info/index.html)

So I think the contents look fine.

**Comment by ajres** [comment]
@raghusarangapani please review this ticket and comment here if you think there are outstanding issues that have not been addressed and I'll update.

**Comment by raghusarangapani** [comment]
My only concern was that the output asks users to report the issue:
```
Exception during compression: [Error 2] The system cannot find the file specified
IMPORTANT:
  Compression using gozip failed.
  Falling back to python implementation.
  Please let us know about this and provide console output.
```
May be we can document that this error is expected if go is not available?

**Comment by ajres** [comment]
@raghusarangapani 

I agree that we should add this to the docs where we already have a note about go being optional.

**Comment by jamesnocentini** [comment]
If there's documentation content that only applies to 1.3 or 1.4, you can use the following tags in the `.md` file:

```
{% if site.version == '1.3' %}
  // ...
{% elsif site.version == '1.4' %}
  // ...
{% endif %}
```

Should be in the style guide but we haven't got one yet.

**Comment by ajres** [comment]
Updated the docs, raised [PR](https://github.com/couchbaselabs/couchbase-mobile-portal/pull/580)

**Comment by ajres** [comment]
Ooops, missed the striping comment, I'll update the doc

**Comment by ajres** [comment]
Added the conditionals around the 1.4 only content, can't preview in my .md editor

**Comment by jamesnocentini** [comment]
@ajres I wanted to give the `{% %}` tags a go to maximize on content reuse but the fact it breaks the markdown syntax and hurts readability isn't ideal. So I created two copies of the file with the changes specific to each one ([1.3](https://github.com/couchbaselabs/couchbase-mobile-portal/blob/dev/md-docs/_13/guides/sync-gateway/sg-collect-info.md) and [1.4](https://github.com/couchbaselabs/couchbase-mobile-portal/blob/dev/md-docs/_14/guides/sync-gateway/sg-collect-info.md)) from https://github.com/couchbaselabs/couchbase-mobile-portal/pull/580.
