### ISSUE TITLE
Sync gateway going into changes loops

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2309]
This happened after changing the default di functional job to target 3 Couchbase Server cluster + 2 accels

### Sync Gateway version
1.4-82
### Operating system
CentOS 7

### Config file
normal

### Log output
Where the looping starts - https://gist.github.com/sethrosetter/84f34115e38ffecb54af1744e0311f95
Section of the loop - https://gist.github.com/sethrosetter/53fe2a5868e6134c6b3d5b9ded6e14e9

sg_accel 1 
```
2017/02/13 21:49:26 janitor: adding pindex: data-bucket593656bfec809e3aa478fe268cf7632c_1ac2ef92e71583d2_103fc5fb
2017/02/13 21:49:26 janitor: adding pindex: data-bucket593656bfec809e3aa478fe268cf7632c_1ac2ef92e71583d2_84003db0
2017/02/13 21:49:26 janitor: adding pindex: data-bucket593656bfec809e3aa478fe268cf7632c_1ac2ef92e71583d2_120a6de6
2017/02/13 21:49:26 janitor: startPIndex, OpenPIndex error, cleaning up and trying NewPIndex, path: ./data-bucket593656bfec809e3aa478fe268cf7632c_1ac2ef92e71583d2_120a6de6.pindex, err: pindex: could not load PINDEX_META_FILENAME, path: ./data-bucket593656bfec809e3aa478fe268cf7632c_1ac2ef92e71583d2_120a6de6.pindex, err: open ./data-bucket593656bfec809e3aa478fe268cf7632c_1ac2ef92e71583d2_120a6de6.pindex/PINDEX_META: no such file or directory
2017-02-13T21:49:26.960-05:00 FATAL: Unable to verify bucket sequence index parity: IndexBucketStable clock is not AllBefore the data bucket clock -- indexwriter.NewSyncGatewayPIndex() at sgw_pindex.go:51
```

sg_accel 2 - 
```
nagerSleepInitMS":0,"dataManagerSleepMaxMS":2000,"feedBufferSizeBytes":0,"feedBufferAckThreshold":0} SourcePartitions:256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319 Nodes:map[57c7ea9ce8e004fa:0xc420229560]}
2017/02/13 21:49:26 janitor: adding pindex: data-bucket593656bfec809e3aa478fe268cf7632c_1ac2ef92e71583d2_7332d0c7
2017-02-13T21:49:26.589-05:00 FATAL: Unable to verify bucket sequence index parity: IndexBucketStable clock is not AllBefore the data bucket clock -- indexwriter.NewSyncGatewayPIndex() at sgw_pindex.go:51
```

### Steps to reproduce
1.  Failing test - testsuites/syncgateway/functional/tests/test_longpoll.py::test_longpoll_changes_parametrized[sync_gateway_default_functional_tests-50-100]

**Comment by sethrosetter** [comment]
Failing test run - http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/189/console

**Comment by adamcfraser** [comment]
The looping is SG waiting for the stable sequence to catch up to the user doc update, and looks like a direct result of the accel issues.

**Comment by adamcfraser** [comment]
The accel issues look like what would happen if the data bucket was flushed, but the index bucket wasn't.  If you don't think that's the case, may need some assistance reviewing exactly what's going on.

@tleyden The index parity check is still logging fatal in accel - is that intentional?  I don't think it should be fatal, since it's valid in a rollback scenario.

**Comment by tleyden** [comment]
> The index parity check is still logging fatal in accel - is that intentional? I don't think it should be fatal, since it's valid in a rollback scenario.

This was changed to a warning in 

https://github.com/couchbase/sync_gateway/commit/027407219f9489a755323f58c1395623d53f4103

and is on the master branch:

https://github.com/couchbase/sync_gateway/blob/master/db/kv_change_index_reader.go#L90-L92

@sethrosetter which Sync Gw commit is this being tested against?

**Comment by adamcfraser** [comment]
@tleyden It's the corresponding change in accel that hasn't been updated:
https://github.com/couchbaselabs/sync-gateway-accel/blob/master/indexwriter/sgw_pindex.go#L51

**Comment by tleyden** [comment]
Ok, I missed that in the PR to change from an error to a warning.  Will send an SG-accel PR to fix that.

**Comment by tleyden** [comment]
I just pushed up PR: https://github.com/couchbaselabs/sync-gateway-accel/pull/98

**Comment by adamcfraser** [comment]
Merged - should be fixed.
