### ISSUE TITLE
Duplicate doc being returned in subsequent changes request

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2313]
### Sync Gateway version
1.4-86

### Operating system
CentOS 7

### Config file
standard

### Log output
Failing test - http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/196/testReport/junit/testsuites.syncgateway.functional.tests/test_conflicts/test_winning_conflict_branch_revisions_sync_gateway_default_functional_tests_/
SG Logs - http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-di/196/artifact/results/logs/test_winning_conflict_branch_revisions%5Bsync_gateway_default_functional_tests%5D-2017-02-14-14-52-35-sglogs.zip

### Expected behavior
changes with since == "7-0" should return 7-foo

### Actual behavior
changes with since == "7-0" should return 6-2bc4bb75b53f468e611317c44de897ed
6-2bc4bb75b53f468e611317c44de897ed has already been returned for since == "6-0"

**Comment by adamcfraser** [comment]
Closing based on age.
