### ISSUE TITLE
support for 'application/json' in the _bulk_get

### ISSUE THREAD

**Issue by davengeo** [couchbase/sync_gateway#2318]
Hi guys

I have made some experiments with pouchdb and sync-gateway and it seems there is a trivial mismatch between the content type accepted by the sync-gateway and the one required by pouchdb.

I have shown this in a small project in angular2 here https://github.com/davengeo/pouch-experiment
which requires 'a man in the middle' doing the correct translation of content types: https://github.com/davengeo/middle-patch

There are some screenshots I have made as outcome of the experiment.

with patching: https://github.com/davengeo/pouch-experiment/blob/master/screenshots/experiment-1.png
without patching: https://github.com/davengeo/pouch-experiment/blob/master/screenshots/experiment-3.png
The whole point of the content type: https://github.com/davengeo/pouch-experiment/blob/master/screenshots/experiment-2.png

The gain in performance seems remarkable IMO and I think it deserves a try. Besides this I am not aware if this trivial translation cover all the corner cases, but it seems working in the happy path.

Please let me know if I can help in any other way. I am posting a similar comment in the pouchdb issues site.
https://github.com/pouchdb/pouchdb/issues/5820

Is it possible to make this enhancement?

**Comment by davengeo** [comment]
BTW It seems like in the documentation tell us that _bulk_get accepts 'application/json' :)

https://developer.couchbase.com/documentation/mobile/1.3/references/sync-gateway/rest-api/index.html#!/database/post_db_bulk_get

But this is not true for the at least for the version 1.3.x I am using here.

**Comment by jchris** [comment]
The implementation code would need to be patched https://github.com/couchbase/sync_gateway/blob/f18e83359777f9e1c8ba6d16282c276a9024715c/rest/bulk_api.go#L287

Maybe mimicking the usage of writeDoc above? https://github.com/couchbase/sync_gateway/blob/f18e83359777f9e1c8ba6d16282c276a9024715c/rest/bulk_api.go#L171

**Comment by davengeo** [comment]
Here there is another example of support for 'application/json', for the getDoc api I guess 
https://github.com/couchbase/sync_gateway/pull/592

**Comment by adamcfraser** [comment]
@davengeo This does seem like a similar scenario to the current handling for single doc open_revs=true requests that don't support multipart.  

I'd need to dig into this a bit to understand the implications for attachment handling and interactions w/ compression, but it seems like a reasonable enhancement.

**Comment by nolanlawson** [comment]
Hi all, just so everyone is aware: CouchDB did indeed add `_bulk_get` in 2.0 partially inspired by Couchbase, but the implementation is slightly different (e.g. application/json instead of multipart/mixed). You can check out [COUCHDB-2310](https://issues.apache.org/jira/browse/COUCHDB-2310) for discussion, and for an example implementation you can see how [CouchDB 2.0 does it](https://github.com/apache/couchdb-chttpd/pull/33) and how [pouchdb-server does it](https://github.com/pouchdb/express-pouchdb/blob/b1c6c3567f6ac1ea1538d7b3b642687a838e9ba6/lib/routes/bulk-get.js).

We'd be happy to see CSG support this API as Couch 2 and pouchdb-server do, so that we can have better perf/compatibility. 🙂

**Comment by adamcfraser** [comment]
@nolanlawson thanks for the additional links - I was looking for the specifics of the CouchDB request/response API earlier.  

I expect the multipart vs. application/json is relatively straightforward - the greater challenge will be working out how to align request/response signatures.  If there's a relatively lightweight transform (like @davengeo has implemented) that also covers enough of the core pouchdb use cases, that might work.

**Comment by funkyeah** [comment]
so does this merge: https://github.com/couchbase/sync_gateway/pull/592 solve this issue?

**Comment by adamcfraser** [comment]
@funkyeah No, #592 was just for the single doc case.

**Comment by lucapale** [comment]
Hi. Do you know if this issue is going to be solved in the next releases of SyncGateway?
I'm also building an app that heavily relies on PouchDb and SG and it would be great to see the two platforms working better together.

**Comment by adamcfraser** [comment]
Closing based on age, and no current prioritization of enhanced PouchDB support.
