### ISSUE TITLE
Separating Couchbase Server from Sync Gateway AMI

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2332]
From @djpongh:

The decision was made to separate out Couchbase Server from the Sync Gateway AMI image.
 
Items to do now to make this happen:

- Change the packer script to not install CBS 
    - Change the packer script to not install CBS
    - Change AMI name to no longer contain CBS
- Update readme instructions
    - Remove all references to Couchbase Server bundled on the instance, since there will no longer be one
    - Add step-by-step instructions on how to spin up a Couchbase Server and a Sync Gateway EC2 instance separately and then connect them together
    - Update Anil Kumar’s spreadsheet that is submitted to Amazon 
 
To do later:

-  Provide cloud formation template
    - Spins up/shuts down 2 EC2 instances that talk to each other

**Comment by tleyden** [comment]
Related to https://github.com/couchbase/sync_gateway/issues/2049

**Comment by djpongh** [comment]
Dup of #97

**Comment by ceejatec** [comment]
#97 seems completely unrelated to this ticket. Does this ticket duplicate some other ticket, or was it closed in error?

**Comment by tleyden** [comment]
@ceejatec I think you can safely ignore @djpongh's comment.  This was closed because the bulk of the work for removing Couchbase Server from the AMI builder script has been completed.

The code for that is in two places:

- [sync gateway ami builder jenkins job](http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-ami/)
- [packer configuration file](https://github.com/couchbase/sync-gateway-ami/blob/master/packer/sync-gateway.json)
