### ISSUE TITLE
in-memory bucket is confusing for sync function development

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#234]
This makes it impossible to iterate on sync function development, as your data disappears each time you delete and recreate the database.

I think the real fix for this is Sync Gateway having a PUT to update databases, and we use that instead of requiring a DELETE then a PUT.

But for now, the other storage mediums are OK, but the default we ship with behaves differently.

Maybe a solution is to use file walrus by default instead of memory walrus? Or maybe fixing PUT to handle updating databases without erasing them?

**Comment by adamcfraser** [comment]
Closing based on age, and since Couchbase Server development would be recommended approach.
