### ISSUE TITLE
Investigate potential bottlenecks when running behind ELB

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2347]
Found during https://github.com/couchbase/sync_gateway/issues/2339 testing.

Seeing very quick ramp up of round trip times when running gateload.

Adding telegraf/grafana dashboards to investigate

**Comment by tleyden** [comment]
I ran a 4 node SG + 4 node SG Accel cluster on AWS with [these cluster specs](https://github.com/couchbaselabs/sg-autoscale/blob/f294f23df03ddf822b4762c091c37cd0ff10d5e5/src/cloudformation_template.py) and the round trip time went out of the expected bounds [up to 4 mins](http://s61103cnt72.sc.couchbase.com:3000/dashboard/db/sync-gateway-perf-test?var-perftestrundbs=telegraf&from=1487981756308&to=1487982663966&var-lb_host=All&var-sg_host=All&var-cb_host=All&var-lg_host=All&var-ac_host=All)

<img width="1427" alt="screen shot 2017-02-24 at 8 44 38 pm" src="https://cloud.githubusercontent.com/assets/296876/23328266/18ee7de8-fad2-11e6-9c20-3520cb7d8a66.png">

All Sync Gateway CPU's appeared to be pegged at 100%:

<img width="1440" alt="screen shot 2017-02-24 at 8 47 20 pm" src="https://cloud.githubusercontent.com/assets/296876/23328285/8128a960-fad2-11e6-93da-ed69c512317b.png">

The main difference between the standard perf tests and this scenario is that in this case the Sync Gateways are running behind a load balancer.
  
Potential bottlenecks worth looking into:

1. Empty rev caches
1. Empty channel caches 
1. Empty password hash caches

Which could result in increased bucket retrievals and thus slow things down

**Comment by adamcfraser** [comment]
In a real-world scenario, I think some of these issues would be mitigated by using sticky sessions on the ELB.  

We need to identify whether our existing load generation tools are compatible with sticky sessions, and if not, what we'd need to change.  In particular:
- If the ELB is set up to set it's own cookie (AWSELB, as described here http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html), will gateload send that cookie on subsequent requests **by that user only**?
- Can gateload use session-based authentication, to allow us to configure sticky sessions on the ELB based on our own cookie?

**Comment by tleyden** [comment]
@agyryk @adamcfraser is it possible to add a load balancer to the scenarios you are looking into?

**Comment by adamcfraser** [comment]
Closing based on age, and the fact that 2.x replication is based on a persistent connection.
