### ISSUE TITLE
Document AWS Elastic Load Balancer (ELB) settings

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2348]
See https://github.com/couchbase/sync_gateway/issues/2339#issuecomment-282141858

**Comment by tleyden** [comment]
- If using continuous changes feeds, must tune load balancer setting to have much longer timeout than default

See https://github.com/couchbase/sync_gateway/issues/2339#issuecomment-282141858

**Comment by jamesnocentini** [comment]
@tleyden what are the steps to get started with ELB and SG/CBS?

**Comment by tleyden** [comment]
If you want to actually run it, use this job:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sg-autoscale/

but I think you might be able to document it based on https://github.com/couchbase/sync_gateway/issues/2339#issuecomment-282141858 

or you can also check the raw ELB settings here:

https://github.com/couchbaselabs/sg-autoscale/blob/master/src/sgautoscale_cloudformation_template.py#L197-L232

the main one being this one:

https://github.com/couchbaselabs/sg-autoscale/blob/master/src/sgautoscale_cloudformation_template.py#L204

```
ConnectionSettings=elb.ConnectionSettings(
            IdleTimeout=3600,  # 1 hour to help avoid 504 GATEWAY_TIMEOUT for continuous changes feeds
        ),
```

**Comment by jamesnocentini** [comment]
exsiting SG install docs https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/md-docs/_1x/installation/sync-gateway.md

**Comment by dropwhile** [comment]
I saw a bit of a performance improvement using "sticky sessions" with ELB/ALB (application load balancer). My hypothesis is that it results in slightly better caching.

**Comment by tleyden** [comment]
Cool, thanks for reporting that @cactus!

**Comment by tleyden** [comment]
PR up: https://github.com/couchbaselabs/couchbase-mobile-portal/pull/640
