### ISSUE TITLE
Use a stronger digest algorithm for attachment storage

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#2350]
We've always used SHA-1 digests as identifiers for attachments: as the digest metadata property, and as the key for storing the attachment files. Like many other systems, we treated the digests as unique for all practical purposes. That's not viable anymore; the SHA-1 algorithm has been broken such that it's now possible to create multiple files with the same digest (and there are such files in the wild.)

We need to upgrade to a stronger algorithm, likely SHA-256 or SHA-3. The downside is that the digests are twice as large, and take longer to compute.

Backward compatibility will take some thought. Attachment stores can be upgraded by re-digesting and renaming all the files, but what do we do about the existing revisions containing "digest":"sha1-…" properties? It seems like we'll need to support both digests for a while — the attachment store may need to have both types of keys in use.

(For the client side of this, see https://github.com/couchbase/couchbase-lite-core/issues/59.)

**Comment by snej** [comment]
A shorter-term workaround is to use the [SHA1-Collision-Detection library](https://github.com/cr-marcstevens/sha1collisiondetection), an augmented SHA-1 implementation that detects and rejects data that shows the signs of being crafted to create a collision.

**Comment by adamcfraser** [comment]
Migrated to CBG-794
