### ISSUE TITLE
Service install script does not run on MacOS

### ISSUE THREAD

**Issue by doronkatz** [couchbase/sync_gateway#2352]
### Sync Gateway version
1.4-78_x86_64

### Operating system
OSX

### Expected behavior
In terminal it should install the service.

### Actual behavior
It gives the **chown error**

### Steps to reproduce
Refere to [official installation instructions](https://developer.couchbase.com/documentation/mobile/current/installation/sync-gateway/index.html) for Mac. This ticket relates to [#549](https://github.com/couchbase/sync_gateway/issues/549)

### Fix
To fix, simply edit the _sync_gateway_service_install.sh_ file as follows (fix line 10 to refer to */Users/sync_gateway* instead of */Home/sync_gateway*:

...
#!/bin/sh

# Set default values
```
OS=""
VER=""
SERVICE_NAME="sync_gateway"
SRCCFGDIR=../examples
SRCCFG=serviceconfig.json
RUNAS_TEMPLATE_VAR=sync_gateway
RUNBASE_TEMPLATE_VAR=/Users/sync_gateway
PIDFILE_TEMPLATE_VAR=/var/run/sync-gateway.pid
GATEWAYROOT_TEMPLATE_VAR=/opt/couchbase-sync-gateway
GATEWAY_TEMPLATE_VAR=/opt/couchbase-sync-gateway/bin/sync_gateway
CONFIG_TEMPLATE_VAR=${RUNBASE_TEMPLATE_VAR}/sync_gateway.json
LOGS_TEMPLATE_VAR=${RUNBASE_TEMPLATE_VAR}/logs
SERVICE_CMD_ONLY=false
```

**Comment by tleyden** [comment]
@doronkatz thanks for the bug report!  If you have a chance, please send a PR with this change.  Regardless this will be very useful.

**Comment by ajres** [comment]
The fix as proposed would break linux installs

Changing the path for macOS should already be handled in this code block

```
#If the OS is MAC OSX, set the default user account home path to /Users/sync_gateway
if [ "$OS" = "Darwin" ]; then
    RUNBASE_TEMPLATE_VAR=/Users/sync_gateway
    CONFIG_TEMPLATE_VAR=${RUNBASE_TEMPLATE_VAR}/sync_gateway.json
    LOGS_TEMPLATE_VAR=${RUNBASE_TEMPLATE_VAR}/logs
fi
```
Which macOS version was the script run on, there might be an issue with the OS type identification.

**Comment by doronkatz** [comment]
> Right I did that code there to set OS. I haven't tested with the case statement again in my machine but I did test manually changing the path to Users and it works.  

So as long as that fix up there works and it doesn't break Linux( I'm no Bash expert ) and I didn't test with Linux it should be fine

**Comment by ajres** [comment]
Tested on macOS Sierra 10.12.1

Created macOS user sync_gateway
Note: You need to create a valid macOS user, not just a directory, as the plist service file will run the sync_gateway process as that user.

Downloaded tarball from couchbase.com

couchbase-sync-gateway-enterprise_1.3.1.1-1_x86_64.tar

Un tar'd contents to /opt

Changed directory to

$ cd /opt/couchbase-sync-gateway/service

Ran the service installer with default parameters

$ sudo ./sync_gateway_service_install.sh

Validated that sync_gateway process was running

ps -ef | grep sync_gateway 
    0    82     1   0  6:39pm ??         0:00.06 /opt/couchbase-sync-gateway/bin/sync_gateway /Users/sync_gateway/sync_gateway.json

**Comment by ajres** [comment]
Closing this PR as we don't think a change is required to the service installer.

If you continue to experience this problem then please re-open or create a new ticket.
