### ISSUE TITLE
Windows service wrapper should write to a configurable stderr log file

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2354]
The windows service wrapper currently has a hardcoded path to the stderr log file, this is used to capture any output written directly to stderr, or when no custom logFilePath is defined all logging will be written to stderr.

To allow the stderr logging to be written to a custom path, the Windows service wrapper will need to be updated to accept an additional command line argument.

The Windows service wrapper already accepts command line arguments for a custom path to the sync_gateway.exe and the config.json file.

**Comment by djpongh** [comment]
Unit testable?
