### ISSUE TITLE
Timeout parameter is not taken into account in _changes request

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2357]
### Sync Gateway version
1.3.1

### Operating system
RedHat 7.2

### Log output
https://gist.github.com/ArihantRk/f5e8b531217eb66e8dd90658dc34353a.

**14:10:11.061636 2017-02-28T14:10:11.061+05:30 HTTP:  #5643: POST /ptxdata/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=37794&filter=sync_gateway%2Fbychannel  (as 919845012121)**
14:10:11.061752 2017-02-28T14:10:11.061+05:30 Changes+: Int sequence multi changes feed...
14:10:11.061788 2017-02-28T14:10:11.061+05:30 Changes: MultiChangesFeed({919845012121-CH, PTX-919845012121-meta-CH}, {Since:37794 Limit:0 Conflicts:true IncludeDocs:false Wait:true Continuous:false Terminator:0xc821d28780 HeartbeatMs:300000 **TimeoutMs:300000** ActiveOnly:false}) ...   (to 919845012121)
14:10:11.062268 2017-02-28T14:10:11.062+05:30 Bucket: Update("_sync:role:level-2", 0, ...) --> CAS quit [287.375Âµs]
14:10:11.062346 2017-02-28T14:10:11.062+05:30 Changes+: MultiChangesFeed: channels expand to channels.TimedSet{"PTX-919845012121-meta-CH":channels.VbSequence{VbNo:(*uint16)(nil), Sequence:0x91c5}} ...   (to 919845012121)
14:10:11.062365 2017-02-28T14:10:11.062+05:30 Changes+: MultiChangesFeed waiting...   (to 919845012121)
14:10:11.062373 2017-02-28T14:10:11.062+05:30 Changes+: Waiting for "ptxdata"'s count to pass 140
**14:20:09.058977 2017-02-28T14:20:09.058+05:30 HTTP+: #5643:     --> 200 OK  (0.0 ms)**
From syncgateway logs for transaction_id  #5643 we could see that timeout is 300 seconds but could see that response for the same took 10 minutes.
### Expected behavior
response for the _changes should be timeout for 5 min 

### Actual behavior
Timeout parameters not taken into account. response took 10 minutes eventhough timeout is set for 5 minutes

**Comment by adamcfraser** [comment]
When a heartbeat value is specified, the timeout parameter is ignored.

https://developer.couchbase.com/documentation/mobile/1.3/references/sync-gateway/rest-api/index.html#!/database/get_db_changes
