### ISSUE TITLE
linux/macOS install archives contain windows service wrapper sources

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2359]
When the SGA 1.4 tar archives are installed the service folder includes the sg-windows sub folder that contains the Windows service wrapper golang source.

**Comment by ajres** [comment]
This is not a regression, 1.3.1 installers also contain the golang sources

**Comment by ajres** [comment]
This requires a change to 

https://github.com/couchbase/build/blob/master/scripts/jenkins/mobile/sgw_unix_build.sh

Need to raise a Gerrit ticket.

**Comment by ajres** [comment]
For PR review see gerrit ticket 85571

**Comment by tleyden** [comment]
I rebased and merged the [gerrit ticket](http://review.couchbase.org/#/c/85571/).

Commit in couchbase/build repo: https://github.com/couchbase/build/commit/b48ec7bf93dc2c09c605bca32ff8bd0cd6b2bf47
