### ISSUE TITLE
Make sure SG install archives contain the correct manifest files

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2360]
When the SGA 1.4 tar archives are installed the sync_gateway root folder contains the following manifest files:

`manifest.txt`

contents:

```
couchbase-sync-gateway  2  macosx-x86_64
```
`manifest.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    <remote    name="couchbase" fetch="git://github.com/couchbase/" />
    <project remote="couchbase" name="sync_gateway" path="sync_gateway" revision="9e18d3e60e1e6f3b39fddbcf2f59b567a5f4ff05" />
</manifest>
```

These files don't appear to add any value to the install archive.

**Comment by ajres** [comment]
This is not a regression, 1.3.1 installers also contain the manifest files

**Comment by ajres** [comment]
The inclusion of a manifest is intentional as this aides support in debugging issues as they know the exact version of the deployed software.

After talking to the build team, they would expect this to be the full manifest.xml used to create the build.

I think the original manifests were created before SG moved to using the repo tool for builds release management.

I have asked the build team whether adding the manifest would normally be done in the "build" repo scripts or the SG packaging scripts. For the latter we will need to know the path to copy the correct build manifest from when creating the install packages.

**Comment by adamcfraser** [comment]
Closing baed on age.
