### ISSUE TITLE
Submit AMI's to AWS Marketplace

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#2362]
Pending SG #97

**Comment by ceejatec** [comment]
This has nothing to do with #97, does it?

**Comment by ceejatec** [comment]
FYI, there's basically 0 chance I'll be able to work on this anytime soon. I'm going to assign to Ken as he has a background task to work on the Server AMIs, and maybe this could be related.

**Comment by tleyden** [comment]
Also closing this until there is a clear path forward on AWS / AMI deployment plan
