### ISSUE TITLE
Omit doc during Changes+ logging

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2364]
When a changes request includes doc bodies, Changes+ logging ends up logging the full doc body.  Should modify to just include entry information.

Example:
https://github.com/couchbase/sync_gateway/blob/master/db/changes.go#L566

**Comment by Fujio-Turner** [comment]
Still need the option to emit the whole doc so a "Changes++" would be a good option. Else you have to do TCPDUMP.

HTTP+,HTTP++
https://github.com/couchbase/sync_gateway/issues/2240

**Comment by adamcfraser** [comment]
@Fujio-Turner What's the value in emitting the entire doc in Changes+ logging?  The normal use is to diagnose changes feed traffic issues - the doc doesn't help with that.

**Comment by jamesnocentini** [comment]
The HTTP++ log tag in 1.4 prints the doc body AFAIK. And is documented on https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/config-properties/index.html. Don't know if it gets printed in changes feed requests though.

**Comment by adamcfraser** [comment]
@jamiltz HTTP++ logging support has been removed from 1.4, for security reasons.  Sounds like we'll need to update the doc.

**Comment by jamesnocentini** [comment]
ok HTTP++ is removed now.
