### ISSUE TITLE
Improvement - Logging - CRUD+, CRUD++

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/sync_gateway#2366]
CRUD+ is a great option b/c it gives size of the payload. 
Still need a way to see what the whole payload sometimes to see what Couchbase Lite is sending so a CRUD++ would be good.

**Comment by adamcfraser** [comment]
Full payload logging was explicitly disabled due to potential security concerns. (originally covered in #2231).  Using external tools like HTTP Scoop/Wireshark are usually better for diagnosing client/server traffic.

Can you provide specific details about what type of scenarios you think would benefit from full payload logging?

**Comment by househippo** [comment]
@adamcfraser ,

> Can you provide specific details about what type of scenarios you think would benefit from full payload logging?

"log":["Changes"] is great b/c it provides the _id & _rev being sent to CBL, but there is no way to see what is being sent to SG on the bulk post method except execution time. If we could see _id & _rev on the bulk post or PUT/POST/DELETES that would help debug an Push Replication issues and/or CRUD issues. We could find things like.

_"XYZ person is send a bulk post of 2000 items 50KB each item & its gZipped"_

I'm a big fan of auditing/tracking documents with a CreatedDateTime & By and UpdatedDateTime & BY inside the document but not all use case need it or can afford to have it. So debugging an issue like below can be hard:

_"ABC person is intentionally introduction conflicts cause the document sizes to grow to the 20MB limit"_

Conflicts are a particular matter of interest. Many times this happens naturally , but other times it can happen maliciously.

**Comment by tleyden** [comment]
@househippo I agree that full payload logging can be helpful sometimes.  One approach I've thought of would be to front Sync Gateway with a reverse proxy that provides full logging.  

A few reverse proxies that might already do this:

- Mashape Kong
- https://github.com/mholt/caddy

In the meantime, the `ngrep` tool is a lightweight way on Linux to sniff the traffic: `ngrep -W byline port 4984 or port 4985`

**Comment by djpongh** [comment]
Lots of security concerns and unsure if this is really needed.

**Comment by Fujio-Turner** [comment]
@djpongh ,

"Lots of security concerns and unsure if this is really needed."

I would agree with you.
Instead of the whole payload could we just do the _id and _revs by the user.

CURRENTLY
After user does a PUT via _bulk_doc  (as User 1) a few lines later you see in CRUD. Its clear that the CRUD came from User 1
T1 HTTP: #004 PUT .  _bulk_docs (as User 1)
T2 CRUD: .... _id 1234 _rev 1-123
T3 CRUD: .... _id 5678 _rev 1-456
T4 HTTP+:#004 ----> (200) 54.0ms (to User 1)

Sometimes when CBL uses WebSockets the SG logs can get mixed so its not always clear who is making the CRUD, but If you simple put (from User1)
....
T2 CRUD++: .... _id 1234 _rev 1-123 **(from User 1)**
T3 CRUD++: .... _id 5678 _rev 1-456  **(from User 1)**
....
or even
....
T2 CRUD++: .... _id 1234 _rev 1-123 **(from User 1 on #004)**
T3 CRUD++: .... _id 5678 _rev 1-456  **(from User 1 on #004)**
....

The Idea of the ask is to be able to ID what data by who and when was inserted into the CB.
