### ISSUE TITLE
Allow systemd to handle log capture instead of redirecting manually

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2368]
Investigate options for systemd log capture.  Based on comment from @cactus on #2397:

> Aside: It would also be nice if the systemd unit files stopped redirecting stdout/stderr and instead let systemd handle log capture itself.

**Comment by dropwhile** [comment]
@adamcfraser this is what I have done locally..

example "by hand edit" (fake diff) of `/usr/lib/systemd/system/sync_gateway.service` (centos7 via rpm install)
```
- ExecStart=/usr/bin/bash -c '${GATEWAY} ${CONFIG} >> ${LOGS}/${NAME}_access.log 2>> ${LOGS}/${NAME}_error.log'
+ ExecStart=/opt/couchbase-sync-gateway/bin/sync_gateway /home/sync_gateway/sync_gateway.json
```

**Comment by adamcfraser** [comment]
Closing based on age, and changes to service logging since. If additional changes are required, should be filed as new issue in issues.couchbase.com.
