### ISSUE TITLE
Logging - "Replicate" works when in *.json but not when you PUT _logging

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/sync_gateway#2371]
Logging for sg-replicate works fine when you hard code "Replicate" into the sync gateway *.json config file at start up like BELOW.
```
{
"log":["HTTP","Replicate"]
}
```

but using if you try to turn on or off  "Replicate":false or "Replicate":true via  
-XPUT localhost:4985/_logging does not start or stop the logging of "Replicate" in the SG logs.

Issue found is SG 1.4 GA.

**Comment by adamcfraser** [comment]
It looks to me like there are a few other special cases (log+ handling, gocb logging) that don't get invoked when calling the _logging endpoint.  I think logging.UpdateLogKeys should be calling into the equivalent of ParseLogFlags, but with handling for the `key:false` scenarios.  

Could probably refactor ParseLogFlags to ParseLogFlagMap (that takes map[string]bool), and then have ParseLogFlags call into that w/ all values set to true.
