### ISSUE TITLE
sg causing the android app to stop replicating

### ISSUE THREAD

**Issue by npomfret** [couchbase/sync_gateway#2374]
Apparently https://github.com/couchbase/couchbase-lite-android/issues/1063#issuecomment-285120426 is a bug in the sync gateway.  It causes the Android app to stop continuous pull replication.    

Without continuous pull replication my app is useless, as I imagine are many others.  Can this be looked into as a priority?

**Comment by adamcfraser** [comment]
Reviewed with @hideki - he's got some followup questions he'll post to https://github.com/couchbase/couchbase-lite-android/issues/1063.

**Comment by adamcfraser** [comment]
Working on getting a reproducible scenario to identify whether this is a case of the client sending an incorrect attr_since, or Sync Gateway calculating the wrong revpos.

It looks more like the former case, but need to repro to be sure.

**Comment by adamcfraser** [comment]
Closing this, as the client handling has been improved.  Filed a ticket for a functional test to get this scenario into automated testing - will reopen this ticket if that test fails.
https://github.com/couchbaselabs/mobile-testkit/issues/1023
