### ISSUE TITLE
Review using gocb vs. gocbcore

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2377]
There may be a performance benefit to using the underlying gocbcore library, instead of the higher-level gocb client library.

Questions to consider include:
1. What are the expected performance benefits?  Less reflection in transcoding seems likely - anything else?
2. What functionality do we lose when we move away from the gocb layer?  (wondering about things like dropped connection detection, node failover, bucket authentication, etc)
3. Are we just going to end up rewriting a lot of the gocb client code in our bucket wrapper anyway?

**Comment by tleyden** [comment]
@brett19 any insight on #2 related to gocb vs gocbcore? 

> What functionality do we lose when we move away from the gocb layer? (wondering about things like dropped connection detection, node failover, bucket authentication, etc)

**Comment by tleyden** [comment]
From @brett19 via hipchat:

The main things on top of gocbcore that gocb provides:

- Synchronous API
- HTTP support: views, n1ql, etc

**Comment by tleyden** [comment]
Gains by moving to gocbcore:

1. Can avoid some transcoding overhead
    * Can be mitigated even in gocb by implementing a custom transcoder that doesn't transcode. (??? so then what does it do?  I don't get this)
1. Cain some overhead back from synchronization if we take advantage of the asynchronous nature of gocbcore
    * IE: If you need to do 100 operations simultaneously, you can do them all asynchronously and synchronize on a single channel.
    * Rather than having 100 channels, which is what gocbcore would do (though our Bulk API gets around that in gocb, if your using that)

Stays the same if moving to gocbcore:

* Things like identifying changes in cluster topology (vbuckets moving between nodes, dropped nodes, etc) are already part of gocbcore, so dropping down to gocbcore will not lose this functionality

**Comment by tleyden** [comment]
Closing this out since there aren't any more action items that I can see.
