### ISSUE TITLE
Conflicting revision bodies referencing attachments by revpos

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2378]
A user has reported a scenario where a conflicting revision body includes a stub=true/revpos reference, instead of digest.  When the attachment is subsequently removed from the active document, attempts to retrieve the conflicting revision by revid return error.

https://forums.couchbase.com/t/getting-this-error-interface-conversion-interface-is-nil-not-string/10988/5

Need to review whether Sync Gateway should either be switching attachment references to digest when writing old revision bodies, or if there's additional processing that should happen when an attachment is deleted to cover this scenario.

**Comment by alex7egli** [comment]
Using couchbase lite 1.3.0 and sync gateway 1.3.1. The document that had this issue has many revisions (306) and many conflicts (over 40). At least some of the conflicts have the _attachments object removed, and the latest revision of the document has the _attachments object removed. To reproduce I would recommend causing many conflicts where at least some of the conflicts are that _attachments is gone.

**Comment by alex7egli** [comment]
Attached sanitized version of the user doc that is having this issue.
[sanitized-user-doc.txt](https://github.com/couchbase/sync_gateway/files/839550/sanitized-user-doc.txt)

**Comment by adamcfraser** [comment]
@alex7egli Thanks for the sanitized doc.  Do you know which rev in that doc triggers the error when you attempt to retrieve it?

**Comment by alex7egli** [comment]
I have seen a couple revs cause it. Here are examples of two of the urls we see in sync gateway logs that caused the error. So looks like rev 251-4d89ab13569abfba6471f961baa2cd25 and 188-c20d8bbea275c8ebf552f95daf255f3e are causing the error to occur.

`2017-03-06T20:31:54.166Z HTTP:  #646445: GET /todos/<doc id>?rev=251-4d89ab13569abfba6471f961baa2cd25&revs=true&attachments=true&atts_since=%5B%22246-48f17fec3614a950ea21cd9ef087dc07%22%2C%22242-742891349c9a422fbad0cca03db042dd%22%2C%22235-536cb247642b25ef77e1b68bf4e4bf69%22%2C%22224-ee8138d173e55935174f5c9652743a53%22%2C%22220-ffacd163fa2b423ab4a276a5c6fa9d59%22%2C%22218-f3e22fcdf6bd8e33827faab14e39803d%22%2C%22189-0ec3f3d6ddc189b25fb149efdb6acd75%22%2C%22188-f574f9af946837ec521b089064a268bb%22%2C%22184-03a8cd14580a94dcd27e43a0bb71a913%22%2C%22176-62e7280c1bce7074e8e6b850cb1d3d63%22%5D  (as <user id>)`
`2017-03-06T20:49:53.992Z HTTP:  #647311: GET /todos/<doc id>?rev=188-c20d8bbea275c8ebf552f95daf255f3e&revs=true&attachments=true&atts_since=%5B%22184-03a8cd14580a94dcd27e43a0bb71a913%22%2C%22176-62e7280c1bce7074e8e6b850cb1d3d63%22%2C%22172-cb18f190712554df3466b448db8ef8c6%22%2C%22146-e3c09a3fbc55dd764ff4a72386faf0da%22%2C%22140-25c3c718449158d4de91687057638568%22%2C%22137-b33f582e8513cda3f3fa4b331a70efae%22%2C%22130-88a1093a4360519020ce7c6a86e4ad66%22%2C%22120-ae0f836db9a04c95ff7d816c323abad8%22%2C%22116-a5d6cc3366818354f2d844ca532f2abb%22%2C%22104-f370a9ede870aed4de8c801c358c2a4d%22%5D  (as <user id>)`

**Comment by adamcfraser** [comment]
The second one of those (`rev 188-c20d...`) looks like it's the conflicting doc with body:
`            "195": "{\"_attachments\":{\"profileImage\":{\"revpos\":7,\"stub\":true}},"<doc body"},`

which is the one that looked suspicious to me (stub=true, no digest).  

This doesn't explain why `rev 251-4d89...` would return an error, though.  It may be related to the atts_since processing.  

I think we'll need to spend some time trying to get a reproducible test case in order to get to the bottom of this.

**Comment by adamcfraser** [comment]
Closing based on age, and subsequent enhancements to attachment storage since 1.x.  Should be reopened in issues.couchbase.com if recurs with current builds.
