### ISSUE TITLE
Channel cache missing data when request instantiating cache times out

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2383]
Details here:
https://forums.couchbase.com/t/different-sync-gateway-instances-working-with-same-cluster-return-different-results/12086/7

Need additional investigation, but sounds like there's a potential problem with channel cache initialization when either the view query times out, or the changes request triggering the creation of the cache times out.

**Comment by AndrejRW** [comment]
Additional situation where this issue with sync gateway is critical: sync gateway communicates with couchbase instances. one of couchbase instance crashes - sync gateway's requests times out and wrong response is cached. After it couchbase instance comes up (or restarted) - sync gateway has to be restarted as well manually because wrong response still cached.

**Comment by adamcfraser** [comment]
@AndrejRW This is only the case during channel cache initialization, and timeout during a view call (not any other operation).  

I agree that this should get fixed sooner rather than later, though - moving to 2.0.0.

**Comment by adamcfraser** [comment]
From the forum post linked above:

1) Working scenario:
```
10:10:13.927090 2017-03-14T10:10:13.927+01:00 HTTP: #71094: GET /ag-dev/_changes?filter=sync_gateway/bychannel&channels=apptables_mainUser111507_timeRecording (ADMIN)
10:10:13.929556 2017-03-14T10:10:13.929+01:00 Cache: Initialized cache for channel "apptables_mainUser111507_timeRecording" with options: &{ChannelCacheMinLength:50 ChannelCacheMaxLength:500 ChannelCacheAge:1m0s}
10:10:14.069901 2017-03-14T10:10:14.069+01:00 Cache: Got 8 rows from view for "apptables_mainUser111507_timeRecording": #530593 ... #5153974
10:10:14.069974 2017-03-14T10:10:14.069+01:00 Cache: Initialized cache of "apptables_mainUser111507_timeRecording" with 8 entries from view (#530593--#5153974)
10:10:14.070032 2017-03-14T10:10:14.070+01:00 Cache: GetChangesInChannel("apptables_mainUser111507_timeRecording") --> 8 rows
```
So as you see records related to channel found pretty fast (withing 1 sec)


2) Broken scenario:
```
16:27:36.081647 2017-03-13T16:27:36.081+01:00 HTTP: #332784: POST /ag-dev/_changes?feed=normal&heartbeat=30000&style=all_docs&filter=sync_gateway%2Fbychannel (as mainUser111507)
16:27:36.090443 2017-03-13T16:27:36.090+01:00 Cache: Initialized cache for channel "apptables_mainUser111507_timeRecording" with options: &{ChannelCacheMinLength:50 ChannelCacheMaxLength:500 ChannelCacheAge:1m0s}
16:28:20.953915 2017-03-13T16:28:20.953+01:00 Changes: Connection lost from client: (as mainUser111641)
16:28:20.954341 2017-03-13T16:28:20.954+01:00 Changes+: Notifying to check for _changes feed termination
16:28:20.955457 2017-03-13T16:28:20.955+01:00 Changes+: Waiting for "ag-dev"'s count to pass 5634
16:28:36.110316 2017-03-13T16:28:36.110+01:00 changes_view: Query took 1m0.019498692s to return 3 rows, options = db.Body{"stale":false, "startkey":[]interface {}
16:28:36.110420 2017-03-13T16:28:36.110+01:00 Cache: GetChangesInChannel("apptables_mainUser111507_timeRecording") --> 3 rows
```

In the broken case, we're not seeing any of the logging normally found in [prependChanges](https://github.com/couchbase/sync_gateway/blob/master/db/channel_cache.go#L349).  My suspicion is that we're getting an error in the view call [here](https://github.com/couchbase/sync_gateway/blob/2651bf6c7ad11cbfd039c9f29523907a0ccddfa0/db/channel_cache.go#L223), and that's leaving the channel cache in an invalid state, where subsequent calls to GetChanges don't retrigger the view query.  

I'd try the following to repro:

1. Write a few documents to a channel
2. Flush the channel cache (either restart SG, or use FlushChannelCache)
3. GetChanges, artificially forcing an error in getChangesInChannelFromView.
4. GetChanges again, and see if/why getChangesInChannelFromView doesn't get called.

**Comment by adamcfraser** [comment]
Could also review whether view is timing out, but returning partial data and no error.

**Comment by tleyden** [comment]
I changed the link from the master branch to the actual commit: https://github.com/couchbase/sync_gateway/blob/2651bf6c7ad11cbfd039c9f29523907a0ccddfa0/db/channel_cache.go#L223, so it will survive changes in line numbers on the master branch

**Comment by tleyden** [comment]
Also, if it points to an actual commit, then github will inline it which is nice

**Comment by bbrks** [comment]
As discussed yesterday @adamcfraser , unsure of the best approach for fixing the actual problem, but left proposals below. Related: #2682 #2702 

After some investigation, I've created a repro unit test. However a minor change in `getChangesInChannelFromView()` (`changes_view.go`) needs to be done in order to force a one-off error to see this issue manifest.

## Force one-off partial error

Below the lines:
https://github.com/couchbase/sync_gateway/blob/e54d1cdb01819fb63aecf5e76c3896a7fd3d0804/db/changes_view.go#L46-L47

Insert this (and create `hasRunOnce` global bool)

```go
// FIXME: force a one-off partial error here
if !hasRunOnce {
	vres.Rows = nil
	vres.Errors = []couchbase.ViewError{{From: "error from", Reason: "error reason"}}
	hasRunOnce = true
}
```

## Possible fixes

- Treat partial errors as an actual error in `ViewCustom` (i.e. return error from below code):

https://github.com/couchbase/sync_gateway/blob/e54d1cdb01819fb63aecf5e76c3896a7fd3d0804/base/bucket_gocb.go#L1866-L1888

- Add an explicit check for `vres.Errors` here so the cache doesn't get initialized:

https://github.com/couchbase/sync_gateway/blob/e54d1cdb01819fb63aecf5e76c3896a7fd3d0804/db/changes_view.go#L46-L57

E.g:
```go
} else if len(vres.Errors) > 0 {
	base.Logf("Partial errors from 'channels' view: %v", vres.Errors)
 	return nil, fmt.Errorf("Partial errors from 'channels' view: %v", vres.Errors)
} else if len(vres.Rows) == 0 {
```

## Repro test

```go
func TestReproduce2383(t *testing.T) {
	rt := RestTester{SyncFn: `function(doc, oldDoc){channel(doc.channels);}`}

	response := rt.SendAdminRequest("PUT", "/_logging", `{"*":true, "color":true}`)
	assert.NotEquals(t, response, nil)

	a := rt.ServerContext().Database("db").Authenticator()
	user, err := a.NewUser("ben", "letmein", channels.SetOf("PBS"))
	assertNoError(t, err, "Error creating new user")
	a.Save(user)

	// Put several documents
	response = rt.SendAdminRequest("PUT", "/db/doc1", `{"channels":["PBS"]}`)
	assertStatus(t, response, 201)
	response = rt.SendAdminRequest("PUT", "/db/doc2", `{"channels":["PBS"]}`)
	assertStatus(t, response, 201)
	response = rt.SendAdminRequest("PUT", "/db/doc3", `{"channels":["PBS"]}`)
	assertStatus(t, response, 201)

	testDb := rt.ServerContext().Database("db")

	fmt.Printf("\n\n\n\n\n\n")

	testDb.WaitForSequence(3)
	testDb.FlushChannelCache()

	var changes struct {
		Results  []db.ChangeEntry
		Last_Seq interface{}
	}

	fmt.Printf("\n\n\n\n\n\n")

	changes.Results = nil
	changesResponse := rt.Send(requestByUser("POST", "/db/_changes?filter=sync_gateway/bychannel&channels=PBS", "{}", "ben"))
	err = json.Unmarshal(changesResponse.Body.Bytes(), &changes)
	assertNoError(t, err, "Error unmarshalling changes response")

	// In the first changes request since cache flush, we're forcing a nil cache with no error. Thereforce we'd expect to see zero results.
	// This should maybe be an error so the cache can be re-initialized at a later time.
	assert.Equals(t, len(changes.Results), 0)
	for _, entry := range changes.Results {
		log.Printf("Entry:%+v", entry)
	}

	fmt.Printf("\n\n\n\n\n\n")

	changes.Results = nil
	changesResponse = rt.Send(requestByUser("POST", "/db/_changes?filter=sync_gateway/bychannel&channels=PBS", "{}", "ben"))
	err = json.Unmarshal(changesResponse.Body.Bytes(), &changes)
	assertNoError(t, err, "Error unmarshalling changes response")

	// view was not getting called again, as the cache thinks it should have no entries. In reality, there should be 3 things returned here...
	assert.Equals(t, len(changes.Results), 3)
	for _, entry := range changes.Results {
		log.Printf("Entry:%+v", entry)
	}

	fmt.Printf("\n\n\n\n\n\n")

	// if we create another doc, does the cache get updated?
	response = rt.SendAdminRequest("PUT", "/db/doc4", `{"channels":["PBS"]}`)
	assertStatus(t, response, 201)

	fmt.Printf("\n\n\n\n\n\n")

	changes.Results = nil
	changesResponse = rt.Send(requestByUser("POST", "/db/_changes?filter=sync_gateway/bychannel&channels=PBS", "{}", "ben"))
	err = json.Unmarshal(changesResponse.Body.Bytes(), &changes)
	assertNoError(t, err, "Error unmarshalling changes response")

	// Should now be 4 docs (existing 3 in cache, plus newest change)
	assert.Equals(t, len(changes.Results), 4)
	for _, entry := range changes.Results {
		log.Printf("Entry:%+v", entry)
	}

}
```

**Comment by tleyden** [comment]
@bbrks I just caught up w/ @adamcfraser on this ticket to chat a bit more about the view partial errors.  Here's some rough notes from the call:

Relevant code in `bucket_gocb.go`

```
	// Any error processing view results is returned on Close.  If Close() returns errors, it most likely means
	// that there were "partial errors" (see SG issue #2702).  If there were multiple partial errors, Close()
	// returns a gocb.MultiError, but if there was only a single partial error, it will be a gocb.viewErr
	errClose := goCbViewResult.Close()
	if errClose != nil {
		switch v := errClose.(type) {
		case *gocb.MultiError:
			for _, multiErr := range v.Errors {
				viewErr := sgbucket.ViewError{
					// Since we only have the error interface, just add the Error() string to the Reason field
					Reason: multiErr.Error(),
				}
				viewResponse.Errors = append(viewResponse.Errors, viewErr)
			}
		default:
			viewErr := sgbucket.ViewError{
				Reason: v.Error(),
			}
			viewResponse.Errors = append(viewResponse.Errors, viewErr)
		}
	}
```

- Related ticket: https://github.com/couchbase/sync_gateway/issues/2702

- Best approach at this point looks to be to
    - Return a new typed error to distinguish between partial errors and total errors
    - Callers can check the error type and react accordingly.  There might be code that was currently ignoring partial errors that shouldn't have been, but it's probably best to flush those out during the release QE process rather than allowing them to cause hard-to-find downstream bugs.
