### ISSUE TITLE
Sync Gateway AMI: Add bootstrap REST API into Cloudformation

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2386]
Currently the [cloudformation template](https://github.com/couchbase/sync-gateway-ami/blob/master/generated/generated_cloudformation_template.json) associated with the [Sync Gateway AMI](https://github.com/couchbase/sync-gateway-ami) launch depends on an external REST API required for bootstrapping the Couchbase Server + Sync Gateway nodes.

This isn't ideal for users -- if the external REST API breaks, then it could break their deployment. 

To fix this, the REST API should be launched as part of the cloudformation itself.  That way the cloudformation will be 100% self-contained and not have any dependencies on external services.

**Comment by tleyden** [comment]
Caveat: this might not be feasible!  

Adding the requirement to include the bootstrap rest api into the cluster itself feels like starting with this:

![levitating-street-performer-magic-trick-revealed](https://cloud.githubusercontent.com/assets/296876/24027123/77013fdc-0a82-11e7-8c40-3f0977db6fed.jpg)

and then adding the requirement to remove (2) from the picture.

So, I definitely think we should timebox this.

**Comment by tleyden** [comment]
Closing this out since other folks are planning to look into the cloudformation template

**Comment by djpongh** [comment]
@tleyden I forgot - what are the tickets tracking the other folks?

**Comment by tleyden** [comment]
I don't know of any specific tickets, but I think this is the repo to track: https://github.com/couchbase-partners/amazon-cloud-formation-couchbase/issues
