### ISSUE TITLE
Make DCP the default feed type

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2388]
Use DCP as the default feed type for Sync Gateway running in channel cache mode.

Add config validation to throw an error and abort startup if running with FeedType explicitly set to TAP and any of:
 - auto-import set to true
 - XATTR enabled

**Comment by tleyden** [comment]
After this change, the functional tests will test https://github.com/couchbase/sync_gateway/issues/2414

**Comment by ajres** [comment]
Couldn't see any XATTR config on master to do the validation check when TAP is explicitly defined.
