### ISSUE TITLE
Walrus support for XATTRs

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2390]
Add the ability to emulate XATTR support in Walrus.

Initial requirements:
- Walrus support for XATTR-related bucket API defined in https://github.com/couchbase/sync_gateway/issues/2389
- Macro expansion for CAS (to support writing CAS values into XATTRs)
- Read XATTRs from view map function
- Retention of XATTRs on normal document deletion

**Comment by djpongh** [comment]
and unit tests passing

**Comment by djpongh** [comment]
testing vs. Server instead
