### ISSUE TITLE
open_revs=all returning tombstones?

### ISSUE THREAD

**Issue by dropwhile** [couchbase/sync_gateway#2401]
### Sync Gateway version
1.4

### Operating system
CentOS-7.3.1611 

### Expected behavior
The documentation implies that leaf node tombstones would be omitted from the response.

### Actual behavior
All leaf revisions appear to be present, deleted or not.

### Steps to reproduce
```
$ curl -X PUT -H 'content-type: application/json' 'http://127.0.0.1:4985/db/testdoc' --data '{"test": 1, "channels": ["venue-1"]}'
{"id":"testdoc","ok":true,"rev":"1-35100c06431aa062661ccc8ce1917815"}

$ curl -X DELETE 'http://127.0.0.1:4985/db/testdoc?rev=1-35100c06431aa062661ccc8ce1917815'
{"id":"testdoc","ok":true,"rev":"2-0d019025bab03c8a08850b06dff5da2e"}

$ curl -s -H 'accept: application/json' 'http://127.0.0.1:4985/db/testdoc?open_revs=all'
[
{"ok":{"_deleted":true,"_id":"testdoc","_rev":"2-0d019025bab03c8a08850b06dff5da2e"}}
]
```

**Comment by adamcfraser** [comment]
I think that's the expected behaviour for open_revs.  Can you point me to the documentation that implies this isn't expected?  The API documentation looks like it's accurate (all leaf revisions are returned):
https://developer.couchbase.com/documentation/mobile/1.4/references/sync-gateway/admin-rest-api/index.html#!/document/get_db_doc

**Comment by dropwhile** [comment]
@adamcfraser hmm. It appears you are correct. I must have conflated [what I was reading](https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/resolving-conflicts/index.html#resolving-conflicts) with a [forum comment](https://forums.couchbase.com/t/getting-revisions/8954/4) (a comment which, coincidentally, it appears that you wrote?).

>  open_revs=all should give you all the open (i.e. non-deleted leaf) revisions as multipart entries. If that's not working for you, I'd be interested in hearing the details.....
> -- https://forums.couchbase.com/t/getting-revisions/8954/4

**Comment by adamcfraser** [comment]
Ah - my apologies for the confusion.  I've added a followup correction to that forum thread.
