### ISSUE TITLE
sg-replicate stops due to document not found in couchbase

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2402]
### Sync Gateway version
1.4.0 

### Operating system
RedHat 7.2

### Config file
"replications":[
   {
               "replication_id":"C1_C2",
               "source": "ptxdata",
               "target": "http://prod-SYNCGWREP-V1.service.2.com:4985/ptxdata/",
               "continuous":true,
               "changes_feed_limit":1000
    }],

### Log output
sg-replicate is stopping due to document not found is not handled in sg-replication. This issue we had when we used channel based replication
[https://github.com/couchbase/sync_gateway/issues/2212](url)

but with above config with no filter also we are facing same issue.

syncgateway replicator logs
02:40:46.672274 2017-03-20T02:40:46.672+05:30 HTTP: #6441394: POST /ptxdata/_bulk_docs (ADMIN)
02:40:46.672316 2017-03-20T02:40:46.672+05:30 BulkDocs: Doc "" --> 400 Bad _revisions (400 Bad _revisions)

below is the pcap of error log
POST /ptxdata/_bulk_docs HTTP/1.1
Host: prod-SYNCGWREP-V1.service.2.com:4985
User-Agent: Go-http-client/1.1
Content-Length: 162
Accept-Encoding: gzip

{"new_edits":false,"docs":[{"error":"not_found","id":"Location.doc","reason":"missing","rev":"3048-d170d345fe73a058469b7a034fcbe985","status":404}]}

##curl http://localhost:4985/ptxdata/Location.doc
{"_id":"Location.doc","_rev":"3807-4ebacd6a34970acdfc0b5b6e51ad99c8","cellLocation":{"cellId":"8071","lac":"2030","mcc":"310","mnc":"410"},"channels":[]}

##curl http://localhost:4985/ptxdata/Location.doc?rev=3048-d170d345fe73a058469b7a034fcbe985
{"error":"not_found","reason":"missing"}

Due to this replication is stopped.

### Expected behavior
sg-replicate should not stop

### Actual behavior
sg-replicate is stopped when response status is 404 Not Found in _bulk_docs request body

### Steps to reproduce
1.  Insert documents and update documents and purge the older revision from couchbase and make sure **_changes** feed should show particular older revisions
2.  Enable replication

**Comment by ArihantRk** [comment]
We have enabled feed type as DCP.

**Comment by adamcfraser** [comment]
Will be addressed with Hydrogen sg-replicate enhancements, tracked w/ CBG-709.
