### ISSUE TITLE
Querying a View with POST request

### ISSUE THREAD

**Issue by polyvjk** [couchbase/sync_gateway#2409]
### Sync Gateway version
Couchbase Sync Gateway/1.4.0(2;9e18d3e) 

### Operating system
macOS Sierra

We've created a view and we are trying to query it. In the [Admin REST API](https://developer.couchbase.com/documentation/mobile/1.4/references/sync-gateway/admin-rest-api/index.html#/) documentation there is POST method in the query section /{db}/_design/{ddoc}/_view/{view}. We try to use it because "POST method supports the specification of explicit keys to be retrieved from the view results." However, we received:
 
```HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Length: 42
Content-Type: application/json
Date: Tue, 21 Mar 2017 15:50:27 GMT

{
    "error": "Method Not Allowed",
    "reason": ""
}
```

When we looked in the source code and the tests we didn't find such method at all. Does this method even exist?

**Comment by adamcfraser** [comment]
The documentation is incorrect - the POST method is only available on Couchbase Lite, not Sync Gateway.  I'll see that this gets fixed.  

You can specify the keys property when using the GET method.
