### ISSUE TITLE
Sync Gateway trying to relaunch with invalid user in config

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2412]
### Sync Gateway version
1.4.0-2  

### Operating system
CentOS 7

### Config file
```javascript
{
  "interface": ":4984",
  "adminInterface": "0.0.0.0:4985",
  "maxIncomingConnections": 0,
  "maxCouchbaseConnections": 16,
  "maxFileDescriptors": 90000,
  "slowServerCallWarningThreshold": 500,
  "compressResponses": false,
  "log": [
    "*"
  ],
  "databases": {
    "db": {
      "unsupported": {
        "user_views": {
          "enabled":true
        }
      },
      "server": "http://{{ couchbase_server_primary_node }}:8091",
      "bucket": "data-bucket",
      "roles": {
        "Scientist": {
          "admin_channels": [
            "Download"
          ]
        },
        "Researcher": {
          "admin_channels": [
            "Upload"
          ]
        }
      },
      "users": {
        "seth": {
          "password": "pass",
          "admin_channels": [
            "Create"
          ],
          "admin_roles": [
            "Scientist"
          ]
        },
        "raghu": {
          "admin_channels": [
            "Edit"
          ],
          "admin_roles": [
            "Researcher"
          ]
        }
      }
    }
  }
}
```

### Expected behavior
Since "rahgu" has no password defined, Sync Gateway fails to launch. I would expect it to fail and exit.

### Actual behavior
After failing, Sync Gateway tries to relaunch multiple times.

### Steps to reproduce
1. Using the config above, launch sync gateway
2. Tail the logs and see the multiple restarts

**Comment by adamcfraser** [comment]
I'm not able to reproduce running Sync Gateway from the command line.  If the restarts are due to the service wrapper, I think that's expected - I don't think we (currently) have a way for the service wrapper to distinguish between config-type failures and other transient failures.

**Comment by ajres** [comment]
Yes, the service wrapper is configured to restart the Sync Gateway service if it exits unexpetedly
