### ISSUE TITLE
Creating a view via sg admin port does not return a response

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2413]
### Sync Gateway version
1.4.0-2

### Operating system
CentOS 7

### Config file
standard

### Log output
```
2017-03-18T03:56:43.459Z HTTP:  #003: PUT /db/_design/test_views  (ADMIN)
_time=2017-03-18T03:56:43.459+00:00 _level=INFO _msg= Trying with selected node 0
2017-03-18T03:56:43.470Z HTTP+: #003:     --> 201 OK  (11.4 ms)
```

### Expected behavior
PUT of a view should return a response - https://developer.couchbase.com/documentation/mobile/1.4/references/sync-gateway/admin-rest-api/index.html#!/query/put_db_design_ddoc

### Actual behavior
It does not return a response. I can see that the view is creating in Couchbase Server and there are no errors in the Sync Gateway logs.

### Steps to reproduce
1. `curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"views": {"filtered": {"map": "function(doc, meta) {emit(doc.name, null);}"}}}' 'https://localhost:4985/db/_design/test_views'`
2. The doc PUT is successful but no response is returned

**Comment by adamcfraser** [comment]
`PUT /db/_design/[ddoc]` doesn't return a response body, just 201 OK (which it looks like it's being returned in the logs).

**Comment by sethrosetter** [comment]
For the CBLite Mac OSX,

```
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"views": {"filtered": {"map": "function(doc, meta) {emit(doc.name, null);}"}}}' 'http://localhost:59840/db/_design/test_viewss'
```
```
{"id":"_design\/test_viewss","rev":"1-fc7b07ab54bcf4604032a5f10fd39b4d","ok":true}
```

**Comment by adamcfraser** [comment]
We don't expect parity in the API between SG and CBL in this case.

**Comment by adamcfraser** [comment]
@jamiltz Can you review the docs to make sure that the SG API shows the correct response (201 OK only).

**Comment by djpongh** [comment]
Movd to Jira DOC-3015
