### ISSUE TITLE
Bucket going offline with feed_type=DCP

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2414]
### Sync Gateway version
1.4.0

### Operating system
RedHat 7.2

### Log output

During startup of syncgateway bucket will in offline state, manual trigger to online required and also when one of couchbase node goes down.

03:47:58.768267 2017-03-14T03:47:58.768-05:00 WARNING: Bucket Updater for bucket ptxdata returned error: Get http://10.0.29.135:8091/pools/default/bucketsStreaming/ptxdata: dial tcp 10.0.29.135:8091: getsockopt: connection refused -- base.GetCouchbaseBucket.func1() at bucket.go:405
03:47:58.768295 2017-03-14T03:47:58.768-05:00 WARNING: Lost TAP feed for bucket ptxdata, with error: Get http://10.0.29.135:8091/pools/default/bucketsStreaming/ptxdata: dial tcp 10.0.29.135:8091: getsockopt: connection refused -- rest.(*ServerContext)._getOrAddDatabaseFromConfig.func1() at server_context.go:352
03:47:58.768315 2017-03-14T03:47:58.768-05:00 CRUD: Taking Database : ptxdata, offline
03:47:58.768332 2017-03-14T03:47:58.768-05:00 CRUD: Waiting for all active calls to complete on Database : ptxdata
03:47:58.768365 2017-03-14T03:47:58.768-05:00 HTTP+: #225:     --> 200 OK DB has gone offline  (0.0 ms)
03:47:58.768544 2017-03-14T03:47:58.768-05:00 CRUD: Database : ptxdata, is offline
03:47:58.768780 2017-03-14T03:47:58.768-05:00 Bucket: Refresh() [212.038µs]

### Actual Behavior
syncgateway bucket going offline. All request t syncgateway are failing.

### Expected Behavior
syncgateway should be able to find the bucket information for healthy node and continue

**Comment by adamcfraser** [comment]
It's expected that the bucket goes offline when Sync Gateway loses the DCP feed.  Is the actual issue here that the bucket is failing to automatically come back online?  Are you seeing a difference in behaviour between DCP and TAP?

**Comment by ArihantRk** [comment]
In TAP we faced same issue in 1.2.0 but 1.3.1 we did not. DCP we are onserving same issue bucket going offline during start of sybcgateway eventhough all couchbase nodes are healthy and also when one node goes down.

**Comment by adamcfraser** [comment]
1. In 1.3.1, did the bucket automatically reconnect, or not go offline in the first place?
2. In 1.4 using DCP, the bucket is going offline and failing to come back online automatically?
3. In 1.4 using TAP, do you see the same behaviour as 1.3.1?

**Comment by ArihantRk** [comment]
@adamcfraser 
1. In 1.3.1 we did not observed bucket going offline.
2. In 1.4 using DCP, bucket is going offline at the start and during traffic and automatically bucket is not coming to online state.
3. In 1.4 using TAP, we have not tested node failover scenarios.

**Comment by tleyden** [comment]
Possibly fixed in ea211429fc68b645d69a3489d53a95113d19ad1e

**Comment by adamcfraser** [comment]
DCP processing significantly enhanced in 1.5.0.  Please reopen if you continue to see this in 1.5.0.
