### ISSUE TITLE
Assign channel dinamically on user

### ISSUE THREAD

**Issue by gine** [couchbase/sync_gateway#2415]
METHOD 1

I have 2 roles (A[admin]  B[agents]), 2 user (cA  dB) and 3 type of documents (Y[clients] W[docs related to Y] Z[staff related to Y]).

On sync gateway i have this function:

```
if(doc.type==Y)
  channel(doc._id)
elseif(doc.type==W || doc.type==Z)
  channel(doc.Y._id)
```

On client-side when the user cA save a doc.type==Y with the attribute doc.assign == dB, I set the new channel on user dB with a rest api operation ( /_user/_put )

Y will be seen from dB user because on client-side will arrive a change for that document, but the documents W and Z will never seen from dB until maybe someone re-save this docs or dB user clean its database and download it again.

A can see  every docs, but B can see only clients and related clients documents where A setted B.

--
METHOD 2

The other approach is to save, on docs.channels = [] of every documents related to the document Y, the channel (presetted on each user with role agent) of the agent chosed. But in my case can be 100 docs each agent setted on Y.

--

I would like to use the method 1 but without "something" from the server it doesn't work. Is there any other approach? Can you work to implement this "something"? Is there any other solution to avoid stupid multiple revision?

Thanks.

**Comment by ajres** [comment]
@gine

Hi, have you looked at the sync function access() method, it dynamically adds channels to users.

Here are the [docs]{https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/sync-function-api-guide/index.html}

**Comment by adamcfraser** [comment]
This is definitely the intended use case for the Sync Function.  If you have further questions on usage, the forums would be the best place to get an answer.

https://forums.couchbase.com/c/mobile/sync-gateway
