### ISSUE TITLE
Move more functionality into sg-bucket interface and avoid type assertions

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2418]
## Move GetMaxVbno() into sg-bucket interface 

This code is unnecessarily brittle:

```
	log.Printf("indexWriteBucket: %+v type: %T", k.indexWriteBucket, k.indexWriteBucket)
	cbBucket, ok := k.indexWriteBucket.(base.CouchbaseBucketGoCB)
	var maxVbNo uint16
	if ok {
		maxVbNo, err = cbBucket.GetMaxVbno()
		if err != nil {
			base.Warn("Unable to obtain vbucket count from cluster - defaulting to 1024")
			maxVbNo = 1024
		}
	} else {
		// walrus, for unit testing
		base.Warn("Not a couchbase bucket - assuming walrus, setting maxVbNo=1024")
		maxVbNo = 1024
	}
```

If `k.indexWriteBucket` is a `*base.CouchbaseBucketGoCB` rather than a `base.CouchbaseBucketGoCB`, then this code will break.  So far it looks like that's what's behind https://github.com/couchbaselabs/mobile-testkit/issues/1072

If `GetMaxVbno()` was defined on the sg-bucket bucket interface and all buckets implemented it, it feels like it would be more robust.

**Comment by adamcfraser** [comment]
I'm not against the idea of adding GetMaxVbno() to the bucket interface, but I think the check here may have just been implemented incorrectly - I think should have been this all along:
`cbBucket, ok := k.indexWriteBucket.(*base.CouchbaseBucketGoCB)`

**Comment by tleyden** [comment]
This also should be moved into sg-bucket interface:

Add to the bucket interface: `getUUID()`

sgw_pindex.go

```
cbBucket, ok := bucket.(base.CouchbaseBucket)
	if ok {
		log.Printf("is base.CouchbaseBucket, call GetCBGTIndexName")
		indexName = GetCBGTIndexName(cbBucket)
	} else {
		log.Printf("not base.CouchbaseBucket, call bucket.GetName()")
		indexName = bucket.GetName()
	}
	return indexName
```

**Comment by djpongh** [comment]
Make sure all functional test post merge.

**Comment by tleyden** [comment]
> Add to the bucket interface: getUUID()

I'm not seeing an easy way to get the bucket UUID via gocb.  I posted a question on the go sdk forum:

https://forums.couchbase.com/t/is-it-possible-to-get-the-bucket-uuid/12267

**Comment by tleyden** [comment]
I'm looking at all the places where we need to do type assertions, and will list the ones that look like decent candidates for moving into the sg-bucket interface.

## GetStatsVbSeqno

If this method:

```
_, highSeqnos, err := cbBucket.GetStatsVbSeqno(maxVbNo, false)
```

is moved into the sg-bucket interface, then this type assertion could be removed:

```
// Make sure that the index bucket and data bucket have correct sequence parity
// https://github.com/couchbase/sync_gateway/issues/1133
func VerifyBucketSequenceParity(indexBucketStableClock SequenceClock, baseBucket Bucket) error {

	bucket, err := GetCouchbaseBucketFromBaseBucket(baseBucket)
	if err != nil {
		Warn(fmt.Sprintf("Bucket is a %T not a base.CouchbaseBucket, skipping verifyBucketSequenceParity()\n", bucket))
		return nil
	}

	return VerifyBucketSequenceParityCouchbaseBucket(indexBucketStableClock, bucket)

}
```
