### ISSUE TITLE
Flushing DB can cause subsequent replication to miss docs because of checkpoint

### ISSUE THREAD

**Issue by paulharter** [couchbase/sync_gateway#2419]
I guess this might be a feature request rather than a bug. ie make it safer to delete/flush db.

### Sync Gateway version
==== Couchbase Sync Gateway/1.4.0(2;9e18d3e) ====

### Operating system
Ubuntu  in recent docker images

### Config file
```javascript
{
   "interface":":4984",
   "adminInterface":":4985",
   "log":["REST"],
    "replications":[
        {
            "replication_id":"down",
            "source": "http://test_user:password@sync_gateway_b:4984/sync_gateway",
            "target": "sync_gateway",
            "continuous":true,
            "changes_feed_limit":1000,
            "filter":"sync_gateway/bychannel",
            "query_params":["shared_docs"]
        },
        {
            "replication_id":"up",
            "target": "http://test_user:password@sync_gateway_b:4984/sync_gateway",
            "source": "sync_gateway",
            "continuous":true,
            "changes_feed_limit":1000,
            "filter":"sync_gateway/bychannel",
            "query_params":["shared_docs"]
        }
    ],
   "databases":{
      "sync_gateway":{
        "users":{"test_user":{ "disabled": false, "admin_channels": ["shared_docs"], "password": "password" }},
         "server":"http://couchbase_a:8091",
         "bucket":"sync_gateway",
         "feed_type": "DCP",
         "sync":`function(doc) {channel(doc.channels); requireUser("test_user"); requireAccess("shared_docs");}`
      }
   }
}
```

### Log output
NA

### Expected behavior
After stopping one to two SG replicatiing to each other, flushing the bucket and restarting, all documents present across the two DB should replicate correctly.

### Actual behavior
They don't

### Steps to reproduce

Create 2 x SG called A and B set up pull and push replications from A to sync all docs in "shared_docs" channels

Add some docs:

to A:
A1 channels=["shared_docs"]
A2 channels=["shared_docs"]
A3 channels=[]
A4 channels=[]
A5 channels=[]
A6 channels=[]

to B:
B1 channels=["shared_docs"]
B2 channels=["shared_docs"]
B3 channels=[]

As expected
A gets A1-6 and B1-2
B gets B1-3 and A1-2

Turn off both SG
flush A
turn on SG A

add to A
A7 channels=["shared_docs"]

turn off SG A

Turn everything on again
A gets A1 A2 A7 B1 B2 which is correct
B gets B1 B2 B3 A1 A2 but is missing A7

So any docs that are added to A after it is flushed but before a new successful replication to B will not then be replicated to B. If the checkpoint in B is deleted at the same time as flushing A then all documents are replicated correctly.

Is this expected behaviour?

Is this the same for mobile clients where is this more likely to happen?

Maybe this could be fixed if all buckets/DB contained a UUID doc that tied them to the target's checkpoint, then deleting/flushing would in effect remove checkpoint.

Thanks

P

**Comment by adamcfraser** [comment]
This makes sense, and I was going to suggest something similar to the last point - Sync Gateway should create a UUID to identify itself, persist that UUID to it's bucket, and use that UUID when setting remote checkpoints.

**Comment by paulharter** [comment]
Sounds good.  Maybe CB lite too if same thing happens there?

**Comment by adamcfraser** [comment]
Migrated to [CBG-796](https://issues.couchbase.com/browse/CBG-796)
