### ISSUE TITLE
Replication Issue in Sync Gateway 1.4

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#2426]
[Client and SG Logs.zip](https://github.com/couchbase/sync_gateway/files/873818/Client.and.SG.Logs.zip)

Issues with one time pull replication in Sync Gateway 1.4. This issue did not exist in the 1.4 DP.

### Log output
Please see attached.

### Steps to reproduce
1 – CBL connects to SG, gets authorized, assigned to a channel, etc.
2 – CBL requests any/all data changes in that channel (one-time pull).
3 – SG responds that the channel is empty (or at least closes the pull replication without sending any documents).
4 – SG Reopens the pull replication to send the documents that were in the channel, without prompting from CBL, and without CBL receiving the replication.

**Comment by adamcfraser** [comment]
This sounds like the scenario discussed at length here:
https://forums.couchbase.com/t/how-to-address-the-issue-caused-by-initial-one-shot-pull-skiping-iteration/12138
