### ISSUE TITLE
Avoid document body unmarshalling on changes requests

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2428]
Currently changes requests that specify style=all_docs have unnecessary performance overhead when retrieving branched documents.  

changes.addDocToChangeEntry will retrieve the document from the bucket (to identify the set of leaf revisions).  In the process it will unmarshal the entire doc.

Two enhancements:
 - Store the list of leaf rev ids in the revision cache along with the active revision, to avoid retrieving the document from the bucket when it's resident in the rev cache
 - When bucket retrieval is required, unmarshal only the rev history, not the full doc body.

**Comment by adamcfraser** [comment]
For the second item ("When bucket retrieval is required, unmarshal only the rev history, not the full doc body.") - in the context of this ticket, this is specifically about the call to db.GetDoc in changes.addDocToChangeEntry.  

One option would be to add a new db method (like 'GetDocSyncData') that only returns the sync data.

Another would be to modify the document struct to always lazy unmarshal the document body.  This has the potential for more benefits across the entire codebase, but would require more significant refactoring - it might make more sense to hold that refactoring until 2.0, when the sync data moves to xattrs.

**Comment by tleyden** [comment]
Notes to self:

1. Get doc bytes by calling `GetRaw` 
1. Call UnmarshalDocumentSyncData

Benchmark:

1. Pre-timer setup: Create 2k docs of size 50k, 1000 keys with branches, 1 parent + 2 child branches -- doesn't matter which API .. bucket api
1. Start the timer 
1. Changes request of all docs (could also do GetDoc call, but misses other possible things).  One shot, .. etc

**Comment by tleyden** [comment]
Test results


| Fix Status  | Millisconds/Op | Bytes/Op | Allocations/Op |
| ------------- | ------------- | ------------- | ------------- |
| Without Fix  | 5074  | 699042928 | 1031780 | 
| Without Fix  | 5127  | 699030160 | 1031734 | 
| Without Fix  | 4689  | 699035600 | 1031753 | 
| With Fix  | 1366  | 341696136 | 493655 | 
| With Fix  | 1334  | 341695456 | 493651 | 
| With Fix  | 1307  | 341695536 | 493652 | 

Without fix: 8ef9a00e9154b03702f56aa401a3da1c1e2f6091
With fix: 341bf8090b6e1866ac12fb6f556bec4b7afb4c10

So it looks like a ~3.5X speedup
