### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#2435]
The sync gateway logs should include information about what features are being used in a particular deployment. 

This data can be used to determine which features are being in a particular deployment.

**Comment by adamcfraser** [comment]
@ssmotra This issue is too vague in its current form to be implemented.

It's not clear what's meant by 'features', and why this would be included in the Sync Gateway logs (as opposed to being available in the other material that's aggregated by sg_collectinfo).

**Comment by ghost** [comment]
This was from my notes and I did not want to forget adding it here. I'll add more meat to the ticket and then add it to the backlog by adding the correct label.

**Comment by djpongh** [comment]
We need more info before a ticket is filed. Closing. Feel free to reopen when you have more details.
