### ISSUE TITLE
RedHat/Centos 6 'initctl restart sync_gateway' does not work as expected

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2441]
On RedHat/CentOS 6 executing 

`initctl restart sync_gateway` 

Does not result in Sync Gateway being stopped and an new instance started.

The original process ID is still running after the above command.

This means that a restart can not be used load new config changes.

As a work around the following two commands can be run

`initctl stop sync_gateway`
`initctl start sync_gateway`

This will result in a new Sync Gateway process being started which will read the latest config.

This particular OS uses the Upstart init system, which does not directly support a `restart` event.

Further investigation is needed to determine how to handle it in the Upstart service script.

**Comment by bbrks** [comment]
This behavior of Upstart can't be changed or worked around. I've raised [DOC-3131](https://issues.couchbase.com/browse/DOC-3131) to add a note to the documentation for RHEL/CentOS 6 that both `initctl stop sync_gateway` and `initctl start sync_gateway` must be issued for a restart.

This issue doesn't affect other distros, or older/newer versions of RHEL/CentOS.
