### ISSUE TITLE
Detected data races

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2451]
| Function/Method Call | Gist | Product  |  Map Access  | 
| ------------- | ------------- | ------------- | ------------- |
| (*SyncSequenceClock).SetMaxSequence()  | [gist](https://gist.github.com/tleyden/6027293cf2d38aab317913830b854dd2) | Sync Gateway | N |
| (*KvChangeIndexWriter).Init.func3.1()  | [gist](https://gist.github.com/tleyden/f6a59c811f3319b92299679592ef358d) | SG Accel | N |
| gomemcached/debug.(*mcops).count()  | [gist](https://gist.github.com/tleyden/0a69e6798278dadc998712965d96bcb3) | SG Accel | N | 
| db.(*changeListener).NotifyCheckForTermination()  | [gist](https://gist.github.com/tleyden/d0b0e1c3e9ae52db150d36db98513b8c) | Sync Gateway | N |
| github.com/couchbase/cbgt.CalcPlan() | [gist](https://gist.github.com/sethrosetter/90700fe772bc02231a52298018a3bae3#file-gistfile1-txt-L1-L7) | CBGT  | N |
| github.com/couchbase/go-couchbase.(*Bucket).getMaxRetries() | [gist](https://gist.github.com/sethrosetter/90700fe772bc02231a52298018a3bae3#file-gistfile1-txt-L8-L14) | Sync Gateway  | N |
| github.com/couchbase/go-couchbase.Bucket.HealthyNodes() | [gist](https://gist.github.com/sethrosetter/90700fe772bc02231a52298018a3bae3#file-gistfile1-txt-L15-L21) | Sync Gateway  | N |
| github.com/couchbase/go-couchbase.Bucket.Nodes() | [gist](https://gist.github.com/sethrosetter/90700fe772bc02231a52298018a3bae3#file-gistfile1-txt-L22-L28) | Sync Gateway  | N | 
| github.com/couchbase/sync_gateway/db.(*sequenceHasher).calculateHash() | [gist](https://gist.github.com/sethrosetter/5b8f21a2d88666a9475fdb3b5af5f713#file-gistfile1-txt-L80-L94) | Sync Gateway  | N |
| github.com/couchbase/sync_gateway/db.ClockMatches() | [gist](https://gist.github.com/sethrosetter/90700fe772bc02231a52298018a3bae3#file-gistfile1-txt-L43-L49) | Sync Gateway  | N |
| github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*ChannelWriter).AddSet() | [gist](https://gist.github.com/sethrosetter/90700fe772bc02231a52298018a3bae3#file-gistfile1-txt-L50-L56) | SG Accel  | N |
| github.com/couchbase/cbgt.CalcPlan() | [gist](https://gist.github.com/sethrosetter/90700fe772bc02231a52298018a3bae3#file-gistfile1-txt-L64-L70) | CBGT  | Y |
| sg_accel.(*SGAccelContext).registerCbgtPindexType() | [gist](https://gist.github.com/sethrosetter/90700fe772bc02231a52298018a3bae3#file-gistfile1-txt-L71-L77) | SG Accel  | Y |
| db.(*changeCache).Clear() | [gist](https://gist.github.com/sethrosetter/4ffbbdefe178d5c7f56ea45fe785511c#file-base_cc_data_races-L51-L78) | Sync Gateway  | N |
| go-couchbase.(*TapFeed).closeNodeFeeds() | [gist](https://gist.github.com/sethrosetter/4ffbbdefe178d5c7f56ea45fe785511c#file-base_cc_data_races-L360-L385) | go-couchbase  | N |
| go-couchbase.(*Bucket).getMaxRetries() | [gist](https://gist.github.com/sethrosetter/4ffbbdefe178d5c7f56ea45fe785511c#file-base_cc_data_races-L669-L706) | go-couchbase  | N |
| go-couchbase.Bucket.Nodes() | [gist](https://gist.github.com/sethrosetter/4ffbbdefe178d5c7f56ea45fe785511c#file-base_cc_data_races-L1081-L1113) | go-couchbase  | N |
| go-couchbase.Bucket.HealthyNodes() | [gist](https://gist.github.com/sethrosetter/4ffbbdefe178d5c7f56ea45fe785511c#file-base_cc_data_races-L1184-L1218) | go-couchbase  | N |
| github.com/couchbase/sync_gateway/rest.(*ServerContext).startShadowing()  | [gist](https://gist.github.com/sethrosetter/1395eb901d043dd316f2fa0410adb778#file-gistfile1-txt-L51-L72) | Sync Gateway | N |
| github.com/couchbase/go-couchbase.(*Bucket).UpdateBucket() | [gist](https://gist.github.com/sethrosetter/1395eb901d043dd316f2fa0410adb778#file-gistfile1-txt-L360-L378) | go-couchbase | N |
| github.com/couchbase/go-couchbase.(*TapFeed).connectToNodes()  | [gist](https://gist.github.com/sethrosetter/1395eb901d043dd316f2fa0410adb778#file-gistfile1-txt-L463-L486) | go-couchbase | N |
| github.com/couchbase/go-couchbase.(*TapFeed).Close() | [gist](https://gist.github.com/sethrosetter/1395eb901d043dd316f2fa0410adb778#file-gistfile1-txt-L1184-L1225) | go-couchbase | N |
| github.com/couchbase/sync_gateway/base.(*ShardedClock).UpdateAndWrite.func1.1() |  [gist](https://gist.github.com/sethrosetter/5b8f21a2d88666a9475fdb3b5af5f713#file-gistfile1-txt-L17-L32) | Sync Gateway | N |
| github.com/couchbase/sync_gateway/base.(*ShardedClockPartition).GetSequence() |  [gist](https://gist.github.com/sethrosetter/5b8f21a2d88666a9475fdb3b5af5f713#file-gistfile1-txt-L33-L48) [gist2](https://gist.github.com/tleyden/37014f2884bc85086f96b5eedfc42365) | Sync Gateway | N |
| github.com/couchbase/sync_gateway/base.(*ShardedClockPartition).getSequenceForOffset() | [gist](https://gist.github.com/sethrosetter/5b8f21a2d88666a9475fdb3b5af5f713#file-gistfile1-txt-L49-L64) | Sync Gateway | N |
| github.com/couchbaselabs/sg-replicate.(*ReplicationStats).AddDocsRead() |  [gist](https://gist.github.com/sethrosetter/5b8f21a2d88666a9475fdb3b5af5f713#file-gistfile1-txt-L95-L110) | SG Replicate | N |
| github.com/couchbaselabs/sync-gateway-accel/indexwriter.(*KvChangeIndexWriter).Init.func3.1() |  [gist](https://gist.github.com/sethrosetter/5b8f21a2d88666a9475fdb3b5af5f713#file-gistfile1-txt-L111-L125) | SG Accel | N |
| runtime.mapaccess2_faststr() |  [gist](https://gist.github.com/sethrosetter/5b8f21a2d88666a9475fdb3b5af5f713#file-gistfile1-txt-L126-L141) [gist2](https://gist.github.com/tleyden/a93fefede1372e5bd8ff5ca173e0cb2b) | CBGT | Y |
| runtime.mapassign1() | [gist](https://gist.github.com/sethrosetter/5b8f21a2d88666a9475fdb3b5af5f713#file-gistfile1-txt-L142-L158) | SG Accel | Y |
| sync/atomic.CompareAndSwapInt32() | [gist](https://gist.github.com/sethrosetter/5b8f21a2d88666a9475fdb3b5af5f713#file-gistfile1-txt-L159-L174) | SG Replicate | N |

**Comment by adamcfraser** [comment]
Since there's no tracking of modifications/fixes made for these, the list will need to be regenerated to be actionable.  Closing.
