### ISSUE TITLE
Docs missing in sg-replication when backup-restore of only _sync:user documents of syncgateway bucket

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2453]
### Sync Gateway version
1.3.1

### Operating system
RedHat 7.2 

### Expected behavior
Docs are missing from replication

### Actual behavior
Should not 

### Steps to reproduce
1.  Inserted 100 users to source cluster. 
2. Inserted 100 document to source cluster. It got replicated to destination cluster.
3. Took filtered backup of user documents alone from source cluster.
4. Shutdown all syncgateway and syncreplicate nodes.
5. Deleted and recreated ptxdata bucket on both the clusters.
6. Restored the backup taken in step 3  to both clusters.
7.  Started all the syncgateway and syncreplicate nodes.
8. Tried inserting data as of step 2. 

Observation :
Once backup restored in source cluster for 100 user documents , _sync:seq documents will have value as 0. But _changes feed(mutation feed from couchbase) will show 100 user profiles documents which sg-replicate ignores from replication to destination cluster and update _sync:local (reference document) as 100.

If 100 normal documents are inserted to source cluster which will make _sync:seq value as 100 but these documents will not be replicated as _sync:local document(reference document for replication) will be already updated to 100 by user documents. Hence these documents will not replicated to destination cluster.

**Comment by ajres** [comment]
@ArihantRk I wouldn't recommend using  backup/restore to only transfer a subset of the contents of a bucket. This does not completely replicating the state of the bucket, in this situation the behaviour of Sync Gateway is not defined

What problem are you trying to resolve using this process?

**Comment by ArihantRk** [comment]
@ajres since sg-replication does not support replication of _sync:user documents. In case of Disaster recoveryR, we would need user documents to be created at both cluster hence we are taking backup and restore (key-based) .

In case of disaster recovery, we wanted to restore all user profiles so that all clients can connect back quickly. Recreation of user profiles may take longer time and may cause longer outage. Also we don't want to backup entire bucket data. 

What is the best solution for DR without taking full backup?

**Comment by adamcfraser** [comment]
@ArihantRk As you've seen, sg-replicate isn't intended for DR, it's intended for two-way data replication.  

Attempting to isolate user documents in a backup can introduce problems - user documents are assigned sequence numbers on update, and isolated backup/restore will have the potential for sequence ordering issues. 

For DR, I think the better approach would be a unidirectional XDCR backup of the bucket.  I don't think there's a 'partial backup' solution that will maintain data integrity.
