### ISSUE TITLE
Does gocb need to support TCP connection keep alive

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2461]
go-couchbase supports tcp connection keep alive.

With SG migration to gocb, should gocb support the connection keep alive, or does it use a different connection model?

The motivation of this question is that some customers have firewalls between SG and CBS which close idle connections after a fixed period.

In this case SG reports connection errors and eventually reconnects.

**Comment by ajres** [comment]
From discussion with Go SDK team:
```
The Go SDK does not currently expose a TCP keep alive  option, however it does perform configuration fetches on a regular basis which are automatically round-robined over the various Couchbase server connections. This acts as an implicit keep-alive and should mitigate any sort of firewall disconnects.

Currently configuratuion is fetched from one node every 10 seconds, with Go SDK 1.4.0 for Server 5.0, that will be down to 2.5 seconds.

So a 10 node cluster will be completely 'pinged' every 100s currently, and 25s in the next minor release
```

**Comment by ajres** [comment]
@adamcfraser do you think the Go SDK behaviour us acceptable or do we need to raise a ticket for the SDK to expose a TCP keep alive configuration option?

If the Go SDK behaviour is adequate, is there an SG config where the CouchbaseKeepaliveInterval will have no affect (go-couchbase never called). 

We should log a warning in this case that the CouchbaseKeepaliveInterval config property will not take affect.

**Comment by adamcfraser** [comment]
@ajres Given that we're not using gocb for DCP, this sounds fine - I wouldn't expect to have any other long-lived idle connections related to gocb.

It's worth investigating whether the previous CouchbaseKeepaliveInterval was used only for TAP feeds, and if so, whether it's used/needed for cbdatasource/DCP.

**Comment by ajres** [comment]
In base.GetBucket()

The GetCouchbaseBucket() gets called for both feed types:

```
case GoCB, GoCBCustomSGTranscoder:
			if strings.ToLower(spec.FeedType) == TapFeedType {
				Warn("Cannot use TAP feed in conjunction with GoCB driver, reverting to go-couchbase")
				bucket, err = GetCouchbaseBucket(spec, callback)
			} else {
				bucket, err = GetCouchbaseBucketGoCB(spec)
			}

		case GoCouchbase:
			bucket, err = GetCouchbaseBucket(spec, callback)
		default:
			panic(fmt.Sprintf("Unexpected CouchbaseDriver: %v", spec.CouchbaseDriver))
		}
```

GetCouchbaseBucket() calls:

`client.GetPool(poolName)`

Which refreshes the connection pools, which use the default connection creator that uses the TCPKeepAlive settings.

**Comment by ajres** [comment]
base.StartDCPFeed() calls cbdatasource.NewBucketDataSource() which takes a poolName and sets it on the bucketDataSource struct.

The pool is used when bucketDataSource.Start() is called.
