### ISSUE TITLE
[enhance] encrypt password field in db configuration for security objective

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#2475]
I am using SG 1.4.0-2 on MAC 10.10.5 (14F2315) with following config
```
{
  "log": ["*"],
  "CORS": {
    "Origin":["*"],
    "LoginOrigin":["*"],
    "Headers":["Content-Type"],
    "MaxAge": 1728000
  },
  "databases" : {
    "sgdb" : {
      "server":"http://127.0.0.1:8091",
      "bucket":"cbdb",
      "username":"Administrator",
      "password":"let_me_in",
      "users" : {
        "GUEST": { "disabled" : true }
      },
      "enable_star_channel" : false,
      "sync" :
    `
  ......
```
for security objective, the password field in db configuration should be encrypt.

**Comment by Fujio-Turner** [comment]
@atom992 ,  instead of hard coding the CB bucket and SG db info why don't you use the HTTP PUT _config when you boot strap the the sync gateway. That way the password will only be in memory and will be obfuscated when you do a GET on the SG db _config.

https://developer.couchbase.com/documentation/mobile/current/references/sync-gateway/admin-rest-api/index.html?language=ios#!/database/put_db_config

**Comment by atom992** [comment]
good idea.but I think encrypt password field in db configuration is necessary.

**Comment by adamcfraser** [comment]
@atom992 I'm not sure encrypting the password in the config file provides much additional security (beyond some obfuscation) - wouldn't that just require Sync Gateway to know the location of the key to decrypt that password, and not provide any additional real security?  (i.e. anyone with access to the config file could decrypt the password themselves)

Let me know if you've got additional details on your specific concerns.  Perhaps adding support for retrieving environment variables in the Sync Gateway config would be an alternative approach?

**Comment by atom992** [comment]
[FYI ](https://www.owasp.org/index.php/Password_Plaintext_Storage)

**Comment by adamcfraser** [comment]
@atom992 That link doesn't make a case for encryption as a solution for the problem of plaintext passwords in config files - it's just describing the general problem.

**Comment by ghost** [comment]
Request to encrypt the CB server credentials for compliance.

**Comment by adamcfraser** [comment]
Targeted as part of manageability work in 3.0.  In the interim, can avoid plaintext credentials in config via x.509 auth.

**Comment by adamcfraser** [comment]
Closing based on age - will be tracked with 3.0 work as prioritized.
