### ISSUE TITLE
Tutorial sync-gateway-config.json isCreate bugfix

### ISSUE THREAD

**Issue by neopaf** [couchbase/sync_gateway#2486]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
2017-04-19T16:12:49.883+03:00 ==== Couchbase Sync Gateway/1.4.0(2;9e18d3e) ====

### Operating system
macOS

isCreate is obviously broken.
currently:
```
  function isCreate() {
    // Checking false for the Admin UI to work
    return ((oldDoc == false) || (oldDoc == null || oldDoc._deleted) && !isDelete());
  }
```

it fails in UI:
given 
* oldDoc==false 
* doc._deleted==true

isCreate currently returns true, which is wrong.

I feel should be:
```
  function isCreate() {
    // Checking false for the Admin UI to work
    return ((oldDoc == false || oldDoc == null || oldDoc._deleted) && !isDelete());
  }
```

**Comment by jamesnocentini** [comment]
> it fails in UI:
> given
> 
> oldDoc==false
> doc._deleted==true

So in this case, it's a deletion revision (`doc._deleted` is `true`) without a parent (`oldDoc` is `null` (`false` in the Admin UI)) which is an edge case I think. Do you mean the Admin UI fails to load in this case or that `isCreate` is returning something different to what you would expect?

Note: the `isCreate` function is taken from https://developer.couchbase.com/documentation/mobile/1.4/training/develop/adding-security/index.html

**Comment by neopaf** [comment]
James, isCreate returns "true".
This is totally unexpected, because it is wrong.
See documents? No oldDoc available to UI, and current doc._deleted==true.
This is NOT a new document.

**Comment by neopaf** [comment]
If you'd agree this is bug, it's good idea to fix that web page too.
Do we need a separate issue for that?

**Comment by jamesnocentini** [comment]
Thanks @neopaf, I see how the issue can happen with the current sync function now. Under the conditions you outlined, the return statement becomes `true || false && false` which is `true`.  Your suggestion would return `(true || false) && false` which is `false`. Let's keep this ticket open to update the web page.

> If you'd agree this is bug

Can you be more specific? What is a bug?

**Comment by neopaf** [comment]
James, I was referring to same thing you refer in "the issue can happen", just that.

So let us change 
* [code of sample](https://forums.couchbase.com/c/mobile/sync-gateway)
* AND on [the page](https://developer.couchbase.com/documentation/mobile/1.4/training/develop/adding-security/index.html)

**Comment by jamesnocentini** [comment]
Ok, just wanted to confirm there wasn't something else you had identified. We'll update the page soon.

**Comment by djpongh** [comment]
Moved to Jira DOC-3021
