### ISSUE TITLE
console.dir is missing

### ISSUE THREAD

**Issue by neopaf** [couchbase/sync_gateway#2487]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
2017-04-19T16:12:49.883+03:00 ==== Couchbase Sync Gateway/1.4.0(2;9e18d3e) ====

### Operating system
macOS

### problem

console.dir outputs NOTHING. not implemented?

in UI it is very convenient to see things with it.
but one wants that logged on server side... and there it does not work.

### workaround
`console.log("doc: "+ObjToSource(doc))`
from
http://stackoverflow.com/questions/957537/how-can-i-display-a-javascript-object

(but it is not as convenient as console.dir -- in browser there is a nice GUI folding/unfolding of parts of complicated document which does NOT work when it's all just a string)

**Comment by ajres** [comment]
Sync Gateway uses the [otto](https://github.com/robertkrimen/otto.git) Javascript interpreter.

On latest otto git master console.dir is still a [no-op](https://github.com/robertkrimen/otto/blob/7d9cbc2befca39869eb0e5bcb0f44c0692c2f8ff/console.go#L27)

The [specification](https://developer.mozilla.org/en-US/docs/Web/API/Console/dir) for this call is that it displays an interactive list of the properties of the specified JavaScript object.

This is not directly applicable when writing to the SG log.

**Comment by ajres** [comment]
issue [#2471](https://github.com/couchbase/sync_gateway/issues/2471) is tracking updating the SG depenedency to the latest otto version which includes support for [JSON.stringify](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify).

This might be more appropriate for SG logging of JavaScript objects.

**Comment by neopaf** [comment]
Andrew, that would be a step forward, definitely.
But not as elegant as .dir
for in web-browser complex JSON documents are extremely convenient foldable.

One would have to use both:
```
console.log(JSON.stringify(object));
console.dir(object)
```

so to have best of both worlds: logging on server-side, and web-browser logging for debugging.

I would much rather prefer to use only one line.
I guess, the only course is to go to otto tracker and plead there ;)
