### ISSUE TITLE
XATTRS: Getting doc after restart fails

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2497]
### Sync Gateway version
1.4.2-337 / 5.0.0-2703

### Operating system
CentOS 7

### Config file
```javascript
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                }
            }
        },
        "interface": ":4984",
        "log": [
            "*"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
    }
}
```

### Log output
https://gist.github.com/sethrosetter/1bd53de00deeb4d029328bff47295060

### Expected behavior
After reset, the doc should be gettable

### Actual behavior
The doc is not found and a 404 is returned

### Steps to reproduce
1.  pytest -s --skip-provisioning --xattrs --pdb --mode=cc --server-version=5.0.0-2703 --sync-gateway-version=1.4.2-337 -k "test_attachment_revpos_when_ancestor_unavailable[sync_gateway_default]" testsuites/syncgateway/functional/tests

**Comment by adamcfraser** [comment]
https://github.com/couchbaselabs/mobile-testkit/blob/769e1112cb50496856e0b4b0434f92c129bcad32/testsuites/syncgateway/functional/tests/test_attachments.py#L24

**Comment by adamcfraser** [comment]
@seth What's meant by 'after reset' in the expected behaviour?

**Comment by sethrosetter** [comment]
@adamcfraser 
- Stopping SG
- Deleting _sync:rev docs on Server
- Start SG

**Comment by adamcfraser** [comment]
Steps to repro:
 - create doc (potentially requires attachments), create several revisions
 - restart SG
 - attempt to retrieve doc w/ conflicts=true, revs=true

**Comment by adamcfraser** [comment]
I haven't been able to reproduce this locally following the above steps (including deleting _sync:rev documents).  May need to work with @sethrosetter to get a locally reproducible scenario.

**Comment by sethrosetter** [comment]
Not seeing with 1.4.2-337. Will reopen if I see it again.
