### ISSUE TITLE
Allow tombstones to be written with a TTL

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#2498]
At present, when a document it deleted in Sync Gateway, we keep the tombstone in Couchbase Server indefinitely. Over a long term deployment with unique keys, this is going be be ever increasing and eventually a point of failure (disk space may be cheap, but running out of disk space will happen well before running out of UUIDs!).

There's a good reason for keeping this data around - we don't know how long a client may wait to sync, and we would still need to propagate the delete out when they eventually do. Couchbase Server has the same problem with XDCR - we don't know how long the link between clusters might be down. The [Metadata Purge Interval](https://developer.couchbase.com/documentation/server/current/architecture/core-data-access-bucket-disk-storage.html) allows us to strike a balance here - a reasonable time to hold onto the tombstone before purging it. The default here is 3 days, which is quite conservative for CB, but probably a bit aggressive for SG. Regardless, I think the concept is valid.

The good news is that this shouldn't need re-inventing at the SG level - we could simply write the CB document with a TTL and let CB take care of it.

We could make this opt-in by only doing it if specified in the config with a default of "don't purge".

**Comment by JFlath** [comment]
One thing I've slightly glossed over here is conflicts. The above makes sense if you assume that there are no conflicts, but not for branching trees. In this case, we should probably only care about doing this if the current winning rev is a tombstone (i.e. any others are too).

**Comment by adamcfraser** [comment]
Some additional discussion around this topic on https://github.com/couchbase/sync_gateway/issues/1860

**Comment by djpongh** [comment]
Convergence supports this. Not planning to implement on non convergence.
