### ISSUE TITLE
Webhook event not fired when using bucket shadowing

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2500]
Commit ebb92f9, from PR #2014 introduced a regression that results in no WebHook events being fired for document updates triggerd by processing changes from a shadow bucket feed.

**Comment by ajres** [comment]
Regression is in db/crud.go in function UpdateDoc

**Comment by ajres** [comment]
Need to add a failing unit test to catch this regression, then fix.

**Comment by tleyden** [comment]
Looks like there is also a [functional test](https://github.com/couchbaselabs/mobile-testkit/blob/414f6e4e7161d3f75c8b39e9ae97df682ba16db4/testsuites/syncgateway/functional/tests/test_db_online_offline_webhooks.py) that tests webhooks.  

@sethrosetter any idea if this test is currently passing on the latest master branch?

**Comment by adamcfraser** [comment]
@tleyden I don't think those functional tests include bucket shadowing.

**Comment by tleyden** [comment]
Yeah you're right, thanks for the clarification
