### ISSUE TITLE
Bucket Shadowing is possibly incompatible with DCP feeds

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2502]

**Comment by tleyden** [comment]
To play it safe, until we know about the compatibility, it might make sense to add this check:

```
func (sc *ServerContext) startShadowing(dbcontext *db.DatabaseContext, shadow *ShadowConfig) error {

	if shadow.FeedType != base.TapFeedType {
		return fmt.Errorf("Bucket Shadowing only works with the TAP feed type. " +
			"Please add feed_type=TAP and retry.")
	}

```

**Comment by adamcfraser** [comment]
In general I think bucket shadowing is compatible with using a DCP feed.  The main difference in the shadowing scenario is that we force the feed to start from zero, but there's handling for that case in the StartDCPFeed code.  

There are some functional differences - the DCP feed doesn't send the 'backfill start/backfill end' messsages that the shadower uses to provide logging on shadowing status:
https://github.com/couchbase/sync_gateway/blob/master/db/shadower.go#L65
https://github.com/couchbase/sync_gateway/blob/master/db/shadower.go#L85

Functionally, though, I think this scenario should work.
