### ISSUE TITLE
Document expiry behaviour when using xattrs

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2504]
Need to put together documentation on how Sync Gateway expiry is expected to behave under convergence:
 - changes from ttl-to-purge to ttl-to-tombstone
 - server purge interval manages tombstone cleanup

**Comment by adamcfraser** [comment]
### Convergence and Sync Gateway TTL

When running with extended attributes enabled, there's a change in the way Sync Gateway's expiry (ttl) functionality behaves. Instead of the document being purged from Sync Gateway when the tombstone triggers, the document will instead be treated the same as if the document were deleted through the SDK - it will create a Sync Gateway tombstone. This provides consistency between expiry values set directly through the SDK, and expiry values set through Sync Gateway.

Previously, the main purpose of the Sync Gateway expiry setting was to provide a way to clean up obsolete documents.  When Sync Gateway is using extended attributes, that functionality is provided by Couchbase Server.  Sync Gateway tombstones are purged based on the server's Metadata Purge Interval.

When a bucket includes mobile data, the value used for the Metadata Purge Interval should be based on the maximum length of time expected between client replications.  Clients that fail to replicate within that time window may not be notified for documents that were tombstoned while they were offline.

See https://github.com/couchbase/sync_gateway/issues/2550 for additional handling for clients that fail to replicate in the Metadata Purge Interval window.

**Comment by adamcfraser** [comment]
@jamiltz The above paragraph can be included in the convergence docs.  Let me know if there's any additional context that you think needs to be provided.

**Comment by jamesnocentini** [comment]
done in https://github.com/couchbaselabs/couchbase-mobile-portal/commit/23b7d18d10ff8c95117a27ca75d87a5f0a87fd13#diff-fa77f90df39aac282cc6963f3689def4
