### ISSUE TITLE
XATTRs: View not returning results after restart

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2505]
### Sync Gateway version
1.4.2-340  

### Operating system
CentOS

### Config file
```
{
        "adminInterface": "0.0.0.0:4985", 
        "compressResponses": false, 
        "databases": {
            "db": {
                "bucket": "data-bucket", 
                "password": "password", 
                "server": "http://XXXX:8091", 
                "unsupported": {
                    "enable_extended_attributes": true
                }
            }
        }, 
        "interface": ":4984", 
        "log": [
            "*"
        ], 
        "maxCouchbaseConnections": 16, 
        "maxFileDescriptors": 90000, 
        "maxIncomingConnections": 0, 
        "slowServerCallWarningThreshold": 500
    }
```

### Log output
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/514/artifact/results/logs/test_channels_view_after_restart%5Bsync_gateway_default%5D-2017-04-27-09-34-04-sglogs.zip

### Expected behavior
After restarting Sync Gateway, view results are returned

### Actual behavior
After restarting Sync Gateway, no view results are returned

### Steps to reproduce
1.  http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/514/testReport/junit/testsuites.syncgateway.functional.tests/test_channels/test_channels_view_after_restart_sync_gateway_default_/

Link to the test source - https://github.com/couchbaselabs/mobile-testkit/blob/feature/sg-sdk-tests/testsuites/syncgateway/functional/tests/test_channels.py#L16-L85

Possibly related to #2484 except view results should be returned

**Comment by adamcfraser** [comment]
Potentially related to https://issues.couchbase.com/browse/MB-21350?focusedCommentId=201721&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-201721

**Comment by sethrosetter** [comment]
Passes with http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/535/console
