### ISSUE TITLE
Automatically Archival of documents in a channel

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#2520]
- As a user I would like to store all documents in a channel indefinitely on the server. 

- Sync Gateway should allow automatic archival of docs in channel that meet a specific criteria like older than x days, satisfy a N1QL query. 

- As a result, whenever a new device comes online, they would only those documents in the channel that have not been archived.

**Comment by Fujio-Turner** [comment]
This might be good use case for Couchbase Eventing

**Comment by ghost** [comment]
If this can be implemented then we should have the reverse of this too where automatic channel addition can be done after x number of days or after y date.

By doing this the data for apps will be available only when they need it and this will be automatic instead of writing a solution to check if the data has arrived and if yes then add the channel. Or if the date has gone then remove the channel.

**Comment by adamcfraser** [comment]
Closing - as mentioned, eventing is a reasonable way to trigger update to documents to move them out of channels.
