### ISSUE TITLE
Support attachments=[true|false] when replicating documents

### ISSUE THREAD

**Issue by krugster** [couchbase/sync_gateway#2522]
In order to reduce network bandwidth (and in some cases the data charges associated with that), it is requested to support an option for syncing|not syncing binary attachments on documents.  This would be required for both push and pull replicators.

**Comment by adamcfraser** [comment]
Standard Couchbase Lite replication doesn't retrieve document bodies (or attachments) via the _changes endpoint.  It's only using _changes to get the list of doc/revids, and then issuing a bulk_get call to retrieve documents it doesn't already have a copy of.  bulk_get already includes an attachments=true/false flag.

Given that, I don't think this is required for standard push/pull replicators.  However, if you're thinking about a custom changes worker that's setting include_docs=true, I can see the value of an attachments flag (to match the bulk_get functionality).  Is that the motivation?

**Comment by krugster** [comment]
Thanks Adam.  Yes, that sounds like the motivation.  So you're saying this sits better as a CBLite flag/feature rather than on the changes feed itself, and that certainly makes sense to me.  The requirement is still the same from the user's perspective.  Thanks!

**Comment by snej** [comment]
Mac/iOS has supported this for a while (since 1.2 I think?) — it's an option in the CBLReplication class.
We're planning to support this across all platforms in CBL 2.0, but it's not implemented yet.

**Comment by djpongh** [comment]
Not a SG issue
