### ISSUE TITLE
Customize DCP feed name

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2526]
This is a request for Couchbase Support to make it easier to differentiate.

DCP streams should be named: `eq_dcpq:SyncGateway-1.4.0-XXXXX`

It looks like cbdatasource already supports this ability, but I haven't verified for sure.

**Comment by adamcfraser** [comment]
Looks like it's just a matter of setting Options.Name when setting up the bucket data source.

**Comment by steveyen** [comment]
Another way would be to initialize the cbgt.DCPFeedPrefix global var in some init() function.  Please see https://issues.couchbase.com/browse/MB-24201 for some more info.

**Comment by adamcfraser** [comment]
Once this is in, we can (should?) revert https://github.com/couchbase/sync_gateway/pull/2527.

**Comment by adamcfraser** [comment]
Addressed w/ https://github.com/couchbase/sync_gateway/issues/2747
