### ISSUE TITLE
Sync gateway returns 201 after write attachment fails

### ISSUE THREAD

**Issue by yudhiwidyatama** [couchbase/sync_gateway#2534]
### Sync Gateway version
Couchbase Sync Gateway/1.4.0(2;9e18d3e)

### Operating system
Docker on Ubuntu 14.04.2 LTS

### Config file
```javascript
{
  "log": ["*"],
  "databases": {
    "surveydb": {
      "server": "http://couchbase-server:8091",
      "bucket": "surveydb",
      "username":"surveydb",
      "password":"<redacted>",
      "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } }
    }
  }
}
# When relevant, copy-paste your sync gateway config here.  Remove any sensitive information
as appropriate (including addresses, passwords, etc).
```

### Log output
https://gist.github.com/yudhiwidyatama/de529a9a37240600d6d3161ad49521e1

### Expected behavior
Sync gateway should recover from 'Database over capacity'. When the user retry the operation after the database recovers from over capacity condition then sync gateway should retry the operation fully and re-send the attachment. The retry in line 129-133 should re-send the attachment, and attachments for other documents being PUT in line 164-168 and line 196-200 should also be sent to couchbase server.

### Actual behavior
The attachment no longer being sent to the server even though the operation returned 201 (document created) in line 168 of the attached log. Note that the Attach line no longer exists for  operations in line 164-168 (creation of attach10) and line 196-200 (creation of attach11).
Documents being created but the attachments are not.

### Steps to reproduce
1.  Create a bucket with 100 MB memory
2. POST with body from file contents to url /surveydb/attach01/filename
3. repeat step 2 until Database Over capacity error received (9 times with file contents @10MB), with different attach name (attach02, attach03, etc) and filename
4. wait 5 minutes to give time for eviction to occur in the couchbase server
5. repeat step 2 about 3 times

**Comment by tleyden** [comment]
@yudhiwidyatama thanks for the clear bug report!  I filed a ticket in our testing repo to create a functional test case to repro it.  Let me know if you'd be interested in tackling that and I can walk you  through what you'd need to do.  Here's an [example test case](https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/functional/topology_specific_tests/multiple_sync_gateways/test_sg_replicate.py#L31-L106) 

Also, can you add a curl/httpie request that shows what the verification would look like?  I take it that you'd just be curly for the attachment `/surveydb/attach01/filename` and it would return a 404 error since the attachment never made it?

**Comment by yudhiwidyatama** [comment]
@tleyden My python is a bit rusty (almost never coded in it) but let me see what can I make of it. Right now I have no idea how to setup a python-based couchbase testing environment.. And maybe we should replace step 4 with a DELETE operation on some of existing attachments in order to free memory in couchbase server, so the automated test doesn't need to wait 5 minutes.

Anyway, you are right, I just curl for the attachment content. I have updated the description in the issue above..

**Comment by tleyden** [comment]
> Right now I have no idea how to setup a python-based couchbase testing environment..

We have some instructions in the [README](https://github.com/couchbaselabs/mobile-testkit/blob/master/README.md), but admittedly they are a bit rough.  I run the virtualbox/vagrant cluster locally.  It can also run on AWS.

**Comment by adamcfraser** [comment]
Closing based on age, and enhancements in attachment handling.  If this is still an active concern, can reopen ticket at issues.couchbase.com.
