### ISSUE TITLE
Adding sg-accelerator nodes is not increasing syncgateway write throughput

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2535]
### Sync Gateway version
1.4.1

### Operating system
Red-hat 7.2

### Expected behavior
sg-accelerator should scale with horizontal scaling of syncgateway

### Actual behavior
sg-accelerator is not scaling with scaling of syncgateway

###Setup details
2 syncgateway
3 CBS nodes
1 sg-replicator

### Steps to reproduce
1.  Add one sg-accelrator and observer the TPS
2.  Add one more sg-accelerator and observe the TPS
3.  TPS should increase at step 2

**Comment by adamcfraser** [comment]
There isn't enough information here to act on - please provide details on the nature of the testing you're doing.

**Comment by ArihantRk** [comment]
@adamcfraser set up details as below in each of 2 clusters
2*syncgateway
3*CBS nodes
1*sg-replicator

Replication is configured between both clusters. Data is being inserted at source which is being replicated to destination cluster by replicator.

No sync function is added in configuration
below is the observation of timetaken to insertion 500000 documents
1.	Without accelerator
Time Taken : 12-13 minutes

2.	With 1 accelerator
Time Taken : ~6 minutes

3.	With 2 accelerators
Time Taken : ~6 minutes

Scaling of sg-accelerator is not improving the throughput.

**Comment by adamcfraser** [comment]
The primary purpose of sg-accelerator is to support horizontal scalability of the Sync Gateway cluster, to support distribution of overall load across the cluster.

Unfortunately this doesn't help with cluster-to-cluster replication - that's still currently limited to a single node, and so doesn't benefit from scaling out the SG cluster.  There have been initial discussions about how to deliver horizontal scalability for cluster-to-cluster replication, but that feature hasn't been implemented yet.
