### ISSUE TITLE
Sync Gateway blocking on initial import

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2537]
### Sync Gateway version
Couchbase Sync Gateway/1.4.2(358;9319d64)  

### Operating system
Mac OSX

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "compressResponses": false,
    "log": ["*", "Import+"],
    "databases":{
        "db": {
            "import_docs": "continuous",
            "unsupported": {
                "enable_extended_attributes": true
            },
            "users": {
                "admin": {
                    "password": "pass",
                    "admin_channels": [
                        "*"
                    ]
                },
                "airline": {
                    "password": "pass",
                    "admin_channels": [
                        "airline"
                    ]
                },
                "route": {
                    "password": "pass",
                    "admin_channels": [
                        "route"
                    ]
                },
                "airport": {
                    "password": "pass",
                    "admin_channels": [
                        "airport"
                    ]
                },
                "landmark": {
                    "password": "pass",
                    "admin_channels": [
                        "landmark"
                    ]
                },
                "hotel": {
                    "password": "pass",
                    "admin_channels": [
                        "hotel"
                    ]
                }
            },
            "server": "http://localhost:8091",
            "bucket": "travel-sample",
            "password": "password",
            "sync": `function(doc, oldDoc){
                channel(doc, doc.type);
            }`
        }
    }
}
```

### Expected behavior
User should be able to hit sync gateway root endpoint during import

### Actual behavior
Unable to hit sync gateway root endpoint during import
```
~ » http localhost:4984

http: error: ConnectionError: HTTPConnectionPool(host='localhost', port=4984): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10c1d1b38>: Failed to establish a new connection: [Errno 61] Connection refused',)) while doing GET request to URL: http://localhost:4984/
```

### Steps to reproduce
1. Download 1.4.2(358;9319d64)
2. Download 5.0.0-2824
3. Import travel sample and create a 'travel-sample' bucket admin user
4. Start sync gateway with the provided config
5. While importing, try `http localhost:4984`

This may be a resource starvation issue. Still looking into it

**Comment by adamcfraser** [comment]
This looks like it's potentially related to the fix in #2539 - if the import processing deadlocks when the DCP feed gets started, there may not be any single ops available for sequence Incrs when the database users are going to be created.

Reopen if this persists in builds with the fix for #2539.

**Comment by sethrosetter** [comment]
Still seeing this with `Couchbase Sync Gateway/1.4.2(361;c2b4f25)`

**Comment by sethrosetter** [comment]
Go routine dump - https://gist.github.com/sethrosetter/61eec5f8fabad14a8317933e2767d017

**Comment by adamcfraser** [comment]
I think this is a similar deadlock on the GetWithXattr, which still has a workaround (pending a server fix) that can result in a nested call to Get.

Now that http://review.couchbase.org/#/c/77374/ has been merged, I think we can pull out the workaround and avoid this.

**Comment by sethrosetter** [comment]
What is the ETA of getting this in?

**Comment by adamcfraser** [comment]
The fix for the deadlock has been merged.  However, it's still the case that Sync Gateway will be unresponsive at startup when importing a large database for the first time, until the import is complete.  Filed https://github.com/couchbase/sync_gateway/issues/2546 to fix that, but don't expect it to be fixed in the first DP.

**Comment by sethrosetter** [comment]
It still blocks for a few seconds but then allows connections.

**Comment by sethrosetter** [comment]
I am reopening as it is failing one of our functional tests and the issue is only partially resolved. Sync Gateway doesn't block connections for the whole import but it still blocks for some time at the start of a large import.

**Comment by adamcfraser** [comment]
It only blocks on the large dataset if import is enabled?

**Comment by sethrosetter** [comment]
Failing regression test - https://github.com/couchbaselabs/mobile-testkit/blob/feature/sg-sdk-tests/testsuites/syncgateway/functional/tests/test_xattrs.py#L231-L312
