### ISSUE TITLE
Use enum for bucket feedtype

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2552]
See https://github.com/couchbase/sync_gateway/pull/2543/files#r115866967:

> Seems like FeedType shouldn't be a string in BucketSpec - we should do this kind of strings.ToLower processing once when we parse the config, and then store as an enum/custom type on the BucketSpec. Otherwise it feels like we're going to forget this again in future.

**Comment by adamcfraser** [comment]
Closing based on age, priority.
