### ISSUE TITLE
Unable to resurrect tombstones when using xattr

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2556]
Attempting to mutate the doc body and xattr for a document that's been tombstoned (doesn't have a document body) is returning a key not found error, instead of updating the body+xattr, even though the AccessDeleted flag is set for the operation.

https://github.com/couchbase/sync_gateway/blob/master/base/bucket_gocb.go#L866

**Comment by tleyden** [comment]
Is there a failing test this is linked to?

**Comment by adamcfraser** [comment]
Pending test: https://github.com/couchbaselabs/mobile-testkit/issues/1131

**Comment by sethrosetter** [comment]
Is this a potential server bug?

**Comment by sethrosetter** [comment]
Is this a duplicate of this - https://github.com/couchbase/sync_gateway/issues/2641?

If so, the doc resurrection tests are passing and I think this is no longer an issue.
