### ISSUE TITLE
XATTRs: Sync Gateway missing revs in import under high load

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2562]
### Sync Gateway version
1.4.2-366

### Server Version
5.0.0-2837

### Operating system
macOS

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "compressResponses": false,
    "log": ["*", "Import+", "DCP"],
    "databases":{
        "db": {
            "import_docs": "continuous",
            "unsupported": {
                "enable_extended_attributes": true
            },
            "users": {
                "admin": {
                    "password": "pass",
                    "admin_channels": [
                        "*"
                    ]
                },
                "airline": {
                    "password": "pass",
                    "admin_channels": [
                        "airline"
                    ]
                },
                "route": {
                    "password": "pass",
                    "admin_channels": [
                        "route"
                    ]
                },
                "airport": {
                    "password": "pass",
                    "admin_channels": [
                        "airport"
                    ]
                },
                "landmark": {
                    "password": "pass",
                    "admin_channels": [
                        "landmark"
                    ]
                },
                "hotel": {
                    "password": "pass",
                    "admin_channels": [
                        "hotel"
                    ]
                }
            },
            "server": "http://localhost:8091",
            "bucket": "travel-sample",
            "password": "password",
            "sync": `function(doc, oldDoc){
                channel([doc.type]);
            }`
        }
    }
}

```

### Log output
Provide a link to a GitHub Gist containing relevant Sync Gateway log output when
the error occured. Do NOT paste the log output in the issue, just paste the
link to the Gist.

### Expected behavior
All documents end up on revision 2.

### Actual behavior
A small percentage of the docs aren't imported after the SDK update, and remain on revision 1.

### Steps to reproduce
1.  Import travel-sample bucket
2.  Verify import successful (all_docs)
3.  Bulk update all docs in travel-sample bucket via SDK
4.  Verify all updates appear (all_docs)

**Comment by sethrosetter** [comment]
For step 3, use https://github.com/couchbaselabs/mobile-testkit/blob/feature/sg-sdk-tests/testsuites/simulations/Travel.NET/validate_and_updater.py but make sure to comment out the following line, https://github.com/couchbaselabs/mobile-testkit/blob/feature/sg-sdk-tests/testsuites/simulations/Travel.NET/validate_and_updater.py#L66

Run with:
`python testsuites/simulations/Travel.NET/validate_and_updater.py`

**Comment by adamcfraser** [comment]
Ran locally against 5.0.0-2836 (mac os) and wasn't able to repro - all documents were revision 2 post-validate_and_updater.  Possibly the DB wasn't under enough load to generate the transient errors that we think may be responsible.

Going to retry w/ 2837 in case anything changed on the server side.

**Comment by adamcfraser** [comment]
Was able to repro by running the script multiple times.  Found root cause - incorrectly returning err=nil on a transient server error
