### ISSUE TITLE
Add a lower bound to revs_limit

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#2567]
Currently we allow setting revs_limit incredibly low, but this can very quickly cause huge issues with the revtree - if more changes are made locally in between syncs of a remote client for example, we can't join the two parts of the rev tree together and end up with false conflicts. 

Ideally, I'd like to suggest setting a reasonable lower bound on this, but a big warning in the logs if it's set too low would be good too. Maybe an warning on <100 and a hard limit at 20-30ish?

**Comment by adamcfraser** [comment]
I think this is a reasonable suggestion, and should be straightforward to implement for 1.5.0.  Some nuances of this may change post-1.5, but this makes sense as an interim enhancement.
