### ISSUE TITLE
Gracefully handle a revision already existing in the rev tree

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#2568]
Currently, when inserting a new revision for a document we do some good sanity checking on it, but there's an edge case we don't cover that can be hit in a couple of ways:

* The rev tree is disconnected in some way
* An actual, real hash collision

I've previously typed this up, so shamelessly copying that in here:

>It looks like we're trying to put a revision into the history that's already there.

>This comes from here: https://github.com/couchbase/sync_gateway/blob/1.3.1/db/crud.go#L416 , and more specifically this line: https://github.com/couchbase/sync_gateway/blob/1.3.1/db/crud.go#L459

>Here's the function with my comments inline:

```
// Updates or creates a document.
// The new body's "_rev" property must match the current revision's, if any.
func (db *Database) Put(docid string, body Body) (string, error) {
    // Get the revision ID to match, and the new generation number:
    //JFLATH: So, this is the revision passed in as the one to change. E.g. DELETE /db/foo?rev=2-abc. 2-abc is the current one, and the one in the request - we're not dealing with the new revision id yet.
    matchRev, _ := body["_rev"].(string)
    generation, _ := parseRevID(matchRev)
    if generation < 0 {
        return "", base.HTTPErrorf(http.StatusBadRequest, "Invalid revision ID")
    }
    generation++
    deleted, _ := body["_deleted"].(bool)

    :    :    :

    return db.updateDoc(docid, false, expiry, func(doc *document) (Body, AttachmentData, error) {
        // (Be careful: this block can be invoked multiple times if there are races!)
        // First, make sure matchRev matches an existing leaf revision:
        if matchRev == "" {
            //JFLATH: We haven't passed in a revision with the document.
            //JFLATH: If we didn't pass a revision, currentRev should be empty - i.e. there shouldn't be an existing winning rev already in the db unless it's a tombstone
            matchRev = doc.CurrentRev
            if matchRev != "" {
                // PUT with no parent rev given, but there is an existing current revision.
                // This is OK as long as the current one is deleted.
                if !doc.History[matchRev].Deleted {
                    return nil, nil, base.HTTPErrorf(http.StatusConflict, "Document exists")
                }
                generation, _ = parseRevID(matchRev)
                generation++
            }
        } else if !doc.History.isLeaf(matchRev) {
            //JFLATH: We did pass a rev, but it's not a leaf. We're not allowed to directly create a child of this rev, as that would be a conflict
            return nil, nil, base.HTTPErrorf(http.StatusConflict, "Document revision conflict")
        }
        //JFLATH: For this particular scenario, we know we're passing in a rev, so the `if matchRev ==""` doesn't trigger. We don't get the conflict error, so by this line we can say that the revision we've passed in *IS* a leaf node

    :    :    :

        // Make up a new _rev, and add it to the history:
        newRev := createRevID(generation, matchRev, body)
        //JFLATH: So now we've created the new rev id. If we passed 2-abc, newRev = 3-bcd, we should never have seen the id 3-bcd before.
        body["_rev"] = newRev
        //JFLATH: We try to add this to the tree, and things go wrong.
        doc.History.addRevision(RevInfo{ID: newRev, Parent: matchRev, Deleted: deleted})
        return body, newAttachments, nil
    })
}
```

>At line [445](https://github.com/couchbase/sync_gateway/blob/1.3.1/db/crud.go#L445) we know that the parent revision we passed in is a leaf node - it has no children. By the time we call `addRevision()` at line [459](https://github.com/couchbase/sync_gateway/blob/1.3.1/db/crud.go#L459), we find the child revision we've just created is already in the revision tree. There is the minuscule possibility of a genuine hash collision I suppose - we only check the rev tree based on ID, not parent, so if `5-abc` and `5-xyz` both happen to independently to have children who hash to `6-wat`, technically we wouldn't allow both of those to go into the revtree, even though they're distinct. However, we hash [based on the parent too](https://github.com/couchbase/sync_gateway/blob/1.3.1/db/revision.go#L139), so I don't believe a hash collision is to blame here.

```
// Records a revision in a RevTree.
func (tree RevTree) addRevision(info RevInfo) {
    //JFLATH: Note we're only checking by revID, not parent
    revid := info.ID
    :    :    :
    if tree.contains(revid) {
        panic(fmt.Sprintf("already contains rev %q", revid))
    :    :    :
```

Credit to @adamcfraser for actually clocking what's happening here! Essentially, if you delete revision `5-abcd`, creating `6-dead`, but somehow (perhaps through low `revs_limit`) insert `6-dead` as a conflicting orphan you hit the edge case: 

* You go to delete `5-abcd` again (as part of your conflict resolution perhaps).
* We check, and confirm `5-abcd` is indeed a leaf node, because `6-dead` isn't associated as a child.
* We go to insert `6-dead` as a child of `5-abcd`, but panic because it's already *somewhere* in the revtree.

---

Ideally, I'd like to think we could do something clever here - repair the link between parent and child.

Short term though, I think we should consider not panicking on this, whether that means demoting the panic to a logged warning, or just checking for the edge case in the `Put()`...

**Comment by ArihantRk** [comment]
@JFlath is the below issue because of this.
https://github.com/couchbase/sync_gateway/issues/2261
