### ISSUE TITLE
XAttrs: 500 errors returned for purged docs

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2570]
### Sync Gateway version
1.4.2-368 

### Operating system
CentOS 7

### Config file
```
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "import_docs": "continuous",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                },
                "users": {
                    "GUEST": {
                        "admin_channels": [
                            "*"
                        ],
                        "disabled": true
                    }
                }
            }
        },
        "interface": ":4984",
        "log": [
            "CRUD+",
            "Cache+",
            "HTTP+",
            "Changes+"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
    }
```

### Log output
https://gist.github.com/sethrosetter/e0590bfd5b61d001295fb80b193b6db6

bulk_get 500 error:
```
{u'status': 500, u'reason': u'Internal error: an unknown error occurred (211)', u'id': u'sg_0', u'error': u'500'}
```

### Steps to reproduce
1. checkout `feature/sg-sdk-tests` in mobile-testkit and run `pytest -s --pdb --skip-provisioning --xattrs --mode=cc --server-version=5.0.0-2873 --sync-gateway-version=1.4.2-368 -k "test_purge" testsuites/syncgateway/functional/tests/test_xattrs.py`

**Comment by adamcfraser** [comment]
Regression due to changes in the recent Spock builds that haven't been uptaken by SDK or Sync Gateway yet.  Server has added a new SUBDOC_MULTI_PATH_FAILURE_DELETED error code, and we're hitting this when attempting to retrieve purged docs.
