### ISSUE TITLE
Use N1QL queries to assign documents to channels

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#2572]
From CMOB-2 by Davis Chapman.

We should have mechanism where we should be able to say write N1QL queries and the output of which should be given to channels.
   Basically an approach to join output of multiple queries for a channel to provide data to device client subscribed to that channel.

**Comment by adamcfraser** [comment]
Channels are intentionally required to be based on fields on the document itself, and not based on any external state.

However, it sounds like the desired functionality could be achieved by using the results of the N1QL query to update a property on the document, and reference that property in the sync function to assign channels.
