### ISSUE TITLE
View backfill for deletes not working

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2573]
### Sync Gateway version
1.4.2-368  

### Operating system
CentOS 7

Should be fixed with https://issues.couchbase.com/browse/MB-23888

Regression test that should be green when fixed - http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/582/testReport/junit/testsuites.syncgateway.functional.tests/test_views/test_view_backfill_for_deletes_sync_gateway_default_functional_tests_False_/

**Comment by sethrosetter** [comment]
Test is passing with 5.0.0-2958

**Comment by sethrosetter** [comment]
Reopening as this is failing in distributed index.

**Comment by adamcfraser** [comment]
Distributed index doesn't use views for backfill, so this issue might need a new title and details on what's failing.

**Comment by sethrosetter** [comment]
Ok. Will open a new ticket.
