### ISSUE TITLE
Empty change feed results after unassigning documents from channel

### ISSUE THREAD

**Issue by AndrejRW** [couchbase/sync_gateway#2577]
### Sync Gateway version
Couchbase Sync Gateway/1.3.1(16;f18e833)
Couchbase Sync Gateway/1.4.1(3;ddffd85)  

### Operating system
Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-110-generic x86_64)

### Config file
```
{
  "log": ["*"],
  "logFilePath": "/home/sync_gateway/logs/sync-gateway.log",
  "CouchbaseKeepaliveInterval": 300,
  "slowServerCallWarningThreshold": 1000,
  "maxCouchbaseConnections": 100,
  "maxFileDescriptors": 250000,
  "compressResponses": true,
  "maxHeartbeat": 10,
  "serverReadTimeout": 1300,
  "serverWriteTimeout": 1300,
  "adminInterface": "127.0.0.1:4986",
  "interface": "0.0.0.0:4984",
  "databases": {
    "ag": {
      "server": "http://localhost:8091",
      "bucket": "ag",
      "rev_cache_size": 1000,
      "cache": {
        "max_wait_skipped": 300000
      },
      "sync":
        `
        function(doc, oldDoc) {
            channel("type_" + doc.$type);
            if (doc.active && doc.deviceSerialNumber) {
              // access everyone
              access("role:user", "launcher_deviceCommands_" + doc.deviceSerialNumber);
              // add document to appropriate channel
              channel("launcher_deviceCommands_" + doc.deviceSerialNumber);
            }
        }
        `
    }
}
```

### Expected behavior
Document which is removed from channel should still present in change feed with flag removed=true

### Actual behavior
Change feed is empty

### Steps to reproduce
1.  Verify that change feed is empty:
Request:
```
curl -v -H "Content-Type: application/json" --cookie "SyncGatewaySession=7abc6b44e6402f943f0e69b2dbd7a233e99933c5" "http://localhost:4984/ag/_changes?filter=sync_gateway/bychannel&channels=launcher_deviceCommands_273181244642627"
```
Response:
```
{"results":[
{"seq":5205904,"id":"_user/mainUser111697","changes":[]}
],"last_seq":"5205904"}
```
2.  Insert two documents:
```
{
  "_id": "fed7f05cce24217f8da1893a45078bb8",
  "active": true,
  "deviceSerialNumber": "273181244642627"
}
{
  "_id": "2cd9bcc95f688fb3d080083a700d1972",
  "active": true,
  "deviceSerialNumber": "273181244642627"
}
```
3.  Verify change feed:
```
{"results":[
{"seq":5205904,"id":"_user/mainUser111697","changes":[]},
{"seq":8390396,"id":"fed7f05cce24217f8da1893a45078bb8","changes":[{"rev":"1-64d853d4761c12600d979d00d9ed6c52"}]},
{"seq":8390402,"id":"2cd9bcc95f688fb3d080083a700d1972","changes":[{"rev":"1-bf4ed6f4f6f9e0f9bae806343669bf22"}]}
],"last_seq":"8390402"}
```
Both documents present which is correct
4. Update document with id 2cd9bcc95f688fb3d080083a700d1972 to be the following:
```
{
  "_id": "2cd9bcc95f688fb3d080083a700d1972",
  "active": false,
  "deviceSerialNumber": "273181244642627"
}
```
5. Verify change feed:
```
{"results":[
{"seq":5205904,"id":"_user/mainUser111697","changes":[]},
{"seq":8390396,"id":"fed7f05cce24217f8da1893a45078bb8","changes":[{"rev":"1-64d853d4761c12600d979d00d9ed6c52"}]},
{"seq":8390405,"id":"2cd9bcc95f688fb3d080083a700d1972","removed":["launcher_deviceCommands_273181244642627"
],"changes":[{"rev":"2-3aef321c8e0a5755fb153c58419f4a9f"}]}
],"last_seq":"8390405"}
```
Both documents present, second one marked as removed from the channel, which is correct.
6. Update document with id fed7f05cce24217f8da1893a45078bb8 to be the following:
```
{
  "_id": "fed7f05cce24217f8da1893a45078bb8",
  "active": false,
  "deviceSerialNumber": "273181244642627"
}
```
7. Verify change feed:
```
{"results":[
{"seq":5205904,"id":"_user/mainUser111697","changes":[]}
],"last_seq":"5205904"}
```
Both documents doesn't exist which is wrong. Both documents should present and both document should be marked as removed from change feed. As results - couchbase lite doesn't receive appropriate changes via replication.

**Comment by adamcfraser** [comment]
Once you make both documents inactive, the user is no longer being granted access to the channel, and so isn't getting removal notifications for that channel.

**Comment by AndrejRW** [comment]
Yes, looks like my fault. And if user doesn't have access to channel anymore - it's not possible to remove documents via replication like for documents excluded from channel?

**Comment by tleyden** [comment]
@AndrejRW that sounds like it might be one of the scenarios [described here](https://github.com/couchbase/sync_gateway/issues/264#issuecomment-297478296) -- can you take a look and see either scenario matches your case?
