### ISSUE TITLE
go-couchbase doesn't fully support SSL-only communication with Couchbase Server

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2584]
### Sync Gateway Version
1.4.1-3

### Steps
1. I blocked the 8091 and 8092 ports on the server node.
```
iptables -A INPUT -p tcp --destination-port 8091 -j DROP
iptables -A INPUT -p tcp --destination-port 8092 -j DROP
```
2. Ran the testsuites/syncgateway/functional/tests/test_changes_backfill.py

### Actual
All tests fail right away as SG wont start

### SG Logs
```
2017-03-31T01:00:41.338Z Opening db /db as bucket "data-bucket", pool "default", server <https://192.168.33.20:18091>
2017-03-31T01:00:41.338Z Opening Couchbase database data-bucket on <https://192.168.33.20:18091> as user "data-bucket"
_time=2017-03-31T01:00:41.353+00:00 _level=INFO _msg= Trying with selected node 0 
_time=2017-03-31T01:00:41.353+00:00 _level=INFO _msg= Trying with http://192.168.33.20:8091/pools/default/bucketsStreaming/data-bucket 
2017-03-31T01:01:11.354Z WARNING: Bucket Updater for bucket data-bucket returned error: Get http://192.168.33.20:8091/pools/default/bucketsStreaming/data-bucket: dial tcp 192.168.33.20:8091: i/o timeout -- base.GetCouchbaseBucket.func1() at bucket.go:404
2017-03-31T01:01:11.354Z WARNING: Lost TAP feed for bucket data-bucket, with error: Get http://192.168.33.20:8091/pools/default/bucketsStreaming/data-bucket: dial tcp 192.168.33.20:8091: i/o timeout -- rest.(*ServerContext)._getOrAddDatabaseFromConfig.func1() at server_context.go:350
_time=2017-03-31T01:01:11.354+00:00 _level=ERROR _msg= Bucket Updater exited with err Get http://192.168.33.20:8091/pools/default/bucketsStreaming/data-bucket: dial tcp 192.168.33.20:8091: i/o timeout
``` 

http://192.168.33.21:4984/ does not respond
 
All tests pass if I flush the firewall rules. 

Adam's analysis:

What this means is that go-couchbase doesn't fully support SSL-only communication with Couchbase Server.  The SSL server endpoint being provided by Sync Gateway looks like it's being used for KV operations, but not for bucket streaming (used to monitor changes in the cluster topology), and I suspect not for views (based on the previous logs).  Here's where go-couchbase is still hardcoding the non-SSL endpoint for this case:
  https://github.com/couchbase/go-couchbase/blob/master/streaming.go#L106

We should review what this means for SSL support in 1.4.1 tomorrow, but I think the options probably break down like this:
 1.  I suspect that SSL is fully supported in the official go SDK (gocb).  We're halfway migrated to gocb in our 2.0 branch (moving over the view functionality is still pending), but switching to gocb is a significant change that can't be rushed out without a full release testing cycle.  
 2.  Getting an enhancement to go-couchbase to support SSL.  It's hard to estimate how much work this is – some of the hardcoded http references are obvious, but there are other usages (like the view endpoints) that aren't as clear cut.  We would probably want a fairly significant test cycle here as well, to make sure everything is covered.

My preference would be to go the gocb route, and wait for 1.4.2 (the 'old' 1.4.1) for full SSL support between SG and CBS.

**Comment by adamcfraser** [comment]
We'd previously been tracking this on https://github.com/couchbase/sync_gateway/issues/1552 for the general case, and https://github.com/couchbase/sync_gateway/issues/2496 specifically for gocb.

Unless there's something distinct about this ticket, can we track using those?

**Comment by raghusarangapani** [comment]
I am fine with that, tagging Seth @sethrosetter
