### ISSUE TITLE
syncgateway hung during couchbase re-balance

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2588]
### Sync Gateway version
1.4.1
### Couchbase version
4.6.1
### Operating system
RedHat 7.2

###Setup details
3* CBS nodes
2* syncgateway
2* sg-replicator

couchbase bucket replica is set 1
In three node cluster, one of couchbase node got hard fail-over due to cbs service stop and node got failover after autofailover time(60 seconds). we did rebalance after bringing up failover node.
we are seeing syncgateway hung state during rebalance.
All request to syncgateway are timing out.

### Expected behavior
syncgateway should be able to respond with 2 nodes active as replica will be enabled after failover

### Actual behavior
syncgateway going into hung state . all requests to syncgateway are getting timeout

### Steps to reproduce
1.  Setup as mentioned with 200 GB data and autofailover 60 seconds
2.  Do CBS service stop and rebalance after adding failover node 
3. Restart syncgateway restart
3.  verify syncgateway response

**Comment by tleyden** [comment]
Might be related to https://github.com/couchbase/sync_gateway/issues/2576

**Comment by adamcfraser** [comment]
Based on review, this looks to be the same issue as https://github.com/couchbase/sync_gateway/issues/2576.  Closing based on the fix to support multiple server URLs in the SG config.
