### ISSUE TITLE
XATTRs: Document expiry not working as expected

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2591]
### Sync Gateway version
1.5.0-377

### Operating system
CentOS 7

### Config file
```
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "import_docs": "continuous",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                },
                "username": "data-bucket",
                "users": {
                    "GUEST": {
                        "admin_channels": [
                            "*"
                        ],
                        "disabled": true
                    }
                }
            }
        },
        "interface": ":4984",
        "log": [
            "CRUD+",
            "Cache+",
            "HTTP+",
            "Changes+"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
}
```

### Log output
https://gist.github.com/sethrosetter/d197b6b28d4ce2836490d5c2b438e2bb

### Expected behavior
After ttl expiry, the document should be soft deleted an reimported. 

### Actual behavior
I'm not seeing any import behavoir, and the doc is not soft delete

### Steps to reproduce
1.  `pytest -s --xattrs --mode=cc --server-version=5.0.0-2873 --sync-gateway-version=1.5.0-377 -k "test_numeric_expiry_as_ttl" testsuites/syncgateway/functional/tests`

**Comment by adamcfraser** [comment]
Looks like the expiry property isn't being set on the server document when that document has xattrs - need to investigate to determine whether this is a SG or CBS issue.

May be a case of WriteWithXattr not setting expiry properly, or the SubdocMutate not setting it as expected.

**Comment by adamcfraser** [comment]
I think this is a server bug - I see the expiry value being set in the subdoc mutate that creates the document w/ xattrs, and the same operation works when the document is updated.

**Comment by adamcfraser** [comment]
Filed https://issues.couchbase.com/browse/MB-24542

**Comment by adamcfraser** [comment]
Retested expiry via unit tests and it looks like it's working as expected now that  https://issues.couchbase.com/browse/MB-24542 has been delivered.  

Assigning back to @sethrosetter for update based on any remaining functional test issues.
