### ISSUE TITLE
sgcollect_info: libc: dynamic linker errors

### ISSUE THREAD

**Issue by malarky** [couchbase/sync_gateway#2598]
`sgcollect_info` appears to be linked against libc 2.14 (or later).

As far as I can tell all releases of RHEL/CentOS 6 ship with libc 2.12 or earlier, which results in:

    /opt/couchbase-sync-gateway/tools/sgcollect_info: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIdUHmdr/libz.so.1)

From https://github.com/pyinstaller/pyinstaller/wiki/FAQ#gnulinux

> Under Linux, I get runtime dynamic linker errors, related to libc. What should I do?
The executable that PyInstaller builds is not fully static, in that it still depends on the system libc. Under Linux, the ABI of GLIBC is backward compatible, but not forward compatible. So if you link against a newer GLIBC, you can't run the resulting executable on an older system. The supplied binary bootloader should work with older GLIBC. However, the libpython.so and other dynamic libraries still depends on the newer GLIBC. The solution is to compile the Python interpreter with its modules (and also probably bootloader) on the oldest system you have around, so that it gets linked with the oldest version of GLIBC.

**Comment by tleyden** [comment]
@malarky thank you for digging into that.

**Comment by tleyden** [comment]
Here's a proposed short-term fix:

- Bundle the original sgcollectinfo python script in addition to the compiled version 
- If the compiled version doesn't work, point people to the sgcollectinfo python script with instructions on how to run it, including any dependencies they might need to install.

**Comment by malarky** [comment]
Can't you just build it all with an older libc (I'm guessing on an older OS)?

**Comment by tleyden** [comment]
Yeah it would work in theory, but it seems like it would be an ever-increasing number of libc's that would need to be compiled against.

**Comment by tleyden** [comment]
I just tested the following steps on a centos6 box:

1. `cd /opt/couchbase-sync-gateway/tools`
1. `rm sgcollect_info`
1. `wget https://github.com/couchbase/sync_gateway/archive/master.zip`
1. `unzip master.zip`
1. `mv sync_gateway-master/tools/* .`
1.  `./sgcollect_info -p /tmp/path_to_output.zip`

But ran into this error:

```
[root@ip-172-31-54-236 tools]# ./sgcollect_info -p
  File "./sgcollect_info", line 193
    return {k.lower():v for k,v in original_dict.items()}
                          ^
SyntaxError: invalid syntax
```

due to apparently using some syntax that's only available in python 2.7 (centos7 default), but not python 2.6 (centos6 default)

**Comment by tleyden** [comment]
After the change in https://github.com/couchbase/sync_gateway/commit/d2c9607069c9d37818b478d135519d1d93e4d3b2 which makes a few very minor updates to sgcollect_info to make it compatible w/ python 2.6, the following works on centos6:

1. `cd /opt/couchbase-sync-gateway/tools`
1. `rm sgcollect_info`
1. `wget https://github.com/couchbase/sync_gateway/archive/feature/issue_2598_sgcollect_info.zip`
1. `unzip issue_2598_sgcollect_info.zip`
1. `mv sync_gateway-feature-issue_2598_sgcollect_info/tools/* .`
1.  `./sgcollect_info -p /tmp/path_to_output.zip`

**Comment by tleyden** [comment]
Btw, these steps can get wrapped up into a script if that makes it easier to ship to people.

**Comment by adamcfraser** [comment]
Reopening to investigate whether we can build w/ the older GLIBC to avoid the manual steps on centos6.

**Comment by ceejatec** [comment]
If the script is python 2.6 compatible, you'd really be best off building on a centos6 box. Even if it's not python 2.6 compatible, you'd be best off installing python 2.7 on a centos6 box and building there. glibc is jealously monogamous; it's really hard to safely have two on a system.
