### ISSUE TITLE
Feature Request - Delta Compression in SG logs

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#2603]
It be great to know when data was sent via delta compression vs non-delta Compression in the SG logs.

That way I can figure out over time  the delta compression vs non-delta Compression ratio 
EX.50/50 or 70/30 

from there I can tune to store more or less old docs/revs

**Comment by adamcfraser** [comment]
I think this sort of diagnostic would make more sense as an expvar than a log entry.

**Comment by adamcfraser** [comment]
Tracking with #3719.
