### ISSUE TITLE
Intermittently Sync Gateway stops with panic

### ISSUE THREAD

**Issue by jaekwonpark** [couchbase/sync_gateway#2609]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
Version information is written on startup to the Sync Gateway log, or can 
be obtained by accessing the root endpoint (`/`) on the Sync Gateway Admin REST API.   

1.4.2-366

### Operating system
The operating system you're running Sync Gateway on.

CentOS7

### Config file
```javascript
# When relevant, copy-paste your sync gateway config here.  Remove any sensitive information
as appropriate (including addresses, passwords, etc).
```
{
  "log": ["*", "Import+"],
  "databases": {
    "db": {
      "users": {
          "testuser": {
            "admin_channels": ["*****"],
            "password": "******"
          }
        },
      "server": "http://node0:8091",
      "bucket": "default",
      "password": "*******",
      "import_docs": "continuous",
      "unsupported": {
         "enable_extended_attributes":true
      }
    }
  }
}

### Log output
Provide a link to a GitHub Gist containing relevant Sync Gateway log output when
the error occured. Do NOT paste the log output in the issue, just paste the
link to the Gist.

0panic: runtime error: slice bounds out of range

goroutine 9467 [running]:
panic(0xade260, 0xc42001e0b0)
8    /usr/local/go/1.7.4/go/src/runtime/panic.go:500 +0x1a1
�github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).handleRecv(0xc4201c2500, 0xc421524e40, 0xc423b26480, 0xc42129bf80, 0x0, 0x0)
�    /home/couchbase/jenkins/workspace/sgw-unix-build/1.4.2/enterprise/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1346 +0xbb6
�github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).worker.func5(0xc421524f00, 0xc4201c2500, 0xc4242e25f0, 0x10, 0xc421f55b40, 0x1d, 0xc423bef1a0, 0xc4242a6030, 0xc423b26480, 0xc421524e40, ...)
�    /home/couchbase/jenkins/workspace/sgw-unix-build/1.4.2/enterprise/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1162 +0xf11
Ucreated by github.com/couchbase/go-couchbase/cbdatasource.(*bucketDataSource).worker
�    /home/couchbase/jenkins/workspace/sgw-unix-build/1.4.2/enterprise/godeps/src/github.com/couchbase/go-couchbase/cbdatasource/cbdatasource.go:1184 +0x563

### Expected behavior
What should have happened?

No panic

### Actual behavior
What actually happened?

Stopped with panic

### Steps to reproduce
1. prepare 4 node cluster 
2.  connect sync gateway
3.  run SDK workload against the cluster

Intermittently sync gateway stops with panic.
I know there were MB-24254 but it looks like the bug was for couchbase server and this is for sync gateway specifically 1.4.2-366

**Comment by tleyden** [comment]
@jaekwonpark the latest released version on the [downloads](https://www.couchbase.com/downloads#couchbase-mobile) page is 1.4.1.  Can you post the exact URL where you are grabbing this binary?  Or if building it yourself, which commit?

I'm going to close this proactively since it doesn't seem to be against a released version and this bug has been fixed on the master branch, but feel free to keep the conversation going and this can be re-opened if needed.

**Comment by adamcfraser** [comment]
Some additional context here:
https://github.com/couchbase/sync_gateway/issues/2561#issuecomment-303220417

Should be addressed in the DP and on master.
