### ISSUE TITLE
SG won't let CBL 2 pull attachments

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#2611]
LiteCore and CBL get an error '403 Attachment's doc not being synced' when attempting to pull attachments from SG. This is blocking us from getting the ToDo app fully functional on CBL 2.0.

I believe this happens because CBL 2 stores attachments in different places than SG expects — instead of just in `_attachments`, they can be anywhere in the doc, in any nested object with the property `"_cbltype": "blob"`.

When SG's BLIP handler receives a request for an attachment, it checks whether the doc currently being pulled contains an attachment with that digest. (This is a security requirement to keep a client from being able to pull an attachment that it doesn't have access to but whose digest it knows somehow.)

SG's code that looks for the attachment digests in a revision needs to be updated to find ones put there by CBL 2.

**Comment by snej** [comment]
Pushing attachments doesn't work either; we just hadn't noticed because it doesn't result in an error. When CBL sends a doc that has, SG is supposed to send back a `getAttachment` request for each attachment. CBL sends the attachment body in the reply. (This is the reverse of what happens during pull; the protocol is symmetric.) But since SG doesn't recognize that the revision body contains attachments, this doesn't happen. So the doc gets uploaded to SG but not the attachments.

Not sure if you want to track this as a separate issue or not, since it stems from the same problem.

**Comment by snej** [comment]
FYI, @pasin, @waynecarter and I decided to handle backward compatibility by synthesizing a legacy `_attachments` property when pushing a doc to SG, as documented [here](https://github.com/couchbase/couchbase-lite-core/wiki/Legacy-Attachment-Handling). So we won't require SG to change.

In the long run it would probably be beneficial for SG to support the new schema for blobs. If nothing else it will save work for CBL in replication if it doesn't need to transform the document. But it's not necessary for 2.0.

**Comment by tleyden** [comment]
@snej this looks like an obsolete issue -- can it be closed?

**Comment by snej** [comment]
Closing. I'll file a new issue for new-style blob support.

**Comment by snej** [comment]
Filed #3377.
