### ISSUE TITLE
PouchDB - Unable to start sync gateway

### ISSUE THREAD

**Issue by naveen-gupta** [couchbase/sync_gateway#2617]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
1.3.1-16

### Operating system
Ubuntu LTS 16.04

### Config file
{
    "log":["*"],
    "databases": {
        "buildercycle": {
            "server":"http://localhost:8091",
            "bucket": "default",
            "users": {
                "GUEST": {
                    "disabled": false,
                    "admin_channels": ["*"]
                }
            },
            "sync":`function(doc, oldDoc) {
                  if (doc.type == "sports"){
                    channel(doc.type);
                    access(doc.owner,doc.type);

                  } else  {
                    channel(doc.type);
                   access(doc.owner,doc.type);
                  } 
            }`
            
        }
    },
    "CORS": {
        "Origin": ["http://localhost:8000","http://localhost:8083", "http://localhost:4985"],
        "LoginOrigin": ["http://localhost:8000","http://localhost:8083","http://localhost:4985"],
        "Headers": ["Content-Type"],
        "MaxAge": 17280000
    }
}

### Log output
XMLHttpRequest cannot load http://localhost:4984/test/. Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

### Expected behavior
Should sync data from of provided user from couchbase server using sync gateway. 

### Actual behavior
It is giving CORS error.

**Comment by adamcfraser** [comment]
This should work, as far as I know.  Have you reviewed the blog information here?  https://blog.couchbase.com/first-steps-with-pouchdb-sync-gateway-todomvc-todolite/

If you've reviewed and it's still not working, can you share some more specifics about the error you're seeing?

**Comment by naveen-gupta** [comment]
Had created the same way as described in blog.
But when i am trying to sync my pouchdb, then local document created is not found and it is throwing 404 error.

**Comment by adamcfraser** [comment]
Closing based on age.
