### ISSUE TITLE
Split Sync Gateway views into separate design documents

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2628]
To optimize reindexing of Sync Gateway views (including after failover), split the views in the Sync Gateway design doc into separate design documents.

One design doc each for:
 - access
 - access_vbseq
 - channels
 - role_access
 - role_access_vbseq

The 'principals' view isn't used during core processing, and should be moved to the housekeeping design doc.

**Comment by JFlath** [comment]
Sorry, should have jumped in and commented on this sooner - has consideration been made about the impact this will have to Couchbase Server and sizing requirements?

This also doesn't really address the issue of how to upgrade one of these views - changing one will no longer affect the others, but *will* cause an outage for that one. On the other hand, it *does* allow adding more, provided that we never need to change the old ones.

**Comment by adamcfraser** [comment]
@jflath This isn't intended to address upgrade of views - it's just around optimization of reindexing when it happens.

The change is based on a recommendation from the view engine team - I don't have any context on how this will impact sizing requirements.  If you've got background on that topic, pass it along.

**Comment by JFlath** [comment]
Hmm, I can see that the rational there, it would certainly be faster to reindex, but there's the cost/benefit to consider.

The very rough guide would be +1 CPU core per ddoc (within a limit, caveats apply, etc.). For users/customers that have explicit sizings, there could very well be knock on effects from this change. It *could* be fine, but I wanted to make sure we considered this.

**Comment by adamcfraser** [comment]
As a compromise, I'll review whether we can coalesce the vbseq-based views with their corresponding non-vbseq views, as well as moving the principals view into housekeeping.

That will result in a net total of 4 design docs, which I think should be reasonable while optimizing reindexing.

**Comment by adamcfraser** [comment]
Filed https://github.com/couchbase/sync_gateway/issues/2679 for the followup work.
