### ISSUE TITLE
Store/Check Sync Version before installing views

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2631]
## Problem 

- sg 1.4 and sg 1.3 targeting the same bucket, and restarting both, causes unwanted view re-indexing.

## Proposal

* Add a new document to the bucket which stores the Sync Gateway version
* If the Sync Gateway version in the bucket is newer than the current Sync Gateway version, don't install/update the views and emit a warning or refuse to startup

## Tasks

- [ ] Flesh out proposal

**Comment by JFlath** [comment]
My concern here is what happens if I accidentally connect to the cluster with (say) 1.5 when I run 1.3 in production? Have I just poisoned the cluster to not allow connecting 1.3s to start?

**Comment by adamcfraser** [comment]
A benefit of this versioning would be to avoid duplicate attempts to write the same design docs - we might put that handling in place first (without blocking downgrade to address the concerns raised by @JFlath).
