### ISSUE TITLE
Better error reporting needed when views are not ready

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2639]
Filing this issue on behalf of @suravarjjala 

### Sync Gateway version
1.5.0

### Operating system
Windows

### Steps to reproduce
- Install and configure a couchbase server
- Add a lot of docs to the bucket, in this case there were 80 million docs
- Try to add a doc to SG

### Actual behavior
» curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{}' 'http://<SG_IP>:4984/db/Test?new_edits=true'
{"error":"Internal Server Error","reason":"Internal error: Get http://localhost:8092/default-ycsb/_design/sync_gateway/_view/access?key=%22%22\u0026stale=false: net/http: request canceled"}%

### Expected behavior
An appropriate message saying that the views are not yet ready should be logged

### Requirements 

- [ ] Return 503 error instead of 500

**Comment by tleyden** [comment]
@raghusarangapani can you confirm the error code is 500?  (as opposed to another 5xx error)

**Comment by djpongh** [comment]
Also look at #2699

**Comment by tleyden** [comment]
## Artificial reproduce test steps

1. In `bucket_gocb.go`, add the following artificially low viewquery timeout:

```
	bucket.SetViewTimeout(time.Nanosecond)
	goCbViewResult, err := bucket.ExecuteViewQuery(viewQuery)
```

2. Add a user via `_user` endpoint on port 4984 admin port
3. It should emit the error mentioned in https://github.com/couchbase/sync_gateway/issues/2639#issuecomment-318151761

**Comment by tleyden** [comment]
@djpongh / @ssmotra 

The new error will be:

```
--> 500 Internal error: Timeout performing ViewQuery.  This could indicate that views are still reindexing. Underlying error: Get http://localhost:8092/data-bucket/_design/sync_gateway_access/_view/access?key=%22foo3%22&stale=false: net/http: request canceled while waiting for connection  (1.2 ms)
```

If you want any changes to this, please let me know

**Comment by raghusarangapani** [comment]
Verified with CBS 4.6.2, SG 1.4.1.1-8:

- Loaded 500,000 docs to the CBS through SG. 
- Stopped SG.
- Deleted the views on CBS.
- Started SG.
- Issued a query to _all_docs.

```
~ » curl http://192.168.33.20:4985/db/_all_docs
{"rows":[
{"error":"Service Unavailable","reason":"Timeout performing ViewQuery - could indicate that views are still reindexing"}% 
```
