### ISSUE TITLE
Feature Request - SG should have a way to set maximum RAM quota

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2642]
Filing this issue on behalf of @suravarjjala

### Sync Gateway version
1.5.0

### Operating system
Windows-10

### Feature Request
Couchbase server has memory quota for various services like Data Service, Index Service, Search Service, Query Service etc.

SG should take in a memory quota through its config and should not exceed this memory usage.

**Comment by JFlath** [comment]
This MB might be relevant/interesting here: https://issues.couchbase.com/browse/MB-22595

**Comment by adamcfraser** [comment]
Closing based on age, and existing memory sizing for caches.
