### ISSUE TITLE
Sync Gateway should return 503 Service Unavailable and drop requests if overloaded (backpressure)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2646]
**Problem** 

If a load is applied to Sync Gateway that is more than it can handle, it is liable to run out of memory.   If the Sync Gateway -> Couchbase Server connection pool is full, then requests will "pile up" waiting for connections and start to fill up the heap.

**Proposed Fix** 

If Sync Gateway cannot get a connection to Couchbase Server in a certain time period -- could be configurable, but **1s** might be a sensible default -- it should return a 503 error as backpressure to the clients.  The clients should do a backoff/retry in these cases.

**Comment by adamcfraser** [comment]
Historically the problem with this has been that client libraries (go-couchbase) haven't provided a timeout mechanism that would allow Sync Gateway to fully release requests if they take longer than a given time interval.  Need to review whether we have better options with gocb.

**Comment by adamcfraser** [comment]
Tracking with CBG-638.
