### ISSUE TITLE
Add HTTPStats log key

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2647]
## Problem

It's hard to get a feel for the load going through sync gateway when looking at logs.   This would be potentially useful for a number of reasons, like being able to reproduce issues based on logs

## Proposed fix

**Requests**

1. For _bulk_docs requests
   - Num docs
   - Total size in bytes of all docs
1. For single doc operation mutation requests (PUT/POST)
    - Size of incoming doc in bytes
    - Number of attachments
    - Total size of attachments in bytes

**Responses**

1. For _bulk_docs responses
    - Num docs with errors
1. For single doc operation get response (GET)
    - Size of doc in bytes
    - Num attachments
    - Total size of attachments in bytes

**Comment by bbrks** [comment]
This should be covered by the stats enhancements in Iridium/Cobalt.
