### ISSUE TITLE
XATTRs: View backfill for deletes test failing

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2649]
### Sync Gateway version
1.5.0-428

### Operating system
CentOS 7

### Config file
```javascript
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "import_docs": "continuous",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                },
                "username": "data-bucket"
            }
        },
        "interface": ":4984",
        "log": [
            "CRUD+",
            "Cache+",
            "HTTP+",
            "Changes+"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
    }
```

### Log output
Successful run (non XATTRs) - https://gist.github.com/sethrosetter/820c858f4dae4e5c91ee27671441ab29
Unsuccessful run (XATTRs) - https://gist.github.com/sethrosetter/54e0d7f321f5c157ddaf2f065eb15a50

### Expected behavior
I would expect a view backfill with deletions to be send via _changes after SG restart

### Actual behavior
Only half of the docs are sent to changes after restart

### Steps to reproduce
1. http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/709/testReport/junit/testsuites.syncgateway.functional.tests/test_views/test_view_backfill_for_deletes_sync_gateway_default_functional_tests_False_/

Failing test scenario - https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/functional/tests/test_views.py#L15-L132

**Comment by adamcfraser** [comment]
I expect this is due to pending SG uptake of https://issues.couchbase.com/browse/MB-24616.
