### ISSUE TITLE
Build Active Replicator For Blip And Initial Unit Test

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#2653]
Need to get automated unit tests for sync gateway blip replication

**Comment by djpongh** [comment]
Step 1: investigate how to do web socket based unit testing

**Comment by ajres** [comment]
for a well maintained full WebSocket implementation the [recommended](https://godoc.org/golang.org/x/net/websocket) WebSocket library is https://github.com/gorilla/websocket.

There are some resources that cover WebSocket testing in Golang:

https://play.golang.org/p/X8GLU-Gcox
https://github.com/posener/wstest
https://groups.google.com/forum/#!topic/golang-nuts/KmVFFM980ac

I think that there is enough relevant information to be able to write an initial unit test suite for Blip over Websockets.

**Comment by ajres** [comment]
Current task is to create the first blip unit test with all associated scaffolding to support it.

**Comment by ajres** [comment]
Primary blip references:

https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Protocol#4-algorithm
https://github.com/couchbase/couchbase-lite-core/tree/master/Replicator
https://blog.couchbase.com/data-replication-couchbase-mobile/

SG currently implements the passive methods of the blip sync protocol, to support unit tests it will be necessary to implement the active methods of the protocol.

**Comment by djpongh** [comment]
- [x] delete go-blip-sync repo
- [x] move code back to sync gateway
- [ ] push up active replicator code
- [ ] single unit test to validate framework

**Comment by snej** [comment]
Crap, it's supposed to be `Sec-WebSocket-Protocol` in both the client and server handshake. I don't even remember where I got `Sec-WS-Protocols` from … maybe an earlier draft of the WebSocket spec? I'll need to fix go-blip.
