### ISSUE TITLE
XAttr:Sync Gateway unexpected rev history

### ISSUE THREAD

**Issue by rajagp** [couchbase/sync_gateway#2654]
### Sync Gateway version
1.5 latest download

### Operating system
Mac OS Sierra

### Config file
https://gist.github.com/rajagp/9b7a34c272f8aa910cd7916ce85b028e

### Log output
SG Logs: https://gist.github.com/rajagp/ef966cfa99fc1d0fe59607dfd836d1e3

SG _raw Metadata : https://gist.github.com/rajagp/82ae643ec2dee092d12f7dfb41d45c26

SG GET Doc with revs=true: https://gist.github.com/rajagp/925f3b01f2b65a6e36dcf20e3391534b

**Comment by tleyden** [comment]
- Revs tree has multiple roots
- Usually happens due to: when Lite does new edits = false PUT, it sends a list of ancestors.  If SG doesn't recognize any of those ancestors, it will create a new root on the rev tree.

**Comment by tleyden** [comment]
* New logging: whenever we create a new root revision, a new CRUD+ log should be emitted
   - Generic, endpoint independent
* HTTP++/Crud++ equivalent, lower level.

```
Dump ID and history.
func (db *Database) PutExistingRev(docid string, body Body, docHistory []string) error {
	newRev := docHistory[0]
	generation, _ := ParseRevID(newRev)
	if generation < 0 {
		return base.HTTPErrorf(http.StatusBadRequest, "Invalid revision ID")
	}
	deleted, _ 
```

**Comment by rajagp** [comment]
This is likely  a manifestation of a pull replication encoding issue on CB Lite - https://github.com/couchbase/couchbase-lite-core/issues/156

**Comment by adamcfraser** [comment]
Closing as a client issue - feel free to reopen if it looks like there's something on the SG side.
