### ISSUE TITLE
Need Blip WireShark Plugin

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#2657]
To help with debugging we need to create a wireshark plugin for the new replication protocol, blip.

**Comment by djpongh** [comment]
Work is done! Need to get this added to Wireshark.

**Comment by borrrden** [comment]
@tleyden Do you know the criteria for acceptance?

**Comment by tleyden** [comment]
Looks like the bulk is here:
https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob;f=doc/README.developer;hb=HEAD

More docs here:
https://wiki.wireshark.org/CreatingPatches
https://wiki.wireshark.org/Development/SecureProgramming
https://wiki.wireshark.org/Development/SubmittingPatches

**Comment by borrrden** [comment]
Submitted -> https://code.wireshark.org/review/30229

**Comment by djpongh** [comment]
Code has been merged
