### ISSUE TITLE
sg-replicate infinite retry loop with failed attachments

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2658]
Extracted out of https://github.com/couchbase/sync_gateway/issues/2607#issuecomment-308974353

@tleyden 
I was able to get this to work fine now with the config I provided. However, when replicating documents with attachments we do notice the following errors:
```
2017/06/16 08:52:07 Replicate: [db-local] stateFnActivePushBulkDocs got event: {PUSH_BULK_DOCS_SUCCEEDED [{com.id.dependency:pikaday_132  bad_request Missing data of attachment "pikaday.css"} {com.id.dependency:autocomplete_1  bad_request Missing data of attachment "autocomplete.css"} {com.id.dependency:moment_2103  bad_request Missing data of attachment "moment.min.js"} {com.id.dependency:fastclick_1  bad_request Missing data of attachment "fastclick.js"} {com.id.dependency:fontawesome_430  bad_request Missing data of attachment "fontawesome-webfont.eot"} {com.id.dependency:d3_1  bad_request Missing data of attachment "d3.js"} {com.id.dependency:pen-signature_1  bad_request Missing data of attachment "pen-signature.js"} {com.id.dependency:d3_2  bad_request Missing data of attachment "d3.js"} {com.id.dependency:charts_1  bad_request Missing data of attachment "charts.js"}]}
2017/06/16 08:52:07 Replicate: [db-local] BulkDoc response contains partial errors: [{Id:com.id.dependency:pikaday_132 Revision: Error:bad_request Reason:Missing data of attachment "pikaday.css"} {Id:com.id.dependency:autocomplete_1 Revision: Error:bad_request Reason:Missing data of attachment "autocomplete.css"} {Id:com.id.dependency:moment_2103 Revision: Error:bad_request Reason:Missing data of attachment "moment.min.js"} {Id:com.id.dependency:fastclick_1 Revision: Error:bad_request Reason:Missing data of attachment "fastclick.js"} {Id:com.id.dependency:fontawesome_430 Revision: Error:bad_request Reason:Missing data of attachment "fontawesome-webfont.eot"} {Id:com.id.dependency:d3_1 Revision: Error:bad_request Reason:Missing data of attachment "d3.js"} {Id:com.id.dependency:pen-signature_1 Revision: Error:bad_request Reason:Missing data of attachment "pen-signature.js"} {Id:com.id.dependency:d3_2 Revision: Error:bad_request Reason:Missing data of attachment "d3.js"} {Id:com.id.dependency:charts_1 Revision: Error:bad_request Reason:Missing data of attachment "charts.js"}], going to retry
```
This results in an infinite retry loop.

I ran a tcpdump capture on this request and when inspecting I noticed that the bulk put indeed only contains the json documents but no attachments in any multipart segment. Could this be a bug in sg-replicate?

The captured POST request can be found at https://gist.github.com/b-smets/3a46469c8a44673389670ec9651bbb36 .

**Comment by b-smets** [comment]
Do you have any ETA on when this will be available?

**Comment by tleyden** [comment]
I believe in approx 2 weeks

**Comment by tleyden** [comment]
@djpongh any idea?

**Comment by tleyden** [comment]
@b-smets can you attach a tcpdump of the `_bulk_get` request/response pair?  

Actually, if possible, these would also be helpful:

- Full tcpdump started when beginning replication up until the error
- The full document from Couchbase Server for one of the docs that is getting the error (eg, `com.id.dependency:pikaday_132`)
- Sync gateway logs with the `Replicate` log key turned on 


If it's easier, you can send these via email (check my github profile) or a private message on [gitter](https://gitter.im/couchbase/discuss)

**Comment by tleyden** [comment]
I am trying to figure out why there are _attachment fields in the docs that sg replicate pushes via bulk docs.  It is supposed to issue PUT requests for docs with attachments, not push them via bulk docs.

@b-smets those debugging artifacts I requested in previous comment would really help narrow this down
