### ISSUE TITLE
Crud++ Logging

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2659]
Extracted from https://github.com/couchbase/sync_gateway/issues/2654#issuecomment-308840614

* New logging: whenever we create a new root revision, a new CRUD+ log should be emitted
   - Generic, endpoint independent
* HTTP++/Crud++ equivalent, lower level.

```
Dump ID and history.
func (db *Database) PutExistingRev(docid string, body Body, docHistory []string) error {
	newRev := docHistory[0]
	generation, _ := ParseRevID(newRev)
	if generation < 0 {
		return base.HTTPErrorf(http.StatusBadRequest, "Invalid revision ID")
	}
	deleted, _ 
```

**Comment by djpongh** [comment]
Logging has been redone for 2.1.0
