### ISSUE TITLE
Feature request JSONP

### ISSUE THREAD

**Issue by ssured** [couchbase/sync_gateway#266]
On CouchDB I use JSONP for querying the `_session` of the active user by including `<script src="http://localhost:5984/_session?callback=registerSession"></script>`

This returns something like:

```
/* CouchDB */registerSession({"ok":true,"userCtx":{"name":"admin","roles":["_admin"]},"info":{"authentication_db":"_users","authentication_handlers":["oauth","cookie","default"],"authenticated":"cookie"}});
```

In `index.html` function `registerSession` is a function which triggers Persona `navigator.id.watch`:

```
function registerSession(sessionData){
  navigator.id.watch({
    loggedInUser: sessionData.userCtx.name,
    onlogin: function(assertion){...},
    onlogout: function(){}
  });
}
```

The thing I like here is that the session data is loaded during the initial page load.

Is JSONP support in the pipeline of SyncGateway? Are you interested in a PR, if so where should this code be placed? I'm not familiar with GO, but with a little help I think I can manage.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
