### ISSUE TITLE
Update version in build/README.txt during build process

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2667]
The readme.txt for 1.5 points to 1.4. Also the license needs to be updated.

**Comment by adamcfraser** [comment]
I've fixed this manually for 1.5 - turning this into a backlog ticket to automate this.

**Comment by tleyden** [comment]
Remove version from readme, add instructions on how to discover version via curl

**Comment by adamcfraser** [comment]
Removed version from README, it's already communicated elsewhere.
