### ISSUE TITLE
Persona origin a per database option

### ISSUE THREAD

**Issue by ssured** [couchbase/sync_gateway#267]
The persona authentication URL is `:4984/$databasename/_persona`. IMHO this implies that the persona configuration is more specific than the database config, as it's deeper in the URL. Currently persona (and facebook too, but I have no experience with facebook...) is a top level property in config.json, which is set for all databases at once, which conflicts with the url scheme.

Current config.json:

```
  "persona" : {
    "origin"   : "http://example.com/",
    "register" : true
  },
  "databases": {
    "todos": {
      "server": "http://localhost:8091",
...
```

Proposed situation:

```
  "databases": {
    "todos": {
      "persona" : {
        "origin"   : "http://example.com/",
        "register" : true
      },
      "server": "http://localhost:8091",
...
```

Please note that this is a CORS related issue, which is not officially supported yet. It can be easily resolved by starting an extra sync gateway instance, but I thought moving the property was the more correct solution.

Another correct solution would be to move the persona url to the root level: `server:4984/_persona` and leave the config the way it is.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
