### ISSUE TITLE
Update forum link in license

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2671]
It should be forums.couchbase.com

**Comment by tleyden** [comment]
I checked the https://github.com/couchbase/sync_gateway/blob/master/LICENSE file .. didn't see a forums link

**Comment by sethrosetter** [comment]
I looked at the license http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.5.0/1.5.0-442/couchbase-sync-gateway-enterprise_1.5.0-442_x86_64.tar.gz and it is there. Perhaps a build copy issue?

**Comment by tleyden** [comment]
Yeah maybe related to this: https://github.com/couchbase/build/blob/master/scripts/jenkins/mobile/build_sgw_unix.sh#L305
 
@ajres any idea if there is a separate license file?

**Comment by djpongh** [comment]
Need to resolve where the license file for the build is coming from.

**Comment by tleyden** [comment]
The license source file is here:

https://github.com/couchbase/build/blob/81b5138e08480f27e864a49abe22a4bceef9b6b9/license/sync_gateway/LICENSE_enterprise.txt

The broken link to the forum was removed in this commit:'

https://github.com/couchbase/build/commit/81b5138e08480f27e864a49abe22a4bceef9b6b9#diff-d002cfc55e14a86e39c658448e4e0db6
