### ISSUE TITLE
XAttrs: Updates reverted during concurrent Sync Gateway / SDK writes

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2672]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
1.5.0-441

### Operating system
CentOS 7

### Config file
```javascript
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "import_docs": "continuous",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                },
                "username": "data-bucket"
            }
        },
        "interface": ":4984",
        "log": [
            "CRUD+",
            "Cache+",
            "HTTP+",
            "Changes+"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
    }
```

### Expected behavior
I would expect that SG (new edits=False) SDK (CAS safe writes) would error if one of the clients had mutated the doc underneath the other

### Actual behavior
Sync Gateway is blowing away some SDK updates

### Steps to reproduce
1. `pytest -s --skip-provisioning --xattrs --ci --mode=cc --server-version=5.0.0-3158 --sync-gateway-version=1.5.0-441 -k "test_sg_sdk_interop_shared_docs[sync_gateway_default_functional_tests-1-1000]" testsuites/syncgateway/functional/tests/`

**Comment by sethrosetter** [comment]
Working on getting more details but want to file a tracking ticket.

**Comment by adamcfraser** [comment]
(removed incorrect statement about cas failure logging)

**Comment by adamcfraser** [comment]
Added additional unit testing for cas failure scenarios and still haven't been able to reproduce this issue.  Turning on HTTP+ logging in your tests might shed light on what's going on (i.e. to confirm when SG is returning the expected 409).

**Comment by adamcfraser** [comment]
I think I finally managed to repro this in a unit test (with some artificial race conditions added to the code).  It looks like it's a case of the SDK imports stepping on each other (and not actually the SG writes stepping on the SDK writes).  An on-demand SDK import would retry on CAS failure, but was re-attempting import the original SDK write - meaning that when it eventually succeeded, it was importing a stale SDK write.

This uncovered a fundamental difference between on-demand imports and feed-based imports we weren't previously covering - on-demand imports should proceed with the latest version of the doc on cas failure, while feed-based imports should just abandon import on cas failure (as they will eventually see the subsequent update on the feed and import at that time).

Have a fix in place that's working for the unit test scenario - will clean it up so it's ready for merge and retesting.

**Comment by sethrosetter** [comment]
Awesome. Thanks @adamcfraser!
