### ISSUE TITLE
Sync Gateway panics when reopening bucket

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2673]
This panic appears to be caused by a node failing over in a 3 node cluster. 

### Sync Gateway version
1.5.0-441

### Operating system
CentOS7

### Config file
```javascript
# When relevant, copy-paste your sync gateway config here.  Remove any sensitive information
as appropriate (including addresses, passwords, etc).
```

### Log output
https://gist.github.com/sethrosetter/f6b6cb96b6c3e387bf52a636217c4c4c - You will have to download to see the panic at the end

### Expected behavior
Graceful handling of DCP feed

### Actual behavior
Sync Gateway crashes with a panic

### Steps to reproduce
1. Start Sync Gateway pointing at a 3 node cluster
2. Failover a node
3. Sync Gateway crashes

**Comment by adamcfraser** [comment]
This doesn't appear to be triggered by DCP errors, based on the SG logs.  The panic is happening in gocb code (which we don't use for DCP).

It may be in response to the bucket going offline/online in response to a DCP error, but the actual panic looks like a potential bug in gocb when making a Stats() call.

**Comment by adamcfraser** [comment]
The underlying gocb panic has been addressed in gocbcore, and the current SG master picks up this change.  Should be fixed now - please reopen with new logs if this issue resurfaces.
