### ISSUE TITLE
Unable to install SG 1.5.0 on Win 10

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2677]
### Sync Gateway version
1.5.0-444

### Operating system
Win 10 x64

### Steps to reproduce
1.  Download SG 1.5.0-444 and double click to install.

### Expected behavior
SG installer should launch and SG should get installed.

### Actual behavior
SG installer does not launch. SG cannot be installed.

**Comment by raghusarangapani** [comment]
Installer works fine on Win 2012 R2 but not on Win 10. I tried 2 different Win 10 VMs.

**Comment by ajres** [comment]
On a Windows 10 VM that had previously been used to install SG(A) 1.4.1 I was unable to run the SG(A) installers from build 1.5.0-458.

This VM got corrupted and I had to create a fresh Windows 10 installation VM.

On this VM I am able to run the above installers, start the Windows service and call the SG(A) REST API.

**Comment by ajres** [comment]
@raghusarangapani are there any entries to the Windows Events viewer when you attempt to launch the installer?

Had the two Windows 10 VM's been used for installation testing of previous SG(A) versions?

**Comment by raghusarangapani** [comment]
Synced up with @ajres and experimented with the installer. For some reason Win 10 thinks that the 1.5.0 installer is not secure and blocks it from launching.

The workaround to get it to run is to right click on the installer and select Properties. At the bottom, there is a message that says 
```
This file came from another computer and might be blocked to help protect this computer [ ] Unblock
```
Check Unblock and say OK. Now the installer runs.

The same behavior is not observed with 1.4.1 installer.

The workaround has to be documented. It would also be good to identify why 1.4.1 is not blocked but 1.5.0 alone is blocked.

I tried to verify the signature of the exe with Microsoft's SignTool. Neither 1.4.1 nor 1.5.0 are signed. 

```
C:\Program Files (x86)\Windows Kits\10\bin\x64>.\signtool.exe verify C:\Users\Administrator\Downloads\couchbase-sync-gateway-enterprise_1.4.1-3_x86_64.exe
File: C:\Users\Administrator\Downloads\couchbase-sync-gateway-enterprise_1.4.1-3_x86_64.exe
Index  Algorithm  Timestamp
========================================
SignTool Error: No signature found.

Number of errors: 1

C:\Program Files (x86)\Windows Kits\10\bin\x64>.\signtool.exe verify C:\Users\Administrator\Downloads\couchbase-sync-gateway-enterprise_1.5.0-463_x86_64.exe
File: C:\Users\Administrator\Downloads\couchbase-sync-gateway-enterprise_1.5.0-463_x86_64.exe
Index  Algorithm  Timestamp
========================================
SignTool Error: No signature found.

Number of errors: 1
```

**Comment by raghusarangapani** [comment]
Couchbase server seems to have 2 msis, one signed and the other unsigned:
```
C:\Program Files (x86)\Windows Kits\10\bin\x64>.\signtool.exe verify C:\Users\Administrator\Downloads\couchbase-server-enterprise_5.0.0-3217-windows_amd64.msi
File: C:\Users\Administrator\Downloads\couchbase-server-enterprise_5.0.0-3217-windows_amd64.msi
Index  Algorithm  Timestamp
========================================
SignTool Error: A certificate chain processed, but terminated in a root
        certificate which is not trusted by the trust provider.

Number of errors: 1

C:\Program Files (x86)\Windows Kits\10\bin\x64>.\signtool.exe verify C:\Users\Administrator\Downloads\couchbase-server-enterprise_5.0.0-3217-windows_amd64-unsigned.msi
File: C:\Users\Administrator\Downloads\couchbase-server-enterprise_5.0.0-3217-windows_amd64-unsigned.msi
Index  Algorithm  Timestamp
========================================
SignTool Error: No signature found.

Number of errors: 1
```

**Comment by raghusarangapani** [comment]
Tested it out with the latest build 1.5.0-466.
SG 1.5.0-444 with which this issue was logged is unsigned and gets blocked by windows.
Confirming that the build 1.5.0-466 is signed and does not get blocked by windows
```
C:\Program Files (x86)\Windows Kits\10\bin\x64>signtool.exe verify C:\Users\Administrator\Downloads\couchbase-sync-gateway-enterprise_1.5.0-466_x86_64.exe
File: C:\Users\Administrator\Downloads\couchbase-sync-gateway-enterprise_1.5.0-466_x86_64.exe
Index  Algorithm  Timestamp
========================================
SignTool Error: A certificate chain processed, but terminated in a root
        certificate which is not trusted by the trust provider.

Number of errors: 1
```
