### ISSUE TITLE
Use optimal number of design docs

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2679]
After splitting out the design docs in issue https://github.com/couchbase/sync_gateway/issues/2628, we've had subsequent input from the view team that there's a performance tradeoff when adding design docs, as each design doc creates a separate DCP feed.

Pending feedback from the view team, we may need to scale back the existing 6 design docs.

We may be able to conditionally deploy either the _vbseq or non-vbseq version of the access and role_access views depending on whether the deployment is using accel.  This would be a benefit even if we revert back to two design docs, because of the overall reduction in indexing work.

**Comment by JFlath** [comment]
@adamcfraser Thinking about it more, I think we need to revert https://github.com/couchbase/sync_gateway/issues/2628. Without a non-downtime system for upgrading views, splitting the ddocs out has broken the upgrade path from 1.4 -> 1.5 and 1.3 -> 1.5.

**Comment by JFlath** [comment]
(Luckily, I do have a plan, wait out ;))

**Comment by tleyden** [comment]
@JFlath I think you meant to say "revert https://github.com/couchbase/sync_gateway/pull/2655", which is a PR.  

#2628 that you mentioned is the issue associated w/ the PR, but I just wanted to make it explicit and get the cross-linking working (now #2655 will point back to this comment)

**Comment by adamcfraser** [comment]
Closing - staying with 2 and dealing with view-related downtime via view versioning in 2.0.0, supporting GSI in 2.1.0.
