### ISSUE TITLE
Sync Gateway takes a long time to launch intermittently

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2680]
### Sync Gateway version
1.5.0-446

### Operating system
CentOS 7

### Config file
```javascript
# When relevant, copy-paste your sync gateway config here.  Remove any sensitive information
as appropriate (including addresses, passwords, etc).
```

### Log output
https://gist.github.com/sethrosetter/d53d112ce666a796f7bb9e3a596b9194

The first log is where the startup hangs.
The second is a second launch

### Expected behavior
Sync Gateway should have fast startup against an empty bucket

### Actual behavior
Sync Gateway takes a long time to launch intermittently

### Steps to reproduce
1.  http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/758/testReport/junit/testsuites.syncgateway.functional.tests/test_changes_backfill/test_backfill_channel_grant_to_role_longpoll_custom_sync_access_CHANNEL_SYNC_channels_to_grant3_/

**Comment by sethrosetter** [comment]
We need to do some profiling during startup plus more logging. I'm going to bump the launch timeout in the tests to hopefully work around this. I will pull it back once this has been fixed.

**Comment by sethrosetter** [comment]
I am seeing this frequently now and it is failing ~5 tests per run due to this. We need to pin down if it is a regression or environmental. Marking as a p1 High.

**Comment by sethrosetter** [comment]
When I increase log verbosity and run the job again, I'm not seeing any timeouts on start. 
2 possibilities:
- decreased load on the hypervisors
- race that is not longer apparent with more verbose logging

http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/775/

**Comment by djpongh** [comment]
Same as: https://github.com/couchbaselabs/sync-gateway-accel/issues/151 ?

**Comment by djpongh** [comment]
Also: https://github.com/couchbase/sync_gateway/issues/1515 ?

**Comment by adamcfraser** [comment]
Several enhancements in startup processing since 1.5 - closing, can reopen based on recent repro.
