### ISSUE TITLE
High Gateload – Failed to push/pull

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2688]
A sync gateway perf test was started with xattrs disabled and the ramp up time increased by a factor of 10. The grafana URL shows high Gateload – Failed to push/pull data. Someone familiar with gateload should take a look at the graph data and triage the issue.

Perf run:
http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/556/consoleFull

Grafana:
http://s61103cnt72.sc.couchbase.com:3000/dashboard/db/sync-gateway-perf-test?var-perftestrundbs=jenkins-sync-gateway-perf-test-556&var-lb_host=All&var-sg_host=All&var-cb_host=All&var-lg_host=All&var-ac_host=All&from=1498253969000&to=1498513169000

**Comment by raghusarangapani** [comment]
I have the profile info and SG/SG_Accel logs downloaded to my mac. @tleyden Let know if I can upload it to some place you can access.

**Comment by adamcfraser** [comment]
It's interesting to note that the failed push/pull occurred in the first hour of the test, and the test ran clean for the remaining 3 days.  Based on the CPU spike on startup, I'm guessing that the reduced ramp-up resulted in high SG load during, causing GL requests to fail.

Given that the system recovered, and clients would normally retry on this type of failure, I think this can be treated as a P2 issue.

**Comment by adamcfraser** [comment]
Closing - perf switched over to perfrunner.
