### ISSUE TITLE
Do not panic for empty unsupported dictionary (1.3.1)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2689]
### Expected behavior
Sync Gateway should not panic for empty unsupported block in config, < 1.4.0

### Actual behavior
Sync Gateway panics for empty unsupported block in config, < 1.4.0

**Comment by tleyden** [comment]
Related mobile-testkit ticket with more info: https://github.com/couchbaselabs/mobile-testkit/issues/1240

**Comment by tleyden** [comment]
Fixed in https://github.com/couchbase/sync_gateway/commit/56db54c2b3f721e923a2d1c7d003f9bca19aeb05

@sethrosetter re-assigning to you to verify

**Comment by sethrosetter** [comment]
Since @raghusarangapani is running tests, this is fixed. Can you verify and close @raghusarangapani?

**Comment by raghusarangapani** [comment]
The issue is fixed with 1.3.1.2 MP
