### ISSUE TITLE
WriteDirect() test helper method should support xattr mode

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2691]
Currently the `WriteDirect()` helper method doesn't support writing to a doc with xattrs, and so a few unit tests have been disabled against xattr buckets in the meantime.

Benefit: running these tests against xattr buckets could surface issues and prevent regressions.

This fixes the root cause of https://github.com/couchbase/sync_gateway/issues/2666 -- the initial fix was just a workaround to disable those tests.

**Comment by adamcfraser** [comment]
Closing based on age.
