### ISSUE TITLE
Sync Gateway change feed order is different when using active_only true and limit parameters

### ISSUE THREAD

**Issue by mjosephd** [couchbase/sync_gateway#2696]
We currently use pouchdb and couchbase sync gateway to sync data. During development we noticed that the initial sync time for existing users on a new or different devices took time and this time increased more the user used the application. Upon investigation we noticed that all deleted/removed true documents were getting synced to the client upon the initial sync.

In order to mitigate this we saw that couchbase has a parameter called active_only which when true ignores these deleted and removed true documents. So we decided to use active_only true just for the initial sync. We intercepted the pouchdb request for the initial sync and added the active_only true get parameter.

However after doing this we noticed that there were sync issues, upon investigation we noticed that when limit is used to get changes from the change feed part by part the order is incorrect.

For example we did a change feed call like the following where active_only is false as a base test

```
`http://${hostAddress}/${dbName}/_changes?timeout=25000&style=all_docs&since=0&active_only=false`;
```

After that we did the same test but with limit

```
`http://${hostAddress}/${dbName}/_changes?timeout=25000&style=all_docs&since=0&active_only=false&limit=10`;
```

Then we compared the second requests records to the first ten records of the first request (without limit) and the order was correct, we also tried this by changing the since value and the given order was still correct.

However when active_only is true the order is incorrect.

### Sync Gateway version
1.3 (Was unable to do deep testing with the latest 1.4.1 version, but the given test case attached failed for that as well)

### Operating system
Ubuntu

### Expected behavior
The order of the change feed should be maintained when a limit value is passed like when active_only is false then

### Actual behavior
The order is not maintained when the active_only parameter is true then

### Steps to reproduce

I have created a sample test case (in nodejs with typescript using async await so code is more readable)

I have attached a test sample that will demonstrate this, run `npm install` to get the packages and `npm run start` to start the tests.

[submitvalues.zip](https://github.com/couchbase/sync_gateway/files/1102619/submitvalues.zip)

**Comment by tleyden** [comment]
@mjosephd can you post `_changes` endpoint responses for both the normal case and the `active_only` case into gists and link to the ticket?

Also, when you say:

> we noticed that there were sync issues

Can you elaborate?

Looks like you submitted a test sample, which is great.  Can you expand on instructions?  What does sync gateway config need to look like for this to run?

**Comment by mjosephd** [comment]
In the test sample what I do is I make a baseline request WITHOUT the limit parameter to the change feed. Afterwards I store it's json result in a variable.

Then there is a while loop that runs repeatedly calling the change_feed, get it's last_seq value store it and for the NEXT change_feed call use that last_seq value in the since parameter. After each change feed call I compare it's result with the initial request WITHOUT limit's respective portion.

What this means is if I have a limit of 5, for my second request I will compare the results array of the baseline request (the change feed call without a limit) from index 5 to 10 with the second change feed call.

In the comparison when using active_only true the comparison fails, which means that there is a sync issue since we use limit in all of the calls.

The following gist demonstrates the difference when using limit and not limit with active_only false (check the url for each json). The baseline call without no limit starts with `10318`, however the call with limit returns `224212:7702` as the first sequence value. However if I change the limit to let's say 10 we again get the sequence value of `10318` as the first sequence, but the second sequence is not `10328 ` and is different.

https://gist.github.com/mjosephd/bc5d5c9fb9d1d73883b7167f6f0dabab

The sample sync gateway json is similar to what we are using

```
{
    "log": ["*"],
    "interface":":4984",
    "adminInterface":":4985",
    "CORS": {
        "Origin":["...."],
        "LoginOrigin":["...."],
        "Headers":["Content-Type", "auth-token"],
        "MaxAge": 1728000
    },
    "databases": {
      "database": {
        "server": "http://localhost:8091",
        "users": {
          "GUEST": { "disabled": true, "admin_channels": ["*"] }
        },
        "sync": "function(doc) {channel(doc.channels);  }",
        "event_handlers": {
          "document_changed": [
            {
              "handler": "webhook",
              "url": "....",
              "filter": "function(doc) { .... }"
            }
          ]
        }
      }
    }
}

```

**Comment by adamcfraser** [comment]
May be addressed by CBG-731.
