### ISSUE TITLE
Crash when bringing database online after performing resync

### ISSUE THREAD

**Issue by b-smets** [couchbase/sync_gateway#2712]
### Sync Gateway version
{"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":1.5},"version":"Couchbase Sync Gateway/1.5.0(381;6a1598b)"}

### Operating system
Ubuntu 16.04

### Log output
https://gist.github.com/b-smets/9d3b8ca7fdc7a15c796d9bc76c474956

We noticed that some documents were not passing through the sync function properly causing them not to be assigned to any channels other than the default (Should we create a separate issue for this?). In order to work around this we could either restart the SG service which fixes the syncing but a cleaner way is to bring the database offline, resyncing and bringing it back online.

### Expected behavior
- Only this specific database is taken offline
- It comes back online after performing the resync

### Actual behavior
- It seems other databases are also offline (line 3-4 in gist)
- Attempting to bring the database back online results in the service crashing with the provided trace (see gist)

### Steps to reproduce
1.  POST http://localhost:4985/mydb/_offline
2.  POST http://localhost:4985/mydb/_resync
3.  POST http://localhost:4985/mydb/_online
=> Service crashed

**Comment by tleyden** [comment]
> (Should we create a separate issue for this?)

@b-smets yeah I think that merits it's own ticket.  Please mention this ticket so they get linked together.

**Comment by ajres** [comment]
I tried to repro on latest SG master, I was unable to generate a panic, gist here: https://gist.github.com/ajres/8f7935df43a75e169fc19caa584acca1

One notable difference in the original gist the backing bucket is opened by GoCBGoCouchbaseHybrid

But on latest master it is opened by:

GoCBCustomSGTranscoder

@adamcfraser is this a configuration option or is this a code change on latest master?

**Comment by ajres** [comment]
As this can't be repro'd on latest master I'm going to close this ticket out.

@b-smets if you are able to repro this on latest master, please re-open the ticket and post your SG config.json file.
