### ISSUE TITLE
2.0: Forum: CouchBaseLite 2.0 Replication Error When multiple clients delete Documents

### ISSUE THREAD

**Issue by hideki** [couchbase/sync_gateway#2713]
### Sync Gateway version
1.5-beta

### Operating system
OSX

### Config file
https://github.com/couchbaselabs/mobile-training-todo/blob/feature/2.0/swift/sync-gateway-config.json

### Log output
```
2017-07-05T13:51:52.179-04:00 WARNING: Sync fn exception: TypeError; doc = map[_id:user1.6E398F3F-6B63-4A42-BB30-064CAC3A9D98 _rev:2-3b145348adc408cb6c426a0a0858380eb3c1a5f0 _deleted:%!s(bool=true)] -- db.(*Database).getChannelsAndAccess() at crud.go:1049

```

### Expected behavior
Deleted doc should be replicated.

### Actual behavior
Deleted doc is not replicated.

### Steps to reproduce
1.  Run ToDo sample with two devices, and run SG.
2.  Create tasks and share.
3.  Delete Task from one device
4. Deleted task should be replicated to another device. But not.

### NOTES
CBL Android Ticket: https://github.com/couchbase/couchbase-lite-android/issues/1242

Forum: https://forums.couchbase.com/t/couchbaselite-2-0-replication-error-when-multiple-clients-delete-documents/13341

> now ,I using ToDo Example(Couchbase lite 2.0 beta 011) to test Replication Items。i runing app on the multiple android devices, I found add\update items replication is okey.but when one client delete a document,the other client document does not change anything.i don't know what happened.

**Comment by djpongh** [comment]
@snej , can you take care of this?

**Comment by snej** [comment]
This was actually a LiteCore bug. https://github.com/couchbase/couchbase-lite-core/issues/197
