### ISSUE TITLE
Invalid memory address error while running sync-gateway on zap tool.

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#2719]
### Sync Gateway version
sync-gateway 1.5  

### Operating system
Centos

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": [
        "*",
        "BLIP+"
    ],
    "databases": {
        "db": {
            "import_docs": "continuous",
            "server": "http://192.168.33.10:8091",
            "bucket": "default",
            "password": "password",
            "unsupported": {
                "enable_extended_attributes": true,
                "replicator_2": true
            },
            "users": {
                "GUEST": {
                    "disabled": false,
                    "admin_channels": [
                        "*"
                    ]
                }
            }
        }
    }
}
```

### Log output
https://gist.github.com/sridevi-15/61f7dd16d5ec8e148fb595740d151e1d

### Expected behavior
Should have a response that database not found

### Actual behavior
Throwing error with invalid memory address/nil pointer dereference

### Steps to reproduce
1.  Add the config file as above
2.  start sync-gateway and couch base server.
3. tail sync-gateway logs
4.  Hit this request below request using curl or on the browser
http://192.168.33.11:4984//ZAP%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%0A/

**Comment by tleyden** [comment]
I wasn't able to reproduce on https://github.com/couchbase/sync_gateway/commit/ed62ba3c31dd377825d501fa4d4a372a4c9819ee
