### ISSUE TITLE
Unmarshaling warning messages for user delete operation

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2723]
### Sync Gateway version
1.4.1
### Operating system
RedHat 7.2

Unmarshaling warning messages are confusing user even-though valid json body is provide while  creating user.  These messages are observing during user deletion.
Are these warning valid?

### Log output
WARNING: changeCache: Error unmarshaling doc "_sync:user:SyncGW1C1": unexpected end of JSON input – db.(*changeCache).processPrincipalDoc() at change_cache.go:441

### Expected behavior
WARNING message should not observe in logs even though valid JSON body.

### Actual behavior
Unmarshaling warning messages about JSON body confusing user.

### Steps to reproduce
1.  Create user with request body 
 {"name":"SyncGW1C1",
            "admin_roles":["level-2"],
            "password":"password",
            "admin_channels":["SyncGW1C1"]
            }

2.  Delete user

**Comment by ArihantRk** [comment]
@djpongh any impact on functionality from these warnings. 
Also what are the scenarios these warning messages are expected?

**Comment by ajres** [comment]
This issue also applies to deleting roles.

The cause is that the JSON body of deleted _user/_role docs is being passed as an empty byte slice to processPrincipalDoc().

The body appears to be missing in the underlying  sgbucket.FeedEvent that is passed to 

`func (c *changeCache) DocChanged(event sgbucket.FeedEvent) {`

**Comment by adamcfraser** [comment]
@ajres It's expected that there's no body on a delete mutation.  For principal docs in particular, there's no additional processing required for delete mutations - there's no sequence update, and we don't need to improt - so we can filter these out in ProcessFeedEvent.
