### ISSUE TITLE
Sync Gateway configured with a non-Couchbase bucket

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#2741]
As a user, i should receive an error message when a Sync Gateway is configured with a non-Couchbase bucket. 

If there is only one database configured in Sync Gateway, then Sync Gateway should fail at startup. 

If there are multiple databases configured in the Sync Gateway, an error message should be logged to capture buckets which database connections could not be established with the correct error message.

**Comment by adamcfraser** [comment]
@ssmotra For the first item, what do you mean by non-Couchbase bucket, specifically?  I assume walrus buckets are fine - is this specifically for memcached/ephemeral buckets in a Couchbase Server instance?

For the second and third points - Sync Gateway currently fails to start if it can't connect to any of the databases defined in the config.  I'm not sure we need/want to change that behaviour.

**Comment by ghost** [comment]
@adamcfraser - you are correct about  memcached/epehemeral buckets. Walrus buckets are perfectly fine. 

I agree on not wanting to change the current behavior with Sync Gateway failing to start if any database in the config is not connected to a Couchbase bucket.

**Comment by adamcfraser** [comment]
I think the first part of this ticket may still apply - doing a check for memcached/ephemeral buckets and failing with a useful log message in those cases.

**Comment by JFlath** [comment]
>If there is only one database configured in Sync Gateway, then Sync Gateway should fail at startup.

I think this is probably a little far - it's possible to create a db after startup.

**Comment by adamcfraser** [comment]
@JFlath The current behaviour is that if you've got a database defined in your config, and we're unable to successfully connect/start that database, Sync Gateway is stopped.  I think we want to stick with that for now - at least until we have better runtime diagnostics (admin console) for Sync Gateway that would make it clear to users that they have a problem with one of their databases.

**Comment by JFlath** [comment]
Huh, I stand corrected. Withdrawn :P

**Comment by adamcfraser** [comment]
Closing based on age.
