### ISSUE TITLE
Sync Gateway Facebook Login email is missing

### ISSUE THREAD

**Issue by pradipvaghasiya** [couchbase/sync_gateway#2760]
I am raising this as an Issue as Jens suggested on below post.
https://forums.couchbase.com/t/sync-gateway-facebook-login-email-is-missing/13553

Hello,
I have checked other forums but could not identify the solution of below problem.

Currently we have many users who are using Facebook through their mobile number and not using email at all. Those can not login to my app as Sync Gateway Throws the error saying email is missing. Indeed their tokens do not have email.

2017-07-24T11:54:46.928+05:30 HTTP: #38388: --> 400 Cannot register new user: email is missing (104.8 ms)

Is there any way I can bypass this so that users can use the app only using facebook id?

We are using below

### Sync Gateway version
Sync Gateway Community edition : 1.4.1

### Operating system
Ubuntu 14

iOS/Android Mobile Client: 1.4

### Steps to reproduce
1.  Try to Login with Facebook using userId which does not have email

**Comment by pradipvaghasiya** [comment]
There are many users affected by this.
Can you please suggest any work around for this? Is it fixed in Sync Gateway 1.5?

**Comment by adamcfraser** [comment]
I'll look into whether this can get fixed for 1.5.1.

**Comment by pradipvaghasiya** [comment]
If email is must, then for Facebook, email can be created with [facebook-userid]@facebook.com

**Comment by pradipvaghasiya** [comment]
Hi @adamcfraser,
Thanks very much for fixing it! Is there anyway I can use or get any build which contains this fix? As I can see 2.0.0 is due in Feb End. I am currently using 1.5.1

Or I will have to build locally and use it?
