### ISSUE TITLE
Date parsing in sync-function gives wrong epoch time.

### ISSUE THREAD

**Issue by shashanktomar** [couchbase/sync_gateway#2765]
The Date().getTime in sync-function returns wrong time. This is a bug in otto library. I have filed an issue [here](https://github.com/robertkrimen/otto/issues/264). This might have some major implications on time critical code.

**Comment by adamcfraser** [comment]
Based on the otto issue, it looks like there's the potential for a difference of one millisecond in epoch time conversion.  Assuming the conversion is consistent (and so date equality checks are fine), it doesn't strike me as something that would result in major implications in most use cases.  If you've got a specific use case where this is impacting your application, I'd be interested in hearing more details.
