### ISSUE TITLE
View queries public REST API limit, skip options don't work

### ISSUE THREAD

**Issue by swaheed2** [couchbase/sync_gateway#2773]
### Sync Gateway version   

Couchbase Sync Gateway/1.4.0(2;9e18d3e)

### Operating system
Debian

### Expected behavior

```GET``` request to ```...4984/todos/_design/test/_view/AllAccounts?limit=6``` should return 6 row. 

### Actual behavior

```GET``` request to ```...4984/todos/_design/test/_view/AllAccounts?limit=6``` returns 0 row 

```GET``` request to ```...4984/todos/_design/test/_view/AllAccounts``` (without limit) returns 17 rows

```GET``` request to ```...4984/todos/_design/test/_view/AllAccounts?limit=600``` returns 4 rows. 

The View

```
    AllAccounts: {
		map: function (doc) {
			if (doc.type === 'PartyGroup') {
				const value = {
					groupName: doc.groupName,
					partyId: doc.partyId
				};
				if (doc.slmnFirstName && doc.slmnLastName) {
					value['salesmanName'] = doc.slmnFirstName + ' ' + doc.slmnLastName;
				}
				if (doc.slmnPartyId) {
					value['salesmanPartyId'] = doc.slmnPartyId;
				}
				emit([doc.groupName, Number(doc.partyId)], value);
			}
		}.toString()
	}

```

**Comment by swaheed2** [comment]
@djpongh Do you have any idea why this is happening... seems like a major bug, need to use the limit query.

**Comment by tleyden** [comment]
Hey @swaheed2 thanks for the issue report.  Can you give step-by-step to repro?  (including your SG config, couchbase server version, and how you inserted the docs)

**Comment by tleyden** [comment]
@raghusarangapani do you know if we have any existing functional tests that exercise limit and skip options on pass through view queries?

**Comment by raghusarangapani** [comment]
Not to my knowledge

**Comment by adamcfraser** [comment]
When processing views via the public API, Sync Gateway executes the raw view query against the server, and then does post-filtering to restrict the results to those documents the user has access to.  

The net result is that the limit is being applied on the server view query, and then those results are being subsequently filtered by channel.  

As pass-through view queries on the public port are still officially an unsupported feature, I don't expect this would be a high priority item to address.  In general view queries have relatively high performance overhead, and aren't suited for high concurrency usage via the public API.  The alternative approach would be to use replication for data retrieval, and perform a client side query using Couchbase Lite.  If this isn't an option for you, any additional specifics on your use case would help us understand the priority.

**Comment by swaheed2** [comment]
Our use case is build a mobile app (cordova) that also works as a web app. The mobile app users will need to go through a replication process and download all the data. The web app users will use the REST API directly and don't need to download the data on their devices. 

We have the same views on the sync gateway and the local database. So depending on which environment the app is running on (cordova or non cordova), we either point the database url to the sync-gateway, or get the local SQLite database url through the plugin.

We wanted to use limit to retrieve limited # of docs and load more as the user scrolls.

Everything works great in our prototype app other than the ```limit``` feature on the sync-gateway, and https://github.com/couchbase/sync_gateway/issues/2774

**Comment by adamcfraser** [comment]
Closing based on age.
