### ISSUE TITLE
Support for prefix_match_level

### ISSUE THREAD

**Issue by swaheed2** [couchbase/sync_gateway#2774]
### Sync Gateway version   

Couchbase Sync Gateway/1.4.0(2;9e18d3e)

### Operating system
Debian

### Expected behavior

support ```prefix_match_level``` query options. This options is supported in the couchbase lite REST API

### Actual behavior

no support for ```prefix_match_level``` query options. This options is supported in the couchbase lite REST API.

**Comment by adamcfraser** [comment]
Closing based on age.
