### ISSUE TITLE
Improvement - run sg_collect via PUT/POST on admin port

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/sync_gateway#2778]
For those running SG as a PAAS or Docker image where access is limited is it possible to have 
:4985/_sg_collect to run sg_collect info tool much like Couchbase server has its admin GUI to run cb_collects.

With the optional of specifying the path to write to. 

Thank you

**Comment by djpongh** [comment]
@ssmotra , this needs a spec with full requirements

**Comment by djpongh** [comment]
Dup of #2516
