### ISSUE TITLE
Minimize overhead and log noise when binary documents arrive over DCP

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2780]
Currently we're logging a warning when a binary document arrives over the DCP stream.  In this scenario we shouldn't even be attempting to unmarshal the document in the first place, if we're able to recognize the document as binary based on doc type.

**Comment by sridevi-15** [comment]
verified on 1.5.0-573 , do not see warning message for binary document created via SDK and imported via SG
