### ISSUE TITLE
sync Gateway replication slows down

### ISSUE THREAD

**Issue by Yuvraj-Sorav** [couchbase/sync_gateway#2783]
I am facing issue with sync gateway when the number of documents on the server increases. Here, the scenario is when we have few documents on server.The devices (iOS and Android) Pusher and puller works fine.But when the number of documents increases, the devices  (iOS and Android) gets the documents with delay which has no fixed time. Sometimes, documents comes live, sometime after 2 mins or sometimes devices will not able to get the documents.Sync gateway shows no error or warning. Also, no error or warning in pusher and puller in the device.     
 
### Sync Gateway version
Currently i am using sync gateway 1.4. Also, i have tried all the versions of sync gateway from version 1.1 to 1.5.

### Operating system
I am using macOS.

### Config file
[syncGatewayFile.txt](https://github.com/couchbase/sync_gateway/files/1207101/syncGatewayFile.txt)

### Log output
https://gist.github.com/Yuvraj-Sorav/1632ab38021f2540c09a402990467f73
No error occur in the sync gateway logs

### Expected behavior
Documents should pass from device to other device with the help of sync gateway.Devices must push and pull the data within no time.

### Actual behavior
Documents not syncing properly.Takes too much time to sync the documents.Sometimes documents not synced. 

### Steps to reproduce
Its a random issue.It occurs anytime and when it occurs no sync takes place.

**Comment by adamcfraser** [comment]
Can you provide some more specifics on the behaviour you're seeing?  The provided log excerpt only shows a few milliseconds after the changes request was issued, and some documents are being returned.  In particular:
 - what document id is taking longer than expected to synchronize?
 - what document id (if any) is failing to synchronize altogether
 - complete logs showing when this document was written to Sync Gateway, and when (if ever) it was eventually replicated

**Comment by Yuvraj-Sorav** [comment]
Sorry for replying late.
I am giving you sync gateway log file which contains a document with id - 1781138699.This document should sync to other devices and it is not conflicted either.This document has roles channels everything.It should sync to the device which has id- 919636251422.
[log.txt](https://github.com/couchbase/sync_gateway/files/1217120/log.txt)

**Comment by adamcfraser** [comment]
There is something unusual going on with your instance, based on the logs.  There are many messages like:

2017-08-11T02:09:39.888-04:00 Cache:   Received unexpected out-of-order change - not in skippedSeqs (seq 3771, expecting 10612) 

This suggests that documents are arriving over the server's mutation feed with sequences much lower than what's already been buffered by Sync Gateway.  This shouldn't be the case.  A few questions might help clarify what's going on:

1. How many Sync Gateway instances are running?
2. From the logs it looks like you're using bucket shadowing?  Is that required?  In general bucket shadowing is discouraged.  In particular it's not needed when using Sync Gateway 1.5.
3. Has there been any backup/restore done of the buckets?

**Comment by Yuvraj-Sorav** [comment]
I am using sync Gateway 1.4 only one instance, but having four databases with shadowing concept, like

DB One with A bucket and A_shadow bucket
DB  Two with B bucket and B_shadow bucket
DB Three with C bucket and C_shadow bucket
DB Four with D bucket and D_shadow bucket

 and B and B_shadow has XDCR to A and A_shadow with one specific id filter

Yes, bucket shadowing is necessary for our structure because we update documents in shadow buckets by php SDK 2.3 .

And we are not using any backup and restore.

Our mobile users are connected to DB one and DB Two.

**Comment by adamcfraser** [comment]
Closing based on age.
