### ISSUE TITLE
Shadowing failing for documents containing numbers

### ISSUE THREAD

**Issue by jnordberg** [couchbase/sync_gateway#279]
I'm trying to shadow a bucket with 1 million documents, the sync gateway manages to get through 500k records and then hangs.

Using 11ab09a2900eed58ea9db57eafaab36bb51a1fe4 and Couchbase Server 2.5

Config:

``` json
{
  "log": [
    "Shadow"
  ],
  "users": {
    "GUEST": {
      "disabled": true
    }
  },
  "databases": {
    "soter": {
      "server": "http://localhost:8091",
      "bucket": "soter_sync",
      "shadow": {
        "server": "http://localhost:8091",
        "bucket": "soter"
      }
    }
  }
}

```

Log

```
14:47:24.893553 Enabling logging: [Shadow]
14:47:24.893626 ==== Couchbase Sync Gateway/0.93 ====
14:47:24.893640 Configured Go to use all 8 CPUs; setenv GOMAXPROCS to override this
14:47:24.893661 Opening db /soter as bucket "soter_sync", pool "default", server <http://localhost:8091>
14:47:24.893693 Opening Couchbase database soter_sync on <http://localhost:8091>
14:47:24.927168 Shadow: Watching doc changes...
14:47:24.928213 Using default sync function 'channel(doc.channels)' for database "soter"
14:47:24.928256 Opening Couchbase database soter on <http://localhost:8091>
14:47:24.958758 Database "soter" shadowing remote bucket "soter", pool "default", server <http://localhost:8091>
14:47:24.958770 Starting admin server on 127.0.0.1:4985
14:47:24.959816 Starting server on :4984 ...
14:47:24.961082 Shadow: Reading history of external bucket
14:47:24.961865 WARNING: Error applying change from external bucket: json: cannot unmarshal number into Go value of type db.Body -- db.(*Shadower).readTapFeed() at shadower.go:73
```

Last message is repeated for about 5 minutes and then just stops, restarting makes it go for another 5 minutes but it never manages to catch up with the history of the external bucket. (the sync bucket stops at around 500k docs, vs 1000k for the bucket its trying to shadow)

**Comment by Steve2724214** [comment]
I am new to couchbase, but in your documentation for sync gateway it provides a potential solution for working with web apps... "Pre-existing data and 'bucket shadowing'.  A reference guide to how you can enable Couchbase Lite-side sync with existing Couchbase Server apps."  I would think non-JSON documents would be of interest in replicating to/from the shadow bucket.  I tested with an image converted to base64 and added it to the shadow bucket with sync_gateway configured and running with the default sync function.  

Shadow: Reading history of external bucket
Shadow: Doc "base64_replication_test" is not JSON; skipping
Shadow: Caught up with history of external bucket

Is this a limitation in using sync gateway with shadow buckets or am I missing something?  Or is there a more obvious solution to web app + mobile app syncing that I am missing in my limited knowledge of the couchbase suite?

**Comment by ajres** [comment]
@HawaiianBBQ 

Please don't hijack year old closed out tickets, we are less likely to see your post.

Ask questions either on the couchbase mobile [gitter channel](https://gitter.im/couchbase/mobile?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or on the [couchbase forums](forums.couchbase.com).

Sync gateway needs to add metadata to a document when it is replicated from the shadow bucket, so it can't replicate non JSON docs.

If you want to integrate a Web App with Couchbase Mobile, we'd recommend the two following approaches:

1) Your Web App make REST calls directly to the Sync Gateway rest API, Sync Gateway now supports custom map reduce views that you can use in your app as well as CRUD operations and listening to _changes feeds for document revision changes.

2) If you have a requirement for a Web client document cache and full offline operation, you should consider using [pouchdb](http://pouchdb.com) in the Web Client, which will replicate with Sync Gateway. This gives similar functionality to Couchbase Lite for mobile. You will need to build pouted and Sync Gateway from their respective master branches for seamless integration.
