### ISSUE TITLE
Update build_sgw_windows.bat to incorporate rest/api.go -> base/version.go change

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2794]
See https://github.com/couchbase/sync_gateway/issues/2792 for the backstory.  I pushed up a fix for unix, once that gets merged we need to port the fix to the build_sgw_windows.bat script.

**Comment by adamcfraser** [comment]
Included with https://github.com/couchbase/build/commit/ee75d2598ac3e572ccf1222efe01ba1ccdc9a4a9
