### ISSUE TITLE
script for deleting big amounts of documents

### ISSUE THREAD

**Issue by arethasamuel** [couchbase/sync_gateway#2796]
### Sync Gateway version
1.4

### Operating system
Amazon Linux

Can someone provide a script for deleting 1000+ documents? (and having those reflected on the mobile?)

**Comment by adamcfraser** [comment]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests.  You could try this request in the forums.
https://forums.couchbase.com/c/mobile
