### ISSUE TITLE
test_sg_sdk_interop_shared_docs[sync_gateway_default_functional_tests-1-1000] fails with timeout on Jenkins

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2802]
### Sync Gateway version
1.5.0-526.   

### Operating system
CentOS 7.

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://cbs-1.st:8091",
        "data_dir":".",
        "bucket":"data-bucket",
        "username":"data-bucket",
        "password": "password"
    },
    "databases":{
        "db":{
            "unsupported": {
                "enable_extended_attributes": true
            },
            "server":"http://cbs-1.st:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "channel_index":{
                "num_shards":16,
                "server":"http://cbs-1.st:8091",
                "bucket":"index-bucket",
                "username": "index-bucket",
                "password": "password",
                "writer":false
            }
        }
    }
}
```

### Log output
https://gist.github.com/raghusarangapani/16cd7a202ec627dae9bfec1ce05f1bf2

### Steps to reproduce
`pytest -s -k test_sg_sdk_interop_shared_docs --xattrs --mode=di --server-version=5.0.0-3456 --sync-gateway-version=1.5.0-526 testsuites/syncgateway/functional/tests/`

### Expected behavior
Test should pass

### Actual behavior
test_sg_sdk_interop_shared_docs[sync_gateway_default_functional_tests-1-1000] hangs at `Updating: doc_set_one_0 from SDK`. SG uses 100% CPU.

**Comment by adamcfraser** [comment]
@raghusarangapani What build was this test last passing?

**Comment by raghusarangapani** [comment]
It last passed with 1.5.0-514. After this build, the tests weren't run due to https://github.com/couchbase/sync_gateway/issues/2792

**Comment by adamcfraser** [comment]
@raghusarangapani Is this failing in a manual test, or is there a jenkins link you can share?

**Comment by raghusarangapani** [comment]
http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-di/789/console

Test timed out after 12 hours. You won't find the logs as the test got killed by jenkins. I posted a gist of the log I ran in a docker container.

**Comment by adamcfraser** [comment]
What value of number_updates_per_doc_per_client does the test run with?  From your gist, I see a large number of updates (1500+) being made per doc, and no sign of the test blocking.

**Comment by raghusarangapani** [comment]
Its the fourth one: 
'sg_conf_name, number_docs_per_client, number_updates_per_doc_per_client'
('sync_gateway_default_functional_tests', 1, 1000)

The first three pass.

**Comment by adamcfraser** [comment]
Note: QE reporting that test is using 100% CPU when being run locally on Docker.

**Comment by adamcfraser** [comment]
Looking at the logs from the failed test (thanks @raghusarangapani for the details), it looks like there's a CAS failure that ends up in an infinite loop:
https://gist.github.com/adamcfraser/3433b344137689009ecf2a816bf61111

**Comment by adamcfraser** [comment]
May be related to the pending fix here:
https://github.com/couchbase/sync_gateway/pull/2801/files#diff-c6b9f50555be165960fa00d4c360bfe3L1459

**Comment by tleyden** [comment]
I retested against a4a6ad77e871655e36a2f839e66dc47f1e44331a (latest commit on feature/issue_2725) and the test passed.

Test command:

```
./redeploy_docker.sh
./repeat 5 pytest -s --skip-provisioning --xattrs --mode=di --server-version=local-build --sync-gateway-version=1.5.0-524 -k "test_sg_sdk_interop_shared_docs" testsuites/syncgateway/functional/tests/
```

[Output](https://gist.github.com/tleyden/b0462477bc372c11fd17094662ca27e9) 

@raghusarangapani I'm going to proactively close this, but feel free to re-open if you still this issue after https://github.com/couchbase/sync_gateway/pull/2801/files#diff-c6b9f50555be165960fa00d4c360bfe3L1459 is merged.
