### ISSUE TITLE
How to prepeare PR?

### ISSUE THREAD

**Issue by RidgeA** [couchbase/sync_gateway#2811]
Hello!

I'm going to add new feature to sync_gateway - event handler to publish changes directly into RabbitMQ.
This feature will be usefull in my current project and I'd like to share it with community :-).
(Yes, I know that it is poosble to implement it via webhook, but it will require additional http listener and lead to increase network interaction ...)

I'm new in contributing into OSS and have questions about prepearing this PR:
0. Do you have some contributing guides to prepeare PR?
1. I should make separate branch named 'feature/....' or fork the project ?
2. How to test integration with RabbitMQ server ?
3. How to add new dependencies intoproject (I a little bit confused with 'manifest/*.xml' files....)

Thanks!

**Comment by tleyden** [comment]
Hey @RidgeA, this sounds exciting!  I think step 1 is that you should file an issue clearly stating the problem and your proposed solution.  We can discuss if it makes sense to have this tightly coupled with Sync Gateway, or to have it more loosely coupled with a changes event worker (and possibly short-circuiting the networking stack)

I do think it's a common problem though, and a lot of users would be interested in this.  This issue has come up before.

**Comment by RidgeA** [comment]
Thanks!
I'v created new issue to discuss this feature: https://github.com/couchbase/sync_gateway/issues/2813
