### ISSUE TITLE
Gateway fails to sync after 1 million docs

### ISSUE THREAD

**Issue by gateixeira** [couchbase/sync_gateway#2814]
### Sync Gateway version
1.5.0-377_x86_64 Enterprise 

### Couchbase Server version
5.0.0 build 2873 Enterprise

### Operating system
centos7

### Config file
```
{
  "log": ["HTTP+"],
  "adminInterface":":4985",
  "interface": ":4984",
  "databases": {
    "data": {
      "server": "http://172.16.20.141:8091",
      "bucket": "data",
      "username": "sync-gateway",
      "password": "sync-gateway",
      "unsupported": {
          "enable_extended_attributes": true
      },
      "import_docs": "continuous",
      "users": {
          "GUEST": {"disabled": false, "admin_channels": ["*"] }
      },
      "sync": `function(doc, oldDoc) {
        channel(doc.channels);
      }`
    }
  }
}
```
### Log output
WARNING: Unable to import doc "PRICE_250_12345" - external update will not be accessible via Sync Gateway.  Reason: unexpected end of JSON input -- db.(*changeCache).DocChanged.func1() at change_cache.go:354

### Expected behavior
Sync gateway should be able to make data available for query and later sync with mobile but an unmarshall error happens instead after 1 million documents. 

### Actual behavior
![error2](https://user-images.githubusercontent.com/4645845/29363671-3156056c-8291-11e7-8f4b-ef81b7fd4616.JPG)

### Steps to reproduce

See https://github.com/couchbase/sync_gateway/issues/2814#issuecomment-322866712

1.  Config bucket in Couchbase Server
2.  Turn on sync gateway
3.  Start adding data to Couchbase Server, through Sync Gateway with POST to public API
4. Error appears in the document number 1 million and unmarshall keeps failing from then on with uint64 error

### Details/Questions
- Sync gateway running as containerized application
- Is 1 million a limitation in terms of number of documents that can be made available via Sync Gateway?
- Less than 1 million documents need to be synced to Couchbase Mobile, however, many endpoints will need to access the same gateway, which will have to make more than 1 million available.

**Comment by tleyden** [comment]
Thanks for the excellent bug report @gateixeira 

One thing that would be really helpful would be to capture the HTTP request that is paired with the `{"error": "Bad Reqeust"}` response.  There are several tools to help with this, including `ngrep`, `tcpdump`, `wireshark`, or httpscoop (OSX only).  

Or if you are directly sending POST requests, rather than capturing on the wire, include the CLI command or code snippet you are using for the request that causes the `{"error": "Bad Reqeust"}` response to be returned.  Please include all parameters. 

Another helpful debug angle: if you can enable the `*` log key and rerun, it would be useful to see the sync gateway logs directly before the failure.

**Comment by adamcfraser** [comment]
@tleyden It looks like there's a scenario where we're the sequence is being incorrectly marshalled using floating point notation.  Need to review whether what's changed in 1.5 - whether it's the fact we're writing to xattrs, or just gocb in general.  Should be straightforward to repro by modifying _sync:seq.

**Comment by gateixeira** [comment]
Thanks for the prompt reply.

@tleyden:
It's worth mentioning that the document shows up in Couchbase Server after the post, as it had been successfully created. 
However, sync-gateway seems not to be able to handle it anymore

Code snippet:
```
String url = "http://172.16.20.88:4984/data/";

HttpClient client = new DefaultHttpClient();
StringEntity requestEntity = new StringEntity(object, ContentType.APPLICATION_JSON);
HttpPost postMethod = new HttpPost(url);
postMethod.setEntity(requestEntity);

HttpResponse response = client.execute(postMethod);
```

Where _object_ is my json.

This post results in the following from ngrep (omitted the json due to sensitive info :):

`POST /data/ HTTP/1.1..Content-Length: 352..Content-Type: application/json; charset=UTF-8..Host: 172.16.20.88:4984..Connection: Keep-Alive..User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_111)....{<json object>} `

And the GET from public API via chrome:
```
GET /data/PRICE_250_12345 HTTP/1.1..Host: 172.16.20.88:4984..Connection: keep-alive..Upgrade-Insecure-Requests: 1..User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071
  .86 Safari/537.36..Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8..Accept-Encoding: gzip, deflate..Accept-Language: en-US;q=0.6,en;q=0.4..Cookie: <SESSIONIDs>
```

I'm afraid  **"log": ["*"]** didn't really made a difference cause I had already "HTTP+" activated

**Comment by tleyden** [comment]
I ran into an issue with json numbers where they are handled differently on go 1.7 vs go 1.8.  Wonder if it's related

Golang nuts thread: https://groups.google.com/forum/#!msg/golang-nuts/9SaVxumSc-Y/rNAI8R7_BAAJ

**Comment by tleyden** [comment]
Interesting to note that in my test program the number in question is > 1m

https://play.golang.org/p/2guVNJLE87

I have a feeling that changing that to a smaller number would cause it to print in decimal format rather than e notation format

**Comment by gateixeira** [comment]
@tleyden Changed your code to do it the other way around and it looks like the error I'm running into (maybe a mistake, not someone familiar with Go here):
With: 
_ID *uint64
"id":1e+06_

```
2009/11/10 23:00:00 json.Unmarshal() + json.Marshal(): {
    "Doc": {
        "GithubUsers": [
            {
                "id": 1000000,
                "type": "User"
            }
        ],
        "_id": "github_users_default"
    }
}
2009/11/10 23:00:00 The id field was changed to floating point format
2009/11/10 23:00:00 json.Decode() + json.Marshal(): {
    "Doc": {
        "GithubUsers": [
            {
                "id": 1e+06,
                "type": "User"
            }
        ],
        "_id": "github_users_default"
    }
}
2009/11/10 23:00:00 Couldn't unmarshal into github user object: json: cannot unmarshal number 1e+06 into Go struct field User.id of type uint64
```

**Comment by tleyden** [comment]
The SG dev team is actively digging into this.  Great catch!!

**Comment by tleyden** [comment]
@gateixeira one thing that doesn't make sense is that the failure apparently happens on import, however you are only doing writes via Sync Gateway.  Are you sure there are no SDK updates as well?

Any chance you can give exact steps to repro including commands or scripts?

**Comment by tleyden** [comment]
Also if you are able to, please hop into [gitter](https://gitter.im/couchbase/discuss) and ping me (@tleyden) and we can chat in realtime

**Comment by gateixeira** [comment]
@tleyden yes, when the error happened, Sync Gateway was the only entry point for writings. I will ping you in gitter

**Comment by tleyden** [comment]
## Repro steps

1. Run Centos7
1. Install http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.5.0/1.5.0-377/couchbase-sync-gateway-enterprise_1.5.0-377_x86_64.rpm
1. Start SG
1. Set _sync:seq to 999999
1. Restart SG
1. Write a couple of docs via Couchbase Server Admin UI
1. Look for errors:
   - in the logs
   - when doing a GET
   - when calling _changes

**Comment by gateixeira** [comment]
Step 5 might have happened since it's a dockerized env. Step 6 I don't think happened in my case

**Comment by tleyden** [comment]
On the first attempt to repro with the 533 build, after I set _sync:seq to 999999, I'm seeing this error restarting SG

```
2017-08-16T19:09:23.665Z GoCBCustomSGTranscoder Opening Couchbase database db on <http://s61903cnt72.sc.couchbase.com:8091> as user "db"
2017-08-16T19:09:29.769Z FATAL: Error opening database: Error retrieving stats-vbseqno - DCP not supported -- rest.RunServer() at config.go:764
```

Still looking into it, but it might be due to running an older version of Couchbase Server (Community Edition 5.0.0 build 3193)

**Comment by tleyden** [comment]
I upgraded to Couchbase Server Enterprise Edition 5.0.0 build 3490, and now things are working correctly with the steps in https://github.com/couchbase/sync_gateway/issues/2814#issuecomment-322866712, but replacing the Sync Gateway version with http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.5.0/1.5.0-533/couchbase-sync-gateway-community_1.5.0-533_x86_64.rpm

Sg logs:

```
[root@debe4398e205 ~]# sync_gateway sync_gw_config.json
2017-08-16T19:20:42.196Z Enabling logging: [HTTP+]
2017-08-16T19:20:42.196Z ==== Couchbase Sync Gateway/1.5.0(533;96208d5) ====
2017-08-16T19:20:42.196Z requestedSoftFDLimit < currentSoftFdLimit (5000 < 1048576) no action needed
2017-08-16T19:20:42.196Z Opening db /data as bucket "db", pool "default", server <http://s61903cnt72.sc.couchbase.com:8091>
2017-08-16T19:20:42.196Z GoCBCustomSGTranscoder Opening Couchbase database db on <http://s61903cnt72.sc.couchbase.com:8091> as user "db"
2017-08-16T19:20:47.220Z Importing documents...
2017-08-16T19:20:47.779Z Re-running sync function on all 0 documents...
2017-08-16T19:20:47.779Z Finished re-running sync function; 0 docs changed
_time=2017-08-16T19:20:48.318+00:00 _level=INFO _msg=Using plain authentication for user db
2017-08-16T19:20:48.792Z     Reset guest user to config
2017-08-16T19:20:48.792Z Starting admin server on :4985
2017-08-16T19:20:48.795Z Starting server on :4984 ...
2017-08-16T19:21:00.592Z WARNING: changeCache: Doc "doc1" does not have valid sync data. -- db.(*changeCache).DocChangedSynchronous() at change_cache.go:409
2017-08-16T19:21:14.569Z WARNING: changeCache: Doc "doc2" does not have valid sync data. -- db.(*changeCache).DocChangedSynchronous() at change_cache.go:409
2017-08-16T19:21:38.432Z HTTP:  #001: GET /data/doc1  (ADMIN)
2017-08-16T19:21:38.601Z HTTP+: #001:     --> 200   (169.5 ms)
2017-08-16T19:21:44.647Z HTTP:  #002: GET /data/_raw/doc1  (ADMIN)
2017-08-16T19:21:44.815Z HTTP+: #002:     --> 200   (169.0 ms)
```

Curl responses:

```
$ curl -X GET   http://localhost:4985/data/doc1   -H 'authorization: Basic Zm9vOmZvbw=='   -H 'cache-control: no-cache'   -H 'content-type: application/json'   -H 'postman-token: ccbe4e97-6e2a-bd06-4596-e8f60e1e0920'   -d '{
  "key": "val"
}' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   142  100   124  100    18    582     84 --:--:-- --:--:-- --:--:--   584
{
  "_id": "doc1",
  "_rev": "1-f97ffb79945badf2fc8f7708ddbf6667",
  "click": "to edit",
  "with JSON": "there are no reserved field names"
}
```

```
$ curl -X GET   http://localhost:4985/data/_raw/doc1   -H 'authorization: Basic Zm9vOmZvbw=='   -H 'cache-control: no-cache'   -H 'content-type: application/json'   -H 'postman-token: ccbe4e97-6e2a-bd06-4596-e8f60e1e0920'   -d '{
  "key": "val"
}' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   332  100   314  100    18   1708     97 --:--:-- --:--:-- --:--:--  1715
{
  "_sync": {
    "rev": "1-f97ffb79945badf2fc8f7708ddbf6667",
    "sequence": 1000001,
    "recent_sequences": [
      1000001
    ],
    "history": {
      "revs": [
        "1-f97ffb79945badf2fc8f7708ddbf6667"
      ],
      "parents": [
        -1
      ],
      "channels": [
        null
      ]
    },
    "cas": "",
    "time_saved": "2017-08-16T19:21:01.134574681Z"
  },
  "click": "to edit",
  "with JSON": "there are no reserved field names"
}
```

**Comment by tleyden** [comment]
@gateixeira can you try to repro with http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.5.0/1.5.0-533/couchbase-sync-gateway-community_1.5.0-533_x86_64.rpm and report your results here?

**Comment by tleyden** [comment]
Was using wrong config.

Retesting w/ 

```
{
  "log": ["HTTP+"],
  "adminInterface":":4985",
  "interface": ":4984",
  "databases": {
    "data": {
      "server": "http://localhost:8091",
      "bucket": "db",
      "password": "password",
      "enable_shared_bucket_access": true,
      "import_docs": "continuous",
      "users": {
          "GUEST": {"disabled": false, "admin_channels": ["*"] }
      },
      "sync": `function(doc, oldDoc) {
        channel(doc.channels);
      }`
    }
  }
}
```

**Comment by gateixeira** [comment]
@tleyden it seems to be working fine with the new version. I'm running some other tests but no problems so far. Thanks for the effort!
