### ISSUE TITLE
Session 10% update not converting to correct TTL for CB Expiry

### ISSUE THREAD

**Issue by wilsondy** [couchbase/sync_gateway#2824]
### Sync Gateway version
we're on 1.3.1 but looks like its still on master

### Operating system
Windows

### Config file
```NA```

### Example Session Document
{
  "id": "01fd1df870578b01b5ba405c5b4f4a9812738fdb",
  "username": "VEZXgpKrK66IsQ",
  "expiration": "2018-01-26T05:04:35.4754797Z",
  "ttl": 15780000000000000
}

### Log output
NA

### Expected behavior
A long TTL session is maintained for the full length of the term.  We are using 6 month sessions.

### Actual behavior
(I think) At 10% of total TTL, the session document is destroyed.

### Steps to reproduce
https://github.com/couchbase/sync_gateway/blob/master/auth/session.go#L61 doesn't convert the ttl to account for the duality in the CB expiry values while Line 88 shows what I think would be the correct usage.

**Comment by adamcfraser** [comment]
@ajres Can you review - if the session is actually being destroyed (and not just failing to expire), fix and get a unit test to repro/validate.

**Comment by ajres** [comment]
I have fixed the issue with the CBS document ttl not being set correctly on session update.

**Comment by ajres** [comment]
It looks like this issue would only manifest for sessions over 30 days, as these switch to using UNIX epoch time for the CBS document expiry. I'm not sure how to validate this in a unit test.
