### ISSUE TITLE
API /db/_all_docs returns wrong number of rows

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#2837]
### Sync Gateway version
1.5.0-538

### Operating system
RHEL69

### Config file
```{
    "out.stdout": {
        "adminInterface": "0.0.0.0:4985", 
        "compressResponses": false, 
        "databases": {
            "db": {
                "bucket": "data-bucket", 
                "offline": false, 
                "password": "password", 
                "server": "http://172.23.106.160:8091", 
                "username": "data-bucket"
            }
        }, 
        "interface": ":4984", 
        "log": [
            "CRUD+", 
            "Cache+", 
            "HTTP+", 
            "Changes+"
        ], 
        "maxCouchbaseConnections": 16, 
        "maxFileDescriptors": 90000, 
        "maxIncomingConnections": 0, 
        "slowServerCallWarningThreshold": 500, 
        "verbose": "true"
    }
}
```

### Log output
http://uberjenkins.sc.couchbase.com/job/rhel69-sync-gateway-functional-tests-base-cc-EXPERIMENTAL/8/
Under build artifacts .Click on the link
test_offline_false_config_rest[bucket_online_offline-bucket_online_offline_offline_false-100]-2017-08-22-02-35-52-sglogs.zip

### Expected behavior
It should get 300 rows 

### Actual behavior
It is getting 490 rows

### Steps to reproduce
1.  Run the test : test_db_online_offline.test_offline_false_config_rest
with mode cc, on RC build 1.5.0-538 
CBS - 5.5.0-3497 
xattrs false

**Comment by adamcfraser** [comment]
@sridevi-15 Can you provide information on what the all_docs query is returning (vs. expected)?

**Comment by sridevi-15** [comment]
@adamcfraser , I could not able to run on RHEL7 as I do not have VM to run. I looked at the test and this is what it is doing : 
1. This test verify rest apis on db.
2. It create users, roles
3. It create docs : 
    post call to create one doc at a time with doc name -> 100 docs
    Rest call for bulk docs -> 100 docs
    Rest call to create again one doc at a time without name -> 100 docs
4. Do rest call /db/_all_docs is returning 490 rows, but expected rows are 300

Once Jenkins RHEL 7 VMs are free , I will try to run individually and locally and see if test passes

**Comment by sridevi-15** [comment]
Ran it on Jenkins RHEL VMS locally and test has passed without issues. So, closing the ticket
