### ISSUE TITLE
Key error on the test test_online_to_offline_changes_feed_controlled_close_continuous

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#2838]
### Sync Gateway version
1.5.0-538

### Operating system
RHEL69

### Config file
```{
    "out.stdout": {
        "adminInterface": "0.0.0.0:4985", 
        "compressResponses": false, 
        "databases": {
            "db": {
                "bucket": "data-bucket", 
                "password": "password", 
                "server": "http://172.23.106.160:8091", 
                "username": "data-bucket"
            }
        }, 
        "interface": ":4984", 
        "log": [
            "CRUD+", 
            "Cache+", 
            "HTTP+", 
            "Changes+"
        ], 
        "maxCouchbaseConnections": 16, 
        "maxFileDescriptors": 90000, 
        "maxIncomingConnections": 0, 
        "slowServerCallWarningThreshold": 500, 
        "verbose": "true"
    }
}

```

### Log output
http://uberjenkins.sc.couchbase.com/job/rhel69-sync-gateway-functional-tests-base-cc-EXPERIMENTAL/8/
Under build Artifacts, look for below text and click on it

test_online_to_offline_changes_feed_controlled_close_continuous[bucket_online_offline-bucket_online_offline_default-5000]-2017-08-22-02-38-27-sglogs.zip

### Expected behavior
It should find matching id for rev on expected results

### Actual behavior
It fails with Key error while comparing rev with id on expected results

### Steps to reproduce
1.  Run test_online_to_offline_changes_feed_controlled_close_continuous
with xattrs false
CBS = 5.0.0-3497
mode = cc
pytest -s -k test_online_to_offline_changes_feed_controlled_close_continuous --ci --mode=cc --server-version=5.0.0-3497 --sync-gateway-version=1.5.0-538 testsuites/syncgateway/functional/tests/

**Comment by adamcfraser** [comment]
'Key Error' is test output, and doesn't provide much insight into what's failing from a Sync Gateway perspective.  

There's nothing in the test output to indicate what the expected vs. actual was for the rev.  Looking at the Sync Gateway logs there's only a single entry for that key in the entire logs, so it doesn't shed much light on the situation.

Can we get details on this ticket showing:
 - what operations the test performed on the doc
 - what the expected rev was for the doc
 - what the actual rev was for the doc

**Comment by sridevi-15** [comment]
I used Jenkins Vms for testing on Rhel and ran it locally. Test has passed, so closing the ticket
