### ISSUE TITLE
Internal server error while accessing :4985/db/_user/dj_0

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#2839]
### Sync Gateway version
1.5.0-538

### Operating system
RHEL69

### Log output
http://uberjenkins.sc.couchbase.com/job/rhel69-sync-gateway-functional-tests-base-cc-EXPERIMENTAL/8/
Under build Artifacts, look for below text and click on it

test_sync_sanity_backfill[custom_sync-sync_gateway_custom_sync_one]-2017-08-22-04-09-24-sglogs.zip

### Expected behavior
:4985/db/_user/dj_0 should be accessible 

### Actual behavior
seeing internal server error while accessing :4985/db/_user/dj_0

### Steps to reproduce
1.  Run test_sync_sanity_backfill 
with mode=cc, xattrs=false
CBS=5.0.0-3497

pytest -s -k test_sync_sanity --ci --mode=cc --server-version=5.0.0-3497 --sync-gateway-version=1.5.0-538 testsuites/syncgateway/functional/tests/

**Comment by adamcfraser** [comment]
This specific 500 error:
```
500 Internal error: not_found - Design document _design/sync_gateway_access not found 
```
indicates that the views created by Sync Gateway haven't completed installation before you issued the user creation call.  This should be handled by the test w/ retry handling.  It's also unexpected that the test attempts to create a user before doing the GET to see if SG is running - that may be related to the race in this particular test. 

Filed a longer-term enhancement to have SG block startup until design docs are deployed (https://github.com/couchbase/sync_gateway/issues/2840), but that's not something needed for 1.5.
