### ISSUE TITLE
Update handling of changeEvents for principal docs

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2842]
Currently changeEvents for principal (_user/_role) docs results in entries in the changes feed on the ADMIN REST API. This is because the principal docs are added to the * channel.

This behaviour has been in SG codebase since 1.0.3.

But the entry in the changes feed gives no indication as to the state change of the event i.e. created/updated/deleted. 

The output on the changes feed always has the ame format:

`{"seq":24,"id":"_user/SyncGW1C3","changes":[{"rev":""}]}` 

This means these entries offer little to no value, it proposed to remove these entries in 2.0.

Internally the changeEvents still need to be processed e.g. for late sequence check.

**Comment by adamcfraser** [comment]
Closing based on age.
