### ISSUE TITLE
Compute expvars for caching latency

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2846]
Currently collecting round-trip latency stats (from write to read over the changes feed) requires calculations to be done by the load generator.  

Computing aggregate (non-histogram) stats for caching time and exposing as expvar would make it easier to track this KPI.

**Comment by djpongh** [comment]
timebox work to a 3.

**Comment by adamcfraser** [comment]
Updated timing stats have been included in Iridium stats overhaul.
