### ISSUE TITLE
Remove legacy import handling in assimilator.go

### ISSUE THREAD

**Issue by tahmmee** [couchbase/sync_gateway#2854]
### Sync Gateway version
1.5.0-538

### Operating system
CentOS 7.2

### Config file
```javascript
{
  "log":[
    "*",
    "Import+"
  ],
  "databases":{
    "db":{
      "users":{
        "GUEST":{
          "disabled":false,
          "admin_channels":[
            "*"
          ]
        },
        "testuser":{
          "admin_channels":[
            "ch_testuser"
          ],
          "password":"ch_password"
        }
      },
      "server": "http://Administrator:password@172.23.108.103:8091",
      "bucket":"default",
      "password":"password",
      "import_docs":"continuous",
      "unsupported":{
        "enable_extended_attributes":true,
        "replicator_2":true
      }
    }
  }
}
```

### Log output
https://gist.github.com/tahmmee/7b5b1be3fb932127877392f194c881d6

### Expected behavior
Expected Gateway to start.

### Actual behavior
Panic occurs

### Steps to reproduce
1.  Start the sg against default bucket
2.  Run the mobile testkit's dotnet container against the gateway
3.  Run background loaders with binary & json docs against same default bucket
4.  Loop step #2 for ~4 days
5.  Stop sync gateway and try to start again

* Note the reason for step 5 was that I noticed somehow we had 3 instances of the gateway running against the bucket.

**Comment by adamcfraser** [comment]
It looks like the config used for this test has the obsolete parameter used for xattrs (unsupported/enabled_extended_attributes), and Sync Gateway is panicking during the legacy import handling (based on data passed from assimilator.go).  It still merits cleaner handling, but I don't think this would be a common configuration.

**Comment by tahmmee** [comment]
Thanks Adam, changed to **enable_shared_bucket_access** and it works now
```javascript
      "enable_shared_bucket_access": true,
      "unsupported": {
            "replicator_2": true
       }
```

**Comment by adamcfraser** [comment]
Should avoid panic during legacy import - targeted for 2.0.

**Comment by adamcfraser** [comment]
We can remove the legacy import handling, as it's been superseded by the mobile convergence handling.
