### ISSUE TITLE
Revision tree repair tool

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2857]
To repair the revision trees with cycles caused by https://github.com/couchbase/sync_gateway/issues/2847

- [x] Dry run mode
- [x] Call Import View to walk keys (UpdateAllDocChannels) -- current doc path
- [x] Cas safe write if identified changes
- [x] Instructions: Take bucket offline, do changes, then restart.  Solves stale revcache issue.
- [x] Wire up to endpoint

## Instructions

See https://github.com/couchbase/sync_gateway/wiki/Issue-2857-Repair-Tool

## Test Instructions

- Run Couchbase Server 4.x, with empty `data-bucket` bucket
- Run Sync Gateway with [this config](https://gist.github.com/tleyden/935ffaa7b4c82703f50ea3f89d8bb402)
- `wget https://gist.githubusercontent.com/tleyden/bc4d9cae6ac8bfe408c373e673ff58e9/raw/659700bc6287ed44cdd8158a9e8a82a33cb80e08/data_for_test`
- `cbc cp data_for_test -U couchbase://localhost/data-bucket`
- Verify that the doc has cycles in revtree by running `curl http://{{host}}:{{port_admin}}/{{db}}/data_for_test?revs=true` and looking for `"reason": "Internal error: getHistory found cycle in revision tree`
- Repair the bucket via the [instructions](https://github.com/couchbase/sync_gateway/wiki/Issue-2857-Repair-Tool)

**Comment by tleyden** [comment]
Work in progress at: https://github.com/couchbase/sync_gateway/tree/feature/issue_2847_repair_tool

**Comment by tleyden** [comment]
```
POST /_repair
{
  dry_run: true
  revTreeCycle: {}
}


```

**Comment by tleyden** [comment]
@adamcfraser here's what I have so far:

https://github.com/couchbase/sync_gateway/compare/release/1.3.1.3...feature/issue_2847_repair_tool

Can you take a quick pass to make sure we're on the same page?  In particular the [RepairBucket](https://github.com/couchbase/sync_gateway/compare/release/1.3.1.3...feature/issue_2847_repair_tool#diff-1266d96386cbb28ff091c720476035e0R37) method

What's still pending:

- Cas safe write if identified changes
- Get doc to refresh rev cache (or drop rev cache)
- Wire up to endpoint

**Comment by ArihantRk** [comment]
@tleyden I went through https://github.com/couchbase/sync_gateway/issues/2847 about dangling parent.

I am more interested in identifying documents have revision tree issues.
please let us know the working of repair tool. will it apply on all documents or documents having issues.
how do we know a document has issue and it can be repaired by this tool.

**Comment by tleyden** [comment]
@ArihantRk the docs are here: https://github.com/couchbase/sync_gateway/wiki/Issue-2857-Repair-Tool

If you do a dry run, it will show you which docs it would repair (but not actually make any changes)

**Comment by adamcfraser** [comment]
@ArihantRk The tool is only intended to be used in conjunction with data affected by a specific maintenance patches, and only if that data can't be otherwise rolled back.  It's not intended for general detection of 'revision tree issues'.  If you feel like you're in a situation that requires this tool, you should review w/ support.
