### ISSUE TITLE
[enhance] get rev info via N1QL when using XAtrr

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#2862]
query rev info via N1QL is necessary for the application who use N1QL and SG both. for example, web application can use N1QL to query data include rev info,and then web application can update document via SG REST API with rev info.

**Comment by adamcfraser** [comment]
When using extended attributes, you do have the option to just update the document using the SDK (and not the SG REST API), and allow Sync Gateway's import processing to create the new revision.  

There are a few ways this differs from a SG write:
- oldDoc will be empty when the SDK write is imported
- The document is imported as admin (so require-style write security isn't applied)
- the new write will be a child of the active revision (no option to create a child of a non-active rev)
- latency between SDK write and SG import

I'd be interested to hear which of these differences (or if there are other reasons) make writing through the SDK not feasible for your scenario, to help evaluate whether exposing the rev id through N1QL is the only (or the ideal) solution.

**Comment by rajagp** [comment]
Also, from Forums discussion - https://forums.couchbase.com/t/can-sync-gateway-channels-be-used-in-couchbase-server/13923/8, it appears that access to channel metadata may be something that may be useful to retrieve via N1QL.

**Comment by atom992** [comment]
the important part is require-style write security isn't applied. when update document by SG or Mobile,it is important to make sure the write security.

The another question is when we use XAtrr with XDCR in Couchbase Server,can XAtrr info sync by XDCR?

**Comment by tleyden** [comment]
@atom992 good question.  I'm assuming it can, but I think it's worth confirming by asking on forums.couchbase.com and mentioning System XATTRS specifically.

**Comment by adamcfraser** [comment]
XATTR support in N1QL is currently planned for an upcoming Couchbase Server release - there isn't a Sync Gateway deliverable associated with it.
