### ISSUE TITLE
Document the _expvars available variables and their meaning

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2864]
Sync Gateway ADMIN REST API provides a `/_expvars` endpoint to return runtime stats.

The endpoint is documented but not the variables and their meaning that are returned in the response.

Should we document these to make it easier for devs to integrate these stats into their monitoring systems?

**Comment by jamescooke** [comment]
Working with sync gateway instances in production and working on bottlenecks, it would be great to have more information about these stats. Even a couple of words on the wiki page (https://github.com/couchbase/sync_gateway/wiki/expvars) covering some of the stats that don't appear in that list would be super helpful. At the moment we are monitoring some of these numbers and looking for correlations with slow performance on mobile clients and the stats.

**Comment by tleyden** [comment]
@jamescooke thanks for the feedback.  Any in particular you want to highlight that would be most interesting to document.

/cc @jamiltz

**Comment by adamcfraser** [comment]
Covered by https://issues.couchbase.com/browse/DOC-2920.
