### ISSUE TITLE
/{db}/_user/{username} endpoint doesn't handle urlencoded usernames correctly

### ISSUE THREAD

**Issue by saschwarz** [couchbase/sync_gateway#2870]
### Sync Gateway version  
1.4.1

### Operating system
Linux

### Config file
```javascript
```

### Log output
```
2017-08-31T23:17:36.348Z HTTP:  #2135: GET /db/_user/acm_auth0%7C592b99c46b81fe5bad864ad0  (ADMIN)
2017-08-31T23:17:36.350Z HTTP: #2135:     --> 404 missing  (2.1 ms)
2017-08-31T23:18:40.287Z HTTP:  #2137: GET /db/_user/acm_auth0%257C592b99c46b81fe5bad864ad0  (ADMIN)
2017-08-31T23:18:40.289Z HTTP+: #2137:     --> 200   (2.2 ms)
```
### Expected behavior
What should have happened?
The details for the registered user should be returned by the API.

### Actual behavior
What actually happened?
A `not_found` response is returned.

### Steps to reproduce
1.  Create a user with an encoded '|' in it's username i.e. `acm_auth0%7C592b99c46b81fe5bad864ad0`
2.  Query for all users via _user endpoint: `http://localhost:4985/db/_user/`
```
[
     "acm_auth0%7C592b99c46b81fe5bad864ad0"
]
```
3.  Query for that user returns "not found" "missing": `http://localhost:4985/db/_user/acm_auth0%7C592b99c46b81fe5bad864ad0`:
```
{
    error: "not_found",
    reason: "missing"
}
```
4 However, urlencoding the username again and querying for that user does return the information
`http://localhost:4985:/db/_user/acm_auth0%257C592b99c46b81fe5bad864ad0`:
```
{
    name: "acm_auth0%7C592b99c46b81fe5bad864ad0",
    all_channels: [
    "!"
    ],
    email: "tester@example.com"
}
```

Forum discussion: https://forums.couchbase.com/t/inspecting-user-role-channels-user-not-found/14012

**Comment by ajres** [comment]
We handle URL encoded '/' characters in document names and attachment names. We do this by defining specific regex patterns in the http router.

We can't use the same approach here as these _user names appear as though they can contain any escaped characters.

@saschwarz are there a limited subset of encoded characters in your use case or can it be any of the set of special characters?

**Comment by saschwarz** [comment]
I'd think in general there could be any encoded characters so to be safe using a general URL decoding algorithm may be necessary. 

In my scenario the username is being generated and encoded by SyncGW/Couchbase when the user is authenticated by a third party (Auth0 in this case). Auth0 prepends the social network to the username with an '|' so as long as I continue to use them for auth I should only see that character.
