### ISSUE TITLE
Include notification error information when sg-replicate replication aborted

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2875]
When an [sg-replicate replication is aborted ](https://github.com/couchbaselabs/sg-replicate/blob/master/synctube.go#L101), error information included in the replication notification (ReplicationNotification.error) is not being logged/returned.  This should either be logged at the time, or included in the returned error.

## Action items

- [x] Merge https://github.com/couchbaselabs/sg-replicate/pull/53
- [x] Create SG PR on dev branch that updates the manifest to point to this sg-replicate commit

**Comment by tleyden** [comment]
Will make debugging issues such as https://github.com/couchbase/sync_gateway/issues/2884 easier

**Comment by adamcfraser** [comment]
Done.
