### ISSUE TITLE
Sync-gateway doesn't sync counters and boolean jsons.

### ISSUE THREAD

**Issue by bharath-gp** [couchbase/sync_gateway#2877]
### Sync Gateway version
1.5.0-555
### Operating system
Centos

### Config file
{
  "interface":":4984",
  "log": ["*"],
  "databases": {
    "travel-sample": {
      "import_docs": "continuous",
      "enable_shared_bucket_access": true,
      "unsupported": {
        "replicator_2":true
      },
      "bucket":"travel-sample",
      "server": "http://localhost:8091",
      "username": "test",
      "password": "password",
      "users":{
        "test": {"password": "password", "admin_channels": ["*"]},
        "demo": {"password": "password"},
        "tester": {"password": "password"},
        "GUEST": { "disabled": false, "admin_channels": ["*"] }
      }
    }

### Log output
2017-09-06T08:40:43.600Z Import: Unmarshal error during importDoc json: cannot unmarshal bool into Go value of type db.Body
2017-09-06T08:40:43.600Z WARNING: Unable to import doc "boolean_test" - external update will not be accessible via Sync Gateway.  Reason: json: cannot unmarshal bool into Go value of type db.Body -- db.(*changeCache).DocChangedSynchronous() at change_cache.go:394
2017-09-06T08:57:35.094Z Cache+: Unable to unmarshal sync metadata for feed document "counter1".  Will not be included in channel cache.  Error: json: cannot unmarshal number into Go value of type db.documentRoot

### Expected behavior
Mobile sync to sync even counters and boolean jsons like normal json documents.

### Actual behavior
Sync gateway doesn't sync counters and boolean documents. If a json document is changed to counter or boolean, then we show warning to user in sync gateway logs.

### Steps to reproduce
1.  Create a bucket in 5.0 CB cluster and connect it to mobile sync 1.5
2.  Create a counter document (only a numerical value in the document) or boolean document
3.  Check the mobile sync logs to check if the document was synced. 

I created counters using cbc-incr tool and by creating a document using python SDK and the sync gateway didn't detect the newly created document. If I changed a different json to a counter, then got a warning  Error: json: cannot unmarshal number into Go value of type db.documentRoot.  Similar error is seen while creating a boolean document (document with only a boolean value of true or false).

**Comment by adamcfraser** [comment]
This is the expected behaviour - Sync Gateway doesn't currently support replication of counters or boolean values - primarily because there's insufficient information in the document to compute security.

**Comment by tleyden** [comment]
@jamiltz this might be worth mentioning in the docs.
