### ISSUE TITLE
Attachment disappears after document is updated

### ISSUE THREAD

**Issue by sirtopp** [couchbase/sync_gateway#2878]
Document that has been updated loses it's attachments.

### Sync Gateway version
Couchbase Sync Gateway/1.4.1(3;ddffd85)

### Operating system
Ubuntu 16.10 (dockerized)

### Expected behavior
I would expect attachments to stay with the document after document is updated since attachment is a separate being in the database than a document.

### Actual behavior
Attachment is missing after document's properties were changed.

### Steps to reproduce
1. Put a new doc to DB (PUT /db/docWithAttachments)
2. Add and attachment (PUT /db/docWithAttachments/someAttachment)
3. So far the doc looks ok:
```
{
    "_attachments": {
        "someAttachment": {
            "content_type": "application/json",
            "digest": "sha1-CJ7Bt+S2GkbSMZVNk0Xg2DlYZ0g=",
            "length": 37,
            "revpos": 2,
            "stub": true
        }
    },
    "_id": "docWithAttachments",
    "_rev": "2-46328697ce3d2664e00114ee56fec192",
    "iAm": "a doc and i haz attachmentz"
}
```
4. Make an update to document: `PUT /doc/docWithAttatchments`
```
{
    "_id": "docWithAttachments",
    "_rev": "2-46328697ce3d2664e00114ee56fec192",
    "iAm": "a doc and i haz attachmentz -- just got updated"
}
```
5. The attachments are gone: `GET /db/docWithAttachments` returns
```
{
    "_id": "docWithAttachments",
    "_rev": "2-46328697ce3d2664e00114ee56fec192",
    "iAm": "a doc and i haz attachmentz -- just got updated"
}
```
 regardless of `attachments` or `atts_since` query params. They are also missing from the underlying Couchbase document:
```
{
  "_sync": {
    "rev": "3-ce951c2f7aa6d62ccb517612fa7a9ed2",
    "sequence": 4418,
    "recent_sequences": [
      4416,
      4417,
      4418
    ],
    "history": {
      "revs": [
        "2-46328697ce3d2664e00114ee56fec192",
        "3-ce951c2f7aa6d62ccb517612fa7a9ed2",
        "1-06c9d9c5c619abc26be1c7e5aa2a0445"
      ],
      "parents": [
        2,
        0,
        -1
      ],
      "channels": [
        null,
        null,
        null
      ]
    },
    "time_saved": "2017-09-06T07:19:05.181556911Z"
  },
  "iAm": "a doc and i haz attachmentz -- just got updated"
}
```

**Comment by adamcfraser** [comment]
Although it's correct to say that the attachment is stored as a separate entity in the database, the `_attachments` property in the document defines the relationship between the document and the attachment.  If that relationship information is removed from the document, as you've done with an update, it's expected that the attachment is no longer associated with that document.

It's functionally equivalent to a foreign key reference in the document body - if you remove that reference, the relationship no longer exists.

The attachment API (`PUT /db/doc/attachment`) provides a more user-friendly way of initially generating the attachment metadata, but subsequent updates to the document are responsible for maintaining that metadata.
