### ISSUE TITLE
Replication Monitoring Metrics

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#2881]
A Sync Gateway administrator should be able to monitor the replication traffic on their cluster. The two key metrics to track would be:

- Total # of replicators
- Replication Rate
- Replication Queue

**Comment by ArihantRk** [comment]
@ssmotra , Until these feature out, As a workaround, can you please let us know how we can identify replication lag.

**Comment by tleyden** [comment]
@ArihantRk there is the `_active_tasks` endpoint which has in-progress documentation here:

https://github.com/couchbaselabs/couchbase-mobile-portal/blob/703f4b5ba8217096d2538507b8ea5ac5f456fa5e/swagger/1.5/sync-gateway-admin.yaml#L539-L577

Let me know if you have any further questions on the stats and I'll clarify the docs.

The endpoint should already be available, it's just the docs that have been delayed.

**Comment by ArihantRk** [comment]
Thank you @ssmotra , we did tried _active_tasks endpoint but we had observed the results will be how many documents have been replicated from syncgateway replicator which is not interest of us. Adn also sometimes response will be empty, hence we may not depend on _active_tasks.

Will getting difference of sequence number in _local document created at remote cluster by syncgateway and _sync:seq number of local cluster get lagging count?
if so, can you please suggest how we can identify _local document created by syncgateway replicator.

**Comment by adamcfraser** [comment]
@ArihantRk There's a lack of clarity on this original issue description - apologies if it's causing confusion.  My expectation is that this ticket covers replication status from an sg-replicate (cluster-cluster) replication perspective.  

What specific metric are you looking for when you use the term 'replication lag'?

**Comment by ArihantRk** [comment]
@adamcfraser As sg-replication concerned, We would like to know below
1. What is the rate replication, how many documents being replicated per second
2. Sg-replication lag, how many documents pending to be replicated to remote cluster at given time.
with _active_tasks we don't get how many documents to be replicated to remote cluster.
I hope this clarifies confusion.

**Comment by adamcfraser** [comment]
Closing based on age - enhancements already in place around stats recording, additional stats planned for sg-replicate in Hydrogen.
