### ISSUE TITLE
Handling for conflicted revision bodies when using xattrs

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2882]
System xattrs are intended to have a 1MB limit.  

Storage of conflicting revision bodies within the _sync metadata have the potential to exceed that limit, particular in the case of tombstone revisions that include a full revision body.

**Comment by adamcfraser** [comment]
One option is to support storage of conflicting revision bodies in separate documents, similar to what's done for obsolete revision bodies.

This has other benefits - in particular it may reduce the overhead related to unmarshalling the conflicting doc bodies when we're only interested in lower-level sync metadata (security, seq).

The other approach would be to remove the 1MB limit on system xattr size, and have it use the rest of the standard 20MB on overflow.

**Comment by tleyden** [comment]
@adamcfraser / @JFlath -- if I'm understanding this issue correctly, would these be steps to repro?

## Steps to repro

1. Add doc that has 0.99 MB worth of content
1. Add conflicting rev that has 0.99 MB worth of content
1. Would it be expected to fail at this point?

**Comment by JFlath** [comment]
That sounds good to me, at least theoretically.

**Comment by adamcfraser** [comment]
@tleyden The initial doc doesn't have to be 0.99 MB - any size is fine.  Adding a non-winning rev with size > 1MB with xattrs enabled should be sufficient to repro, but only against CBS 5.0.0-3512 or later.  Prior to 5.0.0-3512 the 1MB limit wasn't being enforced.

**Comment by JFlath** [comment]
If testing against an actual CB instance, it would need to pick up the fix for [MB-25928](https://issues.couchbase.com/browse/MB-25928) (build 5.0.0-3512) to actually hit the limit.

**Comment by adamcfraser** [comment]
**Read/Write of revision bodies**

The revtree and document structs aren't bucket-aware, and should stay that way.  We want the ability to work with revtree/document in memory, and only trigger disk persistence when appropriate.

However, document can be aware of changes to revision bodies that require persistence/purge.  

Reads of revision bodies from the bucket can be lazy loaded - pass the RevLoader to revtree.getRevisionBody.  If not already present in the in-memory rev tree, they are retrieved from the bucket and add to the tree.  

Writes of revision bodies need to be asynchronous - they are modified in the in-memory document as the doc is updated, but we need to wait until the document has been successfully run through the sync function and other pre-write processing completed before persisting bodies to the bucket.  To ensure this is the case, we need to modify update processing in crud.go to read and write all revision bodies through the `document` , and track revisions requiring persistence in the document: 

- When document.setRevisionBody is called, add modified revid to the set requiring persistence.
- When revtree node is pruned that contains revision body information, add revid to the set requiring persistence

Once pre-write processing is complete, call to document.getModifiedRevisionBodies to determine what updates need to be made.

Call to document.resetModifiedRevisionBodies (post-persistence) resets the list to empty.

**Revtree marshalling**

Keys for bodies that are persisted to the bucket are stored in a new BodyKeyMap element in the bucket.  This behaves identically to the existing BodyMap element.

**Migration processing**
When a document is migrated to use xattrs, we'd like to avoid full tree traversal to identify leaves (this could significantly slow down migration).  Instead, only trigger migration of revision bodies to separate docs if marshalled xattr size exceeds a target value (500kb)

**Comment by adamcfraser** [comment]
- [x] move all non-winning revision body management to `document`
- [x] refactor to clearly distinguish between main body and non-winning body management
- [x] retrieval of externally stored revisions
- [x] persistence of externally stored revisions post-sync function
- [x] update marshalling/unmarshalling of revtree to include external rev keys
- [x] migration processing
- [x] additional unit tests
- [x] store non-winning revisions as binary to ensure they don't get indexed
- [x] define minimum size for external storage, to avoid backing up simple tombstones or other cases where the external key wouldn't be significantly smaller than the actual doc body
- [ ] set expiry on all externally stored tombstones when main doc is tombstoned (to ensure they are removed when metadata purge interval removes tombstone)
