### ISSUE TITLE
[Perf] Inefficient JSON marshaling: Increasing amount of fields in documents degrades read throughput 

### ISSUE THREAD

**Issue by agyryk** [couchbase/sync_gateway#2890]
**SG build:** http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.5.0/1.5.0-561/
**Config file** basic, with XATTR
**OS** centos 7
**Cluster** 1 SG, 1 CB 

Noticed this behavior while running plain read operations (GET db/doc id). Within same doc size, increasing amount of fields in the doc significantly degrades SG performance.
Numbers:
1 field of 1KB size:  max throughput is 24k reads/sec
10 fields, 100B each: max thr. is 14k reads/sec
50 fields, 20B each: max thr. is 11k read/sec

Attached are CPU profiles from these 3 runs. More fields in the doc more time is taken by marshaling/unmarshaling code path and also way more garbage is generated. With 50 fields docs nearly half of the request time is GC work.

Few more notes:
1) no-XATTR setup has similar behavior (5k ops/sec single field docs, 3k for 50f docs)
2) even though there are multiple fields the document structure is pretty basic, just plain string value per field. I assume if it is marshaling/unmarshaling code issue then rich json structures (arrays, objects, n-levels) will have even more impact on read performance.

[CPUFlameGraphs_1_10_50f_docs.zip](https://github.com/couchbase/sync_gateway/files/1286862/CPUFlameGraphs_1_10_50f_docs.zip)

**Comment by adamcfraser** [comment]
@agyryk What exactly do you mean by 'ineffective' in this context?  I'm not sure if you're leaning more towards 'unnecessary' or 'inefficient'.

For this particular read scenario, I can see the case for 'unnecessary', particularly when xattrs are used for storing metadata - we should be able to avoid unmarshalling the document bodies altogether.

If you're thinking about it from a different perspective (i.e. the json marshalling could be done more efficiently), let me know.  I haven't seen any alternatives to the native library that offer improvements for non-well-known JSON schemas, which is what Sync Gateway needs to support.

**Comment by agyryk** [comment]
@adamcfraser Sorry, I meant 'inefficient'. Is it necessary or not I don't know as I'm not familiar with SG internals well enough yet. From my perspective such 50% throughput drop and memory usage pattern doesn't look optimal. Especially if metadata is coming from attributes and not from the doc body itself. 
Do I understand it correctly, with XATTTR case there are two calls from SG to CB - first 'subdoc' call for attributes and then 'get' for the document itself? If so and if we can avoid the unmarshaling completely this should give a good boost in read performance.

**Comment by adamcfraser** [comment]
Should be addressed by read/write enhancements in 2.6 and 2.7 to avoid unnecessary document marshalling/unmarshalling.
