### ISSUE TITLE
Repair tool efficiency improvements

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2892]
The repair tool in https://github.com/couchbase/sync_gateway/issues/2857 needs efficiency improvements for iterating large datasets.

**Comment by adamcfraser** [comment]
Requires the following fixes to pagination:
- Default value is not being used when view_query_page_size isn't set.  Results in no repair processing being done.  Need to change RepairBucketParams.ViewQueryPageSize to `*int` and treat absence as trigger to use default.
- When view_query_page_size is explicitly set to zero, the limit value shouldn't be set in the view query

Requires the following enhancement for writing temporary docs (from support):

> Can we have the option to change the TTL and/or turn off writing the docs at all (in the case of a dry run, that would let us get a list of those affected without doing anything else)?
