### ISSUE TITLE
Walrus view queries appear to ignore skip parameter

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2894]
In https://github.com/couchbase/sync_gateway/pull/2893#issuecomment-328231538, the skip parameter doesn't seem to be working correctly against walrus in a unit test.

When looking at the walrus code that processes the view results, it seems to ignore the skip parameter.

https://github.com/couchbase/sg-bucket/blob/master/views.go#L29-L121

**Comment by adamcfraser** [comment]
Closing based on age, and as a Walrus-only issue.
