### ISSUE TITLE
sg-replicate "terminate on failure" flag

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2895]
Based on https://github.com/couchbase/sync_gateway/issues/2884, it would make sense for the sg-replicate config settings to have the ability to control the behavior when it hits unexpected situations like getting a 4/5xx error trying push a doc.

1. warning_on_failure - rather than terminating on failure, the behavior in this mode would log a warning, skip that doc or set of docs, and continue replicating.
1. terminate_on_failure - current behavior

**Comment by adamcfraser** [comment]
Tracking with [CBG-683](https://issues.couchbase.com/browse/CBG-683)
