### ISSUE TITLE
sg-replicate JSON logging (similar to HTTP++)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2896]
In order to debug issues such as https://github.com/couchbase/sync_gateway/issues/2884, it would be helpful to have a logging mode / configuration that would either:

- Log all JSON request/response bodies

or

-  Log all JSON request/response bodies when errors occur.  (which will still make it challenging to find "downstream errors", for example if the `bulk_docs` request fails due to sending the wrong number of attachments, it will still be hard to figure out without seeing the previous `_bulk_get` response)

**Comment by adamcfraser** [comment]
Closing since HTTP++ wasn't implemented.
