### ISSUE TITLE
test_sg_sdk_interop_shared_docs failing with 404 for delete

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2897]
### Sync Gateway version
1.5.0-557.   

### Operating system
Cent OS 7.

### Config file
```
{
    "out.stdout": {
        "adminInterface": "0.0.0.0:4985", 
        "compressResponses": false, 
        "databases": {
            "db": {
                "bucket": "data-bucket", 
                "enable_shared_bucket_access": true, 
                "import_docs": "continuous", 
                "password": "password", 
                "server": "http://<server_ip1>,<server_ip2>,<server_ip3>:8091", 
                "username": "data-bucket"
            }
        }, 
        "interface": ":4984", 
        "log": [
            "CRUD+", 
            "Cache+", 
            "HTTP+", 
            "Changes+", 
            "Import+"
        ], 
        "maxCouchbaseConnections": 16, 
        "maxFileDescriptors": 90000, 
        "maxIncomingConnections": 0, 
        "slowServerCallWarningThreshold": 500
    }
}
```
The server IPs are masked above

### Log output
http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc-converg/41/

### Expected behavior
Test should pass

### Actual behavior
Test failed with a 404 error for delete. This test last passed with sg=1.5.0-546, cbs=5.0.0-3506

### Steps to reproduce
`pytest -s -k test_sg_sdk_interop_shared_docs --xattrs --mode=cc --server-version=5.0.0-3512 --sync-gateway-version=1.5.0-557 testsuites/syncgateway/functional/tests/`

**Comment by raghusarangapani** [comment]
Test passed with sg=1.5.0-557, xattrs=true, cbs=5.0.0-3516. Will watch for intermittent issues.

**Comment by sridevi-15** [comment]
Let it have it opened until it passed for few builds.
It failed with CBS -  5.1.0-1229, SG - 1.5.1-573, xattrs true, mode = di. It failed once in Jenkins with and once in my local machine with same builds .

**Comment by adamcfraser** [comment]
Closing based on age.
