### ISSUE TITLE
Improvement - Use SG to pass through N1QL/FTS

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/sync_gateway#2906]
It be great to go 
from using the Couchbase SDK directly for FTS 
to using SG as a single pane of glass to interact with CB.
**BEFORE**
<img width="582" alt="screen shot 2017-09-15 at 7 55 53 am" src="https://user-images.githubusercontent.com/16341130/30489289-bcb5f114-99eb-11e7-99ee-87691278fc90.png">
**AFTER**
<img width="579" alt="screen shot 2017-09-15 at 7 56 41 am" src="https://user-images.githubusercontent.com/16341130/30489306-c59b973e-99eb-11e7-907f-396de6df9322.png">

```
_user:bender
{
"name":"bender",
"admin_channels":["!"],
"admin_n1ql":["prepared-statement-1"],
"admin_fts":["query-1"],
"admin_analytics:[""]
}
```

**Comment by JFlath** [comment]
@Fujio-Turner Are you thinking admin or user level? 

If user level, we'd presumably have the same issues as views - having to filter in SG. Even then, that requires special handling (wrapping of the views IIRC) - could we do that for FTS?

If admin level, then we're talking about a pass through essentially right? Post convergence would there be much of a need for this?

**Comment by Fujio-Turner** [comment]
@JFlath ,

People say:
"I have business units that want to query and search my data after it was sync. Why can't I use Sync Gateway as a true microservice to access Couchbase? Its has auth built-in already and then I don't have to touch the SDK"

Q:Do people want to filter the queries results by channel access permissions?
A: No .... people want to do something like below.
{
"name":"businessReportUser1",
"admin_channels":["!"],
"admin_n1ql":["prepared-n1ql-statement-1"],
"admin_n1ql_limit":{"maxPerSecond":10},
"admin_fts":["pre-build-fts-string-xyz"],
"admin_analytics":["prepared-SQL++-statement-1"]
}

**Comment by adamcfraser** [comment]
@JFlath It's not row-level filtering, but I don't think it's correct to say it's not using SG's auth at all.  As described, access to specific named queries are granted to individual users.  In some scenarios I'd expect this is a reasonable performance tradeoff.

**Comment by Fujio-Turner** [comment]
@JFlath 
>  why not go to Couchbase Server's REST API for Query and Search?

People want simple: 

> 1.now I have to track the vbucket map to see what nodes in the cluster that are available to query if they go down.
> 2. if I have to do all of that then I should use the SDK 
> 3.Now I have a hire an engineer to write against the SDK.
> 4.Now I have to tie in my new app to my internal or third party auth.
> 5.Now I have to manage and maintain that code base
> 
> Why do I have to do all of that? 
> Does the Sync Gateway use the golang SDK?
> Does that version of the SDK that Sync Gateway uses able to do N1QL/FTS/Analytics using the SDK?
> I want to keep users/app separate from Sync Gateway  separate from Couchbase server.
> Anyways IF I build an app using the SDK I'm going to expose it as a rest service anyways.
> Why can't I just use Sync Gateway for all of this?


**Auth**
> That's fine, but it's not using SG's auth at all

(1)Authentication (Who are you)
(2)Authorization( ok you can do XYZ , but not ABC)

People want SG to handle (1) and the prepared statement to handle (2)

**Bonus Auditing built-in**
When I set my logging to "log":["HTTP","N1QL","FTS"]
in the SG log I know who, when and what queries/searches users performed.

**Comment by adamcfraser** [comment]
Closing based on age and lack of prioritization.  Reopen in JIRA based on priority.
