### ISSUE TITLE
Logfile appended multiple times (sgcollect-info)

### ISSUE THREAD

**Issue by Binary-Ape** [couchbase/sync_gateway#2910]
Hello all,

https://github.com/couchbase/sync_gateway/blob/5264ef4255214fcac3071336e14b5e6548b2afc6/tools/sgcollect_info#L265-L267

So at this piece of code you check for the old level top style log file. I have noticed that this can return the full log path of the error log file and it replaces it in `sg_log_files` dict that is being used. For example, you go from this:

`sg_log_files['sync_gateway_error.log']` prints out `sync_gateway_error.log`

To this:

`sg_log_files['sync_gateway_error.log']` prints out `/var/log/couchbase/sync_gateway/sync_gateway_error.log`

Then later in the function you use this loop to try and check all the different OS log file locations. You expect to join the OS path to the log file name:

https://github.com/couchbase/sync_gateway/blob/5264ef4255214fcac3071336e14b5e6548b2afc6/tools/sgcollect_info#L271-L275

And more specifically this line here is problematic:
            `sg_log_file_path = os.path.join(os_home_dir, path)`

When you do an os.path.join with a fully qualified path (like the /var/log.../ above) it will always return the fully qualified path. We are expecting it to be checking the different os paths:

`/home/sg_accel/logs/sync_gateway_error.log`
`/home/sync_gateway/logs/sync_gateway_error.log`
`/var/log/sg_accel/sync_gateway_error.log`
`/var/log/sync_gateway/sync_gateway_error.log`
`/Users/sync_gateway/logs/sync_gateway_error.log`
`/Users/sg_accel/logs/sync_gateway_error.log`
`C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sync_gateway_error.log`

but instead we get check the same log file location (which does exist) seven times:
`/var/log/couchbase/sync_gateway/sync_gateway_error.log`
`/var/log/couchbase/sync_gateway/sync_gateway_error.log`
`/var/log/couchbase/sync_gateway/sync_gateway_error.log`
`/var/log/couchbase/sync_gateway/sync_gateway_error.log`
`/var/log/couchbase/sync_gateway/sync_gateway_error.log`
`/var/log/couchbase/sync_gateway/sync_gateway_error.log`
`/var/log/couchbase/sync_gateway/sync_gateway_error.log`

So in the end we will try to add this file into the final zip file multiple times (it just appends the file to itself 7 times). This can cause the script to fail if the log file is larger and you run out of space to temporarily store it. It can also cause issues for the compression later on as the Zip64 extensions are not enabled by default and if the file goes over 2GB then it will fail out.

**Comment by tleyden** [comment]
@Binary-Ape thanks for the excellent bug report!  Looking into it.

**Comment by tleyden** [comment]
How I'm testing:

* Add temp code to sync gateway:

```
// Get admin config info
func (h *handler) handleGetConfig() error {
	config := h.server.GetConfig()
	logfilepath := "/Users/tleyden/tmp/sync_gateway_error.log"
	config.DeprecatedLogFilePath = &logfilepath
	h.writeJSON(config)
	return nil
}

```

so that it returns json from the `_config` endpoint like:

```
{
    "Interface": ":4984",
    "AdminInterface": ":4985",
    "log": [
        "*"
    ],
    "logFilePath": "/Users/tleyden/tmp/sync_gateway_error.log",
```

and then run sg_collectinfo and repro the issue:

```
Contents of /Users/tleyden/tmp/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
OK
Contents of /Users/tleyden/tmp/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
OK
Contents of /Users/tleyden/tmp/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
OK
Contents of /Users/tleyden/tmp/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
OK
Contents of /Users/tleyden/tmp/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
OK
Contents of /Users/tleyden/tmp/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
OK
Contents of /Users/tleyden/tmp/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
```

(it's trying add this same log file multiple times)

After the fix, I can see from the sgcollect_info logs that it's no longer trying the same file multiple times:

```
Contents of /home/sg_accel/logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exit code 1
Contents of /home/sync_gateway/logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exit code 1
Contents of /var/log/sg_accel/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exit code 1
Contents of /var/log/sync_gateway/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exit code 1
Contents of /Users/sync_gateway/logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
OK
Contents of /Users/sg_accel/logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exit code 1
Contents of /Users/tleyden/tmp/sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
OK
```

**Comment by tleyden** [comment]
While testing, I ran into this error:

```
Traceback (most recent call last):
  File "sgcollect_info", line 664, in <module>
    main()
  File "sgcollect_info", line 638, in main
    if os.path.exists(sg_binary_path):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

and so I've added another check to see if the string is None or `""`

**Comment by tleyden** [comment]
PR is up here: https://github.com/couchbase/sync_gateway/pull/2927

@Binary-Ape would be great if you could add your review!  Or even better, test out the [proposed new version](https://raw.githubusercontent.com/couchbase/sync_gateway/feature/issue_2910_sgcollectinfo_multi_logfile/tools/sgcollect_info)
