### ISSUE TITLE
Client writes not pushed to server during upgrade in di mode

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2911]
### Sync Gateway version
1.5.0-571

### Operating system
CentOS7

### Config file
```
{
     "out.stdout": {
         "adminInterface": "0.0.0.0:4985", 
         "cluster_config": {
             "bucket": "data-bucket", 
             "data_dir": ".", 
             "password": "password", 
             "server": "http://<SERVER_IP>:8091", 
             "username": "data-bucket"
         }, 
         "compressResponses": false, 
         "databases": {
             "db": {
                 "bucket": "data-bucket", 
                 "channel_index": {
                     "bucket": "index-bucket", 
                     "num_shards": 16, 
                     "password": "password", 
                     "server": "http://<SERVER_IP>:8091", 
                     "username": "index-bucket", 
                     "writer": false
                 }, 
                 "password": "password", 
                 "server": "http://<SERVER_IP>:8091", 
                 "username": "data-bucket"
             }
         }, 
         "interface": ":4984", 
         "log": [
             "CRUD+", 
             "Cache+", 
             "HTTP+", 
             "Changes+"
         ], 
         "maxCouchbaseConnections": 16, 
         "maxFileDescriptors": 90000, 
         "maxIncomingConnections": 0, 
         "slowServerCallWarningThreshold": 500
     }
 }
```

### Log output
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-upgrade/112/

### Expected behavior
Doc updates should be present in both cc and di mode.

### Actual behavior
Run the upgrade test in cc and di mode. In cc mode test passes. In di mode, doc updates are missing.

### Steps to reproduce
From `feature/upgrade` branch of mobile-testkit:
`pytest --timeout 18000 -s --mode=di --server-version=4.6.3 --server-upgraded-version=5.0.0-3516 --sync-gateway-version=1.4.1-3 --sync-gateway-upgraded-version=1.5.0-557 --liteserv-host=localhost --liteserv-port=59840 --liteserv-version=1.4.0-3 --liteserv-platform=macosx --liteserv-storage-engine=SQLite --num-docs=10 --cluster-conf=2each_lb testsuites/syncgateway/upgrade`

**Comment by pasin** [comment]
I have looked the client log and I saw a lot of _rev_diff errors:

```
CBLRemoteJSONRequest[POST http://s61706cnt72.sc.couchbase.com:4984/db/_revs_diff]: Got error CBLHTTP[500, "internal server error", <http://s61706cnt72.sc.couchbase.com:4984/db/_revs_diff>]
```

So when the rev-diff has an error, the updates cannot be push.

**Comment by adamcfraser** [comment]
When running against channel cache, the same test gets similar 500 errors, but the test is passing.  Investigating what the difference is - whether it's just coincidental based on what operation the client is performing when the errors occur, or something else.  

Passing test:
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-upgrade/114/

Also need to understand why gocb is raising the 'not connected to a bucket ' errors during rebalance, if one of the nodes is actually available.

**Comment by adamcfraser** [comment]
Observations on failing test http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-upgrade/113:

- the test is expecting rev 23-51691f7271beac03ec555a5bc48c71ab for doc ls_db_upgrade_doc_8_0
- the last revision of that document that was sent to Sync Gateway was 12-043be86d8c5232fce67b8448e723ad67 (which is the last version verified by the client)
- all other documents in the test had updates sent by the client after the last SG restart (post-server upgrade)
- there are no failed updates in the logs associated with this document
- there are a many failed revs_diff operations in the logs prior to the final SG restart (post-server upgrade), indicating that push replication is blocked from the client's perspective.  When push replication resumes post-restart, doc ls_db_upgrade_doc_8_0 isn't being updated
- looking at the client logs, ls_db_upgrade_doc_8_0 was queued for update at 09:50:33.748.  Subsequently queued entries are being successfully pushed

**Comment by adamcfraser** [comment]
In general it looks like it's possible for the gocb connection to the bucket to get into a bad state during an in-place upgrade of server from 4.6 to 5.0.   This doesn't happen every time - in the passing cc test it occurred for one SG node and not the other.  It's resolved by a restart of Sync Gateway.

Had an initial review w/ @brett19, but there's nothing obvious in the error messages being sent.

@raghusarangapani - can you provide the specific steps that are being taken to upgrade server, so that I can file an SDK issue?

**Comment by sridevi-15** [comment]
@adamcfraser , Here are the steps that have written for upgrade testing for scenario : 

SG 1.4.x docmeta to 1.5.0 docmeta/CBS 3.1 to CBS 5.0.0 upgrade in cc mode

 Provision CBS, SG nodes, 1 load balancer for SGs and a CBL client.
- Start push/pull replication between SG and LiteServ
- Load docs to CBS through LiteServ clients.
- Start updating the docs from the client in a separate thread, keep track of the updates you make to verify the revision.
- Upgrade CBS to CBS 5.0.0 
  - Rebalance out the node.
  - Stop the CBS service.
  - Rum rpm -e
  - Run rpm -U
  - Start the CBS service.
  - Add node back to the cluster.
  - Rebalance in.
- Upgrade SG 1.4.x to SG 1.5.0.
  - Stop the SG service.
  - Run rpm -U
  - Start the SG service.
- Stop doc updates.
- Verify data before and after upgrade.
- Scan logs for any errors or panics

**Comment by adamcfraser** [comment]
This looks like the gocb bucket connection returning errors during upgrade - initially when the first 5.0 node is rebalanced in (not connected to bucket), and subsequently when the last 4.6 node is rebalanced out (no access).  

Filed https://issues.couchbase.com/browse/GOCBC-235 for followup.

The net result is that most SG operations will be blocked during server upgrade, until the SG nodes are restarted.

**Comment by adamcfraser** [comment]
@raghusarangapani Can you rerun the cc version of this test with the 'gocb' log key enabled?

**Comment by raghusarangapani** [comment]
@adamcfraser Here it is: http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-upgrade/127/

**Comment by adamcfraser** [comment]
Clarified the subject to reflect what's actually happening here - during server upgrade to 5.0, the Sync Gateway connection to the bucket may be lost (https://issues.couchbase.com/browse/GOCBC-235).  During that time, any push replication from clients to Sync Gateway will fail.  There's no data loss between SG and CBS.
