### ISSUE TITLE
SG panics with GET /db/docID if client connection is closed when writing doc body

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2915]
When calling GET /mydb/docid on the REST API Sync Gateway will serialize the document body for return in the response.

In the handler.go addJson() method the json marshaller writes directly to the http handler response.

```
func (h *handler) addJSON(value interface{}) {
	encoder := json.NewEncoder(h.response)
	err := encoder.Encode(value)
	if err != nil {
		base.Warn("Couldn't serialize JSON for %v : %s", value, err)
		panic("JSON serialization failed")
	}
}
```
If the handler is closed or the response is unwritable due to the client dropping their end of the connection, then the json marshaller will return an error and the addJson method will panic.

This behaviour has been ascribed as possibly the cause of memory spikes in Sync Gateway.

We have CloseNotify support on http connections, which should detect when a client has dropped their end of a connection and close the server connection out.

We need to write a test to see if the CoseNotify() can close the server side of a connection while the json marshaller is blocked attempting to write to the client.

We also need a test to determine if there is a potential memory spike when these errors occur and if the size of the spike is related to the size of the document bodies being written to the http response.

**Comment by tleyden** [comment]
Possibly related to https://github.com/golang/go/issues/16100

**Comment by ajres** [comment]
Sync Gateway does not use CloseNotify on simple request/response calls like GET for a doc.

CloseNotify requires that a go routine is able to select on the CloseNotify channel, this is possible for the changes feed as it spends most of it's time in a wait loop.

We have considered using custom values for ServerWriteTimeout in the SG config to reduce the amount of time it takes to timeout a tcp connection where the client has disconnected. But it is difficult to identify a timeout that will only terminate connections that have permanently lost client conneciton and not just temporary loss due to mobile networks e.t.c.

In this scenario, it's possible that connections are being lost because SG is under load, rather than the lost connections causing SG to exhibit excessive load.

The approach we are going to take it to handle the specific tcp timeout issue gracefully in the addJSON method

if encoder.Encode fails because of a JSON error
  then
     return status 500 and log a warning

If encoder.Encode fails because of a tcp timeout
  then
    return status 503 and log a CRUD+, "client closed connection"
