### ISSUE TITLE
Logging as invalid json for binary documents in sg logs

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#2916]
### Sync Gateway version
1.5.0-573

### Operating system
CentOS

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+", "Import+"],
    "databases":{
        "db":{
            {{ autoimport }}
            {{ xattrs }}
            "server":"{{ server_scheme }}://{{ couchbase_server_primary_node }}:{{ server_port }}",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password"
        }
    }
}
```
### Steps to reproduce
1.  Create a binary document through SDK 
I used python SDK
```
from couchbase import FMT_BYTES
from couchbase.bucket import Bucket
SDK_CLIENT = Bucket(’couchbase://192.168.33.10/data-bucket’, password='password')

SDK_CLIENT.upsert("sg_doc_1", 'Hello, UTF-16 World!'.encode('utf16'),format=FMT_BYTES)
```
2.  Tail sync-gateway logs
3.  Do get on the doc  for binary document created via SDK.
4. Check the logs

### Actual behavior
It is logging as invalid Json for binary documents
Also When I do get on this binary doc using syn-gateway API , I get response as 
```
{"error":"Bad Request","reason":"Invalid JSON: \"invalid character 'Ã¿' looking for beginning of value\""}
```

### Expected behavior
It should log as 'not imported' . -> sg logs
Get using sync-gateway API should respond as 'not found' as binary documents is not supposed to import by sync-gateway 

### Log output : Sg logs
2017-09-20T01:08:51.526Z HTTP:  #029: GET /db/sg_doc_1  (as autotest)
2017-09-20T01:08:51.527Z CRUD+: No xattr content found for key=sg_doc_1, xattrKey=_sync: sub-document path does not exist
2017-09-20T01:08:51.527Z HTTP: #029:     --> 400 Invalid JSON: "invalid character 'ÿ' looking for beginning of value"  (1.1 ms)

**Comment by djpongh** [comment]
Minor issue, potential 2.0 fix.

**Comment by adamcfraser** [comment]
I believe this has been addressed in 2.x - please reopen in JIRA if this is still an issue.
