### ISSUE TITLE
Custom auth: use token without setting a cookie

### ISSUE THREAD

**Issue by fredericgermain** [couchbase/sync_gateway#2917]
Custom Authentication. 

### Sync Gateway version
Couchbase Sync Gateway/1.4.1(3;ddffd85)"

### Operating system
docker on Fedora 25

###
I've read this doc and, and want to implement a "custom auth" : https://blog.couchbase.com/how-to-authorize-users-in-sync-gateway/

My app is pure HTML. I get a token from my auth server, and I need to use the token when making calls to the sync gateway server.
The problem is that the auth server and sync gateway are on different domains, and I cannot force the cookie on the sync gateway.
It would be nice to have some other means to use the token, like using a HTTP header "authorization bearer {session_token}" for authentification.

**Comment by ajres** [comment]
@fredericgermain

What issues are you experiencing trying to create the SG session cookie in your App. From JavaScript you should be able to add a cookie to your local cookie store and have it forwarded to SG. The full SG cookie format is:

SyncGatewaySession=4afbfc27b40746d67622341916839a7b5a026189; Path=/db; Expires=Wed, 25 Oct 2017 19:43:21 GMT

**Comment by ajres** [comment]
Closing this ticket and associated PR, please re-open if you can document your specific issues.

**Comment by hubgit** [comment]
This would be very useful for situations where the browser client has the session token (e.g. via a call to a separate authentication service), but is not able to write a cookie for the Sync Gateway domain.

I think the concerns about security mentioned in https://github.com/couchbase/sync_gateway/pull/2988#issuecomment-338791551 are unwarranted, as there are many applications that use JWTs for authentication and trust browser clients to store the tokens securely.
