### ISSUE TITLE
Set up 1.5.1 builds

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2918]
- [x] tag master as [1.5.0](https://github.com/couchbase/sync_gateway/tree/1.5.0)
- [x] create [release/1.5.0 branch](https://github.com/couchbase/sync_gateway/tree/release/1.5.0)
- [x] [create 1.5.0.xml manifest](https://github.com/couchbase/sync_gateway/pull/2925)
- [x] merge dev to master [in progress](https://github.com/couchbase/sync_gateway/pull/2924/files)

**Comment by tleyden** [comment]
This can be closed once https://github.com/couchbase/sync_gateway/pull/2925 is merged
