### ISSUE TITLE
Cant stop Service Sync gateway 1.5 beta 2

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2936]
From https://forums.couchbase.com/t/cant-stop-service-sync-gateway-1-5-beta-2/14268

> I installed couchbase sync gateway on windows machine but I think there is some issue with installation as the service can be started or stopped and looking into its properties it throws error : The specified service does not exists as an installed service.

### Sync Gateway version
Sync gateway 1.5 beta 2

### Operating system
Windows (which version?)

**Comment by ghost** [comment]
Its Windows 10

**Comment by djpongh** [comment]
We test this and haven't had any issues. Have you made sure you have the proper privileges?

**Comment by erpankaj22** [comment]
Yes I have Administrator privileges. If you want I can create a video and sent it over to you.

**Comment by ajres** [comment]
@erpankaj22 Did you install Sync Gateway into the default location on the C: drive?

**Comment by djpongh** [comment]
Suspect this is a dup of #2579
