### ISSUE TITLE
Apply ttl on pre-existing checkpoints

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/sync_gateway#2939]
https://github.com/couchbase/sync_gateway/issues/1280

@adamcfraser ,
There are customers with pre-existing deployments of SG/CB that need to apply their pre-existing checkpoints with the new TTL.
Could we have in the _resync process an optional flag that also updates the checkpoints with the new ,non-Zero, TTL.

I say optional flag because there are some customers with millions of checkpoints that might need an independent script ,to change the TTL, to speed up the process.

**Comment by djpongh** [comment]
This feels more like a support/SE issue.

**Comment by Fujio-Turner** [comment]
@djpongh,

> This feels more like a support/SE issue.

hmmmm ... SG ,by default, can not query all the /_local/{MD5 hash}. Also older CB pre-4.0 also will HAVE to use M/R only to find the _local/{MD5 hash} while 4.x+ can leverage N1QL.

**Comment by djpongh** [comment]
Can you explain more of what the customer is trying to accomplish?

**Comment by adamcfraser** [comment]
Closing - file a tracking JIRA issue for customer requirements.
