### ISSUE TITLE
Avoid XATTR upgrade fallback for Couchbase 4.x

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2943]
This came up when working w/ @adamcfraser and digging into https://github.com/couchbase/sync_gateway/issues/2938#issuecomment-333192189.

When running against Couchbase Server 4.1, I was seeing the following error logs:

```
goroutine 39 [running]:
panic(0x5849a0, 0xc4200160f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbase/sync_gateway/db.(*DatabaseContext).GetDocWithXattr(0xc420236280, 0xc42039dbb0, 0x3, 0xd, 0x0, 0xc4203443e2, 0xc42039dbb0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:89 +0x69
github.com/couchbase/sync_gateway/db.(*DatabaseContext).checkForUpgrade(0xc420236280, 0xc42039dbb0, 0x3, 0x1, 0x0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:1378 +0x52
github.com/couchbase/sync_gateway/db.(*changeCache).DocChangedSynchronous(0xc4201e0690, 0x2, 0x0, 0xc4203443df, 0x3, 0x10, 0xc4203443e2, 0xd, 0xd, 0x8a12c7c20000, ...)
```

Since it's Couchbase 4.x however, it should never try to use XATTRS.  This code might be ignoring the server version check and need to be updated.

**Comment by adamcfraser** [comment]
Wasn't able to repro this running against Couchbase Server 4.6.3.  Installing 4.1 to see if behaviour is any different there.

**Comment by adamcfraser** [comment]
Also unable to repro against 4.1 - created a doc in the bucket without valid sync data, verified that the upgrade check was triggering, and it returned the expected error.  This includes processing the change as it arrives over the DCP feed (where the above stack trace looks to be occuring), and also during a subsequent GET on the doc:
```
2017-10-24 14:27:06.211895 I | Checking for upgrade for key noSyncData
2017-10-24T14:27:06.212-07:00 WARNING: changeCache: Doc "noSyncData" does not have valid sync data. -- db.(*changeCache).DocChangedSynchronous() at change_cache.go:424
2017-10-24T14:27:17.571-07:00 HTTP:  #001: GET /default/noSyncData  (ADMIN)
2017-10-24 14:27:17.571699 I | Checking for upgrade for key noSyncData
2017-10-24T14:27:17.571-07:00 HTTP: #001:     --> 404 Not imported  (1.0 ms)
```

**Comment by adamcfraser** [comment]
Looking at the original panic, it looks like it was actually related to the bucket being closed before the DCP feed was terminated in a previous test, and that was causing the panic at crud.go:89 when it tried to access the bucket.

This has been fixed by the improved DCP closedown handling added w/ https://github.com/couchbase/sync_gateway/pull/2972

**Comment by tleyden** [comment]
@adamcfraser I think the reference to https://github.com/couchbase/sync_gateway/pull/2972 might have been a typo, since the title of that issue is "Feature/issue 2937 improve code coverage".

If so, do you know the correct issue or know how to find any more details?

**Comment by adamcfraser** [comment]
Based on the description, sounds like https://github.com/couchbase/sync_gateway/pull/2953
