### ISSUE TITLE
Avoid panic if revision not found in history

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2945]
While looking into a user's panic stacktrace in Sync Gateway 1.4.1.2, I noticed places in the code where it's trying to get a revision out of the history without doing a check first.

For example here: https://github.com/couchbase/sync_gateway/blob/788b186dcc83c2c89f44269952f6e0ee66aa79b5/db/crud.go#L195-L197

This should be changed to call `doc.GetRevision(revId)` (creating this method if needed), which will return an error if that revision doesn't exist in the history.

**Comment by adamcfraser** [comment]
I agree this could be more defensively coded, but it's worth digging into how https://github.com/couchbase/sync_gateway/blob/788b186dcc83c2c89f44269952f6e0ee66aa79b5/db/crud.go#L181 succeeded if the rev isn't in the history.

**Comment by tleyden** [comment]
The example I posted was actually just me searching that file for the first call to `doc.History[id.RevID].Deleted`, and the actual stacktrace wasn't at that line (sorry, my initial post was a bit misleading).  

In general I think there are several calls to `doc.History[id.RevID].X` which could probably benefit from some extra checking.

**Comment by adamcfraser** [comment]
Closing based on age, and lack of specific risk areas.
