### ISSUE TITLE
Basic authentication failure and data leakage

### ISSUE THREAD

**Issue by keith-redbite** [couchbase/sync_gateway#2946]
Hi, we found a rather severe issue where SG does not ask for credentials (for basic authentication) when it is visited via web browser at the following. 

> $sync-gateway-host-ip:$sync-gateway-interface-port/$bucket/_changes

The expected behaviour for the above is for the SG to ask for credentials or 401. In this case however, the SG immediately shows full changes feed, which virtually leaks all data. 

Further inspection on the following API endpoint gives a clue to what's happening.

> http://$sync-gateway-host-ip:$sync-gateway-interface-port/$bucket/_session

The result of the GET of the above gives below. Note that this seems to say that the channels that the **null** user has access to are "!" and "*". 

> {"authentication_handlers":["default","cookie"],"ok":true,"userCtx":{"channels":{"!":1,"*":46175},"name":null}} 

The expected result should be the following, which gives no channels access to the null user.

>{"authentication_handlers":["default","cookie"],"ok":true,"userCtx":{"channels":{},"name":null}}

Initially thinking that a newer SG version may fix this, I actually ran 3 different SG version via docker and all exhibited the same bug:
i) 1.3.0
ii) 1.3.1
iii) 1.4.0

The OS of the docker host: 4.4.41-35.53.amzn1.x86_64

Logs:
> 2017-10-03T15:30:38.340Z HTTP:  #106012: GET /$bucket/_changes
> _time=2017-10-03T15:30:38.383+00:00 _level=INFO _msg=go-couchbase: call to ViewCustom("sync_gateway", "channels") in github.com/couchbase/sync_gateway/db.(*DatabaseContext).getChangesInChannelFromView took 409.993596ms 
> 2017-10-03T15:30:38.393Z changes_view: Query took 420.893934ms to return 38444 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"*", 0x1}, "endkey":[]interface {}{"*", 0xc3bf}}

Note that the log does NOT indicate which user is performing the GET on "$bucket/_changes". It usually does by appending "($username)" on the same line when a user is authenticated, or at least that I know of when done via cookie. 

```javascript
{
        "interface":":4984",
        "adminInterface":":4985",
        "log":["HTTP"],
        "databases":{
                "$bucket":{
                        "server":"http://$couchbase-server-ip:8091",
                        "bucket":"$bucket",
                        "sync":
                                `function(doc,oldDoc) {
                                        if(doc["redacted.GrantAccessToAdmin"]) {
                                                requireUser("redactedsuperuser");
                                                access("redactedsuperuser",doc["redacted.GrantAccessToAdmin"].channels);
                                                return;
                                        }
                                        if(oldDoc){
                                                requireAccess(oldDoc["redacted"].channels);
                                                channel(oldDoc["redacted"]. channels);
                                                return;
                                        }
                                        requireAccess(doc["redacted"]. channels);
                                        channel(doc["redacted"]. channels);
                                }`
                }
        }
}
```

**Comment by adamcfraser** [comment]
This sounds like the behaviour when the GUEST user has been created, and they have been granted access to the `*` channel.  It's possible that the GUEST user was created when Sync Gateway was started with a previous config, and wasn't subsequently deleted/disabled. 

Assuming that's the root cause here, deleting the GUEST user would fix this.  You could also guard against this scenario in future by adding:
`
      "users": { "GUEST": { "disabled": true } }
` 
to your config.

**Comment by keith-redbite** [comment]
I was not able to remove GUEST, primarily because it does not exist.

>curl -X DELETE localhost:4985/$bucket/_user/GUEST
>{"error":"not_found","reason":"missing"}

Explicitly disabling GUEST user in sync config however does seem to fix the issue. Maybe GUEST user should be disabled by default if newer config no longer has GUEST user?

**Comment by keith-redbite** [comment]
P.S. Thanks Adam!

**Comment by adamcfraser** [comment]
@keith-redbite Thanks for the information - that looks like a bug on the DELETE user operation.  Filed https://github.com/couchbase/sync_gateway/issues/2951.

Disabling by default if not present isn't really feasible, as there are many paths by which the GUEST user could be defined (through config, through a single config in a cluster of SGs, through REST API), and a single SG node can't make assumptions about intended behaviour.
