### ISSUE TITLE
SG should track and log resource usage

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2969]
This request originated from support to make it easier to investigate time specific issues in SG nodes.

SG should track (and presumably log)  the memory, networking (to clients and to server separately), CPU and Disk (SG uses disk only for logging, except in di mode where local cluster data is fgenerated) it is using.

This will allow support to validate what a customer is saying postmortem of the reported event.

As a reference couchbase Server does some of this today.

**Comment by adamcfraser** [comment]
Included in the stats logging enhancements in 2.5.0, will be included as part of Mobile Service integration in future.
