### ISSUE TITLE
Noisy log warning: Unable to import doc - external update will not be accessible via Sync Gateway

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2973]
Steps to repro:

- Large bucket (30 million docs)
- SG Import function to only select a few docs

Will emit gigs of logs with this message:

```
				base.Warn("Unable to import doc %q - external update will not be accessible via Sync Gateway.  Reason: %v", docID, err)
```

**Comment by tleyden** [comment]
Looks like this is possible to suppress by setting the logLevel to `panic` in this config setting: https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/config-properties/index.html#1.4/logging-default-logLevel

**Comment by adamcfraser** [comment]
Filtered imports shouldn't log a warning - it should only be reported to the logs as Import+ logging.
