### ISSUE TITLE
_all_docs not accepting options

### ISSUE THREAD

**Issue by jnordberg** [couchbase/sync_gateway#298]
Querying with `limit` or `startkey` has no effect.

https://wiki.apache.org/couchdb/HTTP_Document_API#all_docs

**Comment by jchris** [comment]
For [reasons to do with Safari ugliness](https://github.com/pouchdb/pouchdb/pull/1239) PouchDB passes `keys` as a query string when it can. Adding support for this in SG would make it easier to use PouchDB as a remote client for SG. I don't think it's necessary for replication.

Just leaving this here for folks who might wander by for the same reason I did.
