### ISSUE TITLE
Documentation for oidc scope says string but should be array of strings

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#2990]
[Sync Gateway config docs](https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/config-properties/index.html#1.4/databases-foo_db-oidc-providers-foo_provider-scope) says that the oidc scope param should be a string:

> Optional. By default, Sync Gateway uses the scope "openid email" when calling the OP's authorize endpoint. If the scope property is defined in the config (as a map of string values), it will override this scope.

But this causes an error, as it should actually be an array of strings like `["openid", "email"]`.

### Sync Gateway version
1.4.1(3;ddffd85) 

### Operating system
Ubuntu 14.04, Docker Image 1.4.1-3

### Config file
```javascript
{
  "log": ["*"],
  "databases": {
    "db": {
      "server": "http://server:8091",
      "bucket": "db",
      "users": { "adminUser": { "password": "adminPassword", "admin_channels": ["*"], "disabled": false } },
      "oidc": {
		"default_provider": "oidc1",
        "providers": {
          "oidc1": {
            "issuer":"https://authserver",
            "client_id":"clientId",
            "validation_key":"secretKey",
            "register":true,
            "scope": "openid email offline_access"
          }
        }
      },
      "sync": `mysyncfunction` 
    }
  }
}
```

### Log output
https://gist.github.com/tura08/3c5fe85dc5a76658dbb5c73e8c76a9fd

### Expected behavior
Sync gateway should start up with no errors

### Actual behavior
Sync gateway has errors as per gist

### Steps to reproduce
1.  Put scope param as a string e.g. "openid email offline_access"
2.  Start sync gateway
3.  See errors

**Comment by adamcfraser** [comment]
Thanks for catching - this looks like a documentation error.  As noted, Sync Gateway expects scope to be defined as an array of strings.

**Comment by ghost** [comment]
Happy to help. You'll want to also update the config file reference:
`scope: "string",` -> `scope: ["string"] `

**Comment by adamcfraser** [comment]
@tura08 Good catch - will update that as well.
