### ISSUE TITLE
Possible bug: specifying revs_limit on a per-doc basis

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2997]
From @adamcfraser via email thread:

> Sync Gateway supports setting revs_limit on an individual get doc, and as a top-level parameter for an entire bulk_get request, but I don't see support for specifying revs_limit on a per-doc basis in a bulk_get request in the Sync Gateway code.

> From the original spec (https://github.com/couchbase/sync_gateway/wiki/Sending-Minimal-Histories) it looks like supporting both was the intended behaviour, so this may be a SG bug.

> @snej – do you know if this is the consistent behaviour across CBL clients – they always use the per-doc revs_limit on a bulk_get request?

**Comment by adamcfraser** [comment]
Duplicate of https://github.com/couchbase/sync_gateway/issues/2992
