### ISSUE TITLE
Sporadic test failure: TestRecentSequenceHistory

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3004]
Originally filed in https://github.com/couchbase/sync_gateway/issues/1589

**Comment by tleyden** [comment]
Replace this sleep with an event based wait of some sort

```
	// Add many sequences to validate pruning when past max (20)
	for i := 0; i < kMaxRecentSequences; i++ {
		revid, err = db.Put("doc1", body)
		// Sleep needed to ensure consistent results when running single-threaded vs. multi-threaded test:
		// without it we can't predict the relative update times of nextSequence and RecentSequences
		time.Sleep(50 * time.Millisecond)
	}
```

**Comment by tleyden** [comment]
Just saw this fail on drone.ci using `-race`

http://drone.couchbase.io/couchbase/sync_gateway/3354

Should this test be skipped when running under `-race`?  (note: -race might be a red herring)

**Comment by tleyden** [comment]
Test Logs snippet:

```
	database_test.go:1296
	assert.True(t, len(doc.RecentSequences) <= kMaxRecentSequences)	
--- FAIL: TestRecentSequenceHistory (0.25s)
	assert.go:31: 
```

**Comment by adamcfraser** [comment]
That test output is useful.  I think kMaxRecentSequences + 1 is actually valid - it won't get pruned until next write.  

I'll look into whether the test should be tweaked, or the functionality changed to prune when #sequences = kMaxRecentSequences - 1.
