### ISSUE TITLE
PouchDB incompatibility due to multipart-only responses

### ISSUE THREAD

**Issue by wspringer** [couchbase/sync_gateway#301]
The reason for it is that it fails on requests where PouchDB expects `application/json` and all Sync gateway is willing to give is `multipart/mixed`. 

See https://github.com/daleharvey/pouchdb/issues/1666

**Comment by jchris** [comment]
I think the next step on this is here https://github.com/pouchdb/pouchdb/issues/2832 -- after that is in there is some additional work we can do for deeper sync gateway interop.

**Comment by zgramana** [comment]
Closing here as it's closed in pouchdb. Anyone please re-open/re-file if I missed something.
