### ISSUE TITLE
Admin API "sudo" mode

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#3023]
When debugging issues, it's useful to check the output of REST calls as a specific user (e.g. "this doc isn't replicating, does it appear in the _changes feed for user `JFlath`?"). Generally, this requires knowledge of that user's credentials - something that's not always possible.

Instead, it would be good to force the admin api to act as though it has the permissions of that user (we already have unlimited access as an admin, so it's not a privilege escalation). Perhaps something along the lines of:

```
:4985/_sudo/USERNAME/PATH/OF/ORIGINAL/REQUEST
:4985/_sudo/JFlath/db/_changes
```

From an implementation standpoint, I suspect it would make sense to try and follow the same codepath as the "original" request as closely as possible to reduce the risk of different behaviour in a failure scenario.

**Comment by adamcfraser** [comment]
Closing based on age - reopen in JIRA if there's still a compelling use case.
