### ISSUE TITLE
TestIndexChangesBasic disabled integration/walrus tests

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3036]
The following tests are disabled with this comment:

> These tests require manual setup at the moment, and will require more work to run in a fully automated fashion.  Also, some of this functionality already covered in tests that use mock DCP feed

* TestIndexChangesBasic
* TestIndexChangesAdminBackfill
* TestIndexChangesRestartBackfill

Original ticket: https://github.com/couchbase/sync_gateway/issues/2977

**Comment by adamcfraser** [comment]
These look like they may just require Couchbase Server to run.

**Comment by adamcfraser** [comment]
Tests have been replaced/updated.
