### ISSUE TITLE
[windows] in startup menu under Couchbase, Inc.: Sync_Gateway does not show Uninstall option

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#3039]
### Sync Gateway version
v 1.5.1 - master

### Operating system
Windows 10

### Expected behavior
After installing Sync Gateway from the Windows installer there should be 2 menu items under the Couchbase Inc menu folder

Launch Couchbase Sync Gateway
Uninstall Couchbase Sync Gateway

### Actual behavior
Only see:
Launch Couchbase Sync Gateway

### Steps to reproduce
1.  Install Couchbase Sync Gateway from the Windows installer
2.  Go to the startup Menu and expand the "Couchbase Inc" Menu folder
3.  Observe the entries in the folder

**Comment by djpongh** [comment]
Will be using WIX for 2.0
