### ISSUE TITLE
Avoid duplicate changes entries for late-arriving sequences in multiple channels

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3056]
Since 1.4, Sync Gateway uses the currently cached sequence to ensure that updates to the channel cache midway through a changes iteration doesn't result in the same sequence being sent from multiple channels in separate changes iterations.

However, this doesn't handle late-arriving (skipped) sequences, which will always have a value lower than the currently cached sequence.  

To fix, we need to check the current low sequence for the SG node at the start of a changes iteration, and ignore entries from late feeds that are later than that value.  As with the currentCached handling in place today, needs to ensure that if any entries are ignored in this way, the changes loop doesn't go into wait mode.

**Comment by adamcfraser** [comment]
When fixed, re-enable DisableTestLowSequenceHandlingNoDuplicates

**Comment by tleyden** [comment]
This only affects connected REST clients rather than Couchbase Lite clients.

**Comment by adamcfraser** [comment]
Closing based on age - low priority issue.
