### ISSUE TITLE
Refactor SimpleMultiChangesFeed

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3060]
A few places this could be refactored to increase readability:

- Rename method to `ChangesFeed`

- Pull out the function run by the goroutine from the method, so that invokers must call `go SimpleMultiChangesFeed`, or keep `SimpleMultiChangesFeed` as-is and have it call `go othermethod`.  Either approach would reduce indentation on `SimpleMultiChangesFeed` itself.

- Factor out the code to decide the values of `backfillRequired`, `backfillPending`, and `backfillInOtherChannel` into a separate method, which can have it's own comment block and potentially it's own unit test if it was warranted.

**Comment by adamcfraser** [comment]
Closing - has been done to some degree.
