### ISSUE TITLE
sync_gateway without cache is killed by OOM-killer

### ISSUE THREAD

**Issue by ont** [couchbase/sync_gateway#3063]
### Sync Gateway version
`"version":"Couchbase Sync Gateway/1.4.1(3;ddffd85)"`

### Operating system
Official docker container `1.4.1-3-comunity`

### Config file
```javascript
curl web.node.consul:4985/_config

{
  "Interface": ":4984",
  "AdminInterface": ":4985",
  "log": [
    "*"
  ],
  "Databases": {
    "babycare": {
      "server": "http://couchbase-server-master.service.consul:8091",
      "pool": "default",
      "bucket": "some-bucket",
      "name": "some-bucket",
      "sync": "... some sync function ...",
      "cache": {
        "max_wait_pending": 1,
        "max_num_pending": 1,
        "max_wait_skipped": 1,
        "enable_star_channel": true,
        "channel_cache_max_length": 1,
        "channel_cache_min_length": 1,
        "channel_cache_expiry": 1
      },
      "rev_cache_size": 0
    }
  }
}

```

### Expected behavior
Constant memory usage and high CPU usage for couchbase server.

### Actual behavior
Memory constantly grows and sync-gateway is OOM-killed

### Current setup 
- more than 5000 active connections which are proxied via nginx to two sync-gateway instances
- each sync-gateway containers have 3Gb memory limit
- near 50 requests per second to sync-gateway instances
- at current time each active connection is related to unique user with unique 2 or 4 channels. This channels are related to ACL access and may have over 1000 user's personal documents.
- there is no errors from nginx proxy except when sync-gateway is OOM-killed

### Heap profile
Output for memory heap taken with `curl -XPOST -H "Content-Type: application/json" -d '{"file": "heap.profile"}' web.node.consul:4985/_heap`:
```
ont@ont-work ~> go tool pprof -text /tmp/sync_gateway /tmp/heap.profile 
1459.33MB of 1495.84MB total (97.56%)
Dropped 619 nodes (cum <= 7.48MB)
      flat  flat%   sum%        cum   cum%
 1234.89MB 82.55% 82.55%  1424.72MB 95.25%  compress/flate.NewWriter
  189.83MB 12.69% 95.25%   189.83MB 12.69%  compress/flate.(*compressor).init
   17.56MB  1.17% 96.42%    17.56MB  1.17%  github.com/couchbase/sync_gateway/db.newChannelCacheWithOptions
    8.52MB  0.57% 96.99%     8.52MB  0.57%  net/http.newBufioWriterSize
    8.03MB  0.54% 97.53%     8.03MB  0.54%  net/http.newBufioReader
    0.50MB 0.033% 97.56%  1444.73MB 96.58%  github.com/couchbase/sync_gateway/rest.(*handler).invoke
         0     0% 97.56%  1425.72MB 95.31%  compress/gzip.(*Writer).Write
         0     0% 97.56%    18.55MB  1.24%  github.com/couchbase/sync_gateway/db.(*Database).SimpleMultiChangesFeed.func1
         0     0% 97.56%    15.55MB  1.04%  github.com/couchbase/sync_gateway/db.(*Database).changesFeed
         0     0% 97.56%    15.55MB  1.04%  github.com/couchbase/sync_gateway/db.(*changeCache).GetChanges
         0     0% 97.56%    17.56MB  1.17%  github.com/couchbase/sync_gateway/db.(*changeCache)._getChannelCache
         0     0% 97.56%    15.55MB  1.04%  github.com/couchbase/sync_gateway/db.(*changeCache).getChannelCache
         0     0% 97.56%  1426.22MB 95.35%  github.com/couchbase/sync_gateway/rest.(*EncodedResponseWriter).Write
         0     0% 97.56%     8.38MB  0.56%  github.com/couchbase/sync_gateway/rest.(*handler).handleBulkDocs
         0     0% 97.56%  1303.60MB 87.15%  github.com/couchbase/sync_gateway/rest.(*handler).handleChanges
         0     0% 97.56%   129.75MB  8.67%  github.com/couchbase/sync_gateway/rest.(*handler).handleRevsDiff
         0     0% 97.56%  1302.60MB 87.08%  github.com/couchbase/sync_gateway/rest.(*handler).sendSimpleChanges
         0     0% 97.56%  1444.73MB 96.58%  github.com/couchbase/sync_gateway/rest.makeHandler.func1
         0     0% 97.56%  1446.23MB 96.68%  github.com/couchbase/sync_gateway/rest.wrapRouter.func1
         0     0% 97.56%  1445.73MB 96.65%  github.com/gorilla/mux.(*Router).ServeHTTP
         0     0% 97.56%  1465.78MB 97.99%  net/http.(*conn).serve
         0     0% 97.56%  1446.23MB 96.68%  net/http.HandlerFunc.ServeHTTP
         0     0% 97.56%  1446.23MB 96.68%  net/http.serverHandler.ServeHTTP
         0     0% 97.56%  1488.84MB 99.53%  runtime.goexit
```

Does it normal that sync-gateway spends more than 1Mb of memory per connection (2 * 3Gb / 5000 connections)?

Does our config completely disables caching for sync-gateway? With enabled cache we can see even faster memory grows.

Does current memory grow is related to http gzip compression?

**Comment by adamcfraser** [comment]
3GB of memory is relatively low per Sync Gateway, but I agree that sounds like higher memory usage than expected per user.

A few followup questions:
- Are the connected clients all Couchbase Lite clients?   If so, what type of pull replication(s) are they running?  (continuous vs. one-shot, etc)
- What's your average document size?  
- When you say "near 50 requests per second to sync-gateway instances", what type of requests are you talking about?
- How many total channels do you expect to have in your deployment?  Running with a very small channel cache will reduce memory allocated to the cache, but will require additional bucket operations.  Document unmarshalling associated with those bucket operations may be memory intensive, so unless you've got a very large number of channels, it's typically more memory efficient to run with a moderately tuned channel cache, instead of attempting to disable altogether.

A few things you might try:
- You can disable compression, to evaluate whether that's causing significant memory usage in your scenario, by setting CompressResponses=false in your config
- Generating a graph of the heap profile (using the --pdf flag) will provide some more insight on which Sync Gateway operations are generating the memory usage - if you can provide that in addition to the text output you've already provided, it might shed some more light on what's going on
- Ensure that you don't have more than the expected number of active replications to Sync Gateway.  Checking the `changesFeeds_active` value in the Sync Gateway stats (`:4985/_expvar`) is probably the easiest way to check that

**Comment by ont** [comment]
> Are the connected clients all Couchbase Lite clients? If so, what type of pull replication(s) are they running? (continuous vs. one-shot, etc)

Yes, it is Couchbase Lite clients (android version).
Probably it is continuous replication. Currently main part of traffic is longpoll queries. Example for one client:
```
ont@ont-home /tmp [130]> tshark -r out.pcap -Y 'http.request.full_uri contains "4477263"' -T fields -e _ws.col.Time -e _ws.col.Info
15.484104	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
74.799551	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
202.924032	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
260.259567	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
344.241089	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
385.220277	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
451.041093	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
500.041992	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
542.702210	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
588.680343	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
631.022492	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
684.063256	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
764.885642	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
873.921187	POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=4477263 HTTP/1.1  (application/json)
```
This queries are shot every minute and got 200 responses with `{"results":[],"last_seq":"4477263"}`

HTTP query distribution for tcpdump recording:
```
38096 — total amount of http queries
22478 — POST _changes feed=longpoll
951   — POST _changes feed=normal
4196  — POST _revs_diff
4065  — POST _bulk_docs
2194  — various GET queries
4212  — other queries (mainly PUT _local/{hash})
```

> What's your average document size?

Example of typical document (json taken from couchbase server): 1220 bytes = 369 bytes data + 851 bytes for `_sync` section. Currently there are more than 6 million documents in couchbase server. Also we have `Metadata overhead warning.` messages in couchbase log.

> When you say "near 50 requests per second to sync-gateway instances", what type of requests are you talking about?

They are http requests which are reported by nginx  ngx_http_status_module. Mainly they are longpoll queries.

> How many total channels do you expect to have in your deployment?

We plan to have 30000 * 2 = 60000 channels (2 channel per user) in near future.

> Generating a graph of the heap profile (using the --pdf flag)

`go tool pprof -pdf /tmp/sync_gateway /tmp/heap.profile > /tmp/profile.pdf`

[profile.pdf](https://github.com/couchbase/sync_gateway/files/1466057/profile.pdf)


> Checking the changesFeeds_active value in the Sync Gateway stats (:4985/_expvar) is probably the easiest way to check that

Seems that it correlates with nginx reports of active connections:
```
3682 — active connections from nginx
6929 — changesFeeds_total
1139 — changesFeeds_active
```

**Comment by adamcfraser** [comment]
The longpoll behaviour you're describing sounds suspicious.  Normally a client longpoll request should block until it sees new changes (and not close and retry every minute).  We've seen issues like this in the past if the load balancer is terminating the connection.  Sync Gateway will detect and close half-closed connections in this scenario, but it can still result in significant extra work by Sync Gateway.  The face that the bulk of the memory allocation in your profile.pdf is in sendSimpleChanges suggests that this may be what's generating your high memory usage.

Have you already reviewed the [nginx documentation for Sync Gateway](https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/nginx/index.html)?  As described there, you'll want to ensure that the keep_alive_timeout and proxy_read_timeout for your nginx are longer than the heartbeat used by Couchbase Lite for changes requests (30000 ms, as seen in your _changes requests above).

**Comment by ont** [comment]
After some research and experimentation:

1. `CompressResponses=false` **greatly reduces** memory growth. Now with 2x3Gb sync-gateway configuration we can reach over 20k active connections.
2. After some hard research I can be sure that our proxy doesn't close `keep-alive` connection, so, probably, problem is not located on server. Also I can confirm probably abnormal client behaviour when server doesn't sends heartbeat after 30 seconds:
![sync-gateway](https://user-images.githubusercontent.com/350218/32888484-f9c8a756-caf9-11e7-882b-68faba6c7c16.png)
It can be seen that after 40 seconds client sends `[FIN, ACK]` tcp packet which results in the connection being closed.
3. Yes, nginx configuration was taken from documentation for sync gateway. With this configuration http version of sync-gateway endpoint sends heartbeat every 30 seconds as expected but https version **does not**.

Example of testing http version:
```
curl -iv 'http://some-site.com/babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=11475107' 
--cookie "SyncGatewaySession={some-auth-cookie}" 
-H "Content-Type: application/json" 
-d '{"style":"all_docs","heartbeat":30000,"feed":"longpoll","since":11475107}'

{"results":[
... new empty line every 30 seconds ...
```
(it does not matter whether `Connection: Keep-Alive` is sent or not)

Example of testing https version:
```
openssl s_client -connect some-site.com:443
... some debug info then I send this request:
POST /babycare/_changes?feed=longpoll&heartbeat=30000&style=all_docs&since=11475107 HTTP/1.1
Host: some-site.com
User-Agent: curl/7.56.0
Accept: */*
Cookie: SyncGatewaySession={some-auth-cookie}
Content-Type: application/json
Content-Length: 73

{"style":"all_docs","heartbeat":30000,"feed":"longpoll","since":11475107}

... no error or response from server at all...
```
... and after wating looong time there is response from https endpoint:
```
{"results":[
... multiple new lines...
{"seq":"11498078::11498083","id":"1f4404f2-2a7a-48fe-8a65-37e8c657148e","changes":[{"rev":"5-515538f21b897a6dbd273b2cdf70c0d3"}]}
],
"last_seq":"11498078::11498083"}
```

Is it because nginx caches ssl responses? Does mobile clients reacts to missing heartbeats correctly?

**Comment by adamcfraser** [comment]
It sounds like https://github.com/couchbase/sync_gateway/issues/1263 hasn't been addressed by https://github.com/couchbase/sync_gateway/pull/971.  Will try to get some attention on #1263.

**Comment by ont** [comment]
@adamcfraser I was able to fix this issue via `ssl_buffer_size 1;` nginx option. But I was really unhappy with this solution. I could not find a better solution.

**Comment by adamcfraser** [comment]
@ont Thanks for the info - that will help our investigation for a better approach.

**Comment by adamcfraser** [comment]
Closing based on age, and changes to replication persistence with the 2.x clients.  Can be reopened if shown to recur w/ current builds.
