### ISSUE TITLE
Getting EOF errors: "Couldn't interpret error type *errors.errorString, value EOF"

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#309]
In two test runs, Li's seen some warnings about EOF errors:

```
4063234:08:55:39.174927 HTTP:  #3920534: POST /db/_bulk_get?revs=true&attachments=true&n=3920057
...
08:55:39.174952 WARNING: Couldn't interpret error type *errors.errorString, value EOF -- base.ErrorAsHTTPStatus() at error.go:61
4063236:08:55:39.174986 HTTP: #3920534:     --> 500 Internal error: EOF  (0.0 ms)
```

Something is returning a standard Go EOF error (`io.EOF`). But it would be hard to figure out exactly what. My first guess would be something at the memcached layer, because there isn't much in the gateway itself that reads from raw IO streams.

**Comment by djpongh** [comment]
Will reopen if see again
