### ISSUE TITLE
Active sessions don't expire when password is changed

### ISSUE THREAD

**Issue by yoshrote** [couchbase/sync_gateway#3106]
Active sessions do not appear to expire when a user's password is changed

### Sync Gateway version
1.5

### Operating system
CentOS release 6.9 (Final)

### Expected behavior
According to the Sync Gateway API docs all of a user's active sessions expire if the user's password is modified.

### Actual behavior
Modifying the user's password via the Admin API does not invalidate existing sessions. Requests made to the Public API using a session created prior to the user change still works.

### Steps to reproduce
1.  Create a user
2.  Create a session via the Admin API
3.  Query for a document using the Public API and the session information from step 2 (of course this should work)
4.  Update the user's password
5.  Query for a document using the Public API and the session information from step 2 (this should return a 403 but instead returns the document)

**Comment by adamcfraser** [comment]
This looks like potential consequence of https://github.com/couchbase/sync_gateway/pull/3077, particularly given #3032.

Fixed in 1.5.1, needs verification.

**Comment by yoshrote** [comment]
Seems to work as expected when I built and ran 1.5.1

**Comment by adamcfraser** [comment]
@yoshrote Thanks for confirming!  Closing as fixed in 1.5.1.
