### ISSUE TITLE
Closing a db should stop any sg-replicate replications

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3113]
From @adamcfraser:

>  It feels like TestDocumentChangeReplicate may leave things running, when it's supposed to be just an API test. That might point to an underlying problem w/ _replicate - that sg-replicate processes/goroutines don't get terminated when a database is closed.

**Comment by adamcfraser** [comment]
TestDocumentChangeReplicate should be re-enabled when this is fixed, and the 10s sleep at the start of the test needs to be removed.
