### ISSUE TITLE
How to work with couchbase sync gateway and webhook (for realtime web App) ?

### ISSUE THREAD

**Issue by mahdi-gh33** [couchbase/sync_gateway#3114]
I have a angular dashboard and nodejs server behind it.I use couchbase sync gateway for insert my documents. Now I want to have realtime map in my dashboard to show the docs which their `docType=='Location' ` I don't know how I can have new docs in my front app when new location was sent to my couchbase server. I read somthing about webhook but I don't know How I should work with that.

**Comment by adamcfraser** [comment]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!
