### ISSUE TITLE
[Perf] SG read operation (get doc by id)  performance degradation in 2.0.0

### ISSUE THREAD

**Issue by agyryk** [couchbase/sync_gateway#3117]
Test scenario:
1) load documents to CB via SG
2) read random doc by id:  GET  _/db/<doc_id>_  (revision not specified)
3) measure max Throughput (ops/sec)

For 1-node SG setup, the numbers are
build 1.5.0-582:  27,653 ops/sec
build 1.5.1-4:   28,649  ops/sec
build 2.0.0-683:  15,064 ops/sec

All results: http://showfast.sc.couchbase.com/#/timeline/Linux/syncgateway/read/all

Stats comparison (1.5.1-4 versus 2.0.0-683):
http://cbmonitor.sc.couchbase.com/reports/html/?snapshot=hebe_200-683_run_test_e03a&snapshot=hebe_151-4_run_test_56de
(.190-.194 are CB hosts, .204 is SG host)

According to Adam, there's been a change in 2.0.0 to use the rev cache for GET requests w/ no rev specified. This has a performance benefit for rev cache hits.
But since current test doesn't specify any revs in the request the slowness might be caused by rev cache misses.

I'm going to add "GET by docid + rev" test scenario to the scope as well. Will update this ticket with new results as soon as its done

[cpu_and_heap_prof.zip](https://github.com/couchbase/sync_gateway/files/1708558/cpu_and_heap_prof.zip)

**Comment by adamcfraser** [comment]
In 1.5.1, Sync Gateway bypassed the rev cache for documents requested w/out a rev, so the work being done for a GET operation by this test was:
 - Get document from bucket
 - Unmarshal document body + metadata
 - Validate security access
 - Marshal document body, return

In 2.0.0, SG attempts to use the rev cache for documents requested w/out a rev, which results in the following:
- Get document from bucket
- Unmarshal metadata to get current rev id
- Attempt to retrieve document body from rev cache
- Rev cache hit:
      - Validate security access
      - Marshal document body, return
- Rev cache miss:
      - Unmarshal document body
      - Update rev cache
      - Validate security access
      - Marshal document body, return

On a rev cache hit, we'd expect a moderate performance improvement, as we're avoiding unmarshalling the document body. 

On a rev cache miss, we're doing more work than in 1.5.1, due the churn of updating the cache.

In this test, where the number of docs in the dataset are much larger than the rev cache, we're only hitting the rev cache about 0.1% of the time (see syncGateway_stats__revisionCache_hits, syncGateway_stats__revisionCache_misses [here](http://cbmonitor.sc.couchbase.com/reports/html/?snapshot=hebe_200-683_run_test_e03a)

**Comment by adamcfraser** [comment]
What we care about most is the performance when the doc id **and revid** are specified on the GET request, as this is what is done during CBL replication.  Given the testing so far, I'm expecting retrieval by doc id and rev id to be WORSE than just doc id in this scenario (doc set >>> rev cache size), since it's going to be generating the same rev cache churn.

We need to review how items are added to the rev cache to try to reduce the overhead associated with cache misses.

**Comment by adamcfraser** [comment]
Even in the 99.99% rev cache miss case, Get w/out rev (GetActive) is still showing about 50% less 
throughput than Get w/ rev.  This is unexpected - both need to retrieve the document from the bucket once, unmarshal once, and insert into the rev cache once.

Under low concurrency (single YCSB, multiple threads) this difference isn't seen.  

Benchmark of rev cache miss scenario (no concurrency) shows no significant difference in throughput, memory allocation:
```
BenchmarkReadOps_GetRevCacheMiss/Admin_Simple-8         	  100000	    195349 ns/op	   31680 B/op	     590 allocs/op
BenchmarkReadOps_GetRevCacheMiss/Admin_WithRev-8        	  100000	    196360 ns/op	   32192 B/op	     592 allocs/op
BenchmarkReadOps_GetRevCacheMiss/User_Simple-8          	  100000	    239480 ns/op	   37767 B/op	     692 allocs/op
BenchmarkReadOps_GetRevCacheMiss/User_WithRev-8         	   50000	    249015 ns/op	   38288 B/op	     694 allocs/op
```

**Comment by adamcfraser** [comment]
High-level overview of difference between get w/ rev and get w/out rev:

With Rev (faster in high-concurrency perf test):
```
- Get rev cache lock
  - Look up rev cache value (miss)
  - Create empty rev cache value
 	- Push to front of lrulist
 	- Pop oldest in lrulist
 	- Purge rev cache value for oldest
  - Release rev cache lock
- Get rev cache value lock
   - Get doc from bucket
      -  Unmarshal metadata
      -  Unmarshal doc body
   - Update rev cache value based on body, metadata
   - Release rev cache value lock
- Return result
```
Without Rev (slower in high-concurrency perf test):
```
- Get doc from bucket
  - Unmarshal metadata
  - Retain doc body as raw bytes
- Get rev cache lock 
  - Look up rev cache value (miss)
  - Create empty rev cache value
  	- Push to front of lrulist
 	- Pop oldest in lrulist
 	- Purge rev cache value for oldest
  - Release rev cache lock
- Get rev cache value lock
   - Unmarshal doc body
   - Update rev cache value based on body, metadata
  - Release rev cache value lock
- Return result
```

Here `rev cache lock` is the mutex for the entire cache, and `rev cache value lock` is the mutex for an individual docid/revid pair.

The main difference from a concurrency perspective is that in the first (faster) case, the document retrieval from the server is being done while holding the rev cache value lock.  However, there shouldn't be high contention on the rev cache value lock in this scenario - it's a few hundred clients picking random documents from a set of 1M, so it would be rare that they are trying to retrieve the same document concurrently. 

Given that, a remaining difference is the deferred unmarshalling of the document body in the slower case.  Plan to provide a build for perf to test without the deferred unmarshalling to test whether that's a factor.

**Comment by adamcfraser** [comment]
This has been found to be a side effect of moving to go 1.9.  Have moved the build back to go 1.8.5, which doesn't show this performance degradation based on initial performance testing.

**Comment by adamcfraser** [comment]
Full weekly perf run completed, and perf degradation is gone after rolling back to go 1.8.5.
