### ISSUE TITLE
Kick off integration tests against master after PR merges

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3120]
If a PR is merged that breaks an integration test, we should know about it ASAP.

## Separate Jenkins job

- We could setup notifications and have a clean history
- Downside: more jobs to maintain

## Interleaved in existing Jenkins job

- Is there a way to send conditional notifications based on params?  (eg, if branch=master)
- Is there a way to get a filtered view/search of the history?

**Comment by djpongh** [comment]
Filed: https://issues.couchbase.com/browse/MB-27408 to track.
