### ISSUE TITLE
Linking a SG user to Checkpoints

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/sync_gateway#3135]
Currently there is no way to link a Sync Gateway user to a checkpoint that was created except through mining the Sync Gateway logs.

The ask is "How can I track when a user last synced?"

N1QL?
Could we leverage xattr and have SG put in UserID in them?

**Comment by Fujio-Turner** [comment]
With xattr now is there a way to put USER name + _changes feed  bychannel info in xattr.
That way you can query user and what channels they want + the last_seq inside the checkpoint to figure out if they sync a document belonging to a particular channel.

We could even do a N1QL joint on KEYs to get Roles doc  & admin_channel data .

**Comment by tleyden** [comment]
I think this is better in an email to the mobile-interest mailing list and highlight PM input.  

Github should be reserved for tasks that have clear-cut action items, whereas this will need some discussion / debate before it's on engineering's plate to implement.
