### ISSUE TITLE
start_last_seq from sg-replicate active_tasks always set to 0

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3137]
In https://github.com/couchbaselabs/couchbase-mobile-portal/pull/833/files, there was an entry for:

```
                start_last_seq:
                   type: integer
                   description: TODO
```

However I don't see anything in the codebase that is calling `ReplicationStats.SetStartLastSeq()`, so the field appears to always be 0.  I'm removing it from the docs for the time being.

**Comment by adamcfraser** [comment]
Addressed by upcoming active_tasks changes in Hydrogen.
