### ISSUE TITLE
SG is throwing error "PANIC handling BLIP request"

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3144]
### Sync Gateway version
2.0.0-687

### Operating system
CentOS

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+", "Import+"],
    "databases":{
        "db":{


            "unsupported": {
                "allow_conflicts": false,
                "replicator_2":true
             },
            "revs_limit": 5,
            "rev_cache_size": 1000,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password"
        }
    }
}

```

### Log output

sync-gateway logs : 

```
2017-12-13 11:36:56.899322 I | *** PANIC handling BLIP request MSG#376!~: runtime error: index out of range:
goroutine 4005 [running]:
runtime/debug.Stack(0xc42058db50, 0xb54400, 0x11fd640)
        /usr/local/go/1.9/go/src/runtime/debug/stack.go:24 +0xa7
github.com/couchbase/go-blip.(*Context).dispatchRequest.func1(0xc4203f2750, 0xc4201b2380)
        /home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/go-blip/context.go:107 +0xab
panic(0xb54400, 0x11fd640)
        /usr/local/go/1.9/go/src/runtime/panic.go:491 +0x283
github.com/couchbase/sync_gateway/rest.(*blipHandler).handleProposedChanges(0xc4204682f0, 0xc4203f2750, 0xc3230b, 0xc)
        /home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/blip_sync.go:394 +0x627
github.com/couchbase/sync_gateway/rest.(*blipSyncContext).register.func1(0xc4203f2750)
        /home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/blip_sync.go:110 +0x25c
github.com/couchbase/go-blip.(*Context).dispatchRequest(0xc420498750, 0xc4203f2750, 0xc4201b2380)
        /home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/go-blip/context.go:126 +0x159
github.com/couchbase/go-blip.(*receiver).handleIncomingFrame.func1(0x0, 0x0)
        /home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/go-blip/receiver.go:110 +0x3f
github.com/couchbase/go-blip.(*Message).asyncRead.func1(0xc4203f2750, 0xc420536088, 0xc4207463c0)
        /home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/enterprise/godeps/src/github.com/couchbase/go-blip/message.go:336 +0x5e
created by github.com/couchbase/go-blip.(*Message).asyncRead
        /home/couchbase/jenkins/workspace/sgw-unix-build@2/2.0.0/ent

```

CBL logs : 
12-14 19:34:55.191 10653-10716/com.couchbase.androidclient I/LiteCore [Sync]: {3} Read 4 changes: Pusher sending 'changes' with sequences 362 - 365
12-14 19:34:55.193 10653-10719/com.couchbase.androidclient E/WebSocket: WebSocketListener.onMessage() bytes -> f602120d0300424c49500002003530300050616e69633a2072756e74696d65206572726f723a20696e646578206f7574206f662072616e6765
12-14 19:34:55.193 10653-10719/com.couchbase.androidclient E/C4Socket: C4Socket.callback.completedReceive() socket -> 0xad6f4d28, byteCount -> 57
12-14 19:34:55.193 10653-10716/com.couchbase.androidclient I/LiteCore [Actor]: Push->blip:192.168.33.11:4985/db/_blipsync performNextMessage
12-14 19:34:55.193 10653-10716/com.couchbase.androidclient E/LiteCore [Sync]: {3} Got error response: BLIP 500 'Panic: runtime error: index out of range'

### Steps to reproduce
1.   Set up couch base server, sync-gateway, 
2. I have set up CBL on android app and used DB 20 Android API in the app.
3. In android app, scenario covered  
4.  Start replication(push and pull)
5 . Create docs
6. update docs randomly until the specified timeout

### Expected behavior
Changes should get pushed successfully 

### Actual behavior
Looks like some times more changes getting pushed and throwing an error. 
When I look at the logs on android, most of the time changes it is trying to push is 1 or 2 , then I do not see this error, I see only when it tries to push changes more than 2.

Note : It is race condition. It is not happening all the time. 
I tested with no conflicts mode

**Comment by tleyden** [comment]
Possible cause -- the client is sending a blip message body w/ the `changes` profile format when it's using the `proposedChanges` profile

**Comment by tleyden** [comment]
@snej as a follow up to this question in https://github.com/couchbase/sync_gateway/pull/3138#issuecomment-355426248.  I just wanted to mention the context of this ticket, where the CBL client is sending blip messages with a profile of `proposedChanges`

This issue is filed under Sync Gateway, but may be a client issue (see https://github.com/couchbase/sync_gateway/issues/3144#issuecomment-355439911)

Also it's probably worth calling out that Sync Gateway will currently *reject* messages with the  `changes` profile in no-conflicts mode, which makes me think that CBL 2.0 clients are configured to use `proposeChanges` in certain cases.

```
func (bh *blipHandler) handlePushedChanges(rq *blip.Message) error {
	if !bh.db.AllowConflicts() {
		return base.HTTPErrorf(http.StatusConflict, "Use 'proposeChanges' instead")
	}
        ....
}
```

**Comment by tleyden** [comment]
@sridevi-15 can you enable verbose blip replication logs in CBL that dumps the messages being sent?  If you post those logs to the ticket, then I will try to verify whether it's conforming to the [replication spec](https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Protocol#proposechanges) for `proposedChanges`.

This will help determine whether it's a CBLite or a Sync Gateway bug.

I'm not sure if we have docs on how to enable the blip replication logs, but if not then please file a docs issue since this will be crucial in the absence of a wireshark dissector.

**Comment by tleyden** [comment]
I was able to reproduce the issue w/ this test:

```
// Attempt to repro https://github.com/couchbase/sync_gateway/issues/3144 with following steps
// 1. Start sync gateway in no-conflicts mode
// 2. Send changes push request with multiple doc revisions
// 3. Make sure there are no panics
func TestMultipleChangesNoConflictsMode(t *testing.T) {

	bt := CreateBlipTester(t, true)
	defer bt.Close()

	proposeChangesRequest := blip.NewRequest()
	proposeChangesRequest.SetProfile("proposeChanges")

	// According to proposeChanges spec:
	// proposedChanges entries are of the form: [docID, revID, serverRevID]
	// where serverRevID is optional
	changesBody := `
[["foo", "1-abc"],
["foo2", "1-abc"]]
`
	proposeChangesRequest.SetBody([]byte(changesBody))
	sent := bt.sender.Send(proposeChangesRequest)
	assert.True(t, sent)
	changesResponse := proposeChangesRequest.Response()
	log.Printf("changesResponse: %v", changesResponse)

	// TODO: this test currently panics with https://gist.github.com/tleyden/5ba6e759dc1f99abc48fff8a0160c1c5

}
```

Looks like this cause is this Sync Gateway code:

```
func (bh *blipHandler) handleProposedChanges(rq *blip.Message) error {

	for i, change := range changeList {
		docID := change[0].(string)
		revID := change[1].(string)
		parentRevID := ""
		if len(change) >= 2 {  // <-- should be checking if len(change) > 2
			parentRevID = change[2].(string)
		}
```

I'll fix it on the `feature/issue_2653_blip_active_replicator` branch that I'm currently working, since it will have an added unit test that catches the issue.
