### ISSUE TITLE
GSI Index and query for channels view

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3145]
Define GSI replacement for channels view.  Query output doesn't need to be identical to view output, but must provide the same functionality.

**Comment by adamcfraser** [comment]
Initial index, query, plan here:
https://gist.github.com/adamcfraser/6fb52527e44464843fb98dab8adf41bf

Is functionally complete, but needs performance improvements to:
- [ ] Use covering index
- [ ] Use span instead of filter for sequence range

**Comment by Fujio-Turner** [comment]
@adamcfraser ,

In the future using a prepared statement / named query might get you a little more performance since SG will do channel query millions of times a year.

https://developer.couchbase.com/documentation/server/4.0/n1ql/n1ql-language-reference/prepare.html
