### ISSUE TITLE
Allow custom headers in Webhooks

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#3147]
At the moment, we're somewhat limited in what we can pass with a remote endpoint with a webhook. We can do basic auth in the `http://user:pass@couchbase.com/` pattern, but not anything more complex.

Given that we essentially wrap a `net/http` request, I don't think it should be too difficult to allow specifying custom headers alongside the request.

**Comment by JFlath** [comment]
Unless/until other people pile on, I think it's only me who currently wants this, so I might take a look at raising a PR myself...

**Comment by adamcfraser** [comment]
Closing based on age - can be reopened in JIRA based on priority.
