### ISSUE TITLE
Allow formatting/customisation of DocumentChangeEvent webhook data 

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#3148]
Currently, we allow posting the entire document on a DocumentChangeEvent with webhooks.

https://github.com/couchbase/sync_gateway/blob/0ada307c70924a18ba2abd44d566a3c8e04baadf/db/event_handler.go#L91-L99

In some cases we'd want to notify another system that a document has changed, but not send the whole document. Instead, it'd be nice if we could specify *what* gets posted. I can see a few sensible options, like:

* Full Doc
* Doc ID/Rev
* Specified fields

but I wonder if something more customisable for the implementation might be better. For example, passing in some JS à la the Sync Function that is expected to return a JSON object to be posted. That way you could do things like:

```
function(doc){
    return doc;
}
```
```
function(doc){
    return {"_id" : doc._id, "_rev": doc._rev};
}
```
```
function(doc){
    return {"type" : doc.type};
}
```

Maybe this could be merged with the filter, rather than having two separate...

**Comment by adamcfraser** [comment]
Closing based on age - can be reopened/prioritized via JIRA.
