### ISSUE TITLE
Uptake the latest gocb for ipv6 support

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#3157]
The latest gosdk can talk to a single node cluster over ipv6. This is a tracking ticket to get the latest gocb changes into sync gateway

**Comment by suravarjjala** [comment]
Adam this should be targeted for 2.1.0 as P1:High in line with the Server release

**Comment by bbrks** [comment]
Fixed in #3250 (merged into dev branch for 2.1.0 release)
