### ISSUE TITLE
Add mutex contention to sgcollect_info

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3162]
From https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/:

"First – when working with pprof it’s good to be running a recent version of Go! For example Go 1.8 adds mutex profiles so you can see mutex contention." 

This seems like a very useful addition to sgcollect_info.

/cc @JFlath

**Comment by bbrks** [comment]
Already in Cobalt

https://github.com/couchbase/sync_gateway/pull/3998
