### ISSUE TITLE
Blip replication does not work in DI mode

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3165]
### Sync Gateway version
2.0.0 -> Tested with 2.0.0-683, 2.0.0-722

### Operating system
Centos

### Config file
```javascript
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://192.168.33.10:8091",
        "data_dir":".",
        "bucket":"data-bucket",
        "username":"data-bucket",
        "password": "password"
    },
    "databases":{
        "db":{
            "unsupported": {
                "replicator_2": true
            },
            "revs_limit": 30,
            "rev_cache_size": 1000,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "channel_index":{
                "num_shards":16,
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket",
                "username": "index-bucket",
                "password": "password",
                "writer":false
            }
        }
    }
}
```

### Log output
https://gist.github.com/sridevi-15/d1360d52e37ce6850b1f3006606c44f7

### Steps to reproduce
1.  Create db and docs in CBL 
2.  Enable blip replication on SG 
3.   start replication with continous to SG
4. Verify docs got replicated in SG

### Expected behavior
It should replicate to SG successfully and should be able to see docs in SG 

### Actual behavior
What actually happened?
Docs did not get replicated in SG and it throws an error in sg logs -> check the log output in gist

**Comment by tleyden** [comment]
Most likely the SG handler is creating a channel cache style sequence value rather than a vector clock sequence

Todo:

- [ ] Unit test to repro

**Comment by tleyden** [comment]
I'm able to manually repro this on the sync gateway `feature/issue_2653` branch running SG + SG-Accel, and using the Todo sample app on the feature/2.0 branch.

Error in SG logs:

```
2018-01-09T15:51:04.162-08:00 Changes+: Vector multi changes feed...
2018-01-09T15:51:04.162-08:00 Changes+: Vector MultiChangesFeed(channels: {*}, options: {Since:0 Limit:0 Conflicts:true IncludeDocs:false Wait:true Continuous:true Terminator:0xc4201c2c60 HeartbeatMs:0 TimeoutMs:0 ActiveOnly:false}) ...   (to user1)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x150163e]

goroutine 281 [running]:
github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).SetTo(0xc4207988a0, 0x0, 0x0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:257 +0x3e
github.com/couchbase/sync_gateway/base.(*SyncSequenceClock).SetTo(0xc4203d63e0, 0x0, 0x0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:438 +0x85
github.com/couchbase/sync_gateway/db.(*Database).VectorMultiChangesFeed.func1(0xc42071c0d0, 0xc, 0xc420532120, 0xc420864000, 0xc420798300, 0xc420396280, 0xc42009002c)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/index_changes.go:79 +0x24a
created by github.com/couchbase/sync_gateway/db.(*Database).VectorMultiChangesFeed
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/index_changes.go:37 +0x248
```

It completely crashes the Sync Gateway.

**Comment by hrajput89** [comment]
I've tried the replication with SG 2.0.0-747 build and SG Accel -747 in DI mode and I'm getting below error.

From  sync_gateway_error.log 
2018-01-15T17:00:19.435Z BLIP: Error: Client doesn't support WS protocol BLIP_3a2, only 
2018-01-15T17:00:19.435Z HTTP+: #002:     --> 200   (90.7 ms)

From CBL todo2.0 app

E/ListsAdapter: result -> {$1=1, id=hemant.4ab3c017-4d54-4f91-a41b-0f7009b11732}
E/ListsAdapter: result -> {$1=1, id=hemant.4fc06368-8693-4053-a5e4-5bd8c575e16b}
E/WebSocket: WebSocketListener.onFailure() response -> Response{protocol=http/1.1, code=403, message=Forbidden, url=http://192.168.0.112:4984/todo/_blipsync}
             java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
                 at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:219)
                 at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:186)
                 at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                 at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                 at java.lang.Thread.run(Thread.java:761)

**Comment by hrajput89** [comment]
attaching SG error log file 
[sync_gateway_error.log](https://github.com/couchbase/sync_gateway/files/1632425/sync_gateway_error.log)

**Comment by adamcfraser** [comment]
Based on that log excerpt, it looks like you need to move to the latest CBL client that supports the recent compression changes (included in https://github.com/couchbase/go-blip/commit/9cbef5227a0304d736e34387b65e5344502312f3#diff-a33afa00c75a82ea9f6770d2746f3345).

**Comment by tleyden** [comment]
I'm going to close this proactively, please re-open w/ CBL client versions if you're still seeing errors
