### ISSUE TITLE
Data race in TestChangeIndexCompactSingleTombstone

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3173]
Causes intermittent build failures.
  
Sample failures:
http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-unix-build/5059/
http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-unix-build/5054/

**Comment by adamcfraser** [comment]
For the race in 5059, it looks like there a race in accessing ChannelWriter.lastUpdated.

This should get fixed in ChannelWriter - it should use its own mutex to manage read/write of lastUpdated, and create accessors for lastUpdated that go through the mutex.

**Comment by bbrks** [comment]
Fixed in #3196
