### ISSUE TITLE
Add sglog() javascript function to make it easier to debug Sync Functions

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3190]
## Problem

Currently it's inconvenient to debug sync functions.  The emitted logs have no timestamps, are visually mis-aligned, and cannot be controlled via log keys.

This change would add an `sglog()` javascript function which would take a single argument.  Callers would have to preformat the string rather than passing a format string w/ variadic args.

## Tasks

- [ ] Implementation
- [ ] Add documentation
- [ ] Update todo example sync function to have logging
- [ ] Verify correct behavior specifically on Windows machines

## Implementation

In `sync_runnner.go`

```
	runner.DefineNativeFunction("sglog", func(call otto.FunctionCall) otto.Value {
		base.LogTo("SyncFn", "sglog message: %v", call.Argument(0))
		return otto.Value{}
	})
```

**Comment by Fujio-Turner** [comment]
It be great to be able to toggle the sglog() on and off.
Below I have to change and redeploy the sync function by uncommenting out the 
`//console.log()`
Which require a resync by SG

```
function(doc){
 if(doc.type === "water"){
     channels(doc.channels);
     //console.log("water")
 }else{
    //console.log("not water")
 }
}
```

**Comment by adamcfraser** [comment]
I agree that toggling without redeploying the sync function is nice, but it's not necessarily the case that you'd need to run a resync.  A resync is only required if there's a change to the channels or access grants that would be calculated by the sync function, AND you want those changes to be recalculated for docs that have already been processed.

**Comment by Fujio-Turner** [comment]
Team,

The above
`console.log()`
I have found don't always work on windows machine.
Could you test sglog() on windows based machines.

Thank you

**Comment by tleyden** [comment]
@Fujio-Turner interesting note about Windows.  I think that gives more ammunition to this ticket.

I added a checkbox to the sub-task list based on your comment.

**Comment by mglasgow** [comment]
+1 to this. I just upgraded my couchbase to use the log rotation configuration. Now the sync gateway console.log lines I have are written to console while the rest is written to file, leaving me no context at all. It would be great to be able to replace console.log with a function which actually logged to the same file.

**Comment by bbrks** [comment]
Issue now tracked by [CBG-200](https://issues.couchbase.com/browse/CBG-200)
