### ISSUE TITLE
Revision cache enhancements for high rev cache miss scenarios

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3203]
In scenarios with high rev cache miss rates, the performance overhead of inserting into the rev cache can outweigh the caching benefits.  

See https://github.com/couchbase/sync_gateway/issues/3117 for additional details

To evaluate potential enhancements, we want to do the following
- [ ] Write benchmarks to evaluate the performance overhead in a high cache miss scenario
- [ ] If the benchmarks determine that waiting for RevisionCache.lock is a bottleneck, add the ability to bypass the rev cache when there's a large queue for the lock (may require rewriting the lock as a custom queue).

**Comment by adamcfraser** [comment]
This is on hold pending the results of perf testing w/ #3204.

**Comment by bbrks** [comment]
Done as part of 2.6.0 https://issues.couchbase.com/browse/CBG-327
