### ISSUE TITLE
SG 1.5.1 becomes unresponsive after updating a document

### ISSUE THREAD

**Issue by jamescooke** [couchbase/sync_gateway#3212]
Original forums post is here: https://forums.couchbase.com/t/errors-in-sg-1-5-1-with-cb-5-0/15442 - since that was posted we've been able to find more info which is listed below.

We have an issue when syncing using SG 1.5.1 on top of CB 5. We've narrowed this down to a certain document which is around 500K of data, 2500 revisions and 80 conflicts. When we update this document via the admin port or via Couchbase Lite sync, the SG goes offline. It appears that connecting to the database in the cluster from SG is timing out.

In our worst case this time out has taken 40 minutes to resolve, however, it's not clear if there were other requests making it through to SG and creating more issues. In the best cases, we've had this resolve in 2 minutes - however, that does mean 2 minutes of downtime for our clients which is not acceptable in our production environment.

### Sync Gateway version

Couchbase Sync Gateway/1.5.1(4;cb9522c)

### Operating system

Ubuntu 16.04.3 LTS

### Config file

```javascript
{
  "interface": "localhost:4984",
  "adminInterface": "[IP address]:4985",
  "CORS": {
    "Origin":["https://[url]","https://[url]"],
    "Headers":["Authorization","Content-Type"]
  },
  "maxFileDescriptors": 250000,
  "databases": {
    "[database]": {
      "server": "http://cb01:8091",
      "bucket": "[bucket]",
      "username": "[user]",
      "password": "",
      "unsupported": {
        "user_views": {"enabled":true},
        "enable_extended_attributes": {"enabled":false}
      }       
    }
  },
  "logging": {
    "default": {
      "logFilePath": "/var/log/sync_gateway/sync_gateway_access.log",
      "logKeys": ["HTTP"],
      "logLevel": "debug",
      "rotation": {
        "maxsize": 1,
        "maxage": 30,
        "maxbackups": 7,
        "localtime": true
      }
    }
  }
}
```

### Log output

Here is the log after the update of a document happens via Couchbase Lite - you can see the update on `_local` and then SG locks up. This is the full output from our SG, I've added some notes but not deleted any lines: https://gist.github.com/jamescooke/2b3eb428d3518bf57264b82a7699728d

### Expected behavior

The document should have been updated and SG should have remained responsive.

### Actual behavior

The document is updated and SG starts timing out. Time outs break sync and login and GET requests to the database on the Admin port. No users can use SG during this outage as far as we can tell.

### Steps to reproduce

We've narrowed this issue down to the update of a particular set of documents which we call "snag codes". An example of a snag codes document is here: https://gist.github.com/jamescooke/6f3fe93d65d0c382fe0e93433ec06ce2 (I've pretty printed it to make it more human-readable)

1. Couchbase Lite syncs its database that includes a snag codes document.

2. Couchbase Lite updates any content in the document while online.

3. Change is received on SG and SG becomes unresponsive.

Alternatively, we can also reproduce by updating the document via the admin port:

1. Retrieve a snag code document.

2. Add a field `"james_test": true`.

3. Update document with PUT.

4. SG becomes unresponsive.

#### Health check

Our server hits the database and expvars endpoints every 5 seconds to collect information. This generates these lines in the log when this behaves normally:

```
2018-01-16T11:29:40.724Z HTTP:  #089: GET /construct/  (ADMIN)
2018-01-16T11:29:40.731Z HTTP:  #090: GET /_expvar  (ADMIN)
2018-01-16T11:29:40.731Z HTTP: Recording snapshot of current debug variables.
```

This check takes an average of ~40ms on SG 1.4 and ~20ms on SG 1.5.

#### Work arounds

* We've found that we can run SG 1.4 on top of the same cluster using `"feed_type": "DCP"` in the database settings and the problem goes away. This is what we've reverted to in production to ensure that our system stays up.

* We have found that by increasing the `serverReadTimeout` and `serverWriteTimeout` settings we're able to write the document via the admin port without the SG falling over. This is the success log: https://gist.github.com/jamescooke/545482d75ef3310d0e78965d495cad40

    However, even when we've got the document update request to work via the Admin port, for 20 - 30 seconds after that, the responsiveness of our health check goes down from 20ms to 1 to 2s.

**Comment by adamcfraser** [comment]
@jamescooke The document itself seems fine.  I suspect this may be related to processing the revision history for the doc.

Can you stick the raw document (either from the bucket, or via SG's `/[db]/_raw/[docid]` endpoint) in a gist?

Do you expect this document to have a large number of conflicting revisions?

**Comment by adamcfraser** [comment]
In particular - if the 80 conflicting revisions you mentioned are of similar size to the winning revision you've provided, then the total doc size is likely to be approaching Couchbase Server's doc size limit of 20MB.  Given that the operations are succeeding when you increase the timeout, I'm assuming you haven't quite reached the limit.

The difference in behaviour between SG 1.4.1 and 1.5.1 is possibly related to the change in Couchbase SDKs used by Sync Gateway, in particular around timeout handling.  If you can share the full document, I can work to repro and identify any potential fixes/workarounds.

**Comment by jamescooke** [comment]
@adamcfraser Thanks for the reply and insights :+1: 

`curl` reports the size of the `_raw` download as `19.7M` - so it's getting close to that 20M limit. The raw document is here: https://gist.github.com/jamescooke/211c7262eae7595018179f90c4cef1ac

> Do you expect this document to have a large number of conflicting revisions?

Information from @skela : "... expect lots of revisions, and lots of conflicts ... this document is updated frequently, by multiple clients , sometimes at the same time"

Today we've been experimenting with rolling a test cluster forwards to xattrs / shared bucket access with positive results: The snag docs get successfully migrated (as per "CRUD+" and "IMPORT+" logging) and a test iOS client can update one of the docs without the SG going offline.

**Comment by adamcfraser** [comment]
@jamescooke Thanks for the additional details.  When running w/ xattrs enabled, one side effect is that conflicting revision bodies will be stored as separate documents - which I think would generally help in your scenario (as you've seen).

In SG 1.4 Sync Gateway established separate CBS connections per request, with a limit on the number of concurrent connections to the server cluster. 

In 1.5, Sync Gateway (with the switch to the gocb SDK), it's using a pipeline per CBS node for requests.  Requests are sent asynchronously, and in general results in much higher throughput than SG 1.4.  In your scenario, the problem may be down to the cumulative effect of timeouts on large requests.  The `serverReadTimeout` and `serverWriteTimeout` properties only modify SG's HTTP server timeouts.  Since modifying those alleviates the problem, it suggests that both SG's internal timeout on the gocb request as well as the client's timeout/retry handling are exacerbating the problem.

I'm looking into what can be done on timeout to avoid this cascading effect - will post findings here.

**Comment by adamcfraser** [comment]
As a side note, I suspect this won't be the only performance overhead associated with a large (500K) document that expects to have multiple authors and frequent conflicts.  If there are good reasons that you need to use this data model, at minimum I'd recommend an aggressive conflict resolution strategy to ensure the conflicts aren't long-lived.

**Comment by adamcfraser** [comment]
@tleyden @bbrks We want to build a simple repro scenario using gocb only (not full SG) to be able to evaluate options for terminating in-flight requests based on client timeout:
 - Send write requests for relatively large (10MB+) documents 
 - Simulate client-side request timeouts on those requests, with client retry on timed out requests
 - Investigate whether it's possible to remove in-flight requests from gocb's queue on timeout

**Comment by adamcfraser** [comment]
Initial step (for 2.1.0) is to build the gocb-based repro case, so that we can review w/ SDK team.
