### ISSUE TITLE
"Sequence" field appears to be ignored in blip sync "rev" request handler

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3215]
In the [replication protocol spec for rev](https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Protocol#rev) it states:

> sequence: Sequence ID, JSON-encoded (optional unless unsolicited, q.v.)
> The sequence property is optional unless this message was unsolicited.

However in `handleAddRevision` that field seems to be ignored:

https://github.com/couchbase/sync_gateway/blob/8aca5f03d8493744bf1a15db53b7bdbbcbb35cf8/rest/blip_sync.go#L499-L537

Is it being used in `handleAddRevision()` and I'm not seeing it, or was this an oversight in `handleAddRevision()`, or should the replication protocol be updated?

**Comment by snej** [comment]
`sequence` is used for tracking the latest sequence replicated, which is used for updating the checkpoint. The reason SG ignores it is because SG is a purely passive replicator that doesn't manage any checkpoints of its own.
