### ISSUE TITLE
Add blip replication heartbeat mechanism

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3216]
From discussion in https://github.com/couchbase/go-blip/issues/12:

> we should have a period heartbeat that sends data over the socket periodically, as in the REST changes feed.

Without this, intermediate proxies and load balancers might close connections it determines to be idle, due to no replication activity.

This is a tracking ticket to implement that on the Sync Gateway side of that change.

**Comment by djpongh** [comment]
This was handled in LiteCore: https://github.com/couchbase/couchbase-lite-core/issues/356
