### ISSUE TITLE
Sync fn access() calls made on deleted revisions should be ignored

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#322]
It seems pretty clear that deleting a document should clear any channel access that it formerly granted to users or roles. This will happen by default with a normal deletion since the sync fn will be called on a revision with no properties other than `_deleted`, so it won't find any properties that would tell it to grant access.

But it's possible to create a deletion revision with other properties in it, and these could trigger the sync function into granting channel access. That seems very unintuitive and potentially confusing. ("I looked through all_docs and couldn't find any document that gave this user access to that channel! Where is it coming from?")

I suggest we make the gateway ignore any `access()` calls made in response to a deletion revision.

@jchris, do you agree?

**Comment by adamcfraser** [comment]
Generally less of a concern with 2.x and shared_bucket_access, as tombstones don't support document bodies.  Closing based on age, can reopen in JIRA if there's a compelling use case.
