### ISSUE TITLE
Automated test to run LiteCore replication tests against Sync Gateway 

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3224]
@djpongh you mentioned a ticket should get filed for this.  Putting in the Sync Gateway repo for now, but feel free to move it where you see fit.

- [ ] Depends on https://github.com/couchbase/sync_gateway/pull/3333

Upstream Jira ticket for the C4tests binary:

https://issues.couchbase.com/browse/CBD-2360

**Comment by djpongh** [comment]
since #3286 has more details, closing this as dup

**Comment by tleyden** [comment]
Closing this since https://issues.couchbase.com/browse/CBD-2360 was closed as "WON'T DO"
