### ISSUE TITLE
Continuous changes started by blipsync not terminated when connection is closed

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3225]
I used [sg-blip](https://github.com/couchbaselabs/sg-blip) to open a continuous changes feed over blip:

<img width="813" alt="screen shot 2018-01-18 at 4 52 35 pm" src="https://user-images.githubusercontent.com/296876/35129896-b6ee68c6-fc72-11e7-976d-4a8d65504c11.png">

However, the expars showed the active changes feeds at 0:

<img width="683" alt="screen shot 2018-01-18 at 4 52 45 pm" src="https://user-images.githubusercontent.com/296876/35129900-c05c64ee-fc72-11e7-8c7d-6f12e79f8c2f.png">

Currently that expvar seems to be updated in the REST handler, and might need to be moved down to `generateContinuousChanges()`

## Tasks

- [ ] Modify code to update expvar in this case
- [ ] Verify that when BLIP clients disconnect, the number of active changes goes down

**Comment by adamcfraser** [comment]
Added new expvar, discovered that continuous changes goroutines started via handleBlipSync aren't closed when the client disconnects (e.g. handleBlipSync exits).

Need to create terminator for blip context, and pass down for use by any long-running spawned goroutines.
