### ISSUE TITLE
Fix startup race in replicator.go

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3229]
The concurrency management for Replicator.replications doesn't properly prevent startup of duplicate replications when multiple replications are started concurrently.

There's a check for existing replications initially (https://github.com/couchbase/sync_gateway/blob/master/base/replicator.go#L44), but there's a gap between that read lock being released, and the write lock being taken to add the new replication to the set.  There's no subsequent duplicate check being done when adding the new replication.

The following enhancements should be made:
 - Move the existing/duplicate check down into stopReplication/startReplication
 - Get the write lock on the mutex for the entire lookup/write to replications
 - In server_context, properly handle any errors (https://github.com/couchbase/sync_gateway/blob/master/rest/server_context.go#L112)
 - Don't log 'Starting replication' messages until the replication is successfully added to the set and started (move https://github.com/couchbase/sync_gateway/blob/master/base/replicator.go#L137)
 - Since we're forcing replications to run async when they are defined in the config, we don't need to be kicking off separate goroutines here:https://github.com/couchbase/sync_gateway/blob/master/rest/server_context.go#L105

**Comment by bbrks** [comment]
Separate race detected but still occurring in sg-replicate startup. Logs:
https://gist.github.com/bbrks/40bdc3be1f7735d2489f1c04f98e9251

PR in sg-replicate for fix: https://github.com/couchbaselabs/sg-replicate/pull/56
