### ISSUE TITLE
Improve coverage of BLIP unit tests

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3236]
Enhance the set of BLIP unit tests to address all standard replication messages and improve overall coverage of blip_sync.go.

Should include coverage for:
- [x] Attachments
- [x] Checkpoints (see https://github.com/couchbase/sync_gateway/pull/3246)
- [ ] Rev message edge cases
   - [ ] Conflicts/non-winning revisions
   - [ ] Invalid revs

**Comment by tleyden** [comment]
Work in progress: `feature/issue_3236_blip_coverage`
