### ISSUE TITLE
Replication doesn't run properly for continuous update of docs

### ISSUE THREAD

**Issue by hrajput89** [couchbase/sync_gateway#3239]
I added some 1000 docs to CBL app and then for a period of 30 mins, I'm modifying random docs. Docs are not getting synced up for the updates from CBL to SG/CBS. I tried 2 ways, first, having single "PULL AND PUSH" replicator and second, having two replicator - one for "PUSH" and other for "PULL". In both ways, same behavior.

### Sync Gateway version
2.0.0.-749

### Operating system
CentOS7

### Config file
```javascript
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "databases":{
        "db":{
            {{ autoimport }}
            {{ xattrs }}
            "unsupported": {
                "replicator_2": true
            },
            "server":"{{ server_scheme }}://{{ couchbase_server_primary_node }}:{{ server_port }}",
            "bucket":"travel-sample",
            "username":"travel-sample",
            "password": "password"
        }
    }
}
```

### Log output
Provide a link to a GitHub Gist containing relevant Sync Gateway log output when
the error occured. Do NOT paste the log output in the issue, just paste the
link to the Gist.

### Steps to reproduce
1.  Run AndroidClient app from mobile-testkit branch - "cbl2.0_android" from this pat - "/Users/hemant/couchbase/couchbase/mobile-testkit/apps/testkit.java/testkit.java.android"
2.  Check the update docs getting synced to CBS and SG.
[sgcollect_info.zip](https://github.com/couchbase/sync_gateway/files/1655586/sgcollect_info.zip)

**Comment by adamcfraser** [comment]
There aren't any errors in the provided Sync Gateway logs, and there isn't enough information here to dig into this issue further.  Can you provide some additional specifics?
 - Information on specific documents that aren't being updated
 - What's the actual/expected state of those documents
 - What's the state of those documents in the bucket?
 - Client side logs/errors

**Comment by hrajput89** [comment]
I ran the app for 1000 docs for 10 min with one contionous PUSH_AND_PULL replicator. Below are the logs from CBL app and SG.

The app picks random doc and update name field. CBL app have info on the docs getting changed. For example - 

I/System.out: updating doc: doc__604
I/System.out: Before: user_604
I/System.out: After: New_user_598

[sgcollect_info.zip](https://github.com/couchbase/sync_gateway/files/1657192/sgcollect_info.zip)

[CBL.log](https://github.com/couchbase/sync_gateway/files/1657195/CBL.log)

**Comment by snej** [comment]
Thanks for the logs, Hemant, but could you turn off the `C4Socket` and `WebSocket` logging? Those are very low level and super-verbose and I have to filter them out to be able to see the useful logs. Thanks.

**Comment by snej** [comment]
From the log, halfway through:
```
I/LiteCore\'a0[Sync]: \{Repl#1\} Replication complete! Closing connection\
```
That looks like a non-continuous replication, which stopped after it finished syncing all the docs. In which case this is behaving correctly. Can you double-check that you're running a continuous replication?

**Comment by hrajput89** [comment]
@snej 
if my understanding of Replication API is correct, then I believe the replication is continuous, as I'm setting replicator as below 

`

> ReplicatorConfiguration.Builder replBuilder = new ReplicatorConfiguration.Builder(database, new URLEndpoint(uri));
>         ReplicatorConfiguration replConfig = replBuilder.build();
>         **replBuilder.setContinuous(true);**
>         BasicAuthenticator authenticator = new BasicAuthenticator("travel-sample", "password");
>         replBuilder.setAuthenticator(authenticator);
>         replBuilder.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);

`

If there is any issue in replication configuration, let me know. Will try with the modification. 

FYI, the app I'm using is available here - https://github.com/couchbaselabs/mobile-testkit/blob/cbl2.0_android/apps/testkit.java/testkit.java.android/Tests/AndroidClient/app/src/main/java/com/couchbase/androidclient/MainActivity.java

**Comment by snej** [comment]
@hrajput89, you created the ReplicatorConfiguration on line 3 of your listing. After that, any further changes to the builder won't affect the configuration (which is an immutable object.) So your replication is _not_ continuous.

**Comment by adamcfraser** [comment]
Closing, as this looks like a test issue.
