### ISSUE TITLE
Improve logging for 2.0 replication functional debugging

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3241]
- [ ] Switch back to WS/WS+/WS++ for logging done by the go-blip library (via callback)
- [x] Use "Sync/Sync+" for SG contextual logging in blip_sync
- [x] Use "SyncMsg"/"SyncMsg+" in the same way "HTTP" and "HTTP+" are used for 1.x REST calls.  
  - [x] Should log "SyncMsg" once at the start of each handler.  SyncMsg should include at least the same information that was available for the corresponding HTTP request in 1.x.  Parameters should not be logged if they aren't present
     - getCheckpoint (all parameters)
     - setCheckpoint (all parameters)
     - subChanges (all parameters)
     - changes (length of array)
     - proposeChanges (length of array)
     - rev (all parameters except history)
     - getAttachment (all)
     - proveAttachment (all)
  - [x] Should log "SyncMsg+" in a defer when leaving each handler (note that async handlers like subChanges would need to log when their goroutine exits).  Should include status code similar to HTTP+
  - [x] Timing information on SyncMsg+ similar to HTTP+
  - [x] Numbering on the SyncMsg logging (like "#1"), so that we can correlate SyncMsg with their corresponding SyncMsg+
  - [x] Reduce blip context to 32 bit number

**Comment by tleyden** [comment]
@jamiltz this is another change to the logging config.  The "low-level" blip logging will be enabled via:

1. BLIP
1. BLIP+
1. BLIP++

which users will not typically need.

The higher level Sync Gateway 2.0 replication logging will be enabled via:

1. `Sync` and `Sync+` for SG contextual logging in blip_sync
1. Use "SyncMsg"/"SyncMsg+" in the same way "HTTP" and "HTTP+" are used for 1.x REST calls.

and this is something users will typically need.

**Comment by adamcfraser** [comment]
As discussed, should switch BLIP to WS/WS+/WS++.  Similar to gocb and DCP, these shouldn't be enabled w/ log "*".

**Comment by tleyden** [comment]
Sounds good

**Comment by jamesnocentini** [comment]
I think this [doc commit](https://github.com/couchbaselabs/couchbase-mobile-portal/commit/b7aa447c3f4a24a65c26e2ae1d083bd4efe1ece9) is enough for users to know about. If you reckon there should be more, please edit that file directly on the master branch.

**Comment by tleyden** [comment]
- [ ] Remove spaces after colon: `2018-01-25T10:42:57.753-08:00 SyncMsg: [58d32e29249b0a73] #002: "subChanges" Since: 0  user:user1
`

**Comment by tleyden** [comment]
- [ ] Remove ellipses: `2018-01-25T10:42:57.753-08:00 Sync: [58d32e29249b0a73] Sending changes since 0 ... user1` replace with user:

**Comment by tleyden** [comment]
- [x] subChanges needs special handling for exit logs

**Comment by tleyden** [comment]
> subChanges needs special handling for exit logs

subChanges with artificial delay:

https://gist.github.com/tleyden/ee095e17a3228e8a22562427dd89eed9#file-gistfile1-txt-L3267

The last line shows the total time for the changes to be streamed:

```
2018-01-25T12:45:19.304-08:00 SyncMsg+: [742b6d61] #1500: Type:subChanges   --> Time:17.683262292s User:GUEST 
```

**Comment by tleyden** [comment]
Example logs with `WS/WS+/WS++` logs enabled:

https://gist.github.com/tleyden/2e82c6a15aa9e19ec491bcecf4af3dfa
