### ISSUE TITLE
RunTime error , nil pointer deference error in DI mode

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3249]
### Sync Gateway version
2.0.0-759

### Operating system
Centos
###  SG Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://192.168.33.10:8091",
        "data_dir":".",
        "bucket":"data-bucket",
        "username":"data-bucket",
        "password": "password"
    },
    "databases":{
        "db":{
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "allow_conflicts": false,
            "revs_limit": 5,
            "channel_index":{
                "num_shards":16,
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket",
                "username":"index-bucket",
                "password": "password",
                "writer":false
            }
        }
    }
}

```
###  SG Accel Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://192.168.33.10:8091",
        "data_dir":".",
        "bucket":"data-bucket",
        "username":"data-bucket",
        "password": "password"
    },
    "databases":{
        "db":{
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "allow_conflicts": false,
            "revs_limit": 5,
            "channel_index":{
                "num_shards":16,
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket",
                "username":"index-bucket",
                "password": "password",
                "writer":true
            }
        }
    }
}


```
### Log output
https://gist.github.com/sridevi-15/a8dd8d50d121368da96ac683380e8e3b

### Steps to reproduce
1.  Set up SG with sg accel
2.  Create docs in CBL,
3.  Start replication with continous true and push_pull
4. update docs in SG and CBL concurrently by running `pytest -rsx -s -k test_get_set_pinnnedServerCertificates --server-version=5.0.0 --sync-gateway-version=2.0.0-759 --mode=cc --liteserv-host=192.168.0.104 --liteserv-port=8080 --xattrs  --create-db-per-test=pull-test  --skip-provisioning --liteserv-platform=ios testsuites/CBLTester/CBL_Functional_tests/`
5. Wait for replicator to be idle

### Expected behavior
Replication should complete and all docs should replicated in SG and CBL

### Actual behavior
CBL got an error 'Connection reset by Peer'
It throw an error on sg logs

### Link to the test code : 
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py#L953

### Additional information : 
CBL logs . : https://gist.github.com/sridevi-15/a3402ff18c4837ff5e365471d5bdf463
Note : This error happening with ios build 565 : http://latestbuilds.service.couchbase.com/builds/latestbuilds/couchbase-lite-ios/2.0.0/565/

but I did not see this issue with 560

**Comment by adamcfraser** [comment]
This feels like a case where the since value isn't being properly initialized as a clock-based sequence, but that should be covered by the standard sequence unmarshaller.

**Comment by adamcfraser** [comment]
@sridevi-15 It would be useful to run these tests with log:["*"] - the verbose output would make it quicker to repro/diagnose these issues.

**Comment by adamcfraser** [comment]
May be related to the error handling here:

```
	// Depeding on the db sequence type, use correct zero sequence for since value
	since := bh.db.CreateZeroSinceValue()

	if sinceStr, found := rq.Properties["since"]; found {
		var err error
		if since, err = db.ParseSequenceIDFromJSON([]byte(sinceStr)); err != nil {
			bh.blipSyncContext.LogTo("Sync", "%s: Invalid sequence ID in 'since': %s ... %s", rq, sinceStr, bh.effectiveUsername)
			since = db.SequenceID{}
		}
	}
```

**Comment by tleyden** [comment]
Related issue: https://github.com/couchbase/sync_gateway/issues/3165#issuecomment-356453025

**Comment by tleyden** [comment]
Adding step to repro:

```
pytest -rsx -s -k test_sg_cbl_updates_concurrently_with_push_pull --server-version=5.0.0 --sync-gateway-version=2.0.0-759 --mode=di --liteserv-host=10.17.1.93 --liteserv-port=8080 --xattrs  --create-db-per-test=pull-test  --no-conflicts testsuites/CBLTester/CBL_Functional_tests/
```

**Comment by tleyden** [comment]
@sridevi-15 should that be `--mode=di`?

**Comment by tleyden** [comment]
Logs w/ additional debug logs: 

https://gist.github.com/sridevi-15/8d7906d0001e04b1abec34edb93288f2
