### ISSUE TITLE
Customizable HTTP response to "/"

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#3257]
As a developer, i should be able to customize the Sync Gateway response to the root path. 

This would typically be done to not reveal the version of the Sync Gateway to HTTP requests to the root path.

**Comment by adamcfraser** [comment]
@ssmotra What level of customization is being proposed here?

In addition, Sync Gateway version information is also included in the `Server` header on all Sync Gateway responses (including responses to the root path).  Would this also need to be 'customized'?  If so - for all endpoints, or just `/`?

**Comment by JFlath** [comment]
I think this probably forms part of a broader issue - users wanting to adjust this response are probably looking to remove identifying info. In that case, we probably need to worry about headers too.

For example, even if I tweak the code to return nothing (I even added a config setting!), I can get this:

```
$ curl :4984/ -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to  (::1) port 4984 (#0)
> GET / HTTP/1.1
> Host: :4984
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Couchbase Sync Gateway/2.0 branch/feature/issue_3276 commit/23e772a+CHANGES
< Date: Tue, 06 Feb 2018 16:26:29 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Curl_http_done: called premature == 0
* Connection #0 to host  left intact
```
So, as @adamcfraser pointed out, the info is basically still available.

Even if we have an option to nuke that endpoint, this is still an issue:

```
$ curl :4984/db/ -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to  (::1) port 4984 (#0)
> GET /db/ HTTP/1.1
> Host: :4984
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json
< Server: Couchbase Sync Gateway/2.0 branch/feature/issue_3276 commit/23e772a+CHANGES
< Www-Authenticate: Basic realm="Couchbase Sync Gateway"
< Date: Tue, 06 Feb 2018 16:28:27 GMT
< Content-Length: 50
<
* Curl_http_done: called premature == 0
* Connection #0 to host  left intact
{"error":"Unauthorized","reason":"Login required"}
```

@ssmotra we probably need some real world requirements on this - what are people looking for and why?

**Comment by bbrks** [comment]
Agreed. It's less about response customisation and more about an option to protect against fingerprinting.

https://www.owasp.org/index.php/Fingerprint_Web_Server_(OTG-INFO-002)
https://www.owasp.org/index.php/Fingerprint_Web_Application_(OTG-INFO-009)

I think we can probably mask the Sync Gateway version to some extent, as long as clients don't rely on it for negotiation? The second link has a useful list of remediations.

It would be impossible to mask the fact that Sync Gateway is the application that is running.

**Comment by djpongh** [comment]
Moved to: https://issues.couchbase.com/browse/CBG-759
