### ISSUE TITLE
BLIP replicator doesn’t support docIDs filter

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#3275]
The BLIP replicator in SG doesn't recognize filtering a pull replication to specific document IDs. This breaks the corresponding feature in CBL 2.

The docIDs filter is specified in the body of a `subChanges` request:
>If a request body is present, it MUST be a JSON dictionary/object. In this dictionary the key docIDs MAY appear; its value MUST be an array of strings. If present, the recipient MUST only send changes to documents with IDs appearing in that array. Other unrecognized keys in the dictionary MUST be ignored. [\*](https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Protocol#subchanges)

(This is basically my fault; I added this functionality last July, or at least documented it in the wiki then, but didn't implement it on the SG side.)

**Comment by adamcfraser** [comment]
Sync Gateway doesn't support the doc_ids filter for anything but one-shot replications (over REST).  I'm assuming the same limitation (valid for non-continuous only) will apply for blip_sync until we add that support.  Does that pose any problems for CBL 2?

**Comment by snej** [comment]
Should be fine.

**Comment by adamcfraser** [comment]
@snej @hideki Is there a sample subChanges payload for the doc_ids filter that we can use to validate/unit test the SG implementation?

**Comment by snej** [comment]
Do you just want an example of what a subChanges message with docIDs looks like? Or are you asking for a LiteCore or CBL test that filters by docID?

**Comment by adamcfraser** [comment]
Just the sample subChanges message with docIDs should be sufficient.

**Comment by adamcfraser** [comment]
@snej Also - I'm assuming that doc_ids and filter will need to be mutually exclusive (at least for SG in 2.0), even though that's not required based on the spec.  It would be a larger enhancement for SG to  support both channel filtering and doc id filtering on a single request.
