### ISSUE TITLE
BLIP: Accept ‘proposeChanges’ request when not in conflict-free mode

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#3279]
LiteCore [should always use the conflict-free push mode](https://github.com/couchbase/couchbase-lite-core/issues/181), even when SG doesn't require it; this will prevent it from inadvertently creating conflicts on the server.

At a protocol level this means LiteCore always sending "proposeChanges" requests, not "changes". SG will need to allow this, even when conflict-free mode isn't enabled. This should just require taking out a test in the handler.

**Comment by snej** [comment]
I just added a note to [the LiteCore issue](https://github.com/couchbase/couchbase-lite-core/issues/181) identifying a race condition that could still allow a conflict, and suggesting a property be added to the `rev` message to fix that.

**Comment by adamcfraser** [comment]
For the latter change (supporting `noconflicts: true` on the `rev` message), we should just need to do the following on the SG side:
- grab the noconflicts property in blipHandler.handleRev, and pass as a new parameter to db.PutExistingRev
- in PutExistingRev, pass the noconflicts value as a new parameter to db.IsIllegalConflict
- in IsIllegalConflict, modify handling to immediately return false only if both db.AllowConflicts()=true and rev.noconflicts=false

**Comment by bbrks** [comment]
As discussed yesterday, I'll take over this in exchange for #3275 @adamcfraser
