### ISSUE TITLE
Modify sample configs to use allow_conflicts=false, low revs_limit

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3284]
The recommended configuration for 2.0 and later will be allow_conflicts=false and a low revs_limit.  We aren't making these the default values in 2.0, primarily due to upgrade considerations.  However, we should update the sample configs to use these settings.

**Comment by djpongh** [comment]
Just as an FYI - the default values will be:
Default value for allow_conflicts: true
Value used for revs_limit when allow_conflicts == false: if specified in SG config use configured value, otherwise use the standard revs_limit default (1000)
