### ISSUE TITLE
Run litecore replication tests against sync gateway

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3286]
## Setup Steps (via Cmake):

1. Clone couchbase-lite-ios
1. cd into the `vendor/couchbase-lite-core` subdirectory
1. Build litecore via running `./build_cmake/scripts/build_macos.sh`
1. Open a shell at at couchbase-lite-core/Replicator/tests/data/
1. In that shell, start SG with config file config.json.
1. Repeat previous 2 steps except use ssl_config.json
1. Cd back to `couchbase-lite-core`
1. `./build_cmake/macos/C/tests/C4Tests -r list '[.SyncServer]'`
1. Repeat with SG + SG Accel

If you want to run SG on a different host, you can do that, but in the invocation of C4Tests set environment variables REMOTE_HOST and REMOTE_PORT appropriately.

## Acceptance criteria

- [x] Run against Sync Gateway w/ walrus bucket
- [x] Run against Sync Gateway w/ Couchbase Bucket + XATTR
- [x] Run against Sync Gateway w/ Couchbase Bucket + DocMeta: [Result logs](https://gist.github.com/tleyden/142b163d50f1dd0a80fc27935117406e)
- [x] Fix underlying issue that caused https://github.com/couchbase/sync_gateway/issues/3307 to fail.

## Steps (via Xcode):

TODO

**Comment by tleyden** [comment]
Would be interesting to see if this catches https://github.com/couchbase/sync_gateway/issues/3283

**Comment by adamcfraser** [comment]
Manual test only - automation covered by #3224.

**Comment by tleyden** [comment]
On `feature/enable_gocb_flush` branch, I'm currently stuck on this error when trying to flush the bucket:

```
2018-02-12T16:26:12.853-08:00 WARNING: Error flushing bucket: No available management nodes."
```

**Comment by tleyden** [comment]
I got test failures when using LiteCore against SG + Couchbase Server + XATTRS (where as when using docmeta, it passed)  https://gist.github.com/tleyden/354ee8d892dd5352b17c0381648e0d5f#file-gistfile1-txt-L1379

This log in particular looks worth digging into further:

```
16:41:06.158786| [Sync] ERROR: {Push#45} Got error response to rev doc #2-c001d00d (seq 2): HTTP 404 'missing'
```

**Comment by tleyden** [comment]
With the changes from https://github.com/couchbase/sync_gateway/pull/3316 + https://github.com/couchbase/sync_gateway/pull/3306, the full LiteCore replicator suite is now passing.

Logs: 

https://gist.github.com/tleyden/ad810e4eb6fc4a32380154fa01935985

Caveat: currently only the *scratch* database is being backed Couchbase Server

**Comment by tleyden** [comment]
> Caveat: currently only the scratch database is being backed Couchbase Server

When I set all the db's to use Couchbase Server buckets, I'm seeing this error:

```

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C4Tests is a Catch v1.5.6 host application.
Run with -? for options

-----------------------------------------------------------------------------------------------------------------------
API Pull Big Attachments
-----------------------------------------------------------------------------------------------------------------------
/Users/tleyden/Development/couchbase-lite-ios/vendor/couchbase-lite-core/Replicator/tests/ReplicatorAPITest.cc:314
.......................................................................................................................

/Users/tleyden/Development/couchbase-lite-ios/vendor/couchbase-lite-core/Replicator/tests/ReplicatorAPITest.cc:320: FAILED:
  REQUIRE( doc )
with expansion:
  false

16:29:57.706766| [DB]: Closing DataFile
=======================================================================================================================
test cases:    13 |    12 passed | 1 failed
assertions: 37480 | 37479 passed | 1 failed

ENDED TESTS AT Thu Feb 15 16:29:57 2018

```

**Comment by tleyden** [comment]
LiteCore test failure logs for that test:

https://gist.github.com/tleyden/ca7d0800e65f100eb58ec31f85206a37

**Comment by tleyden** [comment]
@snej @borrrden @pasin I'm getting a LiteCore test failure on this test:

```
TEST_CASE_METHOD(ReplicatorAPITest, "API Pull Big Attachments", "[.SyncServer]") {
    _remoteDBName = kImagesDBName;
    replicate(kC4Disabled, kC4OneShot);

    C4Error error;
    c4::ref<C4Document> doc = c4doc_get(db, "Abstract"_sl, true, &error);
    REQUIRE(doc);
    auto root = Value::fromData(doc->selectedRev.body).asDict();
    auto sk = c4db_getFLSharedKeys(db);
    auto attach = root.get("_attachments"_sl, sk).asDict().get("Abstract.jpg"_sl, sk).asDict();
    REQUIRE(attach);
    CHECK(attach.get("content_type",sk).asString() == "image/jpeg"_sl);
    slice digest = attach.get("digest",sk).asString();
    CHECK(digest == "sha1-9g3HeOewh8//ctPcZkh03o+A+PQ="_sl);
    C4BlobKey blobKey;
    c4blob_keyFromString(digest, &blobKey);
    auto size = c4blob_getSize(c4db_getBlobStore(db, nullptr), blobKey);
    CHECK(size == 15198281);
}
```

when running against Sync Gateway w/ a Couchbase Server bucket, whereas it works against a Walrus bucket.

Here are the failure logs on the litecore side: https://gist.github.com/tleyden/ca7d0800e65f100eb58ec31f85206a37

Any idea why this is failing?  I was going to try to reduce the size a little bit to see if that made a difference, but couldn't see how to do that .. 

Also I did verify that the max couchbase document size is 20MB, so the 15MB attachment should work

Another data point: it fails if I use `walrus:` rather than `walrus:walrus_data`, so does that mean there is a large attachment pre-baked into a db and this test won't work unless that pre-baked db is used?

**Comment by tleyden** [comment]
Aside from that one failing test, which I think is due to a dependency on a pre-baked db, all tests are passing against SG + Couchbase Server in XATTR + non-XATTR mode w/ these configs: https://gist.github.com/tleyden/51f475f9872faa135985726fbbe5d54f

**Comment by snej** [comment]
I don't see any errors in the gist above. But I don't understand the XML that's being mixed in with the LiteCore logs ... what is that from?

**Comment by snej** [comment]
Oh, and yes, that test requires the "images" database, which has some attacchments in it. You can find it in the `Replicator/test/data/walrus` directory.

**Comment by tleyden** [comment]
Sorry, that was from CLion, I was running an individual test since it was faster.

I think your last comment answers my question though.  Thanks!
