### ISSUE TITLE
Log redaction: 'auth' package

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3297]
## 'auth' package log redaction

- Find all logging calls - use regex: `base\.(Log(f|To|Error|Panic|Fatal)?|Warn|TEMP|Error)\(`
- Identify ones that have redactable data and wrap with `base.UD()`, `base.MD()` or `base.SD`
- Change the logging calls to use the redacted variants (`base.WarnR()`, etc.) introduced in #3295 

Could also change `%v` formatting directives to the correct types (i.e. `%s`, `%b`, `%d`)

**Comment by adamcfraser** [comment]
@bbrks to complete auth, then split out tickets for the remainder

**Comment by bbrks** [comment]
Split other packages out into:

#3310 #3311 #3312 #3313
