### ISSUE TITLE
Upstart script broken on 2.0 beta 1

### ISSUE THREAD

**Issue by gajohnson** [couchbase/sync_gateway#3300]
### Sync Gateway version

Couchbase Sync Gateway/2.0.0(773;5a497fd)

http://packages.couchbase.com/releases/couchbase-sync-gateway/2.0.0-beta1/couchbase-sync-gateway-enterprise_2.0.0-beta1_x86_64.rpm

### Operating system
CentOS release 6.9 (Final)

### Expected behavior
`sudo start sync_gateway` succeeds.

### Actual behavior
/etc/init/sync_gateway.conf sets the env var PIDFILE to empty string and then tries to echo the pid into it.

```
env PIDFILE=
...
 # Keep a pid around
  echo $$ > $PIDFILE
  cd $RUNBASE
...
```
This prevents the sync gateway from starting.

### Steps to reproduce
1.  Install gateway from http://packages.couchbase.com/releases/couchbase-sync-gateway/2.0.0-beta1/couchbase-sync-gateway-enterprise_2.0.0-beta1_x86_64.rpm
2.  `sudo start sync_gateway`
3.  `sudo status sync_gateway`

**Comment by bbrks** [comment]
Hi @gajohnson,

Thanks for raising this issue. I've managed to reproduce it in CentOS 6.9 and seems to be a regression in our build scripts.

We'll be looking to address this ASAP. For now, you can set the `PIDFILE` location manually in `/etc/init/sync_gateway.conf`, if you haven't done so already, to get Sync Gateway started.
