### ISSUE TITLE
Bucket flush endpoint doesn't work against Couchbase server buckets

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3305]
When trying to run https://github.com/couchbase/sync_gateway/issues/3286 against Sync Gateway backed by Couchbase server, I noticed that the bucket flush endpoint was not working.

**Comment by adamcfraser** [comment]
Want to add an unsupported config flag to enable flush support for non-Walrus buckets (to ensure users don't start accidentally flushing their production buckets via SG).
