### ISSUE TITLE
Log redaction: 'rest' package

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3313]
## 'rest' package log redaction

- Find all logging calls - use regex: `base\.(Log(f|To|Error|Panic|Fatal)?|Warn|TEMP|Error)\(`
- Identify ones that have redactable data and wrap with `base.UD()`, `base.MD()` or `base.SD`
- Change the logging calls to use the redacted variants (`base.WarnR()`, etc.) introduced in #3295 

Could also change `%v` formatting directives to the correct types (i.e. `%s`, `%b`, `%d`)

**Comment by tleyden** [comment]
@bbrks I noticed that when switching from:

```
base.LogTo("Changes+", "Changes POST request.  URL: %v, feed: %v, options: %+v, filter: %v, 
bychannel: %v, docIds: %v %s", h.rq.URL, feed, options, filter, channelsArray, docIdsArray, to)
```

to:

```
base.LogToR("Changes+", "Changes POST request.  URL: %v, feed: %v, options: %+v, filter: %v,
 bychannel: %v, docIds: %v %s", base.MD(h.rq.URL), base.MD(feed), base.MD(options), base.MD(filter), base.UD(channelsArray), base.UD(docIdsArray), base.UD(to))
```

the log output changed slightly, from:

```
2018-03-21T15:30:14.439-07:00 Changes+: Changes POST request.  URL: /db/_changes, feed: normal,
 options: {Since:0 Limit:0 Conflicts:false IncludeDocs:false Wait:false Continuous:false Terminator:<nil> HeartbeatMs:0 TimeoutMs:300000 ActiveOnly:false}, filter: , bychannel: [[_admin]], docIds: [-MCw8q3tzq5EYSdrivfWjy1]

```

to: 

```
2018-03-21T15:29:00.218-07:00 Changes+: Changes POST request.  URL: /db/_changes, feed: normal,
 options: {0 0 false false false false <nil> 0 300000 false}, filter: , bychannel: [[_admin]], docIds: [-MCw8q3tzq5EYSdrivfWjy1]

```

(note that the field names have been lost)

Is that expected?

**Comment by tleyden** [comment]
@bbrks 

If I accidentally wrap with `base.MD()` but forget to call `base.WarnR()`, will the `base.MD()` effectively be a no-op?

For example:

```
base.Warn("Error compiling regex: %v.  Err: %v", base.MD(regex), err)
```

**Comment by tleyden** [comment]
For this particular log statement:

```
base.Logf("Wrote %s profile to %s", profileName, params.File)

```

it's logging that it wrote a CPU profile to a particular file (from the profiling admin API) -- does this need to be wrapped in `base.MD()`?  Or restated, does every logged item aside from errors need to be wrapped in either UD/MD/SD?

**Comment by tleyden** [comment]
This seems slightly problematic:

```
func (ctx *blipSyncContext) LogTo(key string, format string, args ...interface{}) {
	formatWithContextID, paramsWithContextID := base.PrependContextID(ctx.blipContext.ID, format, args...)
	base.LogTo(key, formatWithContextID, paramsWithContextID...)
}

```

the blip context wraps the `base.LogTo()` method.

A few ways to deal with it:

1. In `blipSyncContext.LogTo()`, call `base.LogToR()` and wrap everything in `paramsWithContextID` with `base.UD()`, even though some items shouldn't be `base.UD()`
1. Create `blipSyncContext.LogToR()`, and callers could optionally wrap args in `base.UD()`.  
1. Leave it named as  `blipSyncContext.LogTo()`, but wrap `base.LogToR()` and callers of `blipSyncContext.LogTo()` can optionally wrap args in  `base.UD()/MD()/etc`

**Comment by bbrks** [comment]
@tleyden 

1. Interesting, something I'd overlooked... `base.UD` is falling back to `%v` as a way of getting a string from an `interface{}`.
https://github.com/couchbase/sync_gateway/blob/870efec37867b4bf5949e8d4e53922bc6c171c83/base/redactor_userdata.go#L43-L44
By the time it's logged it's been converted to a string and run through `Redact()`, and so has no struct fields anymore. Unfortunately the `%+v` or `%#v` directives in the original log call won't have any effect on the resulting string.
I could change the default fallback to `%+v` instead, if we always wanted to log the struct field names?

2. Kind of. There's no call out to `Redact()`, so avoids that processing overhead, but it will still be converted to a string before being logged, as described in `1.`

3. I think a lot of what gets tagged is subjective, and not everything we log fits into those three categories. For the profile/file question, I'd err on the side of caution and tag it with `UD` (it's a user supplying the profile name and file in the request - I.e. they could call the profile `CompanyNameSGCPUProfile` and store it in `/home/company_name/sg_cpu_profile`).

4. I'd keep it consistent and create a `blipSyncContext.LogToR()`, these special redacted variants will eventually become the normal log functions, once we're sure we've covered everything. Unfortunately the redact wrapper I call in base is private. So you could either make it public, and call from `blipSyncContext.LogToR()`, or copy the logic into your own redacted variant.
https://github.com/couchbase/sync_gateway/blob/870efec37867b4bf5949e8d4e53922bc6c171c83/base/logging.go#L441-L444
https://github.com/couchbase/sync_gateway/blob/870efec37867b4bf5949e8d4e53922bc6c171c83/base/redactor.go#L16-L25

**Comment by tleyden** [comment]
> I'd keep it consistent and create a blipSyncContext.LogToR()

Would there be any harm in *just* having a `blipSyncContext.LogToR()` and remove `blipSyncContext.LogTo()` completely?  Or are we following a rule that if a logging call doesn't have any redacted fields, we don't want to pay the cost and `LogTo()` should be called rather than `LogToR()`?

**Comment by tleyden** [comment]
> Unfortunately the redact wrapper I call in base is private

For this case it's not an issue, since `blipSyncContext.LogToR()` can just wrap `base.LogToR()`:

```
func (ctx *blipSyncContext) LogToR(key string, format string, args ...interface{}) {
	formatWithContextID, paramsWithContextID := base.PrependContextID(ctx.blipContext.ID, format, args...)
	base.LogToR(key, formatWithContextID, paramsWithContextID...)
}
```

**Comment by bbrks** [comment]
@tleyden I think it's fine to remove the non-redacted variant. If it's so costly to call it, or it causes problems, perhaps we should revisit the approach :)

**Comment by tleyden** [comment]
I'm wondering the best way to identify all calls that might need to be redacted.  Currently I'm doing a string search for `base.Log*` and `base.Warn*`

Any others I need to look for?

**Comment by bbrks** [comment]
@tleyden I ended up writing a regex today to find all the logging calls, I added it to the top of this issue

**Comment by adamcfraser** [comment]
Fixed by https://github.com/couchbase/sync_gateway/pull/3379
