### ISSUE TITLE
add log message when bucket level ttl enabled

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#3314]

**Comment by djpongh** [comment]
and fail to start?

**Comment by djpongh** [comment]
and how to tell if feature is enabled.

**Comment by adamcfraser** [comment]
Need to investigate whether this information is included in the cluster definition (i.e. retrievable via SDK/HTTP).

**Comment by tleyden** [comment]
SG cannot deal with a non-zero maxTTL, and so it shouldn't bring the DB online if the bucket has a non-zero maxTTL setting.
