### ISSUE TITLE
TestUserAPI data race in integration tests 

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3323]
Discovered at the same time as https://github.com/couchbase/sync_gateway/issues/3322

Steps to repro:

- Run [integration tests](http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/414/consoleFull) with
    - SG_COMMIT: feature/issue_3281_blip_handler_cant_get_doc
    - TARGET_TEST: ALL
    - SG_TEST_BACKING_STORE: Couchbase
    - SG_TEST_COUCHBASE_SERVER_URL: http://integration-cbs.sc.couchbase.com:8091
    - SG_TEST_USE_XATTRS: true
    - GO: 1.8.5
    - DATA_RACE: true

Logs: https://gist.github.com/tleyden/adbd4496d47cd3cca6f1afcfa9f90c9f

**Comment by adamcfraser** [comment]
Closing - not currently triggering data race.
