### ISSUE TITLE
Add Unit test for DocID filter and resurrected docs

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3327]
Need test to validate the following scenario:
1. Create a user w/ access to channels A and B
2. Create a doc w/ rev-1 in channel A
3. Tombstone doc (rev-2)
4. Resurrect doc w/ rev-3 in channel B
5. Issue a changes request as the user w/ doc ID filter - ensure that the document is returned w/ deleted:false.

**Comment by adamcfraser** [comment]
Consider refactoring the logic that does this computation in DocIDChangesFeed once the test is written.

**Comment by bbrks** [comment]
Issue being tracked at [CBG-228](https://issues.couchbase.com/browse/CBG-228)
