### ISSUE TITLE
BlipTester concurrency safety issues 

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3335]
* BlipTester's are not safe to use by multiple goroutines
* Even in a single goroutine, using a single BlipTester/BlipContext can run into data race issues since the `blipContext.HandlerForProfile` map is not protected by any locks, and there are goroutines within the blipContext that access it.

This was noticed in the build failures and PR review for https://github.com/couchbase/sync_gateway/pull/3304#issuecomment-367814325,

**Comment by adamcfraser** [comment]
Closing - blip testers undergoing rewrite for Hydrogen.
