### ISSUE TITLE
Change feed is empty when pulling data on a new device

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#334]
Moved from https://github.com/couchbase/couchbase-lite-android/issues/326

This sounds like a possible issue of sync gateway rather than couchbase lite, so I'm moving the issue here.

**Comment by milky-la** [comment]
I'm getting the same issue: couchbase.lite client doesn't pull any documents on port 1984 (pushing changes is ok). It's 100% repro: just trying to set up and validate some new project with couchbase

Versions:
gateway 1.0.3
Replication: Server Version: Couchbase Sync Gateway/1.00

Repro:
1. create two nothing-special buckets from couchbase server web console: mybucket, sync-mybucket (or use sample)
2. nothing-special config (allow GUEST, shadow)

``` json
{
   "interface":":4984",
   "adminInterface":":4985",
   "log":["CRUD", "REST+", "HTTP+"],
   "pretty": true,
   "verbose": true, 
   "databases":{
      "sync-mybucket":{
         "server":"http://localhost:8091",
         "bucket":"sync-mybucket",
         "importDocs": true,
          "shadow": {
            "server": "http://localhost:8091",
            "bucket": "mybucket"
         },
         "users": {
              "GUEST": {"disabled": false}
          },

      }
   }
}
```
1. Start sync gateway:

```
09:50:17.242285 ==== Couchbase Sync Gateway/1.0.3(81;fa9a6e7) ====
09:50:17.242285 Configured Go to use all 8 CPUs; setenv GOMAXPROCS to override this
09:50:17.242285 WARNING: Error setting MaxFileDescriptors to 5000: Unsupported on Windows -- 
rest.setMaxFileDescriptors() at config.go:378
09:50:17.242285 Opening db /sync-mybucket as bucket "sync-mybucket", pool 
"default", server <http://localhost:8091>
09:50:17.242285 Opening Couchbase database sync-mybucket on <http://localhost:8091>
09:50:17.369330     Reset guest user to config
09:50:17.369330 Opening Couchbase database mybucket on <http://localhost:8091>
09:50:17.489336 Database "sync-mybucket" shadowing remote bucket "mybucket", 
pool "default", server <http:localhost:8091/>
09:50:17.489336 Starting admin server on :4985
09:50:17.491340 Starting server on :4984 ...
```
1. Add some test docs to mybucket
   via client push replication (which is working)
   or via server web console in mybucket, create document 
   (Ok: sync-mybucket picks it) 
2. lite client with url=http://<myhost>:4984/sync-mybucket, continuous Replication.. 
   Result: pull doesn't see any changes (Idle, change count 0)

5 In general changes are not seen on :4984 but are returned ok on admin interface :4985

*\* 4984 **

```
curl http://<myhost>:4984/sync-mybucket/_all_docs
{"rows":[
],
"total_rows":0,"update_seq":16}

curl http://<myhost>:4984/sync-mybeacon/_changes
{"results":[
{"seq":1,"id":"_user/GUEST","changes":[]}
],
"last_seq":"1"}
```

*\* 4985 is ok **

```
curl http://<..>:4985/sync-***/_changes
{"results":[
 ... ## <erased> ##
,{"seq":5,"id":"1","changes":[{"rev":"1-1d7a1a352c0abb293fdd16883ef6985b"}]}
,{"seq":10,"id":"test_channel","changes":[{"rev":"2-94a1ec92d7c464c3272742b1594edcb4"}]}
 ...
],
"last_seq":"16"}

_all_docs are ok too
```

**Comment by ajres** [comment]
@milky-la Can you enter your post in a new ticket, this may not be related to the previous issue.

**Comment by milky-la** [comment]
@ajres  created #687
