### ISSUE TITLE
Sync Gateway 1.5.1 panics when querying a view

### ISSUE THREAD

**Issue by timritzer** [couchbase/sync_gateway#3344]
This occurs on Sync Gateway 1.5.1. We are currently on 1.4.1, and this functionality works fine. This was found while testing for upgrade path due to other bugs fixed in the 1.5 timeframe.

Occurs on Windows environments. Have tested on Windows 10 as well as Server 2008 R2

Configuration:
Nothing special on the config, using the provided example for pointing at a real bucket, only changing the URL to our server, and the bucket to our bucket. (Also occurs on other environment with multiple buckets currently running 1.4.1 successfully)

Relavent Logs
https://gist.github.com/timritzer/63899082e218029f7d17bc5fe93c5e9b

Expected:
Expected the sync to return filtered view results based on the passed in keys.

What Happens:
Sync Gateway panics logs errors, and fails to respond to request.

Steps to reproduce:

1. Create view through Sync Gateway. We usually do this in the back end application, but for reference created using CURL in windows:
`curl -v -X PUT http://localhost:4985/db/_design/keylookup_withreduce -H "Content-Type: application/json" -d "{ \"views\": {\"keylookup_withreduce\": { \"map\": \"function (doc, meta) { if(doc._deleted) { return; } for(var i in doc.channels) { emit(doc.channels[i], doc.keyid);}}\" , \"reduce\": \"function (keys, values, rereduce) { if (rereduce) { var result = []; for (var i = 0; i ^< values.length; i++) { var distinct = values[i]; for (var j = 0; j ^< distinct.length; j++){result.push(distinct[j]);}} return result.filter(function (e, i, arr) { return arr.lastIndexOf(e) === i;}); } return values.filter(function (e, i, arr) { return arr.lastIndexOf(e) === i; } );} \" }}}"`

2. Query view through Sync Gateway. Again, usually done in code, but for purposes of recreation here is a CURL request:
`curl -v http://localhost:4985/db/_design/keylookup_withreduce/_view/keylookup_withreduce?keys=%5B%22env_1%22%5D`

3. Note that no response is returned, and the error logs show the panic posted in the logs above.

Note that querying for only one key works as expected, and returns results.
`curl -v http://localhost:4985/db/_design/keylookup_withreduce/_view/keylookup_withreduce?key=%22env_1%22`
Also querying through Couchbase itself works as well.

**Comment by tleyden** [comment]
@timritzer thanks for the clear issue report!

Which version of Couchbase Server are you on?

**Comment by timritzer** [comment]
At the moment 4.6.2

Specifically 4.6.2-3905 Enterprise Edition (build-3905)

**Comment by tleyden** [comment]
Ok thanks.  I will try to reproduce the issue.

(note to self: possibly related to https://github.com/couchbase/sync_gateway/issues/1580#issuecomment-182729570, same error message as https://github.com/couchbase/sync_gateway/issues/1572#issuecomment-182153496)

**Comment by tleyden** [comment]
## Steps to repro

- SG commit 2b99523e75f291294d85a287b2bb9c1a795ad968
- Run SG with the config below
- `curl "http://localhost:4985/db/_design/foo/_view/foo?keys=%5B%22env_1%22%5D"`

## Config

```
{
  "interface":":4984",
  "log": ["*", "Sync", "Sync+", "Sync++", "HTTP+"],
  "databases": {
    "db": {
      "server": "http://couchbase-server:8091",
      "bucket": "db",
      "password": "password"
    }
}
```

## Error log

```
2018-02-28 13:51:29.139154 I | http: panic serving 127.0.0.1:54216: interface conversion: interface {} is []interface {}, not []string
goroutine 192 [running]:
net/http.(*conn).serve.func1(0xc420bcf4a0)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x176db00, 0xc420598e00)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/couchbase/sync_gateway/base.applyViewQueryOptions(0xc420598dc0, 0xc420978570, 0xc420978630, 0x0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/bucket_gocb.go:2223 +0x1672
github.com/couchbase/sync_gateway/base.CouchbaseBucketGoCB.View(0xc4202c2120, 0xc420015880, 0x1c, 0x184556e, 0x7, 0xc42001fe2c, 0x2, 0x0, 0x0, 0x1ca2b40, ...)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/bucket_gocb.go:1845 +0x209
github.com/couchbase/sync_gateway/base.(*CouchbaseBucketGoCB).View(0xc4202886e0, 0xc420372090, 0x3, 0xc42037209a, 0x3, 0xc420978570, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:1 +0x109
github.com/couchbase/sync_gateway/db.(*Database).QueryDesignDoc(0xc420db1220, 0xc420372090, 0x3, 0xc42037209a, 0x3, 0xc420978570, 0x3, 0xc4204b37c0, 0x11687de)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/design_doc.go:213 +0x119
github.com/couchbase/sync_gateway/rest.(*handler).handleView(0xc420bcf860, 0xc420db1220, 0xc420474250)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/view_api.go:105 +0x890
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc420bcf860, 0x187c798, 0x0, 0x0)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:222 +0x2c4
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x1ca9f40, 0xc42046a8c0, 0xc420382300)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/handler.go:97 +0x80
net/http.HandlerFunc.ServeHTTP(0xc420c38140, 0x1ca9f40, 0xc42046a8c0, 0xc420382300)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202180f0, 0x1ca9f40, 0xc42046a8c0, 0xc420382300)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/gorilla/mux/mux.go:114 +0xdc
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x1ca9f40, 0xc42046a8c0, 0xc420382100)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/routing.go:304 +0x64a
net/http.HandlerFunc.ServeHTTP(0xc42040e400, 0x1ca9f40, 0xc42046a8c0, 0xc420382100)
	/usr/local/go/src/net/http/server.go:1918 +0x44
net/http.serverHandler.ServeHTTP(0xc42028a000, 0x1ca9f40, 0xc42046a8c0, 0xc420382100)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420bcf4a0, 0x1caa9c0, 0xc420598b00)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288

```

**Comment by tleyden** [comment]
Pull request up at https://github.com/couchbase/sync_gateway/pull/3347
