### ISSUE TITLE
Wireshark dissector for blip traffic

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3356]
Create a Wireshark dissector for blip traffic

**Comment by tleyden** [comment]
@avsej after reading through `packet-websocket.c` more thoroughly, I noticed this code:

```
if (websocket_conv->subprotocol) {
    handle = dissector_get_string_handle(protocol_subdissector_table, websocket_conv->subprotocol);
  }
```

in:

```
static void
dissect_websocket_data_frame(tvbuff_t *tvb, packet_info *pinfo, proto_tree *tree, proto_tree *pl_tree, guint8 opcode, websocket_conv_t *websocket_conv, gboolean pmc _U_, gint raw_offset _U_)
{
  proto_item         *ti;
  dissector_handle_t  handle = NULL;
  heur_dtbl_entry_t  *hdtbl_entry;

  /* try to find a dissector which accepts the data. */
  if (websocket_conv->subprotocol) {
    handle = dissector_get_string_handle(protocol_subdissector_table, websocket_conv->subprotocol);
  } else if (websocket_conv->server_port) {
    handle = dissector_get_uint_handle(port_subdissector_table, websocket_conv->server_port);
  }

  if (handle) {
    call_dissector_only(handle, tvb, pinfo, tree, NULL);
    return; /* handle found, assume dissector took care of it. */
  } else if (dissector_try_heuristic(heur_subdissector_list, tvb, pinfo, tree, &hdtbl_entry, NULL)) {
    return; /* heuristics dissector handled it. */
  }

  /* no dissector wanted it, try to print something appropriate. */
  switch (opcode) {
    case WS_TEXT: /* Text */
    {
    ....

   }
```

And that `websocket_conv->subprotocol` is essentially being set from the `Sec-WebSocket-Protocol` request header (which is `BLIP_3+CBMobile_2` in the blip case).  

Adapting the lua example:

```
-- create myproto protocol and its fields
p_myproto = Proto ("myproto","My Protocol")
local f_command = ProtoField.uint16("myproto.command", "Command", base.HEX)
local f_data = ProtoField.string("myproto.data", "Data", FT_STRING)

p_myproto.fields = {f_command}

-- myproto dissector function
function p_myproto.dissector (buf, pkt, root)
  info("p_myproto blip")
  -- validate packet length is adequate, otherwise quit
  if buf:len() == 0 then return end
  pkt.cols.protocol = p_myproto.name

  -- create subtree for myproto
  subtree = root:add(p_myproto, buf(0))
  -- add protocol fields to subtree
  subtree:add(f_command, buf(0,2)):append_text(" [Command text]")

  -- description of payload
  subtree:append_text(", Command details here or in the tree below")
end

-- Initialization routine
function p_myproto.init()
end

-- register a blip dissector
local ws_dissector_table = DissectorTable.get("ws.protocol")
ws_dissector_table:add("BLIP_3+CBMobile_2", p_myproto)
```

It's now emitting `p_myproto blip` in the logs, and showing `MYPROTO` in the wireshark UI:

![screen shot 2018-03-06 at 2 52 06 pm](https://user-images.githubusercontent.com/296876/37063353-fbc9f6cc-214d-11e8-915f-de7bb4be666c.png)

**Comment by tleyden** [comment]
@avsej 

I took `packet-json.c` and started adding the same hooks as from the lua file above:

https://github.com/couchbaselabs/blip-wireshark-dissector/blob/7b521aaacf2c54a42eee208a52bba292d2fbf512/packet-blip.c#L737-L748

When recording blip traffic, this successfully gets callbacks to `dissect_json` (not renamed yet), which shows that at least it's wired up correctly.

**Comment by avsej** [comment]
@tleyden, that's a great progress!

**Comment by rajagp** [comment]
@tleyden  Awesome! Can't wait to try and blog about it. Keep me posted!

**Comment by tleyden** [comment]
@avsej what are the restrictions on a dissector depending on 3rd party code?  (Eg blip-cpp).  Also can it be in c++?

**Comment by avsej** [comment]
I don't see any dissector written in C++ at the moment, but wireshark itself heavily using C++ and because they are going to deprecate GTK+ UI and moved to QT, I don't think that developers strongly against C++ in dissectors. Most part of the dissector is static and is not exported anyway.

But because this will be the first dissector in C++, it might require more than just adding single like into `epan/dissectors/CMakeLists.txt` and rather have some extra rules to hook C++ compiler there.

**Comment by tleyden** [comment]
It's now extracting more info:

<img width="1072" alt="screen shot 2018-03-07 at 7 00 45 pm" src="https://user-images.githubusercontent.com/296876/37130764-dcf4b290-2239-11e8-90a8-d63983103c89.png">

**Comment by tleyden** [comment]
I'm closing this out as done:

- The code is [here](https://github.com/couchbaselabs/blip-wireshark-dissector), with build instructions
- I posted a link to a pre-built OSX binary on internal hipchat Sync Gateway channel
- I added some [TODOs](https://github.com/couchbaselabs/blip-wireshark-dissector) to the `couchbaselabs/blip-wireshark-dissector` repo that would make it easier to use

**Comment by avsej** [comment]
Well done, @tleyden!!! :1st_place_medal:
