### ISSUE TITLE
Upgrade JQuery UI to at least 1.12.0

### ISSUE THREAD

**Issue by mikewied** [couchbase/sync_gateway#3360]
Vulnerability Description
Cross-site scripting (XSS) vulnerability in jQuery UI before 1.12.0 might allow remote attackers to inject arbitrary web script or HTML via the closeText parameter of the dialog function.

**Comment by adamcfraser** [comment]
@mikewied What flagged this as something that needed to be covered in the SG codebase?  We've taken an initial look at https://github.com/couchbaselabs/sync_gateway_admin_ui and nothing jumped out.

**Comment by mikewied** [comment]
This was flagged by an internal scanning tool that we've seen external users use as well.

**Comment by bbrks** [comment]
@mikewied Do you have any more information about what is being flagged? Does it show the path to the file/issue?

It would help us track down where the jQuery UI library is being pulled in from, as we couldn't find reference to the file from a quick search of our repos.

**Comment by adamcfraser** [comment]
@mikewied Is there a tracking ticket for this fix in FTS, that we can use to track the underlying fix in cbgt?

**Comment by tleyden** [comment]
Filed CBGT issue: https://issues.couchbase.com/browse/MB-29279
