### ISSUE TITLE
Adding "_delete" to CBS/SG docs doesn't reflect with continuous replication immediately

### ISSUE THREAD

**Issue by hrajput89** [couchbase/sync_gateway#3361]
### Sync Gateway version
2.0.0-814

### Operating system
The operating system you're running Sync Gateway on.

### Config file
```javascript
{
    "Interface": ":4984",
    "AdminInterface": "0.0.0.0:4985",
    "log": [
        "*"
    ],
    "MaxCouchbaseConnections": 16,
    "SlowServerCallWarningThreshold": 500,
    "MaxIncomingConnections": 0,
    "MaxFileDescriptors": 90000,
    "CompressResponses": false,
    "Databases": {
        "db": {
            "server": "http://172.16.1.169:8091",
            "pool": "default",
            "bucket": "travel-sample",
            "username": "travel-sample",
            "password": "password",
            "name": "db",
            "import_docs": "continuous",
            "unsupported": {
                "user_views": {},
                "oidc_test_provider": {}
            },
            "enable_shared_bucket_access": true,
            "session_cookie_name": ""
        }
    }
}
```

### Log output
[sgcollect_info.zip](https://github.com/couchbase/sync_gateway/files/1796479/sgcollect_info.zip)

### Expected behavior
Docs should get delete immediately after replication becomes idle

### Actual behavior
Docs are not deleted immediately after replication becomes idle

### Steps to reproduce
1.  Create a cluster with CBL app, SG and CBS server with push and pull replication
2. Add few docs and let the cluster come in sync.
3.  Now pick a doc and add _delete: true to the doc.
4. Wait for replication to finish and check if the doc is deleted from CBL app

**Comment by adamcfraser** [comment]
Are you setting `_deleted:true`, or `_delete:true`?  The latter isn't correct.

There's also not enough information on this ticket to get anything meaningful out of the SG logs.  Can you provide:
1. What's the docid for the document you're attempting to mark as deleted?  
2. How are you updating it?  (SDK, SG, CBL)?
3. Does the doc appear as deleted in somewhere other than CBL?

**Comment by hrajput89** [comment]
This is the doc content from CBS after http://192.168.0.177:4984/db/_bulk_docs to SG -

```
{  
    "_deleted":false,
    "channels":[  
        "ABC"
    ],
    "date_time_added":"2018-03-10 22:27:46.560054",
    "dict":{  
        "name":"PIEhiXiQcg"
    },
    "dict_with_list":{  
        "list":[  
            false,
            true
        ]
    },
    "list":[  
        587148159882254600,
        7170469240812529000
    ],
    "list_of_dicts":[  
        {  
            "friend_one":"htPoKsffzP"
        },
        {  
            "friend_two":"ATJgTyTtbB"
        }
    ],
    "updates":0
}
```

Doc doesn't get deleted from CBS immediately too.

PFA CBL logs for the this run - 
[sync_gateway_error.log](https://github.com/couchbase/sync_gateway/files/1799590/sync_gateway_error.log)

**Comment by adamcfraser** [comment]
@hrajput89 Can you provide answers for the four questions I asked above?  That will help clarify what’s being tested here.

**Comment by hrajput89** [comment]
@adamcfraser 

>Are you setting _deleted:true, or _delete:true? The latter isn't correct.

I'm setting _deleted:true

> What's the docid for the document you're attempting to mark as deleted?

I'm deleting several docs during the test. For instance, I've deleted "cbl_1", "cbl_115", etc. You can find the reference of doc ids deleted during test in attached "cbl_client_logs.log". Reference would be something like this -

```
Deleting 50 docs on SG
GET http://172.16.1.107:4984/ 200
http://172.16.1.107:4984/db/_bulk_docs
{"docs": [{"value": {"rev": "1-df9b2b1470e535c3069a7600ab71c823faecbda0"}, "id": "cbl_1", "key": "cbl_1", "_deleted": true}, {"value": {"rev": "6-a5238e748d26af05f0b2715558752df4"}, "id": "cbl_115", "key": "cbl_115", "_deleted": true}...
POST http://172.16.1.107:4984/db/_bulk_docs 201 
```

> How are you updating it? (SDK, SG, CBL)?

I'm updating docs using REST API of SG. Specifically using _bulk_docs api

> Does the doc appear as deleted in somewhere other than CBL?

Doc should get deleted from all CBL, SG and CBS. However, I don't see docs deleted anywhere.

CBL Logs - 
[sgcollect_info.zip](https://github.com/couchbase/sync_gateway/files/1801751/sgcollect_info.zip)
 
CBL Client Logs - 
[cbl_client_logs.log](https://github.com/couchbase/sync_gateway/files/1801753/cbl_client_logs.log)

**Comment by adamcfraser** [comment]
The `_bulk_docs` request you're using isn't correct.  The id and rev values for the doc should be specified as root level properties `_id` and `_rev`.  Since you're not specifying the `_id` property, the bulk_docs you're issuing is actually creating new documents with system-generated id values.  

You can see evidence of this in the SG logs:
```
2018-03-12T06:35:05.457Z HTTP:  #493: POST /db/_bulk_docs (as autotest)
2018-03-12T06:35:05.459Z CRUD+: Invoking sync on doc "76ae4c9de637a54d4fcffa82d5fad3a9" rev 1-429f56174d329b6fd11c2f6dfccac764
2018-03-12T06:35:05.460Z CRUD+: Saving doc (seq: #1513, id: 76ae4c9de637a54d4fcffa82d5fad3a9 rev: 1-429f56174d329b6fd11c2f6dfccac764)
```

Here's a sample payload for `_bulk_docs` that would accomplish what you're trying to do:

```
{"docs": [{"_rev": "1-f6fa803508c40388de38c9f99729c835", "_id": "cbl_1", "_deleted": true}]}
```

**Comment by adamcfraser** [comment]
Closing this ticket, as it seems like a clear-cut test issue.
