### ISSUE TITLE
Pull Replication hangs on large-sized Json-Documents.

### ISSUE THREAD

**Issue by weis** [couchbase/sync_gateway#3363]
We got problems with 5 large-sized documents in a pull-replication: the replication-process halted and the status remains "busy".

### Sync Gateway version
```
{
  "couchdb": "Welcome",
  "vendor": {
    "name": "Couchbase Sync Gateway",
    "version": "2.0"
  },
  "version": "Couchbase Sync Gateway/HEAD(keinZweig)(2b99523)"
}

```
### Client
Couchbase Lite Core 2.0, commit e457098d37af73af0d87175da392836d96982813, Date:   Fri Mar 2 18:17:58 2018 -0800.

### Operating system
CentOS Linux release 7.2.1511 (Core)

### Steps to reproduce
The reason seems to be in the size of a singular document.
In the attachement I have a file with five sample records, sorted by their size. 
As can be seen from the corresponding logfiles all five records are easily replicated 
to the couchbase server via sync-gateway in an empty bucket.
However, an appropriate pull-replication to a client stops at record 4(183 KB) and 5(366 KB).
The replication status remains "busy",  and the process stops, also after several attempts.
I posted the issue here, because we think this is a sg-problem.   

### Attachement
[testjson.zip](https://github.com/couchbase/sync_gateway/files/1802347/testjson.zip)

**Comment by adamcfraser** [comment]
This sounds like https://github.com/couchbase/couchbase-lite-core/issues/457 (and the associated SG fix https://github.com/couchbase/sync_gateway/pull/3362), which has been fixed since the build you're using.  Are you able to test with an updated build?

**Comment by weis** [comment]
Thank you, we will test it with the last commit.

**Comment by weis** [comment]
Now i have tested the updated build.
All ok, thank you!

**Comment by adamcfraser** [comment]
@weis Fantastic - thanks for the quick verification!
