### ISSUE TITLE
Move bucket shadowing to unsupported

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3364]
As of Sync Gateway 2.1, bucket shadowing will be an unsupported feature.  Move the config settings for shadowing to unsupported.

**Comment by tleyden** [comment]
@adamcfraser does this need to issue a warning if shadowing is in the previous place in the config?  (top-level of db config)  Or is it ok to silently ignore?

**Comment by tleyden** [comment]
@adamcfraser also, it seems like this will be easier to call this `deprecated_options` in the config, due to package dependency issues, and I think it also might be clearer to someone looking at the config or the code that these are deprecated as opposed to (possibly) upcoming features.

**Comment by tleyden** [comment]
Related docs ticket: https://issues.couchbase.com/browse/DOC-3486

**Comment by tleyden** [comment]
> does this need to issue a warning if shadowing is in the previous place in the config? (top-level of db config) Or is it ok to silently ignore?

On the current feature branch, it's returning this error:

```
		return fmt.Errorf("Bucket shadowing configuration has been moved to the 'deprecated' section of the config.  Please update your config and retry")
```
