### ISSUE TITLE
Log Redaction: Stub metadata and system data type functions

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3370]
As we're going through packages redacting user data, we might want the option of tagging data as metadata or system data, even if we don't do anything with it yet...

Need to write some no-op util functions that we can flesh out so less work is required to redact these extra types in the future:

```go
func MD(i interface{}) MetaData { ... }
func SD(i interface{}) SystemData { ... }
```

**Comment by tleyden** [comment]
I think this can be closed since https://github.com/couchbase/sync_gateway/pull/3371 was merged
