### ISSUE TITLE
CBL 2.0 replication spec w/ regards to proposeChanges and normal mode

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3372]
@snej / @adamcfraser: 

From the [2.0 replication spec](https://github.com/couchbase/couchbase-lite-core/blob/master/modules/docs/pages/replication-protocol.adoc#proposechanges)

> A peer not in conflict-free mode MUST reject a received proposeChanges message by returning a BLIP/404 error. This informs the sender that it should use changes instead.

After a cursory glance of [proposedChanges](https://github.com/couchbase/sync_gateway/blob/7e36f5f9cefbbbb87fcb15f1bdecdcb3b2b8dd61/rest/blip_sync.go#L472-L510), I'm not seeing anything that checks ` bh.db.AllowConflicts()` and conditionally returns a 404 error.

Should this be implemented?  Or should the spec be updated?

**Comment by snej** [comment]
That's obsolete. In fact LiteCore _always_ sends `proposeChanges` now, to avoid creating any conflicts remotely. It didn't use to, but then [Wayne & I realized](https://github.com/couchbase/couchbase-lite-core/issues/181) that if it pushed a conflict, it would end up pulling in the other branch of the conflict soon thereafter, and CBL would resolve it and push the merge. So it was less messy all around to just avoid pushing the conflicting rev. That way the conflict only exists in the local db.

**Comment by tleyden** [comment]
Ok thanks.  I submitted a PR to update the spec:

https://github.com/couchbase/couchbase-lite-core/pull/485
