### ISSUE TITLE
SG 2.0 Beta 2: Attachments missing 404

### ISSUE THREAD

**Issue by jayzhanghs** [couchbase/sync_gateway#3376]
It was working before, but suddenly I'm hit with missing attachment 404. On the workbench I can see the document `Demo::AppBundle` with its attachments, but not sure what went wrong when trying to fetch it from `CouchbaseLiteSwift` DB23. A recent change is two of the individual attachment size increased from 8MB to 27MB, but I believe size is not a matter with attachments.  

```
2018-03-21T21:21:02.221Z Sync+: [3b5a5e26] Sending rev "Demo::AppBundle" 11-dceaa
a14bf19aa0bb22d4ff4c210d1882 based on 0 known.  User:buyer@customer.com
2018-03-21T21:21:02.222Z Sync+: [3b5a5e26] Sending rev "648f0f18-cc8a-4150-8e9f--
cb56239e58eb" 2-2034cd62a237f9c951534edb971e1890 based on 1 known.  User:buyer@cc
ustomer.com
2018-03-21T21:21:02.224Z SyncMsg: [3b5a5e26] #003: Type:getAttachment Digest:shaa
1-T+Nzw+HIWRFm0jwn1b8A2+YQm94=  User:buyer@customer.com
2018-03-21T21:21:02.224Z SyncMsg: [3b5a5e26] #003: Type:getAttachment   --> 404
missing Time:806.896µs User:buyer@customer.com
2018-03-21T21:21:02.226Z SyncMsg: [3b5a5e26] #004: Type:getAttachment Digest:shaa
1-yyUwmm9x6EvGyQsD//yGQxsCYFg=  User:buyer@customer.com
2018-03-21T21:21:02.227Z SyncMsg: [3b5a5e26] #004: Type:getAttachment   --> 404
missing Time:729.135µs User:buyer@customer.com
2018-03-21T21:21:02.450Z HTTP+: [3b5a5e26] #056:    --> BLIP+WebSocket connectioo
n closed
```

### Sync Gateway version
Couchbase Sync Gateway/2.0.0(827;5b66afb)

### Operating system
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac

**Comment by tleyden** [comment]
> A recent change is two of the individual attachment size increased from 8MB to 27MB

That sounds like it's bigger than the max attachment size that can be handled by Sync Gateway, which I believe is 20 MB.  Are there any sync gateway logs about not being able to store the attachment?

@jamiltz do you know if we have the max attachment size documented anywhere?

**Comment by tleyden** [comment]
According to https://github.com/couchbase/sync_gateway/issues/197:

> because there's a 20mb size limit.

**Comment by jayzhanghs** [comment]
I somehow saw such a restriction somewhere before but I thought it was no longer an issue. but I may mixed up things.

**Comment by jayzhanghs** [comment]
@tleyden so what I understand from the issue #197 you included above, there's no limit on the size of the document, but 20MB is still the per attachment limit, even in SG 2.0?

**Comment by tleyden** [comment]
My understanding is that the size of a single JSON document cannot exceed 20MB, nor can the size of a single attachment.  And yes, this is true for both SG 1.5 and SG 2.0, since it's gated by the document size of the underlying Couchbase Server document size.

**Comment by tleyden** [comment]
@snej what's the expected cblite behavior if the user saves a document with attachment larger than 20 MB?  Will the push succeed for that doc?  Will other puller see the errors mentioned in this issue?

**Comment by jayzhanghs** [comment]
@tleyden just to understand this more accurately, are sizes of attachments calculated into the total size of a JSON document, or just the meta info (purely the text part of the JSON without the attachment binaries)? if the latter, I can actually have multiple 19.5MB attachments on a document as long as the JSON dictionary part doesn't exceed 20MB, right?

**Comment by snej** [comment]
Attachments are stored separately from document bodies, so there is a 20MB limit for each attachment, as well as for the document body itself.

**Comment by tleyden** [comment]
>  or just the meta info (purely the text part of the JSON without the attachment binaries)

Just the meta info

> if the latter, I can actually have multiple 19.5MB attachments on a document as long as the JSON dictionary part doesn't exceed 20MB, right?

Yep

**Comment by jayzhanghs** [comment]
Thanks @tleyden  for the clarification

**Comment by snej** [comment]
Can this be closed?

**Comment by jayzhanghs** [comment]
yes thanks

**Comment by jamesnocentini** [comment]
> do you know if we have the max attachment size documented anywhere?

@tleyden Yes it is mentioned somewhere on a guide. Added that info on the API ref. PUT/POST endpoints for documents and attachments https://github.com/couchbaselabs/couchbase-mobile-portal/commit/218caf52b552c216871b070a000863608196eb79

**Comment by snej** [comment]
@jamiltz That's the SG REST API doc, which is pretty far away (conceptually) from Couchbase Lite; I don't think a CBL developer learning about attachments/blobs would look there.

**Comment by jamesnocentini** [comment]
Yes indeed, wrote it down in the CBL guides too.

1.x: https://github.com/couchbaselabs/couchbase-mobile-portal/commit/63a28112886cfb0a5fa3d6cdc0c0808936692e3c
2.0: https://github.com/couchbase/couchbase-lite-ios/pull/2116
