### ISSUE TITLE
Blip Context Serial Number padding

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3385]
We log the blip context serial number padded to 3 digits (`%03d`), this likely isn't enough, pad to 4 or 5 digits instead.

https://github.com/couchbase/sync_gateway/blob/a60c2d92addb7da9332b9e11156a4b5176482c60/rest/blip_sync.go#L119

**Comment by adamcfraser** [comment]
Can just remove padding altogether.
