### ISSUE TITLE
sg-replicate should skip partial bulk_docs errors if status != 503

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3387]
As reported in https://github.com/couchbase/sync_gateway/issues/3375, does sg-replicate have same behavior as cblite 1.x during errors during _bulk_docs requests?

**Comment by tleyden** [comment]
## sg-replicate behavior

sg-replicate treats all bulk_docs errors as temporary errors, meaning it will keep retrying them until they are resolved.  At no point will it give up and skip the problematic docs and keep replicating.

The reason for this behavior is that it doesn't have a way to differentiate temporary bulk_docs errors vs permanent bulk_docs errors (there's a ticket filed here to improve that on the SG side: https://github.com/couchbase/sync_gateway/issues/1887), and so it doesn't know when to *safely* skip documents.

**Pros**

It won't silently skip over documents when replicating, in particular documents that had temporary errors.  (which was previously seen in https://github.com/couchbase/sync_gateway/issues/1846, and has since been fixed)

**Cons**

As reported in https://github.com/couchbase/sync_gateway/issues/3375, the replicator will get "stuck" in scenarios where permanent errors were introduced on purpose in the sync function

## cblite behavior

In my initial test, when given a permanent bulk_docs partial error:

```
[{"error":"forbidden","id":"-0UXFvX-lT6BZhTN32WM4sm","reason":"artificial error","status":403}]
```

It did not cause the replicator to get stuck, and later changes were successfully pushed to sync gateway.  sg-replicate should be improved to match this behavior.

(note: I haven't yet tested to see the cblite behavior on temporary 503 errors.)


## Recommendation for fix

If https://github.com/couchbase/sync_gateway/issues/1887 can be closed, then sg-replicate can be updated to have the following behavior:

1. If status code indicates a permanent error, ignore it and skip
1. If status code indicates a temporary error, keep the same behavior that is currently done for all partial `_bulk_docs` errors, and keep retrying until it is successfully pushed.

**Comment by tleyden** [comment]
Original ticket from erpankaj22:

We have a expiry time in each document, this expiry time is in epoch. If the time has expired then we reject the document using sync function.

Sync gateway to sync gateway sync stops as soon as one document in the pipeline is rejected by the sync gateway. It goes into a loop where it will not continue syncing any document further.

We need to stop taking the document because we purge them, hence having minimum number of required document in the bucket. So the documents according to business rule will never come back after the purge. And even if they come the data is useless.

What is the workaround to not to stop sync. Is marking them _deleted is the only solution for this. If yes then will tombstone will also be cleared from the application automatically or a compact function call will be required.

the expiry is not the standard TTL. It is a cusom field in which we put date time in EPOCH after which updates of these documents will be discarded on the sync gateway and following is the sync function for the same we are using

```
function(doc,oldDoc)
{
var d = new Date();
var n = d.getTime();
if(doc.ExpiryDateEpoch!=null)
{
if(n >= doc.ExpiryDateEpoch)
{
throw( { forbidden: “Document Expired” } );
}
}
channel(doc.channels);
}
```
now in when the SG to SG replicate starts then this issue comes even if one of the document whose ExpiryDateEpoch has crossed is rejected by the function.

Following is the forum id :- https://forums.couchbase.com/t/sync-gateway-to-sync-gateway-stops-syncing-even-if-one-document-is-rejected-by-sync-function/16237/3

**Comment by tleyden** [comment]
After digging into this a bit, it looks like it's already working as expected.  See https://github.com/couchbaselabs/sg-replicate/pull/59

**Comment by ghost** [comment]
We have faced this issue in sync gateway 1.4.1

**Comment by tleyden** [comment]
@erpankaj22081982 ok thanks.  I think we'll probably need to see the Sync Gateway logs assuming you are running the replications inside of Sync Gateway (as opposed to running sg-replicate as a standalone tool, in which case you will need to provide those logs as well).  

Can you post the logs to a gist and link to this issue?  Alternatively, open a support issue and upload your logs to the support issue.
