### ISSUE TITLE
User TTL support

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3389]
Put together high level technical spec for user TTL support:

 - Ability to define a user TTL in the Sync Gateway config
 - When users are created, set the TTL on the user document
 - Reset the TTL (via GetAndTouch) whenever the user document is accessed

Possible questions:
 - Should role documents have the same treatment?

**Comment by tleyden** [comment]
# Implementation TODO

- [x] Write unit test coverage for `getPrincipal()`
    - Simulate CAS retry failures
- [x] Modify `getPrincipal()` to use `WriteUpdateAndTouch()`
- [x] Rip out temp hacks 
- [x] Add config setting and documentation
- [x] Avoid DCP echo overhead
- [ ] Cascade deletion of `_sync:useremail:` docs

**Comment by tleyden** [comment]
Changing milestone to 2.2.0 -- not sure if it should be 2.2.0 or 3.0

**Comment by househippo** [comment]
This requirement is for user clean up as device are upgraded over time. 
It be great to get a solution that doesn't result in a write to disk every-time the status of the user is checked. I'm guessing a touch() or sub-doc() every second would be to much. Even every minute might mean a lot of writes. I think a write per 15 min , 1 hour or 1 day per user would not be that bad.

**Comment by adamcfraser** [comment]
Closing as proposed feature hasn't been prioritized.

**Comment by adamcfraser** [comment]
Migrated to https://issues.couchbase.com/browse/CBG-799
