### ISSUE TITLE
SG panic during docmeta -> xattr upgrade test with nil pointer dereference

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#3393]
### Sync Gateway version
2.0.0-823

### Operating system
CentOS7

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+", "Import+"],
    "databases":{
        "db":{
            
            "enable_shared_bucket_access": true,
            
            "server":"http://192.168.33.20:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password"
        }
    }
}
```

### Log output
https://gist.github.com/raghusarangapani/cc762f79cf6256f3d58deaf344a69038

### Expected behavior
SG should not panic

### Actual behavior
One SG node had the `"import_docs": "continuous"` and `"enable_shared_bucket_access": true` set. The second SG node only had `"enable_shared_bucket_access": true` set.

The second SG node panicked after enabling the shared bucket access and restart.

### Steps to reproduce

Switch to `fix/upgrade-tombstone` mobile-testkit branch

```
pytest --timeout 36000 -s --xattrs --mode=cc --server-version=4.6.4-4590 --server-upgraded-version=5.1.0-5552 --sync-gateway-version=1.5.1-4 --sync-gateway-upgraded-version=2.0.0-823 --liteserv-host=localhost --liteserv-port=59840 --liteserv-version=1.3.1-6 --liteserv-platform=macosx --liteserv-storage-engine=SQLite --num-docs=10 --cluster-conf=2each_lb --cbs-platform=centos7 testsuites/syncgateway/upgrade
```

### Rolling upgrade scenario:
- Install 2 nodes with 4.6.3 CBS, 2 nodes with 1.4.1 SG and 1 nginx load balancer for SGs.
- Nginx is configured to move on to the next node if there is no response from upstream nodes within 2 seconds.
- If “di” mode is enabled, install 2 nodes with 1.4.1 SGAccel.
- Start CBL that talks to load balancer and start push pull replication between CBL and SG.
- Add docs through CBL.
- In a separate thread, start updating docs.
- In the main thread, upgrade SGs one after the other
   - Stop SG service
   - Rpm –U couchbase-sync-gateway
   - Start SG service.
- If “di” mode is enabled, upgrade SGAccels one after the other
   - Stop SGAccel service
   - Rpm –U couchbase-sync-gateway-accel
   - Start SGAccel service.
- Upgrade CBS one after the other
   - Rebalance out the node
   - Rpm –e couchbase-server
   - Install new 5.0 rpm
   - Add node back to the cluster
   - Rebalance in
- Restart all SG nodes one by one after server upgrade.
- If “di” mode is enabled, restart all SGAccel nodes one by one after server upgrade.
- If xattrs (convergence) is enabled
   - If mode == “cc” (only sync gateways)
      - Stop SG
      - Set "import_docs": "continuous" only on the first SG node.
         - Set "enable_shared_bucket_access": true on all SG nodes.
         - Start SG.   <============================== SG seems to have panicked here.
   - If mode == “di” (sync gateways and SGAccels)
      - Stop SG/SGAccel
      - Set "enable_shared_bucket_access": true on all SG nodes and on all SGAccel nodes.
      - Do not enable import on SG or SGAccel nodes (SGAccel nodes will import with enable_shared_bucket_access set to true)
      - Start SG/SGAccel
- Stop doc updates
- Verify doc ids, revisions, revision history and doc body.

**Comment by adamcfraser** [comment]
Based on the error, the following might repro in a single node environment:
1. Write doc1/rev1 w/out xattrs enabled
2. Restart w/ xattrs enabled, but without import enabled
3. Attempt to write doc1/rev2

**Comment by adamcfraser** [comment]
The above doesn't repro.  However, I'm able to reproduce this with the following steps:

1. Write doc1/rev1 WITH xattrs enabled
2. Restart without xattrs enabled
3. Attempt to write doc1/rev2

This doesn't line up with what @raghusarangapani described as the point of failure, but that may be a test-related issue.  The underlying bug still looks like a regression in 2.0.0.

**Comment by raghusarangapani** [comment]
Verified with SG 832 build:
docmeta -> docmeta and docmeta -> xattrs upgrade went fine with 10 docs. 
Will kick off jenkins jobs with more number of docs.
