### ISSUE TITLE
Add unit test for checkForUpgrade handling

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3395]
Requires writing bucket docs w/ xattrs, but running SG in non-xattr mode.  (reverse of scenario seen in import_test.go.

**Comment by adamcfraser** [comment]
Would require writing a test that's marked to run in non-xattr mode only, and do the following:

1. Write a doc directly to the bucket w/ xattrs
2. Attempt to update that doc using the non-xattr version of SG.

**Comment by bbrks** [comment]
Issue being tracked at [CBG-227](https://issues.couchbase.com/browse/CBG-227)
