### ISSUE TITLE
Sync_Gateway config file only supports one URL in connection string

### ISSUE THREAD

**Issue by NoSQLKnowHow** [couchbase/sync_gateway#341]
Sync_gateway config file only supports 1 URL in the connection string for connecting to a Couchbase DB cluster. The best practice in connecting to a Couchbase DB cluster is to have at minimum 2-3 nodes of the cluster in the connection string in an array so in case the one node is down, the client can still get the cluster map from another member of the cluster. If the node tried is unresponsive, it should move to another node in the array. 

In addition, the sync_gateway should randomize which of the n+1 nodes in the array is used initially.

**Comment by adamcfraser** [comment]
Fixed in 1.5.0.
