### ISSUE TITLE
TestAccessFunctionWithVbuckets fails due to number of vbuckets assumption

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3413]
Failure: https://github.com/couchbase/sync_gateway/pull/3412#issuecomment-378428986

Fix: https://gist.github.com/tleyden/8c83ec51d3fc57b5b5b69242d018b3d8

@adamcfraser to check in with upcoming GSI PR

**Comment by adamcfraser** [comment]
Fixed, but need to re-enable the test.

**Comment by adamcfraser** [comment]
Fixed w/ https://github.com/couchbase/sync_gateway/pull/3486
