### ISSUE TITLE
JavaScript dates far in the past or future are incorrect

### ISSUE THREAD

**Issue by OldSneerJaw** [couchbase/sync_gateway#3426]
The JavaScript `Date` object produces incorrect values when it encounters a date after "2262-04-11T23:47:16.854Z" or before "1677-09-21T00:12:43.146Z" when used in a sync function. Notably, the date seems to wrap around to the low value when it passes the high value and vice versa. For example, parsing "2262-04-11T23:47:16.855Z" (one millisecond after the high value) produces the date "1677-09-21T00:12:43.146Z" (equal to the low value) and parsing "1677-09-21T00:12:43.145Z" (one millisecond before the low value) produces the date "2262-04-11T23:47:16.854Z" (equal to the high value).

Originally reported directly to the otto project as https://github.com/robertkrimen/otto/issues/302.

### Sync Gateway version
Couchbase Sync Gateway/2.0.0(823;5b66afb)

### Operating system
macOS High Sierra

### Config file
```javascript
{
  "log": [ "HTTP+", "Events+" ],
  "adminInterface": "127.0.0.1:4985",
  "interface": ":4984",
  "databases": {
    "test": {
      "server": "walrus:",
      "sync": `
function(doc, oldDoc) {
  var date = new Date(doc.date);
  if (date.getTime() < new Date('1970-01-01')) {
    throw { forbidden: 'date must not be less than 1970-01-01' };
  }
}`
    }
  }
}
```

### Log output
N/A

### Steps to reproduce
1) Attempt to create a document with the high value ("2262-04-11T23:47:16.854Z") described above:

```
PUT /test/foo-1 HTTP/1.1
Host: localhost:4985
Content-Type: application/json

{
  "date": "2262-04-11T23:47:16.854Z"
}
```

This document will be accepted, as expected.

2) Attempt to create a document with a value that is one millisecond after the high value:

```
PUT /test/foo-2 HTTP/1.1
Host: localhost:4985
Content-Type: application/json

{
  "date": "2262-04-11T23:47:16.855Z"
}
```

This document will be erroneously _rejected_ even though it is clearly after the date "1970-01-01". That is because it was incorrectly interpreted by the `Date` object as "1677-09-21T00:12:43.146Z".

3) Attempt to create a document with the low value ("1677-09-21T00:12:43.146Z") described above:

```
PUT /test/foo-3 HTTP/1.1
Host: localhost:4985
Content-Type: application/json

{
  "date": "1677-09-21T00:12:43.146Z"
}
```

This document will be rejected, as expected.

4) Attempt to create a document with a date that is one millisecond earlier than the low value:

```
PUT /test/foo-4 HTTP/1.1
Host: localhost:4985
Content-Type: application/json

{
  "date": "1677-09-21T00:12:43.145Z"
}
```

This document will be erroneously _accepted_ even though it is clearly before the date "1970-01-01". That is because it was incorrectly interpreted by the `Date` object as "2262-04-11T23:47:16.854Z".

### Expected behavior
Documents 1 and 2 should be accepted while documents 3 and 4 should be rejected.

### Actual behavior
Documents 1 and 4 are accepted and documents 2 and 3 are rejected.

**Comment by adamcfraser** [comment]
Tracking ticket for the underlying otto fix.

**Comment by adamcfraser** [comment]
No sign of a fix on the otto side.  Closing this based on age - can be reopened if this is fixed in otto, or the use case is prioritized.
