### ISSUE TITLE
Unable to differentiate between null and missing fields in the sync function

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3432]
Steps to reproduce:

- Create doc with null value: `{"nullProperty": null}`
- In the sync function, add line `console.log("doc['nullProperty']: " + doc['nullProperty'] + " " + typeof doc['nullProperty']);`

Actual output:

```
doc['nullProperty']: undefined undefined
```

Expected output:

```
doc['nullProperty']: null object
```

This was originally reported in https://forums.couchbase.com/t/sync-function-null-equals-undefined/16464

Might be related to this Go behavior: https://play.golang.org/p/iZHgHr1CPEx

**Comment by adamcfraser** [comment]
Closing based on age - can be reopened based on priority.
