### ISSUE TITLE
Sync function allows mutations in in-memory copy of document

### ISSUE THREAD

**Issue by HodGreeley** [couchbase/sync_gateway#3445]
Steps to reproduce:

- Invoke sync function with doc with no key 'foo'
- In sync function, assign, e.g., `doc['foo']` = "bar;`
- In SG admin console, pull up doc.  Notice it contains `"foo": "bar"`

Mutation is not persisted to CB Server or otherwise propagated.

Expected behavior: Mutation should have no visible effect.  Or possibly throw an error?

Confirmed in SG 1.5.1 under OSX

**Comment by adamcfraser** [comment]
Is this only for a doc created via the admin console, or also for a doc created via the REST API?

**Comment by HodGreeley** [comment]
Creation via the REST API shows the same issue.

**Comment by adamcfraser** [comment]
@HodGreeley Can you confirm whether you see this behaviour against a walrus or Couchbase Server backing store (or both)?

**Comment by adamcfraser** [comment]
@tleyden to help @HodGreeley investigate where exactly the underlying issue is.

**Comment by tleyden** [comment]
I'm able to reproduce this using the steps @HodGreeley posted.  Both with Walrus and with Couchbase Server.

When using Couchbase server, I can see that the value set via the sync function:

```
        "sync": `
           function(doc, oldDoc) {
	      channel(doc.channels)
              doc["sync_function_value"] = "hello_world"
           }
`,
```

shows up in the SG Admin UI:

![screen shot 2018-04-26 at 11 38 58 am](https://user-images.githubusercontent.com/296876/39325196-6fa72676-4946-11e8-9c1b-3ff71944ed0f.png)

but not the couchbase server doc:

```
{
  "_sync": {
    "rev": "1-fc2cf22c5e5007bd966869ebfe9e276a",
    "sequence": 4,
    "recent_sequences": [
      4
    ],
    "history": {
      "revs": [
        "1-fc2cf22c5e5007bd966869ebfe9e276a"
      ],
      "parents": [
        -1
      ],
      "channels": [
        null
      ]
    },
    "cas": "",
    "value_crc32c": "",
    "time_saved": "2018-04-26T11:35:13.059007-07:00"
  },
  "value": "foo"
}
```

**Comment by tleyden** [comment]
After trying to edit the value in the admin UI by setting the value to `foo23` and clicking the save doc button, it ends up saving the emitted sync function value into the actual doc.  After the edit, the SG UI shows:

```
{
  "sync_function_value": "hello_world",
  "value": "foo23",
  "_rev": "2-f9184ac6546b9ff24bf17c4669c1f73f",
  "_id": "742280478cb327c2386cec9c738dc1a1"
}
```

and in the Coucbhase Server bucket:

```
{
 "_sync": ... 
 "sync_function_value": "hello_world",  
  "value": "foo23"
}
```
