### ISSUE TITLE
Logging: Update service scripts

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3448]
The service scripts currently redirect `stdout` and `stderr` logs to `_access.log` and `_error.log` files.

The locations of these files may be different depending on OS and distro, and isn't currently passed to SG. This means the new logging stuff has to work out a path for it's log files based on a relative path from the executable.

It would be nice if the service files passed this in as a command line flag and then SG could use it as a fallback if `logFilePath` is not specified in the config.

**Comment by adamcfraser** [comment]
Perf team hit an issue trying to use service install on centos w/ the latest build:

[ERR] Error setting up logging: Invalid LogFilePath: mkdir /opt/couchbase-sync-gateway/bin/var: permission denied -- base.Fatalf() at logging.go:81

Was able to work around by having them specify 
```
  "logging": {
    "logFilePath": "/var/tmp/sglogs"
  },
```
in their config, but need to fix out of the box.
