### ISSUE TITLE
Benchmark test high log rotation churn

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3485]
We want to be sure that very high log-rotation churn will not impact Sync Gateway.

A useful test would be lowering debug level max_size down to 1mb, and hammering SG to force a high rate of log rotation/compression.

A lot of the log-rotation work is done in the Lumberjack library, but it would be useful to verify that it will not impact the main application significantly.

**Comment by adamcfraser** [comment]
Closing based on go benchmarking that's been done.
