### ISSUE TITLE
Handle index creation race between SG nodes

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3488]
Multiple SG nodes can end up in an index creation race on initial startup - after index detection fails, both will attempt to create the new indexes.  

SG needs to identify creation failure due to the index already existing, treat that as a non-fatal error, and proceed to index readiness check.

**Comment by raghusarangapani** [comment]
I still see the issue with the latest build:
```
# tail -f /home/sync_gateway/logs/sg_error.log           
2018-04-27T21:30:36.522Z ==== Couchbase Sync Gateway/2.1.0(60;2416f0b) ====
2018-04-27T21:30:48.344Z [ERR] Error opening database db: [5000] BuildIndexes - cause: Index sg_allDocs_1 is already built . -- rest.RunServer() at config.go:887
```

**Comment by adamcfraser** [comment]
The error above is different than the original one fixed on this ticket, but related.

When we detect a failed create (index already exists), we're still incorrectly issuing a build for that index.

More generally, we need to manage concurrent build invocation failures more gracefully.  The absence of useful error coding from the indexer doesn't help here.  We may need to reconsider some sort of bucket-based locking during startup to avoid these issues.

**Comment by adamcfraser** [comment]
Fixed w. #3498
