### ISSUE TITLE
Cannot set document expiry with a literal numeric value

### ISSUE THREAD

**Issue by OldSneerJaw** [couchbase/sync_gateway#3489]
### Sync Gateway version
Couchbase Sync Gateway/2.0.0(832;2d8a6c0)

### Couchbase Server version
Couchbase Server Enterprise Edition 5.5 Beta

### Operating system
macOS High Sierra

### Config file
```javascript
{
  "log": [ "HTTP+", "Events+", "CRUD+" ],
  "adminInterface": "127.0.0.1:4985",
  "interface": ":4984",
  "databases": {
    "test": {
      "server": "http://localhost:8091",
      "bucket": "test",
      "username": "user",
      "password": "password",
      "enable_shared_bucket_access": true,
      "import_docs": "continuous",
      "sync": "function(doc, oldDoc) { expiry(4077433455); }"
    }
  }
}
```

### Log output
https://gist.github.com/OldSneerJaw/2f0068058344d82aef0b6ba4cbeea6aa

### Steps to reproduce
1. Create a Couchbase Server bucket called "test"
2. Ensure that there is a Couchbase Server user named "user" that has the "Bucket Full Access" role for the "test" bucket
3. Launch Sync Gateway with the example configuration specified above
4. Create a document as follows:

```
PUT /test/expiry-test-1 HTTP/1.1
Host: localhost:4985
Content-Type: application/json

{ }
```

### Expected behavior
The document should be created and assigned an expiration value of 4077433455.

### Actual behavior
The document will be created, but the document's expiration value will be zero. You can see from this line in the referenced log output that the expiry value was rejected:

```
2018-04-21T16:49:06.492-07:00 WARNING: SyncRunner: Invalid value passed to expiry().  Value:4077433455  -- channels.NewSyncRunner.func5() at sync_runner.go:171
```

However, it is worth noting that, if you alter the sync function as follows, the document will be created and it will be correctly assigned an expiration of 4077433455 even though the value that is passed to the `expiry` function is equal to that from the example configuration:

```javascript
function(doc, oldDoc) { expiry(1 * 4077433455); }
```

Furthermore, updating the sync function as follows to pass an ISO 8601 string value that represents the same point in time as in the example configuration also results in the document being created and correctly assigned an expiration value of 4077433455:

```javascript
function(doc, oldDoc) { expiry('2099-03-17T12:24:15Z'); }
```

**Comment by rajagp** [comment]
Seems related to https://github.com/couchbase/sync_gateway/issues/3452.

**Comment by OldSneerJaw** [comment]
@rajagp: Right you are. It seems I neglected to include closed issues in the search filter when I was looking for related issues before creating this duplicate ticket.
