### ISSUE TITLE
Move all gocb error type checking to bucket_gocb.go

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3493]
As discovered in https://github.com/couchbase/sync_gateway/issues/3491, wrapping these errors caused calling code to fail -- this code was doing type assertions on the error looking for specific gocb error types.

Fix:

- Move all type assertions about gocb errors to `bucket_gocb.go`
- Define errors such as sgbucket.ErrKeyNotFound, sgbucket.ErrKeyExists, which would be returned from walrus and to consumers of `bucket_gocb.go`

**Comment by adamcfraser** [comment]
Closing based on age - this approach has been followed in most cases, can reopen if specific cases identified.
