### ISSUE TITLE
Duplicate doc ids with * channel

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#3500]
Originally https://issues.couchbase.com/browse/CM-64

SG 2.1.0-14, CBS 5.0.0-2361:
Issue:
Tests using * channel are failing with duplicate doc ids
Test case:
Run the below test from the feature/sg21 branch of mobile testkit:
pytest -s --timeout 1800 --mode=cc --server-version=5.5.0-2361 --sync-gateway-version=2.1.0-14 testsuites/syncgateway/functional/tests/ --skip-provisioning -k 'test_overloaded_channel_cache[sync_gateway_channel_cache-1000-*-True-50]'

**Comment by raghusarangapani** [comment]
Logs can be found in the jenkins run for 2.1.0-60:
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc-converg/218/

**Comment by adamcfraser** [comment]
The index being used for the star channel query (sg_allDocs) is misconfigured and isn't ordering by sequence.
