### ISSUE TITLE
Unable to modify log level via _logging REST API

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3501]
Ran into a few issues when using the _logging admin endpoint:

 - calling `PUT /_logging?level=10` panics with a nil pointer dereference
 - calling `PUT /_logging?logLevel=debug` returns a 500 internal error "nil log level"
 - calling `POST /_logging` with `{"logLevel":"debug"}` returns "Invalid JSON or non-boolean values"

**Comment by bbrks** [comment]
Thanks @adamcfraser, these seem like good candidates for adding to `TestLogging` 😃 

https://github.com/couchbase/sync_gateway/blob/d736f556c2d8da86f40cfd1ec8a3c03c108db387/rest/admin_api_test.go#L424-L498
