### ISSUE TITLE
Remove pre-emptive GoCB throttling

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3506]
Currently there is a pre-emptive guard to throttling GoCB used throughout the SG codebase, in order to prevent `ErrOverload` errors from happening.

This can be removed and be replaced with more intelligent handling of `ErrOverload` errors (eg, backoff retry)

This came out of the investigation into the cause of https://github.com/couchbase/sync_gateway/issues/3212

**Comment by tleyden** [comment]
Needs some more design to see how this will interact with #3509 to try to find a good balance between intelligently managing backpressure vs propagating to cblite clients.

**Comment by adamcfraser** [comment]
Tracking with CBG-638.
