### ISSUE TITLE
Improve GoCB backpressure handling

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3509]
## Current Behavior

When SG receives `operation timed out` errors, it will do a backoff retry until the request succeeds, or eventually give up after several tries.

## Problems with current behavior

1. Can create an undesirable positive feedback loop where retries trigger more ops which further degrades the performance of the SDK, which causes further timeouts, etc...
1. Increases # of open HTTP request sockets
1. SG API client's (aka CBLite most of the time) HTTP requests can timeout, which will cause t and they implement retry on the client side, which will *exacerbate* the positive feedback loop mentioned above.

## Interim fix

See https://github.com/couchbase/sync_gateway/issues/3508

## Proposed change

When `opTimeout` errors are received, propagate these to SG API clients as temporary errors.  This will effectively propagate the backpressure, and simplify the SG code.

## Possible side effects of change

SG API clients such as CBLite and sg-replicate will need to retry these requests, since they may or may not have succeeded (sometimes even when GoCB returns an `opTimeout` error, the operation still succeeds with Couchbase Server)

This came out of the investigation into the cause of https://github.com/couchbase/sync_gateway/issues/3212

## CBLite changes required

As mentioned in https://github.com/couchbase/couchbase-lite-core/issues/525#issuecomment-406662052, LiteCore already supports the required behavior, but the CBLite platform wrappers will need to be extended to handle these cases.

- [ ] Open issues for each CBLite platform

**Comment by adamcfraser** [comment]
Should evaluate how to easily test client behaviour without needing to generate significant load.

**Comment by tleyden** [comment]
This one probably needs some more discussion w/ the CBLite team in terms of an agreement on retry behavior.   For now, moving this to the icebox.

**Comment by adamcfraser** [comment]
Tracking with CBG-638.
