### ISSUE TITLE
SG 1.4.1 & CB 5.5 - No TAP 

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#3511]
Testing SG 1.4.1 & CB 5.5 compatibility.
Looks like TAP is no longer in CB 5.x. https://developer.couchbase.com/documentation/server/5.0/release-notes/relnotes.html

SG 1.4.1 - GA even if I change and use "feed_type":"DCP or TAP" Its still not working with CB 5.5 - Enterprise Edition 5.5.0 build 2036

WITH TAP I get this error:
```
2018-04-25T14:18:29.170-07:00 [ERROR] go-couchbase: Tap feed from 127.0.0.1:11210 failed: tap connection failed:  
2018-04-25T14:18:29.170-07:00 [INFO] go-couchbase: TAP connection lost; reconnecting to bucket "cake" in 1s 
```
**_changes**
I'm able to get a _changes but it doesn't update _changes b/c there is no TAP feed.

WITH DCP I get this error:

`2018-04-25T14:23:39.914-07:00 WARNING: Feed%!(EXTRA string=Error processing DCP stream: %v, *errors.errorString=UPROpen receive, err: EOF) -- base.(*DCPReceiver).OnError() at dcp_feed.go:115`

**_changes**
There is no changes feed because SG DB goes into offline state.

```
{
  "error": "Service Unavailable",
  "reason": "DB is currently under maintenance"
}
```

**Comment by adamcfraser** [comment]
I don't think we've committed to having 1.4.1 work with 5.5. 

Do you see the same behaviour when attempting to use 1.4.1/DCP with 5.0?

**Comment by adamcfraser** [comment]
Closing this - please reopen if there's something in the published compatibility matrix that doesn't work.
https://developer.couchbase.com/documentation/mobile/2.0/upgrade.html
