### ISSUE TITLE
[Feature request] Allow fetching of documents in sync function

### ISSUE THREAD

**Issue by ssured** [couchbase/sync_gateway#352]
JSON Schema is a really nice way to describe the allowed format of json data. To me it makes sense to use this syntax in the sync function, to validate document writes. A nice library for validating using javascript exists, see https://github.com/acornejo/jjv, which can be copy-pasted into the sync function.

The problem which then arises is that all schemas need to be defined in the sync function. It would be awesome if the sync function can load a document from its own database. That allows for writing a sync function which loads a format from the db and tests the supplied json against the data from the DB.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
