### ISSUE TITLE
2.1.0- sg collect info - Show message if sync gateway is not running 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3526]
### Sync Gateway version
sg version -> 2.1.0-55

### Operating system
Centos

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "logging": {
        "redaction_level": "partial"
    },
    "databases":{
        "db":{


            "num_index_replicas": 0,
            "num_index_replicas_housekeeping": 0,
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "password": "password"
        }
    }
}

```

### Log output
Provide a link to a GitHub Gist containing relevant Sync Gateway log output when
the error occured. Do NOT paste the log output in the issue, just paste the
link to the Gist.

### Steps to reproduce
1.  Start sync_gateway
2.  Do some api calls to sync_gatway
3.  Verify sync_gateway logs
4. Stop sync_gateway

### Expected behavior
It should display a message that sync_gateway is running to let the user know

### Actual behavior
It displays that it is unsuccessful and 'connection refused'. In addition to unsuccessful, it should display that sync_gateway is not running

### logs : 
https://gist.github.com/sridevi-15/b758724dcfd38101de491e14ad6ae8a9

**Comment by adamcfraser** [comment]
I'm not aware of a requirement that SG be running in order to run sgcollect.  sgcollect shouldn't be exiting with error if it's unable to reach the SG endpoints, but I'd expect it to attempt to retrieve from the default config/log locations.

**Comment by bbrks** [comment]
@adamcfraser Turns out I'd made an incorrect assumption about that a while back! 😨  Properly fixed in #3528 !

**Comment by sridevi-15** [comment]
So, what is the final fix, will sgcollect_info will redact though sync_gateaway is not reachable?

**Comment by sridevi-15** [comment]
working fine with sg 2.1.0-71. it collects and redacts data without having sync_gateway running
