### ISSUE TITLE
Review log keys and consolidate

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3529]
Review existing log keys and consolidate

https://github.com/couchbase/sync_gateway/blob/5949967c6bff875be144abf3eb88d8edb58babdf/base/log_keys.go#L55-L90

**Comment by adamcfraser** [comment]
KeyAttach -> KeyCRUD
KeyChannelIndex -> KeyAccel
KeyChannelStorage -> KeyAccel
KeyCompact -> KeyAccel, remove 'time to compact' log line.
KeyFeed -> KeyDCP (one usage in assimilator.go can change to KeyShadow)
KeyHeartbeat -> KeyChanges, and change all usages to debug
KeyIndex -> KeyQuery
KeyIndexEntries -> KeyAccel
KeyOIDC -> KeyAuth
KeyRollback -> KeyDCP
KeySequences -> KeyChanges
