### ISSUE TITLE
Question: which logging API method should I use to enable test logs?

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3531]
While trying to debug a test related to https://github.com/couchbase/sync_gateway/issues/3422, I added this logging statement:

```
LogToR(KeyQuery.String(), "Executing N1QL query: %v", UD(n1qlQuery))
```

and updating the test to enable that log key:

```
var logKeys = map[string]bool{
	"Sequence": true,
	base.KeyQuery.String(): true,  // <-- added
}
base.UpdateLogKeys(logKeys, true)
```

but was not seeing any log output.

After debugging it, it looks like `UpdateLogKeys()` doesn't update the `LogKeys` map, and so I ended up adding this:

```
...
base.UpdateLogKeys(logKeys, true)
base.EnableLogKey(base.KeyQuery.String())  // <-- added this
```

And then I was seeing the expected log output:

Side note / feature request.  I wish there was a cleaner way to refer to the logging string constants than either of these approaches:

```
base.EnableLogKey("Query")  
base.EnableLogKey(base.KeyQuery.String())  
```

I guess the ideal would be:

```
base.EnableLogKey(base.KeyQuery)  
```

**Comment by tleyden** [comment]
OK thanks!

**Comment by tleyden** [comment]
Related question, any idea why I'm not seeing output with:

```
Debugf(KeyQuery, "Executing N1QL query: %v", UD(n1qlQuery))
```

and enabled via:

```
base.SetLogLevel(int(base.LevelDebug))
```

**Comment by bbrks** [comment]
Log level is set to info by default. Try ConsoleLogLevel().Set(LevelDebug)
