### ISSUE TITLE
[Perf, GSI] Sync Gateway is leaking connections to Couchbase query service

### ISSUE THREAD

**Issue by agyryk** [couchbase/sync_gateway#3534]
**Setup:**
Sync Gateway 2.1.0-38, GSI
Sync Gateway cache is disabled

**Test:**
_getChanges api call but it doesn't really matter what tests is it. As long as there are requests to SG which trigger N1QL queries to Couchbase.

**Behavior:**
The connections to CB port 8093 opened by SG aren't being closed and remain in TIME_WAIT state until closed by 60 sec timeout. 
Which is OK for low loads but once load to SG goes up the amount of open connections reaches system limit and SG performance drops (and SG CPU goes 100%). Until connection are timed out.

If SG uses gocb for handling query calls then we are hitting known issue in sdk: https://issues.couchbase.com/browse/GOCBC-159
The problem is that  bug is old and considered low priority. But now its somewhat critical  for Sync Gateway.

![screen shot 2018-05-02 at 4 00 56 pm](https://user-images.githubusercontent.com/20347420/39596726-22ee39a0-4ec8-11e8-8a0d-b459e0fa76c2.png)

**Comment by tleyden** [comment]
Fix: Gocb will expose a larger pool for hosts, set to 100

**Comment by adamcfraser** [comment]
@tleyden gocb enhancement is in: http://review.couchbase.org/#/c/93782/

**Comment by tleyden** [comment]
Thanks!
