### ISSUE TITLE
Error processing DCP stream

### ISSUE THREAD

**Issue by ont** [couchbase/sync_gateway#3541]
### Sync Gateway version
`Couchbase Sync Gateway/1.5.1(4;cb9522c)`

### Operating system
`Ubuntu 16.04.3 LTS`, official docker image `couchbase/sync-gateway:1.5.1-community`

### Log output
There is output of `grep -i error sync-gateway.log`:
https://gist.github.com/ont/c419bd234983d12c53d20c6e74f92dc3

### Expected behavior
No errors after couchbase node restart.

### Actual behavior
Broken synchronization between mobile clients and many errors `Error processing DCP stream` in log files.

### More info
1.  We have two couchbase nodes in cluster
2.  We have two SG (sync gateway) instances connected to cluster
3.  One of couchbase server nodes suddenly rebooted. It was able to self-recover and it become available again.
4.  After node reboot we can see that SG tries to reconnect to couchbase but without success.
5.  We see equal amount of errors from both SG instances.
6.  After manual reboot of SG all works again.

### Related issue
https://github.com/couchbase/sync_gateway/issues/3037  — we can see similar problem

**Comment by adamcfraser** [comment]
@ont To help us repro this:
- Does your Sync Gateway config specify both Couchbase Server nodes in it's 'server' property, or just one of the two nodes?  
- If just one, is it the Couchbase node that rebooted?

**Comment by ont** [comment]
> Does your Sync Gateway config specify both Couchbase Server nodes in it's 'server' property, or just one of the two nodes?

We use value `http://couchbase-server-master-5-0.service.consul:8091` for `server` in both SG configs. It is consul's special domain name. In our configuration it always resolves to `10.0.0.16`. Second node resolves to `10.0.0.17` but we doesn't specify it in our configs. Both SG connects to single couchbase node.

> If just one, is it the Couchbase node that rebooted?

No. Node that rebooted was `10.0.0.17`

**Comment by adamcfraser** [comment]
We've got a functional test that does the following (test_server_goes_down_sanity):
    1. Start with a two node couchbase server cluster
    2. Starting adding docs
    3. Kill one of the server nodes and signal completion
    4. Stop adding docs
    5. Verify that that the expected docs are present and in the changes feed.
    6. Start server again and add to cluster

This test is passing against 1.5.1. This test does specify both nodes in SG's 'server' property.

Aside from the config difference, the main difference between this test and @ont's scenario would be the timing of the failed server node coming back online.  I'll see if I can get this variation added to the functional test suite to see if we can repro.

**Comment by adamcfraser** [comment]
Closing based on age, and there have also been several DCP-related enhancements since 1.5.1.
