### ISSUE TITLE
Store Couchbase Server pool UUID per-database in sgcollect_info

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3551]
Fetching the Couchbase Server pool/cluster UUID per-database as part of sgcollect_info will allow support tooling to automatically link collections of couchbase server and sync gateway.

The pool UUID can be retrieved via the REST API at `GET /pools` under the key `uuid`. This endpoint requires authentication.

**Comment by bbrks** [comment]
@adamcfraser I spoke to support about this yesterday, and they'd prefer it to be in ASAP (and possibly backported if we do any additional releases), even if the specific way in which we do this will change with manageability.

This seems to be the only blocker on the SG side to stop support from enhancing tooling to automate collections and analysis for Sync Gateway.

As this UUID is per-db in Sync Gateway, we'd need to fetch it on initial connection, and stamp it in a field on the responses of `:4985/_config` and/or `:4985/{db}/_config`.

**Comment by tleyden** [comment]
https://github.com/couchbase/gocbmgr might be useful here.

**Comment by JFlath** [comment]
@adamcfraser Just to touch on the point:

> There will be less need for this once the manageability enhancements are in place 

I'm not sure this will be the case - the idea here is that from the output of `sgcollect_info` in isolation, we'll be able to ascertain what cluster it is connected to. I'm not sure we'd be able to do that just through the manageability enhancements, particularly for use cases where it is run manually on each node...
