### ISSUE TITLE
uploadhost is ignored when upload parameter is not given to _sgcollect_info end point 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3561]
### Sync Gateway version
2.1.0-82  

### Operating system
Centos

### Config file
``` "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "logging":{
        "redaction_level": "partial"
    },
    "databases":{
        "db":{
            "import_docs": "continuous",
            "enable_shared_bucket_access": true,


            "num_index_replicas": 0,
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "password": "password"
        }
    }
}

```

### Log output
2018-05-10T16:19:58.448Z [INF] HTTP:  #290: POST <ud>/_sgcollect_info</ud> (as ADMIN)
2018-05-10T16:19:58.462Z [INF] Admin: sgcollect_info started with args: <ud>[--customer sri-15 --log-redaction-level partial --log-redaction-salt salting the customized --sync-gateway-executable /opt/couchbase-sync-gateway/bin/sync_gateway sgcollectinfo-2018-05-10t161958-sg@10.0.2.15.zip]</ud>

### Steps to reproduce
1.  Execute curl command : curl -X POST http://192.168.33.11:4985/_sgcollect_info -H 'Content-Type: application/json' -d '{"redact_level": "partial", "output_directory":"/home", "redact_salt": "salting the customized", "upload_host": "https://s3.console.aws.amazon.com/s3/buckets/cbmobile-testkit", "customer": "sri-15"}'
2.  Monitor sg logs.

### Expected behavior
Though upload parameter is not given in curl command, upload_host should enable upload. This is the behavior for server

### Actual behavior
sg logs does not complain that upload parameter is missing. It just says that it failed, but do not show any reason

**Comment by bbrks** [comment]
After some discussion with @JFlath, I have changed the behavior in #3564 so that `upload` must be set to `true` to use `upload_host`.

```
14:01 $ curl -X POST http://localhost:4985/_sgcollect_info -d '{"upload_host":"https://s3.console.aws.amazon.com/s3/buckets/cb-engineering","customer":"bbrks"}'
{"error":"Bad Request","reason":"Invalid options used for sgcollect_info: upload must be set if upload_host is specified"}
```

**Comment by JFlath** [comment]
Can I be super nitpicky and ask for the same language as `couchbase-cli`?

```
            if opts.upload_host:
                _warning("--upload-host has no effect with specifying --upload")
            if opts.upload_customer:
                _warning("--upload-customer has no effect with specifying --upload")
            if opts.upload_ticket:
                _warning("--upload_ticket has no effect with specifying --upload")
            if opts.upload_proxy:
                _warning("--upload_proxy has no effect with specifying --upload")
```

It's really minor, but I think "has no effect" makes it seem a bit less of an arbitrary requirement...

**Comment by bbrks** [comment]
"upload_host has no effect without specifying upload" implies the process continues without uploading though?

**Comment by JFlath** [comment]
Hmm, true. That's actually the behaviour of couchbase-cli, but I don't think that makes sense for this case. Ignore me ;)
