### ISSUE TITLE
Handle path variable redaction collision

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3567]
When redacting multiple path variables with matching values and different redaction levels, it's possible to end up with incorrect redaction levels applied, because of the way mux provides the list of path variables as a map.

e.g. redacting :4985/foo/foo should redact the db as MD and the docid as UD, but ordering isn't guaranteed by the map iteration.

**Comment by bbrks** [comment]
This issue is not applicable until metadata redaction is supported and enabled.

**Comment by adamcfraser** [comment]
Closing - can be revisited when MD redaction is added.
