### ISSUE TITLE
Integration test to reproduce: continous replication loops

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#357]
https://github.com/couchbase/sync_gateway/issues/314 happens with a Couchbase Server 2.2.0 backend.  

We should create an integration test that simulates the client HTTP requests and reproduces the issue.

NOTE: it might depend on the snapshot of the data in the production TodoLite database.

**Comment by lichenyang2** [comment]
Assign to Andrei who is currently working on a test plan for sync_gateway and building a structure for sync_gateway functional testing.

**Comment by zgramana** [comment]
@andreibaranouski can you please update this week.

**Comment by zgramana** [comment]
@andreibaranouski, nevermind. Moving this to backlog for now.
