### ISSUE TITLE
_sg_collect rest end point : Time stamp for zip file is incorrect

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3575]
### Sync Gateway version
2.1.0-82

### Operating system
CentOS

### Config file
```{ "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "logging":{
        "redaction_level": "partial"
    },
    "databases":{
        "db":{
            "import_docs": "continuous",
            "enable_shared_bucket_access": true,


            "num_index_replicas": 0,
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "password": "password"
        }
    }
}
```

### Log output
-rw-r--r--. 1 sync_gateway sync_gateway 7560961 May 11 09:25 sgcollectinfo-2018-05-11t092400-sg@10.0.2.15-redacted.zip
-rw-r--r--. 1 sync_gateway sync_gateway 7558914 May 11 09:25 sgcollectinfo-2018-05-11t092400-sg@10.0.2.15.zip

### Steps to reproduce
1.  Use the sync_gateway that was installed some time back
2.  Restart sync_gateway
3.  Hit the curl command : 
curl -v -X POST http://192.168.33.11:4985/_sgcollect_info -H 'Content-Type: application/json' -d '{"redact_level": "partial", "upload": false}'

### Expected behavior
It creates zip file under /home/sync_gateway with time stamp of sync_gateway installed

### Actual behavior
It should show current time stamp

**Comment by bbrks** [comment]
@sridevi-15 Can you please provide examples of what the filename should've been?

I'm struggling to follow your example (it looks like the files get created with the correct timestamp and date?)

Note that filename format is as follows, where the timestamp is the current time when sgcollect_info is run, in UTC.

```
sgcollectinfo-YYYY-MM-DDtHHMMSS-sg@255.255.255.255.zip
```
