### ISSUE TITLE
Test loglevel clobbered by ResetTestLogging()

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3579]
In a test, I've tried to set the loglevel to tracing via:

```
base.ConsoleLogLevel().Set(base.LevelTrace)
base.EnableTestLogKey("Query")
```

so that I would see this log statement emitted:

```
Tracef(KeyQuery, "Executing N1QL query: %v", UD(n1qlQuery))
```

However it's not being emitted due to this call:

```
// ResetTestLogging return logging back to a standard state (Info level and HTTP log key)
func ResetTestLogging() {
	ConsoleLogLevel().Set(LevelInfo)
	ConsoleLogKey().Set(KeyHTTP)
}
```

which is happening very early on in the test execution, due to this code in `utilities_testing.go`:

```
func (rt *RestTester) Bucket() base.Bucket {

	if rt.RestTesterBucket == nil {

		// Initialize the bucket.  For couchbase-backed tests, triggers with creation/flushing of the bucket
		if !rt.NoFlush {
			tempBucket := base.GetTestBucketOrPanic() // side effect of creating/flushing bucket
			tempBucket.Close()
		}
                ...
         }
}
```

Since it opens and closes the bucket for the side effect of flushing the bucket, it triggers the log level reset.

**Comment by tleyden** [comment]
Also, somewhat related, a call to:

```
EnableTestLogKey("Something+")
```

will end up resetting the log level to `LevelDebug`, and so this code wouldn't work as expected:

```
base.ConsoleLogLevel().Set(base.LevelTrace)
base.EnableTestLogKey("Query+")
```

Since the call to `base.EnableTestLogKey("Query+")` would end up undoing the previous call enable trace-level logging.

**Comment by tleyden** [comment]
Another somewhat related question around test logging.  Should 

```
func TestBulkDocsChangeToRoleAccess(t *testing.T) {

	var logKeys = map[string]bool{
		"Access":  true,
		"Access+": true,
	}

	base.UpdateLogKeys(logKeys, true)
```

Be changed to:

```
	base.EnableTestLogKey("Access+")
	base.EnableTestLogKey("Query")  
```

or are they basically equivalent?

**Comment by adamcfraser** [comment]
For the first issue - can you workaround by setting the log levels after the bucket gets initialized (w/ flush)?  I can't actually decide whether this is a problem with how we reset log levels, or how we do flush.

**Comment by bbrks** [comment]
I'm not really happy with how closing buckets/RestTesters have side effects on logging. Per-test setup/teardown is really the correct answer to this, but I'm not sure of how to achieve that currently.

The alternative I can think of would be a to use a callback that gets immediately deferred, but would require adding set up calls in each test?

@tleyden @adamcfraser what do you think of this approach for setting up test logging? SetUp could take in desired log level and log keys, and the teardown function can reset to a known-state.

```go
func SetUp() (tearDown func()) {
    fmt.Println("  setup")

    return func() {
        fmt.Println("  teardown")
    }
}

func TestSomething(t *testing.T) {
    defer SetUp()()

    fmt.Println("    test")
}

func TestSomethingElse(t *testing.T) {
    defer SetUp()()

    fmt.Println("    test")
}
```

```
16:28 $ go test -run='TestSomething' -v ./tmp
=== RUN   TestSomething
  setup
    test
  teardown
--- PASS: TestSomething (0.00s)
=== RUN   TestSomethingElse
  setup
    test
  teardown
--- PASS: TestSomethingElse (0.00s)
PASS
ok  	github.com/bbrks/tmp	0.120s
```

**Comment by adamcfraser** [comment]
@tleyden One approach might be to have a more generic test teardown function that we call in every test - like 
`defer TestTeardown([RestTester], [bucket])`
where we do teardown of RestTester and bucket if they are provided, and also do things like resetting logging.  That would at least avoid every test needing 5-6 lines of common teardown code at the top.

**Comment by tleyden** [comment]
@bbrks I guess I'm not following how different tests would be able to fully customize the setup/teardown.  Any chance you'd be willing to sketch out a more complete example using a couple of actual tests?

For example, some tests need to setup/teardown "RestTesters", while others don't .

**Comment by bbrks** [comment]
@tleyden Sorry, maybe I didn't make it clear in my description, I'd talked to Adam about this offline. That setUp example would be specific for logging that has a pre-defined teardown.

So maybe we could create a set of test setup utils that could be composed, that all return pre-baked teardown functions?

```go
func setUpTestLogging(logLevel base.LogLevel, logKeys base.LogKey) func() {}
func setUpTestBucket(config BucketConfig) (Bucket, func()) {}
func setUpRestTester(config RestTesterConfig) (RestTester, func()) {}
```

and then each test can customise what it wants to use:

```go
func TestSomething(t *testing.T) {
    // set debug level with 3 log keys, and immediately defer the teardown
    defer setUpTestLogging(base.LevelDebug, base.KeyCache|base.KeyDCP|base.KeySync)()

    // set up test bucket with given config, and defer the teardown
    bucket, bucketTeardown := setUpTestBucket(BucketConfig{})
    defer bucketTeardown()

    bucket.DoSomething()
}
```

Pros: Fairly consise, pre-defined teardown means consistent state for all tests, flexibility in tests
Cons: Forgetting to defer the teardown function

**Comment by tleyden** [comment]
Ok, thanks, that makes sense.  

I like that a lot better than the current situation.

**Comment by bbrks** [comment]
I've opened PR #3624 for to add and use a `SetUpTestLogging` function which returns a teardown function that can be deferred.
