### ISSUE TITLE
sync-gateway does not show any error on logs when used wrong name/value pairs for logging

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3584]
### Sync Gateway version
2.1.0-95

### Operating system
Centos

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "logging":{
        "redaction_level": "partial",
        "default": {
          "logKeys": ["Admin"],
          "logLevel": "debug"
        },
        "debug": {
          "enabled": true
        }
    },
    "cluster_config": {
        "server":"http://192.168.33.10:8091",
        "data_dir":".",
        "bucket":"data-bucket",
        "username":"data-bucket",
        "password": "password"
    },
    "databases":{
        "db":{
            "enable_shared_bucket_access": true,


            "num_index_replicas": 0,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "channel_index":{
                "num_shards":16,
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket",
                "username": "index-bucket",
                "password": "password",
                "writer":false
            }
        }
    }
}


```

### Steps to reproduce
1.  Use above sg config
2.  restart sg

### Expected behavior
It should throw an error or warning message that "default" is not recognized. If possible provide the replaced field name with new filed name . 

### Actual behavior
sg start as usual with default logging values as log_key as * and log_level as info which are default, but do not have idea why it did not set log key as Admin and log_level as debug

Also, I replaced "default" with "console" , but I tried old logKeys and logLevel field names which did not throw an error, it just set up with default values.

If does not want to throw an error, atleast giving warning message is helpful as it is hard to know why values in sg config is not set

**Comment by bbrks** [comment]
We don't do anything special for incorrect keys in the SG config. This is #826, currently blocked by #3446

Some keys that used to exist are marked as deprecated, and emit a warning when used, and suggest what to change it to.

Additionally, the config you provided has multiple log key definitions: Namely "log" and "logging.default.logKeys". I'm not sure which one takes precedent, but this isn't really something we support. You should only use one of them, with all of the values you require.
