### ISSUE TITLE
sgcollect_info : customer and ticket number is allowed without enabling upload parameter

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3587]
### Sync Gateway version
2.1.0-95

### Operating system
Centos 7

### Steps to reproduce
1.  Run curl command without enabling upload and pass customer or ticket number
curl -v -X POST http://192.168.33.11:4985/_sgcollect_info -H 'Content-Type: application/json' -d '{"redact_level": "partial", "ticket": "123"}'
2.  It starts sg collect successfully

### Expected behavior
It should send response like upload host that upload is not enabled

### Actual behavior
It starts successfully 

cbcollect throws an error if customer or ticket number is provided without enabling upload

**Comment by bbrks** [comment]
Created #3591 to make validation rules stricter.
