### ISSUE TITLE
More authentication methods request

### ISSUE THREAD

**Issue by llwwbb** [couchbase/sync_gateway#3588]
I encountered a problem when using the rest api /{db}/_changes?feed=websocket.

In browser, the Authorization header cannot be set using the websocket api, especially in Safari, cannot use url like _ws://{username}:{password}@{host}:{port}_  (ok in Chrome)

The other way is cookie. In Chrome, I can set cookie "SyncGatewaySession={session}" using ajax, just set withCredentials=true, the request to /_changes will take the cookie. But also in Safari, according to https://webkit.org/blog/7675/intelligent-tracking-prevention/, cookies in 3rd-party context can't be used. 

Is there another way?

**Comment by tleyden** [comment]
Thanks for the report, but API compatibility w/ browsers is not really a priority.

Also, this might be better as a forum post on https://forums.couchbase.com/t/react-native-with-couchbase-via-the-rest-api/16866, since github is meant for issues.
