### ISSUE TITLE
Unable to connect node.js to sync gateway. 

### ISSUE THREAD

**Issue by seanmayes** [couchbase/sync_gateway#3600]
node.js script fails to connect with no output.  Note that this is my first time setting up a node.js backend server to connect with my couchbase server database (via the sync gateway).  I have followed some online tutorials and read up a bit.  Even though my js script appears to run without any errors and it is syntactically correct, it just stops with no output. 

Using "pm2 start my_node_js_file.js", attempts to restart the script about 15 times then just stops reporting "error".  But no further information is shown in any logs.  

Can anyone see from my .config and node.js script what is going wrong.  Greatly appreciated.  Thank you.  Two things to note... 1) Yes, my database is named "sync_gateway", I'll choose a better name later.  2) I was only able to find the sync-gateway-spec in yaml, so I converted it to .json via an online converter.

**Here is my js script that runs on node.js.**

const swagger = require('swagger-client');
const spec = require('./sync-gateway-spec.json');

const SYNC_GATEWAY_HOST = 'localhost:4984';
spec.host = SYNC_GATEWAY_HOST;

let query = {
  db: 'sync_gateway',
  filter: 'sync_gateway/bychannel',
  channels: ['new_msg_notification', 'userchannels'],
  active_only: true,
  include_docs: true,
  feed: 'longpoll',
  timeout: 0
};

// Setup to use swagger syncronously
let client = new swagger({
  spec: spec,
  success: function() {
    monitor(client);
  },
  function(error) {
    console.log('client error: ', error.statusText);
    process.exit(1);
  }
});

function monitor(client) 
{
  console.log("MADE IT TO MONITOR");
  client.database.get_db_changes(query, message);
}

function message(response) 
{
  console.log("MADE IT TO MESSAGE");
  console.log(response.data);
  query.since = response.obj.last_seq;
  monitor(client);
}

**And here is my  sync_gateway_config.json**

{
   "interface":":4984",
   "adminInterface":":4985",
   "log":["*"],
   "CORS": {
    "origin":["*"],
    "loginOrigin":["*"],
    "headers":["Content-Type"],
    "maxAge": 1728000
  },
   "databases":{
      "sync_gateway":{
         "users": {
				"admin": {"password": "password2", "admin_roles": ["admin"]}
			},
			"roles": {
				"user": {},
				"admin": {}
			  },
         "server":"http://localhost:8091",
         "enable_shared_bucket_access": true,
         "enable_extended_attributes": true,
         "bucket":"sync_gateway",
         "username":"my_username",
         "password":"my_password!",

**Update**
Changing my "spec" to "url" and providing a URL produces the following error output

Code Change in the js script:
url: 'http://developer.couchbase.com/mobile/swagger/sync-gateway-public/spec.json',
  //spec: spec,

Produces this error.
/home/seanmayes/.pm2/logs/apns-out-14.log last 15 lines:
/home/seanmayes/.pm2/logs/apns-error-14.log last 15 lines:
14|apns    |     at tryCatch (/home/seanmayes/node_modules/regenerator-runtime/runtime.js:62:40)
14|apns    |     at GeneratorFunctionPrototype.invoke [as _invoke] (/home/seanmayes/node_modules/regenerator-runtime/runtime.js:296:22)
14|apns    |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/seanmayes/node_modules/regenerator-runtime/runtime.js:114:21)
14|apns    |     at step (/home/seanmayes/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
14|apns    |     at /home/seanmayes/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
14|apns    |     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
14|apns    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
14|apns    | Error: Not Found
14|apns    |     at /home/seanmayes/node_modules/swagger-client/dist/index.js:1:8465
14|apns    |     at tryCatch (/home/seanmayes/node_modules/regenerator-runtime/runtime.js:62:40)
14|apns    |     at GeneratorFunctionPrototype.invoke [as _invoke] (/home/seanmayes/node_modules/regenerator-runtime/runtime.js:296:22)
14|apns    |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/seanmayes/node_modules/regenerator-runtime/runtime.js:114:21)
14|apns    |     at step (/home/seanmayes/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
14|apns    |     at /home/seanmayes/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
14|apns    |     at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by adamcfraser** [comment]
This type of question is better directed at the forums - the Sync Gateway issue tracker is reserved for bug reports and enhancement requests.

**Comment by tleyden** [comment]
@seanmayes here's a link to the forums: https://forums.couchbase.com
