### ISSUE TITLE
x509 certification handshake between SG and CBS failed

### ISSUE THREAD

**Issue by hrajput89** [couchbase/sync_gateway#3601]
### Sync Gateway version
2.1.0-95   

### Operating system
Centos7

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    
    
    "databases":{
        "db":{
            "certpath": "/home/sync_gateway/tmp/chain.pem",
            "keypath": "/home/sync_gateway/tmp/pkey.key",
            "cacertpath": "/home/sync_gateway/tmp/ca.pem",
            "use_views": true,
            "num_index_replicas": 0,
            "num_index_replicas_housekeeping": 0,
            "server":"http://172.16.1.166:8091",
            "bucket":"default",
            "cache": {
                "channel_cache_max_length": 15000,
                "channel_cache_min_length": 15000,
                "channel_cache_expiry": 90
            }
        }
    }
}
```

### Expected behavior
[root@localhost tmp]# tail /home/sync_gateway/logs/sync_gateway_error.log 
2018-05-24T10:56:53.532Z [INF] GoCBCustomSGTranscoder Opening Couchbase database default on <http://172.16.1.166:8091> as user "default"
2018-05-24T10:56:53.535Z [INF] Error opening bucket: no access
2018-05-24T10:56:54.816Z [INF] GoCBCustomSGTranscoder Opening Couchbase database default on <http://172.16.1.166:8091> as user "default"
2018-05-24T10:56:54.819Z [INF] Error opening bucket: no access
2018-05-24T10:56:57.379Z [INF] GoCBCustomSGTranscoder Opening Couchbase database default on <http://172.16.1.166:8091> as user "default"
2018-05-24T10:56:57.383Z [INF] Error opening bucket: no access
2018-05-24T10:57:02.503Z [INF] GoCBCustomSGTranscoder Opening Couchbase database default on <http://172.16.1.166:8091> as user "default"
2018-05-24T10:57:02.506Z [INF] Error opening bucket: no access
2018-05-24T10:57:12.748Z [INF] GoCBCustomSGTranscoder Opening Couchbase database default on <http://172.16.1.166:8091> as user "default"
2018-05-24T10:57:12.752Z [INF] Error opening bucket: no access

### Actual behavior
Access should be available

### Steps to reproduce
1.  Generate the client certificates for CBS and enabled it following the procedure mentioned
2.  Start the SG with the attached config.
3.  Check the sync_gateway_error.log

### CBS Memcached logs - 

- Snippet from log
`2018-05-24T10:53:05.159957Z INFO 53: HELO [{"a":"gocbcore/v7.1.0 gocb/v1.3.5","i":"d312c9976aaa6102/1da16ce2bc0e83c4"}] XATTR, XERROR, Select bucket, Tracing` [ 172.16.1.154:33036 - 172.16.1.166:11210 (not authenticated) ]
[memcached.log.000000.txt](https://github.com/couchbase/sync_gateway/files/2035041/memcached.log.000000.txt)

**Comment by hrajput89** [comment]
Attaching sgcollectinfo logs
[sgcollect_info.zip](https://github.com/couchbase/sync_gateway/files/2035046/sgcollect_info.zip)

**Comment by ritamcouchbase** [comment]
1. The user associated with the account is a Admin in the system, so should have rights to entire bucket.
2. Have not checked it, but should be there in memcached.log if auth has failed.

**Comment by ritamcouchbase** [comment]
SG is sending the correct user:
2018-05-24T10:57:12.748Z [INF] GoCBCustomSGTranscoder Opening Couchbase database default on http://172.16.1.166:8091 as user "default"

On memcached it is the select bucket that is failing:
2018-05-24T10:53:05.159957Z INFO 53: HELO [{"a":"gocbcore/v7.1.0 gocb/v1.3.5","i":"d312c9976aaa6102/1da16ce2bc0e83c4"}] XATTR, XERROR, Select bucket, Tracing [ 172.16.1.154:33036 - 172.16.1.166:11210 (not authenticated) ]

Hemant can you also upload the certs as well, i believer the ssl handshake has gone through and now it a matter of get a session from memached.

**Comment by adamcfraser** [comment]
Is the bucket specified in the Sync Gateway config ("default") correct?

I see what looks successful authentication as user 'data-bucket' in the logs, but then failure to connect to the 'default' bucket.

**Comment by adamcfraser** [comment]
Oh - it looks like the problem is that you're not using HTTPS for communication - you've got the server endpoint specified as http://172.16.1.166:8091, when it should be couchbases://172.16.1.166.  
 x.509 auth requires TLS.

**Comment by ritamcouchbase** [comment]
Yes Adam.

**Comment by ritamcouchbase** [comment]
Hemant - try with python code with latest sdk

from couchbase.cluster import Cluster
from couchbase.cluster import PasswordAuthenticator
cluster = Cluster('couchbases://172.23.99.49/?certpath=/Users/jaekwon.park/work/src/github.com/couchbaselabs/sdk-qe/functional-tests/java-functional/cert/chain.pem&keypath=/Users/jaekwon.park/work/src/github.com/couchbaselabs/sdk-qe/functional-tests/java-functional/cert/pkey.key');
cb = cluster.open_bucket('default')
cb.upsert('king_arthur_python', {'name': 'Arthur', 'email': 'kingarthur@couchbase.com', 'interests': ['Holy Grail', 'African Swallows']})

**Comment by adamcfraser** [comment]
@ritamcouchbase @hrajput89 In case it wasn't clear from my previous update - the Sync Gateway config provided above has an error - it needs to be using SSL when authenticating via x.509.  The server should be specified in the config as:
```
"server":"couchbases://172.16.1.166",
```

Let me know if that doesn't fix the problem.

**Comment by ritamcouchbase** [comment]
Thanks Adam, it is bad on my part to overlook at from the document that you had provided.

**Comment by hrajput89** [comment]
I tried with the correct server url, I'm able to run python sdk test mentioned above for the certs but SG is not able to start with x509 cert. I've installed SG and CBS on the same node. I'm attaching both CBS and SG logs.

Python test result - 
<img width="1440" alt="screenshot 2018-05-25 13 10 20" src="https://user-images.githubusercontent.com/18100038/40532428-0ae27626-601d-11e8-8b32-37a9394bce55.png">

#### SG Logs
sgcollect was not working due to below error, so I just tar-ed "/home/sync-gateway" directory
**[root@localhost tools]# ./sgcollect_info /tmp/sgcollect_info.zip
./sgcollect_info: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIIe8o0p/libz.so.1)**
[sglogs.zip](https://github.com/couchbase/sync_gateway/files/2038417/sglogs.zip)

#### CBS logs
[cbsmemcached.log](https://github.com/couchbase/sync_gateway/files/2038422/cbsmemcached.log)

**Comment by adamcfraser** [comment]
There seem to be a few differences between the python test and what's in the SG config:
- Python test isn't specifying the root CA cert (cacertpath).  Assuming the python SDK works the same as the go SDK, this means that the client is skipping verification of the server's TLS cert.  
- The Python test is targeting couchbases://10.142.180.101, while SG is targeting couchbases://172.23.121.214.  Even if those resolve to the same machine, I was under the impression there's specific address information baked into the cert. 
- The python script doesn't look like it's being run from the SG machine (different paths to the certs)

**Comment by ritamcouchbase** [comment]
Python test isn't specifying the root CA cert (cacertpath). Assuming the python SDK works the same as the go SDK, this means that the client is skipping verification of the server's TLS cert.
- Python SDK uses the chain cert, which contains the root + intermediate + client cert. 

The Python test is targeting couchbases://10.142.180.101, while SG is targeting couchbases://172.23.121.214. Even if those resolve to the same machine, I was under the impression there's specific address information baked into the cert.
-  confirming that the test was still 172.23.121.214 to connect to cluster. 

The script is here- 
from couchbase.cluster import Cluster
from couchbase.cluster import PasswordAuthenticator
cluster = Cluster('couchbases://172.23.121.214/?certpath=/tmp/test/chain.pem&keypath=/tmp/test/pkey.key');
cb = cluster.open_bucket('default')
cb.upsert('king_arthur_python1', {'name': 'Arthur', 'email': 'kingarthur@couchbase.com', 'interests': ['Holy Grail', 'African Swallows']})

**Comment by adamcfraser** [comment]
@ritamcouchbase The chain cert is used as the client certificate - it's distinct from the root CA cert, which is used as part of the TLS handshake.

**Comment by hrajput89** [comment]
Adam,

we are using chain certificates, which is concat of node, intermediate and root certificates.

Snippet from gen_keystore.sh (Line 51-55)
```
# Generate certificate chain file
cat ${NODE}.pem ${INTERMEDIATE}.pem ${ROOT_CA}.pem > ${CHAIN}.pem

INBOX=/opt/couchbase/var/lib/couchbase/inbox/
CHAIN=chain.pem
```

**Comment by hrajput89** [comment]
login with x509 certification. Hence closing the ticket.
