### ISSUE TITLE
Build sgcollect_info on centos6

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3605]
Originally reported in https://github.com/couchbase/sync_gateway/issues/3601#issuecomment-391970324, related to https://github.com/couchbase/sync_gateway/issues/2598#issuecomment-306949259

The problem is that while sgcollect_info is compatible w/ python 2.6, it's being built as an executable with a *newer* glibc library than is available on centos6, and so trying to run it on centos6 results in an error:

```
./sgcollect_info: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIIe8o0p/libz.so.1)
```

The most straightforward fix is to build it on centos6 so it picks up the correct version of the glibc library.  This should work according to:

From https://github.com/pyinstaller/pyinstaller/wiki/FAQ#gnulinux

> Under Linux, I get runtime dynamic linker errors, related to libc. What should I do?
The executable that PyInstaller builds is not fully static, in that it still depends on the system libc. Under Linux, the ABI of GLIBC is backward compatible, but not forward compatible. So if you link against a newer GLIBC, you can't run the resulting executable on an older system. The supplied binary bootloader should work with older GLIBC. However, the libpython.so and other dynamic libraries still depends on the newer GLIBC. The solution is to compile the Python interpreter with its modules (and also probably bootloader) on the oldest system you have around, so that it gets linked with the oldest version of GLIBC.

**Comment by adamcfraser** [comment]
Possible approach is to have build generate platform version specific binaries for Sync Gateway, similar to what's done for server.

**Comment by adamcfraser** [comment]
centos6-specific build approach has been taken.
