### ISSUE TITLE
Docs/revisions are lost during upgrade

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#3608]
### Upgrade scenario
SG 2.0.0-832(xattrs) -> SG 2.1.0-95 (xattrs/views); CBS 5.1.1-5721 -> CBS 5.5.0-2764; CBL 1.4.0-3 macosx, num-docs 10000

### Operating system
CentOS7

### Config file
Post upgrade
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "logging": {"debug": {"enabled": true}},
    "databases":{
        "db":{
            "import_docs": "continuous",
            "enable_shared_bucket_access": true,
            
            "use_views": true,
            
            "server":"http://192.168.33.20:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password"
        }
    }
}
```

### Log output
Test log:
```
.............
Verifying that sync gateway returns a 404 deleted message for the deleted docs
doc_id: ls_db_upgrade_doc_0_0 - status:404, reason: deleted
doc_id: ls_db_upgrade_doc_0_1 - status:404, reason: deleted
doc_id: ls_db_upgrade_doc_0_2 - status:404, reason: deleted
doc_id: ls_db_upgrade_doc_0_3 - status:404, reason: missing
............
>           assert reason == "deleted"
E           assert 'missing' == 'deleted'
E             - missing
E             + deleted
```
CBL logs:
```
22:35:41.568‖ Router: PUT http://localhost:59840/ls_db/ls_db_upgrade_doc_0_3 + 1027-byte body
        Host: localhost:59840
        Content-Type: application/json
        Accept-Encoding: identity
        Content-Length: 1027
22:35:41.570‖ Router: Response -- status=201, body=83 bytes
        Server: CouchbaseLite 1.4.0 (build 3)
        Location: http://localhost:59840/ls_db/ls_db_upgrade_doc_0_3
        Content-Type: application/json
        Etag: "1-7aeb18ad77bbdf05514ee008e15e812b"
22:35:41.572‖ Sync: CBLRestPusher[http://192.168.33.25:4984/db]: Server is Couchbase Sync Gateway/2.0.0
22:35:41.572‖ RemoteRequest: CBLRemoteJSONRequest[POST http://192.168.33.25:4984/db/_revs_diff]: Got response, status 200
22:35:41.573‖ RemoteRequest: CBLRemoteSession done with CBLRemoteJSONRequest[POST http://192.168.33.25:4984/db/_revs_diff]
22:35:41.573‖ RemoteRequest: CBLRemoteJSONRequest[POST http://192.168.33.25:4984/db/_revs_diff]: Finished loading
22:35:41.574‖ Sync: CBLRestPusher[http://192.168.33.25:4984/db]: Sending 1 revisions
```
SG 1 - 192.168.33.22:
```
2018-05-26T02:11:26.799Z Cache: Received #5 after -88ms ("ls_db_upgrade_doc_0_3" / "1-7aeb18ad77bbdf05514ee008e15e812b")
2018-05-26T02:13:00.446Z CRUD+: Invoking sync on doc "ls_db_upgrade_doc_0_3" rev 2-38c2fb3bc0c8e5451fce3bfc10c8e612
2018-05-26T02:13:00.446Z CRUD+: Saving old revision "ls_db_upgrade_doc_0_3" / "1-7aeb18ad77bbdf05514ee008e15e812b" (909 bytes)
2018-05-26T02:13:00.454Z CRUD+: Backed up obsolete rev "ls_db_upgrade_doc_0_3"/"1-7aeb18ad77bbdf05514ee008e15e812b"
2018-05-26T02:13:00.454Z CRUD: 	Doc "ls_db_upgrade_doc_0_3" in channels "{}"
2018-05-26T02:13:00.456Z Cache: Received #10005 after   1ms ("ls_db_upgrade_doc_0_3" / "2-38c2fb3bc0c8e5451fce3bfc10c8e612")
2018-05-26T02:13:00.456Z CRUD: Stored doc "ls_db_upgrade_doc_0_3" / "2-38c2fb3bc0c8e5451fce3bfc10c8e612"
```
SG 2 - 192.168.33.26:
```
2018-05-26T02:11:26.888Z CRUD+: Invoking sync on doc "ls_db_upgrade_doc_0_3" rev 1-7aeb18ad77bbdf05514ee008e15e812b
2018-05-26T02:11:26.888Z CRUD: 	Doc "ls_db_upgrade_doc_0_3" in channels "{sg_user_channel}"
2018-05-26T02:11:26.889Z CRUD: Stored doc "ls_db_upgrade_doc_0_3" / "1-7aeb18ad77bbdf05514ee008e15e812b"
2018-05-26T02:11:26.890Z Cache: Received #5 after   2ms ("ls_db_upgrade_doc_0_3" / "1-7aeb18ad77bbdf05514ee008e15e812b")
2018-05-26T02:13:00.547Z Cache: Received #10005 after  92ms ("ls_db_upgrade_doc_0_3" / "2-38c2fb3bc0c8e5451fce3bfc10c8e612")
2018-05-26T02:13:06.439Z CRUD+: PutExistingRev("ls_db_upgrade_doc_0_3"): No new revisions to add
2018-05-26T02:13:06.439Z CRUD+: Did not update document "ls_db_upgrade_doc_0_3" w/ xattr: CAS quit
```
raw doc post upgrade on SG:
```
» http 192.168.33.22:4985/db/_raw/ls_db_upgrade_doc_0_3 
HTTP/1.1 404 Not Found
Content-Length: 40
Content-Type: application/json
Date: Sat, 26 May 2018 04:20:09 GMT
Server: Couchbase Sync Gateway/2.1.0

{
    "error": "not_found",
    "reason": "missing"
}
```
doc on CBS post upgrade:
```
select meta().id from `data-bucket` where meta().id='ls_db_upgrade_doc_0_3'

{
  "results": []
}
```
### Expected behavior
All docs/revisions should be intact.

### Actual behavior
Some docs/revisions are lost post upgrade.

### Steps to reproduce
1.  Install/configure 2 CBS nodes, 2 SG nodes and 1 CBL 1.4.0-3 macosx.
2.  Start continuous push pull replication between CBL and SG.
3.  Add docs to CBL.
4. In the main thread upgrade SGs and CBS.
5. In a separate thread, delete some docs on CBL and update some docs on CBL.
6. After upgrade, verify the doc ids and their revisions.

### Full logs attached
CBL logs:
[LiteServMacOSX-test_upgrade-2018-05-25 22:35:38.387214.txt.zip](https://github.com/couchbase/sync_gateway/files/2041416/LiteServMacOSX-test_upgrade-2018-05-25.22.35.38.387214.txt.zip)
SG logs:
[test_upgrade-2018-05-25-23-52-54-sglogs.zip](https://github.com/couchbase/sync_gateway/files/2041417/test_upgrade-2018-05-25-23-52-54-sglogs.zip)
Packet capture for the entire test:
[nginx_dump.zip](https://github.com/couchbase/sync_gateway/files/2041420/nginx_dump.zip)

**Comment by adamcfraser** [comment]
The SG logs excerpts included above don't show any problems - it's the expected logging when the two revisions are created.  
 - SG2 excerpt shows rev 1 being created, and rev 1 and 2 both appearing over DCP
 - SG1 excerpt shows rev 2 being created, and rev 1 and 2 both appearing over DCP

The _bulk_get requests (from the packet capture) show 296 total docs (out of 1001) returning "reason":"missing" in the bulk_get request:
https://gist.github.com/adamcfraser/e37963ef3e1a745576b04b5b443ee67b

**Comment by adamcfraser** [comment]
The 'No new revisions to add'/'Did not update document' logging is normal logging when CBL sends a revision SG already knows about.  That logging is showing up for documents that are behaving normally (i.e. returning "reason":"deleted"), so it looks unrelated to this issue.

**Comment by adamcfraser** [comment]
Filed https://issues.couchbase.com/browse/MB-29861 to get some server help looking at the cbcollect logs, to see if there is anything going on from the server side.

**Comment by raghusarangapani** [comment]
Attaching sgcollectinfo for the 2 SG nodes from the scenario where only server was upgraded and SG was maintained at 2.1.0-95 with xattrs enabled throughout.

[sgcollect_192.168.33.26.zip](https://github.com/couchbase/sync_gateway/files/2052406/sgcollect_192.168.33.26.zip)
[sgcollect_192.168.33.22.zip](https://github.com/couchbase/sync_gateway/files/2052407/sgcollect_192.168.33.22.zip)

**Comment by adamcfraser** [comment]
Should be addressed by the fix for https://issues.couchbase.com/browse/MB-29861.
