### ISSUE TITLE
Remove CouchbaseBucket (go-couchbase) bucket implementation 

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3611]
All functionality should have been moved over to gocb/cbdatasource at this point, so we'd like to remove the CouchbaseBucket code to clean up the SG code base.

Include an audit of the sg-bucket interface and remove any interfaces that are specific to go-couchbase/CouchbaseBucket.

**Comment by tleyden** [comment]
After this is closed, revisit converting walrus to support DCP rather than TAP
