### ISSUE TITLE
Error decompressing frame / Invalid checksum when using Squid forward proxy

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3634]
## Steps to repro

- Run sg with this config: https://gist.github.com/tleyden/cb5645c228ef5ada9ae06da3c27181d8 (I used commit 1da97bc0046d0acd7740d9c5aa11678c56da26d3, latest on dev branch)
- Run squid proxy with this config: https://gist.github.com/tleyden/160f40d3791fff6bd2eb6ddee85e4950
- Change `acl device src 192.168.212.156` to your macbook ip address
- Run TestSquid ios project (not on github yet)
   - Update ViewController.swift to point to macbook ip address, and use this version of the file that modifies the code to send strings rather than attachments, to reduce memory usage: https://gist.github.com/tleyden/c39dd11ffabda7a459cc597121b2a22e
   - Add the couchbase lite ios swift framework from the website download
- Configure ios device to use macbook dev machine as outbound proxy
- Create docs / start replication

I'm seeing this error in the SG logs:

```
2018-06-05T17:15:29.474-07:00 [INF] WS: [4b0ff63e] Error decompressing frame RPY#72: Invalid checksum 24f5791; should be fcd8fa4d. Raw frame = <4841e38....>
2018-06-05T17:15:29.475-07:00 [INF] WS: [4b0ff63e] Error: parseLoop closing socket due to error: Invalid checksum 24f5791; should be fcd8fa4d
2018-06-05T17:15:29.475-07:00 [INF] WS: [4b0ff63e] BLIP/Websocket Handler exited: Invalid checksum 24f5791; should be fcd8fa4d
2018-06-05T17:15:29.475-07:00 [INF] HTTP: [4b0ff63e] #001:     --> BLIP+WebSocket connection error: Invalid checksum 24f5791; should be fcd8fa4d
2018-06-05T17:15:29.475-07:00 [INF] Changes: MultiChangesFeed done 
```

SG Logs: https://gist.github.com/tleyden/816ba94cd2362e95aaf59a68aec5980f#file-gistfile1-txt-L122-L125

## Setup

![squidproxyreprodiagram](https://user-images.githubusercontent.com/296876/41050895-7c8d2e56-6969-11e8-80c7-26bc5beea29a.png)

**Comment by tleyden** [comment]
Disabling BLIP compression on both litecore and SG didn't seem to workaround the issue.

**Comment by tleyden** [comment]
Setting a breakpoint in sync gateway at the line emitting the error:

![screen shot 2018-06-05 at 8 46 56 pm](https://user-images.githubusercontent.com/296876/41015988-a48ac3cc-6901-11e8-81d8-ab8e27d3e636.png)

Here is the packet that's causing the failure in wireshark:

![screen shot 2018-06-05 at 8 48 00 pm](https://user-images.githubusercontent.com/296876/41016017-d3ed93f6-6901-11e8-9135-9ded530249e6.png)

and the full packet bytes:

https://gist.github.com/tleyden/5fe30b4c420bd533e5cdd0b0f5c62adc

The packet is in response to a continuous subchanges message that happens much earlier in the conversation:

![screen shot 2018-06-05 at 8 50 25 pm](https://user-images.githubusercontent.com/296876/41016067-186c9a9a-6902-11e8-984d-0aba4cbdf899.png)


One thing I'm planning to try is to also capture on port 8080, and maybe try to see the same packet as it comes into squid from cblite and look for any differences.

**Comment by tleyden** [comment]
## Websocket / BLIP frame layout

```
  Websocket Frame                                                                                                                 
 ┌──────────────────────────────────────────────────────────────────────────────────┐  ▲                                          
 │                                                                                  │      WS Header size depends on payload size 
 │                         Variable length WS Frame Header                          │  │     and whether it's masked.  Typically  
 │                                                                                  │  ▼              2,6, or 8 bytes.            
 ├─┬─┬──────────────────────────────────────────────────────────────────────────────┤  ▲                                          
 │ │ │◀┐                         Embedded Blip Frame                                │                                             
 ├▲┴─┘ └── variable length BLIP                                                     │  │                                          
 │└─┐          Frame Flags,                                                         │                                             
 │  │        typically 1 byte                                                       │  │                                          
 │  │                                                                               │                                             
 │ variable length BLIP                                                             │  │             WS Payload                   
 │   Message Number,                                                                │       Variable length, where length         
 │ typically 1-2 bytes                                                              │  │    is defined in the WS header.          
 │                                                                                  │       In BLIP, WS payload length is         
 │                                                                                  │  │       capped at 16384 bytes.             
 │                                                     4 byte BLIP Frame            │                                             
 │                                                          Checksum    │           │  │                                          
 │                                                                      └┐          │                                             
 │                                                                   ┌───▼──────────┤  │                                          
 │                                                                   │              │                                             
 └───────────────────────────────────────────────────────────────────┴──────────────┘  ▼                                                                                                                                
```

**Comment by snej** [comment]
@tleyden, can you describe in detail what "Configure ios device to use macbook dev machine as outbound proxy" entailed? Exactly what type of proxy did you configure it as?

**Comment by tleyden** [comment]
Sure, here are some screenshots from my ios wifi settings:

![img_3025](https://user-images.githubusercontent.com/296876/41136962-9cd4ee68-6a8d-11e8-8736-99502a41b5f2.PNG)
![img_3026](https://user-images.githubusercontent.com/296876/41137031-f4741bd0-6a8d-11e8-9a0e-1f002bc408d0.PNG)


Initially I had it pointed to my macbook IP address that was on the same wifi network as my ios device, but was also able to configure it to reach a squid proxy running on EC2.  If you want to test against that, I've posted the connection details in the chat, and @borrrden has SSH access to the machine.

**Comment by tleyden** [comment]
The **Server** field should have the ip or hostname where the squid proxy is running.  I blacked out the one I was using, so it's cut off after the first few characters... but it's a valid hostname.

**Comment by adamcfraser** [comment]
Closing, as this has been determined to be a client issue.

**Comment by deeksha-microsoft** [comment]
How is determined that its a client issue? How did we find the issue?
