### ISSUE TITLE
Improvement - Use N1QL to see if user synced data

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/sync_gateway#3653]
Could sync gateway add data into CBL's checkpoint,via xattr, so we can connect the checkpoint(s) to user?

<img width="727" alt="screen shot 2018-06-10 at 11 05 49 pm" src="https://user-images.githubusercontent.com/16341130/41209601-da110a7e-6d02-11e8-92a0-fae02795df36.png">

**Comment by Fujio-Turner** [comment]
The N1QL would look like this.

<img width="551" alt="screen shot 2018-06-10 at 10 59 31 pm" src="https://user-images.githubusercontent.com/16341130/41209445-17061e34-6d02-11e8-9258-952c33f4df25.png">

**Comment by Fujio-Turner** [comment]
Duplicate of closed ticket: https://github.com/couchbase/sync_gateway/issues/3135

**Comment by adamcfraser** [comment]
As stated on #3135:
"I think this is better in an email to the mobile-interest mailing list and highlight PM input.

Github should be reserved for tasks that have clear-cut action items, whereas this will need some discussion / debate before it's on engineering's plate to implement."
