### ISSUE TITLE
sg collect rest API does not create zip files under /home/sync-gateway

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3655]
### Sync Gateway version
2.1.0-107

### Operating system
CentOS

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "logging": {"debug": {"enabled": true}, "redaction_level": "partial" },
    "databases":{
        "db":{
            "import_docs": "continuous",
            "enable_shared_bucket_access": true,


            "num_index_replicas": 0,
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "password": "password"
        }
    }
}

```

### Steps to reproduce
1.  Do a rest api call
2.  Verify zip file under /home/sync-gateway
  

### Expected behavior
It supposed to create zip file i.e redacted and non redacted zip file under /home/sync_gaetway

### Actual behavior
It creates zip file under /home/sync_gateway/logs directory

**Comment by adamcfraser** [comment]
@sridevi-15 Did you specify the output path when making the sg_collect REST API call?

If not, this sounds like the expected behaviour (see https://github.com/couchbase/sync_gateway/pull/3636).

**Comment by bbrks** [comment]
Yeah, this change was intentional. @sridevi-15 is there any channel to document or communicate these changes to QE?

**Comment by sridevi-15** [comment]
@adamcfraser , specifying output directory works fine , but if output directory is not specified, it should create in default location i.e under home/sync_gateawy. Looks like it is a change in 107 according to Ben and expected behavior

@bbrks , there is no specific channel, you can tag QE ppl and let us know about the change in Mobile QE chat room. That is best way. 
I will close this ticket then
