### ISSUE TITLE
Investigate performance degradation associated with info-level logging

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3657]
Recent performance testing has shown a relatively significant performance degradation under high write load when info-level logging is enabled (both for 2.0 and 2.1).

Based on the perf results, this issue isn't seen in a single node write test, but is seen in multi-node write tests.  This suggests the bottleneck may be due to DCP processing of writes, as opposed to the initial write.

Need to review root cause.  Potential areas for investigation:
- logging settings being used by perf tests (rotation settings, etc)
- excessively verbose info-level logging
- logging overhead for non-enabled keys/levels

Performance test is a simple write/changes loop:
 - write a document
 - issue a synchronous longpoll changes request (blocks until change arrives)

**Comment by bbrks** [comment]
Based on profiling on local machine, it suggested that extremely high volumes of writes to the underlying logging libraries was causing contention. Possible solutions were async logging, collation buffers and simply reducing the number of logs we make.

Based on discussions to weigh risk vs. reward, we decided to implement log collation for further testing in #3662 (build 2.5.0-20)

Initial developer testing results:

<img width="1029" alt="screen shot 2018-06-27 at 13 14 35" src="https://user-images.githubusercontent.com/1525809/41973154-12bc2e74-7a0c-11e8-814d-05d2965265ca.png">

**Comment by bbrks** [comment]
Results in showfast show that this issue has been resolved with log collation.

![screen shot 2018-07-02 at 12 11 42](https://user-images.githubusercontent.com/1525809/42160999-29f53d0e-7df1-11e8-9a0a-3ffc2257165c.png)
