### ISSUE TITLE
Significant digits to right of decimal point being stripped on save

### ISSUE THREAD

**Issue by pkramerzoll** [couchbase/sync_gateway#3658]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
1.5.1

### Operating system
CentOS

### Config file
```javascript
# When relevant, copy-paste your sync gateway config here.  Remove any sensitive information
as appropriate (including addresses, passwords, etc).
```

### Log output
Provide a link to a GitHub Gist containing relevant Sync Gateway log output when
the error occured. Do NOT paste the log output in the issue, just paste the
link to the Gist.

### Expected behavior
Saving a document with a property that contains the value 1.00 should be persisted as 1.00.

### Actual behavior
Saving a document with a property value of 1.00 is persisted as the value 1 with the zeros to the right of the decimal point being stripped.

### Steps to reproduce
1.  Save document with property value of 1.00
2.  Get the document.
3.  Note the property's value is now 1 and the zeroes to the right of the decimal have been truncated.

**Comment by snej** [comment]
The underlying value doesn’t change, in terms of JSON: mathematically, 100 and 100.0 are the same number. **The JSON format, like JavaScript, does not distinguish between integers and non-integers.** The fact that .NET uses different types to store an integer and a float is a detail of that binding, and shouldn’t be expected to have round-trip fidelity if the JSON is re-encoded elsewhere.

**Comment by adamcfraser** [comment]
When the change to use json.Number for unmarshalling undefined fields is merged (https://github.com/couchbase/sync_gateway/pull/3801), this will be partially addressed:  float values with trailing zeroes will retain a single trailing zero (i.e. 100.00 will be stored as 100.0), sufficient to identify the field as float.

Full byte-level preservation of document contents won't be available until the enhancement https://github.com/couchbase/sync_gateway/issues/3797 is implemented.

**Comment by adamcfraser** [comment]
Closing based on #3801, with the additional work for full byte-level preservation being tracked by #3797.
