### ISSUE TITLE
Auto-repair rev tree cycles detected during write

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3670]
Sync Gateway is currently detecting rev tree cycles in revtree.getHistory and reporting an error.  However, this is run post-bucket write (when the document gets added to the rev cache), and we're not going back to repair the revtree.

Need to review whether repairing the rev tree during write introduces any risk that outweighs the benefit of automating repair.

**Comment by adamcfraser** [comment]
Will need to add sufficient test cases to ensure that the auto-repair doesn't have the potential to introduce new problems.

**Comment by Fujio-Turner** [comment]
Could we throw an error in the logs with docID.

**Comment by adamcfraser** [comment]
@Fujio-Turner If auto-repair is in place, I don't think any enhancements to the existing log messages are required.  I agree that if this gets deferred from Iridium, we should at least enhance error messaging.

**Comment by adamcfraser** [comment]
The underlying issue was fixed in a previous release, and there haven't been enough instances to merit the additional handling.
