### ISSUE TITLE
Go1.11: Some tests hang indefinitely under Go1.11beta1

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3671]
Some of the unit tests, specifically the ones using Otto (like `TestCheckUser`, `TestCheckUserArray`, `TestCheckRole`) hang indefinitely when run under Go1.11beta1.

I've dug down to the root cause, and it seems to be a Go compiler optimisation bug. Issues tracked here:
- https://github.com/robertkrimen/otto/issues/314
- https://github.com/golang/go/issues/26194

**Comment by adamcfraser** [comment]
Fixed on the go side, pending updated 1.11 release.
