### ISSUE TITLE
Investigate failing integration tests

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3675]
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/751/console against the master branch after dev was merged in failed with a timeout error:

```
-p 1 -timeout=60m
Running Sync Gateway unit tests
?   	github.com/couchbase/sync_gateway	[no test files]
2018-07-09T10:11:39.595-07:00 [INF] Successfully opened bucket
2018-07-09T10:11:39.596-07:00 [INF] Flushing bucket test_data_bucket
panic: test timed out after 1h0m0s

goroutine 53 [running]:
testing.startAlarm.func1()
	/root/.gvm/gos/go1.8.5/src/testing/testing.go:1023 +0xf9
created by time.goFunc
	/root/.gvm/gos/go1.8.5/src/time/sleep.go:170 +0x44
```

**Comment by tleyden** [comment]
To try to isolate this to an infrastructure change vs a code change, in [integration test 752](http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/752/console) I'm re-running the tests against commit e93101b2c05bf8818d5414f8fa2faf274e642e4f, which is the commit on the dev branch after https://github.com/couchbase/sync_gateway/pull/3520#issuecomment-393283748, which was passing integration tests at the time of that PR.

* If it's now failing, that would indicate an infrastructure change that's causing integration tests to fail
* If it's still passing, that would indicate a code change that went into master that broke things

**Comment by bbrks** [comment]
Cross-posting findings from chat

> [11:11 AM] Ben Brooks: Based on those last few integration runs you kicked off Traun, looks like the server is in a pretty bad state? Seems to consistently get stuck trying to flush the bucket on the first test
[11:15 AM] Ben Brooks: Just tried flushing through the Server UI and it just hangs. Definitely something wrong on the server side
[12:22 PM] Ben Brooks: Last thing logged on that server was a bucket flush at "4:03:43 AM   Wed Jun 13, 2018" which seems to match when our tests stopped working

**Comment by tleyden** [comment]
I've done a cbcollect info and took a snapshot of the dir, in case there is something worth digging into.

Then I re-installed the same Couchbase Server version, and a smoke test w/ a single test that requires bucket flush is passing:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/755/

Kicking off a re-run of [integration test 752](http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/752/console):

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/756/

as well as a full run against the master branch:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/757/

**Comment by tleyden** [comment]
> Kicking off a re-run of [integration test 752](http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/752/console):
> http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/756/
> as well as a full run against the master branch:
> http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/757/

These both passed!  Looks like it's fixed.
