### ISSUE TITLE
Make bcrypt cost configurable

### ISSUE THREAD

**Issue by will118** [couchbase/sync_gateway#3677]
Would it be possible to add something to `ServerConfig` to allow configuring the `kBcryptCostFactor`?

https://github.com/couchbase/sync_gateway/blob/master/auth/user.go#L25

I feel fairly comfortable making the change if it's something you're interested in.

**Comment by adamcfraser** [comment]
I agree - this is something we should add.  We should also review whether the default should be adjusted based on typical modern processor speeds.

**Comment by bbrks** [comment]
@adamcfraser Go will occasionally increment the default cost factor in their releases based on current hardware, although having said that, the value has not changed from 10 in 7 years.

Incrementing this to 11 will double the time it takes, but there are no strong recommendations above 10 as of right now.

**Comment by bbrks** [comment]
We need to document the fact that password hashes will only utilise a new cost if an existing user changes their password, unless some logic is implemented to add a rolling cost upgrade... For example:

```go
// An example using types/methods from user.go
user := userImpl{...}

ok := user.Authenticate(password)
if !ok {
    panic("login failed")
}

if bcrypt.Cost(user.PasswordHash_) < kBcryptCostFactor {
    // cost factor has since increased, so re-hash the given password
    user.SetPassword(password)
}
```
