### ISSUE TITLE
Documents are not being synced correctly under convergence

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#3683]
See: https://issues.couchbase.com/browse/CM-106

Problem
  Documents are not synced properly under convergence in 5.5 - GA build 2958 and Mobile 2.0
Steps to reproduce
  create a new bucket "syncedBucket"
  update the sync config file (attached), the shared bucket access and import are set to import docs.
  logging tag = *
  create a UI doc 
  create a doc from an SDK (java)
  both are being imported and _sync data is created (channel routing is "uber")
  mobile device does not get the changes
  got to the sync gateway admin "UI"
  verify the documents got the correct channel 
  now click on "Save". 
  The document will now be synced.
  seems like the channel was written twice
  Future updates from SDK are not replicated as well

**Comment by adamcfraser** [comment]
There is a typo in the provided config - it has `enabled_shared_bucket_access` instead of `enable_shared_bucket_access`.  Convergence import isn't being run, explaining the behaviour that's seen.
