### ISSUE TITLE
get, _bulk_get, _all_docs when 404 

### ISSUE THREAD

**Issue by gine** [couchbase/sync_gateway#3686]
When a document is not present _bulk_get and the get API return something like:

{"error":"not_found","id":"id.a","reason":"missing","status":404}

where reason can be "deleted" or "missing".

_all_docs instead doesn't return the attribute "reason".  

Is there any reason for that?

**Comment by adamcfraser** [comment]
Get and bulk_get are used for replication, while all_docs is more of an ad-hoc API.  I expect that's the main reason for divergence between the two.   

For a more general discussion, I'd recommend taking this type of question to the forums:
https://forums.couchbase.com/c/mobile
