### ISSUE TITLE
Store attachment metadata in the rev cache

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3688]
The changes to store attachment metadata in _sync (#3667) currently force a bucket GET to check the value of _sync._attachments, even when the document is resident in the rev cache. 

The revision cache needs to be enhanced to store the attachments metadata outside the body (similar to what's already done for history and channel data).

**Comment by sharujayaram** [comment]
@adamcfraser - 
There is ~18%-22% degradation in read API throughput in 2.5.0-41 build .

http://showfast.sc.couchbase.com/#/timeline/Linux/syncgateway/read/xattr

for tracking purpose .
