### ISSUE TITLE
Session does not propagate to Couchbase when "ttl" field is set in POST request.

### ISSUE THREAD

**Issue by jkingyens** [couchbase/sync_gateway#369]
If I send a POST request to /dbname/_session to customize the session duration, the session does not propagate into couchbase. No session document is even created. However, if I omit the "ttl" field and leave the default (24 hours), everything works fine. The POST response seems to indicate everything is fine, however. I get a valid JSON document with the correct expiry date computed according to the value in the "ttl" field.

**Comment by npomfret** [comment]
Is this fixed?  I'm getting a 401 / "Login Required" when attempting to use a session that was created with the admin api in a one-shot replication on iOS.  The session TTL is longer than the default one day (which is why I'm using the admin api to create it).
