### ISSUE TITLE
Flush log collation on unit test completion

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3693]
Console collated logs aren't being flushed when unit tests complete.  In failing tests in particular, this results in information related to the failure being omitted from the test output logs.

We should force flush of the queued logs on test completion (e.g. testDB.close), or disable log collation when running tests.

**Comment by bbrks** [comment]
I think we should be disabling log collation, as the current implementation of Flush introduces a delay, and would slow down tests dramatically.

It's unlikely we'd need ever log collation enabled in a test scenario.
