### ISSUE TITLE
Sync Gateway should wait for CB Server's N1QL service to become available

### ISSUE THREAD

**Issue by mz2** [couchbase/sync_gateway#3695]
The startup sequence for Sync Gateway with N1QL based indices is awkward in an automated environment where Couchbase Server is started right before Sync Gateway: with multiple buckets created in Couchbase Server, the CB N1QL service becoming available can take a while (on my development iMac Pro where we have six buckets created in CB Server, up to 30s) and Sync Gateway can bail out with the error message suggesting that it thinks the CB Server is run without N1QL service on. Similar issue is not happening as far as I can see with map-reduce views (that we were using until recently), which would suggest that some robustness is in place in SG for that code path that could also be done in case of GSI indices.

I know I can build more logic for this in the Sync Gateway starting end (repeatedly attempt making some N1QL query until it succeeds? is there a less hacky way to query with couchbase-cli or otherwise if the N1QL service is up in the cluster?) but it feels like this kind of logic should existing SG itself given it's a known documented fact that there are warmup periods involved with CB Server and SG requires access to a CB Server.

**Comment by mz2** [comment]
Actually, this looks more like a bug rather than an inconvenience really: I can see a "Unable to install index syncDocs: No available N1QL nodes." (or one of the other indices that are being inserted) in a situation where some seconds before I was able to use the N1QL service with same credentials with a toy query (like `"SELECT _id FROM ${bucket} USE KEYS ["_id"] LIMIT 1"` – this will actually finish successfully *before* I attempt starting up Sync Gateway).

**Comment by adamcfraser** [comment]
@mz2 That's unexpected.  It's possibly a scenario where the updates to the Couchbase Server topology hasn't yet reached the node SG is talking to, but has reached the node your toy query is targeting.  Can you provide some more details on how your toy query specifies a server, and how you're specifying the server node(s) for SG?

In any case, adding a backoff retry instead of failing to start when Query nodes aren't detected seems like a reasonable approach.

**Comment by mz2** [comment]
@adamcfraser nope, not the case – this is with a test cluster that we build using docker-compose, single CB instance, single SG instance. Reason I'd call it a bug is that the map-reduce views don't have this behaviour. What may be bringing this on is that there are a total of six buckets (we are consolidating to a smaller set, and 99% of the data goes already to just one of them, but that is the present status).

**Comment by adamcfraser** [comment]
Several enhancements have been made around retry handling on failed N1QL connection during startup in 2.7.0.  Closing based on this - if there are still gaps, suggest filing a new ticket.
