### ISSUE TITLE
CRUD operations use channels and _doc_ids. Multiple filter conditions.

### ISSUE THREAD

**Issue by dravenk** [couchbase/sync_gateway#3699]
1. If a document exists in a channel.
    Even if the document is stored in a bucket, an error is returned in the channel

It doesn't work. Like that:  
```
 http://localhost:4985/db/_changes?filter=sync_gateway/bychannel&channels=["channel_name"]?filter=_doc_ids&doc_ids=["doc_id_foo"]"
```

Here are two main query conditions
`?filter=sync_gateway/bychannel&channels=["channel_name"]`
`?filter=_doc_ids&doc_ids=["doc_id_foo"]`

**Comment by bbrks** [comment]
There's not currently a way to specify multiple filters on a `_changes` request.

If you already have the document ID, what is the use case of filtering down by channel?

**Comment by dravenk** [comment]
@bbrks 
Hi.
I consider migrating couchdb data to couchbase. I need to consider previous client business compatibility.
A client query /db1/doc_id_1.
B client query /db2/doc_id_2.
If A query /db2/doc_id_2, the return should be 404 or 403.

**Comment by adamcfraser** [comment]
Sync Gateway users are defined at the database level, so user A would only be able to read (anything) from db2 if the user is defined in both db1 and db2.

If it's expected that user A exists in both db1 and db2, they would only be able to read /db2/doc_id_2 if they have read access (i.e. they have access to a channel that doc_id_2 has been assigned to).

**Comment by adamcfraser** [comment]
@dravenk If you have any followup questions on how channels behave, the forums are probably the best place for that type of discussion (https://forums.couchbase.com/c/mobile).  The github issue tracker is intended for bugs and enhancement requests.  Thanks.
