### ISSUE TITLE
Add coverage to integration tests

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3701]
Modify the jenkins integration job to include coverage report, to provide coverage insight for code that depends on a backing Couchbase Server bucket.

**Comment by bbrks** [comment]
It's difficult to adapt the current integration test job cleanly without upgrading to Go 1.10 #3175 

For now I've updated the `sync-gateway-coverage` job to use the `gocoverutil` tool to merge multiple coverage reports and run unit+integration tests.

E.g: http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-coverage/33/Code_Coverage/

I will keep this issue open to implement coverage reporting in our main job once we upgrade the Go version.
