### ISSUE TITLE
Allow restricting of domains for OIDC auth

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#3709]
Take the example of Implicit Auth with Google - with `register:true`, a valid Google user will automatically create a Sync Gateway user with the name like `accounts.google.com_01189998819991197253`. Obviously, this is viable for authentication as the user is definitely (in so far as we can trust Google) who they say they are, and by setting `register:true` we've opted in to creating a user record based on that fact. 

We haven't yet authorised the user to access anything other than the public channel (`!`), so there's not really a risk here. It does mean though that we have to add an extra step (and, likely, component) - it would be nice if we could do some of this inside Sync Gateway.

Imagine creating a application/service where we want to allow any user from one company to create an account, but no one else. If we can validate that the email address for the user we just authenticated ends with `@couchbase.com` and prevent any others from registering, we can treat the public channel as authenticated as it's restricted to `@couchbase.com` users.

**Comment by adamcfraser** [comment]
I would expect this to be done on the OIDC provider side.  The JWT token generated by the provider is for a given client - in our case that client is Sync Gateway.  If the OIDC provider only wants a subset of the users in their backend store to have access to a given client, that would be configured in the provider/IdP.

**Comment by JFlath** [comment]
I think that's a fair (and not uncommon) case; however to the best of my knowledge, Google's API (as an example) doesn't provide this facility. In any case, it'd be nice to belt & braces this - having a check as close to the actual data access as possible makes me feel much more comfortable about the whole affair :).

Whilst not an authoritative source, searching for this does seem to point to client side validation as being a necessary step: https://stackoverflow.com/questions/10858813/restrict-login-email-with-google-oauth2-0-to-specific-domain-name#comment20663614_11001585

**Comment by bbrks** [comment]
@JFlath have you looked at the hd (hosted domain) parameter?

https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

**Comment by JFlath** [comment]
Will have a re-read, but:

> Don't rely on this UI optimization to control who can access your app, as client-side requests can be modified. Be sure to validate that the returned ID token has an hd claim value that matches what you expect (e.g. mycolledge.edu). Unlike the request parameter, the ID token claim is contained within a security token from Google, so the value can be trusted.

**Comment by adamcfraser** [comment]
Closing based on age - can reopen in issues.couchbase.com based on additional use case information.
