### ISSUE TITLE
Allow opt-in overriding of OIDC derived username

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#3712]
We currently allow overriding the prefix of OIDC usernames with the [`user_prefix`](https://github.com/couchbase/sync_gateway/blob/master/auth/oidc.go#L48) option. Overriden or not, this is then used to form the full username in the format `prefix_subject` where subject is returned by the OIDC OP:

https://github.com/couchbase/sync_gateway/blob/master/auth/oidc.go#L259-L261

```
func GetOIDCUsername(provider *OIDCProvider, subject string) string {
	return fmt.Sprintf("%s_%s", provider.UserPrefix, url.QueryEscape(subject))
}
```

This is perfectly reasonable, but we can cater to more usecases by allowing the subject to also be overridden to take another property of the `Identity`:

https://github.com/coreos/go-oidc/blob/v1/oidc/identity.go#L10-L15

```
type Identity struct {
	ID        string
	Name      string
	Email     string
	ExpiresAt time.Time
}
```

Obviously, `ExpiresAt` would be a little daft, but `Email` or perhaps `Name` are valid. `ID` definitely makes sense as the default choice, but depending on the OIDC (looking at you, Google) the returned value can be difficult to predict ahead of time (e.g. `accounts.google.com_01189998819991197253`).

Without adding an extra server side component, we currently would have to rely on the client† to identify it's own email address after the fact (for example, for use in the Sync Function). If we can map the generated username back to an email address, we can use this directly in `requireUser()` calls in the Sync Function.

†We do have this information in Sync Gateway, but AFAIK don't make use of it:

https://github.com/couchbase/sync_gateway/blob/master/auth/auth.go#L215-L225

```
// Looks up a User by email address.
func (auth *Authenticator) GetUserByEmail(email string) (User, error) {
	var info userByEmailInfo
	_, err := auth.bucket.Get(docIDForUserEmail(email), &info)
	if base.IsDocNotFoundError(err) {
		return nil, nil
	} else if err != nil {
		return nil, err
	}
	return auth.GetUser(info.Username)
}
```

**Comment by adamcfraser** [comment]
The motivation behind using subject to build the Sync Gateway username is that we can rely on it being unique and immutable.  That isn't necessarily the case for the claims used to build the Identity.  

An alternative solution for the problem described might be to support admin channel grants based on claims in the JWT token.  There are some interesting challenges here around how this set is maintained as the claims change - for that reason it's probably necessary to store these in a set that's distinct from admin_channels.

**Comment by tleyden** [comment]
@djpongh was this removed from icebox intentionally?

**Comment by adamcfraser** [comment]
Closing based on the above discussion.  If there's an aspect of the original request that's not addressed, suggest reopening in JIRA.
