### ISSUE TITLE
Mirror third-party dependencies in couchbasedeps org

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3728]
There are a number of third-party dependencies in our manifests that aren't tracked by the couchbasedeps remote as identified in #3714 

Need to get these mirrored/updated if necessary in couchbasedeps and then update our manifests.

**Comment by adamcfraser** [comment]
Need to review the current set, and:
- for repos already mirrored in couchbasedeps, update our manifest
- for repos that aren't mirrored, put together list to pass along to couchbasedeps owners

**Comment by bbrks** [comment]
Review of dependencies in default.xml on master revealed many repos need mirroring, and a few which are already mirrored but we're not using. I will send this list out to the couchbasedeps owners to get them mirrored and updated there.

## For couchbasedeps owners:
Mirror needs adding:
- [x] github.com/natefinch/lumberjack (aee4629)
- [ ] github.com/mreiferson/go-httpclient (63fe23f)
- [x] github.com/coreos/go-oidc (5aa9381)
- [x] github.com/coreos/go-systemd (1d9051f)
- [x] github.com/coreos/pkg (160ae62)
- [x] github.com/jonboulle/clockwork (ed104f6)
- [ ] github.com/satori/go.uuid (5bf94b6)
- [x] github.com/go-sourcemap/sourcemap (6e83ace)

Mirror needs updating:
- [x] github.com/elazarl/go-bindata-assetfs (30f82fa - mirrored-HEAD:57eb5e1)
- [x] github.com/rcrowley/go-metrics (7aeccda - mirrored-HEAD:dee209f)

## For Sync Gateway devs:
Mirrored (but not used):
- [ ] github.com/samuel/go-metrics (mirrored as go-metrics-1)
- [ ] github.com/pkg/errors

Mirrored (and used):
- [x] github.com/natefinch/npipe
- [x] github.com/gorilla/context
- [x] github.com/gorilla/mux
- [x] github.com/robertkrimen/otto
- [x] golang.org/x/text
- [x] golang.org/x/net
- [x] golang.org/x/sys
- [x] golang.org/x/crypto
- [x] github.com/kardianos/service
- [x] github.com/kardianos/osext
- [x] github.com/google/uuid
- [x] github.com/opentracing/opentracing-go

Unused/skipped test:
- [x] github.com/tleyden/fakehttp

**Comment by bbrks** [comment]
I've updated `go-bindata-assetfs` and `go-metrics` in couchbasedeps via this Jenkins job: http://server.jenkins.couchbase.com/job/update-couchbasedep/

I'm unable to add the new mirrors via Jenkins, so will leave the owners to do that.
