### ISSUE TITLE
2.0 replication doesn't notify clients when unable to send rev message

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3738]
During pull replication, the following sequence of messages is expected:
1. Sync Gateway sends **changes** message to client.
2. Client returns response indicating which revisions they need.
3. Sync Gateway sends **rev** message for each revision that's requested.
4. Client returns response indicating whether revision was successfully persisted.

In the scenario that Sync Gateway is unable to perform step 3 (most commonly because the revision body is no longer available), it responds by not sending any rev message at all.

Couchbase Lite is currently monitoring replication status by comparing the number of revisions requested in step 2 with the number of rev messages received in step 3.  In the event that Sync Gateway fails to send a rev message, replication becomes stuck in a busy state on the client.  

There are at least two expected scenarios where SG is known to be unable to send a rev, that shouldn't terminate replication:
 - Document has been purged from SG's backing bucket, but is still resident in SG's channel cache
 - Document has been updated on SG under convergence, so old revision body is unavailable 

For expected cases, Sync Gateway could send an rev message with a new `error` property in this scenario to allow CBL to reconcile it's count.  This property could also be used in future to differentiate between error scenarios to trigger additional CBL action.

This doesn't address how to handle unexpected errors (that replication should eventually retry).  I don't know of a mechanism that Lite could do this, other than stopping the entire replication and restarting with the previous since value.  Before triggering that, should Sync Gateway perform a backoff retry on rev message?

**Comment by snej** [comment]
LiteCore has a mechanism for this but I don’t recall the details (I’m away from the computer). IIRC there’s a different message it sends in case of error. I’ll post details later.

**Comment by snej** [comment]
It sends a no-reply `norev` message, with an `error` property containing the error number (as well as the same `id`, `rev`, `sequence` properties as a `rev` message.)

**Comment by adamcfraser** [comment]
Should be straightforward to repro this scenario in a unit test along the following lines:
1. Write 5 documents to a channel
2. Issue a purge for the document through SG
3. Flush rev cache using FlushRevisionCache
4. Perform a one-shot pull replication via the 2.0 replicator

Expected:
- four rev messages, one norev message

Actual:
- four rev messages
- (with actual CBL, results in replication stuck in 'busy' waiting for 5th rev/norev)

**Comment by tleyden** [comment]
@snej I added PR to update the spec and assigned it to you: https://github.com/couchbase/couchbase-lite-core/pull/566

**Comment by pasin** [comment]
https://github.com/couchbase/couchbase-lite-ios/issues/2208 has been opened, and it seems to be the same issue here.

**Comment by tleyden** [comment]
@pasin can you check this PR to see if it matches the Couchbase Lite expectations on what fields should be sent in the norev messages?

https://github.com/couchbase/couchbase-lite-core/pull/569

**Comment by pasin** [comment]
@tleyden From [Puller.cc](https://github.com/couchbase/couchbase-lite-core/blob/6d0ad8fdbdbf694b70be3fbf0bf62451194e60db/Replicator/Puller.cc#L210-L217), it doesn't seem that LiteCore handles error and reason in particular.

**Comment by tleyden** [comment]
Fixed in https://github.com/couchbase/sync_gateway/pull/3763
