### ISSUE TITLE
Sync Gateway should set priority to Medium on DCP stream

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#3739]
Raising this to match the issues spun out of [MB-11640](https://issues.couchbase.com/browse/MB-11640). Suspect this may naturally follow changes in cbdatasource or even be automatic as far as Sync Gateway is concerned. Feel free to close if that's the case - just wanted to make sure this didn't slip under the radar...

**Comment by adamcfraser** [comment]
Migrated to CBG-788.
