### ISSUE TITLE
'/' in blob property names requires encoding URLs for retrieval

### ISSUE THREAD

**Issue by HodGreeley** [couchbase/sync_gateway#3751]
This issue happens when trying to retrieve attached blobs written with CBL 2.1, using SG 2.1.0.

The document format changed to, e.g.,
```
{
  "_attachments": {
    "blob_/cover": {
```

This seems to require CBL 2.1 as well as SG 2.1. (CBL 2.0 in combination with SG 2.1.0 doesn't insert a "/" in the blog property name.)

REST API requests for the blob fail unless the "/" in the property name is encoded.
So
`curl -X GET -H "Content-Type: image/png" -H "accept: application/json" "http://localhost:4985/inventory/069bbbdf-5282-4eff-9808-fe742faa9884/blob_/cover"` fails, but 
`curl -X GET -H "Content-Type: image/png" -H "accept: application/json" "http://localhost:4985/inventory/069bbbdf-5282-4eff-9808-fe742faa9884/blob_%2Fcover"` succeeds.

Tagging it because it seems inconsistent and has confused users.

**Comment by adamcfraser** [comment]
This is standard for special characters in SG's REST endpoints (in this case to differentiate the "/" in the attachment name from a URL path separator).

Given that the default 2.0 attachment naming is path based, it's probably reasonable to call this out in the docs.  I've filed https://issues.couchbase.com/browse/DOC-4131.
