### ISSUE TITLE
sync gateway fail to start with CBS server 6.0.0-1643 using GSI in CC mode

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3755]
### Sync Gateway version
SG version - 2.1.0-121

### Couchbase server
CBS -  6.0.0-1643

### Operating system
Centos

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,


    "logging": {"debug": {"enabled": true} },
    "databases":{
        "db":{
            "import_docs": "continuous",
            "enable_shared_bucket_access": true,


            "num_index_replicas": 0,
            "server":"http://192.168.33.10,192.168.33.11,192.168.33.12:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password"
        }
    }
}
```

### Log output
https://gist.github.com/sridevi-15/f64ac3ba064e887188938478142f7265

### Steps to reproduce
1.  Set up 3 couchbase servers in the CBS cluster.
2.  Start sync-gateway with above config by providing 3 cbs urls
 

### Expected behavior
It should start successfully 

### Actual behavior
Sync gateway failed to start

Note : It passed with previous version 5.5.2-3733 and previous versions of CBS. It passed in DI mode(sg accel) with CBS 6.0.0-1643. 
It passed with use views in CC mode with CBS 6.0.0-1643

**Comment by sridevi-15** [comment]
cbcollect info of all 3 cbs servers
[cbs1.zip](https://github.com/couchbase/sync_gateway/files/2402962/cbs1.zip)
[cbs2.zip](https://github.com/couchbase/sync_gateway/files/2402963/cbs2.zip)
[cbs3.zip](https://github.com/couchbase/sync_gateway/files/2402964/cbs3.zip)

**Comment by sridevi-15** [comment]
Synced up with dev and created server ticket

**Comment by adamcfraser** [comment]
https://issues.couchbase.com/browse/MB-31367

**Comment by adamcfraser** [comment]
Fixed as server issue (see https://issues.couchbase.com/browse/MB-31367)
