### ISSUE TITLE
Increase MaxIdleConnsPerHost to 100 in sg-replicate http client

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3762]
If there are more than two replications with the same host, then the sg-replicate httpclient default setting of MaxIdleConnsPerHost will most likely result in more connection churn and connections that end up in the `TIME_WAIT` state, based on the reasons described here:

http://tleyden.github.io/blog/2016/11/21/tuning-the-go-http-client-library-for-load-testing/

This setting should probably get bumped to 100, which was what we're already doing for the GoCB http client IIRC.

Discovered while reviewing https://github.com/couchbaselabs/sg-replicate/pull/60

**Comment by adamcfraser** [comment]
sg-replicate issue has been merged - pending manifest update.
