### ISSUE TITLE
Omit unnecessary sequence field from norev message

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3764]
As discussed here:

https://github.com/couchbase/sync_gateway/pull/3763#discussion_r220323160

In particular:

> Looking closer, the sequence that we're sending in the rev message is always just the sequence we previously sent in the changes message - we're not attempting to recalculate it from the document's current metadata. Given that, I think there's even less value in sending it back to the client on the rev message. I'm not sure why the changes response from CBL is specifying sequence, in fact.

**Comment by adamcfraser** [comment]
Needs end-to-end testing with Lite to ensure no regressions.

**Comment by adamcfraser** [comment]
CBL is using the sequence in a rev message for checkpoint tracking, so it's only safe to remove from norev.
