### ISSUE TITLE
Update cache on DCP delete mutations without xattrs

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3765]
Currently Sync Gateway's feed processing [ignores delete mutations](https://github.com/couchbase/sync_gateway/blob/master/db/change_cache.go#L373) that don't have an associated xattr, as this doesn't represent a tombstone that needs to be replicated to clients.

However, this mutation may represent a purge of a document that's still resident in Sync Gateway's channel caches.  In that scenario, removing the entry from the cache will avoid potential replication overhead.

Unfortunately, since the delete mutation doesn't have the xattr associated with it, we don't have any visibility to channel membership for the document.  A brute force check of all active channels is required in order to purge the document from the cache.  Each cache already includes a hashmap of resident keys, so what's required is:
- iterate over changeCache.channelCaches
   - requires a read lock on changeCache.lock
- for each cache, check channelCache.cachedDocIDs for the key
   - requires a read lock on channelCache.lock
- delete the entry from the cache (remove from c.cachedDocIDs, c.logs, similar to what's done in pruneCache.  Note that this removal shouldn't require any changes to the cache's validFrom, since any associated sequence is no longer allocated to a revision
  - requires write lock on channelCache.lock

The performance overhead associated with this scan (particularly with the associated locking) is a potential concern.  There are a number of scenarios where a delete mutation wouldn't be expected to be found in the channel cache, resulting in scenarios where the work to check for the key in caches is just processing overhead.  These include:
- delete of documents that were never mobile-enabled (e.g. rejected by import filter)
- delete of documents that are no longer resident in the rev cache

To minimize the impact of the new delete processing on overall feed throughput, we could evaluate treating cache removal as an asynchronous process.  (i.e. stick the incoming event into a buffered channel in DocChangedSynchronous, and have a background worker goroutine process that channel.)  However, need to consider scenarios where a deleted doc gets resurrected - if the resurrected version gets cached before the delete is asynchronously processed, it would result in an invalid cache removal.

**Comment by bbrks** [comment]
We don't remove items from channel cache on a DCP delete in #3770 , but we do upon calling `_compact` and `_purge`.

We could think about having some background task running to clean these up on DCP delete in the future but the potential overhead of doing so was too much to get into 2.1.1
