### ISSUE TITLE
Importing Key/Value pair with null value causes SG to panic

### ISSUE THREAD

**Issue by Binary-Ape** [couchbase/sync_gateway#3774]
Hello!

CB Version: `5.1.0` and `5.1.1`
SG Version: `Couchbase Sync Gateway/2.0.0(832;2d8a6c0)`
OS: `CentOS 7` and `OEL 6.10`

I have a sync gateway with its config below where `enable_shared_bucket_acccess` is true and `import` is set to continuous. If someone saves a Key/Value to Couchbase where the value is just `null` then the import process will cause the SG to crash and restart. It will continue to crash and restart until it either doesn't import for some reason or gets stuck trying to start up.

Here is a simple config file that I used to test the issue on:

```javascript
    "adminInterface": "0.0.0.0:4985",
        "interface": "0.0.0.0:4984",
        "log": ["CRUD+", "HTTP+", "Access", "Changes+", "Events+", "Import+"],
        "logging":{
                "default": {
                        "logFilePath": "/home/sync_gateway/logs/log.log",
                        "rotation": {
                                "maxsize": 1,
                                "maxage": 14,
                                "maxbackups": 15
                        }
                }
        },
        "databases": {
                "db": {
                        "server": "http://localhost:8091",
                        "bucket": "Test_Bucket",
                        "username": "Test_User_App",
                        "password": "couchbase",
                        "users": {
                                "GUEST": {"disabled": false, "admin_channels": ["*"] },
                                "TestSGUser": {"password":"couchbase" ,"disabled": false, "admin_channels":["*"]}
                        },
                        "enable_shared_bucket_access": true,
                        "import_docs": "continuous",
                        "sync": `
                             function(doc, oldDoc){
                                      if(doc.Name){
                                          channel(doc.Name)
                                     }
                            }`
                }
        }
```
### Log output
https://gist.githubusercontent.com/Binary-Ape/5eb2c5224df8cce792c34ca3b9a7dbbd/raw/825bda1e790e6942e0eaec1cbf94905d0141b794/SyncGateway_Null_Issue.log

https://gist.githubusercontent.com/Binary-Ape/5eb2c5224df8cce792c34ca3b9a7dbbd/raw/cc70139a8b39e5ff2c5117e9c7e3f64a38a3788f/sync_gateway_error.log

### Expected behavior
Sync Gateway should of imported the document with its null body.

### Actual behavior
Sync Gateway Crashed

### Steps to reproduce
1.  Create a bucket with shared bucket access and importing continuous
2.  Web Admin UI -- Create a new document
3.  Change document value to `null`

**Comment by bbrks** [comment]
@Binary-Ape Thanks for the bug report, I've managed to reproduce it easily with the steps you've provided. Do you have a use-case for having documents with null bodies in Couchbase Server? Or are these a side-effect of something else?

You'd be able to fix this issue in Couchbase Server by either removing those null documents, or giving them an empty JSON body (i.e. `{}`) so that SG can process them.

Sync Gateway does not allow creation of a document with a 'null' body via the REST API:

```
2018-10-04T12:29:34.455+01:00 [INF] HTTP:  #002: PUT /db/null_doc_body (as ADMIN)
2018-10-04T12:29:34.455+01:00 [ERR] 400 Document body is empty -- rest.(*handler).writeError() at handler.go:689
```

So I think we should adhere to the same behavior for import, and log a message indicating why that document was skipped.

**Comment by Binary-Ape** [comment]
@bbrks There is no use case for the `null` documents as we have put a check in the code to not write them to CB. From my understanding they (developers) were consuming information from another source and if there was missing information then documents would be created with the right key but a `null` body.

I agree that skipping the document for import is a perfectly fine solution. 

*Edit*

One thing I just noticed is that SG is throwing an ERR for the `null` document above, hopefully we would make this an INFO level during the import. I understand why you would pass a ERR/400 back to someone using the REST API.
