### ISSUE TITLE
Improve errors and add warnings when nearing xattr/_sync limits

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3776]
When using convergence, we can easily determine if we're nearing the 1MB xattr limit, and warn when that is the case. We should also clearly error and reject a write that would exceed that size.

For non-convergence, it's more complicated, as `_sync` metadata + doc body size must be under 20MB. So we'll need to take both into account for these warnings/errors.

**Comment by adamcfraser** [comment]
In addition to errors/warnings, we can also trigger revtree pruning when we detect that xattr size exceeds the 1MB limit during migration.  This will allow users to configure revs_limit to avoid migration issues.

**Comment by Fujio-Turner** [comment]
@adamcfraser , should we suggest a litmus test N1QL query(s) to customers to see if they will have any problems for those still using CBM 1.x.

Example
**SELECT META().id FROM bucket where array_length(_sync.history.rev) > 1000**
or
a query for "bodymap":   that do Not only have "_deleted:true" only .. many times people will fill up the 20MB limit with unknown soft deletes

Also this will show customers they have hidden conflicts.

**Comment by bbrks** [comment]
@Fujio-Turner A better approach would be to query based on sync metadata size directly, rather than inferring based on some rev limit.

```sql
-- Returns all doc IDs where _sync is > 1MB
SELECT meta().id FROM `bucket` WHERE ENCODED_SIZE(_sync) > 1000000;
```

**Comment by adamcfraser** [comment]
We should also consider specifying a reasonable 'max recommended channels per document' (with a value of something like 50), and log warnings about expected performance problems when that's exceeded.  Similar for access grants.  Users could have the option to disable this logging with an unsupported flag.

Consider whether same warning approach should be applied to revs limit - have warnings if revs_limit is greater than x, and option to disable warnings.
