### ISSUE TITLE
Add option to fully document delete via the REST api endpoint with conflicting revisions

### ISSUE THREAD

**Issue by samyuyitung** [couchbase/sync_gateway#3779]
When purging my database, I had issues with documents not fully being deleted if they had conflicting tree nodes. In order to fully delete them, I would have to rerun my script until all of the leaves were correctly marked as deleted and then finally it would be "deleted" from my database

I understand that this rolling back and promotion of other leaves is is the intended behaviour of CouchBase, but it would be nice if there was an option in the API call(maybe via a query parameter) to delete all of the leaves of a document rather than just the current one.

**Comment by bbrks** [comment]
@samyuyitung Are you wanting these deletes to be replicated to clients? Or just completely removed from the Couchbase bucket?

**Comment by samyuyitung** [comment]
I guess purging was the wrong word to use to describe this issue. 

For this use case, I would want the deletion to be reflected on both the Couchbase bucket and for all of the affected clients

**Comment by bbrks** [comment]
@samyuyitung I think you're able to do this with a combination of these two requests:

1. `GET /db/my_doc?open_revs=all`
2. `POST /db/_bulk_docs` with `_deleted=true`, along with the revisions retrieved in the first step.

**Comment by samyuyitung** [comment]
oooh, that sounds like it would have done the trick

I've already done the deletions so unfortunately there isn't a good way for me to try it out and see if it will work as I intended right now.

But I will keep this in mind for the next time I have to do a bunch of deletions

Thank you for your help!
