### ISSUE TITLE
Expvars stats buckets can grow unbounded

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#3809]
In a few places in expvar stats, we "bucket" stats to produce a histogram like output, for example:

https://github.com/couchbase/sync_gateway/blob/408ca21d851f2ff128e68666c9da8177096c48be/db/change_cache.go#L708-L715

Here, we group stats to the nearest 100ms. In the general case, this is reasonable, but if anything's going wrong it can lead to a huge number of buckets all with a handful of items, to take a reasonably minor example:

```
{ ... "requests_3700ms": 134, "requests_3800ms": 118, "requests_3900ms": 116, "requests_4000ms": 116, "requests_4100ms": 106, "requests_4200ms": 117, "requests_4300ms": 111, "requests_4400ms": 132, "requests_4500ms": 81, "requests_4600ms": 116, "requests_4700ms": 127, "requests_4800ms": 118, "requests_4900ms": 108, "requests_5000ms": 115, "requests_5100ms": 112, "requests_5200ms": 131, "requests_5300ms": 129, "requests_5400ms": 112, "requests_5500ms": 113, "requests_5600ms": 120, "requests_5700ms": 124, "requests_5800ms": 136, "requests_5900ms": 131, "requests_6000ms": 121, "requests_6100ms": 123, "requests_6200ms": 128, "requests_6300ms": 122, "requests_6400ms": 132, "requests_6500ms": 123, "requests_6600ms": 98, "requests_6700ms": 102, "requests_6800ms": 118, "requests_6900ms": 100, "requests_7000ms": 122, "requests_7100ms": 116, "requests_7200ms": 105, "requests_7300ms": 107, "requests_7400ms": 106, "requests_7500ms": 119, "requests_7600ms": 95, "requests_7700ms": 100, "requests_7800ms": 99, "requests_7900ms": 111, "requests_8000ms": 103, "requests_8100ms": 120, "requests_8200ms": 108, "requests_8300ms": 117, "requests_8400ms": 102, "requests_8500ms": 130, "requests_8600ms": 130, "requests_8700ms": 116, "requests_8800ms": 118, "requests_8900ms": 108, "requests_9000ms": 111, "requests_9100ms": 121, "requests_9200ms": 116, "requests_9300ms": 133, "requests_9400ms": 113, "requests_9500ms": 113, "requests_9600ms": 141, "requests_9700ms": 95, "requests_9800ms": 112, "requests_9900ms": 127}
```

This was particularly noticeable in Issue #3756 where the re-import of the DCP feed would lead to a huge range (as you're essentially replaying history for the majority of the bucket but treating it as if it just happened.

kv-engine/cbstats has a nice handling of this, e.g.:

```
 get_stats_cmd (888295 total)
    4us - 8us        : (  0.01%)    110
    8us - 16us       : (  3.12%)  27619 #####
    16us - 32us      : (  9.71%)  58492 ##########
    32us - 64us      : ( 30.55%) 185189 #################################
    64us - 128us     : ( 48.39%) 158399 #############################
    128us - 256us    : ( 54.95%)  58313 ##########
    256us - 512us    : ( 56.05%)   9775 #
    512us - 1ms      : ( 66.50%)  92851 #################
    1ms - 2ms        : ( 84.28%) 157913 ############################
    2ms - 4ms        : ( 99.79%) 137743 #########################
    4ms - 8ms        : ( 99.93%)   1294
    8ms - 16ms       : (100.00%)    585
    16ms - 32ms      : (100.00%)      7
    32ms - 65ms      : (100.00%)      0
    65ms - 131ms     : (100.00%)      2
    131ms - 262ms    : (100.00%)      2
    262ms - 524ms    : (100.00%)      0
    524ms - 1s       : (100.00%)      0
    1s - 2s          : (100.00%)      1
    Avg              : (  596us)
```

Admittedly, I'm not 100% au fait on how that's generated, but in general it works well. The loss of resolution at the higher end is a reasonable trade off: I don't care if it took 1987ms or 1789ms, I care that it took over a second ;).  IIRC, there's an upper limit where the final bucket will be something like `??s - INF`.

I realise this might change in the future with stats work for Mercury, but I wanted to flag it up.

**Comment by JFlath** [comment]
This is also the only time I'm gonna request *fewer* stats - enjoy it while it lasts ;).

**Comment by adamcfraser** [comment]
You're correct that the plan is to remove/rework histogram stats in Iridium, as part of the pre-Mercury stats enhancements.  We can use this ticket to track.

**Comment by adamcfraser** [comment]
The 'lag' histograms still need to be cleaned up, including review to ensure that any useful information is still being preserved with the new stats.
