### ISSUE TITLE
Numbers have the `'string'` type in the sync function

### ISSUE THREAD

**Issue by will118** [couchbase/sync_gateway#3819]
We've been running 2.1.0 for a while now, but recently made a build off HEAD.

Our sync function then started complaining numbers weren't numbers.

### Sync Gateway version
`{"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":"2.5"},"version":"Couchbase Sync Gateway/HEAD(nobranch)(65c2a7d)"}`

### Operating system
Arch Linux 4.18.16-arch1-1-ARCH

### Config file
```javascript
{
  "log": ["HTTP", "CRUD", "Sync", "Access", "Attach", "Bucket"],
  "interface": ":4984",
  "adminInterface": ":4985",
  "databases": {
      "projects": {
          "server":"http://localhost",
          "sync": "function syncFn(doc, oldDoc) { throw ({ forbidden: typeof doc.createdAt }); }",
          "send_www_authenticate_header": false,
          "use_views": false,
          "password": "foobar",
          "allow_conflicts": false,
          "num_index_replicas": 0
      }
  }
}
```

### Log output
```
~/sg-conf
❯ curl \
  -d '{ "createdAt": 123 }' \
  -H "Content-Type: application/json" \
  0.0.0.0:4985/projects/

{"error":"Forbidden","reason":"string"}
~/sg-conf
❯ curl \
  -d '{ "createdAt": "foo" }' \
  -H "Content-Type: application/json" \
  0.0.0.0:4985/projects/

{"error":"Forbidden","reason":"string"}
~/sg-conf
❯ curl \
  -d '{ "createdAt": false }' \
  -H "Content-Type: application/json" \
  0.0.0.0:4985/projects/

{"error":"Forbidden","reason":"boolean"}
~/sg-conf
❯ curl \
  -d '{ "createdAt": [] }' \
  -H "Content-Type: application/json" \
  0.0.0.0:4985/projects/

{"error":"Forbidden","reason":"object"}
~/sg-conf
❯ curl \
  -d '{ "createdAt": {} }' \
  -H "Content-Type: application/json" \
  0.0.0.0:4985/projects/

{"error":"Forbidden","reason":"object"}
```

### Expected behavior
Numbers should have the number type

### Actual behavior
Numbers have the string type

**Comment by adamcfraser** [comment]
I expect this is related to this change: https://github.com/couchbase/sync_gateway/pull/3801 - numeric values are unmarshaled as json.Number instead of forcing to float64, in order to preserve large integers.  

We're not doing the additional processing to force those back into float/int before passing them to the sync function, as there's a decent amount of performance overhead associated with that work.  In general javascript operations on the values as numbers (i.e. `doc.number == 1234`) work as before.  

It sounds like you may be doing explicit field validation based on the javascript field type - is that correct?  Any details you can share about your use case will help identify how this might be improved.

**Comment by mz2** [comment]
@adamcfraser following up below on behalf of @will118 (we work in the same team, me more nocturnally 😄):

For our application purposes we autogenerate a sync function in part based on a JSON schema, by using [ajv](https://github.com/epoberezkin/ajv) to create a 0-dependency validator function that we then stick inside the sync function.

For example:

```
    "createdAt": {
      "$ref": "numbers.json#/definitions/timestamp"
    }
```

… will end up getting transformed in part to a `typeof` check by ajv. I get what you're trying to do but certainly if it's not a configurable behaviour (preferably opt-in), it seems dangerous. The sync function is a pretty natural component to do data validations, and being able to distinguish between numerical and non-numerical values seems a reasonable validation need.

**Comment by adamcfraser** [comment]
@mz2 @will118 That's a reasonable point.  I don't think a config option would be preferred - ideally we should just support both requirements (this and https://github.com/couchbase/sync_gateway/issues/3783).  However, if we end up having to run the equivalent of [FixJSONNumbers](https://github.com/couchbase/sync_gateway/blob/69555958f20d7e3fc1f3c248d71f39a20f324e82/base/util.go#L84) on the object before passing it to the Sync Function, we may want to reconsider whether this should be opt-in/opt-out based on performance overhead.

Thanks for bringing this to our attention.
