### ISSUE TITLE
Authenticated successfully with invalid session  with  guest enabled in config

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3830]
### Sync Gateway version
Tested on SGW 2.1.1-17

### Operating system
Centos

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,


    "logging": {"debug": {"enabled": true} },
    "databases":{
        "db":{



            "use_views": true,

            "username": "data-bucket",
            "password": "password",



            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "users": {
                "GUEST": {
                    "disabled": false,
                    "admin_channels": [
                        "*"
                    ]
            }
        }
    }
}
}

```

### Steps to reproduce
1.  Load the SGW config and start sync-gateway
2.  Create user in SGW using SGW admin api.
3.  Create docs in SGW with API and pass invalid session 

### Expected behavior
It should fail by throwing 401 error and it should match the behavior with basic authentication 

### Actual behavior
It allow access and it creates docs

Tested with invalid username//password and it is behaving right and throwing 401 error, but with invalid session , it is letting through and giving access to create docs.

**Comment by adamcfraser** [comment]
For clarity - after failing to authenticate the session, it's falling through to GUEST authentication.  It's not authenticating as the user associated with the session.

I agree the behaviour is unexpected, as callers don't get any notification their session is invalid and they've been downgraded to GUEST.

**Comment by adamcfraser** [comment]
Correct behaviour is to reject the auth request when session is provided and is invalid.

**Comment by adamcfraser** [comment]
Moved to https://issues.couchbase.com/browse/CBG-337
