### ISSUE TITLE
CouchbaseServerVersion should use cluster_compat_version

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3833]
`CouchbaseServerVersion()` naively picks the first server version it encounters, however in a mid-upgrade scenario, nodes in the cluster have different versions, and the cluster as a whole is only upgraded when all nodes are running on the same later version.

https://github.com/couchbase/sync_gateway/blob/3e536e5f7e66ab893ff47a02673182c628292786/base/bucket_gocb.go#L2253-L2257

`cluster_compat_version` is a encoded cluster-wide version number which reflects the Couchbase version of the entire cluster. This version is already used by other services determine feature compatibility, and seems cheaper to decode the major/minor versions from it than parsing the string formatted version.

```javascript
function encodeCompatVersion(major, minor) {
   if (major < 2) {
     return 1;
   }
   return major * 0x10000 + minor;
}
```

http://src.couchbase.org/source/xref/6.0.0/ns_server/priv/public/ui/app-new/admin/mn-admin-service.js#encodeCompatVersion

We can get this out of the REST API here, or at `/pools/default/buckets/{bucketName}`:

![screen shot 2018-11-20 at 13 07 45](https://user-images.githubusercontent.com/1525809/48775570-5a26ba00-ecc5-11e8-8e30-8c0e49c8fe29.png)

**Comment by adamcfraser** [comment]
@bbrks Do you know what CBS version added support for `cluster_compat_version`?

**Comment by bbrks** [comment]
@adamcfraser I think it's been exposed via the REST API since CBS 1.6.4
http://review.couchbase.org/c/4042/

Prior art: goxdcr uses it for feature detection seen here:
https://github.com/couchbase/goxdcr/blob/e57c61b95f7a436b105a7592e978fe7a66d1f49e/utils/utils.go#L1318-L1336

https://github.com/couchbase/goxdcr/blob/e57c61b95f7a436b105a7592e978fe7a66d1f49e/base/simple_utils.go#L432-L450

**Comment by adamcfraser** [comment]
@bbrks Great - just wanted to make sure it was reliable back to 4.5 at least.  This change makes sense.

**Comment by JFlath** [comment]
> I think it's been exposed via the REST API since CBS 1.6.4

Technically, I think that's *MBS 1.6.4*. So old that we were still called Membase! :D

**Comment by bbrks** [comment]
Closing as this ticket is being tracked in Jira: https://issues.couchbase.com/browse/CBG-159
