### ISSUE TITLE
Log location of sync_gateway_error.log can not be changed through the config file using : logging.log_file_path 

### ISSUE THREAD

**Issue by girishvjadhav** [couchbase/sync_gateway#3834]
### Sync Gateway version

2.1.1 SG

### Operating system

Ubuntu 14

### Config file

```
{
  "adminInterface": "127.0.0.1:4985",
  "interface": "0.0.0.0:4984",
  "logging": {
    "log_file_path": "/var/log/couchbase/sync_gateway/"
  },
  "databases": {
    "db": {
      "server": "walrus:data",
      "users": {
        "GUEST": {"disabled": false, "admin_channels": ["*"] }
      },
      "allow_conflicts": false,
      "revs_limit": 20
    }
  }
}
```

### Expected behavior

Expected sync_gateway_error.log to be under /var/log/couchbase/sync_gateway/ folder. 

### Actual behavior
What actually happened?

Only the below 3 files were in the log path configured : 

```
-rw-r--r-- 1 sync_gateway sync_gateway  304 Nov 21 09:31 sg_error.log
-rw-r--r-- 1 sync_gateway sync_gateway 9566 Nov 21 09:31 sg_info.log
-rw-r--r-- 1 sync_gateway sync_gateway 1384 Nov 21 09:31 sg_warn.log
```

### Steps to reproduce
1.  Download and install SG 2.1.1. 
2.  Change config file to the one provided. 
3.  Restart SG

I know that continuous logging is a new feature in Sync Gateway 2.1 that allows the console log output to be separated from log files collected by Couchbase Support (sg_error.log ,sg_info.log, sg_warn.log). But is there no way to change log location for sync_gateway_error.log?

**Comment by bbrks** [comment]
The console logs are piped from stdout to a file in the service scripts.
For Ubuntu 15.04, this can be found in: `/etc/init/sync_gateway.conf`

<img width="691" alt="screen shot 2018-11-21 at 12 07 00" src="https://user-images.githubusercontent.com/1525809/48840247-fc0ddb80-ed85-11e8-8e43-6b7c86c19801.png">

This can be customized to suit your own needs.

**Comment by bbrks** [comment]
`sync_gateway_error.log` was removed in Iridium in #3935 and replaced with an optional explicit config-based console file log output.
