### ISSUE TITLE
Unresponsive REST API on startup

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3875]
Issue reported on forums:
https://forums.couchbase.com/t/sync-gateway-admin-service-not-available-after-restart-of-server/19341/6

Based on the logs there, it looks like Sync Gateway successfully connects to the bucket, but then hangs when trying to retrieve/validate the design docs.  This doesn't timeout/fail/otherwise report an error on the Sync Gateway side.  This might be a gocb issue, where gocb is retrying or not setting a timeout on the view request, and so ends up stuck indefinitely.

Seems likely that Couchbase Server is also being restarted along with SG, and that this has to do with attempting to retrieve design docs when the bucket is reachable but the view engine isn't quite ready.

**Comment by bbrks** [comment]
Issue now being tracked at [CBG-225](https://issues.couchbase.com/browse/CBG-225)
