### ISSUE TITLE
Delta Sync: expvar stats not being set for Push replication

### ISSUE THREAD

**Issue by hrajput89** [couchbase/sync_gateway#3876]
### Sync Gateway version
2.5.0-151

### Operating system
Centos7

### Config file
[sync_gateway_json.log](https://github.com/couchbase/sync_gateway/files/2712078/sync_gateway_json.log)

### Log output
Stats from http://172.16.1.112:4985/_expvar - [expvar_stats.log](https://github.com/couchbase/sync_gateway/files/2712079/expvar_stats.log)
Python client runner output - [python_client.log](https://github.com/couchbase/sync_gateway/files/2712080/python_client.log)
SG logs - [sgcollect_info.zip](https://github.com/couchbase/sync_gateway/files/2712081/sgcollect_info.zip)
Logs from iOS app - [xcode_console.log](https://github.com/couchbase/sync_gateway/files/2712082/xcode_console.log)

### Expected behavior
Logs should show the replication as delta or there should be delta stats in SG api call to _expvar

### Actual behavior
Logs doesn't show delta replication and there is no stats for delta in _expvar api call to SG

### Steps to reproduce
Run the below command from this project - https://github.com/couchbaselabs/mobile-testkit/tree/feature/cbl2.5-delta-sync

pytest -rsx -s  --skip-provisioning --timeout 3600 --liteserv-version=2.5.0-126 --liteserv-host=localhost --liteserv-port=8080 --sync-gateway-version=2.5.0-151 --mode=cc --server-version=6.5.0-1813 --liteserv-platform=ios --create-db-per-test=cbl-test testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_delta_sync.py

Test run - https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl2.5-delta-sync/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_delta_sync.py#L50

**Comment by bbrks** [comment]
Added expvar for delta sync push in #3880
