### ISSUE TITLE
sync gateway throws an error when trying to attempt pull replication 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3889]
### Sync Gateway version
SGW - 2.5.0-159

### CBL version:
2.5.0-128

### CBL platform which this test ran:
iOS-swift

### Operating system
Centos

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "logging": {"debug": {"enabled": true} },


    "databases":{
        "db":{




            "num_index_replicas": 0,
            "username": "travel-sample",
            "password": "password",



            "delta_sync": {
                "enabled": true,
                "rev_max_age_seconds": 86400
            },
            "server":"http://192.168.33.10:8091",
            "bucket":"travel-sample"
        }
    }
}

```

### Log output
sg-debug logs : https://gist.github.com/sridevi-15/7b8e2565caa9e6bca0a5c802ed2b0f3f
sync_gateway_error logs : https://gist.github.com/sridevi-15/e7a8ffb948ed4cfe85c6f5b1861e914e

### Steps to reproduce
1.  Create docs in CBL
2.  Do push_pull replication to SGW
3. wait for replication to complete and stop replication
4. Update docs in SGW 
5. Do pull replication , wait for replication to complete and stop the replication

### Expected behavior
Verify that CBL get all updated docs from SGW.

### Actual behavior
None of the docs in CBL got replicated from SGW, it has same old docs as before replication
SG log throwing an error while trying to get change .
Error says that rev id and doc id are empty

**Comment by adamcfraser** [comment]
Merged a fix to avoid the panic.  Underlying issue of why patchRevId was empty may be client/server mismatch, pending merge of https://github.com/couchbase/sync_gateway/pull/3887
