### ISSUE TITLE
Does not log delta sync events on sync gateway logs

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3891]
### Sync Gateway version
SGW - 2.5.0-159

### Operating system
Centos

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "logging": {"debug": {"enabled": true} },


    "databases":{
        "db":{




            "num_index_replicas": 0,
            "username": "travel-sample",
            "password": "password",



            "delta_sync": {
                "enabled": true,
                "rev_max_age_seconds": 86400
            },
            "server":"http://192.168.33.10:8091",
            "bucket":"travel-sample"
        }
    }
}


```

### Log output
https://gist.github.com/sridevi-15/e7a8ffb948ed4cfe85c6f5b1861e914e

### Steps to reproduce
1.  Use syncgateway enterprise edition which should have delta sync enabled by default
2.  start sync gateway
3.  Create docs in CBL and do push_pull replication

### Expected behavior
Verify logs display message that delta sync is enabled

### Actual behavior
do not see any logs related to delta sync on sync gateway

**Comment by bbrks** [comment]
PR #3877 added "DeltaSrc:1-abc" in existing REV message logs (Info level, SyncMsg log key) when the revision is sent as a delta.

There won't be any new log lines per-document, as we want to keep the logging overhead minimal.
