### ISSUE TITLE
Need logging on sync gateway logs if document used is less than 200 bytes

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3892]
### Sync Gateway version
SGW - 2.5.0-159

### CBL version:
2.5.0-128

### CBL platform which this test ran:
iOS-swift

### Operating system
Centos

### Config file
```
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "logging": {"debug": {"enabled": true} },


    "databases":{
        "db":{




            "num_index_replicas": 0,
            "username": "travel-sample",
            "password": "password",



            "delta_sync": {
                "enabled": true,
                "rev_max_age_seconds": 86400
            },
            "server":"http://192.168.33.10:8091",
            "bucket":"travel-sample"
        }
    }
}

```

### Steps to reproduce
1.  Use sync gateway enterprise edition and CBL enterprise edition
2.  start sgw with above config file.
3.  create a doc with less than 200 bytes in SGW and do pull replication

### Expected behavior
Logs has to display in SGW that there is no delta sync for this doc with 200 bytes to identify 

### Actual behavior
No logging related to doc size

**Comment by bbrks** [comment]
I don't think we should be logging anything additional in this case?

**Comment by adamcfraser** [comment]
@bbrks I agree, but I think it's probably valid to add the deltas_inefficient stat that was previously discussed to track these cases, to provide additional insight into the gap between deltas_requested and deltas_sent.

**Comment by bbrks** [comment]
@sridevi-15 We're unable to determine size of documents to add the stat mentioned above without a significant performance hit. In Sync Gateway, we always generate deltas regardless of size.
