### ISSUE TITLE
Limit pending goroutines waiting for channel view lock

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3905]
There's currently no length on the channel view queue (it's a simple lock). Using a fixed length queue and returning a 503-style error when the queue is at capacity will avoid the cumulative increase in latency over time. This will also provide better visibility up the stack about the state of the cache.

May require CBL enhancements to recognize and handle changes entry w/ 503 error correctly.

**Comment by bbrks** [comment]
Issue now being tracked at [CBG-224](https://issues.couchbase.com/browse/CBG-224)
