### ISSUE TITLE
Replace user on blipSyncContext with userName

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3907]
The user on a blipSyncContext isn't guaranteed to be non-stale; any handlers that require an actual user object are reloading the user.  The user on the blipSyncContext is really just used for a name lookup - replacing this with a simple string would future-proof the code from misuse of the blipSyncContext user.

**Comment by adamcfraser** [comment]
This should be integrated with an enhancement to store username and user cas on the blipSyncContext - this could lower the overhead associated with reloading the user.

**Comment by bbrks** [comment]
Issue now being tracked at [CBG-223](https://issues.couchbase.com/browse/CBG-223)
