### ISSUE TITLE
Decrease default revsLimit

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3908]
As more clients are running 2.0 and avoiding conflicts, the need to maintain a high revs limit is reduced.  Would like to bring the default revs limit down to 50 to better manage mobile metadata size in the default config.

**Comment by adamcfraser** [comment]
@JFlath Would like your input on implication for existing users.

**Comment by bbrks** [comment]
Issue now being tracked at [CBG-222](https://issues.couchbase.com/browse/CBG-222)
