### ISSUE TITLE
Error when using basic-walrus-bucket.json from examples

### ISSUE THREAD

**Issue by rominf** [couchbase/sync_gateway#3915]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
2.1.2

### Operating system
Centos 7 in Docker.

### Config file
`basic-walrus-bucket.json` from `examples`.

### Log output
```
...
[ERR] No logFilePath configured, and --defaultLogFilePath flag is not set. Log files required for product support are not being generated. -- base.(*LoggingConfig).Init() at logging_config.go:40
...
```

### Expected behavior
Example config should not raise any errors.

### Actual behavior
See log output.

### Steps to reproduce
1.  Just try it.

**Comment by bbrks** [comment]
We can't reasonably predict where you'll want your logs written to disk in this case. When Sync Gateway is run as a service, the appropriate user, and log directories are created and used as a default.

But when SG is run directly from the command line, we don't know ahead of time where to write logs, so as the error suggests, you'll need to provide a log file path in the config, or use the `--defaultLogFilePath` flag to have logs written to disk.

**Comment by bbrks** [comment]
Just an update as I've seen you're running inside docker. I would ignore this error, as stdout will be used instead via `docker log`. We have 2 different types of logging. Console logging, and file logging. The second of which is intended for product support.

**Comment by rominf** [comment]
Then why does this ERR even exist? It could be an INFO.

**Comment by bbrks** [comment]
Because supported customers _really_ need to know when they're not generating support logs. Keep in mind if you're running Sync Gateway via the service scripts then you'll never see this error.
