### ISSUE TITLE
Add web UI for managing users

### ISSUE THREAD

**Issue by rominf** [couchbase/sync_gateway#3917]
I propose to add a web UI for managing users like in CouchBase Server because now managing users is very non-obvious. I couldn't understand from the docs how to add a read-only user (or to allow anonymous users to only read).

**Comment by rominf** [comment]
I propose to rethink user management in Sync Gateway because writing the code for user authorization is very non-obvious and user-unfriendly.

As for my question, I understood that I don't need to write changes back to CouchBase, so I just throw the forbidden error.

**Comment by adamcfraser** [comment]
@rominf The documentation on Data Routing is probably the right place to start, to understand how to manage a user's read/write access.
