### ISSUE TITLE
Bucket shadowing doesn't recover from app bucket becoming unavailable

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#395]
If the app bucket becomes unavailable while the gateway is running, changes made to the gateway's database after that point won't get propagated to the app bucket when it comes back online.

The problem is that the calls to `Shadower.PushRevision()` are only made as the doc changes are seen in the gateway bucket's live tap feed; there's no mechanism to apply historical changes that have already occurred.

To fix this we'd need to
- [ ] Keep track of the latest gateway db sequence number that's been written to the app bucket
- [ ] Add a mechanism to read the changes feed since a particular sequence and send all those revisions to the shadower
- [ ] Hook those two things together so that when an app bucket comes online any skipped revisions get sent.

**Comment by yuzkan** [comment]
Hi,
is there any progress on this issue? Ajres mentioned it was planned for December but so far it is still opened.

Thanks

**Comment by ajres** [comment]
This is still scheduled for the 1.1.0 release.

SG 1.0.4 has just being completed, 1.1.0 is the next planned release.

**Comment by zgramana** [comment]
Note related https://github.com/couchbase/sync_gateway/issues/748

**Comment by bbrks** [comment]
Bucket shadowing deprecated/removed. No longer relevant.
