### ISSUE TITLE
Unparseable JSRunner warning on valid json docs

### ISSUE THREAD

**Issue by mikemliu** [couchbase/sync_gateway#3959]
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
1.5.1

### Operating system
Ubuntu

### Config file
Will provide upon request

### Log output
2019-01-31T23:07:08.864Z HTTP:  #6487378: POST /workforce/_bulk_docs  (as xxx)
WARNING: Sync fn exception: Unparseable JSRunner input: ^A{"account_id":"11f19c8938d7a124666fae632285df87","assigned_to":"bb7b9698df5cb453312377c860d39207","created_at":"2019-01-21T23:03:18.948Z","created_by":"728876e2a1c19f55f65b339ba23b9531","created_from":"d04974cd4db02ed7c724c3bd8b523ed1","due_at":"2019-02-16T07:59:59.999Z","kind":"task","primary_segment_id":"ce10d85d68dca8cd233dd25e89bbb618","segments":["ce10d85d68dca8cd233dd25e89bbb618","31b1b636af2d0ec2c040314cdc6cdf66","9cc9643a26a79639b47ae1aebc06067d"],"status":"open","task_id":"d04974cd4db02ed7c724c3bd8b523ed1","type":"assignment","updated_at":"2019-01-21T23:03:18.948Z"; doc = map[segments:[ce10d85d68dca8cd233dd25e89bbb618 31b1b636af2d0ec2c040314cdc6cdf66 9cc9643a26a79639b47ae1aebc06067d] account_id:11f19c8938d7a124666fae632285df87 type:assignment created_at:2019-01-21T23:03:18Z created_by:728876e2a1c19f55f65b339ba23b9531 completed_at:2019-01-21T23:39:20Z items:[map[id:OiN69tgVp status:complete type:task]] kind:task _id:671f95c277e88d13cbfce2b5063f2e0f read_at:2019-01-21T23:38:37Z _rev:3-1a01a3123a2164b99d5943488e257e6d status:closed task_id:d04974cd4db02ed7c724c3bd8b523ed1 assigned_to:bb7b9698df5cb453312377c860d39207 created_from:d04974cd4db02ed7c724c3bd8b523ed1 primary_segment_id:ce10d85d68dca8cd233dd25e89bbb618 due_at:2019-02-16T07:59:59Z _revisions:map[ids:[1a01a3123a2164b99d5943488e257e6d ac23d7f35ece4136baed415d603e8ef4 139c73ba2fd9e461d4e67031dc12a27f] start:%!s(float64=3)] updated_at:2019-01-21T23:39:20Z] -- db.(*Database).getChannelsAndAccess() at crud.go:1199
2019-01-31T23:07:08.867Z        BulkDocs: Doc "671f95c277e88d13cbfce2b5063f2e0f" --> 500 Exception in JS sync function (500 Exception in JS sync function)

### Expected behavior
Using ios lite  push replication to sync_gateway should pass sync function as normal, however seeing quite a few of these warnings in logs. Also for the affected documents, seeing a high number of revisions. This may also be resulting in high cpu usage that can only be corrected with a recycle until this document syncs again.

Did notice the initial "\u0001" char, is that an artifact of the print or something wrong with the replication serialization of the document? Not seeing this in normal usage -- only intermittently, so not sure where to begin to debug this.

### Actual behavior
Revisions getting incremented ad infinitum. Only happens to a few select docs, so not sure what is going on.

### Steps to reproduce
Intermittent

**Comment by adamcfraser** [comment]
This sounds like https://github.com/couchbase/sync_gateway/issues/3692, which was fixed in 2.1.1.  See also https://github.com/couchbase/sync_gateway/issues/3700.
