### ISSUE TITLE
IPv6 address not working for couchbase Library

### ISSUE THREAD

**Issue by smithazac** [couchbase/sync_gateway#4024]
Hi,
  I am using robotframework-couchbaselibrary    1.0.4 for using couch base API.

When I use the keyword Connect To Couchbase Bucket for ipv4 address, it works fine. The same function when i try to use for IPv6 address it give me the below error:
('Could not connect to Couchbase bucket. Error:', '<RC=0x15[DNS/Hostname lookup failed], There was a problem while trying to send/receive your request over the network. This may be a result of a bad network or a misconfigured client or server, C Source=(src/bucket.c,793)>')

I have tried passing the ipv6 address  as below:

CouchDB_IP=                    "[fcff:3:10:219::94]"

The ipv6 address is accessible and using the ipv6 address I am able to login to the GUI with default port 8091.

CouchDB_Port=                   8091

Can some one help me out on this?

**Comment by JRascagneres** [comment]
Hi,
The `robotframework-couchbaselibrary` isn't a Couchbase supported project and is a third party library. We therefore recommend you raise an issue with this project directly. I believe this is the GitHub page for the `robotframework-couchbaselibrary` project:
https://github.com/peterservice-rnd/robotframework-couchbaselibrary
