### ISSUE TITLE
Update sync gateway to better support CBS 3.0 view semantics

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#409]
CBS 3.0 has changed the semantics of views so that it is not necessary to first read before the index is updated.

For CBS 2.X the additional read is required, in CBS 3,0 it is not required but in addition calling the additional view read causes a performance issue.

To be considered is whether we switch the behaviour of SG and tie release versions to a specific CBS version or we support both versions of CBS for a period of time.

**Comment by ajres** [comment]
#404 has been completed, a fix for this issue has been coded against #404 branch.

Closing this ticket and opening a ticket for task to merge to master and run perf test.

**Comment by tleyden** [comment]
@ajres in your previous comment: https://github.com/couchbase/sync_gateway/issues/409#issuecomment-71229409 

Can you point to the commit for this fix?

Also what is the status of merging this to the master branch?

**Comment by ajres** [comment]
The PR was merged onto master, the commit was

https://github.com/couchbase/sync_gateway/commit/6051bc69397ce5fe33d9a3761f2b4996d4dd7af8

**Comment by tleyden** [comment]
It doesn't seem to have fixed the issue.  I ran perf tests against cdf269cec0861773f6b2f9991a5284cd9b45407c and here are the results:

http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/775/
http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/776/
- The test only created 11k/13k users in the 30 minutes of time allotted to the test.  (the test stopped before the actual load could be applied)
- In the sync gateway expvars, seeing syncGateway_rest times of requests_39100ms: 84 (84 rest calls took 39.1 seconds to return)
- Lots of warnings in sync gw logs https://gist.github.com/tleyden/a38faeef35f464035b52 about calls to couchbase server taking too long

**Comment by ajres** [comment]
After reviewing this ticket and https://www.couchbase.com/issues/browse/MB-11798 with @adamcfraser, there were two issues related to performance with CBS 3.0.
1. Remove the requirement to Observe (block until data is persisted to disk) on writing to CBS 3.0. This was fixed via commit: 6051bc69397ce5fe33d9a3761f2b4996d4dd7af8
2. A resolution of the view performance issues with stale=false in CBS 3.0 as currently tracked here:

https://issues.couchbase.com/browse/MB-12607

The above appears to be the most recent and active ticket 

Closing this ticket and tracking the progress of the above CBS ticket via #697
