### ISSUE TITLE
Missing dependency go-fleecedelta

### ISSUE THREAD

**Issue by hubgit** [couchbase/sync_gateway#4164]
The Sync Gateway code has a dependency on "github.com/couchbaselabs/go-fleecedelta" but there is no public package at https://github.com/couchbaselabs/go-fleecedelta

https://github.com/couchbase/sync_gateway/blob/5c1a46c4f401be88fc2e1d2b0185a25d8101c0d2/base/deltas_ee.go#L8

Building the Docker image fails with this error:

```
godeps/src/github.com/couchbase/sync_gateway/base/deltas_ee.go:8:2: cannot find package "github.com/couchbaselabs/go-fleecedelta" in any of:
        /usr/local/go/src/github.com/couchbaselabs/go-fleecedelta (from $GOROOT)
        /go/godeps/src/github.com/couchbaselabs/go-fleecedelta (from $GOPATH)
```

**Comment by bbrks** [comment]
`go-fleecedelta` is a private package for the enterprise-edition of Sync Gateway.

By default, Go will build the community edition of Sync Gateway, which does not require this package.

**Comment by hubgit** [comment]
By default, both editions will be built:

https://github.com/couchbase/sync_gateway/blob/99744b03382750601e4063d39ee6e16f8e0073d3/build.sh#L13

**Comment by bbrks** [comment]
I'm going to close this issue now the Dockerfile builds CE-only by default (via https://github.com/couchbase/sync_gateway/pull/4165)

We use `build.sh` internally, and don't particularly want to change the default behaviour of that script. But the Dockerfile, and `go build` (via lack of build tags) both default to CE.
