### ISSUE TITLE
Redhat 8 sync_gatway not able to start on AWS

### ISSUE THREAD

**Issue by DinakaranS** [couchbase/sync_gateway#4172]
### Sync Gateway version
2.5  

### Operating system
RedHat 8

Used command **systemctl start sync_gateway** to start sync gateway. But getting the below error.

**Failed to start sync_gateway.service: Unit sync_gateway.service not found.**

**Comment by bbrks** [comment]
Hi @DinakaranS 

RedHat 8 is not currently an officially supported OS by Couchbase Server or Couchbase Sync Gateway.

https://docs.couchbase.com/sync-gateway/2.5/official-support.html#supported-operating-systems

The Sync Gateway install script will exit here when it encounters a RHEL/Centos version other than 5, 6, or 7.

https://github.com/couchbase/sync_gateway/blob/191f3a81e3f15766cba3f8c0eb0de88346242c4d/service/sync_gateway_service_install.sh#L271-L275

You can swap the 7 for an 8 in the file linked above, and run it from `/opt/couchbase-sync-gateway/service/sync_gateway_service_install.sh` but be aware this hasn't been vetted by our QE or Performance testing teams yet. But for testing/development purposes, this should be enough to get you going.

**Comment by djpongh** [comment]
tracked in https://issues.couchbase.com/browse/CBG-612
