### ISSUE TITLE
Add ability to block users from channels ('deny' mode)

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#42]
it should be possible to manually block a given user from a channel, even if the sync function grants access to them by name or role.

**Comment by househippo** [comment]
So instead of a ,current, white list model for access a black list model?
How would that work with removing docs on CBL after a user has been black listed on a channel they had access to it before?

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
