### ISSUE TITLE
Replication ordering dependencies can cause sync fn to reject updates

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#422]
(Triggered by [this mailing-list thread](https://groups.google.com/d/msgid/mobile-couchbase/d90b4faf-a10c-4157-b7ae-2e633912050c%40googlegroups.com?utm_medium=email&utm_source=footer) —)

It's possible (and somewhat likely) to construct the sync function to create situations that are ordering-dependent: if one doc causes the sync function to call `access()` and another doc causes it to call `requireAccess()`, then the second doc could fail validation if the first hasn't been processed yet. Thus the replication from a client works if the docs are uploaded in one order but fails in the opposite order.

This goes against the fact that the order in which docs are replicated isn't well-defined (well, ok, it's in order of increasing update time), and the guideline that apps shouldn't have dependencies on what order document updates appear.

I think both Chris and I have had this issue at the back of our minds from time to time, but when it's come up we haven't been able to come up with a good solution for it. And we haven't formally written it down (until now.)

**Comment by adamcfraser** [comment]
When implemented, ensure sufficient logging of retry processing to be able to follow this processing in the logs.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.  In particular the idea of retrying within a single bulk_docs scope is less relevant with 2.x replication, and the retry handling feels like something that would scale better if implemented on the Couchbase Lite side of the replication.
