### ISSUE TITLE
"IndexChannels" Index Returns Deleted Documents

### ISSUE THREAD

**Issue by mlopez526** [couchbase/sync_gateway#4226]
### Sync Gateway version
Couchbase Sync Gateway/2.6.0(127;b4c828d) EE (Tested in Docker)
Couchbase 6.0.2 build 2413 (Tested in Docker)

### Expected behavior
When a document is deleted via the Couchbase SDK, an N1QL query on the "IndexChannels" index should not return that docid.

### Actual behavior
The docid IS returned from that index.

The only way to clear it from the index is to create a blank doc with the same docid (which won't be imported), then delete it again.

### Steps to reproduce
1.  Create a document that will be imported by SG and assigned channel "testChannel"
```python
bucket.insert("indexTest::1", {"type": "indexTest", "channels": ["testChannel"]})
```
2.  Remove that document
```python
bucket.remove("indexTest::1")
```
3.  Query the index used by channel replication and "indexTest::1" will be in the results
```python
bucket.n1ql("""
        SELECT  [op.name, LEAST(META(`{0}`).xattrs._sync.sequence, op.val.seq),IFMISSING(op.val.rev,null), IFMISSING(op.val.del,null)][1] AS seq,
                META(`{0}`).id
        FROM    `{0}`
        UNNEST OBJECT_PAIRS(META(`{0}`).xattrs._sync.channels) AS op
        WHERE   [op.name, LEAST(META(`{0}`).xattrs._sync.sequence, op.val.seq),IFMISSING(op.val.rev,null), IFMISSING(op.val.del,null)]
                BETWEEN ['{1}', 0] AND ['{1}', 99999999999999999]
    """.format(bucket.bucket, 'testChannel'))
```
4. Create and remove an empty doc with the same docid
```python
bucket.insert("indexTest::1", None)
bucket.remove("indexTest::1")
```
5. Rerun query from step 3 and docid will no longer be in results.

### Additional Observations
The only difference between the deletions in steps (2) and (4) seems to be the XATTR used by SG.

Couchbase seems to generally handle deletions differently when a document has XATTRs. 
I've noticed that UPR_DELETION events show up in the DCP feed as dataType 4 when the document has XATTRs, rather than dataType 0.  The feed also still contain their XATTRs despite the document being gone.  Not sure if N1QL indexing relies on DCP, but I thought I'd mention it anyway.

**Comment by adamcfraser** [comment]
This is working as intended - when shared bucket access is enabled, a document deleted via the SDK represents a Sync Gateway tombstone (i.e. a deleted document), and is expected to remain in the index in order for that delete to be replicated to mobile clients.

Tombstones are purged from Couchbase Server based on the server's metadata purge interval.  Once documents are purged, they will be removed from the index the next time tombstone compaction is run by Sync Gateway.  This runs every 24 hours by default.
