### ISSUE TITLE
_all_docs still slow

### ISSUE THREAD

**Issue by jnordberg** [couchbase/sync_gateway#440]
Refs #326

On a bucket with `1 742 612` items fetching `_all_docs` logged in as a user who has 1 channel with 10 documents in it takes more than 60 seconds (our LB cuts the request off at that point so I'm unable to see the response, if there is any).

Requesting `_changes?since=0` as the same user on the same bucket only takes ~20ms.

**Comment by ajres** [comment]
For authenticated users on the public API, _all_docs will now generate the list of documents based on the changes feed. On the admin port the _all_docs feed is still generated by iterating over all the documents in the underlying bucket.
