### ISSUE TITLE
setup a replication from couchdb to couchbase server?

### ISSUE THREAD

**Issue by alexalexalex96** [couchbase/sync_gateway#4440]
Hi,

how can I setup a replication from couchdb to couchbase server using Sync Gateway

Thanks in advance

**Comment by bbrks** [comment]
Hi @alexalexalex96 ,

These types of questions are best posted in the Couchbase forums, where you can get help from a much larger number of people.

https://forums.couchbase.com/c/mobile/14

Thanks!
