### ISSUE TITLE
Add view queries to client API

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#449]
Continuing from #379, opening the view query REST API to clients. The major tasks with this are security related — filtering the query results to rows that were emitted only by docs visible to the user.

**Comment by snej** [comment]
This has been checked in on a branch (feature/query_api) for a while now. It's been unit-tested but needs more thorough functional testing to make certain there aren't security/privacy issues, i.e. leaking data from documents the user doesn't have access to.

**Comment by luiginho97** [comment]
This feature is very important to me

**Comment by shirshir** [comment]
Yes, this is a feature that I also would like to have.

**Comment by toddfreese** [comment]
Me too. Very important.

**Comment by snej** [comment]
Just updated the `feature/query_api` branch, bringing it up to date with `master`.
Still doesn't have unit tests to check the result filtering.

**Comment by tleyden** [comment]
@luiginho97 @shirshir @toddfreese ok this is merged to the master branch.  

Here are some docs that haven't made it up to our docs portal yet:

https://dl.dropboxusercontent.com/u/14074521/gen/develop/guides/sync-gateway/accessing-cb-views/creating-and-using-a-view/index.html

(scroll down to the part where it says "Creating and querying a View")

The most important thing to keep in mind is that you must create the views via the Sync Gateway REST API.  If you try to create them via the Couchbase Web UI, they won't work.

**Comment by shirshir** [comment]
Nice! I will have a look and test it. Thanks!

**Comment by shirshir** [comment]
I just did a quick test: compiled from master, created a view, inserted some docs and queried the view. Works nice! Thanks very much. I think it is a good idea to mention in the docs that you can specify the `stale` option when requesting the view.
Any idea when a new stable version will be released?

**Comment by tleyden** [comment]
@shirshir glad to hear.  We are targeting quarterly releases, but I don't have any hard dates.

Regarding the `stale` option, can you specify exactly why you are using it?  (what problem it solves)

**Comment by shirshir** [comment]
@tleyden It came up in issue #727. I am working on a CRUD interface that uses the sync gateway, and I also noticed that a view does not return new documents by default.
