### ISSUE TITLE
bad performance of _changes query with limit parameter

### ISSUE THREAD

**Issue by olivierboudet** [couchbase/sync_gateway#4495]
### Sync Gateway version
Couchbase Sync Gateway/2.6.0(127;b4c828d) CE
Couchbase Server Community Edition 6.0.0 build 1693

### Operating system
Ubuntu 18.04 LTS

### Config file
```javascript
		"evenement": {
			"unsupported": {
				"user_views": {
					"enabled": true
				}
			},
			"server": "http://couchbase-service:8091",
			"allow_empty_password": false,
			"bucket": "evenement",
			"username":"*****",
			"password":"*****",
			"use_views": false,
			"num_index_replicas": 0,
			"enable_shared_bucket_access": true, 
            "import_docs": true,
			"sync": `function(doc, oldDoc) {
				if(doc.error === true) {
					channel(doc.model+'_'+doc.type+'_ERROR_'+doc.identifiantSite)
				} else { 
					channel(doc.model+'_'+doc.type)
				}
			}`,
			"users": {
				"GUEST": {
					"disabled": true,
					"admin_channels": [
						"*"
					],
					"all_channels": [
						"*"
					]
				}
			}
		},

```
### Expected behavior
When querying the changes of one bucket with less than 2000 docs, the parameter limit slow down the query.

I expect the query with limit parameter to respond faster than the query without (or at least with as fast )

### Actual behavior
```
time curl "http://localhost:4985/evenement/_changes?active_only=true&channels=EVENEMENT_MAINTENANCE&filter=sync_gateway%2Fbychannel&active_only=true"
{"results":[
{"seq":386633,"id":"EVENEMENT:LOG:CREATE:1581607122997","changes":[{"rev":"1-4e291fabac6765eee51f02208e453b060eebd818"}]}
,{"seq":386634,"id":"EVENEMENT:LOG:CREATE:1581607123021","changes":[{"rev":"1-c5b7ff3317d3ba26e1ee13bc6363849a0dc85538"}]}
,{"seq":386636,"id":"EVENEMENT:LOG:CREATE:1581607123229","changes":[{"rev":"1-72a075c54edc97e3c70f15bb498336a52ad942c7"}]}
,{"seq":386637,"id":"EVENEMENT:LOG:CREATE:1581607123845","changes":[{"rev":"1-504b5388468ef65f19cf8f6bc1c708a290840299"}]}
,{"seq":386638,"id":"EVENEMENT:LOG:CREATE:1581607123256","changes":[{"rev":"1-413fc50ecf62341db6718885654c48c6af655000"}]}
,{"seq":386639,"id":"EVENEMENT:LOG:CREATE:1581607123635","changes":[{"rev":"1-4662bb0e4b317230f8e7207bb7487cc613a0ec12"}]}
,{"seq":386640,"id":"EVENEMENT:LOG:CREATE:1581607123033","changes":[{"rev":"1-cfe466eec684d0efcc515764a9824e7b18c8296f"}]}
,{"seq":386641,"id":"EVENEMENT:LOG:CREATE:1581607123247","changes":[{"rev":"1-2c26f15a061ef6c98dc2c2c78245e5be0dbc51a0"}]}
],
"last_seq":"386641"}
curl   0,00s user 0,00s system 0% cpu 1,649 total
```

```
time curl "http://localhost:4985/evenement/_changes?active_only=true&channels=EVENEMENT_MAINTENANCE&filter=sync_gateway%2Fbychannel&active_only=true&limit=10"
{"results":[
],
"last_seq":"0"}
curl   0,01s user 0,02s system 0% cpu 7:04,22 total
```

The query took less than 2s without the limit and more than 7 minutes with the limit ! And as you can see the limit parameter results with 0 documents returned.

In couchbase I observe an increase of "Index scanned/sec" statistic during the calls with limit parameter: 
![image](https://user-images.githubusercontent.com/857205/74715097-20c45d80-522c-11ea-8d8d-44f5dbad2c4b.png)

### Log output
Sync-gateway log without the limit parameter : 

```
2020-02-18T07:53:26.000Z [INF] Channel query took 7m3.727935495s to return 26150 rows.  Channel: EVENEMENT_MAINTENANCE StartSeq: 385985 EndSeq: 385994 Limit: 10

```

Sync-gateway log with the limit parameter : 

```
2020-02-18T07:46:22.272Z [INF] HTTP:  #166997: GET /evenement/_changes?active_only=true&channels=EVENEMENT_MAINTENANCE&filter=sync_gateway%2Fbychannel&active_only=true&limit=10 (as ADMIN)
2020-02-18T07:53:26.000Z [INF] Channel query took 7m3.727935495s to return 26150 rows.  Channel: EVENEMENT_MAINTENANCE StartSeq: 385985 EndSeq: 385994 Limit: 10
```

Couchbase logs : https://gist.github.com/olivierboudet/b7cd5e7523faa9a4acb03c8063a1a9e9

**Comment by adamcfraser** [comment]
@olivierboudet What version of Couchbase Server are you running?

**Comment by olivierboudet** [comment]
@adamcfraser sorry I missed that : 
Community Edition 6.0.0 build 1693

**Comment by sarathkumarsivan** [comment]
@olivierboudet Can you enable Debug level logging in Sync Gateway and share the complete logs? It's mentioned above that  the bucket has less than 2000 docs but, the channel query returns 26150 rows; do you think the remaining docs (about 24K) in the bucket are tombstones?

**Comment by olivierboudet** [comment]
Yes lot of documents are tombstoned in this bucket.
I will try to give you the debug log soon.

**Comment by olivierboudet** [comment]
The full debug log from the start up until the end of the request is available here : https://gist.github.com/olivierboudet/5b35933be2d0ba36a4004e54be88c350/
You must download it as it is truncated in the web view of the gist.

**Comment by adamcfraser** [comment]
Fixed by https://github.com/couchbase/sync_gateway/pull/4513
