### ISSUE TITLE
Syncing deltas instead of the whole documents

### ISSUE THREAD

**Issue by byF** [couchbase/sync_gateway#452]
In our Couchbase+gateway+Couchbase Lite evaluation we've just run into the fact the database is syncing the whole documents instead of deltas. We've expected a smarter solution, maybe based around JSON PATCH. The same goes for the revisions, instead of sequence of events they are stored as a complete documents.

**Comment by Fujio-Turner** [comment]
If SG is storing and keeping the older version of the docs is CB. Could SG store the doc a little differently then the newest rev. EX

key:1234
```
{
"some":"data2"
}
```

key:rev-old:1234
```
{
"old_doc":{"some":"data1"}
}
```

1. This way the old doc does not effect N1QL queries and indexes 
2. I can still use N1QL against older docs also by transversing into the "old_doc"

Optional
Maybe have option to store the old doc as a binary value ,that is compressed, it would be more efficient to store on CB side

**Comment by adamcfraser** [comment]
Tracking as #3720.
