### ISSUE TITLE
public _session endpoint should not validate old session cookie

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [couchbase/sync_gateway#4552]
# Sync Gateway version
Couchbase Sync Gateway/2.7.0(166;a52b9c4) CE

### Problem
I have a web application that accesses CSG with CORS calls. Calling _session with username and password sets a session cookie. If the password for the user is changed, this session gets invalidated (as expected). This means that from now on calls to CSG return 401 (as expected). Unfortunately, there is (as far as I know) no way for the web application to get rid of the session cookie if sync gateway runs on another domain than the web application. Trying to obtain a new session cookie (POST to _session) fails with 401 even though the new credentials are used. Even a DELETE to _session does not work.
(see also: 
https://forums.couchbase.com/t/unable-to-delete-session-cookie/25520 )

### Solution?
If the _session didn't validate old session cookies, the problem would be solved.

**Comment by bbrks** [comment]
Are you able to send the request for a new session without the old cookie by using [`XMLHttpRequest.withCredentials=false`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials)?

If not, this does look like a bit of a gap if the client is unable to clear its own cookies.

As a workaround, you _can_ use basic auth along with sending the old cookie in a DELETE session request.

```
15:07 $ curl -i -c sgcookie -b sgcookie -X DELETE http://demo:password3@localhost:4984/db1/_session
HTTP/1.1 200 OK
Server: /2.8 branch/ commit/ EE
Set-Cookie: SyncGatewaySession=; Expires=Tue, 14 Apr 2020 14:07:31 GMT
Date: Tue, 14 Apr 2020 14:07:31 GMT
Content-Length: 0
```

**Comment by bbrks** [comment]
We've filed an issue to track the fix over at: https://issues.couchbase.com/browse/CBG-825
