### ISSUE TITLE
sync_gateway 2.7.3 failed to build on OSX

### ISSUE THREAD

**Issue by chenrui333** [couchbase/sync_gateway#4589]
relates to https://github.com/Homebrew/homebrew-core/pull/55219

Currently, I trying to upgrade sync_gateway formula to v2.7.3, but I getting some `repo` command issues.

But my question is does sync_gateway support python 3.6+ now?
Similar concern is raised in the warning below:
```
warning: 'https://chromium.googlesource.com/external/repo' does not look like a git-repo repository, is REPO_URL set correctly?
repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.

... A new version of repo (2.5) is available.
... You should upgrade soon:
    cp /private/tmp/sync_gateway-20200524-45530-ahy51q/repo_cache/sync_gateway/.repo/repo/repo /private/tmp/sync_gateway-20200524-45530-ahy51q/depot_tools/repo
```

**Comment by adamcfraser** [comment]
The build for the sync_gateway binary (including repo) should support python 3.6+.  However, the sgcollect tool still needs to be updated for python 3.6+ compatibility.  Filed https://issues.couchbase.com/browse/CBG-880 to track that work.
