### ISSUE TITLE
Admin API  _roles returning Moved Permanently

### ISSUE THREAD

**Issue by eadistar** [couchbase/sync_gateway#4668]
Hi i'm executing 
curl -X GET "http://localhost:4985/default/_role" -H "accept: application/json"

and getting  Moved Permanently. in response

**Comment by bbrks** [comment]
The location header (you can view response headers with `-i` in curl) will tell you where the redirect is going.

Most URL endpoints for Sync Gateway need to end with a trailing slash:

![Screenshot 2020-07-14 at 12 01 46](https://user-images.githubusercontent.com/1525809/87418604-df14c480-c5c9-11ea-9486-26a176709254.png)

**Comment by eadistar** [comment]
Got It.
