### ISSUE TITLE
Examples README is out of date

### ISSUE THREAD

**Issue by hubgit** [couchbase/sync_gateway#4702]
The [README in the examples folder](https://github.com/couchbase/sync_gateway/blob/master/examples/README.md) no longer corresponds to the [files in the examples folder](https://github.com/couchbase/sync_gateway/tree/master/examples).

In particular, the "walrus" examples were removed in #4504.

**Comment by JRascagneres** [comment]
Thanks for the report. I've filed an issue for us to update these:

https://issues.couchbase.com/browse/CBG-1005

**Comment by bbrks** [comment]
CBG-1005 has been done - closing issue.
