### ISSUE TITLE
Client sent an HTTP request to an HTTPS server.

### ISSUE THREAD

**Issue by eadistar** [couchbase/sync_gateway#4721]
I have configured sync_gateway with ssl and i'm getting response 
Client sent an HTTP request to an HTTPS server.
can any tell me what am i missing?

**Comment by bbrks** [comment]
Hi @eadistar,

These types of questions are best left in the Couchbase Forums, where there are more people around to help you with your query.

https://forums.couchbase.com/c/mobile/sync-gateway/21 

But to summarise an answer, you need to connect to Sync Gateway with the `https://` protocol scheme from a client, and ensure all middleware (like proxies, load balancers, etc.) are configured for HTTPS and the correct port number.
