### ISSUE TITLE
Implement Mobile Convergence to enable Sync Gateway to directly access Couchbase Server buckets

### ISSUE THREAD

**Issue by jessliu** [couchbase/sync_gateway#473]
There have been several proposals to alternatives to bucket shadowing, with the essential goal to reduce the requirement for a shadow bucket, or reduce the amount of data needed in the shadow bucket. Setting a task for doing further research.

Need to identify:
- What alternatives can exist
- What would be needed by CBS team, if any
- What architecture changes would need to be introduced in SG, and what would those risks be

**Comment by adamcfraser** [comment]
Being addressed by the mobile convergence work.
