### ISSUE TITLE
Abort startup if shadow config uses same bucket as gateway bucket

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#476]
Several people have accidentally configured bucket shadowing with both the app and gateway bucket being the same bucket, causing the gateway not to work. We should detect this at startup and abort with a clearly-worded error message.

I'm setting severity to "major" because this is resulting in support requests, so it's obviously blocking the user and consuming time for us to answer the request.

**Comment by bbrks** [comment]
Closing as bucket shadowing is deprecated (and removed as of Mercury)
