### ISSUE TITLE
Implement Fast CGI support

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#480]
##### Use Case

As an enterprise user, I want to be able to integrate Sync Gateway into my existing web [farm] infrastructure, so that I can deploy and manage it using my existing systems & tools.
##### Acceptance Criteria
- Using `net/http/fcgi` allows SG to be integrated into any web [server|farm] that supports Fast CGI, which includes Apache, nginx, and IIS, among others.
- Include documentation on configuring using Apache, nginx, and IIS.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
