### ISSUE TITLE
Two similar environments resulting in pull replication fails with new clients in only one environment

### ISSUE THREAD

**Issue by jessliu** [couchbase/sync_gateway#488]
There has been a report of a pull replication from new clients added to a system are failing to complete, although in a similar (should be in theory, same except for a larger CBS backend cluster in the failing scenario) environment they are working just fine. Networking diagnostics confirm that there are no networking issues in the failing cluster, and turning off SSL did not improve the situation.

Full summary of the issue, as well as log files from Sync Gateway available here: https://www.couchbase.com/issues/browse/CBSE-1482

**Comment by zgramana** [comment]
@ajres we should add a note in the best practices guide relating to data center deployment notes.
