### ISSUE TITLE
Contradiction in Configuration File documentation in version 2.8

### ISSUE THREAD

**Issue by benjaminglatzeder** [couchbase/sync_gateway#4880]
[import_docs](https://docs.couchbase.com/sync-gateway/current/refer/config-properties.html#databases-this_db-import_docs)

> Starting in Sync Gateway 2.7, all Sync Gateway nodes can be configured as import nodes. This results in performance benefits as the import process is shared across all Sync Gateway nodes.
Prior to version 2.7, import_docs can only be set to true on a single node.

[enable_shared_bucket_access](https://docs.couchbase.com/sync-gateway/current/refer/config-properties.html#databases-this_db-enable_shared_bucket_access)

> enable_shared_bucket_access needs to be true on all nodes participating in such a configuration where as import_docs can only be set to true on a single node.

I think 

> import_docs can only be set to true on a single node

is no longer true for SG version 2.7 and up.

**Comment by adamcfraser** [comment]
That's correct - `import_docs can only be set to true on a single node` is no longer accurate for 2.7 and higher.  Thanks for flagging, will get that fixed.

**Comment by bbrks** [comment]
This still hasn't been fixed. I've filed a DOC issue for tracking:
https://issues.couchbase.com/browse/DOC-8036

**Comment by bbrks** [comment]
@benjaminglatzeder thanks for filing, this should be fixed now.
