### ISSUE TITLE
WebSocket authentication issue with Public REST API /{db}/_changes

### ISSUE THREAD

**Issue by matsunanaro** [couchbase/sync_gateway#4965]
### Sync Gateway version
2.8.1 Community

### Operating system
Mac 0S and Linux in general

### Use Case Scenario
I have an Angular web app using  Google Sign In. Here is the scenario.

1. Log in using Google Sign In.
2. Post the SyncGateway Public REST API /{db}/_google with the token obtained in 1.
3. The SyncGateway returns successfully with 200 and a Set-Cookie SyncGatewaySession=some_string
4.  Establish a WebSocket connection directly by using the WebSocket API e.g.

var exampleSocket = new WebSocket("ws://${my_syncgateway}/${db}/_changes?feed=websocket");

### Expected behavior

The WebSocket will be established based on the assumption that the cookie is automatically set by the browser.

### Actual behavior

The SyncGateway would refuse the connection because of missing cookie. A modern browser such as Chrome will not set any cookie if the HTTP request is a UPGRADE, which is  probably because there is a known security issue when using session cookie for WebSocket authentication/authorization. See this [link](https://christian-schneider.net/CrossSiteWebSocketHijacking.html) by Christian Schneider  for more details

### Suggestion

Defer the authentication after the HTTP connection is established/upgraded, using a subprotocol or simply adding a new  gateway_session parameter as with the other existing parameters.

**Comment by bbrks** [comment]
Hi @matsunanaro 

We've filed an issue over on our Jira to track a non-HTTP-based authentication mechanism on the websocket API.

https://issues.couchbase.com/browse/CBG-1328

**Comment by adamcfraser** [comment]
Closing here, tracking with the JIRA issue linked above.
