### ISSUE TITLE
Please add go module support

### ISSUE THREAD

**Issue by roopakv** [couchbase/sync_gateway#4967]
This tool is installable via brew. Please add go module support in order to make maintenance easy and support go 1.17

https://github.com/Homebrew/homebrew-core/pull/71289

**Comment by bbrks** [comment]
It's something we're looking at doing eventually. But we have a lot of non-Go build processes inside Couchbase using the repo/manifest that we need to make sure are lined up for building Sync Gateway with modules first.

**Comment by bbrks** [comment]
Tracking via CBG-1851

**Comment by bbrks** [comment]
@roopakv Sync Gateway 3.0.0 and later are now built using Go modules
