### ISSUE TITLE
Revision pruning isn't effective when history includes conflicts (even when tombstoned)

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#501]
Issue originally raised as followup to https://github.com/couchbase/couchbase-lite-ios/issues/509.  Crux of the issue is that tombstoned conflict branches are preserved during revision pruning, so documents with many (resolved) conflicts result in very large document bodies.

**Comment by sapieneptus** [comment]
Hey @adamcfraser - any update on a potential workaround for this?

**Comment by snej** [comment]
Hey @sapieneptus: I'd like to see why SG reports no conflicts. Could I see a JSON dump of the doc as stored in the SG bucket, including the `_sync` property? (Actually the `_sync` property is all I need to see, in case the doc body is sensitive.) Thanks!

**Comment by snej** [comment]
@sapieneptus: Never mind! After re-familiarizing myself with the issue I understand why it's going on. The patch I just submitted for review should fix it.

**Comment by sapieneptus** [comment]
Thanks so much @snej ! I'll look into the patch as soon as I can and let you know if it doesn't clear it up.
