### ISSUE TITLE
Feature Request:  Oauth2 Support

### ISSUE THREAD

**Issue by WilliamHoang** [couchbase/sync_gateway#508]
Feature Request:  Oauth2 Support

Scenario:
Provide support for social network login and sync functionality based on session/token

Links:
https://dev.twitter.com/oauth/overview
https://developers.facebook.com/docs/android/login-with-facebook/v2.2

@adamcfraser Would this be possible and what the necessary components needed?

**Comment by zgramana** [comment]
OAuth2 is frequently used as a bridging protocol used to implement federated identity with existing (and often complex) authentication systems. Social providers are among them, but there's also wrapping OAuth2 around Active Directory, for example, or a custom Java SSO system built in-house.

**Comment by adamcfraser** [comment]
Closing, as will be delivered via OpenID Connect support in 1.3.
