### ISSUE TITLE
Gateway runs out of memory every few hours and gets killed

### ISSUE THREAD

**Issue by nl** [couchbase/sync_gateway#509]
Not sure if my machine needs more RAM (it has 8 GB and Couchbase Server / Sync Gateway are the only processes running) or if there are memory leaks in 1.0.3, but SG crashes every few hours.

https://gist.github.com/nl/37d5e553da7851e71c05

**Comment by nl** [comment]
CBS 3.0.2 didn't change anything, but I can add to this ticket that the problem only seems to happen when a document in the database has several thousand revisions.

**Comment by zgramana** [comment]
Possible golang GC issue. Will need to revalidate against the forthcoming build against Go 1.4.

**Comment by nl** [comment]
This still happens on a daily basis. Here's another log. This is even after updating the machine with 16 GB RAM, with sync_gateway as the only custom service running. https://gist.github.com/nl/943bcc6b40b62e9151ce

**Comment by zgramana** [comment]
@nl do you have any load balancers active in your deployment? If so, please list make/model/version.

**Comment by zgramana** [comment]
Consolidating into #768.

**Comment by nl** [comment]
I haven't setup any load balancers, nope

**Comment by zgramana** [comment]
@nl can you help us reproduce this issue by completing this questionnaire: http://goo.gl/forms/2exqyyY2kP? Cheers!

**Comment by hegra** [comment]
We have similar issues. A few hours of running sync gateway eats 3 GB of memory and a restart of sync gateway is needed.

Running the following version https://aws.amazon.com/marketplace/pp/B00FA8DO50 on single m1.medium instance. Also upgraded sync gateway to master(bfb402f) but no noticeable difference.

5 android clients connected with continuous sync in push mode. Documents of around 100kb. Documents updated a few times every minute.

**Comment by ajres** [comment]
Are you running any pull replications during this test or is it purely push?

Andy

Sent from Outlookhttp://taps.io/outlookmobile
