### ISSUE TITLE
Log warning for docs missing _sync property

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#514]
From Skype discussion: 

> @snej That sounds pretty easy — just have the Tap handler check whether it's a regular document (ID doesn't start with _sync) but it has no _sync property. Then log a warning.

Related to https://github.com/couchbase/couchbase-lite-android/issues/466#issuecomment-65692081

**Comment by adamcfraser** [comment]
This looks like it's already in place:
https://github.com/couchbase/sync_gateway/blob/master/db/change_cache.go#L327
