### ISSUE TITLE
Fail to warn when sync_gateway user does not exist

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/sync_gateway#520]
When user account for sync_gateway does not exist, the service install script is supposed to give warning, but instead, it give a misleading message:

ackee-s20130:/opt/couchbase-sync-gateway/service # ./sync_gateway_service_install.sh
./sync_gateway_service_install.sh: line 130: [: missing `]'
The runtime base directory does not exist "/home/sync_gateway".

The error is coming from the following:

if [ "$OS" != "Darwin" && -z `id -u $RUNAS_TEMPLATE_VAR 2>/dev/null` ]; then
    echo "The sync_gateway runtime user account does not exist \"$RUNAS_TEMPLATE_VAR\"." > /dev/stderr
    exit 1
fi

When the user account exists, the script runs ok.

**Comment by ajres** [comment]
PR #1249 auto installs an init service and will create the sync_gateway suer account if it does not already exist.

Closing this ticket out.
