### ISSUE TITLE
Parameter parsing problem in sync_gateway_service_install.sh 

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/sync_gateway#529]
Got this error when specifying a parameter for the service install script:
gateway_1:/root # /opt/couchbase-sync-gateway/service/sync_gateway_service_install.sh --runbase /opt/couchbase-sync-gateway
ERROR: unknown parameter "/opt/couchbase-sync-gateway"

The reason is that the second parameter, /opt/couchbase-sync-gateway, is considered beginning of another key value pair.   To fix it, some key value pairs needs to have two "shift" in the loop to process command line arguments, and some only need one "shift".

Another observation, the help text is not formatted correctly.   It should have tab instead of "/t' in front of each paramters:
\t-h --help
\t--os : Manually set the target OS for the service <Ubuntu | Redhat >; default (auto detected)
\t--ver : Manually set the target OS version; default (auto detected)
\t--runas : The user account to run sync_gateway as; default (sync_gateway)
\t--runbase : The directory to run sync_gateway from; defaut (/home/sync_gateway)
\t--pidfile : The path where the .pid file will be created; default (/var/run/sync-gateway.pid)
\t--sgpath : The path to the sync_gateway executable; default (/opt/couchbase-sync-gateway/bin/sync_gateway)
\t--srccfgdir : The path to the source sync_gateway JSON config directory)
\t--srccfgname : The name of the source sync_gateway JSON config file)
\t--cfgpath : The path to the sync_gateway JSON config file; default (/home/sync_gateway/sync_gateway.json)
\t--logsdir : The path to the log file direcotry; default (/home/sync_gateway/logs)
\t--servicename : The name of the service to install; default (sync_gateway)

**Comment by ajres** [comment]
Actually the issue here was that the parameter name and value need to be separated by '=' not ' ', removed additional shift and added better notes about usage.
