### ISSUE TITLE
external sync functions

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#53]
It should be possible to run the sync function via an external process that speaks to the server via stdio or sockets.

The config file would specify a process to launch, instead of a sync function body. Then the server would launch that process and send documents to it, and expect JSON responses (either a list of channels and access grants, or a validation error).

**Comment by adamcfraser** [comment]
May be revisited as part of https://issues.couchbase.com/browse/CBG-445 - closing here.
