### ISSUE TITLE
sync_gateway_service_install.sh should be executable after installation on Ubruntus

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/sync_gateway#532]
After installation, the file sync_gateway_service_install.sh is not executable during pre-released testing with 1.0.4-7.   This is observed on ubuntu12 and 14, both 32 bit and 64 bit versions.   

-rw-r--r-- 1 couchbase couchbase 6.4K Dec 19 08:07 sync_gateway_service_install.sh

It should be the same as on Centos like the following:
-rwxr-xr-x. 1 bin       bin       6.4K Dec 19  2014 sync_gateway_service_install.sh

**Comment by ajres** [comment]
Ubuntu issue should be fixed by setting file permissions in the package post install script
