### ISSUE TITLE
sync_gateway_service_install.sh should explicitly state that command-line arguments require an '=' before the value

### ISSUE THREAD

**Issue by vfleurima** [couchbase/sync_gateway#535]
I just spent more time than I'd like to admit running into this issue:

```
root@couchbase:/home/sync_gateway/sync_gateway/service# ./sync_gateway_service_install.sh --sgpath /home/sync_gateway/sync_gateway/bin/sync_gateway --cfgpath /home/sync_gateway/config.json 
ERROR: unknown parameter "/home/sync_gateway/sync_gateway/bin/sync_gateway"
```

After perusing the source of the shell script, I figured out that the command-line arguments required an '=' before the value:

```
root@couchbase:/home/sync_gateway/sync_gateway/service# ./sync_gateway_service_install.sh --sgpath=/home/sync_gateway/sync_gateway/bin/sync_gateway --cfgpath=/home/sync_gateway/config.json 
```

I think this should be made explicit somehow. Perhaps it's as simple as adding example usage to the script and README. I feel that with double-dash command line arguments, utilities on Linux don't consistently use '=' or ' ' to indicate values (e.g. http://linuxcommand.org/man_pages/tar1.html) so there's value in being explicit.

**Comment by ajres** [comment]
Updated cli usage and README to show parameter format with '=' separator

**Comment by vfleurima** [comment]
Great!
