### ISSUE TITLE
The script to install sync_gateway service on windows should not be a shell script

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/sync_gateway#536]
After I install SGW on 64 bit windows, including Windows 8 64 bit and windows 2012 R2 64 bit, the only script that is related to installing service is the following:
c:/Program Files (x86)/Couchbase/examples/service/Sync_gateway_service_install.sh 

It is a shell script that can not be ran on windows.   The packaging of the installer may include a wrong file with the window installers.

**Comment by ajres** [comment]
Windows is out of scope for the service installation script, this should not be included in the Windows packaging.
