### ISSUE TITLE
64 bit sync_gateway should not be installed under c:/Program Files (x86)

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/sync_gateway#538]
After I install SGW on 64 bit windows, including Windows 8 64 bit and windows 2012 R2 64 bit, it is install on "c:/Program Files (x86)" folder, which conventionally is for 16 bit applications.  It should be installed on "c:/Program Files".   

 This is also to be consistent with Couchbase server on windows, which is a 64 bit app installed under "c:/Program Files".

**Comment by ajres** [comment]
Added additional Install shield .ism configuration for 64-bit builds

**Comment by ajres** [comment]
The new configuration used by the SG build scripts.
