### ISSUE TITLE
Support for custom Persona verifiers

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#54]
Currently the persona Verifier service URL is hardcoded, supporting a custom verifier URL per DB in a .conf file would provide a flexible integration point for identity/CRM management systems.

These systems could implement features such as, email blacklists, whitelists, subscription validation e.t.c

A custom verifier would have to implement the same API as the default Mozilla service.

**Comment by adamcfraser** [comment]
Closing based on current Persona status.
