### ISSUE TITLE
On windows plateforms, README.md under service directories should be renamed to README.txt

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/sync_gateway#540]
Those two README.md files are not readable by default on the windows.   They should be renamed to README.txt.
c:/Program Files (x86)/Couchbase/examples/service
c:/Program Files (x86)/Couchbase/examples/ssl

The README file at c:/Program Files (x86)/Couchbase is already named correctly as README.txt.

**Comment by ajres** [comment]
Added a plain text README.txt to the services folder for Windows packages
