### ISSUE TITLE
Copyright statement in all LICENSE.txt needs to be updated

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/sync_gateway#542]
LICENSE.txt in all the installers need to update the Copyright from 

```
Copyright 2011 Couchbase, Inc. 
```

to 

```
Copyright 2015 Couchbase, Inc. 
```

**Comment by ajres** [comment]
Updated and created PR https://github.com/couchbase/build/pulls, I can't merge this myself as I don't have permissions on that repo

**Comment by tleyden** [comment]
@ajres that repo is managed by Gerrit.  I'll send out an email.

**Comment by ajres** [comment]
Gerrit issue raised and Michael Kwok added as a reviewer

**Comment by ajres** [comment]
Approved by Michael Kwok
