### ISSUE TITLE
Sync Gateway doesn't work with _doc_ids filter / Can't sync individual docs

### ISSUE THREAD

**Issue by ghost** [couchbase/sync_gateway#545]
Greetings,

When trying to sync specific docs down to a client, the sync request fails with 400 bad_request in the ios logs and a "400 Unknown filter; try sync_gateway/bychannel" on the server logs. 

From what I can tell, if you set the replicationObject.documentIds, the ios framework automatically sets a filter of "_doc_ids" and adds a doc_ids : <list of doc ids> to the post body. When the sync_gateway receives the request, it forwards it to the changeHandler which looks for the filter "sync_gateway/bychannel", but the filter is "_doc_ids" so it fails every time.

iOS code:
NSURL _syncURL = [NSURL URLWithString:@"http://Justins-MacBook-Pro.local:4984/sync_gateway_sw1/"];
CBLReplication_ repl = [self.database createPullReplication:syncURL]
repl.customProperties = @{@"websocket": @NO};
repl.continuous = NO;
repl.credential = loginCredential;
repl.documentIDs = @[@"14113462-a04a-4abf-9271-1d14b83f8329", @"5afe4a8a-1285-47bb-9470-bc8e0f7a96fb"];
[repl start];

Url request (POST body is not printed):
19:07:27.358‖ SyncVerbose: CBLSocketChangeTracker[0x7fb4820709e0 sync_gateway_sw1]: POST //Justins-MacBook-Pro.local:4984/sync_gateway_sw1/_changes

sync_gateway log:
00:07:27.371608 HTTP:  #001: GET /sync_gateway_sw1/_local/1896507b56b329ad336f8618b5700becec31ae4c  (as justin.camp)
00:07:27.372263 HTTP: #001:     --> 404 missing  (129.4 ms)
00:07:27.411767 HTTP:  #002: POST /sync_gateway_sw1/_changes  (as justin.camp)
00:07:27.411988 HTTP: #002:     --> 400 Unknown filter; try sync_gateway/bychannel  (0.9 ms)

Am I missing something? As far as I can tell I can't even find any code to deal with doc_ids in the sync_gateway at all.

Thanks!
Justin

**Comment by snej** [comment]
Adam's right — the implementation of the `_changes` feed in `rest/changes_api.go` doesn't recognize the `doc_ids` pseudo-filter. I think this is something we should implement, and not just for compatibility — it's often useful on the client side to pull a specific set of documents.

**Comment by jchris** [comment]
The use cases for this are powerful. For instance you can have a graph-based document loading approach, and do prefetching however N levels deep you want, etc.

**Comment by push-build-user** [comment]
+1 for this. Our clients generate a lot of data and we need more fine grained filtering. We tried implementing time based filtering with channels but it turns out if too many users have access to too many channels (over 10) sync gateway will no longer function. It will run incredibly slowly and keep using more RAM until it crashes the server. This was with sync gateway v1.1.0.

**Comment by cujo** [comment]
+1. Very useful for me too. Pulling all user's docs at once with initial sync in some cases takes much time and using channels causes thousands of them for each of thousands users. Syncing docs by id on demand will be a perfect solution. And it should be implemented in the way when user can synchronize by ids only those docs he has access to with channels.

**Comment by tleyden** [comment]
@zgramana / @adamcfraser moving this over to incoming so we discuss in the next sprint planning about making this a priority.

**Comment by adamcfraser** [comment]
Sure.  I think the main enhancement around docID filtering will primarily be around continuous/longpoll _changes handling.  One-shot _changes should be straightforward, but we don't have any optimized way to do docID based filtering while watching for new mutations.  We could do the usual channel-based changes and then filter by docID, but need to evaluate whether that addresses the use case. It might address part of the problem (avoiding large sync of older data).

**Comment by snej** [comment]
I think most of the use cases for this will be one-shot pulls, i.e. not using longpoll or continuous mode. So if you did a first-pass implementation that only handled one-shot and returned a 5xx status for other modes, it would still be a big win.

**Comment by elevine** [comment]
+1.  In our case, as deletions build up it causes the first sync to take a long time.  Our current attempt to workaround is to retrieve docs directly through the REST API and insert them into CBL, then startup the continuous pull replicator. If a one-shot replicator supported the doc_ids filter, we could achieve the same results.  For my case, it would be more convenient to be able to filter out deletions instead of having to specify all the doc ids.  

Also, since the Sync Gateway now supports user facing Views, would it be possible to get filtered pull replications as described here for other servers: http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/couchbase-lite/native-api/replication/index.html

**Comment by ajres** [comment]
Initially will limit the scope of this feature to one-shot pull replications only, as this is the primary use case and will not require major redesign of the change feed code.

**Comment by elevine** [comment]
Do you have an approximate time frame for when this feature might get completed and merged into master?  It would help me to decide if I can wait for it or need to implement a workaround.

**Comment by ajres** [comment]
@elevine

This is in the current sprint, so will be worked on this week.

**Comment by ajres** [comment]
Do we want to support the _doc_ids filter for GET requests, the practical number of doc_ids that can be passed will be limited. POST requests are preferable as they can support a large number of doc_ids.

**Comment by adamcfraser** [comment]
We'll want to support both GET and POST, the same way we do for the bychannel filter.

**Comment by elevine** [comment]
Are there any updates regarding the ETA of this?  Thank you.

**Comment by ajres** [comment]
This ticket is schedule to be completed on this weeks sprint.

**Comment by kirtan403** [comment]
Where can I find documentation for this as it is already released in Couchbase Lite 1.2 ??

**Comment by snej** [comment]
Until our docs are updated, you can look at the [CouchDB documentation](http://docs.couchdb.org/en/latest/api/database/changes.html) of this. The significant stuff on that page is where it talks about the "docIDs filter".

**Comment by NitzDKoder** [comment]
@snej filter by docid works from CBL now?
