### ISSUE TITLE
Gateway panic

### ISSUE THREAD

**Issue by nl** [couchbase/sync_gateway#555]
Under heavy load, the gateway crashes. Can anyone decipher this crashlog and help me make sense of it?

https://gist.github.com/nl/c71823832407aa6f4b6e

**Comment by tleyden** [comment]
Here is the line that is panicking: https://github.com/couchbase/sync_gateway/blob/release/1.0.3/src/github.com/couchbaselabs/sync_gateway/rest/handler.go#L443

And what looks suspicious is how many "possible_ancestors" there are here:

https://gist.github.com/nl/c71823832407aa6f4b6e#file-gistfile1-txt-L4

@nl is thus under a real load or a simulated load?  Anything you can provide that we can run to repro this would be super helpful.

**Comment by nl** [comment]
This is under real load. Not particularly heavy use either, but I think a couple clients are maybe contending trying to solve conflicts on a few documents, and iterating revisions rapidly. What could I provide to help out?

Btw, I think this might be the same issue as https://github.com/couchbase/sync_gateway/issues/509

**Comment by nl** [comment]
For now, restarting the gateway whenever this happens is the best workaround I found - every replication seems to resume normally.

**Comment by zgramana** [comment]
Marking this issue for revisit after the upcoming release against Go lang 1.4.

**Comment by adamcfraser** [comment]
The original panic while shadowing has since been fixed (by https://github.com/couchbase/sync_gateway/pull/1617)
