### ISSUE TITLE
Add an admin API to erase/flush a database

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#558]
For testing purposes it's very useful to be able to erase a Gateway database. F'rexample, the Couchbase Lite push-replication tests need this — the database they push into has to be in a known state before the test, without any of the docs that are about to be pushed.

This request has also come up during hackathons.

The API would probably look like a POST to `/db/_flush`, since "flush" is the terminology used in Couchbase Server for this.

**Comment by tleyden** [comment]
Just curios, why is it walrus only? (I thought I heard you say that at least)

**Comment by snej** [comment]
I've only implemented it for Walrus so far, because that's what I need for the Couchbase Lite unit tests. (The tests need databases to replicate with, and need to be able to erase them before pushing.)

Implementing this for Couchbase Server would just mean adding the `CloseAndDelete` method to its Bucket implementation, probably in base/Bucket.go. (Or maybe it should be implemented down in go-couchbase?)

**Comment by zgramana** [comment]
Probably should make this a two-step process, where the first call returns a token on CBS bucket, and a second call with the token actually does it. This can be wrapped in a nice UI once we have an admin console.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.  In general flush on a Couchbase Server bucket is not something we want to make available via Sync Gateway's API, and so this would be walrus-only functionality.
