### ISSUE TITLE
Document SG performance metrics

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#586]
Update and review Sync Gateway performance metrics and current results sets.

**Comment by tleyden** [comment]
This [perfrunner test run](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/567/artifact/gateway_expvar_1.json) is jumping out as being particularly bad:

```
lag-tap-225100ms: 141,
lag-tap-225200ms: 145,
lag-tap-225300ms: 153,
lag-tap-225400ms: 156,
lag-tap-225500ms: 118,
lag-tap-225600ms: 137,
lag-tap-225700ms: 151,
lag-tap-225800ms: 134,
lag-tap-225900ms: 137,
lag-tap-226000ms: 125,
```

This means that 141 documents had a "tap lag" -- the round trip time it took for a Sync Gw to write the doc to Couchbase Server and then receive it on its own tap feed -- of  225.1 seconds.  (nearly 4 minutes)

Likewise, 145 docs had a tap lag of 225.2 seconds.

Also noteworthy in those stats is `view_queries: 963`.  I think it's possible that the view queries are putting a heavy strain on couchbase server, such that they cause the tap lag to skyrocket.

**Comment by zgramana** [comment]
Create a list of new metrics that need to be collected, and a list of tests that can supply the raw data.

**Comment by tleyden** [comment]
Tracking investigation progress in https://github.com/couchbase/sync_gateway/issues/781

**Comment by tleyden** [comment]
Document deliverable:  

what we'd like to have vs what we have
- CPU usage
- Memory usage
- Round trip latency time
- Etc

**Comment by zgramana** [comment]
- EXVARs
- SG logs
- CBS logs

**Comment by zgramana** [comment]
@tleyden please update.

**Comment by tleyden** [comment]
## Server Side Metrics
- Number of goroutines (to detect excessive goroutine explosion bugs)
- GC pause length and frequency
- Estimated round trip latency
- Rev cache misses
- Number of view 
- go-couchbase warnings are good metric

## Client Side Metrics
- Round trip latency time between a document being saved and showing up on the _changes feed

**Comment by tleyden** [comment]
First pass is here: https://github.com/couchbase/sync_gateway/wiki/Performance-Metrics

We should treat this as a "living document" and keep it updated as we discover new metrics
