### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#60]
the admin port :4985 should have an Admin UI for editing the sync function, browsing users, inspecting channels, etc.

**Comment by jchris** [comment]
BTW the code for this lives here https://github.com/couchbaselabs/sync_gateway_admin_ui

**Comment by adamcfraser** [comment]
Actively being worked on here: https://github.com/couchbaselabs/sync_gateway_admin_ui - tracking ongoing development in that repo.
