### ISSUE TITLE
Should there be restrictions on character set of usernames?

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#602]
In the course of [this thread](https://groups.google.com/d/msgid/mobile-couchbase/3a599b21-5bbe-4836-8b9e-8d122fd0b08f%40googlegroups.com) I looked for the code in SG that validates usernames … but I couldn't find any. So it appears that an admin can create a user account with any possible string of characters for a name. Seems like that might be a bad idea.
1. A very long username will cause errors saving the user document, due to exceeding CBS's maximum key length (about 256 I think.)
2. An app server or other software that uses usernames might have trouble with crazy usernames like `bobby<script>alert("pwned!")</script>` ...

Apparently the REST docs say

> name: The user name (the same name used in the URL path). The valid characters for a user name are alphanumeric ASCII characters and the underscore character. The name property is required in a POST request. You don't need to include it in a PUT request because the user name is specified in the URL.

so either the implementation or the docs need to change :)

**Comment by atkit** [comment]
+1 for usernames validation on SG side. As I think everything that come to API needs to be properly validated.

**Comment by elevine** [comment]
When I first read the documentation, it seemed that the username requirements were too restrictive.  If the server is going to do some validation, it should at least allow valid email addresses.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case (particularly given the need for backward compatibility).
