### ISSUE TITLE
Persist changes made via the Admin API

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#608]
As a sync gateway user, I want to make changes via the Admin REST API and have sync_gateway use resume operation using those values when the process next starts up so that I can remotely manage its configuration without having to create a custom configuration server.

Acceptance Criteria:
- Default implementation persists changes in a durable medium (e.g. Walrus).
- If user adds configuration server, then remote config takes priority.
- Configuration errors prevent SG from starting. Warnings are clearly logged to the console.
- Implement an interface to allow multiple persistence strategies. Only one strategy should be active at a time.
- Needs to scale to 100,000 database configurations with reasonable performance.
- Should continue to support reading JSON config from the command line, and should also support flushing the running config to disk as a JSON config file.

**Comment by adamcfraser** [comment]
Closing based on age, needs to be considered in the context of centralized config management.
