### ISSUE TITLE
Enable XSRF token support

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#609]
In order to provide enhanced security around implementing CORS support, need to enable XSRF request token support. This prevents a malicious website on a CORS whitelist from hijacking a user's session. 
#### Notes
- CouchDB doesn't currently support this, though [a proposal to was made previously](https://gist.github.com/sbisbee/817490).

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
