### ISSUE TITLE
"Verbose" flag for log topic config

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#610]
It would be cool if there was a way to turn on all logging without listing every log tag. Forward compatible with new log tags, etc...

This way test automation can use this flag and developers will always have useful logs when tests fail.

**Comment by jchris** [comment]
The big thing this helps with is log topic name discovery, since your next best bet is to grep the source base for logging calls and see what's being used.

**Comment by tleyden** [comment]
We should add this to the documentation.  Re-opening as a reminder.

**Comment by JeffThomasWriter** [comment]
Add what to the documentation? This requires implementation first. True?

**Comment by adamcfraser** [comment]
The previous comment was about documenting the `*` log key.  You've already got that covered in your update to the config docs, I believe.

**Comment by JeffThomasWriter** [comment]
Documented for log in configuration parameters:Use ["*"] to enable logging for all log keys.
