### ISSUE TITLE
Add integration test for logfile rollover

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#614]
Log file rollover involves the OS runtime, need an integration test to give proper coverage

**Comment by tleyden** [comment]
Another option -- can't we leverage an existing tool for log rolling that has it's own test suite?  

If we write this ourselves, it feels like it should be made generic and factored out into its own project / repo.

**Comment by zgramana** [comment]
@andreibaranouski please update.

**Comment by tleyden** [comment]
This still feels strange to me to have log file rollover built right into sync gateway, rather than delegating that to a 3rd party tool such as `logrotate`.  If we did that, we could throw about a bunch of things we have to maintain:
- Code
- Tests
- Docs (assuming we have it)

Not to mention we could throw away this ticket.

@ajres / anyone: do you remember the rationale behind this decision?

**Comment by ajres** [comment]
The default behaviour of log rotation tools is to rename the default log file with a timestamp when rollover is triggered. The generating app is expected to create a new default log file and log to that.

SG will follow the file handle and will keep writing to the timestamped file and does not create a new default log file.

The log rotation tool can use a second technique, when triggered the default log file is copied to a timestamped log file, then the default log file it truncated to zero bytes. The generating app is expected to continue writing to the truncated default log file.

In this case SG will continue to write to the truncated log file as expected. However the copying and truncation actions are not atomic and on a loaded SG instance there is the potential to loose multiple log entries.

If loosing log entries is acceptable option 2 can be used with SG without passing additional parameters.

For systems where information loss is not acceptable option 1 must be used and SG must be an active participant in the rollover process.

SG has been extended to support the HUP system signal, on receipt of HUP SG will close the current log file and then reopen it.

This log file must be directly opened by SG so that it can do a close on the file handle and flush any buffers to the file. To support this SG requires an explicit configuration parameter.

SG can not close the stout or stderr passed to it's process as SG does not own the file handles these are owned by the launching batch script. Closing and opening stdout and stderr in SG just reconnects to the same file handles and SG will continue to write to the same default log file.

**Comment by krugster** [comment]
The field would also request that we provide configuration availability of whatever log rotation mechanism we employ in terms of log file size and time duration

**Comment by zgramana** [comment]
@krugster that would be done via the `logrotate` configuration. The issue @ajres is discussing has to do with how Sync Gateway behaves when a tool like `logrotate` is run. We enabled compatibility, but Andy brought up an issue whereby SG can lose log entries that are in-flight during the rotation process. I'll create a new ticket to track that.

**Comment by adamcfraser** [comment]
Will get handled in the context of planned log rotation improvements.
