### ISSUE TITLE
Documents written by Sync Gateway appear in 2-second clusters on the TAP feed

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#616]
Looking at the timestamps for incoming events on the TAP feed, they are showing up in buffered sets, 2 seconds apart.

Original issue here:
https://forums.couchbase.com/t/how-to-deal-with-sync-gateway-couchbase-server-tap-notification-delay/2644/

I was able to replicate this in a local environment (running gateload against my local instance) - timestamps for incoming TAP entries look something like this when listening to a TAP feed that should be sending continuous updates:

10:53:22.187906 
10:53:22.188207 
… 50 more updates …
10:53:22.203737
10:53:24.186818             <— 2 sec jump
10:53:24.187307 
10:53:24.187607 
… 50 more updates…
10:53:24.201941 
10:53:26.187628            <— 2 sec jump
10:53:26.187723 
10:53:26.187864 
…

I don't see the same results when using something other than sync gateway to write the records.  When using the go-couchbase populate.go to write to the server, the events showing up on the SG tap feed are evenly distributed.  Based on this it seems like something in the way SG is doing writes.  Needs followup to get to the root cause.

**Comment by adamcfraser** [comment]
This has been reported again on ticket #2094.  Summary of the issue again:
- When writes are done through Sync Gateway, items show up on the TAP feed in chunks, with a batch every 2 seconds
- When writes are done using something other than Sync Gateway, items on the TAP feed are evenly distributed

For review:
- Does the same behaviour occur when using the DCP feed?
- What's different in the way SG does writes, vs. populate.go

**Comment by paulharter** [comment]
Good that it's not on the read side as I guess changing things there there are more involved. 

It would be nice to get to the bottom of this as saving 2 secs on the latency would in some cases make a big difference. I'll have another look at it later in the week.

Thanks

**Comment by paulharter** [comment]
@adamcfraser @snej 

I've had another look at the buffering this morning. I've done a few more functional tests and am consistently getting this 2 seconds of additional latency, but have found no helpful hints as to why.

Logging "bucket" writes it looks like Sync Gateway thinks it has completed its write to Couchbase before the buffering takes place. (I may be wrong about this as I don't know my way round the code). So if Sync Gateway is not buffering on write and, as you say above, docs added other ways are not buffered by Couchbase, then maybe Couchbase is selectively buffering docs from sync gateway!

Do you have performance tests for sync gateway that capture latency? Maybe I'm only seeing this as an artifact of the way I'm testing, on a laptop, one client and few docs. I noticed that the SG ftests do have a 2000ms timeout for a similar test.

I don't know how to proceed with debugging so I'm going to leave this for now.

Can I +1 this issue. It seems like a more important problem than its current prioritisation allows, and if fixable the performance gains are quite large. 

P

**Comment by elevine** [comment]
@paulharter I've done some testing previously and noticed similar latency, however it doesn't seem to happen when you use the walrus database with Sync Gateway instead of Couchbase.

**Comment by paulharter** [comment]
@elevine so something in Couchbase looks likely. Maybe a text search for "2000" in couchbase code would turn something up.

**Comment by paulharter** [comment]
libmemcached has a 2000ms timeout in a function memcached_purge which looks like its might be causing this.

https://github.com/trondn/libmemcached/blob/master/libmemcached/purge.c

 line 47

@trondn might writes to sync gateway changes feed be being batched up by this timeout?

**Comment by adamcfraser** [comment]
@paulharter Given that this isn't seen when writing directly to the bucket (as mentioned above regarding populate.go), it's possible that there's still something specific to the way Sync Gateway is doing updates that's resulting in the feed latency.  There are a few possibilities - including the incr operation required to allocate a sequence number, the initial GET required to manage revision history.

We're in the process of moving Sync Gateway to use Couchbase Server's DCP feed (instead of only TAP).  I'm planning to review whether the same issue occurs when using DCP.

**Comment by paulharter** [comment]
@adamcfraser thanks for the update. Hopefully the feed change will sort it out.

**Comment by mdcw** [comment]
+1

**Comment by paulharter** [comment]
@adamcfraser 

Just to let you know that using DCP does seem to fix this. In my tests the buffering has gone now. This is using a build I made this morning. 

Couchbase Sync Gateway/HEAD(nobranch)(2ba7a5c)

with CB 4.5.0

This is big deal to me as I'm using _changes rather than webhooks.

Will using DPC be enabled in 1.4.0?

**Comment by adamcfraser** [comment]
@paulharter Thanks for the update!  Yes, DCP will be re-enabled in 1.4.0 , although it's not yet the default feed - you'll need to set the feed type in the config.

**Comment by adamcfraser** [comment]
DCP is used for mutation feed in 1.5 and later.
