### ISSUE TITLE
Excessive sporadic GC during perf run

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#617]
In [perf run 589](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/589/), I observed the following errors repeated in the gateload logs:

```
2015/01/28 16:35:07 WARNING: Network error: Post http://172.23.96.66:4984/db/_revs_diff?n=1196073: dial tcp 172.23.96.66:4984: connection timed out for http://172.23.96.66:4984/db/_revs_di
2015/01/28 16:35:07 #1196073:   <-- Network error: Post http://172.23.96.66:4984/db/_revs_diff?n=1196073: dial tcp 172.23.96.66:4984: connection timed out (2562047h47m16.854775807s)
```

Immediately after seeing these, I tried to issue the following curl request from the gateload ssh terminal:

```
curl http://172.23.96.66:4985/db/
```

and it hung for a few minutes, until finally I Ctl-C'd it.  Likewise, I went to http://172.23.96.63:9876/debug/vars in my browser, which did not respond either.  I tailed the logs, and nothing was coming out.

When I ran `top`, this is what it showed:

```
244907 root      20   0 8860m 6.7g 3788 S 54.5 87.7 108:16.19 sync_gateway
```

[full top snapshot here](https://gist.github.com/tleyden/6849c242a1aecb885820)

After a few minutes in this totally wedged state, all of the sudden things resumed to normal. 

I checked the sync gateway expvars and confirmed that there were reported tap-lag times of ~360 seconds:

```
lag-tap-362100ms: 48
```

**It felt like it was stuck in a massive stop-the-world GC.**

**Comment by tleyden** [comment]
Todo: investigate memory stats and GC pauses recorded in the expvar output.

**Comment by zgramana** [comment]
Also reminds me of I/O thread starvation.

**Comment by tleyden** [comment]
There is a GC pause recorded in the expvar stats that is [262551391172 nanoseconds](https://gist.github.com/tleyden/012099081ae6e6cc6db1#file-gistfile1-txt-L69) (262.55 seconds)

**Comment by tleyden** [comment]
Note to self: [expvar stats](https://gist.github.com/tleyden/e2d498b946a702d18d72) for one of the gateload processes (just wanted save this for record keeping purposes) since it wasn't attached to the job results.

**Comment by zgramana** [comment]
Wow, 265 seconds. I bet the Go team would want to talk to you about that. ;)

Have you seen golang/go/issues#9477?

**Comment by adamcfraser** [comment]
I was just looking at the golang-nuts thread that inspired that issue as you sent that, Zack.
https://groups.google.com/forum/#!topic/golang-nuts/baU4PZFyBQQ

I didn't think we had any gigantic maps (with millions of entries) - mainly small-to-medium maps, like the map of 10,000 channel caches, the 5000 entry revision cache – but then I noticed:

https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbaselabs/sync_gateway/db/change_cache.go#L247

which looks like a candidate for review.  That's going to have an entry for every sequence seen on the TAP feed by the SG, if I'm reading it correctly.

Adam

**Comment by tleyden** [comment]
I was able to reproduce it again in [perf run 596](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/596/), and capture heap profiling data this time.

There were GC pauses upwards of 225 seconds.

Due to a perfrunner bug, the expvar data did not make it into the artifacts, so I'm posting it here:
- [sync gw expvar 172.23.96.66](https://gist.github.com/tleyden/bffc2b0e65fe63055e0c)
- [gateload expvar ](https://gist.github.com/tleyden/9f3140e6c5c6b7c607c8)

The memory profiles are attached to the build in profiling_1.tar.gz, and they must be viewed on Linux using Go 1.2 and compiling sync gateway from the release/1.0.4 branch.

Here is a snapshot of what I'm seeing in heap profile that I manually grabbed directly after a long GC:

```
(pprof) top25
Total: 1700.9 MB
   300.5  17.7%  17.7%    300.5  17.7% github.com/couchbase/gomemcached.(*MCRequest).Receive
   259.5  15.3%  32.9%    259.5  15.3% net/http.(*expectContinueReader).Read
   218.5  12.8%  45.8%    218.5  12.8% newdefer
   177.5  10.4%  56.2%    181.0  10.6% bufio.(*Reader).fill
   155.5   9.1%  65.3%    155.5   9.1% encoding/json.unquoteBytes
    42.0   2.5%  67.8%     44.5   2.6% compress/flate.(*compressor).deflate
    40.0   2.4%  70.2%     40.0   2.4% reflect.mapassign
    34.0   2.0%  72.2%    126.2   7.4% github.com/couchbaselabs/sync_gateway/db.func·008
    29.0   1.7%  73.9%     29.0   1.7% runtime.malg
    28.5   1.7%  75.5%    183.5  10.8% encoding/json.(*decodeState).literalInterface
    26.5   1.6%  77.1%     26.5   1.6% net/textproto.(*Reader).upcomingHeaderNewlines
    20.5   1.2%  78.3%     20.5   1.2% bytes.(*Buffer).WriteByte
    20.5   1.2%  79.5%     77.5   4.6% net/http.ReadRequest
    20.0   1.2%  80.7%     20.0   1.2% net/textproto.(*Reader).ReadLine
    20.0   1.2%  81.9%     20.0   1.2% net/textproto.(*Reader).ReadMIMEHeader
    19.5   1.1%  83.0%    177.5  10.4% github.com/couchbaselabs/sync_gateway/db.func·004
    19.0   1.1%  84.1%     19.5   1.1% encoding/json.(*decodeState).literalStore
    17.0   1.0%  85.1%     17.0   1.0% net/http.(*headerSorter).Swap
    15.5   0.9%  86.0%     15.5   0.9% github.com/couchbaselabs/sync_gateway/db.func·006
    12.5   0.7%  86.8%     12.5   0.7% github.com/gorilla/mux.(*routeRegexpGroup).setMatch
    11.0   0.6%  87.4%     11.0   0.6% reflect.makemap
    10.5   0.6%  88.0%     99.0   5.8% net/http.(*response).WriteHeader
    10.0   0.6%  88.6%     10.0   0.6% github.com/gorilla/context.init
     8.0   0.5%  89.1%      8.5   0.5% github.com/couchbaselabs/sync_gateway/db.(*Database).GetChanges
     8.0   0.5%  89.6%     19.0   1.1% github.com/couchbaselabs/sync_gateway/db.(*Database).MultiChangesFeed
```

also, drilling in deeper on github.com/couchbase/gomemcached.(*MCRequest).Receive:

```
(pprof) list Receive
Total: 1700.9 MB
ROUTINE ====================== github.com/couchbase/gomemcached.(*MCRequest).Receive in /root/sync_gateway/vendor/src/github.com/couchbase/gomemcached/mc_req.go
 300.5  300.5 Total MB (flat / cumulative)
     .      .  118:     }
     .      .  119:     return
     .      .  120: }
     .      .  121:
     .      .  122: // Receive will fill this MCRequest with the data from a reader.
---
     .      .  123: func (req *MCRequest) Receive(r io.Reader, hdrBytes []byte) (int, error) {
     .      .  124:     if len(hdrBytes) < HDR_LEN {
     .      .  125:         hdrBytes = []byte{
     .      .  126:             0, 0, 0, 0, 0, 0, 0, 0,
     .      .  127:             0, 0, 0, 0, 0, 0, 0, 0,
     .      .  128:             0, 0, 0, 0, 0, 0, 0, 0}
     .      .  129:     }
     .      .  130:     n, err := io.ReadFull(r, hdrBytes)
     .      .  131:     if err != nil {
     .      .  132:         return n, err
     .      .  133:     }
     .      .  134:
     .      .  135:     if hdrBytes[0] != RES_MAGIC && hdrBytes[0] != REQ_MAGIC {
     .      .  136:         return n, fmt.Errorf("bad magic: 0x%02x", hdrBytes[0])
     .      .  137:     }
     .      .  138:
     .      .  139:     klen := int(binary.BigEndian.Uint16(hdrBytes[2:]))
     .      .  140:     elen := int(hdrBytes[4])
     .      .  141:
     .      .  142:     req.Opcode = CommandCode(hdrBytes[1])
     .      .  143:     // Vbucket at 6:7
     .      .  144:     req.VBucket = binary.BigEndian.Uint16(hdrBytes[6:])
     .      .  145:     bodyLen := int(binary.BigEndian.Uint32(hdrBytes[8:]) -
     .      .  146:         uint32(klen) - uint32(elen))
     .      .  147:     if bodyLen > MaxBodyLen {
     .      .  148:         return n, fmt.Errorf("%d is too big (max %d)",
     .      .  149:             bodyLen, MaxBodyLen)
     .      .  150:     }
     .      .  151:     req.Opaque = binary.BigEndian.Uint32(hdrBytes[12:])
     .      .  152:     req.Cas = binary.BigEndian.Uint64(hdrBytes[16:])
     .      .  153:
     .      .  154:     buf := make([]byte, klen+elen+bodyLen)
     .      .  155:     m, err := io.ReadFull(r, buf)
     .      .  156:     n += m
     .      .  157:     if err == nil {
     .      .  158:         if req.Opcode >= TAP_MUTATION &&
     .      .  159:             req.Opcode <= TAP_CHECKPOINT_END &&
     .      .  160:             len(buf) > 1 {
     .      .  161:             // In these commands there is "engine private"
     .      .  162:             // data at the end of the extras.  The first 2
     .      .  163:             // bytes of extra data give its length.
     .      .  164:             elen += int(binary.BigEndian.Uint16(buf))
     .      .  165:         }
     .      .  166:         req.Extras = buf[0:elen]
 300.5  300.5  167:         req.Key = buf[elen : klen+elen]
     .      .  168:         req.Body = buf[klen+elen:]
     .      .  169:     }
     .      .  170:
     .      .  171:     return n, err
---
     .      .  172: }
```

All of the significant memory allocation in the Receive method is coming from line 167: `req.Key = buf[elen : klen+elen]`

**Comment by tleyden** [comment]
I managed to reproduce this again.  This time it was [perfrun 629](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/629/), which was using these params:
- go version 1.4.1
- cb server version: 2.5
- sync gw branch: feature/issue_525 [jenkins build](http://factory.couchbase.com/view/build/view/mobile_dev/view/sync_gateway/view/master/job/build_sync_gateway_dev_cents-x64/17/)
- gateload.pushers.5000,gateload.pullers.8000,gateway.num_nodes.2

[This GC](https://gist.github.com/tleyden/f79796e5fe4b25b0dc55#file-gistfile1-txt-L215) took 146.6 seconds.  Similarly on the other sync gw, [this gc](https://gist.github.com/tleyden/a6c4935b3405f3e37595#file-gistfile1-txt-L445) took 110 seconds.

Here is a [snapshot of the top output](https://gist.github.com/tleyden/fa421103bbd7a9a44553)

The [gateload expvars](https://gist.github.com/tleyden/6f2d70f13ae35e931042) have no failures in terms of pushing / pulling docs.  Inexplicably, the [PushToSubscriberInteractive p99](https://gist.github.com/tleyden/6f2d70f13ae35e931042#file-gistfile1-txt-L653) is only 12.1 seconds.  (I would expect much higher)

**Comment by tleyden** [comment]
Unfortunately the heap profile data I'd captured got deleted by a "cleanup script".  Hopefully I will be able to reproduce again and capture this.

**Comment by tleyden** [comment]
I kicked off several more performance runs to see how reproducible this is. 

| perfrun | sg build | PauseTotalGC seconds |
| --- | --- | --- |
| [630](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/630) | 0.0.1-15 (master) | 146.6 s |
| [631](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/631) | 0.0.1-17 (feature/issue_525) | 1,029.3 s |
| [633](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/633/) | 0.0.1-17 (feature/issue_525) | 1,598.0 s |
| [634](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/634) | 0.0.1-17 (feature/issue_525) | 1,631.3 s |
| [634](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/634) | 0.0.1-15 (master) | 164.9 s |

**Comment by tleyden** [comment]
Here are the highlights for the heap analysis, although we don't know if it's accurate.

**Master branch** (perfrun 640)
- [top 25 output](https://gist.github.com/tleyden/70bac20b093f1e92f389)
- [(pprof) list processEntry](https://gist.github.com/tleyden/7abe7c836c436d044053)

**Feature/issue_525_branch** (perfrun 636)
- [top 25 output](https://gist.github.com/tleyden/a4398685e784e86f3063)
- [(pprof) list db.func](https://gist.github.com/tleyden/15e821f37359df94032e)

**Comment by tleyden** [comment]
May need analysis:

https://gist.github.com/tleyden/15e821f37359df94032e#file-gistfile1-txt-L51

```
ROUTINE ======================== github.com/couchbaselabs/sync_gateway/db.func·005 in /opt/sync_gateway/src/github.com/couchbaselabs/sync_gateway/db/change_cache.go

  137.51MB   137.51MB    312:           Channels:     doc.Channels,
```

**Comment by tleyden** [comment]
In [perf run 645](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/645), which is running against the feature/issue_525_instrumented branch, it has currently exceeded [1 million](https://gist.github.com/tleyden/4a827a1130c1215ce253#file-gistfile1-txt-L109) goroutines.

This corresponds with the previous observation that the function responsible for the most heap allocation was shown to be [newproc_m](https://gist.github.com/tleyden/a4398685e784e86f3063#file-gistfile1-txt-L8)

I have another perf run scheduled against the master branch to compare the number of goroutines being spawned.

**Comment by tleyden** [comment]
In [perf run 647](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/647/), I was able to manually cause the sync gateway process to dump its goroutines towards the end of the run by running `kill -s SIGKILL <sync_gw_pid>`

I think only a portion of the goroutine stacks were captured in the [sync gateway logs](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/647/artifact/gateway.log_1.gz) for that run, but hopefully its enough to go on for now. 

I took a snippet from the top and bottom of the logs and put them in a [gist](https://gist.github.com/tleyden/d47eb9e03937ae8ffe9f) for easy viewing.

Towards the second half of the gist, there are many repeated entries that look like this:

```
goroutine 1909554 [semacquire, 37 minutes]:
sync.(*Mutex).Lock(0xc2081c6158)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*RWMutex).Lock(0xc2081c6158)
	/usr/local/go/src/sync/rwmutex.go:82 +0x33
github.com/couchbaselabs/sync_gateway/db.(*changeCache).processEntry(0xc2081c60d0, 0xc238400a80, 0x0)
	/home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbaselabs/sync_gateway/db/change_cache.go:359 +0x55
github.com/couchbaselabs/sync_gateway/db.func·005()
	/home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbaselabs/sync_gateway/db/change_cache.go:320 +0xb6e
created by github.com/couchbaselabs/sync_gateway/db.(*changeCache).DocChanged
	/home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbaselabs/sync_gateway/db/change_cache.go:324 +0x1b0
 
```

**Comment by tleyden** [comment]
In [perf run 649](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/649/), which was against the master branch, the max # of goroutines I saw in expvars was approx 40K.

I ran `SIGQUIT` against a live process towards the end of the run, and the goroutine stacktraces were captured in this gzipped log file:

http://cl.ly/1G331o412h3b?_ga=1.89479000.257213425.1401744125

It killed the process, which is why the job has no artifacts attached.

**Comment by tleyden** [comment]
I've deleted the previous 3 comments and migrated them to https://github.com/couchbase/sync_gateway/pull/624
