### ISSUE TITLE
Evaluate channel cache performance

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#619]

**Comment by adamcfraser** [comment]
Completed for the in-memory cache. Resulted in the following enhancements:  
- Added benchmarks (in channel_cache_test.go) to identify performance bottlenecks, and implemented optimizations based on results.  (#699)
- Exposed cache tuning parameters via config  (included in #686)
- Ability to disable star channel (#743)

The distributed cache work (https://github.com/couchbase/sync_gateway/labels/dcache) is in progress, to allow SG to go beyond the limitations of the one-cache-per-SG node,
