### ISSUE TITLE
Getting 403 forbidden error sporatically

### ISSUE THREAD

**Issue by deefactorial** [couchbase/sync_gateway#637]
I wrote some qunit tests for my app to test the functionality. 
When I run the tests approximately 1 out 4 times the tests will fail with a 403 forbidden error.
I've checked my sync function and the user has access to the document that is throwing the 403 forbidden error. 
it seems to me like there is a race condition occurring from when the user is created in the sync gateway and the requesting of a document owned by that user.
I see lines in the sync gateway that say:
00:33:52.210058 Cache:   Deferring #3976 (7 now waiting for #3969...#3969)

here is the gist of the logs of what is going on for one test.
https://gist.github.com/deefactorial/fd77d6d1f646523917c1

to run the tests go to:
https://cloud.openmoney.cc/webclient/tests.html
if the test fails logout and refresh the page to run the tests again. sometimes it fails sometimes it passes.

the project is opensource at:
https://github.com/deefactorial/openmoney-mobile
you can find my sync function in there.

the server side code can be found here:
https://github.com/deefactorial/openmoney-server

any help with this would help.

**Comment by deefactorial** [comment]
oh and I'm running the sync_gateway from the master branch of this repo; updated yesterday.

**Comment by adamcfraser** [comment]
Looking at the gist, I don't see anything that would be causing this problem.  I don't think the 'Deferring' message is related - that's the usual buffering done by the SG to process incoming documents from the TAP feed.  

The scenario that I'd expect to result in this behaviour is if the GET for  `trading_name,testuseru8qg31423182835779.cc,cc` is executed before the PUT that grants the user access to the document happens.

I had a couple of questions:
1. What's granting user testuseru8qg31423182835779 access to trading_name,testuseru8qg31423182835779.cc,cc - does that access get granted through a document, or through channels defined on the user when the user is created?
2. If it's granted through a document, when does that document get written?  I don't see it on the gist - is there a chance it's being written before the user is created?
3. Is your config file is something similar to https://github.com/deefactorial/openmoney-mobile/blob/master/sync-gateway-config.json?  In that file it doesn't look like the non-shadow bucket has a server defined - is that modified at runtime by your application prior to use?

Thanks,
Adam

**Comment by deefactorial** [comment]
Hello Adam,
Thanks for the reply.

in my sync function which is found here https://github.com/deefactorial/openmoney-mobile/blob/master/sync-gateway-config.json under the doc type trading_name I create two channels. and grant the owner(steward) access to those two channels so when the doc is created is when the user gets access to the document. 

you can see in the gist on these two lines:
https://gist.github.com/deefactorial/fd77d6d1f646523917c1#file-gistfile1-txt-L10-L11
That the document exists and that the document is in the channel. trading_name_steward@testuseru8qg31423182835779.cc@Y2M=
Then in the next line you see that the user:testuseru8qg31423182835779 has access to the channel: trading_name_steward@testuseru8qg31423182835779.cc@Y2M=
but when the user tries to access the doc on line:
https://gist.github.com/deefactorial/fd77d6d1f646523917c1#file-gistfile1-txt-L114-L115
the user sometimes gets a 403 forbidden error.

Response to your questions:
1. The user has access to that document when the document is created. 
   Specifically:
   channel creation:
   https://github.com/deefactorial/openmoney-mobile/blob/master/sync-gateway-config.json#L190
   access:
   https://github.com/deefactorial/openmoney-mobile/blob/master/sync-gateway-config.json#L194
2. the document is in the gist:
   https://gist.github.com/deefactorial/fd77d6d1f646523917c1#file-gistfile1-txt-L7-L8
   The document gets written on the server side bucket through the registration API.
   https://github.com/deefactorial/openmoney-server/blob/master/index.php#L359
   then it syncs the document to the shadow bucket when the user is created on line 
   https://github.com/deefactorial/openmoney-server/blob/master/index.php#L542
   Should I create the user in the sync gateway before I insert data into the serverside bucket ?
3. yes that is my sync gateway document, the server defined is on line:
   https://github.com/deefactorial/openmoney-mobile/blob/master/sync-gateway-config.json#L15
   both the sync gateway and the couchbase server are on the same server instance: cloud.openmoney.cc
   I have not had issues other than this one with documents syncing between the serverside bucket and the shadow bucket.

I may try executing the user creation API in the sync gateway before inserting documents into the server bucket.

Thank you for looking into this it has been insightful.

**Comment by adamcfraser** [comment]
Unless I'm misreading your sync config, I only see one server defined.

On line https://github.com/deefactorial/openmoney-mobile/blob/master/sync-gateway-config.json#L15 you're defining the server for bucket 'openmoney'.  I don't see the server getting defined for the main SG bucket 'openmoney_shadow', which I would have expected to result in SG using an in-memory-only walrus bucket for that database.

If you're seeing things in that couchbase bucket as expected, though, it's possible that it's defaulting to localhost:8091.  You might want to explicitly define the server in the config file, though, for when you move from localhost testing.

On the user creation timing - I think it's necessary that the user gets created before the document granting the user channel access is processed.  The document granting access will trigger that the user's channel access is recalculated and updated on the user document - if that doesn't exist yet, it might explain why that user ends up getting a 403.

**Comment by jchris** [comment]
Could this have something to do with replication ordering not being what's expected?

Also I took a look at your Open Money project, it looks pretty cool. Have you seen [this crypto currency idea I've been talking about?](http://www.wired.com/2014/07/document-coin/) It's not trying to be as practical as what you are doing, but they are similar, I think. If you wanna chat about this stuff (and get feedback on your app architecture) send me an email at jchris@couchbase.com I think it would be fun to talk.

**Comment by deefactorial** [comment]
Hey Chris,
Yes it could be an issue with replication ordering. 
As Adam pointed out I was using a walrus db for the sync gateway. When I switched to using couchbase server the replication time between the db increased now the server side views aren't populating correctly. I'm going to try moving the views from the server side bucket to the sync gateway bucket since they are read only I'm hoping they will not cause any issues with the sync gateway. I also changed the order of user creation in the sync gateway to occur before any documents are created for that user, hopefully that will fix the 403 forbidden error from occuring I will be able to test that once I get the views to render correctly. 

I have had a look at the crypto currency you have been working on. It sounds very interesting lets have a chat I'm on skype and available most days. send me a message when it's convient for you.

**Comment by zgramana** [comment]
@deefactorial unless you have any updates, we'll closes this one in one week.

**Comment by deefactorial** [comment]
I resolved the issue by accessing the data directly through the sync_gateway REST API rather than through the couchbase server shadow bucket, the REST API is much slower than bucket shadowing but it's not giving us the same error as before. Seems like it was a race condition between setting the data on the server bucket that replicated it's data to the sync gateway bucket which was accessed through the REST API. Thanks for all your help.

**Comment by akpmp** [comment]
HI, have am going to run anyplace server on our own computer after given error   [HTTP/1.1 403 Forbidden 1432ms]. How to solved it
Thanks/Regard
Arun Patel
