### ISSUE TITLE
(Re)implement attachment GC

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#64]
Attachments never get deleted, even after a database compaction when there are no longer any revision bodies referring to them. (Compaction no longer occurs either; see #58).

The issue is that attachment storage is content-addressable: each attachment is named according to its SHA-1 digest. There can be multiple revisions referring to the same attachment. This has a number of advantages, but it means that attachments can only be deleted by garbage-collection techniques — scanning all the live revisions to collect their attachment references, then deleting all attachments that aren't found in that collection.

When we move attachment storage to CBFS we might be able to change the lookup mechanism. I believe CBFS is internally already content-addressable, so we could get the same space savings automatically, and switch to naming an attachment based on the doc/rev ID of the revision that owns it. That would make it easier to delete attachments along with revisions during compaction.

**Comment by adamcfraser** [comment]
Tracking w/ https://github.com/couchbase/sync_gateway/issues/1648.
