### ISSUE TITLE
Admin API User Config does not preserve settings when trying to add role to user.  

### ISSUE THREAD

**Issue by ToddGreenstein** [couchbase/sync_gateway#642]
After creating a user, if any roles are created and added to the user, the initial user configuration settings are overwritten (in this repro the email address in particular)
## Create a User

curl -X PUT http://192.168.41.104:4985/sync_gateway/_user/todd -d '{"name":"todd","password":"cb123","email":"todd@couchbase.com"}'  -H "Content-type:application/json"
## Verify a User

curl -X GET http://192.168.41.104:4985/sync_gateway/_user/todd 
## Create a Role

curl -X PUT http://192.168.41.104:4985/sync_gateway/_role/guitar -d  '{"admin_channels":["acoustic", "electric"]}' -H "Content-type:application/json"
## Verify a Role

curl -X GET http://192.168.41.104:4985/sync_gateway/_role/guitar 
## Assign Role to User

curl -X PUT http://192.168.41.104:4985/sync_gateway/_user/todd -d '{"admin_channels":["acoustic", "electric"],"admin_roles":["guitar"]}' -H "Content-type:application/json"
## Verify user received new role

curl -X GET http://192.168.41.104:4985/sync_gateway/_user/todd

**Comment by ajres** [comment]
The user details are stored in a document, you don't really assign the role to the user, you are updating the user document with the "admin_roles" property.

The new version of the document above includes the "admin_roles" property but it no longer contains, the email property e.t.c.

If you want to update the user record, GET the current user document, update/add/remove the fields that have changed, then PUT the updated user document to update the user properties.

Andy

**Comment by ToddGreenstein** [comment]
Andy,

**I'm trying to understand the workflow for:**

Create User->Create Role-> Add Role To User

**As shown in this unit test in the sync gateway repository:**

https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbaselabs/sync_gateway/rest/admin_api_test.go#L66-L84

**There are two problems with the retrieve the "entire user document and update" approach:**

[1] Sync Gateway will not return a previously defined user password through the api.
[2] To pass the entire document back to the api, the password must be known or the user will have no password.  

Perhaps I'm misunderstanding the process for doing this?

--Todd

**Comment by ajres** [comment]
I just ran through the test steps, user “name" and “password” properties are preserved when other properties are set.

You can explicitly set a new password by passing the “password” property in the PUT command.

All other properties are removed on a subsequent PUT if not redefined in the JSON document you submit..

In your original example change :

curl -X PUT http://192.168.41.104:4985/sync_gateway/_user/todd -d '{"admin_channels":["acoustic", "electric"],"admin_roles":["guitar"]}' -H "Content-type:application/json”

to

curl -X PUT http://192.168.41.104:4985/sync_gateway/_user/todd -d '{"email":"todd@couchbase.commailto:todd@couchbase.com”, "admin_channels":["acoustic", "electric"],"admin_roles":["guitar"]}' -H "Content-type:application/json”

If you use the GET and update approach, the password will not be reset it will remain unchanged as the “password" property is not included in the generated document.

When you do a GET you will also see the read only properties “all_channels” and “roles”, you can leave these in the document and on subsequent PUT they will be ignored.

Andy

On 8 Feb 2015, at 21:05, ToddGreenstein <notifications@github.com<mailto:notifications@github.com>> wrote:

Andy,

I'm trying to understand the workflow for:

Create User->Create Role-> Add Role To User

As shown in this unit test in the syng gateway repository:

https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbaselabs/sync_gateway/rest/admin_api_test.go#L66-L84

There are two problems with the retrieve the "entire user document and update" approach:

[1] Sync Gateway will not return a previously defined user password through the api.
[2] To pass the entire document back to the api, the password must be known or the user will have no password.

Perhaps I'm misunderstanding the process for doing this?

--Todd

**Comment by ToddGreenstein** [comment]
Thank you Andy, I understand now.
