### ISSUE TITLE
Demo cluster data migration: facebook user id / email

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#645]
The ios/android Todolite clients have been upgraded to use the new fb id scheme: https://github.com/couchbaselabs/ToDoLite-iOS/issues/42

There is some pending changes required on sync gateway regarding hitting the facebook graph api: https://github.com/couchbase/sync_gateway/issues/644

Once that's done, we should try to migrate the demo cluster todolite database:

Before

```
{"_id":"9ba8d7ed-c58b-483f-a3e3-33e8b82bc67f","_rev":"1-6f9583f6128bab18240726e9326c1cbf","created_at":"2015-02-10T00:07:08.531Z","members":[],"owner":"profile:user.email@gmail.com","title":"test2list","type":"list"}
```

After:

```
{"_id":"9ba8d7ed-c58b-483f-a3e3-33e8b82bc67f","_rev":"1-6f9583f6128bab18240726e9326c1cbf","created_at":"2015-02-10T00:07:08.531Z","members":[],"owner":"profile:778915335487383","title":"test2list","type":"list"}
```

The difference is that the owner field has the facebook id rather than the user's email address.

**Comment by adamcfraser** [comment]
Based on #644 being closed, closing this as well.
