### ISSUE TITLE
1.0.3: process exits when 1 of 2 buckets is not available

### ISSUE THREAD

**Issue by Macnificent** [couchbase/sync_gateway#648]
Couchbase server version: 3.0.1 Enterprise Edition (build-1444).
Gateway version: 1.0.3(81;fa9a6e7)

The gateway is configured to use 2 buckets, each residing in their own cluster.
Recently tried starting the gateway when one of the servers was unavailable. This of course yielded an error in the log, as expected:

```
FATAL: Error opening database: 502 Unable to connect to server
```

(Some information redacted)
Now, what I expected was that the gateway would still be able to serve requests to the other (still available) cluster. But this was not the case!

**Comment by Macnificent** [comment]
Forgot to add that according to the log, a connection to the available cluster was opened before the unavailable one, but the process still exits.

**Comment by tleyden** [comment]
Thanks for the clear issue report

**Comment by tleyden** [comment]
I agree it should be more robust in this respect.

**Comment by adamcfraser** [comment]
Will get covered by #1019.

**Comment by adamcfraser** [comment]
No plans to support this soon.  Some handling could be done today by starting databases in offline mode.
