### ISSUE TITLE
Bucket Shadowing not getting last changes

### ISSUE THREAD

**Issue by kvaillant** [couchbase/sync_gateway#651]
Hi,
I'm facing a problem with bucket shadowing. I have two clients (a mobile and a web app worker) connected to my sync-gateway server.
1. Mobile updates this doc from rev-1 to rev-2
2. Shadowing pull from rev `2-beedaf0b78d0bbf6dc86a0f064b2901d` and store upstream_rev to `2-a2af29f51d11b086f0ac1057ce48d1cc`
3. Worker listening to sync-gateway changes' feed got previous doc.rev `2-beedaf0b78d0bbf6dc86a0f064b2901d` and update doc to rev : `3-99a00f16f3c7f02025da9ea4ff790e64`

Problem : There is no other shadowing for `rev-3`.

Here is my doc in sync-gateway bucket

```
{
  "_sync": {
    "rev": "3-99a00f16f3c7f02025da9ea4ff790e64",
    "new_rev": "2-a2af29f51d11b086f0ac1057ce48d1cc",
    "flags": 28,
    "sequence": 6340,
    "history": {
      "revs": [
        "1-695e46c7745b5e78586493d2873ba12a",
        "2-beedaf0b78d0bbf6dc86a0f064b2901d",
        "3-99a00f16f3c7f02025da9ea4ff790e64",
        "2-a2af29f51d11b086f0ac1057ce48d1cc"
      ],
    "upstream_cas": 15086427531385994,
    "upstream_rev": "2-a2af29f51d11b086f0ac1057ce48d1cc",
    "time_saved": "2015-02-15T23:37:20.130775366+01:00"
  }
...
}
```
- **Couchbase** : Version: 3.0.1 Community Edition
- **Sync-gateway** : Version: 1.0.3 Entreprise Edition

**Comment by tleyden** [comment]
Thanks for the bug report.  Is this reproducible every time?

**Comment by kvaillant** [comment]
Hello,
Yes I reproduced this bug every time I got a changed from a mobile sync and when I try to update my document on sync-gateway rest api while shadowing is active.

What I do to temporary fix up this bug, is to save my document to rest api and in the same time save it to the shadow bucket so that I definitely store the same doc.

**Comment by adamcfraser** [comment]
Closing - bucket shadowing has been deprecated, replaced by shared bucket access.
