### ISSUE TITLE
Setting CPU and memory for sync_gateway test machine before performance run

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/sync_gateway#658]
PerfRunner measurement may be different with different number of CPU and different size of memory on the sync_gateway test machine.   To be consistent with the setting for previous performance runs, everytime the sync_gateway test machine is freshly rebooted, make sure to set the CPU count to 8 and memory size to 8GB.   

To set memory size, at  /etc/grub.conf, set mem=9265MB in the following line and reboot the system:

```
    kernel /vmlinuz-2.6.32-431.el6.x86_64 ro root=UUID=e3ccc9a7-3c5f-4213-8003-eaf535d2ff6c rd_NO_LUKS rd_NO_LVM LANG=en_US.UTF-8 rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto  KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM rhgb quiet  mem=9265MB
```

The reason to choose 9265MB is because setting this number result in 'free' commend returns the number that is most close to 8G memory.

To set CPU to 8 when the machine has 24 CPU, set 0 to all the /sys/devices/system/cpu/cpuN/online file like the following:

```
echo 0 > /sys/devices/system/cpu/cpu8/online
echo 0 > /sys/devices/system/cpu/cpu9/online
.... etc
echo 0 > /sys/devices/system/cpu/cpu22/online
echo 0 > /sys/devices/system/cpu/cpu23/online
```

There is no need to do this with the test machine for Gateload.

**Comment by tleyden** [comment]
> To set memory size, at /etc/grub.conf, set mem=9265MB

If this is set by grub, I don't understand why it would need to be manually set?

> To set CPU to 8 when the machine has 24 CPU

I don't understand what this means.

**Comment by adamcfraser** [comment]
Closing as obsolete given current perf framework.
