### ISSUE TITLE
Dig into huge go-couchbase latencies in logs

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#665]
Is this a stop-the-world GC or sync gw load.

**Comment by elevine** [comment]
Would this cover the issue I've posted about here: https://groups.google.com/forum/#!topic/mobile-couchbase/ZZHJTW-8wys ?

**Comment by adamcfraser** [comment]
Should be revisited in the context of a potential move to pipelined server requests (e.g. gocb).
