### ISSUE TITLE
Perfrunner: speed up test

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#666]
User creation used to be very fast for the perf test, and then something changed in couchbase server that slowed it down considerably, so you had to switch to the slow ramp-up.

Here is a related ticket: https://issues.couchbase.com/browse/MB-11798

**Comment by tleyden** [comment]
Pre-populate sg config with users and use basic auth.

**Comment by adamcfraser** [comment]
WIll be interesting to see whether there's also a change in perf results using basic auth, given the number of slow go-couchbase _sync:session calls showing up in the gateway logs

**Comment by tleyden** [comment]
As a first step, I made it possible to toggle the authentication strategy between:
- Session based auth (current approach)
- Basic auth (faster -- new default)

It will be possible to change the auth type used by gateload, via the perfrunner, by passing the argument:
- gateload.auth_type.basic
- gateload.auth_type.session

It defaults to basic

**Comment by tleyden** [comment]
I ran gateload locally against my local sync gateway (master branch), using a walrus backed database.

I was able to grab profiling data via:

```
go tool pprof --pdf bin/sync_gateway http://localhost:4985/_debug/pprof/profile > ~/tmp/profile.pdf
```

which resulted in this cpu profiling graph:

![screen shot 2015-02-20 at 3 52 21 pm](https://cloud.githubusercontent.com/assets/296876/6311517/af55c21c-b918-11e4-8537-f331861cb2f2.png)

**Comment by tleyden** [comment]
I did an experiment to cache the hashed passwords and avoid the call to `bcrypt.GenerateFromPassword` for passwords where we've already calculated the hash, and it took **11s** to create 10K users.  

Previously it was taking **3.5 mins** to create the same 10K users.

**Comment by tleyden** [comment]
This doesn't seem to be taking effect:

https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbaselabs/sync_gateway/auth/password_hash.go

when I look at the passwords emitted by bcrypt, the hashes are different for the same password (in this case, “password”):

https://gist.github.com/tleyden/5da0bf7f49a183db5f8c

I expected the hash to be the same for the same password, but I think there’s some salting going on, which seems to be busting the caching

**Comment by tleyden** [comment]
Ran into errors on the perf cluster:

```
2015/02/25 12:45:04 http: panic serving 172.23.96.68:59901: runtime error: invalid memory address or nil pointer dereference
goroutine 1469 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/couchbase/sync_gateway/db.(*DatabaseContext).UpdatePrincipal(0xc20800c840, 0xc2081d2110, 0xc2084861e0, 0x0, 0x0, 0x0, 0x0, 0xc2081d20c0, 0x0, 0x0, ...)
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/db/users.go:82 +0x224
github.com/couchbase/sync_gateway/rest.(*handler).updatePrincipal(0xc2084ec000, 0xc20816d3ee, 0xa, 0x1, 0x0, 0x0)
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/admin_api.go:155 +0x449
github.com/couchbase/sync_gateway/rest.(*handler).putUser(0xc2084ec000, 0x0, 0x0)
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/admin_api.go:176 +0xb3
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc2084ec000, 0xd6e6a0, 0x0, 0x0)
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x4b8
github.com/couchbase/sync_gateway/rest.func·015(0x7f1e3b58dcb0, 0xc2086ce140, 0xc20841e750)
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7d
net/http.HandlerFunc.ServeHTTP(0xc2081d6c40, 0x7f1e3b58dcb0, 0xc2086ce140, 0xc20841e750)
    /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20805c410, 0x7f1e3b58dcb0, 0xc2086ce140, 0xc20841e750)
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x29e
github.com/couchbase/sync_gateway/rest.func·017(0x7f1e3b58dcb0, 0xc2086ce140, 0xc20841e750)
    /home/couchbase/jenkins/workspace/build_sync_gateway_dev_cents-x64/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:226 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc20823e940, 0x7f1e3b58dcb0, 0xc2086ce140, 0xc20841e750)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc2081660c0, 0x7f1e3b58dcb0, 0xc2086ce140, 0xc20841e750)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2084fc460)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e
2015/02/25 12:45:04 http: panic serving 172.23.96.68:59903: runtime error: invalid memory address or nil pointer dereference
```

**Comment by tleyden** [comment]
Done
