### ISSUE TITLE
Resumeable attachment uploads

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#67]
In #59, @march44 wrote:

> when I first started with CouchCocoa and iriscouch, I frequently saw sync issues with large files 20-40Meg from mobile devices. The issue was that a stable connection could not be held open long enough for the binary attachment transfer to complete, often resulting in 5+ attempts to sync those files.
> 
> I realize it would probably break the CouchDB replication protocol, but if sync_gateway is going to be able to support large attachments, there really needs to be a way to chunk the data when replicating to support unreliable mobile connections.
> 
> At the App level I have been looking at using a channel to represent a binary file and have that channel contain multiple documents each with a chunk of the data. I use a hash tree to allow the chunks to be validated and reassembled, out of order if necessary.
> 
> But if this was built into the replication it would make the task of syncing large attachments with mobile devices a lot more practical.

**Comment by adamcfraser** [comment]
Closing based on age.  Valid use case, but would be implemented as a more comprehensive set of enhancements to attachment handling.
