### ISSUE TITLE
"Error unmarshaling doc"

### ISSUE THREAD

**Issue by nl** [couchbase/sync_gateway#672]
In master, using shadowing, user accounts tend not to persist across SG restarts, or at least direct HTTP authentication for those users stops working.

It seems, under unknown circumstances, the gateway is having trouble re-reading the user doc from the gateway bucket.

This could mean a number of things which aren't necessarily bugs, but I'm just wondering what those warnings actually mean?

From the logs:

```
02:10:46.607654 WARNING: changeCache: Error unmarshaling doc "_sync:user:fe8614bd-8d07-439c-9332-018b2657709c": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:207
02:10:46.607666 WARNING: changeCache: Error unmarshaling doc "_sync:user:9536f328-a6dc-44b6-90b2-5fee1c03f84f": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:207
02:10:46.607615 WARNING: changeCache: Error unmarshaling doc "_sync:user:8ec240a5-08dc-463a-86b6-d27a3ae84b48": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:207
02:10:46.607752 WARNING: changeCache: Error unmarshaling doc "_sync:user:1b83f3f6-83cd-4420-bf04-cf5cb5610fd9": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:207
02:10:46.608629 WARNING: changeCache: Error unmarshaling doc "_sync:user:aedb794b-3290-463d-a3dc-b98315b24b8b": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:207
02:10:46.608721 WARNING: changeCache: Error unmarshaling doc "_sync:user:7e553b4a-1ee7-475e-a150-be86b8e7c4a4": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:207
02:10:46.609026 WARNING: changeCache: Error unmarshaling doc "_sync:user:fe8614bd-8d07-439c-9332-018b2657709c": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:207
02:10:46.609161 WARNING: changeCache: Error unmarshaling doc "_sync:user:8ec240a5-08dc-463a-86b6-d27a3ae84b48": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:207
```

**Comment by zgramana** [comment]
In review with @adamcfraser, a number of things are suspect about this log data. Someone on the SG team needs to look into this.

**Comment by adamcfraser** [comment]
We need a clear-cut repro scenario for this.

**Comment by sethrosetter** [comment]
@adamcfraser Can you file a scenario definition against mobile-testkit and I will create a repro?

**Comment by tleyden** [comment]
From @ArihantRk on gitter:

> syncgateway 1.3.1
> it happens everyday, not very frequenctly.
> Not sure how reproduce, belowmoperation we are doing
> updates of same documents every 60 seconds
> New docs inserts for every 4 seconds

**Comment by tleyden** [comment]
@ArihantRk

which OS are you on?  Would you be able to test a pre-release version to see if the issue is still happening?

**Comment by tleyden** [comment]
@ArihantRk 

we are code-freezing the 1.4 release very soon, so the sooner the better on this ticket

**Comment by ArihantRk** [comment]
@tleyden , running on redhat 7.2. changeCache: Error unmarshaling doc is not frequently for _sync:user documents.

**Comment by kirangandhi** [comment]
@tleyden
Here is the warning message received.
WARNING: changeCache: Error unmarshaling doc "cg55972.doc": unexpected end of JSON input -- db.(*changeCache).DocChanged.func1() at change_cache.go:327

**Comment by kirangandhi** [comment]
running 1.3.1 sync gateway on redhat 7.2 docker container.

**Comment by kirangandhi** [comment]
@tleyden Any plan to fix this in 1.4?

**Comment by tleyden** [comment]
@kirangandhi can you open a new bug with clear steps to reproduce?   

Ideally a script, or else a set of instructions that can easily be turned into a [functional test](https://github.com/couchbaselabs/mobile-testkit/tree/master/testsuites/syncgateway/functional/tests)

**Comment by ArihantRk** [comment]
@tleyden 
These warning messages we have seen when documents gets purged either by REST API or couchbase GUI but with **change_cache.go:407.** message  seems like [https://github.com/couchbase/sync_gateway/issues/1557](url)
does it make any difference between at **change_cache.go:207** and at **change_cache.go:407.**

**Comment by tleyden** [comment]
> WARNING: changeCache: Error unmarshaling doc "cg55972.doc": unexpected end of JSON input -- db.(*changeCache).DocChanged.func1() at change_cache.go:327

I think you would want to look at the packet trace in a networking tracing tool like wireshark and see if the client is abruptly terminating the connection.  

Or maybe a similar test -- if you have a couchbase lite client with a feed=continuous changes feed, and you abruptly take the device offline, does that error appear in the error logs?
