### ISSUE TITLE
Sync gw master branch not building

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#675]
http://factory.couchbase.com/view/build/view/mobile_dev/view/sync_gateway/view/master/job/build_sync_gateway_dev_cents-x64/73/console

**Comment by ajres** [comment]
This is due to upstream changes required in couchbase/build via Gerrit

**Comment by ajres** [comment]
Changes have been committed, waiting for Jenkins master build to run to confirm fix.

**Comment by ajres** [comment]
Jenkins build is now working off of master again, closing this ticket
