### ISSUE TITLE
Changes feed not responding on demo cluster (breaks TodoLite app)

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#677]
`curl -v --cookie "SyncGatewaySession=<session_id>" "172.23.121.36:4984/todolite/_changes?since=120073"`

This is hanging for a long time, and seems to be the root cause of https://github.com/couchbaselabs/ToDoLite-Android/issues/36

**Comment by tleyden** [comment]
Seeing error in couchbase server logs:

```
[mapreduce_errors:error,2015-02-24T11:40:21.513,ns_1@pear-s23004.demo.couchbase.local:<0.28152.2857>:couch_set_view_updater:load_doc:483]Bucket `todolite`, main group `_design/sync_gateway`, skipping document with ID `_sync:att:sha1-j1Zh/B/VlzACaa3P3MaPgTv2kfg=`: too large body (1544161 bytes)
[mapreduce_errors:error,2015-02-24T11:40:21.646,ns_1@pear-s23004.demo.couchbase.local:<0.28160.2857>:couch_set_view_updater:load_doc:483]Bucket `todolite`, main group `_design/sync_gateway`, skipping document with ID `_sync:att:sha1-j1Zh/B/VlzACaa3P3MaPgTv2kfg=`: too large body (1544161 bytes)
```

**Comment by tleyden** [comment]
Related google groups thread: https://groups.google.com/forum/#!msg/mobile-couchbase/1-QNAdPPpec/iC2pCW0-cyUJ

**Comment by tleyden** [comment]
From couchbase server support team:

> It means the doc was to large to run through the view.
> 
> There is a problem where large docs can cause the cluster go nuts when they are ran through the view process.
> 
> In one of the builds (2.2?) we add a setting that would check the size and stop it from being processed

**Comment by tleyden** [comment]
From couchbase server support team:

> The view doc size limits can be changed.
> https://issues.couchbase.com/browse/DOC-81
> There are two parts
> The 1st is to do with the size of the object.  The other is to do with the size of the emit from the view.
> This comment explains what the settings do
> https://issues.couchbase.com/browse/CBSE-811?focusedCommentId=70853&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-71841
> That whole CBSE explains why that setting was created.

**Comment by tleyden** [comment]
This ticket seems like it might be related: https://github.com/couchbase/sync_gateway/issues/210

**Comment by tleyden** [comment]
Directly related: https://issues.couchbase.com/browse/DOC-40

**Comment by tleyden** [comment]
Another possibly related ticket: https://issues.couchbase.com/browse/MB-9713

**Comment by tleyden** [comment]
Possible workaround:

Update settings via:

```
ns_config:set({couchdb, <parameter>}, 123456).
curl -X POST http://Administrator:password@localhost:8091/diag/eval -d \ 
        'ns_config:set({couchdb, <parameter>}, 123456)'
curl -X POST http://Administrator:password@localhost:8091/diag/eval -d \ 
        'rpc:eval_everywhere(erlang, apply, [fun() -> ns_config:set({couchdb, <parameter>}, 123456) end, []]).'
```

See https://issues.couchbase.com/browse/MB-9713

or 

```
# default 1048576 bytes 
$ curl -X POST http://Administrator:password@localhost:8091/diag/eval -d \ 
        'rpc:eval_everywhere(erlang, apply, [fun() -> couch_config:set("set_views", "indexer_max_doc_size", "2048576") end, []]).' 

# default 1048576 bytes 
$ curl -X POST http://Administrator:password@localhost:8091/diag/eval -d \ 
        'rpc:eval_everywhere(erlang, apply, [fun() -> couch_config:set("mapreduce", "max_kv_size_per_doc", "524288") end, []]).'
```

See https://issues.couchbase.com/browse/DOC-81

**Comment by tleyden** [comment]
Also related: https://issues.couchbase.com/browse/MB-11831?focusedCommentId=96408&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-96408

**Comment by tleyden** [comment]
@andreibaranouski do we have any functional tests in cblite-tests which add large attachments?  what is the largest attachment added?

**Comment by andreibaranouski** [comment]
we have some test with attachments ~2.3 MB
https://github.com/couchbaselabs/cblite-tests/blob/master/tests/cbl-replication-attachements.js#L93

@tleyden Do you think that we can increase their size in the test?

**Comment by tleyden** [comment]
@andreibaranouski that should be big enough, but are your tests running with a couchbase server backend?

**Comment by andreibaranouski** [comment]
yes, the same tests are used with CB server backend as well.
I'll check again test with the latest CB version and with 2.2 and let you know

**Comment by tleyden** [comment]
Can you re-run the tests that use CB server as a backend, and then look for errors in the logs like these: https://github.com/couchbase/sync_gateway/issues/677#issuecomment-75831542

I believe those were in log files named "mapreduceerror.log" or something similar.

**Comment by andreibaranouski** [comment]
Hi @tleyden 

I do not see this error in CB logs when I run cblite tests with 3.5 and 2.2 CB versions

**Comment by tleyden** [comment]
@andreibaranouski Thanks for checking this.

That means this issue is non-trivial to reproduce, and it's not as simple as just adding an attachment > 1 MB.

**Comment by zgramana** [comment]
@tleyden can we compromise and just create a new CBS bucket so we can move forward, but still keep the old one around for troubleshooting?

**Comment by tleyden** [comment]
Action item:
- Snapshot Couchbase server VMs
- Remove problematic records

**Comment by tleyden** [comment]
Requested VM snapshots: https://issues.couchbase.com/browse/CBIT-2411

**Comment by adamcfraser** [comment]
Assume this has been dealt with - closing.
