### ISSUE TITLE
Do we need to ensure against external dependency repos dissapearing

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#682]
Michael Kwok was asking if external (not in couchbase org) SG dependencies could be depended to always be available for binary builds.

Should we fork external github repos into 'couchbase' org to protect future binary builds?

**Comment by ajres** [comment]
couchbaselabs org projects on Github have been migrated to couchbase org.

sync_gateway still builds, but src package paths are now inconsistent with repo locations.

**Comment by zgramana** [comment]
The right GH org for these is https://github.com/couchbasedeps

**Comment by tleyden** [comment]
@ajres can you make sure we have forks in https://github.com/couchbasedeps for all of the dependencies listed in the [sync gw repo manifest](https://github.com/couchbase/sync_gateway/blob/master/manifest/default.xml)?

**Comment by ajres** [comment]
In the sync gw repo manifest, the retriever dependency should be to the couchbase repo not couchbaselabs.

```
<project name="retriever" path="godeps/src/github.com/couchbaselabs/retriever" remote="couchbaselabs" revision="19c5a5d92a2f34fb96ae91d26901e4a7076b8020"/>
```

**Comment by ajres** [comment]
I checked all the repos are forked to https://github.com/couchbasedeps, I have not validated that each repo is pinned to the correct revision, is this additional step required?

**Comment by tleyden** [comment]
Can you update the retriever entry and make sure its sha hash is correct?

No need to check the other sha hashes, but feel free to

**Comment by ajres** [comment]
Closing this ticket as all the direct and transient dependencies have been forked to couchbasedeps
