### ISSUE TITLE
Shadowing issues & status API

### ISSUE THREAD

**Issue by nl** [couchbase/sync_gateway#692]
I notice that pushing/pulling docs to/from the shadow bucket can take quite a bit of time (sometimes hours) while the gateway is performing other tasks (evaluating sync functions, managing pushers/pullers, ...). It would be great to have an endpoint on the gateway that returns the current status of shadowing to help diagnose issues. 

I think the gateway regularly misses documents from shadowing (especially when pushing back to the shadow bucket, not so much with pulling from it), particularly when one of the nodes where the shadow bucket is running is experiencing downtime, and an API to diagnose this would make a world of difference.

**Comment by nod** [comment]
@nl I believe that I, too, am experiencing issues where the gateway may be missing shadowing documents.  I see documents that have the same channel in the primary bucket, but I do not have all the documents in the shadow bucket.  I can't recreate it exactly yet, but I'm wondering if this is the same issue you are experiencing and if so, how did you recreate it?

(not meaning to issue-hijack.  want to ensure I'm seeing the same issue before opening a different one)

**Comment by adamcfraser** [comment]
I agree that an API to monitor shadowing status would be useful.

In the meantime, I'm curious whether you think the missed documents are intermittent (i.e. SG sees some new updates and not others), or if shadowing looks like it's stopping altogether.

**Comment by nod** [comment]
In my case the missing documents are definitely intermittent.  Discussing this with Jens on the mailing list right now.

**Comment by nl** [comment]
It is intermittent for me too! I'm not sure this helps, but I've noticed vast changes in behavior depending on SG/CBS locations:
1) SG and CBS (both shadow and sync buckets) are on the same machine
2) SG is shadowing a remote bucket to a local sync bucket
3) there is no local CBS, SG connects and maintains both buckets remotely

In scenario 2/3, the issue described here happens a LOT more often to me. But in these scenarios, I also notice SG sometimes takes a WHILE to shadow (or 'shadow back') documents.

What's your setup like, @nod ?

**Comment by nod** [comment]
@nl - My setup is both buckets on machines ABC.     SG is running on machine D and (for now) explicitly pointed at machine A.

**Comment by adamcfraser** [comment]
This sounds like a case of Sync Gateway losing the TAP feed from the shadowed bucket. Wasn't included in the same dropped TAP feed handling we've added for non-shadowing scenarios because there isn't a good way to handle the gap in feed processing until we move to DCP.  Should be revisited in 2.0 in the context of the mobile convergence work.

**Comment by adamcfraser** [comment]
Closing - bucket shadowing is deprecated, shouldn't be an issue for shared bucket access.
