### ISSUE TITLE
Identifying last indexed checkpoint on SG restart

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#707]
On Sync Gateway restart, we're currently doing the following:
- Set initialSequence to _sync:seq
- Start listening to the TAP feed for any new revisions, and write these to the cache.  If a sequence arrives that's earlier than initialSequence, it's ignored.  The channel caches are valid from initialSequence.
  - If a client requests sequences older than initialSequence, we query the channels view to get the older results (and backfill the channel caches where appropriate)

The potential issue is that there may be a range of sequences earlier than initialSequence that aren't yet available view the channels view - particularly when running multiple SG nodes. 

Need to work with server team to identify whether it's possible to identify a checkpoint where we can guarantee visibility to the view, and use that as initialSequence (and to start the TAP feed).

**Comment by adamcfraser** [comment]
I think this is closely related to the advanced sequence tracking discussed here:
https://github.com/couchbase/sync_gateway/issues/525#issuecomment-68824555

One scenario that demonstrates this issue is:
1. A running SG node (SG-1) allocates sequence n (increments sync:seq)
2. SG-1 falls into a stop-the-world GC for 5 minutes
3. A second SG node is started (SG-2), and sees sync:seq is n+1.  

Here SG-2 needs to track n as a skipped sequence until it eventually shows up on the feed.  We might be able to use the sequence use tracking described in the link above to identify these on startup.

**Comment by adamcfraser** [comment]
Long-term solution being managed as part of #747

**Comment by amazkovoi** [comment]
Hi @adamcfraser,

Would you be able to share the current plan for this issue?

We are waiting for its resolution in order to move our syncing to use Sync Gateway.

**Comment by adamcfraser** [comment]
This should be addressed by the changes to sequence buffering introduced in 2.6.0.
