### ISSUE TITLE
Insecure mode on default sync_gateway bucket

### ISSUE THREAD

**Issue by jchris** [couchbase/sync_gateway#708]
I am a lazy developer so when I start a new project I often config my iOS simulator apps to sync with `http://localhost:4985` (eg the admin port). I think this is bad practice because it leads to us wanting to do things like enable CORS on the admin port or whatever.

Instead we should have an out-of-the-box insecure mode on the regular port, maybe by adding this to the default config for the `sync_gateway` bucket:

``` js
"users": {
                "GUEST": {"disabled": false, "admin_channels": ["*"] }
            }
```

Making this change would eliminate having to configure Sync Gateway from many hello world applications and tutorials. Eg you could just start it with `./sync_gateway` and it would work for hello world.

**Comment by jchris** [comment]
Thanks @Jamiltz for [the inspiration](http://blog.couchbase.com/ios-background-fetch-to-sync-hacker-news-stories)

**Comment by jchris** [comment]
When doing this work, it might make sense to add a command line flag for CORS, so that cors apps are able to be launched without a config file also, just something like `-corsOrigin=http://example.com`

**Comment by zgramana** [comment]
After discussing this with @adamcfraser we should enable @jchris's insecure mode proposal, but change the default SG behavior to only listen to localhost:4984 by default (just like with the admin port). This prevents accidental disclosure of data on the Internet.

**Comment by jchris** [comment]
Can we schedule this for 1.1 pretty please?

On Friday, March 27, 2015, Zachary Gramana notifications@github.com wrote:

> After discussing this with @adamcfraser https://github.com/adamcfraser
> we should enable @jchris https://github.com/jchris's admin-party
> proposal, but change the default SG behavior to only listen to
> localhost:4984 by default (just like with the admin port). This prevents
> accidental disclosure of data on the Internet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/couchbase/sync_gateway/issues/708#issuecomment-87117206
> .

## 

Chris Anderson
http://www.couchbase.com
http://twitter.com/jchris
"Compromising before you even begin fighting is illogical." – Joshua Wong

**Comment by tleyden** [comment]
Requirements:
- GUEST user enabled by default
- Only bind to localhost by default on port 4984

**Comment by snej** [comment]
Did you really disable connections from remote hosts for _every SG deployment_ that didn't override the `interface` config property?! That seems like it's going to break nearly everyone.

I tried to look at the implementation of this by reading the diffs of #818, but for some reason there's a ton of unrelated stuff in there, like changes to pruneRevisions.

**Comment by adamcfraser** [comment]
That's a fair point - we should be setting localhost:4984 only when using the default config.

**Comment by tleyden** [comment]
Spec regarding interface + guest user access:

```
if the user passed a config file:

  if the user specified -interface on the command line:
    - bind to -interface specified by user

  otherwise, if the user *did not* specify -interface on the command line:

    if the interface is specified in the config file:
       bind to -interface specified in config file

    otherwise, if the interface is *not* specified in the config file:
       bind to 0.0.0.0:4984 (user would have had to have specified GUEST user enabled, so they are responsible)

otherwise, if the user *did not* pass a config file:

  if the user specified -interface on the command line:
    - bind to -interface specified by user

  otherwise, if the user *did not* specify -interface on the command line:
    - bind to localhost:4984

  - GUEST user enabled and has access to * channel

```

Warnings:
- If no users defined (config or bucket), issue a warning + give tips to fix
- If guest user defined, but has no access to channels .. issue warning + tips to fix

**Comment by tleyden** [comment]
@zgramana can you give me the exact text you'd like to see for the warnings?  (in the meantime I will make something up)

**Comment by tleyden** [comment]
@zgramana currently I have:

> No users have been defined, which means that you will not be able to get useful data out of the sync gateway over the standard port.  FIX: define users in the configuration json or via the REST API on the admin port, and grant users to channels via the admin_channels parameter.

and

> The GUEST user is the only user defined, but is either disabled or has no access to any channels.  This means that you will not be able to get useful data out of the sync gateway over the standard port.  FIX: enable and/or grant access to the GUEST user to channels via the admin_channels parameter.
