### ISSUE TITLE
Web application access control

### ISSUE THREAD

**Issue by luiginho97** [couchbase/sync_gateway#713]
Hi to everyone,

I would develop an application that requires the following infrastructure:
- iOS/Android replication and offline sync
- Web clients
- Access control for all items written and read from web and mobile clients
- User management on top of this

How can I build this infrastructure?

I noticed that with CouchBase Lite and Sync Gateway I can perform sync between mobile and server, and manage access to documents using the sync function.
I also noticed that I can manage users using Sync Gateway and create them via the 4985 admin port.

For the web clients purpose, I've implemented a sort of authentication routine that from my Sails.js server application receive credentials from the not-logged user, authenticates them using Passport.js that is connected to a bucket 'users' in Couchbase Server, and gets the session associated to every user using the Sync Gateway Admin REST API _session.

But, assuming that I would get the data the user is granted to access from a view, how can I implement this in Couchbase Sync Gateway?

If I create a view, let's call it 'conversations', in the design document 'dev_chat', and if I try to get its values using HTTP, I create this request:

curl --cookie "SyncGatewaySession=f0ee25648225aa2b842b3298ce39a07c56e20cab"   http://127.0.0.1:4984/sync_gateway/_design/dev_chat/_view/conversations

But the response from the server is always:

{"error":"Forbidden","reason":"forbidden"}

If I look at the Sync Gateway console, I get these logs (donadev is the username associated with the SyncGatewaySession written above):

05:53:55.181387 HTTP:  #024: GET /sync_gateway/_design/dev_chat/_view/conversations  (as donadev)
05:53:55.181441 HTTP: JSON view "dev_chat"/"conversations" - opts map[]
05:53:55.181513 HTTP: #024:     --> 403 forbidden  (0.8 ms)

**Comment by adamcfraser** [comment]
Support for direct view queries are currently limited to the Admin API.  This isn't yet available via the client API, as there are security issues that still need to be resolved.  This is tracked in issue #449.

For your more general questions about infrastructure and application design, can I ask you to post the questions to the forums (https://forums.couchbase.com/c/mobile/) - it's a better place for that type of discussion.
