### ISSUE TITLE
Use sync.atomic to synchronize logging logLevel

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#716]
sync.atomic performs significantly better than RWMutex for single int synchronization.  (see https://go-review.googlesource.com/#/c/3430/).  

Moving loglevel checks (as in base.LogTo) outside the RWMutex will streamline performance when running in non-debug mode.  (logLevel greater than 1)

**Comment by bbrks** [comment]
This is already being done as part of the new logging in 2.1.0
