### ISSUE TITLE
Two parameters, all_channels and roles, in admin REST interface can be removed

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/sync_gateway#723]
According to http://developer.couchbase.com/mobile/develop/guides/sync-gateway/administering-sync-gateway/authorizing-users/index.html, the following two option parameters have no effect.   Should they be removed?

all_channels: Like the admin_channels property, but also includes channels the user is given access to by other documents via a sync function. This is a derived property and changes to it are ignored.

roles: Like the admin_roles property, but also includes roles the user is given access to by other documents via a sync function. This is a derived property and changes to it are ignored. It contains an array of role name strings.

**Comment by ajres** [comment]
Those two properties are read only and derived at runtime, but documentation should not be removed as doing a GET against the user resource will return those values, so a description in the docs is valid.

When creating or updating a user passing these properties has no effect.
