### ISSUE TITLE
Docs: Add supported versions matrix for sync-gw admin guide

### ISSUE THREAD

**Issue by tom-cb** [couchbase/sync_gateway#725]
The sync gateway administration guide in the documentation should include a matrix of which versions of sync gateway are supported and test with which releases of Couchbase Server and Couchbase Lite.

E.g. Sync-GW 1.0.3  is supported and tested as compatible with Couchbase Server 2.5.2

This is to avoid people just using the latest version of Couchbase Server, which may not yet have been verified to work with sync-gw.

**Comment by larryatcouchbase** [comment]
Any updates?

**Comment by ajres** [comment]
Pushed PR to: https://github.com/couchbaselabs/couchbase-mobile-portal/pull/186

Will appear when docs are re-published

**Comment by ajres** [comment]
Also added to Best Practices Doc

**Comment by ghost** [comment]
Greetings. I found the support matrix between the sync gateway and couchbase server, however I am unable to find any support matrix between couchbase lite clients and the sync gateway. Does this information exist?
