### ISSUE TITLE
documents added via sync gateway are not indexed on write

### ISSUE THREAD

**Issue by paulharter** [couchbase/sync_gateway#727]
I was really pleased to find that I could access the couchbase views via the sync gateway admin api and I have been testing this. It looks like documents added via the gateway are not indexed on write, but the view is lazily updated after a read. This causes every first query on a view after new documents have been added to miss them.

I know accessing views like this is not yet a documented part of the api, but it's such a potentially useful feature that I though I'd raise it as a bug.

Here is a python test that shows the problem

https://gist.github.com/paulharter/ce78fa79ac2d6d384941

Thanks

Paul

**Comment by ajres** [comment]
@paulharter Can you post the Sync Gateway version you are running against.

Andy

**Comment by paulharter** [comment]
I'm using couchbase server 3.0.1 community edition and the sync gateway was built from git yesterday using master(5d231cd). Both are running in dockers on Ubuntu.

Paul

**Comment by adamcfraser** [comment]
I believe this is by design - the majority of Sync Gateway writes don't wait for indexing (the exception are writes that trigger a change to access rules).   This is a performance consideration - waiting for the indexable guarantee on writes slows down processing.  

We can review to see if there's a way to support forcing indexable writes in some or all cases.

**Comment by paulharter** [comment]
That would be great.  Not indexing on write, or at least having a way to force indexing, makes the views unusable as what they return is indeterminate. 

Could you maybe add something to the sync function?

function (doc) {
   indexable(true)
}

**Comment by paulharter** [comment]
Hi Adam,

Any news on this? if it might happen and timescale? 

I'm nudging you as it effects some architectural choices I have to make. If it can happen soon I can wait. If it's coming but not for a while I will probably use a temporary synced CouchDB for view queries. but if it's not coming ever I will have to move majority of application data to CouchDB and only use CBS and gateway for syncing.

Thanks

p

**Comment by paulharter** [comment]
Even if documents were only lazily indexed after write it would be usable. The current situation of only indexing after a view is queried doesn't really work. 

Best would be optional index on write per document somehow.

**Comment by shirshir** [comment]
Maybe there is an option to specify the `stale` option when executing the view call. This option is available in the web interface:

![image](https://cloud.githubusercontent.com/assets/660457/6731217/9f32aa72-ce43-11e4-939d-bc7bad2decd7.png)

**Comment by shirshir** [comment]
It appears you can specify that in the call:

```
http://testing.localhost:4985/sync_gateway/_design/all_lists/_view/all_lists?stale=false
```

**Comment by paulharter** [comment]
Hi Shirshir,

Thanks for pointing this out, I didn't realise this was possible. Having this makes the views coherent (if maybe a bit slower?) and will let me share data between mobile and a back end app. 

It would still be nice to have a way to force index on write but it's an optimisation rather than a show stopper.

P

**Comment by adamcfraser** [comment]
Thanks @shirshir for suggesting that.  You're right - for Couchbase Server 3.0 and higher, the indexable flag is no longer required on write for a 'read-your-own-write' scenario - you should be able to do a standard write and then a query with stale=false to see that data.

For Couchbase Server versions 2.x I believe you'd still need to force persistence (with Indexable) on the write to ensure you're going to see the results in your stale=false query.

**Comment by paulharter** [comment]
@adamcfraser @shirshir thanks for helping me with this.  I've just tested it with "stale=false" and it works fine.
