### ISSUE TITLE
Full date and time stamp in log file by default

### ISSUE THREAD

**Issue by couchbasebrian** [couchbase/sync_gateway#736]
Please consider modifying the default time format in the log files so that each line starts with

YYYY-MM-DD HH:MM:SS  < log message >

When the YYYY-MM-DD is missing, it is difficult to ascertain which date a log entry belongs to.

This is useful when grepping the log file when investigating an issue.

**Comment by adamcfraser** [comment]
Duplicates #719, which I suspect I filed while Brian and I were working with the same set of customer logs.  :)
