### ISSUE TITLE
when try to put nonexistent document with rev: Document revision conflict

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#744]
don't have 'fake' doc in the database

```
curl -i -H "Content-Type: application/json" -X PUT http://127.0.0.1:4985/sync_gateway/fake?rev=1-1e8987d0fbdf47a1f4f3f4966669ed36 -d '{"foo":"bar"}'
HTTP/1.1 409 Conflict
Content-Type: application/json
Server: Couchbase Sync Gateway/unofficial
Date: Tue, 17 Mar 2015 22:26:48 GMT
Content-Length: 58

{"error":"conflict","reason":"Document revision conflict"}
```

it's strange to get error related revision conflict when doc not exists, here is more suitable 404 error?

**Comment by adamcfraser** [comment]
In general it's probably non-intuitive that the error message when trying to update a non-existent revision is 409/conflict, regardless of whether the doc exists.  Should include in the API discussions for 2.0.

**Comment by adamcfraser** [comment]
Not high priority, matches CouchDB handling.
