### ISSUE TITLE
Enable taking a bucket offline/online

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#748]
Need to workshop a spec to define both expected behavior and admin API to expose it.

**Comment by ajres** [comment]
Tracking design notes for impl, [here](https://github.com/couchbase/sync_gateway/wiki/Sync-Gateway-DB-online-offline-design-notes)

**Comment by adamcfraser** [comment]
Added notes inline in the wiki.

**Comment by ajres** [comment]
Updated online Wiki based on feedback from @adamcfraser

**Comment by ajres** [comment]
Requested input on design from support via James Mauss

**Comment by ajres** [comment]
Action items to track
- [x] Document implementation design
- [x] Coded take DB Offline
- [x] Coded take DB Online
- [x] Update _resync to use online/offline
- [x] Detection of lost TAP feed impacting service availability
- [ ] Unit Tests complete

**Comment by zgramana** [comment]
@ajres please break these up into new issues and we'll schedule them on Friday's planning day.

**Comment by ajres** [comment]
Broke out action items into issues #907 --> #912 inclusive
