### ISSUE TITLE
Reproduce TAP feed reconnection issues

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#750]
As mentioned in https://github.com/couchbase/sync_gateway/issues/722, the Sync Gateway seems to be having problems reconnecting when losing the TAP feed.

I think it makes sense to first try to reproduce this manually in order to characterize the problem, since it's still not clear how to repro, and then work on reproducing via an automated test case.

_Possible_ steps to repro:
- Run a 1 node couchbase cluster
- Run a sync gateway process pointed to a bucket on couchbase cluster
- Shut down couchbase server
- **Expected** Sync Gateway will emit TAP connection errors
- Restart couchbase server
- **Expected** Sync Gateway TAP connection errors should stop, and the Sync Gateway should be healthy again.

**Comment by mjq** [comment]
I believe the repro steps you outlined will reproduce the problem - I just tried the exact same thing, and found that SG's _changes feed stopped emitting anything at all even after Couchbase was back up. (`curl http://localhost:4985/sync_gateway/_changes` returns a response with zero changes, one minute after restoring Couchbase). Immediately after restarting Sync Gateway, `curl http://localhost:4985/sync_gateway/_changes` correctly returned the complete list of changes.

Here are the go-couchbase errors I see in the logs when I restarted CB.

```
2015/04/27 21:58:47 go-couchbase: Error connecting to tap feed of 127.0.0.1:11210: dial tcp 127.0.0.1:11210: connection refused
2015/04/27 21:58:47 go-couchbase: TAP connection lost; reconnecting to bucket "default" in 2s
2015/04/27 21:58:50 go-couchbase: Error connecting to tap feed of 127.0.0.1:11210: dial tcp 127.0.0.1:11210: connection refused
2015/04/27 21:58:50 go-couchbase: TAP connection lost; reconnecting to bucket "default" in 4s
2015/04/27 21:58:54 go-couchbase: TAP connection lost; reconnecting to bucket "default" in 8s
...
2015/04/27 21:59:02 go-couchbase: TAP connection lost; reconnecting to bucket "default" in 16s
```

The 16s message is the last one I get from `go-couchbase`.

Here's what I see when trying to access `_changes` a minute later (before restarting Sync Gateway):

```
2015-04-27T22:00:58.359Z HTTP:  #11795: GET /sync_gateway/_changes  (ADMIN)
2015-04-27T22:00:58.359Z Error from 'channels' view: no available couch rest URLs
2015-04-27T22:00:58.359Z WARNING: MultiChangesFeed got error reading changes feed "*": no available couch rest URLs -- db.func·014() at changes.go:246
```

**Comment by zgramana** [comment]
@andreibaranouski please update.

**Comment by andreibaranouski** [comment]
I've created tests to reproduce exactly Traun's steps. test output -https://friendpaste.com/2gcacMVaYapyPwuqPhOAs1
after CB  restarted I see that SG is healthy again and doesn't produce errors.

should I try any other steps or other SG/CB versions?

SG commit 7d6c80cf425d
CB 3.0.3-1716

**Comment by andreibaranouski** [comment]
@mjq when you are talking "Here's what I see when trying to access _changes a minute later (before restarting Sync Gateway):" I think you mean restarting CB but not SG? or you also restart SG in your tests?

**Comment by adamcfraser** [comment]
@andreibaranouski I don't see any _changes requests being made after CBS restart in your test output, which is needed to identify whether the TAP feed has been successfully reconnected (and is being used to successfully generate _changes responses).  Let me know if I'm just missing those.  I think the key steps to be added to the test after restarting the CBS are:
- Write new data to the Sync Gateway.
- Validate that this data is returned by a `_changes` request.

**Comment by andreibaranouski** [comment]
okay, in my previous version I had steps like:
1)stop cb
2)continue loading data on SG
3) start CB
4) verify data on CB are synchronized with SG

I extended this scenario with:
1)stop cb
2)continue loading data on SG
3) start CB
4)continue loading data on SG
5) verify data on CB are synchronized with SG + verify _changes

test output ( line 3053 "# restart CB" is the place where CB restarted)
https://friendpaste.com/6V7ny78rMs9oYudMFAhwOp

**Comment by adamcfraser** [comment]
@andreibaranouski  It's not clear from the test output whether changes are being sent post-restart (other than the '75 of 75' logging at the end).  Can you add "Changes" to the log keys, so that changes sent post-restart will be obvious in the logs?

**Comment by tleyden** [comment]
I looked into the code, and it looks fine to me.  Its calling updateDBDocs() which makes a bunch of updates followed by calling common.verifyChanges(), and makes sure there are the expected number of entries on the changes endpoint.

Also while looking into this, I fixed up the Jenkins job:

https://github.com/couchbaselabs/sync-gateway-tests/issues/2

**Comment by tleyden** [comment]
Re-opening.  @andreibaranouski do you know why there are no log lines like:

```
 HTTP:  #004: POST /db/_changes
```

but that come _after_ the restart CB line?

**Comment by andreibaranouski** [comment]
was able to reproduce with cbl-replication-mismatch-restart-cb.js test. output for failed test looks like:

```
2015-06-17T02:51:30.079+03:00 HTTP:  #952: GET /db/_changes

{ results: 
   [ { seq: 1, id: '_user/', changes: [Object] },
     { seq: 2, id: 'mismatch-restart-one_0', changes: [Object] },
     { seq: 3, id: 'mismatch-restart-one_1', changes: [Object] },
     { seq: 4, id: 'mismatch-restart-one_2', changes: [Object] },
     { seq: 5, id: 'mismatch-restart-one_3', changes: [Object] },
     { seq: 6, id: 'mismatch-restart-one_4', changes: [Object] },
     { seq: 7, id: 'mismatch-restart-one_5', changes: [Object] },
     { seq: 8, id: 'mismatch-restart-one_6', changes: [Object] },
     { seq: 9, id: 'mismatch-restart-one_7', changes: [Object] },
     { seq: 10, id: 'mismatch-restart-one_8', changes: [Object] },
     { seq: 11, id: 'mismatch-restart-one_9', changes: [Object] },
     { seq: 12, id: 'mismatch-restart-one_10', changes: [Object] },
     { seq: 13, id: 'mismatch-restart-one_11', changes: [Object] },
     { seq: 14, id: 'mismatch-restart-one_12', changes: [Object] },
     { seq: 15, id: 'mismatch-restart-one_13', changes: [Object] },
     { seq: 16, id: 'mismatch-restart-one_14', changes: [Object] },
     { seq: 17, id: 'mismatch-restart-one_15', changes: [Object] },
     { seq: 18, id: 'mismatch-restart-one_16', changes: [Object] },
     { seq: 19, id: 'mismatch-restart-one_17', changes: [Object] },
     { seq: 20, id: 'mismatch-restart-one_18', changes: [Object] },
     { seq: 21, id: 'mismatch-restart-one_19', changes: [Object] },
     { seq: 22, id: 'mismatch-restart-one_20', changes: [Object] },
     { seq: 23, id: 'mismatch-restart-one_21', changes: [Object] },
     { seq: 24, id: 'mismatch-restart-one_22', changes: [Object] },
     { seq: 25, id: 'mismatch-restart-one_23', changes: [Object] },
     { seq: 26, id: 'mismatch-restart-one_24', changes: [Object] } ],
  last_seq: '26' }
2015-06-17T02:51:30.083+03:00 HTTP:  #953: GET /db/_all_docs
2015-06-17T02:51:30.083+03:00 HTTP:  #953: GET /db/_all_docs

2015/06/17 02:51:30 go-couchbase: call to ViewCustom("sync_housekeeping", "all_docs") in github.com/couchbase/sync_gateway/db.(*Database).ForEachDocID took 569.839157ms
2015/06/17 02:51:30 go-couchbase: call to ViewCustom("sync_housekeeping", "all_docs") in github.com/couchbase/sync_gateway/db.(*Database).ForEachDocID took 569.839157ms

missing 50 ids: mismatch-restart-two_0, mismatch-restart-two_1, mismatch-restart-two_10, mismatch-restart-two_11, mismatch-restart-two_12, mismatch-restart-two_13, mismatch-restart-two_14, mismatch-restart-two_15, mismatch-restart-two_16, mismatch-restart-two_17, mismatch-restart-two_18, mismatch-restart-two_19, mismatch-restart-two_2, mismatch-restart-two_20, mismatch-restart-two_21, mismatch-restart-two_22, mismatch-restart-two_23, mismatch-restart-two_24, mismatch-restart-two_25, mismatch-restart-two_26, mismatch-restart-two_27, mismatch-restart-two_28, mismatch-restart-two_29, mismatch-restart-two_3, mismatch-restart-two_30, mismatch-restart-two_31, mismatch-restart-two_32, mismatch-restart-two_33, mismatch-restart-two_34, mismatch-restart-two_35, mismatch-restart-two_36, mismatch-restart-two_37, mismatch-restart-two_38, mismatch-restart-two_39, mismatch-restart-two_4, mismatch-restart-two_40, mismatch-restart-two_41, mismatch-restart-two_42, mismatch-restart-two_43, mismatch-restart-two_44, mismatch-restart-two_45, mismatch-restart-two_46, mismatch-restart-two_47, mismatch-restart-two_48, mismatch-restart-two_49, mismatch-restart-two_5, mismatch-restart-two_6, mismatch-restart-two_7, mismatch-restart-two_8, mismatch-restart-two_9
duplicate change ids 0, ids: 
duplicate change seqs 0, seqs: 
# verify sync gateway changes feed has all docs in it
ok 31 correct number of docs in _all_docs:75
ok 32 duplicate ids in changes:0
ok 33 duplicate seqs in changes:0
not ok 34 missing changes:50
  ---
    file:   /home/andrei/couchbase_src/sync-gateway-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js
    line:   21
    column: 11
    stack:  
      - |
        getCaller (/home/andrei/couchbase_src/sync-gateway-tests/node_modules/tap/lib/tap-assert.js:439:17)
      - |
        assert (/home/andrei/couchbase_src/sync-gateway-tests/node_modules/tap/lib/tap-assert.js:21:16)
      - |
        Function.equal (/home/andrei/couchbase_src/sync-gateway-tests/node_modules/tap/lib/tap-assert.js:163:10)
      - |
        Test._testAssert (/home/andrei/couchbase_src/sync-gateway-tests/node_modules/tap/lib/tap-test.js:87:16)
      - |
        /home/andrei/couchbase_src/sync-gateway-tests/tests/cbl-replication-mismatch-restart-cb.js:245:15
      - |
        Request._callback (/home/andrei/couchbase_src/sync-gateway-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js:21:11)
      - |
        Request.self.callback (/home/andrei/couchbase_src/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:122:22)
      - |
        Request.EventEmitter.emit (events.js:98:17)
      - |
        Request.<anonymous> (/home/andrei/couchbase_src/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:661:16)
      - |
        Request.EventEmitter.emit (events.js:117:20)
    found:  50
    wanted: 0
```
