### ISSUE TITLE
Test performance with sync_gateway views in separate design docs

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#752]
CBS assigns assigns one core to each design doc.  Would like to see whether we identify any performance improvement on CBS by splitting the sync_gateway docs into three design docs - one for "access" and "role_access" (since they are functionally related), one for "channels" and one for "principals".  It's unclear whether there's a definite performance benefit for the standard perf test, since we're not assigning users to channels mid-run, and backfilling the cache from the channels view relatively rarely.  

Should be quick to validate.

**Comment by tleyden** [comment]
@zgramana 

[perf run 836](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/836/console) is running, using commit https://github.com/couchbase/sync_gateway/commit/43603d9af5100d4cf442b07b34701f7dbea8733b which splits views over design docs as follows:

![screen shot 2015-03-24 at 8 32 53 pm](https://cloud.githubusercontent.com/assets/296876/6817935/fe977284-d264-11e4-91e0-1d9ecf1516b1.png)

I didn't change any of the `sync_housekeeping` views.

**Comment by tleyden** [comment]
@adamcfraser regarding view queries, there seems to be 30 view queries / second on the `access` or `role_access` view -- and this is _after_ the user creation finished.

![screen shot 2015-03-24 at 8 38 20 pm](https://cloud.githubusercontent.com/assets/296876/6818017/f75fe46e-d265-11e4-86d0-a500e96baae7.png)

**Comment by adamcfraser** [comment]
Remind me what form of auth this run is using?

**Comment by tleyden** [comment]
TODO: test this on 3.0.3

**Comment by tleyden** [comment]
We will wait until we have a better set of Gatling tests and then revisit it

**Comment by adamcfraser** [comment]
Relatively low priority, but still a valid scenario to cover when sgload access tests are completed.

**Comment by djpongh** [comment]
We're moving off of Views.
