### ISSUE TITLE
Ability to control log level from config + perfrunner change

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#756]
- Perfrunner: remove rest call, but default to be loglevel 0 or 1, whatever rest call currently does
- Expose config for setting log level  (loglevel: int)

**Comment by tleyden** [comment]
@adamcfraser looks like there is already a perfunner flag `gateway.logging_verbose.true`.  If this is set, then it will skip the [rest call which turns off logging](https://github.com/couchbaselabs/perfrunner/blob/16c34ae859d0979d8c73ffa9037b3b03bce1b262/perfrunner/helpers/rest.py#L384-L395).

**Comment by adamcfraser** [comment]
Oh perfect - we can probably close this issue then, and just set the LogKeys in a custom config file when needed (and run with logging_verbose).

**Comment by tleyden** [comment]
Ok I'll just close this for now and loop back around if we need to control loglevel from the Sync Gw configs.
