### ISSUE TITLE
Perfcluster AWS: Splunk integration

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#760]
Simple integration with SG and or Galing to generate some basic reports that prove the concept works. Ideally add in some syslog OS performance monitoring.

**Comment by tleyden** [comment]
- [x] Manual splunk configuration to collect System Stats
- [x] Manual splunk configuration to collect Sync Gw + Gateload + Couchbase logfiles
- [x] Manual splunk configuration to collect Sync Gw + Gateload exvpars (may require script)
- [x] Enable splunk to collect Sync Gateway and Gateload expvars

Related ticket: - [Ansible scripts should install splunk forwarder](https://github.com/couchbase/sync_gateway/issues/854)

**Comment by zgramana** [comment]
@tleyden please update.

**Comment by tleyden** [comment]
@andreibaranouski this is already done right?

> Enable splunk to collect Sync Gateway and Gateload expvars

Assuming that's done, closing this ticket.  We have an open ticket for @andreibaranouski for cbagent stats that he's driving forward and I'm working with him on: https://github.com/couchbase/sync_gateway/issues/885
