### ISSUE TITLE
Geospatial views is not working trough Sync Gateway

### ISSUE THREAD

**Issue by hydrargentum** [couchbase/sync_gateway#769]
Have problem when using spatial view trough sync gateway. I put it in design document as it described [there](http://developer.couchbase.com/mobile/develop/guides/sync-gateway/accessing-cb-views/creating-and-using-a-view/index.html) just replaced original view with spatial declaration as it described [there](http://docs.couchbase.com/admin/admin/Views/views-geospatial.html)

when i do my PUT everything looks fine, no errors or anything, when i try to access my _spatial i get

> http GET mydomain.com:4985/sync_gateway/_design/spatialphoto/_spatial/points
> 
> HTTP/1.1 404 Not Found
> Content-Length: 44
> Content-Type: application/json
> Date: Sat, 04 Apr 2015 18:01:04 GMT
> 
> {
>   "error": "not_found", 
>    "reason": "unknown URL"
> }

spatialphoto.js

> {
>     "spatial":
>     {
>         "points":{
>             "map":"function(doc, meta) { if (doc.loc) { emit({ type: \"Point\", coordinates: doc.loc}, [meta.id, doc.loc]);}}"
>         }
>     }
> }

When i put ordinal view in same design document, everything works as expected. When i put this design document in couchbase directly, everything is fine also.

**Comment by jchris** [comment]
The patch will require changing code in the go-couchbase package also: https://github.com/couchbase/go-couchbase/blob/master/views.go#L143

**Comment by robinvanemden** [comment]
It would be awesome if geospatial views were available in Sync Gateway API. Might this issue be reactivated / removed from the icebox?

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
