### ISSUE TITLE
changes feed not returning all the changes made 

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#772]
Steps to reproduce: 
- Download the 1.0.4 build from the couchbase web portal
- launch sync gateway with following config.json
  config.json: 
  {
      "interface":":4984",
      "adminInterface":":4985",
      "log":["REST","REST+","HTTP","HTTP+"],
      "verbose":true,
      "databases":{
      "sync_gateway":{
              "bucket":"sync_gateway",
              "sync":`function(doc) {channel(doc.channels);}`,
              "users": {
                      "GUEST": {"disabled": false, "admin_channels": ["*"] }
                      }
              }
      }
  }
- Create document:  
  curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:4984/sync_gateway/
- Update Document, add field key1=value1. 
  curl -H "Content-Type: application/json" -X PUT -d '{"username":"xyz","password":"xyz","key1":"value1"}' http://localhost:4984/sync_gateway/af0f1423dcf60c944eae7742c11d64a6?rev=1-a22379a3475f084e0f5efb2f7814cf2f
- Add second update to the document. Add key2=value2. 
  curl -H "Content-Type: application/json" -X PUT -d '{"username":"xyz","password":"xyz","key1":"value1","key2":"value2"}' http://localhost:4984/sync_gateway/af0f1423dcf60c944eae7742c11d64a6?rev=2-dc03c75636d58ed30b6f31ebbca879c7
- Run _changes http://localhost:4984/sync_gateway/_changes?limit=2
- expected to receive the last two modifications and two revisions id. 
- Got only the last change revision id. 
  Output: {"results":[
  {"seq":4,"id":"af0f1423dcf60c944eae7742c11d64a6","changes":[{"rev":"3-df86ea5064d68f087e33939a29b8d226"}]}
  ],
  "last_seq":"4"}

**Comment by adamcfraser** [comment]
This sounds like it's working as intended - the _changes feed only returns the active revision for a document - it doesn't return inactive revisions.
