### ISSUE TITLE
Sporadic test -race failure on Jenkins

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#778]
On Ubuntu, there are sporadic failures regarding data races:

http://factory.couchbase.com/view/build/view/mobile_dev/view/sync_gateway/view/master/job/build_sync_gateway_master_ubuntu-x64/521/console

I've capture the logs in a gist:

https://gist.github.com/tleyden/9238ad885af289df7b87#file-gistfile1-txt-L323

Logs snippet:

```

2015/04/13 19:59:16.667746 Opening Walrus database sync_gateway_tests on <walrus:>
2015/04/13 19:59:16 entries: [0xc208088a80 0xc208088af0]
2015/04/13 19:59:16 entries: [0xc208088b60 0xc208088bd0]
2015/04/13 19:59:16 cache.lateLogs: [0xc208108840 0xc2081088c0 0xc208108900]
2015/04/13 19:59:16 cache.lateLogs: [0xc208108900 0xc208108a00 0xc208108a40]
2015/04/13 19:59:16 cache.lateLogs: [0xc208108900 0xc208108a00 0xc208108a40]
2015/04/13 19:59:16.671430 Opening Walrus database sync_gateway_tests on <walrus:>
==================
WARNING: DATA RACE
Write by goroutine 29:
  runtime.mapassign1()
      /usr/local/go/src/runtime/hashmap.go:383 +0x0
  github.com/couchbase/sync_gateway/db.TestChannelRace()
      /home/couchbase/jenkins/workspace/build_sync_gateway_master_ubuntu-x64/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache_test.go:654 +0x9b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133

Previous read by goroutine 11:
  runtime.mapaccess1_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:179 +0x0
  github.com/couchbase/sync_gateway/base.LogTo()
      /home/couchbase/jenkins/workspace/build_sync_gateway_master_ubuntu-x64/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/base/logging.go:146 +0xf4
  github.com/couchbase/sync_gateway/db.(*DatabaseContext).watchDocChanges()
      /home/couchbase/jenkins/workspace/build_sync_gateway_master_ubuntu-x64/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/db/assimilator.go:15 +0xb9

```

**Comment by michaelkwok** [comment]
I also saw the same failure on mac ios build.  At this point, the failure seems "consistently" intermittent between the two platforms.

**Comment by michaelkwok** [comment]
Typo, I meant to say the same failure on macosx.

**Comment by tleyden** [comment]
@michaelkwok not sure what you mean by consistently intermittent.  Does it fail every time or sporadically?  How hard to reproduce?

**Comment by michaelkwok** [comment]
If you build from build_sync_gateway_master, one of 2 platforms will fail.  Thought that may help you reproduce the failure faster.  Otherwise, you're right that the failure is sporadic.

**Comment by tleyden** [comment]
I mean if you do 3 build runs on Ubuntu, how many of the 3 runs fail?

**Comment by michaelkwok** [comment]
So far, I see 1 out of 3 failed.

**Comment by michaelkwok** [comment]
Here is a link to the macosx failure as well.
http://factory.couchbase.com/view/build/view/mobile_dev/view/sync_gateway/view/master/job/build_sync_gateway_master_macosx-x64/455/console

**Comment by adamcfraser** [comment]
That looks like the issue we've seen before when the unit tests set the logging level via a direct update of the LogKeys hashmap.

**Comment by michaelkwok** [comment]
All builds passed last night.  Did you have to make any changes to the unit tests?
