### ISSUE TITLE
Version naming scheme of rpm packages prevents upgrades

### ISSUE THREAD

**Issue by OldSneerJaw** [couchbase/sync_gateway#780]
The version naming scheme for rpm packages of Sync Gateway seems to follow the pattern `<BUILD_NUMBER>-<MAJOR>.<MINOR>.<PATCH>` (e.g. `34-1.0.4`).  Since rpm doesn't allow downgrading packages by default, this can cause problems when the build number of a release is less than the build number of the previous release.  For example, 1.0.3 has a build number of 81 (`81-1.0.3`) and is interpreted by rpm as a higher version than 1.0.4 which has a build number of 34 (`34-1.0.4`).  Attempting to upgrade from 1.0.3 to 1.0.4 with the default set of rpm options (`sudo rpm -U couchbase-sync-gateway-community_1.0.4-34_x86_64.rpm`) results in this error: `package couchbase-sync-gateway-81-1.0.3.x86_64 (which is newer than couchbase-sync-gateway-34-1.0.4.x86_64) is already installed`.

I recommend switching to [semantic versioning](http://semver.org/) or, failing that, to move the build number component to the end of the version string.

In the meantime the workaround is to append the `--oldpackage` option to the rpm command: `sudo rpm -U couchbase-sync-gateway-community_1.0.4-34_x86_64.rpm --oldpackage`

**Comment by michaelkwok** [comment]
I agree the right format needs to put the build number at the end of the version string.  That's the naming convention on all our build packages as well.

http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/0.0.0/

Let me open a JIRA ticket for this and we can figure out the person to make the change.

**Comment by michaelkwok** [comment]
Just check-in the changes with Traun's help.  The version was incorrectly set to build number instead of the correct version-build_number.

**Comment by tleyden** [comment]
Here's the commit: https://github.com/couchbase/sync_gateway/commit/1683b7acd857f894a01d66d3da4e6cb72b44a6f4
