### ISSUE TITLE
Windows line breaks in sync function cause SG to fail

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#783]
Multi-line sync functions in config files that are stored with Windows line breaks aren't parsed properly by Sync Gateway.

More details here:
https://issues.couchbase.com/browse/CBSE-1778

**Comment by alex7egli** [comment]
Tested this on Azure Ubuntu 12.04.5 box and Couchbase Sync Gateway/1.1.0(28;86f028c) still fails to start with windows line breaks. Have to run through cygwin dos2unix command to get sync gateway to start after editing the config file on windows. Error:
2015-07-13T13:51:29.536Z FATAL: Error reading config file sync-gateway-config.json: invalid character '\r' in string literal -- rest.ParseCommandLine() at config.go:336

**Comment by ajres** [comment]
@alex7egli 

Can you upload your breaking config to a gist and post a link to this ticket.

Andy

**Comment by alex7egli** [comment]
It's for our company's database, so for security reasons I would prefer not to upload the file. Would a snippet be sufficient?

**Comment by ajres** [comment]
@alex7egli 

Any valid self contained config.json that exhibits the issue would be fine.

Andy

**Comment by alex7egli** [comment]
Just tested with this config and same issue with same error:
https://gist.github.com/alex7egli/f136b8a9e8ed99de7d06

I upgraded from SG Community 1.0.2 to SG Enterprise 1.1.0 by doing dpkg -r on the old sync gateway package, and then dpkg -i on the new package.

**Comment by ajres** [comment]
That config worked on MAC OS X, but I didn't see any \r chars, it possible they got stripped when unpacking the archive. I'm going to run the same config with SG on Ubuntu 12.

**Comment by alex7egli** [comment]
The steps I use to update our config are:
1) Modify the file on my windows machine in a text editor.
2) Copy them to our server using WinSCP
3) Restart sync gateway

I have to run dos2unix to on the config file before copying it to the server though to fix the endline chars for unix.

**Comment by ajres** [comment]
I have reproduce this issue on 1.1.0 enterprise binary release.

Release note says that "#783 Windows line breaks in sync function cause SG to fail" is included, but it is not.

Testing against latest master, Sync Gateway starts without error.

**Comment by ajres** [comment]
Reclosing this ticket, issue with release build is tracked in new issue #987
