### ISSUE TITLE
Database.Compact method is obsolete; it and its view can be removed

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#791]
`Database.setOldRevisionJSON` now stores the revision body in the bucket with an expiration time of 300 seconds, so it's no longer necessary to clean up those docs by hand. This makes `Database.Compact` obsolete, and also the `old_revs` view; they can be removed.

(Actually `Database.Compact` should be re-implemented to get rid of unreferenced attachments. There's currently a `VacuumAttachments` method for that, but its implementation just returns an error. I believe we have an old issue filed agains this...)

**Comment by bbrks** [comment]
`old_revs` is gone already.

Compact is now used when running with xattrs to remove purged tombstones from views and/or GSI indexes, since Server doesn't have a way to clean those up.

The VacuumAttachments method mentioned is at #1648
