### ISSUE TITLE
TestLowSequenceHandling with -cpu 4 fails on forestdb_bucket branch

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#800]
Although I can't reproduce with Walrus, I think it might be a real bug in either the test or the code, but only manifests itself when using the forestdb_bucket branch.

To reproduce
- Use e85b245e on forestdb_bucket branch
- Run `./test.sh -cpu 4 -run TestLowSequenceHandling$ -v` several times, it should be reproducible within 10 tries

Test failure logs:

https://gist.github.com/tleyden/4a0888fc7f3293b4e855

Test pass logs:

https://gist.github.com/tleyden/bb0f722d41bab733f229

@adamcfraser do you remember why you added this call to `time.Sleep()` in `TestLowSequenceHandling`?

```
    db.changeCache.waitForSequenceWithMissing(4)
    time.Sleep(50 * time.Millisecond)
    err = appendFromFeed(&changes, feed, 2)
```

when I bumped it to sleep 1500 ms instead of 50, I wasn't able to reproduce the issue after 20 tries.  (is there a known race that the sleep for 50 ms is trying to avoid that I might be hitting?

**Comment by tleyden** [comment]
Note to self: [Linux Kernel Tuning for C500k](http://urbanairship.com/blog/2010/09/29/linux-kernel-tuning-for-c500k/)

**Comment by adamcfraser** [comment]
This is a timing issue - the relative timing of the _changes iterations and feed processing can result in variations in sequence ordering on the response.  This test (and others) should probably be changed to assert based on these two variations:
1. Process one sequence at a time (enforcing using waitForSequence), to enforce the ordering. This would be recommended for testing specific compound sequence handling flows.
2. Process multiple sequences at a time, but change assertions to validate that the expected sequences appear on the feed, without enforcing ordering/compound keys.

**Comment by tleyden** [comment]
Ok thanks for the heads up.  Regarding `waitForSequence()`, we should add the "backoff" enhancement  so it doesn't add unnecessary delays to the tests.

**Comment by adamcfraser** [comment]
Definitely.
