### ISSUE TITLE
Add the channel to the document via Admin REST API

### ISSUE THREAD

**Issue by extart** [couchbase/sync_gateway#802]
In my application complex logic. There are one to many relationship.
How can I add a channel to the document via Admin REST API? I do not really understand how I can use this function sync, because the document belongs to the channel based on fairly complex logic. Just when assigning a channel to the document, you need to add a channel other documents.

**Comment by ajres** [comment]
@extart you are correct via the sync function only the current document can be assigned to one or more channels.

If you are able to share your app logic we might be able to suggest ways to make it work with the sync function.

Andy

**Comment by extart** [comment]
Thanks for the answer!
The logic may change with time ... And it needs to be considered when designing.
If we have a server application that creates users and can add / edit a document via REST API, why make the logic of an add channel to document to another entity (sinc function)? In fact, the addition of the channel to the document does not apply to most of synchronization, it is the business logic.
In making this logic in sync function is impossible to create, and even more difficult to develop an application Todolite (sample application) ...
Maybe there is a way to assign a channel to the document from the server application? Otherwise, it is very illogical ...

**Comment by snej** [comment]
Our issue tracker is for bug reports, not questions; please ask questions on the forum or mailing list.
