### ISSUE TITLE
SG sometimes remains more than revs_limit in its storage

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#803]
SG commit df9980fef7217f26
couchbase-lite-ios commit feb7ff5
test https://gist.github.com/andreibaranouski/0ec8ac6d7f07c1a72605

automation steps:
1. git clone https://github.com/couchbaselabs/sync-gateway-tests.git
2. cd sync-gateway-tests 
3. npm install
4. set env variables for sync_gateway & LiteServ like
export SYNCGATE_PATH=~/couchbase_src/sync_gateway/bin/sync_gateway
export LITESERV_PATH=/Users/andrei/couchbase_src/couchbase-lite-ios/build/Products/Debug/LiteServ
5. node tests/a-cb-presetup.js
(this pre-setup script will create 'db' bucket on CB local cluster)
6. replace tests/cbl-large-revisions-compact-revs-limit.js content with https://gist.github.com/andreibaranouski/0ec8ac6d7f07c1a72605
(gist file suspends test on this issue)

result:
I launch SG with config file https://github.com/couchbaselabs/sync-gateway-tests/blob/master/config/admin_party_revslimit.json that contains "revs_limit" : 10 but not all documents have only 10 latest revisions, about half of them have all history revisions

scenario steps:
1.start LiteServ client
2. start syncgateway with tests/cbl-large-revisions-compact-revs-limit.js

```
running /Users/andrei/couchbase_src/sync_gateway/bin/sync_gateway [ '-interface',
  ':9888',
  '-adminInterface',
  ':9889',
  '-url',
  'walrus:',
  '-bucket',
  'db',
  '/Users/andrei/couchbase_src/sync-gateway-tests/tests/../config/admin_party_revslimit.json' ]
```

3.load 10 docs in large-revisions-revslimit liteServ db
4. set continuous push replication to gateway
5. update on SG each document 40 times
6. update on liteServ each document 40 times
7. set continuous pull replication from gateway
8. wait ...
9. verify that number of available revisions for every doc by http://127.0.0.1:59851/large-revisions-revslimit/large-revisions-revslimit_4?revs_info=true equals revs_limit=10

result:
large-revisions-revslimit_4 doc has 81 "available" revisions https://friendpaste.com/22unLv3umxXLaUDGhNnj8F
the expected result should be as for large-revisions-revslimit_1 doc
https://friendpaste.com/4hVeAsEYAqV9Qx2iLgAaCz , num of "available" + "missing" revisions equals revs_limit=10

test output https://friendpaste.com/22unLv3umxXLaUDGhNMCjx

Question:
I'm able to reproduce it with CB cluster too. Do we have any sg API to get all revisions as we have for lite db (revs_info=true)? 

seems like the same issue was described https://groups.google.com/forum/#!msg/mobile-couchbase/fGd-XmHwb4o/ZZwXc2aTf40J

**Comment by adamcfraser** [comment]
If you've got conflicts in your revision history, I assume you're hitting https://github.com/couchbase/sync_gateway/issues/501 (which was fixed last week, after the commit you're testing with).  Can you retry with the current build on master?

**Comment by andreibaranouski** [comment]
still reproduced with commit c3599690e5462efdba947

**Comment by adamcfraser** [comment]
Can you attach a copy of the final document?  I'm curious what the revision tree looks like for the document, since revs_limit pruning is dependent on the branching of the revision tree.

**Comment by andreibaranouski** [comment]
Hi @adamcfraser 
if I understand you correctly, you need the contents of a document where ultimately revs_limit greater than expected( =10) https://friendpaste.com/DOhcqoqRQ5IuWMzyyyTzu

**Comment by adamcfraser** [comment]
The real goal is to understand whether there's branching going on in the revision tree for the document, and that's why there are more revisions remaining than the revs_limit value (revs_limit defines the pruning level for each active branch).  That can be checked by looking at the _sync metadata from the latest revision of the document.

**Comment by sapieneptus** [comment]
Hey @adamcfraser - I'm seeing the same as well from SG 1.1.0 (I'm not sure I was ever able to verify that #501 was actually fixed for us). I can provide a doc that has too many revs, despite having `revs_limit : 10` in our config.json (though we'd probably have to email the gist link for security reasons).

**Comment by adamcfraser** [comment]
@sapieneptus Sure - you can send me the gist link at adam.fraser at couchbase dot com.

**Comment by adamcfraser** [comment]
@sapieneptus The doc you shared has a lot of open branches (unresolved conflicts).  Revision pruning needs to maintain the revs_limit (10, here) for any non-tombstoned branches, so I suspect that's the reason you're seeing so many revs here.

**Comment by sapieneptus** [comment]
@adamcfraser I see - I guess I had assumed that revision pruning would also discard the conflicts older than `revs_limit`. 

So we'd need to manually handle the conflicts and then pruning should work? In our use case we don't particularly need to maintain any of the conflicts, is there a non discriminatory way to axe them from the sync_gateway? Or is this something we'd have to do clientside (e.g. iOS or Java side) ?

**Comment by adamcfraser** [comment]
@sapieneptus Revision pruning needs to maintain some history for any non-tombstoned revisions, to handle the potential scenario where those revisions become the active/winning revision (e.g. if other branches are tombstoned).  

Conflict resolution needs to be done client-side.
