### ISSUE TITLE
Low Ops during bucket shadowing

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#805]
Steps to produce: 
- Install 3.0.3 release with single node and install Beer sample bucket
- Configure bucket shadowing on 1.1 release sync gateway
- Launch sync gateway
- Using cbworkloadgen load 1000 items on the server bucket. 
- Very low ops observed on sync gateway (13~14 ops/sec) during the shadowing of the bucket.

**Comment by adamcfraser** [comment]
What type of items are being loaded using cbworkloadgen?  1000 unique docs?

**Comment by ashvindersingh** [comment]
Yes unique docs. Used the following command:
/cbworkloadgen -n localhost:8091 -b server-bucket -i 2 -s 1000 -j --prefix=ddd

**Comment by adamcfraser** [comment]
Not a priority - focusing on next-gen alternatives to bucket shadowing.
