### ISSUE TITLE
The revision Id passed in the Etag header should be enclosed in quotes

### ISSUE THREAD

**Issue by elevine** [couchbase/sync_gateway#808]
According to the HTTP/1.1 specification, the Etag header's value should be enclosed in quotes (see: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.19 and https://www.rfc-editor.org/rfc/rfc2616.txt (page 29)).  

When making a request to the GET /{db}/{doc} endpoint, the Etag header will be something like:

```
Etag:2-6e3e61c67012f3702a2b454227696c91
```

We noticed this, because it caused the following exception in the .Net HttpHeaders class while processing the response:

```
System.FormatException: Invalid format.
04-28 12:07:53.368: I/mono-stdout(3091):   at System.Net.Http.Headers.HttpHeaders.AddInternal (System.String name, IEnumerable`1 values, System.Net.Http.Headers.HeaderInfo headerInfo, Boolean ignoreInvalid) [0x00000] in <filename unknown>:0 
04-28 12:07:53.368: I/mono-stdout(3091):   at System.Net.Http.Headers.HttpHeaders.Add (System.String name, IEnumerable`1 values) [0x00000] in <filename unknown>:0 
```

This was observed with both the 1.0.3 version of the Sync Gateway, and a recent build off the master branch.

**Comment by ajres** [comment]
Fixed via PR #822
