### ISSUE TITLE
webhook: Not all revision ids are sent with webhook events.

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#811]
Steps: 
- Install and configure Sync Gateway 1.1 release with following config.json
- {
  "log": ["CRUD", "REST+","EVENTS","EVENTS+","HTTP+"],
  "verbose":true,
  "facebook" : {
      "register" : true
      },
  "databases": {
      "db": {
          "server": "walrus:",
          "sync": `function(doc){channel(doc.channels);}`,
          "users": {"GUEST": {"disabled": false, "admin_channels": ["*"] }},
          "event_handlers": {"document_changed":[{"handler":"webhook","max_processes" : 500,"wait_for_process" : "600000","url":"http://testhttpserver:port","timeout":60}] }
      }
  }
  }
- Create 100 docs using and 10 revisions for each document. 
- On the Test http server receiving post request only two revisions are given, example: 
  '{"_id":"api-revision1_299","_rev":"2-4b5c350a8c880c3c4ad24b0a25724475","_revisions":{"ids":["4b5c350a8c880c3c4ad24b0a25724475","46d14cc5eea4aa91c14b208ca7698687"],"start":2},"data":"12345"}': '' }

All the revisions should be provided by SG

**Comment by adamcfraser** [comment]
Is this different than #812?

**Comment by ashvindersingh** [comment]
Yes, in #812 no events are getting generated for documents. In this bug not all revisions are sent in the body of the Http event msg.

**Comment by adamcfraser** [comment]
The example you provide in the ticket is based on the event for revision 2, so the number of revisions shown looks correct.  Have you got additional output from the test HTTP server with examples where the expected set of revisions isn't shown?

**Comment by ashvindersingh** [comment]
I retested this and found that after 10 revisions, the rev ids get pruned and again starts with the previous rev-id. https://gist.github.com/ashvindersingh/aa9f3458c8b0cfa9f9ed

**Comment by ashvindersingh** [comment]
Please find the code to reproduce this issue here: https://gist.github.com/ashvindersingh/dc170958c09e79ba3e28 

To run this script. Please:
- Clone https://github.com/couchbaselabs/sync-gateway-tests.git
- copy the script into /tests/ folder
- Please overwrite the admin_party.json with https://gist.github.com/ashvindersingh/dbd2ae3b0c328a209c4f
- run the tests: node tests/tests_webhooks_rev811.js

**Comment by adamcfraser** [comment]
I suspect the rev id "pruning" is not coming from the Sync Gateway - it's the normal pruning of the revision history when the client does push replication to the client.  I'm not familiar enough with the android replication logic (which I think you're using to generate data here?), but have you validated what the requests to sync gateway look like?

Webhooks should be forwarding the same update that was sent to and processed by Sync Gateway - there's no expectation for Sync Gateway to be forwarding information (such as full revision history) that's not included in the original request.

**Comment by adamcfraser** [comment]
Reviewed with Ashvinder.  This is the expected behaviour - the _revisions property is what's coming through from LiteServ for that particular update.  Important to note that we're just talking about the _revisions property in the doc having less than the full set - not that some revisions aren't resulting in webhook invocation.
