### ISSUE TITLE
webhooks: Not all events are getting POSTed

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#812]
Steps: Install Sync Gateway 1.1 release with following configuration. 
- {
  "log": ["CRUD", "REST+","EVENTS","EVENTS+","HTTP+"],
  "verbose":true,
  "facebook" : {
      "register" : true
      },
  "databases": {
      "db": {
          "server": "walrus:",
          "sync": `function(doc){channel(doc.channels);}`,
          "users": {"GUEST": {"disabled": false, "admin_channels": ["*"] }},
          "event_handlers": {"document_changed":[{"handler":"webhook","max_processes" : 500,"wait_for_process" : "600000","url":"http://TestHTTPServer:port","timeout":60}] }
      }
  }
  }
- Start wireshark: 
- Create 100 documents 
- ensure all the documents are replicated to SG
- Add 10 revisions for each document. 
- No Events are generated for some documents. No POST request was observed on wireshark being sent for the missing events.

**Comment by adamcfraser** [comment]
What's the timing on the creation of the revisions for each document?  If multiple revisions for a document are being deduplicated by the server, we don't expect those to generate events.

**Comment by adamcfraser** [comment]
Details on which docs/revisions aren't sending events would be helpful.  In particular, are any of the latest revisions for each document missing?

**Comment by ashvindersingh** [comment]
Here is link to wireshark logs: https://www.dropbox.com/s/vglr5kjnrlxa2e6/sync_gateway_webhooks_no_post.pcapng.gz?dl=0
In this particular log file 1000 documents are getting generated. After the documents are replicated I start adding revisions to the documents. The last event my test httpserver got was for document 990. Also missing is events of documents 600- 800. 
On my testhttp server I did not get events for ~ 40% of the documents.

**Comment by adamcfraser** [comment]
Reviewed in detail with Ashvinder.  Difficult to reproduce with the current testing methodology, work still in progress.

**Comment by adamcfraser** [comment]
I'm still not able to reproduce this scenario.  Tested using this test scenario (based on the one shared for 811, but creating 100 docs then 10 revisions per doc, as described above:
https://gist.github.com/adamcfraser/ae5e377cb6e0edf8d08f

Made a minor modification to the testhttpserver.js to output a count of the POSTs made:
https://gist.github.com/adamcfraser/3987479d0d87fc43e337

Running the above resulted in the expected number of POSTs (1100):
https://gist.githubusercontent.com/adamcfraser/fcb6b9aaf7a203ef2327/raw/gistfile1.txt

@ashvindersingh - can you provide some more specifics to help me reproduce the issue you were seeing?

**Comment by ashvindersingh** [comment]
Hi @adamcfraser I was able to reproduce this issue on older version of 1.1 release. Here are the steps to reproduce:
- Please clone and setup https://github.com/couchbaselabs/sync-gateway-tests.git repo
- Overwrite admin_party.json with admin_party_w_webhooks.json by copying the contents from admin_party_w_webhooks.json to admin_party.json.
- Please copy tests/posthttpserver.js (or https://gist.github.com/adamcfraser/3987479d0d87fc43e337) to an external server. Running the httpserver on the same host will not reproduce this issue. 
- launch the testhttpserver.js using node
- cd into sync-gateway-tests
- node tests/cbl-webhook_events_not_posted.js

The test script creates 100 documents with 11 revisions. (the script has 10 revisions but count is starting from 0 so 11 revisions.) 

expected events = 100 docs \* 11 revisions + 100 (liteserv docs, unintentional addition) = 1200
But received only 1013 events. 

Here are the sync gateway logs: https://gist.github.com/ashvindersingh/1447912be30eca6d996d

Please note some lines are printed twice as both stderr and stdout are printed by sync-gateway-tests framework. 

Also this is network sensitive test, so the webhooks received count may vary.

**Comment by adamcfraser** [comment]
Have you tested this against the current 1.1 release?

**Comment by ashvindersingh** [comment]
The latest release 1.1.0 http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/release/1.1.0/1.1.0-12/ fixes the issue.

**Comment by ashvindersingh** [comment]
I have tested with 1000 documents and 21 revisions for each document. The testHttpserver got the expected count of 22K events (count based on the calculation provided above).

**Comment by adamcfraser** [comment]
QE identified a followup issue - SG was reporting i/o timeout errors when processing high volumes of webhook events (440K event test), of the form:

Error attempting to post to url http://172.23.105.219:9091: Post http://172.23.105.219:9091: dial tcp 172.23.105.219:9091: i/o timeout

This was addressed with PR https://github.com/couchbase/sync_gateway/pull/846.
