### ISSUE TITLE
Add option to retry delivery of previously failed webhook events

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#813]
The MVP of webhooks in 1.1 was scoped to "best effort" and did not include any retry guarantees.

This enhancement request adds in a mechanism for durable queuing, configurable retry processing, and a deadletter queue for messages that exceeded the maximum retry count specified by the user (or the default).

**Comment by zgramana** [comment]
Needs a spec.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.

**Comment by zachengel** [comment]
> Closing based on age, can reopen in JIRA if there's a compelling use case.

hi @adamcfraser 
We are relying on receiving  webhook events from github.
we would like to know how to guarantee the delivery in case of an intermittent failure to deliver, such that a simple re-transmit at a later time can solve. 

Is there any setting that can ensure that failed events / messages will be re-transmitted ?
or is there a way to automatically trigger a re-transmit of events that failed to be delivered?

thank you 
Zach
