### ISSUE TITLE
Session API does not honor the password parameter

### ISSUE THREAD

**Issue by deefactorial** [couchbase/sync_gateway#821]
When I set the session password:

``` sh
http POST https://cloud.openmoney.cc:4985/openmoney_shadow/_session name=deefactorial@gmail.com password=123456
HTTP/1.1 200 OK
Content-Length: 135
Content-Type: application/json
Date: Mon, 04 May 2015 01:02:50 GMT
Server: Couchbase Sync Gateway/unofficial

{
    "cookie_name": "SyncGatewaySession", 
    "expires": "2015-05-05T01:02:50.468612215Z", 
    "session_id": "blablablablablabalballbalalballbalablbllbalablbal"
}
```

Then try to get data using that password:

``` sh
http -a deefactorial@gmail.com:123456 GET https://cloud.openmoney.cc:4984/openmoney_shadow/_session
HTTP/1.1 401 Unauthorized
Content-Length: 49
Content-Type: application/json
Date: Mon, 04 May 2015 01:01:41 GMT
Server: Couchbase Sync Gateway/unofficial
Www-Authenticate: Basic realm="Couchbase Sync Gateway"

{
    "error": "Unauthorized", 
    "reason": "Invalid login"
}
```

This worked before there were some major updates.
I'm using the latest git version of sync_gateway, compiled yesterday.

Cheers,
Dominique

**Comment by adamcfraser** [comment]
As far as I know, there's never been a concept of a 'session' password.  The password you're sending on the first request to the admin port will be ignored.  When making a similar POST request against the public API, it expects the user's password to be provided (not a session-specific password).

I sanity checked this flow against the 1.0.2 and 1.0.3 builds, and the behaviour is the same as you've described above.  If you've got a specific build where this worked as you described, pass along the details and I can take a closer look.

**Comment by deefactorial** [comment]
That's strange, I used it this way for a while and it worked fine. I fixed my issue by updating the users password in the sync_gateway to the session-specific password. 

Thanks for your comments
