### ISSUE TITLE
Enhance gateload to trigger view queries

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#825]
In gateload:
- Find a userid of a randomly selected puller
- On every doc, modify gateload to add a doc property called targetUser which tells it grant access to a specific puller

On sync gw config:
- Sync function pulls that field and calls `access(doc['targetUser'], channelname)` -- for channelname, use docid.

Cluster config:
- 3 cbs
- 1 gateway 
- 1 gateload

**Comment by tleyden** [comment]
- [x] Modify gateload to support an extra config var that will cause it to add the targetUser: {puller username} to each doc it pushes
- [x] Update gateload config to add config var: https://github.com/couchbaselabs/perfrunner/blob/master/templates/gateload_config_template.json
- [x] Update sync gw config to add the call to `access()`
- [x] Test run against couchbase server 2.5
- [x] Test run against couchbase server 3.0.3

**Comment by tleyden** [comment]
> Update gateload config to add config var

Added to my perfrunner fork (which I recently rebased off couchbase/perfrunner master)

> Update sync gw config to add the call to access()

See http://git.io/vJioy

**Comment by tleyden** [comment]
[Perf run 904](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/904/) is running against Couchbase 2.5

**Comment by tleyden** [comment]
Unfortunately the output for perf run 904 wasn't captured, but after it had reached the peak user load, I was seeing PushToSubscriberInteractive p95 times around 2 seconds.

Also in the sync gw logs:

```
2015/05/04 18:02:26 go-couchbase: call to ViewCustom("sync_gateway", "access") in github.com/couchbase/sync_gateway/db.(*DatabaseContext).ComputeChannelsForPrincipal took 1.130648461s
```

With [Perf run 905](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/905/console) running Couchbase Server 3.0.3:
- PushToSubscriberInteractive p95 is [187 seconds](https://gist.github.com/tleyden/3a5fb8bf3b937b46907c#file-gistfile1-txt-L704)
- In the Sync Gw logs there are reported view queries taking 30 seconds: 

`2015/05/04 19:03:14 go-couchbase: call to ViewCustom("sync_gateway", "access") in github.com/couchbase/sync_gateway/db.(*DatabaseContext).ComputeChannelsForPrincipal took 30.431952943s`

**Comment by tleyden** [comment]
With [Perf run 908](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/908/) running Couchbase Server 4.0.0-1817:
- PushToSubscriberInteractive p95 went as high as [82 seconds](https://gist.github.com/tleyden/e530eb60b59c1dc41a20#file-gistfile1-txt-L678)
- In the Sync Gw logs there are reported view queries taking as long as 37 seconds:

```
2015/05/04 23:13:17 go-couchbase: call to ViewCustom("sync_gateway", "access") in github.com/couchbase/sync_gateway/db.(*DatabaseContext).ComputeChannelsForPrincipal took 37.015453252s
```

**Comment by adamcfraser** [comment]
For Perf run 905, it looks like the P95 value was actually [187s](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/905/artifact/gateload_expvar_0.json) by the end of the run.  So 4.0.0 might be a moderate improvement over 3.0.3, but both are well outside the KPIs.  Especially since the P99 number is even higher (791s for 3.0.3, 608s for 4.0.0).

**Comment by adamcfraser** [comment]
I've created a stale=ok testing branch based on the latest master (feature/stale_ok).  Can you rerun the 3.0.3 test against that branch, to get confirmation that the stale=false calls against the access and role_access views are the only source of the increased latency we're seeing?

**Comment by tleyden** [comment]
[Perf run 909](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/909/) is running against the `feature/stale_ok` branch.

**Comment by tleyden** [comment]
Results for `feature/stale_ok`:
- [PushToSubscriberInteractive P95 is 2.9 seconds](https://gist.github.com/tleyden/a51848c471f205387878#file-gistfile1-txt-L665)

**Comment by tleyden** [comment]
Closing this out since there are no more action items
