### ISSUE TITLE
Aggressively validate config json

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#826]
On validation failure, either fail to start sync_gateway, or return an appropriate HTTP status response code.

**Comment by adamcfraser** [comment]
Two main goals for this validation:
1. Identify any unexpected keys in the JSON (currently ignored), and throw an error on startup when found.
2. Validate any key values we expect to be in a specific range/format.  Several of these scenarios may already being handled by individual validations during config load.

If we can accomplish both of these goals by validating against a JSON schema, that would be the preferred approach.  In this case we should include a review of existing validations to identify which ones could be covered by the schema.

**Comment by zgramana** [comment]
Docs on [JSON-Schema validation](http://json-schema.org/latest/json-schema-validation.html).

**Comment by adamcfraser** [comment]
Based on meeting to review the specs for this ticket:

Validation
- Validation should be based on JSON Schema
- For config parsing errors, include a shortened URL to the config documentation in the log warning
- Continue to support the use of multiple config files for things like DB definitions.

Command line support:
- We should plan to deprecate the majority of command line parameters for 2.0.  For 1.2.0, have SG spit out a ' will be deprecated' warning on startup when command line parameters are used.

Documentation
- Docs should focus on the config file approach.  

Next Steps
- Implement the initial JSON schema definition (without property value validation) based on the existing property definitions in config.go.  Once that's complete, have a working session to define validation rules for those properties.

**Comment by tleyden** [comment]
Having the sync function embedded in the config will make it problematic to validate the JSON.

**Comment by tleyden** [comment]
To give more detail .. I probably should have said that Sync Gateway configs are known to be invalid JSON due to the inline Sync Functions.

To see that, go to https://raw.githubusercontent.com/couchbase/sync_gateway/master/examples/democlusterconfig.json# and then do “view source”, and then paste it into http://jsonformatter.curiousconcept.com/.  It will give JSON validation errors.

![screen shot 2015-06-23 at 4 32 57 pm](https://cloud.githubusercontent.com/assets/296876/8319607/9af0ad42-19c5-11e5-85b7-5e4176645c2a.png)

**Comment by adamcfraser** [comment]
I think this just means we want to do any JSON schema validation after the existing conversion of back quoted strings (e.g. https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/rest/config.go#L259)

**Comment by adamcfraser** [comment]
Should include checking for duplicate entries (#2001).

**Comment by bbrks** [comment]
2.6.0 now checks the config for unknown fields #3974 and fails to start
