### ISSUE TITLE
Gatling scenario - Document CRUD

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#829]
This was identified as a Tier 1 Gatling performance scenario
- [ ] 5. Document CRUD (not just inserts)
  - [ ] 5b. Large revision trees
  - [ ] 5c. Conflicting updates
  - [ ] 5d. Document delete
        - would need a lever for insert/update/delete distribution
  - [ ] 5e. Single doc vs. bulk docs, single get vs bulk get

**Comment by adamcfraser** [comment]
Closing - tracking current perf scenarios in testkit.
