### ISSUE TITLE
Perfrunner: not attaching expvars

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#835]
Fixed by:
- Modifying gateload to write it's expvars to a file during the run and right before exiting
- Modifying perfrunner to grab the expvars file rather than trying to pull expvars from gateload via curl

Successful perf run: http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/912/  (this works because Jenkins is using my fork of perfrunner)

Still remaining to do:
- [ ] Gerrit change request to merge into perfrunner master branch

**Comment by tleyden** [comment]
I think there still might be some issues with this.  On [perf run 927](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/927/), the attached gateload expvars did not have the full user count, so it appears that it may have somehow grabbed an older snapshot.

**Comment by adamcfraser** [comment]
Even the SG expvars look incorrect/stale for that run.
