### ISSUE TITLE
Official docs for webhooks

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#837]
We need to incorporate the current informal webhooks documentation (https://github.com/couchbase/sync_gateway/wiki/Webhooks) into the official docs.

**Comment by JeffThomasWriter** [comment]
I have begun working on this. Jeff

**Comment by JeffThomasWriter** [comment]
Only HTTP posts are mentioned. Are HTTPS POSTs possible? Is that determined by simply providing an HTTPS URL in the URL? Is there a within-datacenter or use-VPN assumption?

**Comment by adamcfraser** [comment]
HTTPS is supported - all that's needed is to define the HTTPS URL.  The implementation assumes that the Sync Gateway node is able to reach the endpoint defined for the webhook.

**Comment by JeffThomasWriter** [comment]
More questions: does the document revision that is posted include both doc and oldDoc (thus "filter": `function(doc, oldDoc) {...? Filtering resembles the testing-doc-properties aspect of the sync function, but I take it you not use requireRole, requireUser, access, role, throw, or channel in a webhook event handler.

**Comment by adamcfraser** [comment]
The filter function (currently) only takes doc as a parameter, not oldDoc.  You're correct that this isn't related to sync function execution - so the access-related calls aren't made.  

There's an enhancement in the backlog (https://github.com/couchbase/sync_gateway/issues/899) to add oldDoc to the filter function parameters.

**Comment by JeffThomasWriter** [comment]
Adam, more questions: I can see that this can be done, but am not clear on the use cases (why do it) for development/test and production. What software would be on the other end? Connectors? Analytics? Auditing? What would be on the other end that is worth the security risk of sidestepping the sync function's control of authorization? Well, OK, I understand the endpoint https://we-read-everything.nsa.gov/, but what about other endpoints? And how does this compare to a changes feed? Thanks.

**Comment by adamcfraser** [comment]
The key goal is to simplify the integration for developers who want to build services that react to document changes.  Some obvious use cases are things like notification (send an email/SMS when certain documents change), auditing/logging, or more generally input to some external system.

I don't follow your point about a security risk.  Any updates that are sent by webhooks have already been through the standard authorization path (sync function) - this isn't bypassing the sync function in any way.  I'd expect users with concerns about security to be targeting the webhook to something behind their firewall for processing.

There is some similarity to the Changes Worker pattern (http://developer.couchbase.com/mobile/develop/guides/sync-gateway/changes-worker/pattern/index.html), but with less work involved for the user (they don't need to build a _changes client).  There's also less latency when using webhooks, as the event is posted during document write, and doesn't have to wait for the document to reappear over the server mutation stream.

**Comment by atom992** [comment]
for auditing/logging, It is necessary to add request user as input for webhooks I think.

**Comment by adamcfraser** [comment]
Docs are pending my review - assigning to myself to get that wrapped.  Issue raised by @atom992 is tracked as enhancement #1053.

**Comment by atom992** [comment]
Is there a roadmap?

**Comment by adamcfraser** [comment]
@atom992 #1053 is currently targeted for 1.2.0.

**Comment by atom992** [comment]
Cool! When will Sync Gateway 1.2.0 be deployed?

**Comment by adamcfraser** [comment]
Docs have been merged to mobile portal repo.
