### ISSUE TITLE
Investigate discrepancies in get times in go-couchbase vs couchbase server

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#842]
As reported in https://github.com/couchbase/sync_gateway/issues/781#issuecomment-97585413:
- Sync gateway expvars are showing [max response time of 15 seconds](https://gist.github.com/tleyden/848583f7f79d540fbc01#file-gistfile1-txt-L8)
- cbstats are showing a [max response time of 4 milliseconds](https://gist.github.com/tleyden/f24dd0c13c676989d301#file-gistfile1-txt-L32)

Further digging to look at the [cpu profiles](https://github.com/couchbase/sync_gateway/issues/781#issuecomment-97614001) indicated goroutines spending a lot of time blocked waiting for a connection from the connection pool.

This raised the question -- are we currently using optimal connection pool sizes in go-couchbase?

Some possible action items:
- Write a test that creates a go-couchbase load, and run the test with different connection pool sizes.
- Attempt to reproduce the above latency discrepancies in an isolated go-couchbase test so that it can be studied in isolation.

**Comment by adamcfraser** [comment]
This would be useful for analysis of go-couchbase vs. gocb.

**Comment by adamcfraser** [comment]
Closing based on switch to gocb.
