### ISSUE TITLE
Add support for calling BulkGet from Sync Gateway

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#843]
As part of the distributed index work, we need the ability to do bulk retrieval.  go-couchbase already includes an implementation of BulkGet (see https://github.com/couchbase/go-couchbase/blob/master/client.go#L331), but it's not included in the bucket API used by SG (walrus).  

One note - the GetBulk implementation in go-couchbase is currently returning an array of raw gomemcached.MCResponse (unlike the single Get, which returns unmarshalled JSON, or GetRaw, which returns the body (as []byte).  I assume we'd want to wrap the existing GetBulk to return something more generic - we could do that post-processing in the CouchbaseBucket implementation of GetBulk (in base/bucket.go).

**Comment by tleyden** [comment]
In progress
- [x] Add method signature to bucket interface
- [x] Add unit test and impl to walrus
- [x] Code review + PR

**Comment by tleyden** [comment]
>  I assume we'd want to wrap the existing GetBulk to return something more generic 

yes, because otherwise it would cause us to add a dependency on gomemcached to three repos which don't already have it:
- sg-bucket
- forestdb-bucket
- walrus
