### ISSUE TITLE
Retrieving a non existent design doc returns 500 error

### ISSUE THREAD

**Issue by stemail23** [couchbase/sync_gateway#844]
It looks like Couchbase server is correctly responding with a 404, but Sync Gateway is failing to parse that response and is returning a 500 error (with a message containing `Internal error: Error reading view: 404 Object Not Found`!)

To reproduce:

```
curl -X GET http://localhost:4985/unit_tests/_design/testDoc
```

 …where `_design/testDoc` does not exist in the bucket (`unit_tests`)

Sync Gateway logs:

```
14:59:37.527771 HTTP:  #250: GET /unit_tests/_design/testDoc  (ADMIN)
14:59:37.527802 TEMP: GetDesignDoc "testDoc" -- rest.(*handler).handleGetDesignDoc() at view_api.go:17
14:59:37.529077 WARNING: Couldn't interpret error type *errors.errorString, value Error reading view: 404 Object Not Found / {"error":"not_found","reason":"deleted"}
 -- base.ErrorAsHTTPStatus() at error.go:63
14:59:37.529114 HTTP: #250:     --> 500 Internal error: Error reading view: 404 Object Not Found / {"error":"not_found","reason":"deleted"}
  (1.3 ms)
```

**Comment by adamcfraser** [comment]
Thanks for the issue report @stemail23.  If you've got any additional details on how the 500 vs. 404 impacts your development (to help us prioritize the fix), pass them along.

**Comment by stemail23** [comment]
Well the workaround at my end is pretty simple (I just watch for a 500 with the correct signature and interpret it as a 404), but it's a bit ugly! ;)

**Comment by stemail23** [comment]
Cheers! :)
