### ISSUE TITLE
SG public view query api with reduce function

### ISSUE THREAD

**Issue by jamesnocentini** [couchbase/sync_gateway#857]
SG 1.1 adds support for querying views on the user port (4984) which returns the view query result filtered for the user logged in.

Views with a reduce function worked in 1.0.4 but do not work anymore with 1.1.

I suspect that it might be because the [filterViewResult](https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/design_doc.go#L113) function considers the result to be `{ "total_rows" : 0, "rows" : [] }` and the result from a view with a reduce function is something like `{ "rows" : [ {"key":null,"value":2} ] }`

Based on the [discussion](https://forums.couchbase.com/t/sync-gateway-view-and-reduce-possible/3775/3).

**Comment by adamcfraser** [comment]
We've backed out the 4984 view support on 1.1, so reduce is working again there.

The 4984 view support is still available on master - will be reviewed for inclusion in a future release.

**Comment by snej** [comment]
This is a pretty important feature for some developers. And I've got a branch with a CBL feature that uses it, making it really easy to query remote views and pull the resulting docs. It would be good to see this in 1.2 rather than 1.3.

**Comment by toddfreese** [comment]
This feature of having reduce work over the public SG port is really important to us. We have a web client that works with our iOS CBL app.  It does work over the SG admin port but then requires us to deal with proxying the request server side. 

Here is a gist that details an example. This is only 1 of dozens of views that need this feature.

https://gist.github.com/toddfreese/b147d5d84a30ff3e879a0922704a242d

**Comment by adamcfraser** [comment]
@toddfreese The key question is around how to secure that type of view query.  Public API map functions include channel information in the view row results, which Sync Gateway can then use to filter the view results based on the user's channel access.

For your use case - are you expecting channel secured results for the view query?  I'd like to understand whether you're interested in channel secured, reduced view results over the public API, or a way to allow non-secured reduced view results over the public API.

**Comment by toddfreese** [comment]
If by channel secure you mean using a channel to filter the results, then yes, we need the results to be filtered by the channel. We use channels to separate data for different users. Each user has an account which is mapped to a channel. A user can only view data within their channel.

**Comment by snej** [comment]
Yeah, that's what makes reducing such a query difficult — reduced results aggregate ranges of rows in the index, and the aggregation is done internally by the Couchbase view server when the index is created/updated, not at query time. So there's no opportunity to filter the data being aggregated, to make sure the individual rows are only those visible to a particular user.

SG might be able to work around this by doing its own reducing at query time, the way Couchbase Lite does. Depending on the size of the data set, though, that can get expensive.

**Comment by adamcfraser** [comment]
@jens I was wondering about the same thing - stripping out the reduce initially, and then attempting to perform the reduce at query time.  In addition to performance, I was also concerned about the ability to handle more complex custom reduce functions (including rereduce), but if it's already in place in CBL, I'm more optimistic.

Until this gets implemented, I'm users would have to take a similar approach within their application - execute a map-only view, and manage the reduce in their application code (which of course would have the additional performance hit of transporting the full view results over the network).

**Comment by snej** [comment]
You can ignore rereduce. It's only there as an optimization for the reduce engine, so it can reduce smaller batches of rows and then combine those. If you don't need to do that, you can just always call the reduce function with `rereduce=false`, as Couchbase Lite does.

If you want to look at how CBL does it, the best reference is probably Index.cc in LiteCore; the group/reduce implementation starts at about line 400.

**Comment by adamcfraser** [comment]
@snej That's very helpful stuff in Index.cc - thanks for the pointer.

**Comment by jens** [comment]
Wrong @jens though :-)

**Comment by toddfreese** [comment]
Is the issue just a security concern, or a technical abilities issue? My SG View with a reduce function works great when using the admin port, so it seems like SG clearly knows how to do the reduce correctly. I ask just because I want to understand this better.

**Comment by snej** [comment]
It's not SG doing the reduce, it's Couchbase Server's view engine. The point is that it does the reduce without taking into account which rows should be visible to the user making the request (because Couchbase Server has no notion of SG users.) That may or may not leak restricted information; it sounds like in your case it doesn't.

**Comment by toddfreese** [comment]
Thanks for the clarification. That helps me a lot.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
