### ISSUE TITLE
Automate basic Authentication test for webhooks URL.

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#865]
Write script to automate verification of basic authentication in webhooks URL. Add tests to https://github.com/couchbaselabs/sync-gateway-tests

**Comment by sethrosetter** [comment]
Tracking here - https://github.com/couchbaselabs/mobile-testkit/issues/697

**Comment by sethrosetter** [comment]
@adamcfraser Do you mind adding a scenario definition?
