### ISSUE TITLE
Automate HTTPS tests for webhooks URL

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/sync_gateway#866]
Write a script to test with HTTPS server and verify functionality is not broken. Add tests https://github.com/couchbaselabs/sync-gateway-tests

**Comment by ashvindersingh** [comment]
Partially implemented using nodejs framework. Need to fully automate and integrate with sync gateway tests repo.

**Comment by sethrosetter** [comment]
Tracking this testing here - https://github.com/couchbaselabs/mobile-testkit/issues/501
