### ISSUE TITLE
Documents missing when requesting _changes in SyncGateway

### ISSUE THREAD

**Issue by mysketches** [couchbase/sync_gateway#870]
HI there, here is my problem.

I inserted 10K documents using SyncGateway. Thoses documents are all the same. They only differ from one to another by their Id. Besides, the size of each document is 10Ko.

When i request _changes, i always get 9998 documents, not 10K. Documents missing are always 9950 & 9951. I tried to insert 50K documents, results are the same.

Strange thing is that if i request _changes with admin syngateway port, i fetch the 10K documents every time !

Is there a bug somewhere ? I have missed something ?

,{"seq":9949,"id":"DOC_9948","changes":[{"rev":"1-8e37c0a4756f3c1ca7e95a1576b2d505"}]}
,{"seq":9950,"id":"DOC_9949","changes":[{"rev":"1-c8c8c99cd19fb91313e64530612aa76a"}]}
,{"seq":9951,"id":"DOC_9952","changes":[{"rev":"1-e9a6ccdf291c8bd7a1a83b1d6b0b5f5d"}]}
,{"seq":9952,"id":"DOC_9953","changes":[{"rev":"1-326224ddd197c49ed32770d862c06ab9"}]}

**Comment by tleyden** [comment]
@mysketches thank you for the bug report.  

Can you take a look at [troubleshooting channels](http://developer.couchbase.com/mobile/develop/guides/sync-gateway/channels/troubleshooting/index.html) and see if that helps reveal the issue?

If not ..
- Can you let us know which version you are using so that we can try to reproduce?
- Can you post your sync gateway config to a gist?
- Can you share the scripts/code you are using to reproduce the issue?
- What are the curl/http requests you are issuing?  As guest or as a logged in user?

It sounds like the user you are using doesn't have read access to 9950 and 9951, for some reason (possibly due to a bug).

**Comment by tleyden** [comment]
@mysketches any update on this?  Also I forgot to ask, can you post your sync gateway config (or at least the sync function)

**Comment by zgramana** [comment]
Possibly related to https://github.com/couchbase/couchbase-lite-ios/issues/723

**Comment by mysketches** [comment]
Here is the information i have :

Couchbase Sync Gateway/1.0.4(34;04138fd)

{
    "log": ["CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Cache", "Shadow", "Shadow+",    "Changes", "Changes+"],
        "interface":":4984",
        "adminInterface":":14985",
        "databases":{
            "main":{
                "server":"http://localhost:8091",
                "bucket":"default",
                "sync":`function(doc, oldDoc) {
                    try {
                        requireUser('master_user');
                        channel(doc.channels);
                    } catch(err) {
                        channel('master_user');
                    }
                }`
            }
        }
}

**Comment by adamcfraser** [comment]
Thanks @mysketches.  If it's possible to share the contents of DOC_9949 (which does get synchronized) and DOC_9950 (which doesn't), that will help us try to reproduce.

**Comment by mysketches** [comment]
Here is the document.

{"_id":"DOC_9549","_rev":"1-2740709c982581109ed4d8497890fc36","channels":"master_worker","id":"9549","items":[{"bool":false,"email":"luis@jones.ps","float":10.7773,"fullname":"Hilda Harper","index":1,"index_start_at":56,"integer":46,"name":"Tommy","surname":"Wiley"},{"bool":false,"email":"karen@schultz.it","float":13.6439,"fullname":"Samantha Cooper","index":2,"index_start_at":57,"integer":34,"name":"Christy","surname":"Davidson"},{"bool":false,"email":"samuel@sykes.pt","float":18.6528,"fullname":"Eugene Richmond","index":3,"index_start_at":58,"integer":34,"name":"Eric","surname":"Bowling"},{"bool":false,"email":"maria@brantley.gb","float":13.4969,"fullname":"Joshua Hartman","index":4,"index_start_at":59,"integer":31,"name":"Hazel","surname":"Bruce"},{"bool":true,"email":"guy@lawrence.tf","float":12.3501,"fullname":"Nina Parks","index":5,"index_start_at":60,"integer":19,"name":"Robert","surname":"Maynard"},{"bool":true,"email":"glenda@waller.de","float":17.5212,"fullname":"Scott Hunt","index":6,"index_start_at":61,"integer":13,"name":"Kelly","surname":"Rose"},{"bool":false,"email":"kathy@berger.um","float":11.8925,"fullname":"Kyle Hobbs","index":7,"index_start_at":62,"integer":35,"name":"Constance","surname":"Underwood"},{"bool":true,"email":"claire@casey.gb","float":13.5348,"fullname":"Ethel Norman","index":8,"index_start_at":63,"integer":5,"name":"Patsy","surname":"Long"},{"bool":true,"email":"bob@abbott.gf","float":13.8833,"fullname":"Juan Schultz","index":9,"index_start_at":64,"integer":3,"name":"Kristine","surname":"Barton"},{"bool":true,"email":"vernon@abrams.ms","float":10.5895,"fullname":"Megan Houston","index":10,"index_start_at":65,"integer":46,"name":"Neal","surname":"Chandler"},{"bool":false,"email":"jeanne@mangum.ca","float":13.8938,"fullname":"Jordan Burnett","index":11,"index_start_at":66,"integer":43,"name":"Curtis","surname":"Blackwell"},{"bool":false,"email":"kent@brantley.so","float":10.1562,"fullname":"Valerie Watson","index":12,"index_start_at":67,"integer":0,"name":"Guy","surname":"Jennings"},{"bool":false,"email":"milton@hughes.hn","float":16.3367,"fullname":"Michelle Barefoot","index":13,"index_start_at":68,"integer":29,"name":"Louis","surname":"Welch"},{"bool":true,"email":"hazel@case.vi","float":12.8532,"fullname":"Guy King","index":14,"index_start_at":69,"integer":26,"name":"Stacy","surname":"Dunn"},{"bool":true,"email":"paige@vincent.ms","float":17.4321,"fullname":"Karen Dyer","index":15,"index_start_at":70,"integer":28,"name":"Tracey","surname":"Chen"},{"bool":false,"email":"hannah@fleming.io","float":13.7916,"fullname":"Maxine Ferrell","index":16,"index_start_at":71,"integer":1,"name":"Patsy","surname":"Parrott"},{"bool":false,"email":"tamara@sutherland.bd","float":17.1484,"fullname":"Jonathan Yates","index":17,"index_start_at":72,"integer":48,"name":"Lynne","surname":"Tyler"},{"bool":true,"email":"geoffrey@olsen.ec","float":13.4869,"fullname":"Wade Rice","index":18,"index_start_at":73,"integer":29,"name":"Frances","surname":"Pearce"},{"bool":false,"email":"jeremy@rowe.cm","float":11.2714,"fullname":"Elaine Fink","index":19,"index_start_at":74,"integer":10,"name":"Annie","surname":"Schultz"},{"bool":true,"email":"vicki@barbour.bg","float":18.4663,"fullname":"Andrew Bowling","index":20,"index_start_at":75,"integer":41,"name":"Janice","surname":"Steele"},{"bool":false,"email":"george@huffman.np","float":17.8647,"fullname":"Philip Nguyen","index":21,"index_start_at":76,"integer":45,"name":"Lillian","surname":"Duke"},{"bool":true,"email":"guy@west.py","float":19.5517,"fullname":"Bradley Douglas","index":22,"index_start_at":77,"integer":2,"name":"Floyd","surname":"Bowling"},{"bool":false,"email":"don@starr.kh","float":19.8217,"fullname":"Clyde Garrett","index":23,"index_start_at":78,"integer":5,"name":"Betty","surname":"Berry"},{"bool":true,"email":"jessica@weinstein.bv","float":18.2415,"fullname":"Jeanne Cates","index":24,"index_start_at":79,"integer":13,"name":"Joseph","surname":"Stuart"},{"bool":true,"email":"chris@benton.pa","float":11.2104,"fullname":"Don Nash","index":25,"index_start_at":80,"integer":27,"name":"Jerome","surname":"Diaz"},{"bool":false,"email":"ashley@mangum.ar","float":10.949,"fullname":"Emily Matthews","index":26,"index_start_at":81,"integer":20,"name":"Michelle","surname":"Rich"},{"bool":false,"email":"juan@berger.bt","float":12.5649,"fullname":"Chris Pope","index":27,"index_start_at":82,"integer":24,"name":"James","surname":"Harmon"},{"bool":true,"email":"sherry@burch.ao","float":12.951,"fullname":"Glen Justice","index":28,"index_start_at":83,"integer":34,"name":"Barbara","surname":"Barber"},{"bool":false,"email":"nicholas@rice.sd","float":18.8727,"fullname":"Clarence Bowden","index":29,"index_start_at":84,"integer":11,"name":"Kathy","surname":"Warner"},{"bool":false,"email":"tammy@eaton.za","float":10.673,"fullname":"Jessica Garrett","index":30,"index_start_at":85,"integer":11,"name":"Rita","surname":"Rowe"},{"bool":false,"email":"lucy@grimes.mf","float":11.287,"fullname":"Ross Tilley","index":31,"index_start_at":86,"integer":42,"name":"James","surname":"Whitehead"},{"bool":true,"email":"angela@hill.vc","float":16.9436,"fullname":"Dolores Coates","index":32,"index_start_at":87,"integer":18,"name":"Nancy","surname":"Ritchie"},{"bool":true,"email":"jerome@saunders.lr","float":15.2765,"fullname":"Alex Siegel","index":33,"index_start_at":88,"integer":2,"name":"Nicole","surname":"Foster"},{"bool":false,"email":"cynthia@hall.tw","float":19.5551,"fullname":"Edgar Bowling","index":34,"index_start_at":89,"integer":13,"name":"Holly","surname":"Stevenson"},{"bool":false,"email":"wendy@hendrix.bl","float":14.4105,"fullname":"Bernice Harrell","index":35,"index_start_at":90,"integer":46,"name":"Lester","surname":"Pritchard"},{"bool":true,"email":"tommy@coates.ms","float":19.828,"fullname":"Virginia Ayers","index":36,"index_start_at":91,"integer":22,"name":"Vickie","surname":"Blair"},{"bool":true,"email":"jerry@cooke.it","float":11.5771,"fullname":"Barry Alexander","index":37,"index_start_at":92,"integer":38,"name":"Bradley","surname":"Blackburn"},{"bool":true,"email":"dan@melton.mn","float":10.5232,"fullname":"Jamie Hawkins","index":38,"index_start_at":93,"integer":29,"name":"Ralph","surname":"Gray"},{"bool":false,"email":"molly@olson.ma","float":16.7134,"fullname":"Clyde Barefoot","index":39,"index_start_at":94,"integer":26,"name":"Jack","surname":"Matthews"},{"bool":true,"email":"luis@lancaster.fo","float":10.7039,"fullname":"Melinda Caldwell","index":40,"index_start_at":95,"integer":28,"name":"Stacy","surname":"Middleton"},{"bool":false,"email":"sidney@freeman.fm","float":16.9714,"fullname":"Scott Bailey","index":41,"index_start_at":96,"integer":10,"name":"Kyle","surname":"Woods"},{"bool":true,"email":"thelma@mcallister.pr","float":16.8025,"fullname":"Lucy Abrams","index":42,"index_start_at":97,"integer":43,"name":"Cynthia","surname":"Richmond"},{"bool":true,"email":"mike@livingston.fj","float":18.3164,"fullname":"Kenneth Hanna","index":43,"index_start_at":98,"integer":4,"name":"Bill","surname":"Graham"},{"bool":true,"email":"marian@weiner.rw","float":13.4521,"fullname":"Harry McCall","index":44,"index_start_at":99,"integer":7,"name":"Albert","surname":"McKenzie"},{"bool":true,"email":"jordan@huffman.nz","float":19.2937,"fullname":"Charlene Kern","index":45,"index_start_at":100,"integer":1,"name":"Richard","surname":"Lucas"},{"bool":false,"email":"emily@link.mn","float":11.8808,"fullname":"Marguerite Garrett","index":46,"index_start_at":101,"integer":38,"name":"Donna","surname":"Hensley"},{"bool":true,"email":"danielle@ritchie.az","float":15.3896,"fullname":"Willie Nixon","index":47,"index_start_at":102,"integer":46,"name":"Katherine","surname":"Mills"},{"bool":false,"email":"martin@woodard.kn","float":11.7708,"fullname":"Louise Fox","index":48,"index_start_at":103,"integer":48,"name":"Christina","surname":"Cooke"},{"bool":true,"email":"luis@palmer.cx","float":11.1888,"fullname":"Erin Joseph","index":49,"index_start_at":104,"integer":24,"name":"Gail","surname":"Caldwell"},{"bool":true,"email":"maureen@crabtree.ao","float":11.1479,"fullname":"Milton Kinney","index":50,"index_start_at":105,"integer":2,"name":"Sue","surname":"Holmes"},{"bool":true,"email":"jose@waller.gq","float":14.0228,"fullname":"Thelma Baker","index":51,"index_start_at":106,"integer":12,"name":"Geraldine","surname":"Atkins"},{"bool":false,"email":"dwight@hendricks.ba","float":17.9395,"fullname":"Chris Friedman","index":52,"index_start_at":107,"integer":0,"name":"Sarah","surname":"King"},{"bool":false,"email":"eva@stuart.lt","float":10.6896,"fullname":"Ralph Sparks","index":53,"index_start_at":108,"integer":45,"name":"Steve","surname":"Lindsay"},{"bool":false,"email":"nicole@brantley.my","float":14.413,"fullname":"Eleanor Waters","index":54,"index_start_at":109,"integer":0,"name":"Janet","surname":"Baxter"},{"bool":false,"email":"dawn@wallace.ie","float":19.4055,"fullname":"Rick Brantley","index":55,"index_start_at":110,"integer":28,"name":"Gretchen","surname":"Rosenthal"}]}

**Comment by adamcfraser** [comment]
A couple of questions...that looks like doc 9549 (not the missing 9949).  Aldo, is it possible to get the full version of doc 9949 from the Couchbase bucket (via the admin console should work), so that we can see the _sync metadata?  That will help confirm channel assignment)?

In addition - it's possible this is related to issue #880, which has been fixed in 1.1.0.  When that is released (should be later this week), is it possible for you to retest with that release?

**Comment by mysketches** [comment]
Oh, sorry, i added the wrong document. Here is the good one, with all the sync data 

{
   "_sync": {
       "rev": "1-0815219091443fc7023016ee01c76b1f",
       "sequence": 9949,
       "history": {
           "revs": [
               "1-0815219091443fc7023016ee01c76b1f"
           ],
           "parents": [
               -1
           ],
           "bodies": [
               ""
           ],
           "channels": [
               [
                   "master_worker"
               ]
           ]
       },
       "channels": {
           "master_worker": null
       },
       "time_saved": "2015-05-04T08:13:47.480964749Z"
   },
   "channels": "master_worker",
   "id": "39456",
   "items": [
       {
           "bool": false,
           "email": "luis@jones.ps",
           "float": 10.7773,
           "fullname": "Hilda Harper",
           "index": 1,
           "index_start_at": 56,
           "integer": 46,
           "name": "Tommy",
           "surname": "Wiley"
       },
       {
           "bool": false,
           "email": "karen@schultz.it",
           "float": 13.6439,
           "fullname": "Samantha Cooper",
           "index": 2,
           "index_start_at": 57,
           "integer": 34,
           "name": "Christy",
           "surname": "Davidson"
       },
       {
           "bool": false,
           "email": "samuel@sykes.pt",
           "float": 18.6528,
           "fullname": "Eugene Richmond",
           "index": 3,
           "index_start_at": 58,
           "integer": 34,
           "name": "Eric",
           "surname": "Bowling"
       },
       {
           "bool": false,
           "email": "maria@brantley.gb",
           "float": 13.4969,
           "fullname": "Joshua Hartman",
           "index": 4,
           "index_start_at": 59,
           "integer": 31,
           "name": "Hazel",
           "surname": "Bruce"
       },
       {
           "bool": true,
           "email": "guy@lawrence.tf",
           "float": 12.3501,
           "fullname": "Nina Parks",
           "index": 5,
           "index_start_at": 60,
           "integer": 19,
           "name": "Robert",
           "surname": "Maynard"
       },
       {
           "bool": true,
           "email": "glenda@waller.de",
           "float": 17.5212,
           "fullname": "Scott Hunt",
           "index": 6,
           "index_start_at": 61,
           "integer": 13,
           "name": "Kelly",
           "surname": "Rose"
       },
       {
           "bool": false,
           "email": "kathy@berger.um",
           "float": 11.8925,
           "fullname": "Kyle Hobbs",
           "index": 7,
           "index_start_at": 62,
           "integer": 35,
           "name": "Constance",
           "surname": "Underwood"
       },
       {
           "bool": true,
           "email": "claire@casey.gb",
           "float": 13.5348,
           "fullname": "Ethel Norman",
           "index": 8,
           "index_start_at": 63,
           "integer": 5,
           "name": "Patsy",
           "surname": "Long"
       },
       {
           "bool": true,
           "email": "bob@abbott.gf",
           "float": 13.8833,
           "fullname": "Juan Schultz",
           "index": 9,
           "index_start_at": 64,
           "integer": 3,
           "name": "Kristine",
           "surname": "Barton"
       },
       {
           "bool": true,
           "email": "vernon@abrams.ms",
           "float": 10.5895,
           "fullname": "Megan Houston",
           "index": 10,
           "index_start_at": 65,
           "integer": 46,
           "name": "Neal",
           "surname": "Chandler"
       },
       {
           "bool": false,
           "email": "jeanne@mangum.ca",
           "float": 13.8938,
           "fullname": "Jordan Burnett",
           "index": 11,
           "index_start_at": 66,
           "integer": 43,
           "name": "Curtis",
           "surname": "Blackwell"
       },
       {
           "bool": false,
           "email": "kent@brantley.so",
           "float": 10.1562,
           "fullname": "Valerie Watson",
           "index": 12,
           "index_start_at": 67,
           "integer": 0,
           "name": "Guy",
           "surname": "Jennings"
       },
       {
           "bool": false,
           "email": "milton@hughes.hn",
           "float": 16.3367,
           "fullname": "Michelle Barefoot",
           "index": 13,
           "index_start_at": 68,
           "integer": 29,
           "name": "Louis",
           "surname": "Welch"
       },
       {
           "bool": true,
           "email": "hazel@case.vi",
           "float": 12.8532,
           "fullname": "Guy King",
           "index": 14,
           "index_start_at": 69,
           "integer": 26,
           "name": "Stacy",
           "surname": "Dunn"
       },
       {
           "bool": true,
           "email": "paige@vincent.ms",
           "float": 17.4321,
           "fullname": "Karen Dyer",
           "index": 15,
           "index_start_at": 70,
           "integer": 28,
           "name": "Tracey",
           "surname": "Chen"
       },
       {
           "bool": false,
           "email": "hannah@fleming.io",
           "float": 13.7916,
           "fullname": "Maxine Ferrell",
           "index": 16,
           "index_start_at": 71,
           "integer": 1,
           "name": "Patsy",
           "surname": "Parrott"
       },
       {
           "bool": false,
           "email": "tamara@sutherland.bd",
           "float": 17.1484,
           "fullname": "Jonathan Yates",
           "index": 17,
           "index_start_at": 72,
           "integer": 48,
           "name": "Lynne",
           "surname": "Tyler"
       },
       {
           "bool": true,
           "email": "geoffrey@olsen.ec",
           "float": 13.4869,
           "fullname": "Wade Rice",
           "index": 18,
           "index_start_at": 73,
           "integer": 29,
           "name": "Frances",
           "surname": "Pearce"
       },
       {
           "bool": false,
           "email": "jeremy@rowe.cm",
           "float": 11.2714,
           "fullname": "Elaine Fink",
           "index": 19,
           "index_start_at": 74,
           "integer": 10,
           "name": "Annie",
           "surname": "Schultz"
       },
       {
           "bool": true,
           "email": "vicki@barbour.bg",
           "float": 18.4663,
           "fullname": "Andrew Bowling",
           "index": 20,
           "index_start_at": 75,
           "integer": 41,
           "name": "Janice",
           "surname": "Steele"
       },
       {
           "bool": false,
           "email": "george@huffman.np",
           "float": 17.8647,
           "fullname": "Philip Nguyen",
           "index": 21,
           "index_start_at": 76,
           "integer": 45,
           "name": "Lillian",
           "surname": "Duke"
       },
       {
           "bool": true,
           "email": "guy@west.py",
           "float": 19.5517,
           "fullname": "Bradley Douglas",
           "index": 22,
           "index_start_at": 77,
           "integer": 2,
           "name": "Floyd",
           "surname": "Bowling"
       },
       {
           "bool": false,
           "email": "don@starr.kh",
           "float": 19.8217,
           "fullname": "Clyde Garrett",
           "index": 23,
           "index_start_at": 78,
           "integer": 5,
           "name": "Betty",
           "surname": "Berry"
       },
       {
           "bool": true,
           "email": "jessica@weinstein.bv",
           "float": 18.2415,
           "fullname": "Jeanne Cates",
           "index": 24,
           "index_start_at": 79,
           "integer": 13,
           "name": "Joseph",
           "surname": "Stuart"
       },
       {
           "bool": true,
           "email": "chris@benton.pa",
           "float": 11.2104,
           "fullname": "Don Nash",
           "index": 25,
           "index_start_at": 80,
           "integer": 27,
           "name": "Jerome",
           "surname": "Diaz"
       },
       {
           "bool": false,
           "email": "ashley@mangum.ar",
           "float": 10.949,
           "fullname": "Emily Matthews",
           "index": 26,
           "index_start_at": 81,
           "integer": 20,
           "name": "Michelle",
           "surname": "Rich"
       },
       {
           "bool": false,
           "email": "juan@berger.bt",
           "float": 12.5649,
           "fullname": "Chris Pope",
           "index": 27,
           "index_start_at": 82,
           "integer": 24,
           "name": "James",
           "surname": "Harmon"
       },
       {
           "bool": true,
           "email": "sherry@burch.ao",
           "float": 12.951,
           "fullname": "Glen Justice",
           "index": 28,
           "index_start_at": 83,
           "integer": 34,
           "name": "Barbara",
           "surname": "Barber"
       },
       {
           "bool": false,
           "email": "nicholas@rice.sd",
           "float": 18.8727,
           "fullname": "Clarence Bowden",
           "index": 29,
           "index_start_at": 84,
           "integer": 11,
           "name": "Kathy",
           "surname": "Warner"
       },
       {
           "bool": false,
           "email": "tammy@eaton.za",
           "float": 10.673,
           "fullname": "Jessica Garrett",
           "index": 30,
           "index_start_at": 85,
           "integer": 11,
           "name": "Rita",
           "surname": "Rowe"
       },
       {
           "bool": false,
           "email": "lucy@grimes.mf",
           "float": 11.287,
           "fullname": "Ross Tilley",
           "index": 31,
           "index_start_at": 86,
           "integer": 42,
           "name": "James",
           "surname": "Whitehead"
       },
       {
           "bool": true,
           "email": "angela@hill.vc",
           "float": 16.9436,
           "fullname": "Dolores Coates",
           "index": 32,
           "index_start_at": 87,
           "integer": 18,
           "name": "Nancy",
           "surname": "Ritchie"
       },
       {
           "bool": true,
           "email": "jerome@saunders.lr",
           "float": 15.2765,
           "fullname": "Alex Siegel",
           "index": 33,
           "index_start_at": 88,
           "integer": 2,
           "name": "Nicole",
           "surname": "Foster"
       },
       {
           "bool": false,
           "email": "cynthia@hall.tw",
           "float": 19.5551,
           "fullname": "Edgar Bowling",
           "index": 34,
           "index_start_at": 89,
           "integer": 13,
           "name": "Holly",
           "surname": "Stevenson"
       },
       {
           "bool": false,
           "email": "wendy@hendrix.bl",
           "float": 14.4105,
           "fullname": "Bernice Harrell",
           "index": 35,
           "index_start_at": 90,
           "integer": 46,
           "name": "Lester",
           "surname": "Pritchard"
       },
       {
           "bool": true,
           "email": "tommy@coates.ms",
           "float": 19.828,
           "fullname": "Virginia Ayers",
           "index": 36,
           "index_start_at": 91,
           "integer": 22,
           "name": "Vickie",
           "surname": "Blair"
       },
       {
           "bool": true,
           "email": "jerry@cooke.it",
           "float": 11.5771,
           "fullname": "Barry Alexander",
           "index": 37,
           "index_start_at": 92,
           "integer": 38,
           "name": "Bradley",
           "surname": "Blackburn"
       },
       {
           "bool": true,
           "email": "dan@melton.mn",
           "float": 10.5232,
           "fullname": "Jamie Hawkins",
           "index": 38,
           "index_start_at": 93,
           "integer": 29,
           "name": "Ralph",
           "surname": "Gray"
       },
       {
           "bool": false,
           "email": "molly@olson.ma",
           "float": 16.7134,
           "fullname": "Clyde Barefoot",
           "index": 39,
           "index_start_at": 94,
           "integer": 26,
           "name": "Jack",
           "surname": "Matthews"
       },
       {
           "bool": true,
           "email": "luis@lancaster.fo",
           "float": 10.7039,
           "fullname": "Melinda Caldwell",
           "index": 40,
           "index_start_at": 95,
           "integer": 28,
           "name": "Stacy",
           "surname": "Middleton"
       },
       {
           "bool": false,
           "email": "sidney@freeman.fm",
           "float": 16.9714,
           "fullname": "Scott Bailey",
           "index": 41,
           "index_start_at": 96,
           "integer": 10,
           "name": "Kyle",
           "surname": "Woods"
       },
       {
           "bool": true,
           "email": "thelma@mcallister.pr",
           "float": 16.8025,
           "fullname": "Lucy Abrams",
           "index": 42,
           "index_start_at": 97,
           "integer": 43,
           "name": "Cynthia",
           "surname": "Richmond"
       },
       {
           "bool": true,
           "email": "mike@livingston.fj",
           "float": 18.3164,
           "fullname": "Kenneth Hanna",
           "index": 43,
           "index_start_at": 98,
           "integer": 4,
           "name": "Bill",
           "surname": "Graham"
       },
       {
           "bool": true,
           "email": "marian@weiner.rw",
           "float": 13.4521,
           "fullname": "Harry McCall",
           "index": 44,
           "index_start_at": 99,
           "integer": 7,
           "name": "Albert",
           "surname": "McKenzie"
       },
       {
           "bool": true,
           "email": "jordan@huffman.nz",
           "float": 19.2937,
           "fullname": "Charlene Kern",
           "index": 45,
           "index_start_at": 100,
           "integer": 1,
           "name": "Richard",
           "surname": "Lucas"
       },
       {
           "bool": false,
           "email": "emily@link.mn",
           "float": 11.8808,
           "fullname": "Marguerite Garrett",
           "index": 46,
           "index_start_at": 101,
           "integer": 38,
           "name": "Donna",
           "surname": "Hensley"
       },
       {
           "bool": true,
           "email": "danielle@ritchie.az",
           "float": 15.3896,
           "fullname": "Willie Nixon",
           "index": 47,
           "index_start_at": 102,
           "integer": 46,
           "name": "Katherine",
           "surname": "Mills"
       },
       {
           "bool": false,
           "email": "martin@woodard.kn",
           "float": 11.7708,
           "fullname": "Louise Fox",
           "index": 48,
           "index_start_at": 103,
           "integer": 48,
           "name": "Christina",
           "surname": "Cooke"
       },
       {
           "bool": true,
           "email": "luis@palmer.cx",
           "float": 11.1888,
           "fullname": "Erin Joseph",
           "index": 49,
           "index_start_at": 104,
           "integer": 24,
           "name": "Gail",
           "surname": "Caldwell"
       },
       {
           "bool": true,
           "email": "maureen@crabtree.ao",
           "float": 11.1479,
           "fullname": "Milton Kinney",
           "index": 50,
           "index_start_at": 105,
           "integer": 2,
           "name": "Sue",
           "surname": "Holmes"
       },
       {
           "bool": true,
           "email": "jose@waller.gq",
           "float": 14.0228,
           "fullname": "Thelma Baker",
           "index": 51,
           "index_start_at": 106,
           "integer": 12,
           "name": "Geraldine",
           "surname": "Atkins"
       },
       {
           "bool": false,
           "email": "dwight@hendricks.ba",
           "float": 17.9395,
           "fullname": "Chris Friedman",
           "index": 52,
           "index_start_at": 107,
           "integer": 0,
           "name": "Sarah",
           "surname": "King"
       },
       {
           "bool": false,
           "email": "eva@stuart.lt",
           "float": 10.6896,
           "fullname": "Ralph Sparks",
           "index": 53,
           "index_start_at": 108,
           "integer": 45,
           "name": "Steve",
           "surname": "Lindsay"
       },
       {
           "bool": false,
           "email": "nicole@brantley.my",
           "float": 14.413,
           "fullname": "Eleanor Waters",
           "index": 54,
           "index_start_at": 109,
           "integer": 0,
           "name": "Janet",
           "surname": "Baxter"
       },
       {
           "bool": false,
           "email": "dawn@wallace.ie",
           "float": 19.4055,
           "fullname": "Rick Brantley",
           "index": 55,
           "index_start_at": 110,
           "integer": 28,
           "name": "Gretchen",
           "surname": "Rosenthal"
       }
   ]
}

**Comment by adamcfraser** [comment]
Thanks - can you also share document 9950 (the one that isn't getting synchronized) for comparison?

**Comment by adamcfraser** [comment]
@mysketches Let me know whether you can provide 9950 - I haven't been able to reproduce thus far.

**Comment by zgramana** [comment]
@mysketches FYI, we'll close this out next Friday barring any new updates.

**Comment by zgramana** [comment]
@mysketches closing this out. Please comment or re-file if the issue has not been resolved.

**Comment by ghost** [comment]
@zgramana 
I'm working with @mysketches. Some news about this issue: after restarting the couchbase server (sync gateway was restared already without success) the problem disappeared. We haven't been able to reproduce it since, so no clue on what hapenned here or how to reproduce it ...
