### ISSUE TITLE
Document all of the options for -log

### ISSUE THREAD

**Issue by couchbasebrian** [couchbase/sync_gateway#872]
Is there a place that lists all of the possible keyword options for -log, and gives an example of the expected output for each?

**Comment by tleyden** [comment]
Not that I know of, but there needs to be.  It is possible to just use "*" and it will emit all log entries.

@JeffThomasWriter putting this on your queue to get documented.

**Comment by couchbasebrian** [comment]
Also is there a way to do automatic log rotation?

**Comment by adamcfraser** [comment]
https://github.com/couchbase/sync_gateway/wiki/Log-file-rotation

**Comment by adamcfraser** [comment]
Summary notes on the log settings, as input for the formal documentation.  The '+' notation indicates more detailed logging for that key.  Adding "foo+" to the log keys defined in the config will enable logging for both "foo" and "foo+"

The following are the most commonly used logging for diagnostics:

CRUD/CRUD+: logging for updates being made by Sync Gateway to the underlying bucket. 
Cache/Cache+: logging interactions with Sync Gateway's in-memory channel cache
Changes/Changes+: processing of _changes requests
HTTP/HTTP+: logs all requests being made against the SG REST API

Other logging:

Access: logs access() calls made by the sync function
Auth: authentication
Feed/Feed+: TAP feed processing
DCP: When enabled, does verbose logging of SG DCP feed processing
Bucket: When enabled, does verbose logging of all SG interactions with the underlying bucket
Shadow/Shadow+: Logging of bucket shadowing operations
Attach: Logging for attachment processing
Events/Events+: Event processing (webhooks)

**Comment by JeffThomasWriter** [comment]
Adam, the notes are helpful. Is this content documented somewhere in some configuration file? (I did find logging.go.) In addition to beefing up the docs, editing comments in the related code file(s) makes sense. Regarding logging.go, it looks like bw, color, and notime are overloaded as keys, and \* gets you everything. Can you also specify log levels as keys? Examples from Dev or QE will be helpful. Thanks.

**Comment by adamcfraser** [comment]
Log keys are defined by consumers of logging.go.  If you do a search for base.LogTo across the Sync Gateway codebase you'll find them.  They get defined as they are used - there's no centralized definition of the log keys.  

bw, color and notime aren't LogKeys (not in the context we're talking about here) - those are lower level interactions with go's default logging package.

Regarding log levels - the usage is documented in the code [here.](https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/base/logging.go#L22), These can be set via the admin API (passing the level parameter to the _logging endpoint), but I don't think we have support for log level in the config file yet (but we should).

**Comment by zgramana** [comment]
Duplicates couchbase/sync_gateway#905
