### ISSUE TITLE
Perfcluster AWS: automate couchbase server IP discovery

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#873]
In the README, there is a step:

> Open ansible/playbooks/files/sync_gateway_config.json and change db/server and db/remote_cache/server to have the couchbase server ip found in previous step

This should be done automatically as part of the `build-sync-gateway.yml` or `install-sync-gateway-service.yml`.  

Rather than updating the `ansible/playbooks/files/sync_gateway_config.json` file, that file should be made into a template and before it is uploaded, the variable would be replaced with the correct ip address of one of the Couchbase Server instances.

**Comment by tleyden** [comment]
Todo:
- [x] Refactor to remove duplication in install-couchbase-server-4.0.0-dp.yml and install-couchbase-server-3.0.3.yml
- [x] Use couchbase server internal ip
- [x] Uninstall + rm /opt/couchbase in order to clean couchbase

**Comment by tleyden** [comment]
@andreibaranouski I'm seeing this issue when trying to run a perf test

```
2015-05-22T00:27:10.247Z HTTP: #666:     --> 500 Internal error: error starting view req at http://ec2-54-205-179-57.compute-1.amazonaws.com:8092/bucket-1/_design/sync_gateway/_view/access?key=%22user-664%22&stale=false: Get http://ec2-54-205-179-57.compute-1.amazonaws.com:8092/bucket-1/_design/sync_gateway/_view/access?key=%22user-664%22&stale=false: dial tcp 10.230.176.234:8092: connection timed out  (127227.4 ms)
```

I think what's happening is that:
- Since Couchbase Server was configured w/ external ip, it's advertising that to sync gw
- Sync gw tries to contact via external ip but the firewall rules don't allow it

While we could open up the firewall rules to fix the problem, I'd rather use the internal ip in case it results in a faster network path. 

Can you look into changing this to find and use the couchbase server internal ip?

**Comment by tleyden** [comment]
If it's difficult to get the private ip using the auto-generated groups from the ec2.py dynamic inventory, it might be easier to just run a shell command `hostname -i` and capture/register that into a variable and use it in the rest of the playbook.

**Comment by andreibaranouski** [comment]
https://github.com/couchbaselabs/perfcluster-aws/commit/ea976abf9a649b937d2d4d3cc464b82b6935f565
