### ISSUE TITLE
Perfcluster AWS: collect Sync Gateway and Gateload expvars and push to Splunk

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#876]
We need something which will collect the expvars published at:
- http://sync-gw:4985/_expvar
- http://gateload:9876/debug/vars

and push these to splunk somehow.  I believe how it works is this:
- We register an "input script" with the splunk forwarder, which it calls based on a frequency that we specify in the config file (eg, once every 60 seconds)
- It calls the input script and expects the result to be passed via stdout
- It forwards the result to the splunk server
- They probably provide a way to pass additional metadata, probably based on the configuration of that input script (next to the frequency)

The input script can be written in anything, and in fact it might be possible to just write a bash script that calls curl or wget.

Otherwise, if that's not possible, it should probably be written in python.

**Comment by andreibaranouski** [comment]
@tleyden please check the commit

**Comment by tleyden** [comment]
Ok looks good to me.  I do think it would be slightly cleaner to configure a script as a callback, where:
- Register a script with spunk forwarder
- Splunk forwarder calls back script
- Script fetches expvar and emits to stdout
- Splunk forwarder reads stdout and sends to splunk server.

I'll test it and get back to you if I run into any issues.
