### ISSUE TITLE
Run CSG tests against PouchDB test suite: cannot DELETE a database

### ISSUE THREAD

**Issue by nolanlawson** [couchbase/sync_gateway#877]
So, I know @jchris did a lot of work to get the tests running against CSG in the PouchDB test suite on our Travis server, but I'm actually kind of struggling to reproduce what he did. (I know, I know, even though the code is right there. I'm a newb to CSG.)

Anyway, I'm running this on a Linux Mint laptop with [these configuration files](https://gist.github.com/nolanlawson/163f3e371b1d521c24b8) as borrowed from the scripts @jchris added to the PouchDB repo. I then run the two scripts as shown in the `test.sh` file.

Unfortunately the error comes when I try to delete a database, e.g.:

```
curl -v -X DELETE localhost:4984/foobar
```

I get:

```
< HTTP/1.1 405 Method Not Allowed
< Allow: GET, HEAD, POST
...
{"error":"Method Not Allowed","reason":""}
```

This stops the PouchDB tests dead in their tracks, because our test suite deletes and recreates a database before every test.

**Comment by zgramana** [comment]
@nolanlawson looks like you're using the user-land port. Try the admin port, which defaults to 4985. Might need to add a trailing forward slash as well.

**Comment by nolanlawson** [comment]
That's undoubtedly it. I'll give it another shot this next weekend.

BTW multipart is coming along nicely; excited to get attachment support for CSG! :D

**Comment by zgramana** [comment]
@nolanlawson did you make any progress on getting this working? If not, let me know.

**Comment by nolanlawson** [comment]
Sorry, haven't run the tests again recently. I also realized we need to put some more work into our HTTP adapter in order to fully fix the PouchDB test suite against CSG, so I'm probably going to focus on that first. (See https://github.com/pouchdb/pouchdb/issues/3913 for discussion.)

**Comment by zgramana** [comment]
@nolanlawson, should we close this out and re-open later?

**Comment by nolanlawson** [comment]
Sure, works for me. I haven't had time lately - been on vacation! :)
