### ISSUE TITLE
Changes feed fails to backfill channel under heavy access() load

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#880]
Moved from https://github.com/couchbase/couchbase-lite-ios/issues/723.

Under heavy access() load, a continuous _changes feed is failing to backfill channels to connected users being granted access to those channels.

A sample client app is available on the iOS ticket to reproduce.

Still working to definitively reproduce via unit tests, but it looks like a race condition between the user doc update (used to identify the new channel access), and the changes feed processing the document that did the access() grant.

**Comment by adamcfraser** [comment]
I'm able to reproduce the same behaviour with the user's modified Todolite app when running against SG 1.0.3, so it doesn't look like this issue is impacted by the late sequence handling changes in 1.1.0.

**Comment by joenoon** [comment]
@adamcfraser Any idea on short-term solutions for this?

As it stands right now, is it correct to assume there is no way to know if an idle replication is actually caught up?

My current attempt is to wait until a replication is fully idle for 3 seconds, then restart the replication with the "reset" option set.  This does eventually bring things back to the correct state but seems and feels very expensive and slow.

Is there any other less expensive check I could implement?

**Comment by adamcfraser** [comment]
@joenoon - I've made some progress on this issue.  It looks like the specific issue you were hitting may just have been related to concurrent backfill of multiple channels by the _changes feed, and not necessarily to a race condition.

I've put together a fix, tested with the modified TodoLite app you provided, and I'm seeing all the expected documents.  The fix is available on the feature/issue_880 branch - if you're able to give it a try with your actual application tests and confirm that it works, I'd appreciate it.

However, I still haven't been able to reproduce the issue via unit tests - even when attempting to replicate the calls being made by the sample app.  I'm continuing to dig into that.

**Comment by joenoon** [comment]
@adamcfraser first few attempts with my actual app are unfortunately showing the same problem:

In my iOS app, in this case 556421d04a6f731fce110000 was one of the missing docs, so I filtered the logs by only lines with that ID.

All: https://gist.github.com/joenoon/43729e01cbeeeec1d92b
556421d04a6f731fce110000 lines only: https://gist.github.com/joenoon/5aa9e155dcffe44231b8

After doing a repl reset/restart, the docs synced in:

All: https://gist.github.com/joenoon/983b793fb8debb99cb1b
556421d04a6f731fce110000 lines only: https://gist.github.com/joenoon/c0d880b13726fae93759

If these logs with the new AccessRace lines off my actual app don't reveal any hints, I can go back to trying to re-create this in the todo app.

**Comment by adamcfraser** [comment]
@joenoon I've pushed an update to feature/issue_880 that should ensure backfill for channels added during a continuous changes feed.  I also think I've got a unit test reproducing your original issue (TestUserAccessRace) - I was previously missing the user assignment to the Profile-[user] channel. 

Give it a try, and let me know how it goes.

**Comment by joenoon** [comment]
@adamcfraser so far so good!  I have yet to produce the bug with feature/issue_880.  I'll continue using this branch tonight and report back tomorrow just to be sure, but it seems like this fixed it.  Thanks for making this happen!

**Comment by joenoon** [comment]
@adamcfraser @zgramana I haven't had an issue since I've been using this branch, so I think this can be considered fixed.  Thanks again.

**Comment by adamcfraser** [comment]
@joenoon Great to hear it, and thanks very much for your help in getting this reproduced quickly - it's much appreciated.
