### ISSUE TITLE
Tool to collect sync gateway debugging info

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#884]
- Dtrace
- Memory profiles
- Netstat

**Comment by zgramana** [comment]
@tleyden please update.

**Comment by tleyden** [comment]
Not started yet, but I will start it now.

**Comment by tleyden** [comment]
@ajres / @zgramana can you take a look at this and let me know how it goes?

https://github.com/couchbase/sync_gateway/wiki/monitoring-script
