### ISSUE TITLE
AWS perfcluster: get cbagent stats into Splunk via forwarder

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#885]
In the non-AWS [perfrunner](https://github.com/couchbaselabs/perfrunner) scenario, [cbagent](https://github.com/couchbaselabs/cbagent) is used to collect Couchbase Server stats and push these to Seriesly.

The goal of this task is to use cbagent to push the same stats into Splunk, via a forwarder.

After chatting with splunk folks over IRC, the recommended approach for this is:
- Push the JSON to a single file
- Point the splunk forwarder at the file, the same way as if you were monitoring a logfile
- To keep the file from growing without bound, use `logrotate`, with the caveat that "note that if you want logrotate to run any more frequently than once a day, you'll need to update cron to call it more often,     otherwise, 4:02am localtime is when yer logs will rotate."

**Comment by tleyden** [comment]
I just updated the ticket description with more information.  See https://github.com/couchbase/sync_gateway/issues/885 (in case you are reading this over email)

There is alternate approach which they mentioned but did not recommend, which was:
- Post directly to the 'submit' endpoint on splunkd, splunk's own rest api where you can throw events in that way

The docs for that are here: 

http://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTinput#receivers.2Fsimple

and the downside is that "all of the overhead of a tcp setup and http crap just to throw 200 bytes of json into an event is decidedly inefficient"

I'm not actually clear on whether that endpoint is available at the forwarder or the indexer.

**Comment by zgramana** [comment]
Based on [this answer](http://answers.splunk.com/answers/38176/data-indexed-via-rest-api-then-forwarded-on-to-another-indexer.html), the answer is yes.

**Comment by zgramana** [comment]
Misc useful article: [Perform selective indexing and forwarding](http://docs.splunk.com/Documentation/Splunk/6.0/Forwarding/Routeandfilterdatad#Perform_selective_indexing_and_forwarding)

**Comment by tleyden** [comment]
Still pending todo:
- [x] Update to "solution 2 -  install cbagent on all CB hosts and collect all stats separately( splunk should monitor logs on every node)" as discussed on skype
- [ ] Update README with docs on how to enable this, if needed (eg, kicking off a new playlist)

**Comment by andreibaranouski** [comment]
cb stats are monitored from one gateload instance. no changes are required in README. full implementation is in install-splunkforwarder.yml

**Comment by tleyden** [comment]
- [x] Add timestamp to data when we collect stats from cbagent
- [x] Verify data is being pushed to splunk server
