### ISSUE TITLE
Define RAM requirements based on number of concurrent users in scaling guide

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#887]
Perform testing to determine average memory usage per 1000 connected users, and include that information in the scaling guide.
- Test based on connected _changes users.
- Validate that memory usage scales linearly (to at least 10K users)
- Compare memory usage of 1K connected _changes with 1K users with the todolite scenario (sanity test that real-world usage doesn't use much higher memory than _changes)
- Test usage on different OSs to identify whether there are significant differences

**Comment by ajres** [comment]
- [ ] Test based on connected _changes users.
- [ ] Validate that memory usage scales linearly (to at least 10K users)
- [ ] Compare memory usage of 1K connected _changes with 1K users with the todolite scenario (sanity test that real-world usage doesn't use much higher memory than _changes)
- [ ] Test usage on different OSs to identify whether there are significant differences

**Comment by ajres** [comment]
- [x] Test based on connected _changes users.
- [x] Validate that memory usage scales linearly (to at least 10K users)
- [ ] Compare memory usage of 1K connected _changes with 1K users with the todolite scenario (sanity test that real-world usage doesn't use much higher memory than _changes)
- [ ] Test usage on different OSs to identify whether there are significant differences

**Comment by ajres** [comment]
Currently running tests against centos6 as this is the OS deployed by perfcluster-aws
