### ISSUE TITLE
Non int last_seq id in _changes request fails

### ISSUE THREAD

**Issue by paulharter** [couchbase/sync_gateway#895]
A `_changes` request to sync gateway sometimes returns a non int last_seq id. In this case the string `"82::100"`. If I pass this identifier back in a second `_changes` request it generates a 500 in sync gateway as it appears to be expecting an int.

From the error it appears that sync gateway is splitting the string by `::` separators but failing to remove the double speech marks first. If the identifier is not being an int but any json it should expect speech marks around strings. I experienced this problem replicating to CouchDB which opaquely returns the last_seq id like this when attempting to replicate.

```
Pauls-MacBook-Pro :: ~ » curl http://test:password@192.168.59.103:4984/sync_gateway/_changes
{"results":[...],
"last_seq":"82::100"}
Pauls-MacBook-Pro :: ~ » curl http://test:password@192.168.59.103:4984/sync_gateway/_changes\?since\=%2282%3A%3A100%22
{"error":"Internal Server Error","reason":"Internal error: strconv.ParseUint: parsing \"\\\"82\": invalid syntax"}%  
```

I suspect this may somehow have been causing the problems I was having last week

Paul

**Comment by adamcfraser** [comment]
_last_seq is always sent as a string in the _changes response, even when that string represents a simple integer.  

e.g. from my local environment:

```
GET /default/_changes?since=130 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic YWRhbToxMjM0
Host: localhost:4984
User-Agent: HTTPie/0.8.0



HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 141
Content-Type: application/json
Date: Mon, 01 Jun 2015 14:49:32 GMT
Server: Couchbase Sync Gateway/unofficial

{"results":[

{
    "changes": [
        {
            "rev": "1-8ac8351aaca1e458dbb7f7932d8e97ac"
        }
    ], 
    "id": "testdoc9", 
    "seq": 131
}
,{"seq":132,"id":"testdoc11","changes":[{"rev":"1-8ac8351aaca1e458dbb7f7932d8e97ac"}]}
],
"last_seq":"132"}
```

When passing the since value as a query parameter in the HTTP request as you're doing above, you shouldn't be including double quotes to send it as a string (the query parameter isn't JSON).   This isn't just an issue with the sequences that include colons - you'd also get an error if you tried to pass `"82"` (quotes, no colons) as the since value.

What's building the _changes request that's failing for you?  It sounds like it's CouchDB related, but I'm not completely clear on the details.

**Comment by paulharter** [comment]
Hi Adam,

I am using CouchDB with Sync Gateway, and I had thought that the last_seq always had to be an int as that is what the CouchDB docs say. I raised this on the forums and Jens said:

```
CouchDB doesn't require ints. It's always been the case that sequences in the replication protocol are arbitrary JSON objects. Both BigCouch and Cloudant use long base64-format strings, for example.

SG should be compatible with CouchDB. If you're having trouble, please post details of exactly what goes wrong.
```

So it looks like CouchDB treats the last_seq identifier as serialised json not as a bare string. This would mean that `82` is not the string 82 but a json number and that `"82"` is a string. So if you give the identifier `"82::100"` to CouchDB in a replication it will return it as `%2282%3A%3A100%22` in the query.

I think to maintain compatibility with CouchDB you can't use bare strings as identifiers. ie If the id is a json object it should be serialised and url encoded. In Python:

```
>>> since = "82::100"
>>> urllib.urlencode({"since": json.dumps(since)})
'since=%2282%3A%3A100%22'
```

At least I am sure that attempts to replicate with CouchDB raise this error as CouchDB will add the double quotes

Paul

**Comment by paulharter** [comment]
As a slightly dirty work around could you maybe strip the quotes if present to allow replication with CouchDB?

**Comment by adamcfraser** [comment]
I think the problem is that you're trying to send a JSON encoded string to a GET request, which isn't appropriate.  

If you send a JSON-encoded `since` in a POST to `_changes`, it works as expected (again from my local):

```
curl -H "Content-Type: application/json" -X POST -d '{"since":"10::100"}' http://adam:1234@localhost:4984/default/_changes 

{"results":[
{"seq":112,"id":"ownerdoc","changes":[{"rev":"1-e57c147bd1398b355d8a8448721e6364"}]}
,{"seq":113,"id":"ownerdoc2","changes":[{"rev":"1-b1a0ebf5b5644cf8c5edf6f5a2eedd40"}]}
,{"seq":114,"id":"ownerdoc3","changes":[{"rev":"1-17372425df280847828565c898bc642b"}]}
,{"seq":115,"id":"ownerdoc4","changes":[{"rev":"1-e57c147bd1398b355d8a8448721e6364"}]}
,{"seq":118,"id":"_user/adam","changes":[]}
,{"seq":121,"id":"testdoc2","removed":["test"],"changes":[{"rev":"2-b54ae6a7272f6ae0ca83a4b3c4a4fa99"}]}
,{"seq":123,"id":"testdoc3","removed":["test"],"changes":[{"rev":"2-b54ae6a7272f6ae0ca83a4b3c4a4fa99"}]}
,{"seq":125,"id":"testdoc4","removed":["test"],"changes":[{"rev":"2-b54ae6a7272f6ae0ca83a4b3c4a4fa99"}]}
,{"seq":127,"id":"testdoc5","removed":["test"],"changes":[{"rev":"2-b54ae6a7272f6ae0ca83a4b3c4a4fa99"}]}
,{"seq":128,"id":"testdoc6","changes":[{"rev":"1-8ac8351aaca1e458dbb7f7932d8e97ac"}]}
,{"seq":129,"id":"testdoc7","changes":[{"rev":"1-8ac8351aaca1e458dbb7f7932d8e97ac"}]}
,{"seq":130,"id":"testdoc8","changes":[{"rev":"1-8ac8351aaca1e458dbb7f7932d8e97ac"}]}
,{"seq":131,"id":"testdoc9","changes":[{"rev":"1-8ac8351aaca1e458dbb7f7932d8e97ac"}]}
,{"seq":132,"id":"testdoc11","changes":[{"rev":"1-8ac8351aaca1e458dbb7f7932d8e97ac"}]}
],
"last_seq":"132"}

```

I'm a bit surprised if Couch DB is sending a quoted string as a GET parameter, but I haven't tried to set up CouchDB-Sync Gateway replication myself.  Can you modify the way replication is set up to POST to the Sync Gateway _changes?

**Comment by paulharter** [comment]
Hi Adam,

It's not me exactly, I'm not constructing the requests I'm simply asking CouchDB to replicate from Sync Gateway to one of its dbs. This is how CouchDB behaves if you use a string as the last_seq. It may seem a bit odd but it does make sense. If the identifier can be any json then the correct serialisation for a string does include the quotes, otherwise how would you distinguish `82` from `"82"` . 

In your example you are not sending serialised json, you are sending a bare string. A json string always has double quotes:

![string](https://cloud.githubusercontent.com/assets/160820/7918925/c5c8d5de-088c-11e5-8c97-db9464a0bf23.gif)

Sending json in query strings is not pretty, but neither is it appropriate, and it is what the CouchDB replication API seems to do. I don't know if this behaviour can be changed. I will have another look at the docs and ask around.

The question is are these identifiers strings or json. Jens told me they are `"arbitrary JSON objects"` in which case strings have quotes

**Comment by adamcfraser** [comment]
I think we're in agreement - in both cases - GET _changes or POST _changes - a string is being sent for the since value.  It's only in the POST case, though, that Sync Gateway expects the string to be sent JSON-encoded.

When Jens mentions `arbitrary JSON objects`, I expect he's talking about the value of last_seq sent in the _changes response, and not how the since value is sent in a GET.  

As you say, it sounds like a problem with the way Couch DB is sending the since value.  If you can share some details on the version of Couch DB you're using, we can take a closer look.

**Comment by paulharter** [comment]
It may be a problem with CouchDB. Certainly if Sync Gateway returns a string like `"82::100"` then CouchDB will treat this as a json object rather than a string and in its next GET to _changes sends it back as a json encoded string.

But it may not be a fault in CouchDB. It may be that CouchDB allows any json as the value of last_seq and so always json encodes it in the query string.

This from the Sync Gateway log:

```
2015/06/01 18:24:52.688219 HTTP:  #155: GET /sync_gateway/_changes?feed=normal&style=all_docs&since=%221%3A%3A21%22&heartbeat=10000  (as test)
2015/06/01 18:24:52.688348 WARNING: Couldn't interpret error type *strconv.NumError, value strconv.ParseUint: parsing "\"1": invalid syntax -- base.ErrorAsHTTPStatus() at error.go:63
2015/06/01 18:24:52.688402 HTTP: #155:     --> 500 Internal error: strconv.ParseUint: parsing "\"1": invalid syntax  (0.9 ms)

```

I am using CouchDB 1.6.1. This is the current stable release. So currently Sync Gateway will not replicate to CouchDB.

**Comment by paulharter** [comment]
Hi Adam,

I asked about this on the CouchDB replication list in case this was an issue with CouchDB, and it seems that last_seq is in fact any json and should be returned json encoded, ie CouchDB is doing the correct thing. Jens confirmed that this is a bug in Sync Gateway.

**Comment by adamcfraser** [comment]
Thanks for following up on the CouchDB side Paul - I reviewed with Jens, and we'll make the change in Sync Gateway to also accept JSON-encoded values for `since` in the GET _changes request.

**Comment by paulharter** [comment]
Thanks Adam that's great.

**Comment by tleyden** [comment]
Note to self: we just want to be able to handle when since is sent as a JSON object in the GET, even just a value like since="123", where the quotes are included.  Should be reproducible by using  since=%22123%22 in a unit test.

**Comment by ajres** [comment]
Should handle generic JSON content passed by client

**Comment by paulharter** [comment]
Adam, Andrew - Thank you for fixing this. 

Compatibility with CouchDB is important to my current project. I'm very grateful that you've made time to keep replication between DBs working.

I'll test it in the morning.

P
