### ISSUE TITLE
Hard to confirm that _change heartbeat is being sent

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#898]
Trying to confirm that Syng Gateway is sending heartbeat characters to the client in a longpoll _change feed is difficult as there is no logging for heartbeat.

Add logging to enable heartbeat tracking

**Comment by zgramana** [comment]
@ajres please update.

**Comment by ajres** [comment]
Added log entries when _changes heartbeats are written, uses custom "Heartbeat" log channel to avoid flooding logs.

PR #906 raised

**Comment by tleyden** [comment]
PR: https://github.com/couchbase/sync_gateway/pull/931

**Comment by tleyden** [comment]
Refs #931
