### ISSUE TITLE
Pass old current revision to 'document_changed' filter function

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#899]
As a dev, I want to compare the current doc revision to the outgoing "current" revision so that I receive notifications only when specific keys change. For example:

``` javascript
function(doc, oldDoc) {
  // Fire when doc transitions into a published state.
  return oldDoc.published==false && newDoc.published==true;
}
```

**Comment by adamcfraser** [comment]
To avoid the performance hit of looking up the ancestor doc again for event processing, I expect we'll want to refactor the getChannelsAndAccess call in updateDoc to return the oldDoc it's using during sync function execution, and reuse it for the call to RaiseDocumentChangeEvent.

**Comment by kirtan403** [comment]
Where is the usage of oldDoc documented? I am looking at http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/sync-gateway/server-integration/webhooks/index.html currently and nothing found about oldDoc

**Comment by ajres** [comment]
It looks like we need to fix the docs for this, but there is a [unit test with filter functions that use oldDoc](https://github.com/couchbase/sync_gateway/blob/master/db/event_manager_test.go#L542) that provide some examples.

**Comment by kirtan403** [comment]
There are many topics not added in docs. Even if the feature is there it needs lots of time to find this out. You guys should update the docs for 1.2 as there are lots of new things added.
