### ISSUE TITLE
Support keys parameter in /_all_docs and other view queries

### ISSUE THREAD

**Issue by jamesnocentini** [couchbase/sync_gateway#901]
The Couchbase Server REST API [views endpoint](http://docs.couchbase.com/admin/admin/Views/views-querying.html) has a keys option in the querystring to get the specified documents.

This could be useful to have on the REST API of Sync Gateway `:4984/todos/_all_docs` to get a set a docs for web app development or `:4985/todos/_design/ddocname/_view/viewname`.

**Comment by adamcfraser** [comment]
There's already support for the keys property when doing a POST to `_all_docs`.   (see http://developer.couchbase.com/mobile/develop/references/sync-gateway/rest-api/database/post-all-docs/index.html)

It looks like the view pass-through also supports including a `keys` parameter - it's explicitly referenced in the handleView() implementation, but I haven't tested that to confirm yet.

**Comment by adamcfraser** [comment]
Reviewed with James - I don't think anything additional is needed to support.
