### ISSUE TITLE
Document implementation design taking bucket offline/online

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#907]
Breaking this action item from ticket #748 into a separate ticket for allocation in next sprint.

**Comment by adamcfraser** [comment]
One additional feature request, based on customer input.  When bringing a bucket online, it would be useful to be able to define a delay between the time we start processing the TAP feed, and the time the Sync Gateway node starts processing requests.  It's probably more like another SG node state - 'STARTING'.  The amount of time the SG node spends in 'STARTING' state should be a config setting.

The goal is to address the scenario where the SG TAP feed starts at sequence y, but the channel views are only indexed up to sequence x.  Any channel cache backfill requests will miss sequences between x and y.  Introducing the 'STARTING' delay will give the index time to catch up to y.

**Comment by ajres** [comment]
Implementation design notes are on the [wiki](https://github.com/couchbase/sync_gateway/wiki/Sync-Gateway-DB-online-offline-implementation-design-notes)

**Comment by adamcfraser** [comment]
Design work is complete - closing this.
