### ISSUE TITLE
Extend Perfcluster AWS to optionally support a load balancer

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#913]
For some load test scenarios it will be necessary to put a load balancer in front of the the Sync Gateway nodes.

We need to optionally support an HAProxy based load balancer in the Perfcluster-AWS for the following test scenarios.

1 - to reproduce the increasing memory scenario, similar to what has been done with Gatling client terminating the connections.  We don't expect results significantly different than the Gatling setup, but would be more definitive confirmation of a connection issue.

2 - to be able to test whether _changes heartbeats get swallowed when using compression and chunked transfer encoding, and then test that setting no-cache on the Sync Gateway _changes requests fixes that issue

**Comment by tleyden** [comment]
@ajres so it sounds like nginx should be the default, but we'd also like to support HAProxy?

**Comment by ajres** [comment]
Closing this in favour of tracking this under the overarching ticket

**Comment by ajres** [comment]
Closing this in favour of tracking progress under the original customer ticket #768
