### ISSUE TITLE
Upgrade CBS from 2.5.2 to 3.1 and run sync gateway tests

### ISSUE THREAD

**Issue by suravarjjala** [couchbase/sync_gateway#919]
Sync gateway functional tests need to be run on a upgraded CBS environment

**Comment by ashvindersingh** [comment]
This task involves upgrading the Couchbase server from version x -> y. The SG is online through out the upgrade process of CBS. There are multiple nodes present in the CBS.  The test would take out node offline, do rebalance of the remaining node, Upgrade the offline node. Verify that  during the upgrade process or after the upgrade data/changes made are consistent with the expected result. 

A jenkins job will used  to run this tests. 
Using repos - 
- https://github.com/couchbaselabs/sync-gateway-tests and https://github.com/couchbase/testrunner.

**Comment by ashvindersingh** [comment]
Completed the automation and implemented it in jenkins: http://qa.hq.northscale.net/view/mobile/job/CBS_Upgrade_test_w_SG_mobile/
