### ISSUE TITLE
Gatling scenario for access grants

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#920]
Factored out of https://github.com/couchbase/sync_gateway/issues/853
- Custom Sync Gateway config (no gatling change needed)
- Gateload was changed to add a new field to the doc, which the sync function used

**Comment by tleyden** [comment]
Gateload commit: https://github.com/couchbaselabs/gateload/commit/5bebb749dc21ba55bbc350d236f53fd8da033b34

**Comment by tleyden** [comment]
Re-assigning this to myself.  This is a good excuse to familiarize myself with Gatling.

**Comment by adamcfraser** [comment]
Will be handled as sgload-based scenario.
