### ISSUE TITLE
Perfcluster AWS: expvars not being indexed correctly

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#926]
When indexed correctly in splunk, the json should look like this when clicking the small arrow to the left of the event. 

![screen shot 2015-06-15 at 5 00 04 pm](https://cloud.githubusercontent.com/assets/296876/8173282/19fc4b38-1380-11e5-8d7e-c643c3df9c77.png)

However, the events with `source="/home/centos/_expvar.logs"` are not being indexed correctly, and it appears as this:

![screen shot 2015-06-15 at 5 02 30 pm](https://cloud.githubusercontent.com/assets/296876/8173306/566c5126-1380-11e5-936d-8268958d08ec.png)

I believe the reason is that there are timestamps being added to _expvar.logs, eg:

```
Mon Jun 15 23:00:01 UTC 2015
{
"cb": {"ops": {"Incr": ...
}
Mon Jun 15 23:01:01 UTC 2015
{
"cb": {"ops": {"Incr": ...
}
```

I _think_ the fix is just to remove the timestamps, but it needs to be tested.

**Comment by andreibaranouski** [comment]
It seems everything is working right now http://www.awesomescreenshot.com/image/338674/6f72b8f12993d00e028e6131514c722d

**Comment by tleyden** [comment]
Did you make a fix?  Which commit?

**Comment by tleyden** [comment]
Under Events section you should see cb.ops.*

**Comment by andreibaranouski** [comment]
fix https://github.com/couchbaselabs/perfcluster-aws/commit/bc08071759f13fd47630af9edc74be45667b81ef
result http://i.imgur.com/06MipCH.png
please let know if something doesn't work for you

**Comment by tleyden** [comment]
Ah cool.  I can tell from the screenshot that it's fixed.
