### ISSUE TITLE
Support skip parameter in querystring for /_all_docs

### ISSUE THREAD

**Issue by jamesnocentini** [couchbase/sync_gateway#928]
The docs [reference](http://developer.couchbase.com/mobile/develop/references/couchbase-lite/rest-api/database/get-all-docs/index.html) the `skip` parameter for :4984/_all_docs but trying this out doesn't seem to skip any document.

See context [here too](http://stackoverflow.com/questions/30867546/couchbase-skip-attribute-for-pagination-not-working).

**Comment by pasin** [comment]
From source code, it doesn't seems SGW handle `skip` param.

**Comment by adamcfraser** [comment]
The docs should get updated to remove skip, but more importantly:

From the linked context, it sounds like the user is wanting to use _all_docs for pagination through their data set.  I'd strongly recommend using _changes instead, for both performance and correctness.  _all_docs is view-based, so each _all_docs request is going to trigger a new view call.  If the data isn't fixed, using skip for pagination could result in either duplicate or missed entries.  Using _changes with limit for pagination avoids these problems.  In addition, _changes is based on the in-memory channel cache, and so will usually have much less performance overhead than the view call being made by _all_docs on every request.

**Comment by jamesnocentini** [comment]
Closing this issue as it's being tracked in this PR https://github.com/couchbaselabs/couchbase-mobile-portal/pull/507
