### ISSUE TITLE
couchbase-sync-gw-functional-tests Jenkins job failing

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#935]
http://mobile.jenkins.couchbase.com/view/Couchbase_Lite/job/couchbase-sync-gw-functional-tests/34/ is failing.  

Tests are taking a very long time.

Logging output is hard to tell what's going on.

**Comment by tleyden** [comment]
@andreibaranouski I see some passed, can we close this ticket? http://mobile.jenkins.couchbase.com/job/sync-gateway-functional-tests/134/

**Comment by ashvindersingh** [comment]
This is fixed now. Please see: http://qa.hq.northscale.net/job/cen006-p0-syncgateway-functional-tests/22/
