### ISSUE TITLE
High memory usage during push replication

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#936]
Separating out the push-specific memory usage issue raised by @hegra from #768.

**Comment by adamcfraser** [comment]
From @hegra on #768:

We have a similar issue.
A few hours of running sync gateway eats 3 GB of memory and a restart of sync gateway is needed.

Running the following version: https://aws.amazon.com/marketplace/pp/B00FA8DO50 on single m1.medium instance. Also upgraded sync gateway to master(bfb402f) but no noticeable difference.
No proxy in use that I'm aware of.

5 android (couchbase-lite-android:1.1.0-532) clients connected with continuous sync in push mode. Documents of around 100kb, no attachments. Documents updated a few times every minute so revisions can get quite long. Using revs_limit:20

"compressResponses": false in config.json didn't have any effect, if this is the right place to add it?

Update: The following client code can consume the memory within 30 min: http://pastebin.com/3mBsENy1 (Need to set sleep to around 1000 ms for every document else a memory leak in the client code will be exposed before!)

**Comment by adamcfraser** [comment]
At this point it seems likely to be related to revision cache size - SG currently stores last 5000 revisions in memory.  Currently working to reproduce internally - then can evaluate potential options to support memory management for revision cache.

**Comment by hegra** [comment]
Setting "revs_limit":5 didn't make any large difference

**Comment by ajres** [comment]
We are current running a load test scenario that pushes document revs to a set of docs to see if we can invoke a memory leak.

Currently we are updating 1000 docs, each doc is 100KBytes, we are writing up to 24 revisions per doc.

This number of revs will fill the rev cache which is currently set to a max size of 5000.

**Comment by tleyden** [comment]
From [Understanding Go Lang Memory Usage](https://deferpanic.com/blog/understanding-golang-memory-usage/):

> Typically if you go 2 minutes without garbage collection it will get ran. If a span goes unused for 5 minutes the scavenger allows it to be released.
> 
> So if you suspect that your memory usage should be going back down give it ~ 7 minutes just to verify.

^^ relevant to our conversation yesterday about whether the GC was being triggered after the Gatling test finished.

**Comment by tleyden** [comment]
By the way, this comment from [Understanding Go Lang Memory Usage](https://deferpanic.com/blog/understanding-golang-memory-usage/)

> Last but not least - on go 1.3 goroutine stacks, which are 8k/pop, don’t get released - they get re-used later on. Don’t fret though - Go still has plenty of room for improvement in the GC department. So if your code is spawning a ton of goroutines and your RES is staying high this could be why.

is no longer true, as it has been addressed in go 1.4 as [discussed here](https://groups.google.com/d/msg/golang-nuts/0WSOKnHGBZE/ZnOX-1LBZBcJ)

**Comment by tleyden** [comment]
[WriteHeapDump](https://golang.org/pkg/runtime/debug/#WriteHeapDump) looks potentially interesting.

**Comment by zgramana** [comment]
As does [FreeOSMemory](), relevant to our conversation this morning:

> FreeOSMemory forces a garbage collection followed by an attempt to return as much memory to the operating system as possible. (Even if this is not called, the runtime gradually returns memory to the operating system in a background task.)

**Comment by zgramana** [comment]
[SetGCPercent](http://golang.org/pkg/runtime/debug/#SetGCPercent) seems like the most pertinent, as it's default is 100%! For an app like SG, you could end up with a GC that seldom runs.

Sounds like others have run into [eerily similar situations](http://stackoverflow.com/a/27214494):

>  I had an HTTP cache take up over 200% the cache size once. Try tuning the percentage to somewhere around 10% and see if it helps.

**Comment by zgramana** [comment]
The interaction between FreeOSMemory and SetGCPercent seems to have the potential to significantly lower SG's memory footprint.

**Comment by ajres** [comment]
Following profile reports were generated from SG with different rev cache sizes.

https://s3-us-west-2.amazonaws.com/couchbase-mobile/misc/issue_936_attachments/100-rand-100KByte-docs-100Byte-props-revdepth-120-cache-5000-profile-data.tar.gz

https://s3-us-west-2.amazonaws.com/couchbase-mobile/misc/issue_936_attachments/100-rand-100KByte-docs-100Byte-props-revdepth-120-cache-5000-stopped-profile-data.tar.gz

https://s3-us-west-2.amazonaws.com/couchbase-mobile/misc/issue_936_attachments/100-rand-100KByte-docs-100Byte-props-revdepth-50-cache-500-profile-data.tar.gz

https://s3-us-west-2.amazonaws.com/couchbase-mobile/misc/issue_936_attachments/100-rand-100KByte-docs-100Byte-props-revdepth-50-cache-500-stopped-profile-data.tar.gz

https://s3-us-west-2.amazonaws.com/couchbase-mobile/misc/issue_936_attachments/100-rand-100KByte-docs-100Byte-props-revdepth-55-cache-1000-profile-data.tar.gz

https://s3-us-west-2.amazonaws.com/couchbase-mobile/misc/issue_936_attachments/100-rand-100KByte-docs-100Byte-props-revdepth-55-cache-1000-stopped-profile-data.tar.gz

https://s3-us-west-2.amazonaws.com/couchbase-mobile/misc/issue_936_attachments/100-rand-100KByte-docs-100Byte-props-revdepth-90-cache-1000-closebody-profile-data.tar.gz

**Comment by ajres** [comment]
Profiles show linear memory consumption with rev cache max size configuration. Initially will add a configuration option to configure rev cache max size, tracking in ticket #966

**Comment by ajres** [comment]
Closing this ticket out, now tracking fix via #963
