### ISSUE TITLE
Come up with a solution for high user doc contention

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#937]
Factored out of #853 

When the Sync Function changes channel access, there is high user doc contention.
- [ ] Describe the issue in detail
- [ ] Schedule discussion meeting
- [ ] Create [gatling scenario](https://github.com/couchbase/sync_gateway/issues/920)

**Comment by adamcfraser** [comment]
Closing based on age, and lack of specifics in this ticket.
