### ISSUE TITLE
Rebuild or remove outdated AMI with Sync Gateway 1.0.3

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#938]
Ideal scenario: generated as part of our build/release process
Interim: manually update it
Interim #2: remove AMI completely until either of the above are completed

**Comment by tleyden** [comment]
See https://github.com/couchbase/couchbase-lite-java-core/issues/665#issuecomment-113570577 for an example of users running into issues because they are using an outdated release.

**Comment by zgramana** [comment]
I need to file a ticket Willy in support.

**Comment by zgramana** [comment]
These should be live now. Pending verification.

**Comment by zgramana** [comment]
Still pending approval from AWS Marketplace staff.
