### ISSUE TITLE
Some example JSON configs include non-UTF8 chars

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#943]
User reported on https://github.com/couchbase/couchbase-lite-java-core/issues/665 that at least one of the example configs had one or more non-UTF8 chars that prevented SG from properly deserializing the config.

**Comment by adamcfraser** [comment]
I did a quick pass and don't see anything non-UTF8 in the example configs - in particular no \r Windows line breaks.  It seems more likely that the user made some manual edits to the config in a Windows text editor (they do mention 'adapting the config to their needs' in the java-core ticket.
