### ISSUE TITLE
Define standardized "spec" for test logging and result reporting

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#946]

**Comment by tleyden** [comment]
@andreibaranouski can you hep me figure out the list of outputs emitted by the [sync-gateway-tests](https://github.com/couchbaselabs/sync-gateway-tests)?
1. Sync Gateway logs
2. Raw "test console ouput" -- this includes which tests are being run
3. TAP test output -- structured test output that can then be rendered into a report

Does this sound right?  Am I missing anything major here?

**Comment by andreibaranouski** [comment]
Hi @Traun,
recently I made some changes in the output logs for the tests:
1) when run entire suite via "npm test" now we get only summary for the tests like
ok tests/cbl-large-revisions-compact.js ............... 62/62
so, we don't get a bunch of unnecessary output from tap tests
2) then I decided to hide SG output as well(but most likely it was superfluous). SG output was hidden when run entire suite('npm test') but still was available when run any test( node tests/test_name.js) 
now I'm rolling back this change and SG output should be available with any run:
https://github.com/couchbaselabs/sync-gateway-tests/commit/e836a2dd1a8f7503e6768e345233a96ae286f22e

probably, soon I will reimplement the output  for SG logs in a separate file for each test.

please let me know if you have any more questions.

**Comment by tleyden** [comment]
@andreibaranouski can you run the functional tests in a jenkins job and link to the result here?

Also, can you list all of the available outputs?  I think it's this:
1. Sync Gateway logs
2. Raw "test console ouput" -- this includes which tests are being run
3. TAP test output -- structured test output that can then be rendered into a report

we want to first confirm what's available and then we need to decide what should be captured into files, and what should be in the jenkins console.

**Comment by tleyden** [comment]
> probably, soon I will reimplement the output for SG logs in a separate file for each test.

If that's too hard, another approach could be to add an admin endpoint to Sync Gateway that would log a custom message (eg, call _log?msg=foo causes foo to be written to the logs), which would at least allow us to segment the logs by tests.
