### ISSUE TITLE
[windows] in startup menu there are 2 folders under Couchbase, Inc.: Sync_Gateway and Sync Gateway

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#949]
build 1.1.0-28
http://i.imgur.com/CP2mS43.png

Couchbase, Inc.
-Sync Gateway
  --Uninstall Couchbase Sync Gateway
-Sync_Gateway
  --Launch Couchbase Sync Gateway

**Comment by adamcfraser** [comment]
Should be validated as part of release testing for 1.4

**Comment by ajres** [comment]
Tested SG(A) on Windows 10, this displays in a single folder on the start menu

<img width="310" alt="screen shot 2017-11-07 at 14 57 40" src="https://user-images.githubusercontent.com/7745210/32500021-1110c3ba-c3cc-11e7-9fa1-ecdaa471f628.png">

**Comment by ajres** [comment]
Closing this ticket, reopen if this needs to be tested on older releases of Windows.

Opened a new ticket #3039 for the missing "Uninstall Couchbase Sync Gateway" menu entry
