### ISSUE TITLE
Identify minimum system requirements

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#951]
Need to systematically identify what we want to consider the minimum system requirements for SG.

**Comment by ingenthr** [comment]
You've probably thought of this too, but I'd recommend separating this into "development" and "production" minimum requirements to make sure getting developing is as easy as possible.

**Comment by zgramana** [comment]
Good suggestion!

> You've probably thought of this too, but I'd recommend separating this into "development" and "production" minimum requirements to make sure getting developing is as easy as possible.

**Comment by djpongh** [comment]
Working on sizing document with sales team
