### ISSUE TITLE
Retry connection to Couchbase Server

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#963]
When starting Sync Gateway if a connection to Couchhbase Server can not be established SG should retry after a delay, SG should keep retraying with an increasing delay until a max time is reached (10 Minutes?)

This will help in situations where Couchbase Server takes longer to startup that Sync Gateway.

**Comment by tleyden** [comment]
You beat me to it.  I was planning to file this same ticket.

**Comment by adamcfraser** [comment]
Fixed with https://github.com/couchbase/sync_gateway/pull/2054.
