### ISSUE TITLE
SSL client cert auth support

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#964]
It would be good if SG could allow clients to authenticate using SSL certs. It's a very secure form of authentication (especially if the client stores the cert on a smart-card or dongle or something.) I've [added client-side support to CBL/iOS](https://github.com/couchbase/couchbase-lite-ios/issues/82).

It's very easy in Go to request and identify the client cert (I've already got a local branch of SG that does it.) The question is how to authenticate that cert, i.e. map it to an SG user account. Some possibilities:
- Let some middleware like nginx do the work — a proxy that acts as the SSL endpoint, authenticates the client cert, then passes the requests to Sync Gateway. It would need to pass on the auth info, maybe by looking up user info and adding an “Authorization” header to the request.
- Let the SG config file point to a CA certificate file; any client cert signed by this CA will be accepted. (But then how are client certs mapped to usernames?)
- Let the SG config file point to a directory of certificate files, any of which will be accepted. (But again, how to map to usernames? Maybe the filename is the username?)
- Maybe that directory of cert files should instead be a group of docs in the bucket, named something like `_sync:cert:______` where the blank is the SHA-1 digest of the certificate. The doc body could contain the username the cert maps to. In that case we'd need a REST API to manipulate these (maybe as part of the existing `_user` API.)

**Comment by adamcfraser** [comment]
Tracking with CBG-570.
