### ISSUE TITLE
Add new configuration option for revision cache size

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#966]
We need to add a new Sg configuration option to allow the revision cache max size to be configured.

This is useful for tuning memory consumption when running SG on smaller resource servers, or for tuning SG for use in high write where odcs are all new and where there are limited read operations.

**Comment by ajres** [comment]
Added a per DB configuration option MaxRevsCacheSize default is 5000 which is unchanged from previous

**Comment by andreibaranouski** [comment]
Hi @adamcfraser, 

first of all there is a spelling error in param max_revs_caHCe_size
https://github.com/couchbase/sync_gateway/blob/55b487be3db991b98711961df86a44deb257a83c/src/github.com/couchbase/sync_gateway/rest/config.go#L96

when I run 

```
{
    "log":["REST", "Shadow", "CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Changes", "Changes+","Auth", "SSL"],
   "databases": {
      "db": {
        "server": "walrus:",
        "max_revs_cahce_size": "444dd"
    }
    }
}
```

I expect to get error like "cannot unmarshal string into Go value of type uint32"
but I don't get any errors when start SG. I think that is not working properly, or am I doing something wrong?

build 1.1.1-5

**Comment by ajres** [comment]
@Andrei

The configuration parameter is:

rev_cache_size

Andy

From: Andrei Baranouski
Reply-To: couchbase/sync_gateway
Date: Friday, 7 August 2015 13:41
To: couchbase/sync_gateway
Cc: Andrew Reslan
Subject: Re: [sync_gateway] Add new configuration option for revision cache size (#966)

Hi @adamcfraserhttps://github.com/adamcfraser,

first of all there is a spelling error in param max_revs_caHCe_size
https://github.com/couchbase/sync_gateway/blob/55b487be3db991b98711961df86a44deb257a83c/src/github.com/couchbase/sync_gateway/rest/config.go#L96

when I run

{
    "log":["REST", "Shadow", "CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Changes", "Changes+","Auth", "SSL"],
   "databases": {
      "db": {
        "server": "walrus:",
        "max_revs_cahce_size": "444dd"
    }
    }
}

I expect to get error like "cannot unmarshal string into Go value of type uint32"
but I don't get any errors when start SG. I think that is not working properly, or am I doing something wrong?

build 1.1.1-5

**Comment by andreibaranouski** [comment]
ops, in the current SG version that's right, I started to look at it in above PR
