### ISSUE TITLE
Document new config option for revision cache size

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#967]
Once issue #966 is complete add documentation for the new revision cache max size configuration proeprty

**Comment by ajres** [comment]
Waiting for PR #982 to be approved

**Comment by JeffThomasWriter** [comment]
Documented: revCacheSize: integer: Size of the revision cache, specified as the total number of document revisions to cache in memory for all recently accessed documents.
When the revision cache is full, Sync Gateway removes less recent document revisions to make room for new document revisions. Adjust this property to tune memory consumption by Sync Gateway, for example on servers with less memory and in cases when Sync Gateway creates many new documents and/or updates many documents relative to the number of read operations. The default is 5000.
