### ISSUE TITLE
Can't initiate websocket connection

### ISSUE THREAD

**Issue by RemyRylan** [couchbase/sync_gateway#973]
I get the following error in the sync gateway process when trying to establish a websocket connection:

```
2015/07/04 22:01:31 http: panic serving [::1]:51356: interface conversion: *rest.EncodedResponseWriter is not http.Hijacker: missing method Hijack
goroutine 37 [running]:
net/http.func·011()
    /usr/local/go/src/net/http/server.go:1130 +0xbb
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x98ea98, ...)
    /Users/jenkins/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/golang.org/x/net/websocket/server.go:74 +0x76
golang.org/x/net/websocket.Server.ServeHTTP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x98ea98, ...)
    /Users/jenkins/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/golang.org/x/net/websocket/server.go:70 +0x5a
github.com/couchbase/sync_gateway/rest.(*handler).sendContinuousChangesByWebSocket(0xc208066ab0, 0xc20820bd70, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208139860, 0x0, 0x493e0, ...)
    /Users/jenkins/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/changes_api.go:404 +0x1c2
github.com/couchbase/sync_gateway/rest.(*handler).handleChanges(0xc208066ab0, 0x0, 0x0)
    /Users/jenkins/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/changes_api.go:142 +0xc49
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc208066ab0, 0x98e910, 0x0, 0x0)
    /Users/jenkins/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x4b8
github.com/couchbase/sync_gateway/rest.func·015(0xe2ad50, 0xc2081430e0, 0xc20816f040)
    /Users/jenkins/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7d
net/http.HandlerFunc.ServeHTTP(0xc20820efe0, 0xe2ad50, 0xc2081430e0, 0xc20816f040)
    /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20813fb80, 0xe2ad50, 0xc2081430e0, 0xc20816f040)
    /Users/jenkins/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x29e
github.com/couchbase/sync_gateway/rest.func·017(0xe2ad50, 0xc2081430e0, 0xc20816f040)
    /Users/jenkins/jenkins/workspace/sync-gateway-unix-builds/release/1.1.0/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:236 +0x32f
net/http.HandlerFunc.ServeHTTP(0xc208180320, 0xe2ad50, 0xc2081430e0, 0xc20816f040)
    /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208157680, 0xe2ad50, 0xc2081430e0, 0xc20816f040)
    /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208142e60)
    /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e
```

My config file looks like this:

```
{
   "interface": ":4984",
   "adminInterface": ":4985",
   "log": ["CRUD", "REST+", "Access", "HTTP+"],
   "CORS": {
     "Origin": ["http://localhost:3000"],
     "Headers": ["Content-Type"],
     "MaxAge": 1728000
   },
   "databases": {
      "foobar": {
         "server": "http://localhost:8091",
         "bucket": "foobar",
         "sync": `
          function(doc) {
            channel(doc.channels);
          }
         `,
         "users": {
           "GUEST": {
             "disabled": false,
             "admin_channels": ["*"]
           }
         }
      }
   }
}
```

I have tried getting this to work with the main download of v1.1.0 from http://www.couchbase.com/nosql-databases/downloads and by building from source -- both produced the same result.

Here's the JavaScript code I am using to test in Chrome:

```
var s = new WebSocket("ws://localhost:4984/foobar/_changes?feed=websocket");

s.onmessage = function (event) {
    console.log(event.data);
}

s.onopen = function (event) {
    s.send("Hello, Server!");
};
```

The other modes work with no problem, longpolling, etc... are all fine, however I really need to use websockets for this particular application.

I'm on a MacBook Pro, OS X Yosemite.

**Comment by ajres** [comment]
@JeremyRylan 

There is a bug in Sync Gateway when trying to promote an http connection to a Websocket when gzip compression is enabled on responses.

It is likely that your JS WebSocket passes a default HTTP Header "Content-Encoding: gzip, deflate", can you remove this header and retest?

We have seen a similar issue when using a node.js client to Sync Gateway over Websockets

Andy

**Comment by RemyRylan** [comment]
@ajres Thank you very much for the response, Andy.

I fired up a proxy just so I could accurately capture all of my headers and here is the result:

```
{ host: 'localhost:3000',
  connection: 'Upgrade',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  upgrade: 'websocket',
  origin: 'http://localhost:3000',
  'sec-websocket-version': '13',
  dnt: '1',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2449.0 Safari/537.36',
  'accept-encoding': 'gzip, deflate, sdch',
  'accept-language': 'en-US,en;q=0.8',
  cookie: 'locale=en-US',
  'sec-websocket-key': 'FNVRAam9+X5Z2GSwRJH4Og==',
  'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits' }
```

Nothing in there for `"Content-Encoding: gzip, deflate"`. For the heck of it, I tried removing `gzip` from the `accept-encoding` header and that just causes a websocket protocol error and refuses to even attempt the connection.

Any other ideas?

**Comment by adamcfraser** [comment]
While Andy looks into this issue, can you test whether you're able to work around the problem by setting `"compressResponses":false` in your Sync Gateway server config? (example here: https://gist.github.com/adamcfraser/a6229a557b955f91553b)

**Comment by RemyRylan** [comment]
@adamcfraser Thank you! `"compressResponses":false` in the config file did the trick. I can successfully connect and stay connected via websockets.

**Comment by ajres** [comment]
ToDoLite-iOS uses websockets and does not cause SG to panic even when "compressResponses":false is missing from the SG config.

The _changes request looks like this:

```
http://andrews-macbook-pro.local:4984/todolite/_changes?feed=websocket
```

The HTTP headers sent with the _changes request from iOS are as follows:

```
Sec-WebSocket-Version    13
Sec-WebSocket-Key EuD1lnzoosD3xhctKHxNBw==
Upgrade    websocket
Connection    Upgrade
User-Agent    CouchbaseLite/1.1.0 (iOS)
Cookie    SyncGatewaySession=f454eb8491bbb82e9dce15646470460fe92e1147
Host    Andrews-MacBook-Pro.local:4984
```

**Comment by ajres** [comment]
Confirmed that adding the following HTTP header to the _changes request causes the panic:

```
"Accept-Encoding: gzip, deflate"
```

**Comment by ajres** [comment]
WebSockets can support per frame compression, via an extension. Draft spec is [here](http://tools.ietf.org/html/draft-tyoshino-hybi-permessage-compression-00).

**Comment by ajres** [comment]
Does CouchBaseLite support this websocket extension?

**Comment by ajres** [comment]
Talking with @snej

"IIRC the WebSocket library I use on iOS supports it. But Go's WebSocket implementation doesn't."
"But BLIP already supports gzip compression of its messages, so I don't think it's necessary."

**Comment by ajres** [comment]
This ticket will address the issue of switching to the EncodedResponseWriter for _changes feed with feed type of "websocket".

**Comment by colinjlacy** [comment]
@ajres , you mention in your first reply that you saw similar problems working with Node.js clients to connect to a sync gateway `_changes` endpoint with `feed=websockets`.  Was a solution ever found?  

I'm currently experiencing the same results listed above:
- I get the connection to my node client and my `client.on('connect')` event fires
- the 101 upgrade code is logged in the sync gateway
- when I close the sync gateway, my `client.on('close') event firest

But no messages are sent on change events from the `_changes` endpoint.  Nor are any `sending X change(s)` events logged in the sync gateway.

```
2015-12-09T15:16:26.354Z HTTP:  #006: GET /default/_changes?feed=websocket
2015-12-09T15:16:26.354Z HTTP+: #006:     --> 101 Upgraded to WebSocket protocol  (0.0 ms)
```

When I switch to `feed=continuous` I get expected behavior.  Changes are logged in the sync gateway, and sent to my client, which then logs them as HTTP responses.

I'm using the latest Docker image of the sync gateway, which I believe is 1.1.0.

My headers are as follows:

```
{ upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-version': '13',
  'sec-websocket-key': '3oEhcMLr65Q/lPj4NZff7w==',
  host: '192.168.99.100',
  origin: 'http://localhost' }
```

I've also tried a few different combinations of the `Accept-Encoding` header, but no luck so far.  Any thoughts?

**Comment by zgramana** [comment]
Can @ajres and @snej discuss the intersection of this ticket with #1179?

**Comment by snej** [comment]
With regard to the earlier discussion: `Accept-Encoding` has nothing to do with WebSocket compression. Once the connection is upgraded to WebSocket protocol, HTTP response attributes are irrelevant.

**Comment by snej** [comment]
@colinjlacy: Sync Gateway is waiting for the client to send the changes feed parameters (`since`, `filter`, etc.) You send those in a text message containing a JSON object whose keys are the regular `_changes` parameter names.

**Comment by colinjlacy** [comment]
Thanks, @snej.  So if I'm understanding you correctly, once I establish the connection, I need to send a message from the client with something like `{since: 112233, include_docs: true}`, just like any other client-to-server message that you might find over a websocket.  Is that right?

**Comment by snej** [comment]
Yes, correct. I've just updated the spec for WebSocket-based changes, and moved it to the Sync Gateway wiki, [here](https://github.com/couchbase/sync_gateway/wiki/WebSocket-Based-Changes-Feed).

**Comment by colinjlacy** [comment]
@snej This worked perfectly.  I am seeing some `1000` disconnect events when the sync gateway doesn't pass data for 5 minutes.  Is there anyway to keep the connection alive?  Currently running v1.2

**Comment by adamcfraser** [comment]
@colinjlacy Have you set the heartbeat property on the changes request?  That will send a newline that should keep the connection open.  (http://developer.couchbase.com/documentation/mobile/1.2/develop/references/sync-gateway/rest-api/database-public/get-changes/index.html#request)
