### ISSUE TITLE
Ability to assign "default channels" to new users

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#98]
Problem: when a new user is created via a Persona Login, that user does not have any access to any channels.

It would be useful to be able to specify in the config that any new users created by the sync gateway woud automatically added to a list of channels.  Eg, "announcements" channel.

**Comment by Fujio-Turner** [comment]
When SG creates users using the oauth 2.0 flow users are created but only have access to the ["!"]. It be great to give access to the username as a channel too. 
["!","sg-username-here"]

**Comment by adamcfraser** [comment]
@Fujio-Turner I think that's fundamentally a different request than this original ticket.  Please file a separate enhancement request for the 'user is granted `username` channel by default'.

**Comment by adamcfraser** [comment]
Closing this ticket - Persona no longer used.
