### ISSUE TITLE
Deleting role w/ Admin REST API isn't removed in GET /db/_role/ response

### ISSUE THREAD

**Issue by jamesnocentini** [couchbase/sync_gateway#980]
See the unit test in PR https://github.com/couchbase/sync_gateway/pull/979.

**Comment by zgramana** [comment]
Per @adamcfraser, there are some unexpected behaviors going on that merit follow-up investigation.

**Comment by adamcfraser** [comment]
This appears to be a walrus-specific issue, as I'm able to reproduce running a standalone Sync Gateway with a walrus bucket, but not when running a Sync Gateway using a Couchbase bucket.

**Comment by adamcfraser** [comment]
Closing as it's a walrus-only issue, and a bit of a corner case.
