### ISSUE TITLE
Improvements to extend session info with auth type and auth level when using custom auth

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#981]
When use custom auth with sync gateway with mobile app and web app,There is a typical use case as follows:
1. auth user by SMS certification by mobile apps, and then create session info;
2. auth user by Qr code certification only, that require user must login in mobile apps first;
3. user can terminate web app's session by mobile's function that delete web app's session;
4. when user logout from mobile app, then terminate web app's session.
sync gateway have no limit in session number, but when I only want to delete web app's session, I can not tacking web app's session, unless I have a type property in session info,such as:

type LoginSession struct {
    ID         string        `json:"id"`
    Username   string        `json:"username"`
    Expiration time.Time     `json:"expiration"`
    Ttl        time.Duration `json:"ttl"`
        Authtype    string   `json:"authtype"`
        Authlevel    int   `json:"authtlevel"` 
}

so with username and authtype,I can find the web app's session and then delete it.maybe I also want to extend auth type with multi-factor auth, So  I might need a authlevel property.
I think this is a common requirement， because most mobile apps have web app, and they might have the same problem.

**Comment by ajres** [comment]
@atom992 

There is documentation[here](http://developer.couchbase.com/mobile/develop/references/sync-gateway/admin-rest-api/session/index.html)  for ADMIN REST API methods for deleting user sessions.

If those do not meet your needs could you provide some more details on what methods you would need for your use case.

Andy

**Comment by ajres** [comment]
This ticket will be closed out in seven days if there is no additional information.

Andy

**Comment by atom992** [comment]
For Create Session,I need the API like this:
POST /{db}/_session
{
    "name": "chef123",
    "password": "1234"，
    "authtype":"SMS",
    "authlevel":"1"
}
where authtype can be custom,such as SMS,QR,CERT etc.authlevel could be int value, the bigger number means the auth level is higher.
when I delete session,I can get session by authtype or authlevel,such as 
GET /{db}/_session?authtype=SMS
and then I can delete the session(it is better if I can delete session by authtype).
