### ISSUE TITLE
Webhook events not sent

### ISSUE THREAD

**Issue by puffin** [couchbase/sync_gateway#984]
I follow the installation instruction on https://github.com/couchbaselabs/couchbase-server-coreos to build up a stack on AWS. Even if I added the event_handlers in the config file, I didn't see any events coming on my server.

Here you can find the config file: https://dl.dropboxusercontent.com/u/413885/sync_gw_config.json.

**Comment by adamcfraser** [comment]
You've got two databases defined in your config - `db` and `couchbase-chat`.  Only `db` has the webhook definition.  To confirm - you're updating documents in the `db` database (bucket `sync_gateway`) and not seeing the webhook events?

**Comment by puffin** [comment]
Yes I confirm that I'm updating documents in the `db` database  (bucket `sync_gateway`) and not the other one.

**Comment by adamcfraser** [comment]
Are you seeing any Events logging in the SG logs?

**Comment by puffin** [comment]
In fact this file `sg_error.log` is not even created.

**Comment by adamcfraser** [comment]
With the config specified, you should at least see the startup information being written to sg_error.log.

You've been able to validate that your sync gateway is started successfully, I take it?

**Comment by puffin** [comment]
Yes the sync_gateway is working properly. It synchronises correctly the app we have on iOS with couchbase lite and couchbase server. We have 3 sync_gateways behind nginx that serves as load balancer. Only webhooks are not working properly yet. the sync_gateway server is hosted here: http://couch.utribo.com at the moment.

**Comment by puffin** [comment]
I think I found the cause of the issue. I used docker to set up the sync_gateway and use the latest build from docker hub: https://registry.hub.docker.com/u/couchbase/sync-gateway/builds_history/188654/. But when I look at the sync_gateway server version here http://couch.utribo.com it returns `Couchbase Sync Gateway/HEAD(nobranch)(04138fd)` which correspond to the the 1.0.4 tag, not the 1.1.0.

**Comment by tleyden** [comment]
@puffin can you try explicitly running the following on allon all of your docker hosts?  After that you'll 
- `docker stop [container_id] && docker rm [container_id]`
-  `docker pull couchbase/sync-gateway` 
- `docker run` it using the same flags you originally ran it with.

**Comment by puffin** [comment]
I explicitly did a pull with the 1.1.0 version on dockerhub `docker pull couchbase/sync-gateway:1.1.0` and it works. So it seems that the latest tag on dockerhub did not point to 1.1.0 but 1.0.4 instead.

**Comment by puffin** [comment]
@tleyden fixed the issue and everything is working properly now. More details can be found also here: https://github.com/tleyden/sync-gateway-nginx-confd/issues/1
