### ISSUE TITLE
Improve failure handling during invalidateChannels

### ISSUE THREAD

**Issue by mjq** [couchbase/sync_gateway#986]
I'm trying to track down why a particular user document doesn't have access to a channel.

Our DB has Group documents that have a userIds field. Every ID in userIds gets access to the group channel (`g_a43...`) and each pair of userIds gets access to a DM channel between them (`dm_93e..._2dc...`).

Here's the sync function:

``` javascript
function(doc, oldDoc) {
  function dmChannelName(id1, id2) {
    var ids = [id1, id2];
    ids.sort();
    return 'dm_' + ids[0] + '_' + ids[1];
  }

  if (doc.type === 'Group') {
    requireUser('admin');
    var groupChannel = 'g_' + doc._id;
    access(doc.userIds, groupChannel);
    for (var i = 0; i < doc.userIds.length - 1; ++i) {
      for (var j = i + 1; j < doc.userIds.length; ++j) {
        var id1 = doc.userIds[i], id2 = doc.userIds[j];
        access([id1, id2], dmChannelName(id1, id2));
      }
    }
    channel(groupChannel);
  } else {
    throw('unknown type: ' + doc.type);
  }
}
```

Here's the group document in question, from Couchbase. It has two users, and it looks like it's assigning the channels correctly.

``` javascript
{
  "_sync": {
    "rev": "4-7897bc456754fe437c67abcfa36a6234",
    "sequence": 48291,
    "recent_sequences": [
      41322,
      45506,
      47792,
      48291
    ],
    "history": {
      "revs": [
        "1-b3bf537ab0e0ed510ef897cdd05ef504",
        "2-19365f26a21fa050089e3b62fd646391",
        "3-fab773c4b54410c754c3167514ef2cdd",
        "4-7897bc456754fe437c67abcfa36a6234"
      ],
      "parents": [
        -1,
        0,
        1,
        2
      ],
      "channels": [
        [
          "g_2bb88abb-a07b-4cca-add4-670b5ca2ae58"
        ],
        [
          "g_2bb88abb-a07b-4cca-add4-670b5ca2ae58"
        ],
        [
          "g_2bb88abb-a07b-4cca-add4-670b5ca2ae58"
        ],
        [
          "g_2bb88abb-a07b-4cca-add4-670b5ca2ae58"
        ]
      ]
    },
    "channels": {
      "g_2bb88abb-a07b-4cca-add4-670b5ca2ae58": null
    },
    "access": {
      "b384a792-743e-4866-92d0-d491bea5010a": {
        "dm_b384a792-743e-4866-92d0-d491bea5010a_eb40057f-6c48-433a-9abc-9a5334742b10": 45506,
        "g_2bb88abb-a07b-4cca-add4-670b5ca2ae58": 45506
      },
      "eb40057f-6c48-433a-9abc-9a5334742b10": {
        "dm_b384a792-743e-4866-92d0-d491bea5010a_eb40057f-6c48-433a-9abc-9a5334742b10": 45506,
        "g_2bb88abb-a07b-4cca-add4-670b5ca2ae58": 41322
      }
    },
    "time_saved": "2015-07-14T18:57:20.359147684Z"
  },
  "brand": "Workbase",
  "createdAt": "2015-07-03T01:08:07Z",
  "createdBy": "eb40057f-6c48-433a-9abc-9a5334742b10",
  "name": "Test",
  "type": "Group",
  "updatedAt": "2015-07-09T23:14:28Z",
  "updatedBy": "b384a792-743e-4866-92d0-d491bea5010a",
  "userIds": [
    "eb40057f-6c48-433a-9abc-9a5334742b10",
    "b384a792-743e-4866-92d0-d491bea5010a"
  ]
}
```

Here's the first user, as they appear in Couchbase and then via Sync Gateway's Admin API. Looks good.

``` javascript
{
  "name": "eb40057f-6c48-433a-9abc-9a5334742b10",
  "all_channels": {
    "!": 1,
    "dm_b384a792-743e-4866-92d0-d491bea5010a_eb40057f-6c48-433a-9abc-9a5334742b10": 45506,
    "g_2bb88abb-a07b-4cca-add4-670b5ca2ae58": 41322
  },
  "sequence": 41321,
  "email": "works@example.com",
  "passwordhash_bcrypt": "...",
  "rolesSince": {}
}

{
  "name": "eb40057f-6c48-433a-9abc-9a5334742b10",
  "all_channels": ["!", "dm_b384a792-743e-4866-92d0-d491bea5010a_eb40057f-6c48-433a-9abc-9a5334742b10", "g_2bb88abb-a07b-4cca-add4-670b5ca2ae58"],
  "email": "works@example.com"
}
```

Here's the second user in the group. Mysteriously, this user doesn't have access to either channel it should.

``` javascript
{
  "name": "b384a792-743e-4866-92d0-d491bea5010a",
  "all_channels": {
    "!": 1
  },
  "sequence": 45507,
  "email": "does_not_work@example.com",
  "passwordhash_bcrypt": "...",
  "rolesSince": {}
}

{
  "name": "b384a792-743e-4866-92d0-d491bea5010a",
  "all_channels": ["!"],
  "email": "does_not_work@example.com"
}
```

Does anyone have any ideas why the second user might not have channel access, or what steps I can take to try to track down the problem? I tried updating the Group document (didn't change any fields, just pushed a new, identical revision) and also tried restarting Sync Gateway. There were no errors in the logs when I updated the group doc.

Thanks very much for your help!

**Comment by tleyden** [comment]
Hey @mjq -- is this 100% reproducible?  Also it might be helpful if you could write up a step-by-step on how to repro, which could be hopefully translated into a test case of some sort.

Also, which version of SG?

**Comment by mjq** [comment]
This issue is not, as far as I can tell, reproducible. There are plenty of other similar groups where all members have the correct channel access. So, I don't have any steps - all I know is, in this instance I'm in a broken state.

Would you (or anyone else) know where in code the user document's `all_channels` field is updated as a result of a documenting granting that user access? With that I can (hopefully) work backwards to where this particular case is failing. Thanks!

**Comment by adamcfraser** [comment]
The user doc's all_channels gets reset (to nil) [here](https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/crud.go#L684), and then recalculated the next time that user record gets loaded.

Looking at that code, it seems like there's an error that's ignored in the call to authr.InvalidateChannels() - so if there was an error on the Save() of the user record, you could end up in the state you're seeing.

**Comment by mjq** [comment]
Thanks for the lead. Resaving the user document using the Admin API fixed the issue -- that user now has access to all the expected channels.

Is there any way that the Save() error you mentioned could be handled better by Sync Gateway?

**Comment by adamcfraser** [comment]
I'd like to leave this ticket open to track whether we can improve that handling.  We can't do much about the scenario where SG fails/crashes between document update and user doc update, but I'd like to dig into whether there are other scenarios we should be handling (conflicting updates to the user doc, for example).

**Comment by zgramana** [comment]
@adamcfraser is going to add a logging fix, and he's adding a new ticket to track the bigger fix.

**Comment by adamcfraser** [comment]
Logged https://github.com/couchbase/sync_gateway/issues/1018 for the more general fix.
