### ISSUE TITLE
SG 1.1.0 missing feature

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#987]
The release not for SG 1.1.0 states that the following bug fix is included:
#783 Windows line breaks in sync function cause SG to fail

But the commit from 15th May is not in the release/1.1.0 branch so is missing fromthe binary builds.

Other fixes in the release note may also be missing

**Comment by tleyden** [comment]
I just noticed this too.  I will make sure it gets into 1.1.1

**Comment by JeffThomasWriter** [comment]
I have not been handling the Release Notes.

**Comment by adamcfraser** [comment]
Been reviewed for 1.1.1.
