### ISSUE TITLE
SG Admin console JS errors

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#989]
When launching the SG admin console against an SG database, the console sends a _changes request to the DB.

In a browse JS console, there are errors parsing the _changes feed and document count on the initial admin screen is not incremented.

**Comment by ajres** [comment]
[Error] TypeError: undefined is not an object (evaluating 'sync.changed')
    onChangeWDoc (_admin, line 579)
    onChange (_admin, line 579)
    forEach ([native code], line 0)
    (anonymous function) (_admin, line 579)
    (anonymous function) (_admin, line 578)
    on_end (_admin, line 578)
    on_state_change (_admin, line 578)

**Comment by adamcfraser** [comment]
Should get covered in the migration to the new Admin UI in 2.0.
