### ISSUE TITLE
Cannot retrieve documents when user is authenticated

### ISSUE THREAD

**Issue by sscarduzio** [couchbase/sync_gateway#990]
Hi guys,

Not sure this is a bug, but we're stuck on this: we have correctly implemented the external auth (logs show the "(as <username>) when we send HTTP requests, we're able to create a new document:

```
2015-07-15T15:31:38.246Z HTTP:  #2995: PUT /soya_sync/MyFancyDoc  (as xxx@yyy.com)
```

Then I change the request to be a GET, and I see:

```
2015-07-15T15:34:56.531Z HTTP:  #4747: GET /soya_sync/MyFancyDoc  (as xxx@yyy.com)
2015-07-15T15:34:56.532Z HTTP: #4747:     --> 403 forbidden  (1.8 ms)
```

We didn't specify a sync function yet. Our configuration is really generic:

```
cat couchbase-sync-gateway.conf
{
  "CORS":{
    "Origin":["http://127.0.0.1:8080", "http://127.0.0.1:80", "http://159.220.39.173:80"],
    "Headers":["If-Modified-Since", "Cache-Control", "Content-Type"],
    "MaxAge": 1728000
  }
,
  "log": ["CRUD+", "REST+", "Changes+", "Attach+"],
  "adminInterface": ":4985",
  "databases":
  {
    "soya_sync": {
      "server": "http://XXXXXX:8091",
      "users":{
        "GUEST": {"disabled": false, "admin_channels":["*"]}

      }
    }
  }
}
```
The iOS guys with their SDK have the same problem: when you're authenticated, you can't retrieve the documents. Everything works well if you are a Guest (no auth).
```

**Comment by adamcfraser** [comment]
It sounds like user xxx@yyy.com just hasn't been granted read access to that document.  Read access is typically managed using channels.  Since you don't have any channels set up yet (no sync function), you'd need to grant the user access to the `*` channel in order to see any documents.

**Comment by sscarduzio** [comment]
Thanks Adam, I kinda understood the concept. However, can I print some log lines from the sync function?

This is how the sync function looks like now (not sure about the user var, that's why I need some logs)
Our user profile documents are named as `user-xxx@yyy.com`, hence the regexp.

```
    "sync": `
        function(doc, oldDoc){
          var user = oldDoc == null ? doc._id.replace(/^user-/, '') : oldDoc._id.replace(/^user-/, '');
          access(user, "*");
        }
    `
```

**Comment by adamcfraser** [comment]
I believe you can use console.log() in the Sync Function to write to the Sync Gateway console.

Since this isn't an actual bug/issue, the right place for this discussion would be the forums:
https://forums.couchbase.com/c/mobile/sync-gateway.  If you've got any followup questions, please raise them there.  Thanks!

**Comment by sscarduzio** [comment]
Adam,

Your forum thinks I'm a spammer and I cannot create an account. I reported the issue, but in the meanwhile I respond here.

In the sync function, `console.log("hello world")`  does not produce any extra log line in the sync gateway stdout. 
I don't know how you guys manage to debug complex sync functions without logging, but seems pretty useful feature. I'm surprised nobody brought this up before. Maybe you can share what's your workflow?

I mean, there's still the option to mock the built in functions and test stuff in the browser, but.. Why? :)

**Comment by adamcfraser** [comment]
I'm still trying to sort out why console.log wouldn't be working for you.  Can you try a simple `log("hello world")`, and see if that gets triggered on a document update?
