### ISSUE TITLE
Facebook REST API docs issue

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#996]
Copied over from [this](https://forums.couchbase.com/t/facebook-documentation-typo/4584)  forum thread:

dbergan dbergan 
July 22
The [rest api information here for facebook_token](http://developer.couchbase.com/mobile/develop/references/sync-gateway/rest-api/authentication/post-facebook/index.html) doesn't work.

It states that we should use

POST /_facebook_token
...which returns a not-found (404).

The correct way to access this function is described [here](http://developer.couchbase.com/mobile/develop/guides/sync-gateway/administering-sync-gateway/authenticating-users/index.html#facebook) in the Authenticating Users guide.

POST /{dbname}/_facebook

**Comment by tleyden** [comment]
@ajres just to confirm - this is a docs issue?

**Comment by ajres** [comment]
The _facebook endpoint is off each DB, and the Authenticating User guide docs are correct, the REST API information documentation is incorrect.

It looks like a documentation issue.
