### ISSUE TITLE
Can we have _facebook validate the token for a given FacebookAppID?

### ISSUE THREAD

**Issue by dbergan** [couchbase/sync_gateway#997]
Slap me if I'm doing this wrong...

The "issue" is that it appears that POST /{dbname}/_facebook  (on the sync gateway public REST API) takes a facebook access_token in the payload, but it doesn't matter what app the access_token comes from.  Villian could get an access token from any facebook app and use it to login to my couchbase.  Thus, using _facebook is essentially the same as enabling the guest user, afaik.

I think the easiest solution would be to specify my FacebookAppID(s) in the sync_gateway config file, like so:

```
{
    "adminInterface": ":4985",
    "interface": ":4984",
    "facebook" : {
        "register" : true,
        "appid": ["1234567890", "9876543210"]
    },
    ...
}
```

Now when someone uses /{dbname}/_facebook sync-gateway can grab the appID of the token submitted and match it to the ones given in the config file... or send them an "unauthorized" response.

~~Alternative could be to allow the FacebookAppID be included in the payload of the request itself.~~
~~curl http://my.server.ip.address:4984/{dbname}/_facebook -H "Content-Type: application/json" -vX POST~~
~~{ "access_token": "CAAULMWm0eXYBAFDo4ZBSIWEl0sha5Vx4srQy6HA88ym4NOx56oyG3fE7ehi6jlo71U4msh1ejwcRToScUziBSwkN2JDlfl8dsZAPVzexnZB5I03cH81NTsxgAXKmKzX9q9sgb8bZBaUDxzfMl5b2mqFNJzg8Tdg84nJBMqDXBzKzXCRDoMGVzToOE8hgp62GoY0E94BPOPx2H0UJwNYZBbAvVv6mJPZBAZD", "appid": "1234567890" }~~

[edit: On second thought, this method will not work.  I don't want it to validate unless it's **my** FacebookAppID **and** their token matches it.]

Here's my long-winded post from yesterday:
https://forums.couchbase.com/t/facebook-logins-via-gateways-rest-api/4585

Kind regards,
David

**Comment by adamcfraser** [comment]
I think the right way to apply app-striping to authentication for Facebook auth would be to use the `appsecret_proof` approach described here:
https://developers.facebook.com/docs/graph-api/securing-requests 

I think this is a valid enhancement - we'll review for inclusion.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if this approach is requested.
