### ISSUE TITLE
CORS and POST _facebook

### ISSUE THREAD

**Issue by dbergan** [couchbase/sync_gateway#998]
This should be a quick fix...

I had my sync gateway config file set up like this:

```
{
    "adminInterface": ":4985",
    "interface": ":4984",
    "facebook" : {
        "register" : true
    },
    "CORS": {
        "Origin": ["http://mydomain.com/"],
        "LoginOrigin": ["http://mydomain.com/"],
        "Headers": ["Content-Type"],
        "MaxAge": 1728000
     },

...
}
```

And I could not make a connection.  The error response was not helpful.

`400 No CORS`

Sync Gateway console says the same thing.  But I have CORS set up...

Turns out that the back-slash at the end of mydomain.com/ was the problem.  This works fine:

```
{
    "adminInterface": ":4985",
    "interface": ":4984",
    "facebook" : {
        "register" : true
    },
    "CORS": {
        "Origin": ["http://mydomain.com"],
        "LoginOrigin": ["http://mydomain.com"],
        "Headers": ["Content-Type"],
        "MaxAge": 1728000
     },

...
}
```

Solutions
1) have sync-gateway automatically remove a trailing back-slash
or
2) have the error response say something a little more clear than "No CORS"
or
3) at least mention the trailing backslash in the [documentation](http://developer.couchbase.com/mobile/develop/guides/sync-gateway/administering-sync-gateway/command-line-tool/index.html)

While we're talking about the documentation, the link at the bottom of the CORS section is dead.

**Comment by adamcfraser** [comment]
Closing based on age, can reopen in JIRA if there's a compelling use case.
