### ISSUE TITLE
Omitting password works even if allow_empty_passwords set to false

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#999]
To reproduce:
- Sync Gateway config with `allow_empty_passwords` omitted or set to false
- Via SG Admin REST api, create a user but do not add a password field to the JSON request

**Expected**: Sync Gateway should not allow the user to be created
**Actual**: Sync Gateway allows the user to be created

**Comment by pasin** [comment]
I have seen the same issue. It seems like the issue happens only when creating a new user but not updating.

**Comment by adamcfraser** [comment]
Moved to https://issues.couchbase.com/browse/CBG-646
